### ISSUE TITLE
Updating aws_lambda_function resource causes crash when updating to Terraform 0.7.12 from 0.7.10

### ISSUE THREAD

**Issue by deverton** [hashicorp/terraform#10302]
Running ``terraform plan`` after updating to 0.7.12 from 0.7.10 I get the below crash trace. It appears that updating the ``aws_lambda_function`` resources is failing. Possibly because the environment value doesn't exist in the old Terraform?

```
08:47:30 panic: runtime error: invalid memory address or nil pointer dereference
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8a9668]
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: 
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: goroutine 1389 [running]:
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: panic(0x2d48a20, 0xc4200160a0)
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/panic.go:500 +0x1a1
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsLambdaFunctionRead(0xc420d42720, 0x29c5920, 0xc420686340, 0x0, 0x13)
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_lambda_function.go:336 +0x7a8
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc4209cbaa0, 0xc420ba20f0, 0x29c5920, 0xc420686340, 0xc4206dc618, 0x1, 0x18)
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:259 +0x131
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc420a1b8c0, 0xc420ba20a0, 0xc420ba20f0, 0x0, 0xc421002488, 0x436e90)
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:203 +0x91
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc420867aa0, 0xc421002540, 0xc421002920, 0x0, 0x0)
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:482 +0x4e
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: reflect.Value.call(0xc420468660, 0xc42002e248, 0x13, 0x336518e, 0x4, 0xc420397ee0, 0x3, 0x3, 0x3, 0xc4202cf5a0, ...)
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:434 +0x5c8
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: reflect.Value.Call(0xc420468660, 0xc42002e248, 0x13, 0xc420397ee0, 0x3, 0x3, 0xf6c94f, 0xc42032bf80, 0xeb2020)
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:302 +0xa4
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc420105180, 0xc420105140, 0xc4202cefa0, 0xc420086e80, 0xc42046e7c0, 0x29c7b60, 0xc421002540, 0x16, 0x29c7ba0, 0xc421002920, ...)
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:383 +0x148
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
08:47:30 2016/11/22 22:47:30 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:477 +0x421
```

**Comment by deverton** [comment]
I've submitted a PR to fix this. See PR #10306
