### ISSUE TITLE
Terraform destroy crashing using vsphere

### ISSUE THREAD

**Issue by davey-dev** [hashicorp/terraform#10365]
My workflow is terraform apply, run ansible playbooks and then terraform destroy.

My destroy only crashes if I run Ansible on the vsphere hosts.
```
+ terraform destroy -force -var vsphere_user=**** -var vsphere_password=****
vsphere_virtual_machine.rabbit: Refreshing state... (ID: TF-RABBIT)
vsphere_virtual_machine.cape: Refreshing state... (ID: TF-CAPE)
vsphere_virtual_machine.mongo: Refreshing state... (ID: TF-MONGO)
vsphere_virtual_machine.soc: Refreshing state... (ID: TF-SOC)
vsphere_virtual_machine.kafka: Refreshing state... (ID: TF-KAFKA)
vsphere_virtual_machine.api: Refreshing state... (ID: TF-API)
Error refreshing state: 1 error(s) occurred:

* vsphere_virtual_machine.api: unexpected EOF
panic: runtime error: index out of range
2016/11/25 10:50:13 [DEBUG] plugin: terraform: 
2016/11/25 10:50:13 [DEBUG] plugin: terraform: goroutine 29 [running]:
2016/11/25 10:50:13 [DEBUG] plugin: terraform: panic(0x2d49a80, 0xc4200120d0)
2016/11/25 10:50:13 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/panic.go:500 +0x1a1
2016/11/25 10:50:13 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/vsphere.resourceVSphereVirtualMachineRead(0xc4204a0660, 0x32e6a60, 0xc42046c100, 0x1, 0x17)
2016/11/25 10:50:13 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/vsphere/resource_vsphere_virtual_machine.go:1066 +0x3458
2016/11/25 10:50:13 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc42038e7e0, 0xc4201b8960, 0x32e6a60, 0xc42046c100, 0xc4203ab1b0, 0x1, 0x18)
2016/11/25 10:50:13 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:259 +0x131
2016/11/25 10:50:13 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc420408060, 0xc4201b8910, 0xc4201b8960, 0xc4203b0ea0, 0x419de6, 
```0xc420045a68)

**Comment by ashkan3** [comment]
Any updates on this thread? We're experiencing the same issue and it's very annoying. We have delivery pipeline that reconstructs our cluster. But every time that we want to build our pipeline it fails at the first step because of this issue.

**Comment by ashkan3** [comment]
Just an update. This time after terraform crashed when trying to destroy the cluster, instead of deleting VMs from vSphere UI, I tried restarting VMs and then terraform was able to destroy the cluster successfully.

**Comment by bamb00** [comment]
@ashkan3 That did not work for me restarting the VMs and still getting the crashed.
