### ISSUE TITLE
Terraform v0.8.4 crashes consistently.

### ISSUE THREAD

**Issue by beanaroo** [hashicorp/terraform#11227]
### Terraform Version
```
Terraform v0.8.4
````

### Affected Resource(s)
- core

### Terraform Configuration Files
Crash happens in any configuration. Attached logs relate to reproduction of example usage of [tf_aws_vpc community module](https://github.com/terraform-community-modules/tf_aws_vpc#usage).

### Debug Output
Crash.log and crash banner only happens 1/5 times. Most of the time terraform just exits silently (with non-zero status). Trace debug output: 
https://gist.github.com/beanaroo/7eb699b9f62467732c144296723ce39c

### Panic Output
https://gist.github.com/beanaroo/32e38eded061252576f3be62e6ab5fcb

### Expected Behavior
Not crashing...

### Actual Behavior
Running `plan` or `apply` or `refresh` exits silently with error return status. Now and then it will produce crash output. Twice it asked for variable input of defined variables...

### Important Factoids
Terraform 0.8.2 worked wonderfully. Not running anything elaborate. Very basic setups.

### References
none yet

**Comment by beanaroo** [comment]
Tried rebuilding from source.
```
runtime: nelems=73 nfree=54 nalloc=19 previous allocCount=14 nfreed=65531
fatal error: sweep increased allocation count

runtime stack:
runtime.throw(0x856aef, 0x20)
        /usr/lib/go/src/runtime/panic.go:566 +0x95
runtime.(*mspan).sweep(0x7f66b8d29120, 0x900000000, 0xc400000001)
        /usr/lib/go/src/runtime/mgcsweep.go:287 +0x7ab
runtime.sweepone(0x4a8a06)
        /usr/lib/go/src/runtime/mgcsweep.go:112 +0xfe
runtime.gosweepone.func1()
        /usr/lib/go/src/runtime/mgcsweep.go:124 +0x2b
runtime.systemstack(0xc420069220)
        /usr/lib/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
        /usr/lib/go/src/runtime/proc.go:1079

goroutine 3 [running]:
runtime.systemstack_switch()
        /usr/lib/go/src/runtime/asm_amd64.s:252 fp=0xc42002cf48 sp=0xc42002cf40
runtime.gosweepone(0x0)
        /usr/lib/go/src/runtime/mgcsweep.go:125 +0x4a fp=0xc42002cf78 sp=0xc42002cf48
runtime.bgsweep(0xc42005c000)
        /usr/lib/go/src/runtime/mgcsweep.go:66 +0xbb fp=0xc42002cfb8 sp=0xc42002cf78
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42002cfc0 sp=0xc42002cfb8
created by runtime.gcenable
        /usr/lib/go/src/runtime/mgc.go:195 +0x61

goroutine 1 [runnable]:
go/parser.(*parser).consumeCommentGroup(0xc4201fa000, 0x1, 0x0, 0x160)
        /usr/lib/go/src/go/parser/parser.go:296 +0x2a9
go/parser.(*parser).next(0xc4201fa000)
        /usr/lib/go/src/go/parser/parser.go:340 +0x106
go/parser.(*parser).init(0xc4201fa000, 0xc4202e6a40, 0xc4203440f0, 0x27, 0xc420066800, 0x240, 0x400, 0x6)
        /usr/lib/go/src/go/parser/parser.go:85 +0x149
go/parser.ParseFile(0xc4202e6a40, 0xc4203440f0, 0x27, 0x7bd6a0, 0xc420138060, 0x6, 0x0, 0x0, 0x0)
        /usr/lib/go/src/go/parser/interface.go:120 +0x1d3
go/build.(*Context).Import(0xa2ea40, 0xc4204d04b1, 0xd, 0xc420240d20, 0x43, 0x4, 0xc42036b601, 0xc42048cea0, 0x47fc01)
        /usr/lib/go/src/go/build/build.go:739 +0xcac
main.loadImport(0xc4204d04b1, 0xd, 0xc420240d20, 0x43, 0xc42036a480, 0xc42048d9f8, 0xc42029a1e0, 0x1, 0x1, 0x1, ...)
        /usr/lib/go/src/cmd/go/pkg.go:365 +0x3b9
main.(*Package).load(0xc42036a480, 0xc42048d9f8, 0xc420110380, 0x0, 0x0, 0xc)
        /usr/lib/go/src/cmd/go/pkg.go:940 +0x12b6
main.loadImport(0x7ffd8ce1f400, 0x18, 0xc4200180a4, 0x49, 0x0, 0xc42048d9f8, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/cmd/go/pkg.go:374 +0x470
main.loadPackage(0x7ffd8ce1f400, 0x18, 0xc42048d9f8, 0x0)
        /usr/lib/go/src/cmd/go/pkg.go:1658 +0x28f
main.packagesAndErrors(0xc4204d01c0, 0x1, 0x1, 0x7ffd8ce1f400, 0x18, 0x848bad)
        /usr/lib/go/src/cmd/go/pkg.go:1703 +0x337
main.packagesForBuild(0xc4204d01a0, 0x1, 0x1, 0xc4204d01a0, 0x1, 0x1)
        /usr/lib/go/src/cmd/go/pkg.go:1719 +0x75
main.runGet(0xa27900, 0xc4204d01a0, 0x1, 0x1)
        /usr/lib/go/src/cmd/go/get.go:130 +0x320
main.main()
        /usr/lib/go/src/cmd/go/main.go:181 +0x624

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x41
```

So possibly golang related?

**Comment by beanaroo** [comment]
Reran build under a different kernel (linux-ck instead of linux-pf) and everything looks to be functioning.

I will close this as it does not seem to be terraform specific.
