### ISSUE TITLE
terraform linux_arm builds unusable (versions >= 0.8.0)

### ISSUE THREAD

**Issue by asobrien** [hashicorp/terraform#11507]
The latest `linux_arm` builds panic as soon as the `terraform` binary is executed.

I tested this both on an `armv7l` laptop (ARMv7 Cortex-A17) and on a Scaleway C1 instance. On both platforms terraform versions >= `v0.8.0` are unusable. 

I also tried building terraform from the repo directly on the platforms noted, using both `make dev` and invoking `go build` directly. While the builds of terraform >= 0.8.0 succeeded, the resulting binaries were unusable (I explicitly tested `v0.8.0` and `v0.8.5`), panicking when called. 

I tested `v0.7.9` (building from source) and `v0.7.1` (dowloaded from [hashicorp release archives](https://releases.hashicorp.com/terraform/0.7.1/)) and neither panicked when called, producing the expected usage message when no additional commands or options are passed.

### Terraform Version
linux_arm `v0.8.5` (versions >= `v0.8.0` panic when executed)

### Affected Resource(s)
Please list the resources as a list, for example:
- linux_arm binary: [terraform_0.8.5_linux_arm](https://releases.hashicorp.com/terraform/0.8.5/terraform_0.8.5_linux_arm.zip)

### Terraform Configuration Files
N/A

### Debug Output
None

### Panic Output
```
unexpected fault address 0x421f53c
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x421f53c pc=0x421f53c]

goroutine 1 [running, locked to thread]:
runtime.throw(0x3294009, 0x5)
/opt/go/src/runtime/panic.go:566 +0x78 fp=0x15037e84 sp=0x15037e78
runtime.sigpanic()
/opt/go/src/runtime/sigpanic_unix.go:27 +0x280 fp=0x15037eb0 sp=0x15037e84
crypto/des.init()
/opt/go/src/crypto/des/const.go:140 +0x4c fp=0x15037eb8 sp=0x15037eb4
crypto/tls.init()
/opt/go/src/crypto/tls/tls.go:298 +0x58 fp=0x15037ed8 sp=0x15037eb8
net/http.init()
/opt/go/src/net/http/transport.go:2172 +0x54 fp=0x15037f7c sp=0x15037ed8
github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-checkpoint.init()
/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-checkpoint/checkpoint.go:360 +0x68 fp=0x15037f80 sp=0x15037f7c
main.init()
/opt/gopath/src/github.com/hashicorp/terraform/version.go:10 +0x58 fp=0x15037f9c sp=0x15037f80
runtime.main()
/opt/go/src/runtime/proc.go:172 +0x224 fp=0x15037fc4 sp=0x15037f9c
runtime.goexit()
/opt/go/src/runtime/asm_arm.s:998 +0x4 fp=0x15037fc4 sp=0x15037fc4
```

### Expected Behavior
The expected behavior is to have usage printed to stdout, e.g.:

```
$ terraform
usage: terraform [--version] [--help] <command> [args]

The available commands for execution are listed below.
The most common, useful commands are shown first, followed by
less common or more advanced commands. If you're just getting
started with Terraform, stick with the common commands. For the
other commands, please read the help and docs before usage.

Common commands:
    apply              Builds or changes infrastructure
    destroy            Destroy Terraform-managed infrastructure
    fmt                Rewrites config files to canonical format
    get                Download and install modules for the configuration
    graph              Create a visual graph of Terraform resources
    import             Import existing infrastructure into Terraform
    init               Initializes Terraform configuration from a module
    output             Read an output from a state file
    plan               Generate and show an execution plan
    push               Upload this Terraform module to Atlas to run
    refresh            Update local state file against real resources
    remote             Configure remote state storage
    show               Inspect Terraform state or plan
    taint              Manually mark a resource for recreation
    untaint            Manually unmark a resource as tainted
    validate           Validates the Terraform files
    version            Prints the Terraform version

All other commands:
    state              Advanced state management
```

### Actual Behavior
When the `v0.8.5` binary is executed on `armv7l` platforms it panics (see panic output above).

### Steps to Reproduce
Initially I noticed this on a laptop with an ARMv7 Cortex-A1`. I was able to reproduce this on a [Scaleway C1 instance](https://www.scaleway.com/faq/server/) (Ubuntu 14.0):

1. On an `armv7l` platform install terraform from official release page: https://releases.hashicorp.com/terraform/0.8.5/terraform_0.8.5_linux_arm.zip
1. Extract: `unzip terraform_0.8.5_linux_arm.zip`
1. Run the binary: `./terraform` or `./terraform --version`

### Important Factoids
Running versions <= `0.7.9` does not panic. Versions >= `0.8.0` (tested), including the latest release (`v0.8.5`) and `master`, panic when the binary is called. I compiled terraform from the repo directly on an `armv7l` platform and the same error is encountered. I used both `gox` via `make dev` and invoked `go build` directly to build a binary: both methods compile successfully on the native platform, however the binary panics when executed.

### References
- [Scaleway C1 Instance](https://www.scaleway.com/faq/server/)
- [Go ARM support](https://github.com/golang/go/wiki/GoArm)

**Comment by mitchellh** [comment]
This error is coming directly from the Go source itself. :(

It is unlikely that this is a Terraform-specific issue, but if there is a way for us to fix this we'd welcome any contribution to do so. We provide linux arm builds as a convenience that Go provides but we unfortunately do not run any tests on that platform itself and isn't a priority for us at the moment as core maintainers. However, like I said, if a community member wants to come through and improve this we'd be thrilled and thankful. 

This error in particular has no immediate actionable thing that we can do as a project other than to debug Go itself. 😭  

I'll try to take a look but if there is no obvious fix I'm going to defer this upstream.

**Comment by jbardin** [comment]
Go @asobrien,

What version of Go were you building with? Could you try with the latest go1.8rc? Though gox doesn't set `GOARM` at all, it doesn't look like an arm version issue which usually results in a bad cpu instruction.

Do either the arm systems have swap enabled? Since this is an odd panic happening during runtime main_init(), I wonder if it's an out of memory condition that's being masked by the panic.

**Comment by asobrien** [comment]
@jbardin I've been building with `go version go1.7 linux/arm`. I went with this since the 0.7 builds of terraform were built against this and they were building sucessfully. I tried building terraform v0.8.5 with `go1.7.5` and `go1.8rc3`, both failed as I recall. I will try building against go1.8 again to confirm.

Neither system had swap enabled. I enabled a 5 GB swapfile on the Scaleway C1, and the binary still panics (built with go1.7). I also rebuilt the binary with swap and still saw a panic.

I ran a git bisect between `v0.8.0` and `v0.7.9` (`make dev` building with `go1.7` looking for a successful exit code when calling `terraform --version` on the resulting binary) to see if I could get any more information. The unstable ARM builds look like they started with commit [bb5f64](https://github.com/hashicorp/terraform/commit/bb5f64) which went in with PR #9538. I'm not saying that's the smoking gun and I haven't been able to find any root cause. The bisect log is below:

```
# bad: [142dd256ad48ab17b6019fe9cd18712167fcf4b4] v0.8.0
# good: [b313e55fe78704bba47d51d42a0a65cff4cf8063] v0.7.9
git bisect start 'v0.8.0' 'v0.7.9' '--'
# bad: [594014d4f65f61c1399fc337e5fc2211b5a28474] Update CHANGELOG.md
git bisect bad 594014d4f65f61c1399fc337e5fc2211b5a28474
# bad: [e7411891f4266fc374b7ca28250d0484f1886091] Update CHANGELOG.md
git bisect bad e7411891f4266fc374b7ca28250d0484f1886091
# good: [a23c5bda729c4c89318cbf5586b76c93d0b2f40a] provider/azurerm: move ConfigureFunc outside of Provider literal, fixes nil reference
git bisect good a23c5bda729c4c89318cbf5586b76c93d0b2f40a
# good: [695bd6d2c894513d78b1896a265c46939fdc68df] update CHANGELOG
git bisect good 695bd6d2c894513d78b1896a265c46939fdc68df
# bad: [4996f3e289a8c821070070f5270415bc19bbba01] provider/azurerm: allow updating load balancer sub-resources (#10016)
git bisect bad 4996f3e289a8c821070070f5270415bc19bbba01
# bad: [e8fa75376c902a3c678ec9efaa2390de48443778] Merge #10008: atlas_artifact data source example
git bisect bad e8fa75376c902a3c678ec9efaa2390de48443778
# bad: [58412762eb870811a2c0b8abe409320b62cd792b] Merge branch 'master' of https://github.com/freeman/terraform into freeman-master
git bisect bad 58412762eb870811a2c0b8abe409320b62cd792b
# bad: [fd498fbfff150bde5ca2b951d98aaa23cbd2ab10] Merge pull request #9538 from hashicorp/f-nomad-provider
git bisect bad fd498fbfff150bde5ca2b951d98aaa23cbd2ab10
# bad: [bb5f6498e2d61dd6444cd91a9617ba5aecce9e4f] provider/nomad
git bisect bad bb5f6498e2d61dd6444cd91a9617ba5aecce9e4f
# good: [8af241e501ec24e32396f54006608aefba975d08] vendor: Nomad
git bisect good 8af241e501ec24e32396f54006608aefba975d08
# first bad commit: [bb5f6498e2d61dd6444cd91a9617ba5aecce9e4f] provider/nomad
```

**Comment by mitchellh** [comment]
Just making a note: Based on that bisect its possible this was caused by new imports brought in from the Nomad provider.

**Comment by abitrolly** [comment]
Does that still happen with https://releases.hashicorp.com/terraform/0.10.7/ ?

**Comment by asobrien** [comment]
I don't see the same error executing the [binary](https://releases.hashicorp.com/terraform/0.10.7/terraform_0.10.7_linux_arm.zip) (e.g., `terraform` or `terraform version`) with the 0.10.7 release. I haven't tried running any states with the latest binary but the error in the 0.8 release manifested whenever the binary was called, for instance a `terraform version` call would fail.

I'll run a bisect again to see when what ARM builds are unstable but it seems that this error is no longer present with the latest builds.

**Comment by asobrien** [comment]
I tested the pre-built binaries from 0.7.9 to 0.10.7 (latest) on a `armv7l GNU/Linux` box and got the following results. The errors with ARM builds is isolated to versions `v0.8.0` to `v0.8.7`.

| version   | executable? |
| --------- | ------      |
| 0.7.9     | YES         |
| 0.8.0     | NO          |
| 0.8.1     | NO          |
| 0.8.2     | NO          |
| 0.8.3     | NO          |
| 0.8.4     | NO          |
| 0.8.5     | NO          |
| 0.8.6     | NO          |
| 0.8.7     | NO          |
| 0.8.8     | YES         |
| 0.9.0     | YES         |
| 0.9.1     | YES         |
| 0.9.2     | YES         |
| 0.9.3     | YES         |
| 0.9.4     | YES         |
| 0.9.5     | YES         |
| 0.9.6     | YES         |
| 0.9.7     | YES         |
| 0.9.8     | YES         |
| 0.9.9     | YES         |
| 0.9.10    | YES         |
| 0.9.11    | YES         |
| 0.10.0    | YES         |
| 0.10.1    | YES         |
| 0.10.2    | YES         |
| 0.10.3    | YES         |
| 0.10.4    | YES         |
| 0.10.5    | YES         |
| 0.10.6    | YES         |
| 0.10.7    | YES         |

Binary source: `https://releases.hashicorp.com/terraform/${version}/terraform_${version}_linux_arm.zip`

**Comment by tomkerswill** [comment]
I see the same issue (arm pre-built binaries immediately segfault) with 0.11.13. Tested on Scaleway c1, as per OP's post.
