### ISSUE TITLE
core: plan after import is issuing since introduction of new backends

### ISSUE THREAD

**Issue by Ninir** [hashicorp/terraform#11504]
Hi there,

I encountered an issue while working on 0.8.6-dev to add new resources. While checking the import, I encountered crashes while trying to plan post-import.

### Terraform Version
0.8.6-dev

### Affected Resource(s)
Please list the resources as a list, for example:
- all as far as I checked

### Terraform Configuration Files
N/A since importing.

### Debug Output
Import was successfully ran:

```
$ $GOPATH/bin/terraform import aws_sns_topic.foo arn:aws:sns:eu-west-1:512425551441:test
aws_sns_topic.foo: Importing from ID "arn:aws:sns:eu-west-1:512425551441:test"...
aws_sns_topic.foo: Import complete!
  Imported aws_sns_topic (ID: arn:aws:sns:eu-west-1:512425551441:test)
aws_sns_topic.foo: Refreshing state... (ID: arn:aws:sns:eu-west-1:512425551441:test)

Import success! The resources imported are shown above. These are
now in your Terraform state. Import does not currently generate
configuration, so you must do this next. If you do not create configuration
for the above resources, then the next `terraform plan` will mark
them for destruction.
```

A .tfstate file was generated too.

### Panic Output
```
 2017/01/29 23:23:01 [INFO] Terraform version: 0.8.6 dev ee1b51754ba0ad37145307aca9daec7f89491e5d+CHANGES
 2017/01/29 23:23:01 [INFO] CLI args: []string{"/Users/ninir/Sites/golang/bin/terraform", "plan"}
 2017/01/29 23:23:01 [DEBUG] Detected home directory from env var: /Users/ninir
 2017/01/29 23:23:01 [DEBUG] Detected home directory from env var: /Users/ninir
 2017/01/29 23:23:01 [DEBUG] Attempting to open CLI config file: /Users/ninir/.terraformrc
 2017/01/29 23:23:01 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
 2017/01/29 23:23:01 [DEBUG] Detected home directory from env var: /Users/ninir
 2017/01/29 23:23:01 [DEBUG] command: loading backend config file: /Users/ninir/Sites/terraform-tests/step_functions/test-fixtures
 2017/01/29 23:23:01 [INFO] command: backend config not found, returning nil: /Users/ninir/Sites/terraform-tests/step_functions/test-fixtures
 2017/01/29 23:23:01 [DEBUG] command: no data state file found for backend config
 2017/01/29 23:23:01 [DEBUG] New state was assigned lineage "4b4624d6-7d17-4f66-9ecc-55239d644717"
 2017/01/29 23:23:01 [INFO] command: backend initialized: <nil>
 2017/01/29 23:23:01 [INFO] command: backend <nil> is not enhanced, wrapping in local
 2017/01/29 23:23:01 [INFO] backend/local: starting Plan operation
 2017/01/29 23:23:01 [TRACE] Preserving existing state lineage "2b604720-0f47-48e0-a9a2-b6b106a7b97f"
 2017/01/29 23:23:01 [TRACE] Preserving existing state lineage "2b604720-0f47-48e0-a9a2-b6b106a7b97f"
 2017/01/29 23:23:01 [TRACE] Preserving existing state lineage "2b604720-0f47-48e0-a9a2-b6b106a7b97f"
 2017/01/29 23:23:01 [TRACE] Preserving existing state lineage "2b604720-0f47-48e0-a9a2-b6b106a7b97f"
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xeeb69]
 
 goroutine 22 [running]:
 panic(0x316ca20, 0xc42000e090)
     /usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
 github.com/hashicorp/terraform/terraform.(*Context).Input(0xc4204003c0, 0xc420400307, 0x0, 0x0)
     /Users/ninir/Sites/golang/src/github.com/hashicorp/terraform/terraform/context.go:329 +0xf9
 github.com/hashicorp/terraform/backend/local.(*Local).context(0xc4203ecab0, 0xc4203ecb40, 0x2, 0x2, 0x3, 0xc4203f0740, 0x2)
     /Users/ninir/Sites/golang/src/github.com/hashicorp/terraform/backend/local/backend_local.go:68 +0x3d6
 github.com/hashicorp/terraform/backend/local.(*Local).opPlan(0xc4203ecab0, 0x57e1360, 0xc42000e4d0, 0xc4203ecb40, 0xc4203017a0)
     /Users/ninir/Sites/golang/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:41 +0x217
 github.com/hashicorp/terraform/backend/local.(*Local).(github.com/hashicorp/terraform/backend/local.opPlan)-fm(0x57e1360, 0xc42000e4d0, 0xc4203ecb40, 0xc4203017a0)
     /Users/ninir/Sites/golang/src/github.com/hashicorp/terraform/backend/local/backend.go:140 +0x52
 github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc4203ecab0, 0xc4202dbf30, 0xc4202dbf20, 0x57e1360, 0xc42000e4d0, 0xc4203ecb40, 0xc4203017a0)
     /Users/ninir/Sites/golang/src/github.com/hashicorp/terraform/backend/local/backend.go:162 +0x98
 created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
     /Users/ninir/Sites/golang/src/github.com/hashicorp/terraform/backend/local/backend.go:163 +0x1aa
```
### Expected Behavior
Plan should have worked properly after importing

### Actual Behavior
Crash happened right after the import. The tfstate is still generated successfully with import.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Created a SNS topic (easy to create)
2. `terraform import` it
3. `terraform plan`
4. CRASH

### Important Factoids
N/A

**Comment by mitchellh** [comment]
Thanks for the catch! Looking into it.

**Comment by mitchellh** [comment]
Got a fix queued up in a PR. :)

**Comment by Ninir** [comment]
Awesome, thanks @mitchellh :)
