### ISSUE TITLE
panic when importing a new custom resource programmatically

### ISSUE THREAD

**Issue by Ninir** [hashicorp/terraform#11532]
Hi there,

While implementing AWS Step Functions resources in https://github.com/hashicorp/terraform/pull/11420, I encountered an issue while checking the correct import of the resource.

Looking at the panic debug lines, it does not seem to come from the new code, but I'm probably missing something there. Forgive me if so 😄 

I have also checked resources directly by using `make dev` with an appropriate configuration, and it works pretty nicely.

### Terraform Version
0.8.6-dev

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_sfn_state_machine (new one)

### Panic Output
```
$ TF_LOG=DEBUG TF_LOG_PATH=terraform.log make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSSfnStateMachine_importBasic'  
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/01/30 23:49:18 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSSfnStateMachine_importBasic -timeout 120m
=== RUN   TestAccAWSSfnStateMachine_importBasic
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x111cf92]

goroutine 1403 [running]:
panic(0x1815760, 0xc4200100e0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
github.com/hashicorp/terraform/terraform.(*NodeRefreshableDataResourceInstance).EvalTree(0xc42008b2d8, 0xc42008b2d8, 0x1165429)
	/Users/ninir/Sites/golang/src/github.com/hashicorp/terraform/terraform/node_data_refresh.go:134 +0x322
github.com/hashicorp/terraform/terraform.(*NodeRefreshableResource).EvalTree(0xc4205560d8, 0x1a97c00, 0xc4205560d8)
	/Users/ninir/Sites/golang/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:31 +0x79
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x1a97c00, 0xc4205560d8, 0x0, 0x0)
	/Users/ninir/Sites/golang/src/github.com/hashicorp/terraform/terraform/graph.go:232 +0xb90
github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk.func3(0xc4203da1a0, 0xc42050ee60, 0xc4203da1b0, 0xc4203ae360, 0xc4203da1c0, 0x1a97c00, 0xc4205560d8, 0xc420541620, 0xc420541980)
	/Users/ninir/Sites/golang/src/github.com/hashicorp/terraform/dag/dag.go:246 +0x251
created by github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk
	/Users/ninir/Sites/golang/src/github.com/hashicorp/terraform/dag/dag.go:255 +0x6a6
exit status 2
FAIL	github.com/hashicorp/terraform/builtin/providers/aws	26.141s
make: *** [testacc] Error 1
```

**Comment by mitchellh** [comment]
Ah we fixed this a couple days ago. Thanks though!
