### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by vrenjith** [hashicorp/terraform#11705]
`Terraform v0.8.5`
[crash.log.zip](https://github.com/hashicorp/terraform/files/752656/crash.log.zip)

**Comment by stack72** [comment]
relevant lines from the crash log

```
panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4f1139]
 
 goroutine 120 [running]:
 panic(0x316f4c0, 0xc420012090)
 	/opt/go/src/runtime/panic.go:500 +0x1a1
 github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsElbRead(0xc420484b40, 0x2d35400, 0xc4201f5a00, 0x0, 0x7)
 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_elb.go:391 +0xa59
 github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc4205f84e0, 0xc420010f50, 0x2d35400, 0xc4201f5a00, 0xc420081d88, 0x1, 0x18)
 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:259 +0x131
 github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc420427aa0, 0xc420010f00, 0xc420010f50, 0x0, 0xc29af7, 0xc42027ea80)
 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:237 +0x91
 github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc420206a80, 0xc420269080, 0xc420269430, 0x0, 0x0)
 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
 reflect.Value.call(0xc4204ae7e0, 0xc42002e060, 0x13, 0x389fa54, 0x4, 0xc42073ded0, 0x3, 0x3, 0xc420271000, 0xc420484960, ...)
 	/opt/go/src/reflect/value.go:434 +0x5c8
 reflect.Value.Call(0xc4204ae7e0, 0xc42002e060, 0x13, 0xc42073ded0, 0x3, 0x3, 0xcf64ef, 0xc4203b3ef0, 0xc4203b3f00)
 	/opt/go/src/reflect/value.go:302 +0xa4
 net/rpc.(*service).call(0xc420120380, 0xc420120340, 0xc420126eb0, 0xc42008a700, 0xc42015c2c0, 0x2d37a80, 0xc420269080, 0x16, 0x2d37ac0, 0xc420269430, ...)
 	/opt/go/src/net/rpc/server.go:383 +0x148
 created by net/rpc.(*Server).ServeCodec
 	/opt/go/src/net/rpc/server.go:477 +0x421
```
