### ISSUE TITLE
[BUG] [Google Cloud] - Terraform Crashes on terraform plan

### ISSUE THREAD

**Issue by zopanix** [hashicorp/terraform#11726]
Terraform creashes on plan. I didn't do anything in particular. Can't reproduce this on any other project of mine even with the same scenario

### Terraform Version
terraform 0.8.5

### Affected Resource(s)
This occured when I changed an unused `google_compute_instance_template` and removed the `access_config` block. But I don't think it is related to that particular resource. It might be an issue with terraform core. I tried reverting the changes and everything but it didn't work.

### Terraform Configuration Files
To be honest, The are a lot of them and I don't think this is relevant.

### Panic Output
* crash.log:
https://gist.github.com/zopanix/d09c0e553e1417bf836a769b92892c74
* statefile:
https://gist.github.com/zopanix/ca9eb3679643db9b1800ad05b68f6571

### Expected Behavior
Not to crash, if there is some error in my files, they should just be notified

### Actual Behavior
Panic Crash
```
-var-file=variables.tfvars ./standard
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

[0m[1mgoogle_compute_http_health_check.hck-rdpall: Refreshing state... (ID: hck-rdpall)[0m
[0m[1mgoogle_compute_address.eip-rdpall: Refreshing state... (ID: eip-rdpall)[0m
[0m[1mgoogle_compute_disk.pdbmst-data: Refreshing state... (ID: pdbmst-data)[0m
[0m[1mgoogle_compute_disk.smball-0-data: Refreshing state... (ID: smball-0-data)[0m
[0m[1mgoogle_compute_network.network: Refreshing state... (ID: network)[0m
[0m[1mgoogle_compute_health_check.hck-prgall: Refreshing state... (ID: hck-prgall)[0m
[0m[1mgoogle_compute_disk.madmst-data: Refreshing state... (ID: madmst-data)[0m
[0m[1mgoogle_compute_global_address.eip-pciall: Refreshing state... (ID: eip-pciall)[0m
[0m[1mgoogle_compute_http_health_check.hck-pciall: Refreshing state... (ID: hck-pciall)[0m
[0m[1mgoogle_compute_instance_template.tpl-ctlall-green: Refreshing state... (ID: tpl-ctlall-green)[0m
[0m[1mgoogle_compute_instance_template.tpl-ctlall-blue: Refreshing state... (ID: tpl-ctlall-blue)[0m
[0m[1mgoogle_compute_instance.rdpall-0: Refreshing state... (ID: rdpall-0)[0m
[0m[1mgoogle_compute_firewall.int-prg: Refreshing state... (ID: int-prg)[0m
[0m[1mgoogle_compute_firewall.hck-all: Refreshing state... (ID: hck-all)[0m
[0m[1mgoogle_compute_instance_template.tpl-pciall-green: Refreshing state... (ID: tpl-pciall-green)[0m
[0m[1mgoogle_compute_instance_template.tpl-prgall-green: Refreshing state... (ID: tpl-prgall-green)[0m
[0m[1mgoogle_compute_instance_template.tpl-pciall-blue: Refreshing state... (ID: tpl-pciall-blue)[0m
[0m[1mgoogle_compute_firewall.int-bst: Refreshing state... (ID: int-bst)[0m
[0m[1mgoogle_compute_firewall.ext-rdp: Refreshing state... (ID: ext-rdp)[0m
[0m[1mgoogle_compute_firewall.int-mad: Refreshing state... (ID: int-mad)[0m
[0m[1mgoogle_compute_instance.bstall: Refreshing state... (ID: bstall)[0m
[0m[1mgoogle_compute_firewall.fx-mad: Refreshing state... (ID: fx-mad)[0m
[0m[1mgoogle_compute_instance_template.tpl-prgall-blue: Refreshing state... (ID: tpl-prgall-blue)[0m
[0m[1mgoogle_compute_firewall.ext-pci: Refreshing state... (ID: ext-pci)[0m
[0m[1mgoogle_compute_firewall.int-pdb: Refreshing state... (ID: int-pdb)[0m
[0m[1mgoogle_compute_firewall.ext-bst: Refreshing state... (ID: ext-bst)[0m
[0m[1mgoogle_compute_target_pool.trp-rdpall: Refreshing state... (ID: trp-rdpall)[0m
[0m[1mgoogle_compute_instance.pdbmst: Refreshing state... (ID: pdbmst)[0m
[0m[1mgoogle_compute_instance.madmst: Refreshing state... (ID: madmst)[0m
[0m[1mgoogle_compute_instance.smball-0: Refreshing state... (ID: smball-0)[0m
[0m[1mgoogle_compute_instance_group_manager.igm-ctlall: Refreshing state... (ID: igm-ctlall)[0m
[0m[1mgoogle_compute_instance_group_manager.igm-pciall: Refreshing state... (ID: igm-pciall)[0m
[0m[1mgoogle_compute_route.rte-mad: Refreshing state... (ID: rte-mad)[0m
[0m[1mgoogle_compute_forwarding_rule.fwd-rdpall: Refreshing state... (ID: fwd-rdpall)[0m
[0m[1mgoogle_compute_instance_group_manager.igm-prgall: Refreshing state... (ID: igm-prgall)[0m
[0m[1mgoogle_compute_route.rte-pdb: Refreshing state... (ID: rte-pdb)[0m
[0m[1mgoogle_compute_region_backend_service.bes-prgall: Refreshing state... (ID: bes-prgall)[0m
[0m[1mgoogle_compute_backend_service.bes-pciall: Refreshing state... (ID: bes-pciall)[0m
[0m[1mgoogle_compute_forwarding_rule.fwd-prgall: Refreshing state... (ID: fwd-prgall)[0m
[0m[1mgoogle_compute_url_map.ump-pciall: Refreshing state... (ID: ump-pciall)[0m
[0m[1mgoogle_compute_target_http_proxy.tpx-pciall: Refreshing state... (ID: tpx-pciall)[0m
[0m[1mgoogle_compute_global_forwarding_rule.fwd-pciall: Refreshing state... (ID: fwd-pciall)[0m

panic: empty structure "service_account." has entry "service_account.0.email"

goroutine 20444 [running]:
panic(0x3276ea0, 0xc4206f3350)
	/opt/go/src/runtime/panic.go:500 +0x1a1
github.com/hashicorp/terraform/terraform.(*InstanceState).MergeDiff(0xc42051aa50, 0xc42079a4c0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/state.go:1689 +0x5df
github.com/hashicorp/terraform/terraform.(*EvalDiff).Eval(0xc4206aca00, 0x5be28c0, 0xc4200484e0, 0x2, 0x2, 0x3ca2388, 0x4)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_diff.go:176 +0x49a
github.com/hashicorp/terraform/terraform.EvalRaw(0x5bc0c60, 0xc4206aca00, 0x5be28c0, 0xc4200484e0, 0x39b5cc0, 0xc42051aa50, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x17f
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc42088e9c0, 0x5be28c0, 0xc4200484e0, 0x2, 0x2, 0x3ca2388, 0x4)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:10 +0x6c
github.com/hashicorp/terraform/terraform.EvalRaw(0x5bc1260, 0xc42088e9c0, 0x5be28c0, 0xc4200484e0, 0x5bc1260, 0xc42088e9c0, 0xc42088ebe0, 0x1e)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x17f
github.com/hashicorp/terraform/terraform.Eval(0x5bc1260, 0xc42088e9c0, 0x5be28c0, 0xc4200484e0, 0xc42088e9c0, 0x5bc1260, 0xc42088e9c0, 0x5)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:34 +0x53
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x3b1fb40, 0xc420020c60, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:301 +0xe7c
github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk.func3(0xc42079d010, 0xc4207929b0, 0xc42079cbe8, 0xc420794660, 0xc42079d030, 0x3b1fb40, 0xc420020c60, 0xc420192d80, 0xc420192de0)
	/opt/gopath/src/github.com/hashicorp/terraform/dag/dag.go:246 +0x251
created by github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk
	/opt/gopath/src/github.com/hashicorp/terraform/dag/dag.go:255 +0x6a6



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Steps to Reproduce
Like I said I cannot reproduce on other stacks, even with exactly the same files. I think there might be some corruption with the statefiles. Since when I use the plan without the statefile, it seems to work. When I spin up a new stack and update it, it seems to work.

### Important Factoids
* This is build by a CI running the fxinnovation/terraform docker container in version 0.8.5
* It is possible that the infrastructure was modified by someone manually, if it's the case I'll take out the baseball bat since it is forbidden to make any manual changes on our infrastructure.
* This is not happening on a PROD environment, I'm creating this issue to have a record of it, the project will be cleaned out and build form scratch again
### References
I didn't find anything similar enough to mention

**Comment by zopanix** [comment]
FYI, we found the culprit, someone recreated a resource. I think this is causing the crash. The resource that was affected is an instance that is statically defined with nothing special but it wasn't recreated exactly the same way...
I still don't believe terraform should crash in such a case but this issue can be closed if you decide you can't do anything with the information I've given you.

Thx,

**Comment by zopanix** [comment]
Just to add some more information on it, I think the crash was cause during the refresh of the state of the stack. It found the instance but the instance property (in our case I think it's the service_account) was different than what was originally created. According to my understanding of the crash report, this caused the panic in terraform

**Comment by k-kawa** [comment]
Have you tried the latest version, v0.8.6?
I got the same error with v0.8.5 but v0.8.6 works well.

**Comment by danawillow** [comment]
Yup, this was fixed in https://github.com/hashicorp/terraform/pull/11498.
