### ISSUE TITLE
aws_ssm_association got an unexpected EOF, caused terraform crash

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#12205]
Terraform 0.8.7

I have a simple aws_ssm_association doc:

```
resource "aws_ssm_association" "console" {
    name        = "AWS-JoinDirectoryServiceDomain"
    instance_id = "${aws_instance.console.id}"
    parameters = {
        directoryId    = "${aws_directory_service_directory.microsoft_ad.id}"
        directoryName  = "${var.ad["domain"]}"
    }
}
```

terraform plan:

```
+ aws_ssm_association.console
    instance_id:              "i-12345678901234567"
    name:                     "AWS-JoinDirectoryServiceDomain"
    parameters.%:             "2"
    parameters.directoryId:   "d-1234567890"
    parameters.directoryName: "corp.mydomain.com"

```

terraform apply:

```
aws_ssm_association.console: Creating...
  instance_id:              "" => "i-12345678901234567"
  name:                     "" => "AWS-JoinDirectoryServiceDomain"
  parameters.%:             "" => "2"
  parameters.directoryId:   "" => "d-1234567890"
  parameters.directoryName: "" => "corp.mydomain.com"
Error applying plan:

1 error(s) occurred:

* aws_ssm_association.console: unexpected EOF

Terraform does not automatically rollback in the face of errors.
...etc.
```

However, if there are other pending objects which have been planned/applied, and created but not yet written to the statefile, terraform proceeds to completely crash out, not updating the state file and losing all the changes.

Multiple errors here

**Comment by gtmtech** [comment]
The error (with TF_LOG) is this

```
Error applying plan:

 runtime error: index out of range
2017/02/23 17:02:16 [DEBUG] plugin: terraform: 
2017/02/23 17:02:16 [DEBUG] plugin: terraform: goroutine 146 [running]:
2017/02/23 17:02:16 [DEBUG] plugin: terraform: panic(0x3287ae0, 0xc4200100d0)
2017/02/23 17:02:16 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/panic.go:500 +0x1a1
2017/02/23 17:02:16 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/aws.expandSSMDocumentParameters(0xc42070bad0, 0x39eca8f)
2017/02/23 17:02:16 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_ssm_association.go:118 +0x14d
2017/02/23 17:02:16 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsSsmAssociationCreate(0xc420871200, 0x2e32360, 0xc42051c380, 0x32dd0c0, 0x169b1)
```

**Comment by gtmtech** [comment]
@stack72 , @liamjbennett  - probably most likely for your attention as youve been helping me with all of this on another issue
