### ISSUE TITLE
Terraform crashed

### ISSUE THREAD

**Issue by joseenriquevasquez** [hashicorp/terraform#12587]
[crash.log.gz](https://github.com/hashicorp/terraform/files/834510/crash.log.gz)
Terraform version v0.8.8 and  v0.8.7

**Comment by stack72** [comment]
Relevant lines from the panic:

```
2017/03/10 11:24:27 [DEBUG] plugin: terraform: panic: interface conversion: interface {} is string, not map[string]interface {}
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 
2017/03/10 11:24:27 [DEBUG] plugin: terraform: goroutine 125 [running]:
2017/03/10 11:24:27 [DEBUG] plugin: terraform: panic(0x36d9780, 0xc420c00e80)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/panic.go:500 +0x1a1
2017/03/10 11:24:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readMap(0xc420bf87e0, 0x3de0f44, 0x4, 0xc420b1fa40, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420c04581, ...)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:145 +0x543
2017/03/10 11:24:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readField(0xc420bf87e0, 0xc420c04570, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:88 +0x4b7
2017/03/10 11:24:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).ReadField(0xc420bf87e0, 0xc420c04570, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420b18f60, ...)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:27 +0xda
2017/03/10 11:24:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*MultiLevelFieldReader).ReadFieldExact(0xc420bfa8a0, 0xc420c04570, 0x1, 0x1, 0x3de3962, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/field_reader_multi.go:31 +0xef
2017/03/10 11:24:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc420c02000, 0xc420c04570, 0x1, 0x1, 0xc420c04512, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:438 +0x134
2017/03/10 11:24:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc420c02000, 0x3de0f44, 0x4, 0x411201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:414 +0x13d
2017/03/10 11:24:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc420c02000, 0x3de0f44, 0x4, 0x3ddf27d, 0x1, 0xc420b5b260, 0x5, 0x0)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:391 +0x61
2017/03/10 11:24:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.diffMap(0xc420b0c840, 0x3de0f44, 0x4, 0xc420b1fa40, 0xc420bfab40, 0xc420c02000, 0xc41ff9fe00, 0x0, 0x0)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:825 +0x11e
2017/03/10 11:24:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc420b0c840, 0x3de0f44, 0x4, 0xc420b1fa40, 0xc420bfa760, 0xc420c02000, 0xc4203ca900, 0x0, 0x0)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:667 +0x520
2017/03/10 11:24:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc420b0c840, 0xc420bad8b0, 0xc420bf8540, 0xc420bcdb70, 0xc420b400d0, 0x0)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:369 +0x1d6
2017/03/10 11:24:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc420b12d80, 0xc420bad8b0, 0xc420bf8540, 0x12, 0xc420b40188, 0xc420bf8601)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:179 +0x42
2017/03/10 11:24:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc420b3a660, 0xc420bad860, 0xc420bad8b0, 0xc420bf8540, 0x0, 0x18, 0x18)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:225 +0x84
2017/03/10 11:24:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Diff(0xc420a13a40, 0xc420bfa060, 0xc420bcdb60, 0x0, 0x0)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:499 +0x57
2017/03/10 11:24:27 [DEBUG] plugin: terraform: reflect.Value.call(0xc4203c0480, 0xc420032438, 0x13, 0x3de0468, 0x4, 0xc420b5bed0, 0x3, 0x3, 0x5dc5360, 0xc420bb1300, ...)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:434 +0x5c8
2017/03/10 11:24:27 [DEBUG] plugin: terraform: reflect.Value.Call(0xc4203c0480, 0xc420032438, 0x13, 0xc420b5bed0, 0x3, 0x3, 0x0, 0xc420bb2540, 0xc420bb24e0)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:302 +0xa4
2017/03/10 11:24:27 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc4209eaf00, 0xc4209eaec0, 0xc420aa6d48, 0xc4209e0b80, 0xc420a13b40, 0x3236e20, 0xc420bfa060, 0x16, 0x3236e60, 0xc420bcdb60, ...)
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:383 +0x148
2017/03/10 11:24:27 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2017/03/10 11:24:27 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:477 +0x421

```

**Comment by stack72** [comment]
Hi @joseenriquevasquez 

Thanks for opening the issue here - sorry this is happening! In order for us to try and work out what the issue is, please can you post your terraform config file (minus any secrets) and describe what you were doing when it happened?

Thanks

Paul

**Comment by joseenriquevasquez** [comment]
Hi Probably I was doing something wrong . it is working now.

I guess you can close the ticket.

**Comment by stack72** [comment]
Thanks for letting me know @joseenriquevasquez
