### ISSUE TITLE
core: Terraform (master) crash in field_reader_config.go

### ISSUE THREAD

**Issue by adamdecaf** [hashicorp/terraform#1291]
I'm getting a crash related to a null reference being used. I'll try and see what I can do in the terraform source as a bug.

Stacktrace: https://gist.github.com/adamdecaf/51c5ad7344bfc28b363e

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1571e5]
 
goroutine 121 [running]:
github.com/hashicorp/terraform/helper/schema.(*Set).add(0xc2080aa860, 0x3931c0, 0xc2080a0720, 0xc2080564d0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/helper/schema/set.go:125 +0x95
github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readSet(0xc2080aa620, 0xc2080722b0, 0x1, 0x1, 0xc2080564d0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:202 +0x5ed
github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readField(0xc2080aa620, 0xc2080722b0, 0x1, 0x1, 0x737300, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:96 +0x619
github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).ReadField(0xc2080aa620, 0xc2080722b0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:25 +0x86
github.com/hashicorp/terraform/helper/schema.(*MultiLevelFieldReader).ReadFieldExact(0xc2080aa660, 0xc2080722b0, 0x1, 0x1, 0x4dc750, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/helper/schema/field_reader_multi.go:31 +0x247
github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc2080b4fc0, 0xc2080722b0, 0x1, 0x1, 0xc208072202, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:387 +0x2a2
github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc2080b4fc0, 0x52cb30, 0x17, 0x1b1201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:356 +0x1d0
github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc2080b4fc0, 0x52cb30, 0x17, 0x0, 0x0, 0x0, 0x0, 0x1ba5ec)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:333 +0x87
github.com/hashicorp/terraform/helper/schema.schemaMap.diffSet(0xc20803d350, 0x52cb30, 0x17, 0xc2080564d0, 0xc2080b1ec0, 0xc2080b4fc0, 0xc20801e800, 0x0, 0x0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/helper/schema/schema.go:707 +0x84
github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc20803d350, 0x52cb30, 0x17, 0xc2080564d0, 0xc2080b1ec0, 0xc2080b4fc0, 0xc2080aa500, 0x0, 0x0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/helper/schema/schema.go:493 +0x2f6
github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc20803d350, 0xc2080a0570, 0xc2080a0480, 0xc2081135b8, 0x0, 0x0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/helper/schema/schema.go:257 +0x1fb
github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc20803ba00, 0xc2080a0570, 0xc2080a0480, 0x11, 0x0, 0x0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:162 +0x51
github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc20803d380, 0xc2080a2c80, 0xc2080a0570, 0xc2080a0480, 0x0, 0x0, 0x0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:167 +0x1b9
github.com/hashicorp/terraform/terraform.(*EvalDiff).Eval(0xc2080775c0, 0x913088, 0xc208070240, 0x0, 0x0, 0x0, 0x0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/terraform/eval_diff.go:86 +0x25a
github.com/hashicorp/terraform/terraform.EvalRaw(0x913900, 0xc2080775c0, 0x913088, 0xc208070240, 0x0, 0x0, 0x0, 0x0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x254
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc20800ba00, 0x913088, 0xc208070240, 0x0, 0x0, 0x0, 0x0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:10 +0xf9
github.com/hashicorp/terraform/terraform.EvalRaw(0x9131c0, 0xc20800ba00, 0x913088, 0xc208070240, 0x0, 0x0, 0x0, 0x0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x254
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc208077680, 0x913088, 0xc208070240, 0x0, 0x0, 0x0, 0x0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x71
github.com/hashicorp/terraform/terraform.EvalRaw(0x9131e8, 0xc208077680, 0x913088, 0xc208070240, 0x0, 0x0, 0x0, 0x0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x254
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc20800b840, 0x913088, 0xc208070240, 0x0, 0x0, 0x0, 0x0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:10 +0xf9
github.com/hashicorp/terraform/terraform.EvalRaw(0x9131c0, 0xc20800b840, 0x913088, 0xc208070240, 0x0, 0x0, 0x0, 0x0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x254
github.com/hashicorp/terraform/terraform.Eval(0x9131c0, 0xc20800b840, 0x913088, 0xc208070240, 0x0, 0x0, 0x0, 0x0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/terraform/eval.go:34 +0x79
github.com/hashicorp/terraform/terraform.func·027(0x4a4440, 0xc2080b0e90, 0x0, 0x0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/terraform/graph.go:158 +0x754
github.com/hashicorp/terraform/dag.func·004(0x4a4440, 0xc2080b0e90, 0xc2080b4660, 0xc2080b46c0)
	/Users/adam/src/go/src/github.com/hashicorp/terraform/dag/dag.go:187 +0x106
created by github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk
	/Users/adam/src/go/src/github.com/hashicorp/terraform/dag/dag.go:196 +0x8ef
```

**Comment by adamdecaf** [comment]
I should mention my terraform version
```
~/src/go/src/github.com/banno/terraform-provider-haproxyapi $ terraform version
Terraform v0.4.0-dev (55d682482a072f783de33954bb396bbf556a882c
```

**Comment by phinze** [comment]
Thanks for the report - taking a look!

**Comment by phinze** [comment]
Ah I see now - `banno/terraform-provider-haproxyapi` - is this a custom provider you're working on?

It seems there's an issue with the "service_discovery_group" attribute in the `haproxyapi_config` resource. Think you could share the schema definition for that attribute?

**Comment by adamdecaf** [comment]
Sure thing.

```
&schema.Resource{
		Create: resourceHaproxyApiConfigCreate,
		Read:   resourceHaproxyApiConfigRead,
		Update: resourceHaproxyApiConfigUpdate,
		Delete: resourceHaproxyApiConfigDelete,

		Schema: map[string]*schema.Schema{
			"host_match": &schema.Schema{
				Type:     schema.TypeString,
				Required: true,
				ForceNew: false,
			},
			"service_type": &schema.Schema{
				Type:     schema.TypeString,
				Required: true,
				ForceNew: false,
			},
			"service_name": &schema.Schema{
				Type:     schema.TypeString,
				Required: true,
				ForceNew: false,
			},
			"service_discovery_group": &schema.Schema{
				Type: schema.TypeSet,
				Optional: true,
				ForceNew: false,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema {
						"group_name": &schema.Schema{
							Type: schema.TypeString,
							Required: true,
						},
						"weight": &schema.Schema{
							Type: schema.TypeInt,
							Optional: true,
						},
					},
				},
			},
		},
	}
```

**Comment by adamdecaf** [comment]
Here's the relevant .tf source from the test I'm writing.

```
resource "haproxyapi_config" "backend-create-example2-http" {
  host_match = "backend-create-example2.dev.banno.com"
  service_type = "http"
  service_name = "backend-create-example2"
  service_discovery_group {
    group_name = "sd_group_1"
  }
  service_discovery_group {
    group_name = "sd_group_2"
    weight = 75
  }
}
```

**Comment by phinze** [comment]
@adamdecaf there we go - any sub-resource with `TypeSet` needs a `Set:` hash function provided. This is something we should make a clearer in with the internal validations we run.

For an example, see https://github.com/hashicorp/terraform/blob/55d682482a072f783de33954bb396bbf556a882c/builtin/providers/aws/resource_aws_instance.go#L297-L307

**Comment by adamdecaf** [comment]
@phinze Ah, that makes more sense. So I guess that's not being checked to make sure it exists before calling into it?

**Comment by phinze** [comment]
Well it's being checked in the provider unit test and failing with a cryptic error message:

```
	provider_test.go:23: err: haproxyapi_config: service_discovery_group: Set must be set
```

But we should probably fail harder and earlier at runtime as well. Let me know if implementing it sorts the problem on your side and I'll leave this issue as a reminder to look into better validation. :+1:

**Comment by adamdecaf** [comment]
@phinze yea, that seems to work now! Thanks for checking into this.
