### ISSUE TITLE
Error while provisioning (remote-exec) azure virtual machines

### ISSUE THREAD

**Issue by shanielh** [hashicorp/terraform#12999]
### Terraform Version

0.9.1

### Affected Resource(s)

- azurerm_virtual_machine

### Terraform Configuration Files
```hcl

resource "azurerm_virtual_machine" "kafka" {

  ...

  connection {
    user        = "[removed]"
    private_key = "${file("${path.module}/[removed]")}"
    timeout     = 5
    agent       = "false"
    host        = "${element(azurerm_public_ip.kafka.*.ip_address, count.index)}"
  }

  provisioner "remote-exec" {
    inline = [
      "mkdir /[removed]"
    ]
  }
}

```

### Debug Log 

```
....
2017/03/23 13:58:02 [DEBUG] plugin: terraform: panic: interface conversion: interface {} is nil, not string
2017/03/23 13:58:02 [DEBUG] plugin: terraform: 
2017/03/23 13:58:02 [DEBUG] plugin: terraform: goroutine 98 [running]:
2017/03/23 13:58:02 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/provisioners/remote-exec.generateScripts(0xc4202e0460, 0x4c5b6bc, 0x6, 0x3fded20, 0xc42051fa40, 0x428901)
2017/03/23 13:58:02 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/provisioners/remote-exec/resource_provisioner.go:84 +0x1c2
2017/03/23 13:58:02 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/provisioners/remote-exec.collectScripts(0xc4202e0460, 0x7407c40, 0xc420732a40, 0x0, 0x0, 0x0)
2017/03/23 13:58:02 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/provisioners/remote-exec/resource_provisioner.go:96 +0x732
2017/03/23 13:58:02 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/provisioners/remote-exec.applyFn(0x73fed60, 0xc42035fb90, 0x0, 0x0)
2017/03/23 13:58:02 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/provisioners/remote-exec/resource_provisioner.go:64 +0x235
2017/03/23 13:58:02 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provisioner).Apply(0xc42037e480, 0x73da7a0, 0xc4201a6040, 0xc4201c0550, 0xc42035e660, 0x0, 0x0)
2017/03/23 13:58:02 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provisioner.go:179 +0x5bb
2017/03/23 13:58:02 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProvisionerServer).Apply(0xc4202cebc0, 0xc42039bb80, 0xc4201a6028, 0x0, 0x0)
2017/03/23 13:58:02 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provisioner.go:142 +0x191
2017/03/23 13:58:02 [DEBUG] plugin: terraform: reflect.Value.call(0xc42017e060, 0xc42000c028, 0x13, 0x4c5783b, 0x4, 0xc4206ebf20, 0x3, 0x3, 0x4389ec, 0xc42047bf38, ...)
2017/03/23 13:58:02 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:434 +0x91f
2017/03/23 13:58:02 [DEBUG] plugin: terraform: reflect.Value.Call(0xc42017e060, 0xc42000c028, 0x13, 0xc42047bf20, 0x3, 0x3, 0x0, 0x180000, 0x0)
2017/03/23 13:58:02 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:302 +0xa4
2017/03/23 13:58:02 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc42037e6c0, 0xc42037e640, 0xc420398c20, 0xc4204d2080, 0xc4202ceee0, 0x3ee7fc0, 0xc42039bb80, 0x16, 0x3ee8000, 0xc4201a6028, ...)
2017/03/23 13:58:02 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:387 +0x144
2017/03/23 13:58:02 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2017/03/23 13:58:02 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:481 +0x404
2017/03/23 13:58:02 [DEBUG] root: eval: *terraform.EvalIf
2017/03/23 13:58:02 [DEBUG] root: eval: *terraform.EvalWriteState
2017/03/23 13:58:02 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/03/23 13:58:02 [DEBUG] plugin: /home/shani/Applications/terraform/terraform: plugin process exited
2017/03/23 13:58:02 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/03/23 13:58:02 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* unexpected EOF
2017/03/23 13:58:02 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* unexpected EOF
```

###  Output

```
...
azurerm_virtual_machine.zookeeper.1: Still creating... (4m0s elapsed)
azurerm_virtual_machine.zookeeper.1: Provisioning with 'remote-exec'...
Error applying plan:

4 error(s) occurred:

* azurerm_virtual_machine.zookeeper[2]: 1 error(s) occurred:

* unexpected EOF
* azurerm_virtual_machine.kafka: 1 error(s) occurred:

* connection is shut down
* azurerm_virtual_machine.zookeeper[0]: 1 error(s) occurred:

* connection is shut down
* azurerm_virtual_machine.zookeeper[1]: 1 error(s) occurred:

* connection is shut down

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
```

### Steps to Reproduce

1. `terraform apply`

### Another information

I've managed to connect to the virtual machine right after that the error occurred.

#### Updates : 

1. Removed timeout since it's invalid and set to the default.
2. Changed Agent to `false` instead of `"false"`

**Comment by StephenWeatherford** [comment]
@shanielh Can you try with 0.9.3?  This scenario worked fine for me, using this configuration file: https://gist.github.com/StephenWeatherford/f1e0b1a4af30e670e983a0ace68b862c.

Thanks!
Stephen

**Comment by shanielh** [comment]
@StephenWeatherford I'll try it tomorrow, thanks.

**Comment by shanielh** [comment]
Not yet. I'll try this week.

**Comment by shanielh** [comment]
Hey @tombuildsstuff , I tried it today but couldn't create the subnet (I waited 20 minutes) that the virtual machine should be inside. You can mark as completed and I'll comment if I'll have problems again. Sorry.

**Comment by tombuildsstuff** [comment]
Hi @shanielh

Sure, no problem / thanks for letting us know - I've just tested @StephenWeatherford's configuration works, so I'm going to close this for the moment. Please comment/open a bug if there's still an issue here / with subnets and we'll take a look :)

Thanks!
