### ISSUE TITLE
azure_virtual_mashine_scale_set: crash after apply on created environment

### ISSUE THREAD

**Issue by shanielh** [hashicorp/terraform#13009]
### Terraform Version

`0.9.1`

### Affected Resource(s)

- azure_virtual_machine_scale_set

### Terraform Configuration Files

Will create if needed

### Debug Output

```
Error applying plan:

1 error(s) occurred:

* module.ingestion-set.azurerm_virtual_machine_scale_set.main: 1 error(s) occurred:

* azurerm_virtual_machine_scale_set.main: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: interface conversion: interface {} is nil, not map[string]interface {}
2017/03/23 16:01:59 [DEBUG] plugin: terraform: 
2017/03/23 16:01:59 [DEBUG] plugin: terraform: goroutine 521 [running]:
2017/03/23 16:01:59 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/azurerm.expandAzureRmVirtualMachineScaleSetOsProfileLinuxConfig(0xc4204bf650, 0x4cb7cf2, 0x17, 0x4a96fc0)
2017/03/23 16:01:59 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/azurerm/resource_arm_virtual_machine_scale_set.go:1083 +0x54c
2017/03/23 16:01:59 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/azurerm.expandAzureRMVirtualMachineScaleSetsOsProfile(0xc4204bf650, 0x4cf0730, 0x1f, 0x4a96fc0)
2017/03/23 16:01:59 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/azurerm/resource_arm_virtual_machine_scale_set.go:998 +0x46a
2017/03/23 16:01:59 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/azurerm.resourceArmVirtualMachineScaleSetCreate(0xc4204bf650, 0x46653e0, 0xc4212a4000, 0x0, 0x0)
2017/03/23 16:01:59 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/azurerm/resource_arm_virtual_machine_scale_set.go:428 +0x36f
2017/03/23 16:01:59 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc42127ade0, 0xc4209f4820, 0xc4208678a0, 0x46653e0, 0xc4212a4000, 0x1, 0x28, 0xc4206ca540)
2017/03/23 16:01:59 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:192 +0x378
2017/03/23 16:01:59 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4202caf50, 0xc4209f47d0, 0xc4209f4820, 0xc4208678a0, 0x7f3e791024b0, 0x0, 0xc420021300)
2017/03/23 16:01:59 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0x9b
2017/03/23 16:01:59 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4206bf2e0, 0xc420866640, 0xc420a0a2f0, 0x0, 0x0)
2017/03/23 16:01:59 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2017/03/23 16:01:59 [DEBUG] plugin: terraform: reflect.Value.call(0xc4201782a0, 0xc4202ed3f0, 0x13, 0x4c5783b, 0x4, 0xc4212a3f20, 0x3, 0x3, 0x0, 0xc4205b3ef8, ...)
2017/03/23 16:01:59 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:434 +0x91f
2017/03/23 16:01:59 [DEBUG] plugin: terraform: reflect.Value.Call(0xc4201782a0, 0xc4202ed3f0, 0x13, 0xc4205b3f20, 0x3, 0x3, 0xc4205b3fc0, 0x7916ce, 0xc42124d320)
2017/03/23 16:01:59 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:302 +0xa4
2017/03/23 16:01:59 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc420ba3840, 0xc420ba3800, 0xc421294140, 0xc420be2b00, 0xc4206c84a0, 0x3ee7ac0, 0xc420866640, 0x16, 0x3ee7b00, 0xc420a0a2f0, ...)
2017/03/23 16:01:59 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:387 +0x144
2017/03/23 16:01:59 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2017/03/23 16:01:59 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:481 +0x404
2017/03/23 16:01:59 [DEBUG] root.ingestion-set: eval: *terraform.EvalWriteState
2017/03/23 16:01:59 [DEBUG] root.ingestion-set: eval: *terraform.EvalApplyProvisioners
2017/03/23 16:01:59 [DEBUG] root.ingestion-set: eval: *terraform.EvalIf
2017/03/23 16:01:59 [DEBUG] root.ingestion-set: eval: *terraform.EvalWriteState
2017/03/23 16:01:59 [DEBUG] root.ingestion-set: eval: *terraform.EvalWriteDiff
2017/03/23 16:01:59 [DEBUG] root.ingestion-set: eval: *terraform.EvalApplyPost
2017/03/23 16:01:59 [ERROR] root.ingestion-set: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* azurerm_virtual_machine_scale_set.main: unexpected EOF
2017/03/23 16:01:59 [ERROR] root.ingestion-set: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* azurerm_virtual_machine_scale_set.main: unexpected EOF
2017/03/23 16:01:59 [TRACE] [walkApply] Exiting eval tree: module.ingestion-set.azurerm_virtual_machine_scale_set.main
2017/03/23 16:01:59 [DEBUG] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/03/23 16:01:59 [DEBUG] plugin: /home/shani/Applications/terraform/terraform: plugin process exited
2017/03/23 16:01:59 [TRACE] Preserving existing state lineage "1c2f530e-4a1e-40a7-beef-739cd887d425"
2017/03/23 16:01:59 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/03/23 16:01:59 [WARN] plugin: error closing client during Kill: connection is shut down
2017/03/23 16:01:59 [DEBUG] plugin: terraform: template-provider (internal) 2017/03/23 16:01:59 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/03/23 16:01:59 [DEBUG] plugin: terraform: random-provider (internal) 2017/03/23 16:01:59 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/03/23 16:01:59 [DEBUG] plugin: terraform: terraform-provider (internal) 2017/03/23 16:01:59 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/03/23 16:01:59 [DEBUG] plugin: /home/shani/Applications/terraform/terraform: plugin process exited
2017/03/23 16:01:59 [DEBUG] plugin: /home/shani/Applications/terraform/terraform: plugin process exited
2017/03/23 16:01:59 [DEBUG] plugin: /home/shani/Applications/terraform/terraform: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
...
```

### Panic Output

[crash.log.zip](https://github.com/hashicorp/terraform/files/864962/crash.log.zip) (Encrypted using https://www.hashicorp.com/security/)

### Expected Behavior

Nothing?

### Actual Behavior

It Crashed :disappointed: 

### Steps to Reproduce

1. Create TF configuration with `azure_virtual_machine_scale_set`
2. `terraform apply`
3. `terraform apply`

**Comment by stack72** [comment]
Hi @shanielh 

Thanks for the issue report here - please can you post your terraform config (minus any secrets) so that we can try and replicate this? 

Paul

**Comment by shanielh** [comment]
Hi @stack72 

Thanks for the help.

[archive.zip](https://github.com/hashicorp/terraform/files/865174/archive.zip), Make sure to updated the variables with your account credentials.

Shani.

**Comment by cberner** [comment]
I've run into a very similar crash in version 0.8.7. After creating a Scale Set, if I try to modify the `storage_profile_os_disk.image` field and apply the change it crashes with the same panic (included below). Let me know if you need more information.
```
17/04/05 21:13:00 [DEBUG] plugin: terraform: azurerm-provider (internal) 2017/04/05 21:13:00 [INFO] preparing arguments for Azure ARM Virtual Machine Scale Set creation.
2017/04/05 21:13:00 [DEBUG] plugin: terraform: panic: interface conversion: interface {} is nil, not map[string]interface {}
2017/04/05 21:13:00 [DEBUG] plugin: terraform:
2017/04/05 21:13:00 [DEBUG] plugin: terraform: goroutine 166 [running]:
2017/04/05 21:13:00 [DEBUG] plugin: terraform: panic(0x32d72e0, 0xc4209a2280)
2017/04/05 21:13:00 [DEBUG] plugin: terraform:  /opt/go/src/runtime/panic.go:500 +0x1a1
2017/04/05 21:13:00 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/azurerm.expandAzureRmVirtualMachineScaleSetOsProfileLinuxConfig(0xc4204fb440, 0x3a33b67, 0x17, 0x3877180)
2017/04/05 21:13:00 [DEBUG] plugin: terraform:  /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/azurerm/resource_arm_virtual_machine_scale_set.go:970 +0x5dc
2017/04/05 21:13:00 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/azurerm.expandAzureRMVirtualMachineScaleSetsOsProfile(0xc4204fb440, 0x3a67359, 0x1f, 0x3877180)
2017/04/05 21:13:00 [DEBUG] plugin: terraform:  /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/azurerm/resource_arm_virtual_machine_scale_set.go:885 +0x5a5
2017/04/05 21:13:00 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/azurerm.resourceArmVirtualMachineScaleSetCreate(0xc4204fb440, 0x34ca120, 0xc4203e8000, 0x32dd0c0, 0x169b1)
2017/04/05 21:13:00 [DEBUG] plugin: terraform:  /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/azurerm/resource_arm_virtual_machine_scale_set.go:377 +0x3f3
2017/04/05 21:13:00 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc420299ce0, 0xc420719270, 0xc4205dc720, 0x34ca120, 0xc4203e8000, 0x1, 0xc4205a3410, 0x0)
2017/04/05 21:13:00 [DEBUG] plugin: terraform:  /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:168 +0x1ff
2017/04/05 21:13:00 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc42054e4e0, 0xc420719220, 0xc420719270, 0xc4205dc720, 0x0, 0x18, 0x18)
2017/04/05 21:13:00 [DEBUG] plugin: terraform:  /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:212 +0x9b
2017/04/05 21:13:00 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4202abc40, 0xc4205cde40, 0xc4200fc930, 0x0, 0x0)
2017/04/05 21:13:00 [DEBUG] plugin: terraform:  /opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2017/04/05 21:13:00 [DEBUG] plugin: terraform: reflect.Value.call(0xc420507560, 0xc42029a3a8, 0x13, 0x39de3ec, 0x4, 0xc4203dbed0, 0x3, 0x3, 0x0, 0x0, ...)
2017/04/05 21:13:00 [DEBUG] plugin: terraform:  /opt/go/src/reflect/value.go:434 +0x5c8
2017/04/05 21:13:00 [DEBUG] plugin: terraform: reflect.Value.Call(0xc420507560, 0xc42029a3a8, 0x13, 0xc4203dbed0, 0x3, 0x3, 0x0, 0x0, 0x0)
2017/04/05 21:13:00 [DEBUG] plugin: terraform:  /opt/go/src/reflect/value.go:302 +0xa4
2017/04/05 21:13:00 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc420123240, 0xc420123200, 0xc4201032d0, 0xc42009e300, 0xc42046bc80, 0x2e346e0, 0xc4205cde40, 0x16, 0x2e34720, 0xc4200fc930, ...)
2017/04/05 21:13:00 [DEBUG] plugin: terraform:  /opt/go/src/net/rpc/server.go:383 +0x148
```
