### ISSUE TITLE
make apply crashes

### ISSUE THREAD

**Issue by mdpradeep** [hashicorp/terraform#13094]
### Terraform Version
`Terraform v0.8.8`

### Affected Resource(s)
- unable to create kubernetes cluster.

### Panic Output
Attached the `crash.log` file

### Expected Behavior
Kubernetes cluster should have got created.

### Actual Behavior
Crashed

### Steps to Reproduce
1. `make apply`

### Important Factoids
Running on Azure

[crash.log.zip](https://github.com/hashicorp/terraform/files/872697/crash.log.zip)

**Comment by grubernaut** [comment]
Panic trace:
```
2017/03/27 12:46:08 [DEBUG] plugin: terraform: panic: interface conversion: interface {} is nil, not map[string]interface {}
2017/03/27 12:46:08 [DEBUG] plugin: terraform:
2017/03/27 12:46:08 [DEBUG] plugin: terraform: goroutine 876 [running]:
2017/03/27 12:46:08 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/azurerm.expandAzureRmVirtualMachineScaleSetOsProfileLinuxConfig(0xc421619f80, 0x407dd81, 0x17, 0x3eb20a0)
2017/03/27 12:46:08 [DEBUG] plugin: terraform:  /go/src/github.com/hashicorp/terraform/builtin/providers/azurerm/resource_arm_virtual_machine_scale_set.go:992 +0x54c
2017/03/27 12:46:08 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/azurerm.expandAzureRMVirtualMachineScaleSetsOsProfile(0xc421619f80, 0xc420802000, 0x0, 0x0)
2017/03/27 12:46:08 [DEBUG] plugin: terraform:  /go/src/github.com/hashicorp/terraform/builtin/providers/azurerm/resource_arm_virtual_machine_scale_set.go:907 +0x46a
2017/03/27 12:46:08 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/azurerm.resourceArmVirtualMachineScaleSetCreate(0xc421619f80, 0x3ae3c00, 0xc420b30000, 0x18, 0x40bcf4)
2017/03/27 12:46:08 [DEBUG] plugin: terraform:  /go/src/github.com/hashicorp/terraform/builtin/providers/azurerm/resource_arm_virtual_machine_scale_set.go:378 +0x350
2017/03/27 12:46:08 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc420c3f8c0, 0xc4211a2820, 0xc4211c9240, 0x3ae3c00, 0xc420b30000, 0x1, 0x28, 0xc420e959b0)
2017/03/27 12:46:08 [DEBUG] plugin: terraform:  /go/src/github.com/hashicorp/terraform/helper/schema/resource.go:168 +0x1c1
2017/03/27 12:46:08 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4206ff260, 0xc4211a27d0, 0xc4211a2820, 0xc4211c9240, 0x7f479559a000, 0x0, 0x0)
2017/03/27 12:46:08 [DEBUG] plugin: terraform:  /go/src/github.com/hashicorp/terraform/helper/schema/provider.go:212 +0x9b
2017/03/27 12:46:08 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc421677e20, 0xc420e93da0, 0xc4208acdc0, 0x0, 0x0)
2017/03/27 12:46:08 [DEBUG] plugin: terraform:  /go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2017/03/27 12:46:08 [DEBUG] plugin: terraform: reflect.Value.call(0xc420382a20, 0xc42000d6a0, 0x13, 0x4025714, 0x4, 0xc420433f20, 0x3, 0x3, 0x0, 0xc420879e40, ...)
2017/03/27 12:46:08 [DEBUG] plugin: terraform:  /usr/local/go/src/reflect/value.go:434 +0x91f
2017/03/27 12:46:08 [DEBUG] plugin: terraform: reflect.Value.Call(0xc420382a20, 0xc42000d6a0, 0x13, 0xc420b6f720, 0x3, 0x3, 0xc420879ea0, 0xc420729be0, 0x0)
2017/03/27 12:46:08 [DEBUG] plugin: terraform:  /usr/local/go/src/reflect/value.go:302 +0xa4
2017/03/27 12:46:08 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc4206242c0, 0xc420624280, 0xc4208ded60, 0xc420b0da00, 0xc4208cc260, 0x342d460, 0xc420e93da0, 0x16, 0x342d4a0, 0xc4208acdc0, ...)
2017/03/27 12:46:08 [DEBUG] plugin: terraform:  /usr/local/go/src/net/rpc/server.go:387 +0x144
2017/03/27 12:46:08 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2017/03/27 12:46:08 [DEBUG] plugin: terraform:  /usr/local/go/src/net/rpc/server.go:481 +0x404
2017/03/27 12:46:08 [DEBUG] plugin: /home/julia/tectonic-installer/bin/terraform: plugin process exited
```

**Comment by tombuildsstuff** [comment]
Another related PR: #13009 

Taking a quick look into this using [the TF config from this comment](https://github.com/hashicorp/terraform/issues/13009#issuecomment-288751341) - after the initial apply is completed successfully, a plan shows (in this debug build, I've temporarily made `admin_password` a regular [non-sensitive] variable, to see the value) as:
```
~ azurerm_virtual_machine_scale_set.main
    os_profile.33411580.admin_password:        "" => "password"
    os_profile.33411580.admin_username:        "" => "ubuntu"
    os_profile.33411580.computer_name_prefix:  "" => "prefix"
    os_profile.33411580.custom_data:           "" => "6a5bd66d24af29ab077673e12b3a06c7ceed97a7"
    os_profile.413497256.admin_password:       "" => ""
    os_profile.413497256.admin_username:       "ubuntu" => ""
    os_profile.413497256.computer_name_prefix: "prefix" => ""
    os_profile.413497256.custom_data:          "Y3VzdG9tIGRhdGEh" => ""
```

On the second apply this crashes as shown in the stack trace
