### ISSUE TITLE
Terraform crash

### ISSUE THREAD

**Issue by michalmedvecky** [hashicorp/terraform#13568]
I accidentally ran terraform in incorrect directory and I'm getting:

```
2017/04/12 11:44:50 [INFO] Terraform version: 0.9.0 dev 89acb5811a25e59e6a9d55cf5a2429846e3b5982+CHANGES
2017/04/12 11:44:50 [INFO] CLI args: []string{"/usr/local/bin/terraform-dev", "apply"}
2017/04/12 11:44:50 [DEBUG] Detected home directory from env var: /home/ubuntu
2017/04/12 11:44:50 [DEBUG] Detected home directory from env var: /home/ubuntu
2017/04/12 11:44:50 [DEBUG] Attempting to open CLI config file: /home/ubuntu/.terraformrc
2017/04/12 11:44:50 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2017/04/12 11:44:50 [DEBUG] command: loading backend config file: /home/ubuntu/devel/sec_tools/gitlab
2017/04/12 11:44:50 [INFO] command: backend config not found, returning nil: /home/ubuntu/devel/sec_tools/gitlab
2017/04/12 11:44:50 [DEBUG] command: no data state file found for backend config
2017/04/12 11:44:50 [DEBUG] New state was assigned lineage "1e8b4b22-55e7-46c1-b779-4224f88af27b"
2017/04/12 11:44:50 [INFO] command: backend initialized: <nil>
2017/04/12 11:44:50 [INFO] command: backend <nil> is not enhanced, wrapping in local
2017/04/12 11:44:50 [INFO] backend/local: starting Apply operation
2017/04/12 11:44:50 [DEBUG] New state was assigned lineage "16c6b93d-9e70-49c0-898d-0fa076b14199"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4ef7d0]

goroutine 14 [running]:
panic(0x358f6a0, 0xc42000e060)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/hashicorp/terraform/terraform.(*Context).Input(0xc420309d40, 0xc420309d07, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/hashicorp/terraform/terraform/context.go:331 +0xe0
github.com/hashicorp/terraform/backend/local.(*Local).context(0xc42034f710, 0xc42034f7a0, 0x2, 0x2, 0x4, 0xc4203533c0, 0x2)
	/home/ubuntu/go/src/github.com/hashicorp/terraform/backend/local/backend_local.go:68 +0x3d6
github.com/hashicorp/terraform/backend/local.(*Local).opApply(0xc42034f710, 0x5c140a0, 0xc420353340, 0xc42034f7a0, 0xc420339200)
	/home/ubuntu/go/src/github.com/hashicorp/terraform/backend/local/backend_apply.go:31 +0x1c7
github.com/hashicorp/terraform/backend/local.(*Local).(github.com/hashicorp/terraform/backend/local.opApply)-fm(0x5c140a0, 0xc420353340, 0xc42034f7a0, 0xc420339200)
	/home/ubuntu/go/src/github.com/hashicorp/terraform/backend/local/backend.go:142 +0x52
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc42034f710, 0xc420325390, 0xc420325380, 0x5c140a0, 0xc420353340, 0xc42034f7a0, 0xc420339200)
	/home/ubuntu/go/src/github.com/hashicorp/terraform/backend/local/backend.go:162 +0x98
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
	/home/ubuntu/go/src/github.com/hashicorp/terraform/backend/local/backend.go:163 +0x1aa
```

Incorrect directory means it's one level upper from my provision dir:

```
$ ls -lia
total 24
1035689 drwxrwxr-x 4 ubuntu ubuntu 4096 Apr 12 11:44 .
1035899 drwxrwxr-x 5 ubuntu ubuntu 4096 Apr 11 15:00 ..
1027490 -rw-rw-r-- 1 ubuntu ubuntu 2758 Apr 12 11:46 crash.log
1027586 drwxrwxr-x 7 ubuntu ubuntu 4096 Apr 11 15:01 deploy
1027492 -rw-rw-r-- 1 ubuntu ubuntu   42 Apr 11 15:00 .gitignore
1035645 drwxrwxr-x 4 ubuntu ubuntu 4096 Apr 12 11:46 provision
```

TF files are in `provision` dir.

I am not sure if this helps, but terraform kindly asked me to report this crash so I kindly do so.

```
$ terraform apply
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4ef7d0]

goroutine 14 [running]:
panic(0x358f6a0, 0xc42000e060)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/hashicorp/terraform/terraform.(*Context).Input(0xc420309d40, 0xc420309d07, 0x0, 0x0)
    /home/ubuntu/go/src/github.com/hashicorp/terraform/terraform/context.go:331 +0xe0
github.com/hashicorp/terraform/backend/local.(*Local).context(0xc42034f710, 0xc42034f7a0, 0x2, 0x2, 0x4, 0xc4203533c0, 0x2)
    /home/ubuntu/go/src/github.com/hashicorp/terraform/backend/local/backend_local.go:68 +0x3d6
github.com/hashicorp/terraform/backend/local.(*Local).opApply(0xc42034f710, 0x5c140a0, 0xc420353340, 0xc42034f7a0, 0xc420339200)
    /home/ubuntu/go/src/github.com/hashicorp/terraform/backend/local/backend_apply.go:31 +0x1c7
github.com/hashicorp/terraform/backend/local.(*Local).(github.com/hashicorp/terraform/backend/local.opApply)-fm(0x5c140a0, 0xc420353340, 0xc42034f7a0, 0xc420339200)
    /home/ubuntu/go/src/github.com/hashicorp/terraform/backend/local/backend.go:142 +0x52
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc42034f710, 0xc420325390, 0xc420325380, 0x5c140a0, 0xc420353340, 0xc42034f7a0, 0xc420339200)
    /home/ubuntu/go/src/github.com/hashicorp/terraform/backend/local/backend.go:162 +0x98
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
    /home/ubuntu/go/src/github.com/hashicorp/terraform/backend/local/backend.go:163 +0x1aa



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by jbardin** [comment]
Hi @michalmedvecky,

Thanks or reporting the issue. I'm not sure if you've noticed, but this is a build from an old unreleased commit, with some local changes. This shouldn't panic with any of the terraform releases.
