### ISSUE TITLE
Terraform crashed when import azurerm vm with managed os disk 

### ISSUE THREAD

**Issue by djatlantic** [hashicorp/terraform#14164]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
Terraform v0.9.4

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_virutal_machine
If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

terraform import azurerm_virtual_machine.centos7test /subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Compute/virtualMachines/centos7test
azurerm_virtual_machine.centos7test: Importing from ID "/subscriptions/xxxxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Compute/virtualMachines/centos7test"...
azurerm_virtual_machine.centos7test: Import complete!
  Imported azurerm_virtual_machine (ID: /subscriptions/xxxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Compute/virtualMachines/centos7test)
azurerm_virtual_machine.centos7test: Refreshing state... (ID: /subscriptions/xxxxxxx-...ft.Compute/virtualMachines/centos7test)
Error importing: 1 error(s) occurred:

* azurerm_virtual_machine.centos7test (import id: /subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Compute/virtualMachines/centos7test): 1 error(s) occurred:

* import azurerm_virtual_machine.centos7test result: /subscriptions/xxxxxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Compute/virtualMachines/centos7test: azurerm_virtual_machine.centos7test: unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d53fc9]
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: 
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: goroutine 11 [running]:
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: github.com/hashicorp/terraform/builtin/providers/azurerm.resourceArmVirtualMachineRead(0xc4201f48c0, 0x4a19dc0, 0xc4203d2000, 0x0, 0x7a82560)
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/azurerm/resource_arm_virtual_machine.go:642 +0x1499
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc4201cafc0, 0xc42072e280, 0x4a19dc0, 0xc4203d2000, 0xc420622660, 0xc420426201, 0x0)
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:314 +0x21d
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4202467e0, 0xc42072e230, 0xc42072e280, 0x7f0bd3f96000, 0x0, 0x0)
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:267 +0x91
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4206570e0, 0xc42069c6f0, 0xc42069c970, 0x0, 0x0)
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: reflect.Value.call(0xc420018de0, 0xc42000c4c0, 0x13, 0x505c04a, 0x4, 0xc4206b2f20, 0x3, 0x3, 0x0, 0x0, ...)
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: 	/opt/go/src/reflect/value.go:434 +0x91f
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: reflect.Value.Call(0xc420018de0, 0xc42000c4c0, 0x13, 0xc4205d6720, 0x3, 0x3, 0x0, 0xd4000f, 0xc4205d6720)
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: 	/opt/go/src/reflect/value.go:302 +0xa4
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: net/rpc.(*service).call(0xc4201bdb80, 0xc4201bdb00, 0xc4204509d8, 0xc420547c80, 0xc4203958c0, 0x41f8dc0, 0xc42069c6f0, 0x16, 0x41f8e00, 0xc42069c970, ...)
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: 	/opt/go/src/net/rpc/server.go:387 +0x144
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: created by net/rpc.(*Server).ServeCodec
2017/05/02 16:00:26 [DEBUG] plugin: terraform_0.9.4: 	/opt/go/src/net/rpc/server.go:481 +0x404
2017/05/02 16:00:26 [DEBUG] plugin: /home/struong/bin/terraform_0.9.4: plugin process exited
2017/05/02 16:00:26 [ERROR] root: eval: *terraform.EvalRefresh, err: azurerm_virtual_machine.centos7test: unexpected EOF
2017/05/02 16:00:26 [ERROR] root: eval: *terraform.EvalSequence, err: azurerm_virtual_machine.centos7test: unexpected EOF
2017/05/02 16:00:26 [TRACE] [walkImport] Exiting eval tree: import azurerm_virtual_machine.centos7test result: /subscriptions/xxxxxx/resourceGroups/xxxxx/providers/Microsoft.Compute/virtualMachines/centos7test
2017/05/02 16:00:26 [DEBUG] dag/walk: upstream errored, not walking "provider.azurerm (close)"
2017/05/02 16:00:26 [WARN] plugin: error closing client during Kill: connection is shut down
2017/05/02 16:00:26 [DEBUG] plugin: waiting for all plugin processes to complete...

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by djatlantic** [comment]
https://gist.github.com/djatlantic/a4735168af60794f1abb54f0ae20752b
