### ISSUE TITLE
Data source openstack_networking_network_v2 leads to crash

### ISSUE THREAD

**Issue by val-scality** [hashicorp/terraform#14538]
### Terraform Version
```bash
> terraform -v
Terraform v0.9.5
```

### Affected Resource(s)
- data "openstack_networking_network_v2"

### Terraform Configuration Files
**main.tf**:
```hcl
variable "p9_auth_url" {}
variable "p9_token" {}
variable "p9_tenant_id" {}

provider "openstack" {
	auth_url  = "${var.p9_auth_url}"
	token     = "${var.p9_token}"
	tenant_id = "${var.p9_tenant_id}"
}
```

**network.tf**:
```hcl
data "openstack_networking_network_v2" "internal" {
	name = "tenantnetwork1"
}

data "openstack_networking_network_v2" "external" {
	name = "externalnetwork1"
}
```

### Debug Output

```log
> terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.openstack_networking_network_v2.external: Refreshing state...
data.openstack_networking_network_v2.internal: Refreshing state...
Error refreshing state: 2 error(s) occurred:

* data.openstack_networking_network_v2.internal: 1 error(s) occurred:

* data.openstack_networking_network_v2.internal: data.openstack_networking_network_v2.internal: unexpected EOF
* data.openstack_networking_network_v2.external: 1 error(s) occurred:

* data.openstack_networking_network_v2.external: data.openstack_networking_network_v2.external: unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x354d566]
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: goroutine 82 [running]:
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud.(*ServiceClient).ServiceURL(0x0, 0xc42075d3a0, 0x1, 0x1, 0xc420523140, 0x0)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud/service_client.go:37 +0x26
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks.rootURL(0x0, 0x0, 0xc42075d470)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/urls.go:10 +0x5f
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks.listURL(0x0, 0x88, 0x4f4d4c0)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/urls.go:18 +0x2b
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks.List(0x0, 0x7ad1680, 0xc42016c900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go:42 +0x6e
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/builtin/providers/openstack.dataSourceNetworkingNetworkV2Read(0xc4202d0460, 0x4cb73a0, 0xc4205e1c20, 0xc4203caa01, 0xc420049a20)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/openstack/data_source_openstack_networking_network_v2.go:69 +0x28c
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc4203664e0, 0xc420475760, 0x4cb73a0, 0xc4205e1c20, 0xc4205bc980, 0xc420520d01, 0x0)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:252 +0xbb
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc4202d0a80, 0xc4201c2690, 0xc420475760, 0x7f968fc38000, 0x0, 0x0)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:381 +0x91
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ReadDataApply(0xc420566880, 0xc420522fa0, 0xc420523030, 0x0, 0x0)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:565 +0x4e
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: reflect.Value.call(0xc42073a180, 0xc4201ca4a8, 0x13, 0x510d6ea, 0x4, 0xc420049f20, 0x3, 0x3, 0x0, 0x0, ...)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/go/src/reflect/value.go:434 +0x91f
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: reflect.Value.Call(0xc42073a180, 0xc4201ca4a8, 0x13, 0xc42036f720, 0x3, 0x3, 0x0, 0x0, 0x0)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/go/src/reflect/value.go:302 +0xa4
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: net/rpc.(*service).call(0xc42010f7c0, 0xc42010f780, 0xc420015f10, 0xc420570200, 0xc4205669c0, 0x4284d40, 0xc420522fa0, 0x16, 0x4284d80, 0xc420523030, ...)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/go/src/net/rpc/server.go:387 +0x144
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: created by net/rpc.(*Server).ServeCodec
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/go/src/net/rpc/server.go:481 +0x404
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: panic: runtime error: invalid memory address or nil pointer dereference
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x354d566]
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: goroutine 81 [running]:
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud.(*ServiceClient).ServiceURL(0x0, 0xc42075b3a0, 0x1, 0x1, 0xc4207c16b0, 0x0)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud/service_client.go:37 +0x26
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks.rootURL(0x0, 0x0, 0xc42075b470)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/urls.go:10 +0x5f
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks.listURL(0x0, 0x88, 0x4f4d4c0)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/urls.go:18 +0x2b
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks.List(0x0, 0x7ad1680, 0xc4201ed200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go:42 +0x6e
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/builtin/providers/openstack.dataSourceNetworkingNetworkV2Read(0xc420320540, 0x4cb73a0, 0xc4205e1c20, 0x1, 0x0)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/openstack/data_source_openstack_networking_network_v2.go:69 +0x28c
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc4203664e0, 0xc4204756a0, 0x4cb73a0, 0xc4205e1c20, 0xc4205bc980, 0xc420520d01, 0x0)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:252 +0xbb
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc4202d0a80, 0xc4201c2640, 0xc4204756a0, 0x7f968fc38e10, 0x0, 0x0)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:381 +0x91
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ReadDataApply(0xc420566880, 0xc420522cc0, 0xc420522f90, 0x0, 0x0)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:565 +0x4e
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: reflect.Value.call(0xc42073a180, 0xc4201ca4a8, 0x13, 0x510d6ea, 0x4, 0xc42071ff20, 0x3, 0x3, 0x0, 0x0, ...)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/go/src/reflect/value.go:434 +0x91f
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: reflect.Value.Call(0xc42073a180, 0xc4201ca4a8, 0x13, 0xc420373720, 0x3, 0x3, 0x0, 0x0, 0x0)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/go/src/reflect/value.go:302 +0xa4
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: net/rpc.(*service).call(0xc42010f7c0, 0xc42010f780, 0xc420015f10, 0xc420570200, 0xc420474e40, 0x4284d40, 0xc420522cc0, 0x16, 0x4284d80, 0xc420522f90, ...)
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/go/src/net/rpc/server.go:387 +0x144
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: created by net/rpc.(*Server).ServeCodec
2017/05/16 12:43:10 [DEBUG] plugin: terraform-0.9.5: 	/opt/go/src/net/rpc/server.go:481 +0x404
2017/05/16 12:43:10 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.openstack_networking_network_v2.internal: unexpected EOF
2017/05/16 12:43:10 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.openstack_networking_network_v2.external: unexpected EOF
2017/05/16 12:43:10 [ERROR] root: eval: *terraform.EvalSequence, err: data.openstack_networking_network_v2.internal: unexpected EOF
2017/05/16 12:43:10 [DEBUG] plugin: /home/user/.local/bin/terraform-0.9.5: plugin process exited
2017/05/16 12:43:10 [TRACE] [walkRefresh] Exiting eval tree: data.openstack_networking_network_v2.internal
2017/05/16 12:43:10 [ERROR] root: eval: *terraform.EvalSequence, err: data.openstack_networking_network_v2.external: unexpected EOF
2017/05/16 12:43:10 [TRACE] [walkRefresh] Exiting eval tree: data.openstack_networking_network_v2.external
2017/05/16 12:43:10 [DEBUG] dag/walk: upstream errored, not walking "provider.openstack (close)"
2017/05/16 12:43:10 [WARN] plugin: error closing client during Kill: connection is shut down
2017/05/16 12:43:10 [DEBUG] plugin: waiting for all plugin processes to complete...



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Panic Output
[crash.log](https://gist.githubusercontent.com/val-scality/65cd38a4d4be1d081d98f156debdea51/raw/186da09efce424542626f6da534bedfa40acb039/crash.log)

### Expected Behavior
Plan should have worked.

### Actual Behavior
Terraform crashed.

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
The OpenStack version is from Platform9. Everything else works fine (instances, volumes, security groups, keys, …).

Note that custom "p9_variables" are set via environment (export TF_VAR_p9_whatever) and work fine.

**Comment by val-scality** [comment]
Obviously, both "tenantnetwork1" and "externalnetwork1" already exist in OpenStack.

**Comment by jtopjian** [comment]
@val-scality Thanks for reporting this. This one might be a little difficult to debug since it's a vendor-specific OpenStack environment, but I'll try my best.

Can you provide the output of a `plan` with the `TF_LOG=DEBUG OS_DEBUG=1` environment variables set?

**Comment by val-scality** [comment]
Hello, thanks for your time!

Of course, here it is: [gist](https://gist.githubusercontent.com/val-scality/c82adfef527572510635a5438b8056da/raw/3141951a4a3bdbfa18052df5d345b01377a6cf34/plan.log%2520DEBUG).

Up to now, I haven't had any issue with the Platform9 OpenStack API, I guess it's a "varnish" OpenStack API; but if you need me to run anything I'll be glad to help you out.

**Comment by jtopjian** [comment]
@val-scality Thanks!

Looks like it's crashing during a network `List` call. This makes sense, because that's what the network data source implements. So that's good, because we've localized it to that.

Can you try running the following and let me know if it works?

```shell
$ token=$(openstack token issue -c id -f value)
$ curl -s -H "X-Auth-Token:$token" http://YOUR_ENDPOINT:9696/v2.0/networks?name=default\&status=ACTIVE | python -mjson.tool
```

**Comment by val-scality** [comment]
@jtopjian well it returns an empty list:
```bash
> curl -L -s -H "X-Auth-Token: $token" https://MY_NEUTRON_ENDPOINT/neutron/v2.0/networks?name=default\&status=ACTIVE | python -mjson.tool
{
    "networks": []
}
```

But if I remove the query parameters, it works as expected:
```bash
> curl -L -s -H "X-Auth-Token: $token" https://MY_NEUTRON_ENDPOINT/neutron/v2.0/networks | python -mjson.tool
{
    "networks": [
        {
            "admin_state_up": true,
            "id": "6655b95d-297f-415e-b4b2-8d2eff2c4d36",
            "mtu": 0,
            "name": "externalnetwork1",
            "router:external": true,
            "shared": true,
            "status": "ACTIVE",
            "subnets": [
                "a92bf38c-ca9c-4d40-87e3-7482dd24f1f3"
            ],
            "tenant_id": "88e8aa0220d64b218f2854a613a7ebbb"
        },
        {
            "admin_state_up": true,
            "id": "a8b5b41e-8478-483c-b348-ffae653414c2",
            "mtu": 0,
            "name": "tenantnetwork1",
            "router:external": false,
            "shared": true,
            "status": "ACTIVE",
            "subnets": [
                "682b5a1f-d5a5-46db-bd84-e67f66323d1d"
            ],
            "tenant_id": "88e8aa0220d64b218f2854a613a7ebbb"
        }
    ]
}
```

**Comment by jtopjian** [comment]
@val-scality Ah, interesting.

So that's the issue: for some reason your Neutron service isn't respecting the `List` query parameters. There are two things to do there:

1. Definitely report a bug to Platform9.
2. You could try to play around with `curl` and see if you can get some type of query to work. [These](https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/networks/requests.go#L19-L30) are the valid query parameters.

In the meantime, I can look at modifying the Network data source to support multiple results. This might take a week or two, though.

**Comment by jtopjian** [comment]
@val-scality Actually, hold on. I just noticed the curl query is incorrect. Try this:

```shell
curl -L -s -H "X-Auth-Token: $token" https://MY_NEUTRON_ENDPOINT/neutron/v2.0/networks?name= externalnetwork1\&status=ACTIVE | python -mjson.tool
```

Note the `name=externalnetwork1` part. :)

**Comment by val-scality** [comment]
@jtopjian well it works:

```bash
> curl -L -s -H "X-Auth-Token: $token" https://MY_NEUTRON_ENDPOINT/neutron/v2.0/networks?name=externalnetwork1\&status=ACTIVE | python -mjson.tool
{
    "networks": [
        {
            "admin_state_up": true,
            "id": "6655b95d-297f-415e-b4b2-8d2eff2c4d36",
            "mtu": 0,
            "name": "externalnetwork1",
            "router:external": true,
            "shared": true,
            "status": "ACTIVE",
            "subnets": [
                "a92bf38c-ca9c-4d40-87e3-7482dd24f1f3"
            ],
            "tenant_id": "88e8aa0220d64b218f2854a613a7ebbb"
        }
    ]
}
```

**Comment by jtopjian** [comment]
OK! That's good news. 

Can you now run:

```shell
$ openstack catalog list
```

And see if the Neutron endpoint you're querying matches what Keystone has in its catalog?

**Comment by val-scality** [comment]
Well I'm stupid.

I noticed that I have 2 regions available thanks to the output of your command. I added a region parameter in the "openstack_networking_network_v2" data source and it worked.
I don't know why I forgot it here, I set the region in every other single resource…

Thanks a lot for the debug! This issue is resolved :-)

**Comment by jtopjian** [comment]
That's awesome news. I'm glad it's working :)
