### ISSUE TITLE
core: crash in InstanceDiff.GetDestroy

### ISSUE THREAD

**Issue by rkroboth** [hashicorp/terraform#14792]
Running 0.9.5 to spin up some AWS services this morning, I encountered the following invalid memory address or nil pointer dereference crash. Thx!
[crash.txt](https://github.com/hashicorp/terraform/files/1025552/crash.txt)

**Comment by stack72** [comment]
Hi @rkroboth 

Please could you post a terraform config that allows us to recreate this?

Thanks 

Paul

**Comment by stack72** [comment]
FYI, relevant crash details are:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x977527]

goroutine 31106 [running]:
github.com/hashicorp/terraform/terraform.(*InstanceDiff).GetDestroy(0x0, 0x52ad500)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/diff.go:578 +0x27
github.com/hashicorp/terraform/backend/local.(*CountHook).PreApply(0xc420690640, 0xc4201bdae0, 0xc421006690, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/hook_count.go:50 +0xa8
github.com/hashicorp/terraform/terraform.(*EvalApplyPre).Eval.func1(0x7af1060, 0xc420690640, 0xc42124d400, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_apply.go:118 +0x4f
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).Hook(0xc421123340, 0xc42169fc40, 0xc420ec9b00, 0x2b)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:61 +0x6c
github.com/hashicorp/terraform/terraform.(*EvalApplyPre).Eval(0xc42169faa0, 0x7af2c20, 0xc421123340, 0x2, 0x2, 0x510e306, 0x4)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_apply.go:119 +0xe0
github.com/hashicorp/terraform/terraform.EvalRaw(0x7abfc80, 0xc42169faa0, 0x7af2c20, 0xc421123340, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc42169fb00, 0x7af2c20, 0xc421123340, 0x2, 0x2, 0x510e306, 0x4)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0xc1
github.com/hashicorp/terraform/terraform.EvalRaw(0x7ac05c0, 0xc42169fb00, 0x7af2c20, 0xc421123340, 0x2b, 0x0, 0x0, 0x2b)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc420ec9920, 0x7af2c20, 0xc421123340, 0x2, 0x2, 0x510e306, 0x4)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x4c

```

**Comment by rkroboth** [comment]
We have a large configuration, but this attached portion 
[tfconfig.txt](https://github.com/hashicorp/terraform/files/1025709/tfconfig.txt)
seems to be the relevant section... it's the portion I was trying to spin up in this case. It's an autoscaling group with some ec2 instances.

**Comment by apparentlymart** [comment]
Hmm... first quick look at the code suggests that somehow we are getting to apply with a `nil` instance diff.

Unfortunately a shallow `nil` check doesn't seem like it will suffice here since this is blowing up in the code that keeps a tally of what was created and destroyed to produce the stats at the end, so if we just default to something we'll likely throw off the stats and produce weird results.

So we will need to go a bit deeper here and figure out how we're ending up with a nil diff in the first place.
