### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by jrigassio** [hashicorp/terraform#14842]
Version 0.9.5
### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

https://gist.github.com/jrigassio/a64a868919a3f4dea2f039eb615c1b12

**Comment by jbardin** [comment]
The relevant part of the logs:

```
2017/05/25 16:49:21 [DEBUG] plugin: terraform: panic: runtime error: index out of range
2017/05/25 16:49:21 [DEBUG] plugin: terraform: 
2017/05/25 16:49:21 [DEBUG] plugin: terraform: goroutine 82 [running]:
2017/05/25 16:49:21 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/github.parseTwoPartID(0xc4204e6de0, 0x10, 0xc42024e230, 0x70, 0x68, 0x5bb65e0)
2017/05/25 16:49:21 [DEBUG] plugin: terraform: 	/private/tmp/terraform-20170511-51692-992qlr/terraform-0.9.5/src/github.com/hashicorp/terraform/builtin/providers/github/util.go:46 +0x9e
2017/05/25 16:49:21 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/github.resourceGithubTeamRepositoryRead(0xc42024e230, 0x4e824c0, 0xc4203ba080, 0x0, 0x87ae080)
2017/05/25 16:49:21 [DEBUG] plugin: terraform: 	/private/tmp/terraform-20170511-51692-992qlr/terraform-0.9.5/src/github.com/hashicorp/terraform/builtin/providers/github/resource_github_team_repository.go:61 +0x99
2017/05/25 16:49:21 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc4202acc00, 0xc4201c0b40, 0x4e824c0, 0xc4203ba080, 0xc420478b20, 0xc4201cd501, 0x0)
2017/05/25 16:49:21 [DEBUG] plugin: terraform: 	/private/tmp/terraform-20170511-51692-992qlr/terraform-0.9.5/src/github.com/hashicorp/terraform/helper/schema/resource.go:314 +0x21d
2017/05/25 16:49:21 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc42004f110, 0xc4201c0af0, 0xc4201c0b40, 0x9b5f000, 0x0, 0x0)
2017/05/25 16:49:21 [DEBUG] plugin: terraform: 	/private/tmp/terraform-20170511-51692-992qlr/terraform-0.9.5/src/github.com/hashicorp/terraform/helper/schema/provider.go:267 +0x91
2017/05/25 16:49:21 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4204efbe0, 0xc4204e6c10, 0xc4204e6e80, 0x0, 0x0)
2017/05/25 16:49:21 [DEBUG] plugin: terraform: 	/private/tmp/terraform-20170511-51692-992qlr/terraform-0.9.5/src/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
2017/05/25 16:49:21 [DEBUG] plugin: terraform: reflect.Value.call(0xc4202adbc0, 0xc42000c398, 0x13, 0x5d0d314, 0x4, 0xc4205cdf20, 0x3, 0x3, 0x10383ec, 0xc420692738, ...)
```

**Comment by stack72** [comment]
Hi @jrigassio 

Please can you post a sample of the terraform configuration that caused this for you? This will help me try and debug the issue

Thanks

Paul
