### ISSUE TITLE
backend/s3: crash in s3.Get

### ISSUE THREAD

**Issue by simondh** [hashicorp/terraform#14927]
terraform v0.9.6

terraform apply  - 

 main.tf in attached ZIP.

has worked before, but I got confused about an S3 backend. Did a destroy on everything, then started again. Crashes every time, even after reboot.

OS X 10.12.5. iTerm2. All AWS in eu-west-2 (London)

[Archive.zip](https://github.com/hashicorp/terraform/files/1038447/Archive.zip)

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- dnsimple_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
terraform.tfstate attached

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
`crash.log`. in zip file

### Expected Behavior
What should have happened?
should create a simple ASG & ELB, from a book.

### Actual Behavior
Crash every time

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
All very standard, following book 'terraform up and running'

**Comment by grubernaut** [comment]
Panic output: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x46f62aa]

goroutine 158 [running]:
github.com/hashicorp/terraform/backend/remote-state/s3.(*RemoteClient).Get(0xc420053340, 0x11, 0x11, 0x18)
        /private/tmp/terraform-20170525-36317-scr3s4/terraform-0.9.6/src/github.com/hashicorp/terraform/backend/remote-state/s3/client.go:64 +0x11a
github.com/hashicorp/terraform/state/remote.(*State).RefreshState(0xc420781d20, 0x100ed72, 0xc420554140)
        /private/tmp/terraform-20170525-36317-scr3s4/terraform-0.9.6/src/github.com/hashicorp/terraform/state/remote/state.go:33 +0x37
github.com/hashicorp/terraform/state.(*BackupState).RefreshState(0xc42057b890, 0x5e21a2f, 0x7)
        /private/tmp/terraform-20170525-36317-scr3s4/terraform-0.9.6/src/github.com/hashicorp/terraform/state/backup.go:21 +0x33
github.com/hashicorp/terraform/backend/local.(*Local).context(0xc4205c5680, 0xc42009e420, 0x2, 0x2, 0x4, 0xc420554140, 0x2)
        /private/tmp/terraform-20170525-36317-scr3s4/terraform-0.9.6/src/github.com/hashicorp/terraform/backend/local/backend_local.go:31 +0x97
github.com/hashicorp/terraform/backend/local.(*Local).opApply(0xc4205c5680, 0x88caa20, 0xc4205540c0, 0xc42009e420, 0xc420473ce0)
        /private/tmp/terraform-20170525-36317-scr3s4/terraform-0.9.6/src/github.com/hashicorp/terraform/backend/local/backend_apply.go:50 +0x1fd
github.com/hashicorp/terraform/backend/local.(*Local).(github.com/hashicorp/terraform/backend/local.opApply)-fm(0x88caa20, 0xc4205540c0, 0xc42009e420, 0xc420473ce0)
        /private/tmp/terraform-20170525-36317-scr3s4/terraform-0.9.6/src/github.com/hashicorp/terraform/backend/local/backend.go:245 +0x52
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc4205c5680, 0xc4209e6eb0, 0xc4209e6ea0, 0x88caa20, 0xc4205540c0, 0xc42009e420, 0xc420473ce0)
        /private/tmp/terraform-20170525-36317-scr3s4/terraform-0.9.6/src/github.com/hashicorp/terraform/backend/local/backend.go:265 +0x9a
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
        /private/tmp/terraform-20170525-36317-scr3s4/terraform-0.9.6/src/github.com/hashicorp/terraform/backend/local/backend.go:266 +0x192
```
