### ISSUE TITLE
Terraform crash during terraform plan, apply

### ISSUE THREAD

**Issue by matthieudolci** [hashicorp/terraform#15135]
### Terraform Version

Terraform v0.9.6

### Affected Resource(s)

No idea

### Panic Output

https://gist.github.com/matthieudolci/03087cbd6b9c01208fa7272cf020e810

Hello,

After an upgrade of terraform, we decided to work on a "old" project and when trying to do a terraform plan or apply terraform crashes. The version of terraform used to create the infra was 0.9.1

Thanks

**Comment by radeksimko** [comment]
@matthieudolci thank you for taking time to report this crash.

Here's the important snippet from the attached panic output for anyone who'll pick this up:

```
2017/06/06 16:33:02 [DEBUG] Interpolating computed list element attribute ingress (1)
panic: runtime error: index out of range

goroutine 17902 [running]:
github.com/hashicorp/terraform/flatmap.expandArray(0xc42045ced0, 0xc42045d253, 0x7, 0x9, 0xc420f9d7c8, 0xc421d30d01)
	/opt/gopath/src/github.com/hashicorp/terraform/flatmap/expand.go:110 +0x70c
github.com/hashicorp/terraform/flatmap.Expand(0xc42045ced0, 0xc42045d253, 0x7, 0x2, 0x2)
	/opt/gopath/src/github.com/hashicorp/terraform/flatmap/expand.go:35 +0x41f
github.com/hashicorp/terraform/terraform.(*Interpolater).interpolateComplexTypeAttribute(0xc420fe2c80, 0xc42045d253, 0x7, 0xc42045ced0, 0x7d25b00, 0xc421d30f00, 0x9, 0x44ee740, 0xc420360390)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/interpolate.go:663 +0x206
github.com/hashicorp/terraform/terraform.(*Interpolater).computeResourceVariable(0xc420fe2c80, 0xc421d314f8, 0xc4206eeb40, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/interpolate.go:468 +0xb67
github.com/hashicorp/terraform/terraform.(*Interpolater).valueResourceVar(0xc420fe2c80, 0xc421d314f8, 0xc42045d232, 0x28, 0xc4206eeb40, 0xc420aac750, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/interpolate.go:251 +0x7c
github.com/hashicorp/terraform/terraform.(*Interpolater).Values(0xc420fe2c80, 0xc421dab4f8, 0xc42045d2c0, 0x0, 0x0, 0xc421d31550)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/interpolate.go:86 +0x699
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).Interpolate(0xc421234620, 0xc4206ee9c0, 0x0, 0x0, 0xc421092000, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:298 +0xe8
github.com/hashicorp/terraform/terraform.(*EvalWriteOutput).Eval(0xc421031e40, 0x7ca0f60, 0xc421234620, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_output.go:48 +0x96
github.com/hashicorp/terraform/terraform.EvalRaw(0x7c6e940, 0xc421031e40, 0x7ca0f60, 0xc421234620, 0xc4200160f0, 0x2, 0xc421ba1000, 0x32)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc421031e60, 0x7ca0f60, 0xc421234620, 0x2, 0x2, 0xc420b57210, 0xb)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0xc1
github.com/hashicorp/terraform/terraform.EvalRaw(0x7c6e5c0, 0xc421031e60, 0x7ca0f60, 0xc421234620, 0x32, 0x0, 0x0, 0x32)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc42045d7a0, 0x7ca0f60, 0xc421234620, 0x2, 0x2, 0xc420b571f0, 0xb)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x4c
github.com/hashicorp/terraform/terraform.EvalRaw(0x7c6e380, 0xc42045d7a0, 0x7ca0f60, 0xc421234620, 0x4795ca0, 0xc421bb087c, 0x44ee740, 0xc421bb0900)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.Eval(0x7c6e380, 0xc42045d7a0, 0x7ca0f60, 0xc421234620, 0xc42045d7a0, 0x7c6e380, 0xc42045d7a0, 0x200000003)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:34 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x4d5c180, 0xc42127a100, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:126 +0xd4d
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc42026f340, 0x4d5c180, 0xc42127a100, 0xc420d087c0)
	/opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x392
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:310 +0x9ca
```

**Comment by apparentlymart** [comment]
Hi @matthieudolci,

This looks like the same issue as #15300, in which case there's a fix in #15390 which should be included in the next release. Sorry for the crash, and thanks for reporting it!

**Comment by matthieudolci** [comment]
@apparentlymart thanks a lot i will try that, we just got the same issue with another state file and this one generated by 0.9.8

**Comment by matthieudolci** [comment]
Confirmed that 0.10.0 solve the issue
