### ISSUE TITLE
Terraform crash

### ISSUE THREAD

**Issue by bennythejudge** [hashicorp/terraform#15334]
### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

Hi,
I had a crash.
Is there any way to share privately source files etc?
I am afraid to breach various NDAs I am subject to otherwise.

```
15:51 $ tf apply
[...]
aws_route_table.subnet_management_route_to_nat: Refreshing state... (ID: rtb-6ae1940c)
panic: runtime error: index out of range

goroutine 1687 [running]:
github.com/hashicorp/terraform/flatmap.expandArray(0xc4209c8210, 0xc4203555e0, 0x6, 0x8, 0xc420bbe708, 0xc420b18d01)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/flatmap/expand.go:110 +0x70c
github.com/hashicorp/terraform/flatmap.Expand(0xc4209c8210, 0xc4203555e0, 0x6, 0x2, 0x2)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/flatmap/expand.go:35 +0x41f
github.com/hashicorp/terraform/terraform.(*Interpolater).interpolateComplexTypeAttribute(0xc420322140, 0xc4203555e0, 0x6, 0xc4209c8210, 0x8e51dc0, 0xc420b18f00, 0x8, 0x0, 0x0)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/terraform/interpolate.go:663 +0x206
github.com/hashicorp/terraform/terraform.(*Interpolater).computeResourceVariable(0xc420322140, 0xc420b194f8, 0xc42070a3c0, 0x0, 0x0, 0x0)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/terraform/interpolate.go:468 +0xb67
github.com/hashicorp/terraform/terraform.(*Interpolater).valueResourceVar(0xc420322140, 0xc420b194f8, 0xc4203555c2, 0x24, 0xc42070a3c0, 0xc4209c8810, 0xc420c32c00, 0x0)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/terraform/interpolate.go:251 +0x7c
github.com/hashicorp/terraform/terraform.(*Interpolater).Values(0xc420322140, 0xc4206b54f8, 0xc4203556b0, 0x0, 0xc420b19550, 0x1091595)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/terraform/interpolate.go:86 +0x699
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).Interpolate(0xc4201547e0, 0xc42070a240, 0x0, 0x0, 0xc420410000, 0x0)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:298 +0xe8
github.com/hashicorp/terraform/terraform.(*EvalWriteOutput).Eval(0xc420a6e500, 0x8dc7cc0, 0xc4201547e0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/terraform/eval_output.go:48 +0x96
github.com/hashicorp/terraform/terraform.EvalRaw(0x8d8f940, 0xc420a6e500, 0x8dc7cc0, 0xc4201547e0, 0xc420016140, 0x2, 0xc4209c8780, 0x2b)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc420a6e520, 0x8dc7cc0, 0xc4201547e0, 0x2, 0x2, 0x6149555, 0x4)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0xc1
github.com/hashicorp/terraform/terraform.EvalRaw(0x8d8f5c0, 0xc420a6e520, 0x8dc7cc0, 0xc4201547e0, 0x2b, 0x0, 0x0, 0x2b)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc4209c8510, 0x8dc7cc0, 0xc4201547e0, 0x2, 0x2, 0x6149555, 0x4)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x4c
github.com/hashicorp/terraform/terraform.EvalRaw(0x8d8f380, 0xc4209c8510, 0x8dc7cc0, 0xc4201547e0, 0x567ac80, 0xc4208d921c, 0x53ce560, 0xc4208d9240)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.Eval(0x8d8f380, 0xc4209c8510, 0x8dc7cc0, 0xc4201547e0, 0xc4209c8510, 0x8d8f380, 0xc4209c8510, 0xc4204d9040)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/terraform/eval.go:34 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x5c5cee0, 0xc42015a600, 0x0, 0x0)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/terraform/graph.go:126 +0xd4d
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc420cfb260, 0x5c5cee0, 0xc42015a600, 0xc42071cb40)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x392
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/dag/walk.go:310 +0x9ca



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by apparentlymart** [comment]
Hi @bennythejudge! Sorry for this crash.

From the stack trace, it looks like what happened here is that there was a disagreement between the recorded number of elements in an array (saved as a special `.#` entry in the state) and the _actual_ number of elements, with the latter being higher.

It's unclear how such a thing can happen, but I think we can make it more resilient to this situation so that it won't crash in this case, since Terraform should be able to "self-repair" by adjusting the count.

Thanks for reporting this!

**Comment by jbardin** [comment]
@apparentlymart: this has the same stack trace as #15300, where we have more info to go by. I'm going to close this as a dupe for now.
