### ISSUE TITLE
Terraform crash - Terraform v0.10.0 

### ISSUE THREAD

**Issue by giladlevy7** [hashicorp/terraform#15544]
PROVIDER ISSUES

PLEASE NOTE: Terraform has split out the builtin Providers into their own repositories. For any Provider issues, please open all issues and pull requests in the corresponding repository. An index of supported Providers can be found here:

https://github.com/terraform-providers
All other issues (that appear to affect multiple or all providers) may be an issue with Terraform's core, and should be opened here.

Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

Terraform Version

Run terraform -v to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.10.0

Expected Behavior

What should have happened?

Terraform should apply the resource with the provider. If there is a problem in the provider then it should've warn me and not crash (I believe).

Actual Behavior

What actually happened?

It crashed. attaching the log file.

Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

terraform apply

Thanks,
Gilad

[crash.log.zip](https://github.com/hashicorp/terraform/files/1144920/crash.log.zip)

**Comment by stack72** [comment]
Relevant lines of panic:

```
2017/07/13 14:12:38 [DEBUG] apply: spotinst_group_azure.sidekiq: executing Apply
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: panic: interface conversion: interface {} is nil, not string
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: 
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: goroutine 12 [running]:
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: github.com/spotinst/spotinst-terraform-provider.buildAzureGroupOpts(0xc4201c36c0, 0x0, 0x0, 0x0)
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: 	/Users/giladlevy/Development/go/src/github.com/spotinst/spotinst-terraform-provider/resource_spotinst_group_azure.go:1099 +0x39ab
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: github.com/spotinst/spotinst-terraform-provider.resourceSpotinstAzureGroupCreate(0xc4201c36c0, 0x17922c0, 0xc420102370, 0x24, 0x1c06c40)
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: 	/Users/giladlevy/Development/go/src/github.com/spotinst/spotinst-terraform-provider/resource_spotinst_group_azure.go:474 +0x58
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc42038e780, 0xc420017040, 0xc42036dae0, 0x17922c0, 0xc420102370, 0x1, 0x28, 0xc4203e21e0)
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: 	/Users/giladlevy/Development/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:192 +0x449
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4201c32d0, 0xc420016ff0, 0xc420017040, 0xc42036dae0, 0x1d81000, 0x0, 0x0)
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: 	/Users/giladlevy/Development/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0x9b
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc42036cec0, 0xc42036d540, 0xc4203be940, 0x0, 0x0)
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: 	/Users/giladlevy/Development/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: reflect.Value.call(0xc420294600, 0xc4201080e8, 0x13, 0x17fe94e, 0x4, 0xc42003bf20, 0x3, 0x3, 0x0, 0x0, ...)
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: 	/usr/local/go/src/reflect/value.go:434 +0x91f
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: reflect.Value.Call(0xc420294600, 0xc4201080e8, 0x13, 0xc42002bf20, 0x3, 0x3, 0x0, 0x0, 0x0)
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: net/rpc.(*service).call(0xc42010d6c0, 0xc42010d680, 0xc420107f20, 0xc42020a180, 0xc42010ae60, 0x16c0c80, 0xc42036d540, 0x16, 0x16c0cc0, 0xc4203be940, ...)
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: 	/usr/local/go/src/net/rpc/server.go:387 +0x144
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: created by net/rpc.(*Server).ServeCodec
2017/07/13 14:12:38 [DEBUG] plugin: terraform-provider-spotinst: 	/usr/local/go/src/net/rpc/server.go:481 +0x404

```
