### ISSUE TITLE
helper/schema: Crash in ConfigFieldReader.readMap

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#15729]
_This issue was originally opened by @jlindsey in https://github.com/terraform-providers/terraform-provider-aws/issues/928 and migrated here as it appears to be core-related._

<hr>

### Terraform Version
v0.9.8

### Affected Resource(s)

- aws_efs_file_system
- aws_efs_mount_target

### Terraform Configuration Files
```
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.72
Comment: https://keybase.io/crypto

wcBMA9X0O2Qy6nfzAQf8D9MeAYmhtxGi8bDLysoYQfxHvPDPvlVLBvGAdxY5BFdE
RQq56IZP4/+qqYFPFKyRf73IiygRb5pPWxEvjaVsA8LFl9SzfVCO+LsraCri+O51
XpebAfFvPSWRjNjRq7pts2y4oBWifkCOrGjYZCPXWzdTj0ZPEMCD/sBJHcL6e+lA
Qo5Y+wY9r4rYjF1h0M3XArwKt6vjHcFLe9O6oMOOEL2RbvGrsBZqvPrLoweqTJMo
t6FX5PIdKS4U29zrrkOeerEPe1+HsBIAyDlda1bTEcezOGkjRV7KzIID1XpGTK3y
leyh2lM0aCPWcE4B/HzvPxmyYVrr2cwTg0VNX97CqcHBTANgrwxC6x82gQEP/31e
Goloe2sued01Zgbj0zx7NinwRPVgJEHhuMr1yZw8jgJJHJb/NKYL/rdcHE3XourR
pL0foHcVphszu+iyngdb3Qg4ScdzeKtcBzR5icInske1qphKGGJECR5LD/qXVq2M
1q+SgRTJlClH/78YsxRjSNX2P+MNFwRWkpLqzb5N2PlwRJyjOZ2hCKr13UYPdGXe
7SHtHwEzrbvIl5l+Mqn7WJq3qcb5diXQru+1bodiF3Kz90F2Zh/xwezl+T3gLRjP
gHLkzK8LiFpCKXUbahaWK4J9LrE0sOLCdBrlgrZfvQMqXOqya8qwpOBhnfyi9tHB
YwfiqHDw2Bam88FeVV706hI0gMFcXFGbRkuZNk2Cr06DCq8+4NuDo1+/yuj6I5Q+
rASToO6ybaV4I6O8+ApXULT6QVAC4MUirJMHpniZYTPEo1RxZBYV7wCFuMNA78Dg
UDtCGaLnpPsNymdnx+k0fv2W51GN3g0h9tV/0NFO5bStDwhbkbe+mlxK9+HyJbVq
qds0Gewiz5fzZYyOipU3XF3XHYWVZEp3pKqzTH0jE6gu4lNoRit90adW3iTwVvvj
6YJAOheO/8BMo0t5ZZYmrqQoLA7W5YCfbmBZQsN6WV1dlPkHyufSUlX8+xougqEk
Gy2DhnG7mKzDsBwWoxKnnilECltB3ZTit8tk1VEY0scMAVtC7D3ZjH3wjf/mGkSD
qk1ppS7vYfx/rGit1ABYas729gJBXz4Sd8xEUN41kvCYZmr2aQK60AWcCs3P4qXr
ePD0RrhIb1jRSshIXzH5VWsIlIjsu/LjKVyH2E2ursPmvRDtI3jLWlTM0AFPvVNc
Fc85DegeBYMaQ2FQI/dNPJVr5mRAskJgjIHDysI71aaP3/CK1WDR+pJtQuWy+Kh7
j2rnxFTZ09X7NR5d8tlKj/tCR3V7c0InVrC+UqpnIglu3uW770fp5kBHwiiCGCE7
WJwJYp5LIv4ja30A020YIR9agGl9JQ0xByjXWxju3RCEEUtAHZBzft6GClOyHsld
v10AzRMgBL+btXCfUIHdP9SlgW8EXVc91WSg/AVo6FtYQOpeHzFzWbcnLN6j5zX9
9zVzTYTwnExvhZ6YmM+fYozhWCA5rrjy8ru++z9lBi2yfVhkjs+UuZngtthigvnc
aiK15vmOfxSkoYqWwDNNUq63JzjGDKGWrgSA5z4K0orW3CeQEwOsNIizKI5nnKKu
htjfaCwwbFzcwCsM57jleuTwqyrOxq5BQtrxDdsE68OvV/iMnYUASzLC8q5oj2Uf
Dfg/gzk2EUCAfAp0g7Qe40SeGoIQM/TacWnIHCfE7H8PcJ9vpkHiSBkgKlbiM3yu
RXIfARhduTRR5zWKLw5X/yYcgw22eeG1LVb6dTsDNtlWbRdAj1OEdKroWwL9jkVZ
AMq8hXplkoRkbiif0VTQw5BHvYGGIXX0sbJf1v5LqgFn13Q7hUYn4ENfemhAXGo2
LgFrjHEz7aOX6rgxUkL73ZSs4L52Zd1J8EbkvmapDOjcAtNTfuPC52kG9/CAPC2c
jXM6T7D9qeHW8/BYunuTKQpfSVwpYHYauZ/F0fW307T8vwXUZFoZAm1gzIaTDV3m
1U9grbBywKTe28qU+TEHWIvpEtrsJBRFMGN5chbY23X7ff/76NmKyAE+mRCfrFVO
vbteF+8EnG55Idua/k+s4chbGAbL/a0yDKJJoSuMEcmGGYq1qH13xcM/+2GKl5zZ
KpJP1AjATLt5yIVKS1dzqE5SlrCW7+d6IoUd6kl4W2DFNbylUInN6PWZVFDQLTo1
GS76HrE3b3v3OI4K1d/br36vrDzL3PZA+DNRdpwWZnyFgBfWOL1c2U3bwYbR5fMW
iYxCSRoExOGJ1XqpaOU5a+Hdv4FFqOyi5HH5z2x9Ju1bQ2Fzpmoe1b6BUVl7rdgf
6PE6VqcLh8szsW0HPpuMMwvUV8DsLd1OQy1t6QQGpGIGBTcHFqRNRvENyqQzWl/1
R38OiC/sf77OcX1/2aq1mi9qtoe33Bwzm8k6vCJUIZGGPasGnlSDgUB8HqH8W4+x
j/izdb5LmetJrk9QDzv1K3oORQd2UR4wipz0BgoqO7/Vx7KkxlIQNfL1nSIRQPMP
N0/8w+AHoq60+oMYmLFrkGEe1lGPXth03XTLQQMsHj/OlAxEKswAhBbn77QdV7oc
1bbGsi6vRGwr9LnlQglaVJoiSzad6mUqDx3rXSNtOcAC/D6O0sjE2/2l0N+5hnU/
VsY+7HLS2J2npnScT4279HNR/bKj1Mxur/NrHB1puX8NGAMa10/hRdQ9DLiJ5fDF
qEYqb+frTByavwuaogkB0x0OCbaTBYVG0prMI1NosWCcUkibLGb13Un7pzkzG37f
IFlaft1i/FJ1yT+kw2r/EoNuiP+HqjPcVg1+i5ktVixzatU2NEQamUQUMRRykMDb
Re/dbiSu+eCZz7mbwJCk9vmDZeL4nB8DmTpmFDvp6O6IFgeZnFN6cQO+ajePAbqi
jTVNaEHXCpMK6YFusXOoKaFVxCDl0en7nL8H8O0m0Mc08t1h2jzlng7l/rP6rxue
YZlsL0Ct3Qrw6JiMevhJ1B3Bu69qrisj4WdX9flHGesAXYTu1btAfJ3X6DggaWlM
oME7Cb/SgzRk4dW2zQGU48CRxCBglYGHCRTI9/KtZEgpFxMFJkpGU7diWkh/wkMh
omE242l3xKvh9KOikKSb4XDa4o6nWwzZrRCm0G6M03xgektrSRJ/X4SnLIvu5WPH
bPA/TlKdH5nYODR7Aw7NwZt1l3wnTU4tFAD8hxrYR5SuJJk1YrEPUv5+pLJzgO/B
Ug3AlQKkDg4GdO02vdF2qdhPmYB3a8kyhvh1T2u/g2NyCJhX+u/MScT1BSDzhOPK
VXr0AHIbDFr5W5OhNHkZWSwgdAiKw8B+VWLH8koL1WWJst5x9V/YzSc1xcPnHWGy
v/LpdJmmsDYiJkv/jfapzO8ov/XLDdZJqxF49cR88km5R/v69ruD26SOgtSA58f6
WynkLmxlADMz1Rz2/A48yTfxMYtHuEcb4MhX4D5yE3aSfeqIlA1tRJ98iUa+g3ET
qzdU5p7edpL+EcZXWafRPRrGFDQE+l/ApZgAYk+PhA/azFa3l2hJlxfIjSqWSghv
6LbVVZwph1K+jQkX7ncAm86lXqJUBg3mPDElsS8ar4X/sJz+uvw58KGIiWqy14J8
SBxcDnwW6rQaWRsWBWk5QyAtxzl81ffq0W5UKlHAuCzThq6dmG/6GUB38sMl+lz6
SbVIZxxvapjlpsRgD3N8l6qglKSuzosYYBGVp0njPVKX7qkMRQxp2pmXTnr31Zc5
HsmSdKnzHIh8IiQylA==
=UWxm
-----END PGP MESSAGE-----
```

### Debug Output
https://gist.github.com/jlindsey/c309bd85c6a14b191b8d5955a91ddd32

### Panic Output
https://gist.github.com/jlindsey/e18b2b1457e3e2d02c42e7221181603e

### Expected Behavior
Not a crash

### Actual Behavior
Crash

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
Using terragrunt, however this happens even when calling the terraform binary directly.

<hr>

Clipping out the interesting part of crash log:

```
panic: interface conversion: interface {} is string, not map[string]interface {}

goroutine 477 [running]:
github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readMap(0xc4223914a0, 0x614967d, 0x4, 0xc422041590, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:170 +0x4d8
github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readField(0xc4223914a0, 0xc421ccd540, 0x1, 0x1, 0xc422391600, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:113 +0x9f6
github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).ReadField(0xc4223914a0, 0xc421ccd540, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x614967d, ...)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:27 +0xe3
github.com/hashicorp/terraform/helper/schema.(*MultiLevelFieldReader).ReadFieldExact(0xc4222f48e0, 0xc421ccd540, 0x1, 0x1, 0x614c94c, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/helper/schema/field_reader_multi.go:31 +0xef
github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc420297ea0, 0xc421ccd540, 0x1, 0x1, 0xc421ccd512, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:475 +0x13a
github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc420297ea0, 0x614967d, 0x4, 0x1001201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:451 +0x135
github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc420297ea0, 0x614967d, 0x4, 0x614750d, 0x1, 0xc421f4d268, 0x5, 0xc421ccd520)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:428 +0x61
github.com/hashicorp/terraform/helper/schema.schemaMap.diffMap(0xc421fe7050, 0x614967d, 0x4, 0xc422041590, 0xc421a7b618, 0xc420297ea0, 0x5f06e00, 0x0, 0x0)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/helper/schema/schema.go:838 +0x11a
github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc421fe7050, 0x614967d, 0x4, 0xc422041590, 0xc4222f47c0, 0xc420297ea0, 0x0, 0x0, 0x0)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/helper/schema/schema.go:689 +0x516
github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc421fe7050, 0xc421b588c0, 0xc4223910e0, 0x0, 0x0, 0x0)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/helper/schema/schema.go:389 +0x1c2
github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc422032b40, 0xc421b588c0, 0xc4223910e0, 0x13, 0xc4211bdc18, 0x1)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/helper/schema/resource.go:211 +0x15b
github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc4202e5b20, 0xc421b58870, 0xc421b588c0, 0xc4223910e0, 0xa33a000, 0x0, 0x0)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/helper/schema/provider.go:255 +0x84
github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Diff(0xc421cbd340, 0xc4222f4660, 0xc421ccd1c0, 0x0, 0x0)
	/private/tmp/terraform-20170608-62088-1i5m5j4/terraform-0.9.8/src/github.com/hashicorp/terraform/plugin/resource_provider.go:499 +0x57
reflect.Value.call(0xc4202c66c0, 0xc420cb8c18, 0x13, 0x614892d, 0x4, 0xc421dc0f20, 0x3, 0x3, 0x0, 0xc4218b7e01, ...)
	/usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc4202c66c0, 0xc420cb8c18, 0x13, 0xc4218b7f20, 0x3, 0x3, 0xc4218b7f68, 0x1208a03, 0xc421e4b180)
	/usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc421f8e1c0, 0xc421f8e180, 0xc421f5b650, 0xc421f8c280, 0xc4222e35a0, 0x523b500, 0xc4222f4660, 0x16, 0x523b540, 0xc421ccd1c0, ...)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/rpc/server.go:387 +0x144
created by net/rpc.(*Server).ServeCodec
	/usr/local/Cellar/go/1.8.3/libexec/src/net/rpc/server.go:481 +0x404
```

**Comment by radeksimko** [comment]
This looks like a duplicate of #15442

**Comment by radeksimko** [comment]
@jbardin are you happy for me to close this in favour of the mentioned issue?

**Comment by jbardin** [comment]
thanks @radeksimko!
