### ISSUE TITLE
helper/schema: Crash in ResourceData.get

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#15730]
_This issue was originally opened by @cmukai-cisco as https://github.com/terraform-providers/terraform-provider-aws/issues/1284 and migrated here as it appears to be core-related._

<hr>

### Terraform Version
0.9.11

### Affected Resource(s)
null_resource

### Terraform Configuration Files
https://cisco.box.com/s/8w5pxjhji8wu7buzn2fnifvqe1jdvz6j
https://cisco.box.com/s/llrcayqcxbhnfze8gg1dzoefish3r2gs

### Debug Output
https://gist.github.com/cmukai-cisco/c3f6e5b764e286f37ef5a1b4efdfe63a

### Panic Output
https://gist.github.com/cmukai-cisco/f0f935aaf76c0aec795802b81672aa19

### Expected Behavior
Install mongos

### Actual Behavior
Unexpected EOF when uploading the repo config. This works on other resources.

### Steps to Reproduce
1. Unpack mongodb.tar.gz and ebs-mount.tar.gz;
2. cd mongodb/test;
3. reset source for ebs-mount in main.tf to unpacked ebs-mount tar ball; and
4. terraform apply

### Important Factoids
None.

### References
None.

<hr>

Found the problem. Specified a provisioned file content incorrectly. Originally I specified it as:

```hcl
  provisioner "file" {
    content = "${data.template_file.config-switch.*.rendered}"
    destination = "/tmp/config-switch.sh"
  }
```

The correct specification is:

```hcl
  provisioner "file" {
    content = "${data.template_file.config-switch.rendered}"
    destination = "/tmp/config-switch.sh"
  }
```

The parser did not detect the incorrect specification so it failed to produce a meaningful error message.

<hr>

Clipping out the interesting part of crash log:

```
panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'

goroutine 157 [running]:
github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc420330310, 0xc4201ce840, 0x1, 0x1, 0xc4201ce812, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:480 +0x311
github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc420330310, 0x614f2dd, 0x7, 0x1001201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:451 +0x135
github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc420330310, 0x614f2dd, 0x7, 0x100ed72, 0xc42034f740, 0x30, 0x30, 0x5f06aa0)
	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:428 +0x61
github.com/hashicorp/terraform/helper/schema.schemaMap.diffString(0xc4207984b0, 0x614f2dd, 0x7, 0xc4207a80f0, 0xc4207635f8, 0xc420330310, 0x5f06a00, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:1051 +0xb5
github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc4207984b0, 0x614f2dd, 0x7, 0xc4207a80f0, 0xc420421860, 0xc420330310, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:685 +0x43b
github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc4207984b0, 0x0, 0xc4203fc390, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:389 +0x1c2
github.com/hashicorp/terraform/helper/schema.(*Provisioner).Apply(0xc42037e5a0, 0x8d54840, 0xc4201d4018, 0xc420015950, 0xc4203fc390, 0x0, 0x10eaba2)
	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provisioner.go:163 +0x2c5
github.com/hashicorp/terraform/plugin.(*ResourceProvisionerServer).Apply(0xc4202ac500, 0xc4205a74c0, 0xc42045a0d8, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provisioner.go:142 +0x191
reflect.Value.call(0xc42037a2a0, 0xc4201c4880, 0x13, 0x61484cd, 0x4, 0xc420045f20, 0x3, 0x3, 0x1004c4d, 0xc4202aaa50, ...)
	/opt/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc42037a2a0, 0xc4201c4880, 0x13, 0xc420487720, 0x3, 0x3, 0xc420001ba0, 0x0, 0xc420001c50)
	/opt/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc420784b80, 0xc420784b40, 0xc42051b610, 0xc42043bf00, 0xc420160a80, 0x523b560, 0xc4205a74c0, 0x16, 0x523b5a0, 0xc42045a0d8, ...)
	/opt/go/src/net/rpc/server.go:387 +0x144
created by net/rpc.(*Server).ServeCodec
	/opt/go/src/net/rpc/server.go:481 +0x404
```

**Comment by radeksimko** [comment]
This looks like a duplicate of #9488

**Comment by radeksimko** [comment]
@jbardin are you happy for me to close this in favour of the mentioned issue?

**Comment by jbardin** [comment]
@radeksimko: yes, that looks like the same underlying issue. Thanks!
