### ISSUE TITLE
Terraform 0.10.1 crashes when running terraform plan

### ISSUE THREAD

**Issue by tombuildsstuff** [hashicorp/terraform#15822]
Issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/247 has highlighted a crash in Terraform 0.10.1 which from looking at the crash log appears to be an issue with Terraform Core rather than with the Provider - as such I'm migrating this issue over here.

The crash being seen is:

```
2017-08-15T19:25:26.082-0400 [ERROR] plugin.terraform-provider-azurerm_v0.1.5_x4: error parsing json from plugin: error="json: cannot unmarshal number into Go value of type map[string]interface {}"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xb7752c]

goroutine 1110 [running]:
github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin.(*Client).logStderr(0xc42054a9a0, 0x3567a80, 0xc4206f0408)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin/client.go:750 +0x39c
created by github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin.(*Client).Start
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin/client.go:544 +0xe2f
```

and a full debug log can be found here: https://gist.github.com/paulv-quest/9a651c9688be8ac4afec5feb810f8488/raw/500a23f3487c6f2d2c551a46caf7d141ee6cf5b0/gistfile1.txt

cc  @paulv-quest @ralfwierzbicki

**Comment by filiptepper** [comment]
Experiencing the same issue with AWS provider.

**Comment by PythonicNinja** [comment]
```
| => terraform --version
Terraform v0.10.1
```

```
| => uname -a
Darwin PythonicNinja 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x17792fc]

goroutine 1295 [running]:
github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin.(*Client).logStderr(0xc42025a230, 0x416aaa0, 0xc42022e090)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin/client.go:750 +0x39c
created by github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin.(*Client).Start
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin/client.go:544 +0xe2f
```

**Comment by miry** [comment]
I have the same, but when I run `terraform apply`, but it works for `terraform refresh` and `terraform plan` with AWS provider and `aws_launch_configuration` resource.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x17792fc]

goroutine 2351 [running]:
github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin.(*Client).logStderr(0xc42072de30, 0x417daa0, 0xc42037c080)
	/private/tmp/terraform-20170815-18271-16pvyh9/terraform-0.10.1/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin/client.go:750 +0x39c
created by github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin.(*Client).Start
	/private/tmp/terraform-20170815-18271-16pvyh9/terraform-0.10.1/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin/client.go:544 +0xe2f

```

**Comment by PythonicNinja** [comment]
Version 0.10.0 works fine. So this bug is probably related to the newest release.
```
| => terraform --version
Terraform v0.10.0
```
