### ISSUE TITLE
Panic when trying to use new salt masterless provisioner

### ISSUE THREAD

**Issue by benosman** [hashicorp/terraform#15867]
### Terraform Version
Terraform v0.10.3-dev (e42130bf14fe09f9d3c4103c8a4a02ea3042135b)

### Terraform Configuration Files
```hcl
resource "null_resource" "configure_agent" {
  triggers {
    version = "3"
  }
  connection {
    type     = "ssh"
    user     = "admin"
    private_key = "<snip>"
    timeout = "3m"
    host = "<snip>"
  }

  provisioner "salt-masterless" {
    local_state_tree = "./salt/state"
  }
}

```
Salt state tree has just a single file - top.sls
```yaml
base:
  '*':
    - docker
    - docker.compose
```

### Panic Output
https://gist.github.com/benosman/1757c2284c98748c8abcb90e0fbfbc36

### Expected Behavior
The salt masterless provisioner should have run the salt bootstrap, and then copied the salt state tree to the server.

### Actual Behavior
A panic is triggered immediately, too quick to be related to the connection.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I was trying to run this against an Azure host, but it happens even in a null resource, with the connection settings correct or not correct. (I've tried a file provisioner in the same block)

I realise that this provisioner has only recently been added, and is not yet part of a release. I'm keen to use it so I built it and tried it out on OSX and Windows with the same issue on both.

### References
- https://github.com/hashicorp/terraform/pull/14720

**Comment by apparentlymart** [comment]
Hi @benosman! Sorry for this crash, and thanks for reporting it.

Here's the stack trace from your panic output, for easier reference:

```
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: panic: runtime error: invalid memory address or nil pointer dereference
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1874746]
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: 
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: goroutine 22 [running]:
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: github.com/hashicorp/terraform/communicator.New(0x0, 0x0, 0x0, 0x0, 0xc42039e1c0)
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: 	/Users/ben/Code/go/src/github.com/hashicorp/terraform/communicator/communicator.go:44 +0x26
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: github.com/hashicorp/terraform/builtin/provisioners/salt-masterless.applyFn(0x42805e0, 0xc4203a0630, 0x2818fe0, 0xc420398dd0)
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: 	/Users/ben/Code/go/src/github.com/hashicorp/terraform/builtin/provisioners/salt-masterless/resource_provisioner.go:126 +0x18e
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: github.com/hashicorp/terraform/helper/schema.(*Provisioner).Apply(0xc42008ce10, 0x426f360, 0xc4203b0000, 0xc42008cfa0, 0xc420396600, 0x0, 0x0)
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: 	/Users/ben/Code/go/src/github.com/hashicorp/terraform/helper/schema/provisioner.go:179 +0x563
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: github.com/hashicorp/terraform/plugin.(*ResourceProvisionerServer).Apply(0xc4202287c0, 0xc420228da0, 0xc420084388, 0x0, 0x0)
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: 	/Users/ben/Code/go/src/github.com/hashicorp/terraform/plugin/resource_provisioner.go:142 +0x191
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: reflect.Value.call(0xc42001cea0, 0xc420084198, 0x13, 0x2ef3e9a, 0x4, 0xc420046f20, 0x3, 0x3, 0x0, 0x0, ...)
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: 	/usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:434 +0x91f
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: reflect.Value.Call(0xc42001cea0, 0xc420084198, 0x13, 0xc42002bf20, 0x3, 0x3, 0x0, 0x0, 0x0)
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: 	/usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:302 +0xa4
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: net/rpc.(*service).call(0xc4201cedc0, 0xc4201ced80, 0xc4201996b0, 0xc4200a2b80, 0xc420228840, 0x2793680, 0xc420228da0, 0x16, 0x27936c0, 0xc420084388, ...)
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: 	/usr/local/Cellar/go/1.8.3/libexec/src/net/rpc/server.go:387 +0x144
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: created by net/rpc.(*Server).ServeCodec
2017-08-22T01:53:43.446+0100 [DEBUG] plugin.terraform: 	/usr/local/Cellar/go/1.8.3/libexec/src/net/rpc/server.go:481 +0x404
```

This suggests that the resource state we're trying to use to instantiate the communicator (SSH client, basically) is missing the connection information that would normally be collected from the `connection` block.

Comparing the `salt-masterless` provisioner code to the `remote-exec` provisioner code I notice that the Salt provisioner is getting the instance state this way:

```go
ctx.Value(schema.ProvConfigDataKey).(*schema.ResourceData).State()
```

...whereas remote-exec is doing the following:

```go
ctx.Value(schema.ProvRawStateKey).(*terraform.InstanceState)
```

I think what's going on here is that `ResourceData.State()` can potentially construct an entirely new state if there are changes pending in the `ResourceData`, and that would lose the information from the `connection` block. By accessing the `schema.ProvRawStateKey` directly instead, we get exactly the state object that was used during the resource creation and so its connection information will always still be attached.

Unfortunately I've run out of time for today but hopefully we can get this fixed up pretty quickly by following the example from the remote-exec provisioner.

I've not dug deep enough to know if there's a way to work around this, but it _might_ work to move the `connection` block so it's a child (rather than a sibling) of the `provisioner "salt-masterless"` block, in case that helps Terraform not to "lose" the connection information attachment when reconstructing the state.

**Comment by benosman** [comment]
@apparentlymart thanks for looking into this :)

**Comment by benosman** [comment]
> I've not dug deep enough to know if there's a way to work around this, but it might work to move the connection block so it's a child (rather than a sibling) of the provisioner "salt-masterless" block, in case that helps Terraform not to "lose" the connection information attachment when reconstructing the state.

I just tried that out and it didn't seem to make any difference.
