### ISSUE TITLE
Terraform Crash Report

### ISSUE THREAD

**Issue by lhagemann** [hashicorp/terraform#16097]
### Terraform Version
```
$ terraform --version
Terraform v0.9.11
```

### Crash Output
https://gist.github.com/lhagemann/01a22be06e77098164724b3b5cc1a8eb

**Comment by apparentlymart** [comment]
Thanks for reporting this, @lhagemann!

Here's just the stack trace from that log, for easier reference:

```
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: panic: runtime error: invalid memory address or nil pointer dereference
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x15ec8e9]
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: 
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: goroutine 455 [running]:
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: main.(*CompartmentResourceCrud).ID(0xc420985a70, 0xc420985a70, 0x45d964b800)
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: 	/Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/resource_obmcs_identity_compartment.go:70 +0x9
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: github.com/oracle/terraform-provider-baremetal/crud.createResourceWithRetry(0xc4209ea3f0, 0x1b2e2c0, 0xc420985a70, 0x1, 0x1d14401, 0xc420985a70)
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: 	/Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/crud/helpers.go:210 +0x1f5
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: github.com/oracle/terraform-provider-baremetal/crud.CreateResource(0xc4209ea3f0, 0x1b2e2c0, 0xc420985a70, 0x1dc7008, 0xc420d46000)
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: 	/Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/crud/helpers.go:191 +0x48
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: main.createCompartment(0xc4209ea3f0, 0x1782c40, 0xc420d46000, 0x0, 0xc4201cf5e8)
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: 	/Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/resource_obmcs_identity_compartment.go:37 +0xc8
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4209c3f80, 0xc420b432c0, 0xc420a8caa0, 0x1782c40, 0xc420d46000, 0x1, 0x28, 0xc420d7af90)
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: 	/Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:186 +0x48d
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc420a24e00, 0xc420b43270, 0xc420b432c0, 0xc420a8caa0, 0x1d144b0, 0x0, 0xc420025300)
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: 	/Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0x9b
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc420b2cd00, 0xc420a8c9a0, 0xc420b22030, 0x0, 0x0)
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: 	/Users/ccushing/Documents/go/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: reflect.Value.call(0xc42025f440, 0xc420a5ee00, 0x13, 0x178407b, 0x4, 0xc420c9cf20, 0x3, 0x3, 0x5, 0xc420ba2420, ...)
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: 	/usr/local/go/src/reflect/value.go:434 +0x91f
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: reflect.Value.Call(0xc42025f440, 0xc420a5ee00, 0x13, 0xc420231720, 0x3, 0x3, 0x0, 0xc420cdbba0, 0xc42001f0e0)
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: net/rpc.(*service).call(0xc420b04f00, 0xc420b04ec0, 0xc420b39160, 0xc4201c7000, 0xc420ba2f40, 0x165c260, 0xc420a8c9a0, 0x16, 0x165c2a0, 0xc420b22030, ...)
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: 	/usr/local/go/src/net/rpc/server.go:387 +0x144
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: created by net/rpc.(*Server).ServeCodec
2017/09/14 09:21:28 [DEBUG] plugin: terraform-provider-baremetal: 	/usr/local/go/src/net/rpc/server.go:481 +0x404
```

Based on this stack trace, this looks like the crash is coming from inside [oracle/terraform-provider-oci](https://github.com/oracle/terraform-provider-oci) (formerly `terraform-provider-baremetal`) though the functions the stack trace is referring to are no longer there so I assume this code has been refactored since the version you're using here.

Since this issue seems to be in the baremetal provider, it may be better to file it over in the other repository where it'll be more visible to the people who work on it. Unfortunately since that provider is not part of the `terraform-providers` organization I can't automatically migrate it over there with our bot as I normally would in this situation. :disappointed:

**Comment by lhagemann** [comment]
Thank you for the timely response. I'll close this now.
