### ISSUE TITLE
config: split() returns nil instead of empty string

### ISSUE THREAD

**Issue by matt40k** [hashicorp/terraform#16220]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

If your issue relates to a specific Terraform provider, please open it in the provider's own repository. The index of providers is at https://github.com/terraform-providers .

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please try upgrading because your issue may have already been fixed.

### Terraform Configuration Files
https://gist.github.com/matt40k/9086a7e0de6d38a4b7e970b5fdadba81#file-do-basicdroplet-tf

https://gist.github.com/matt40k/9086a7e0de6d38a4b7e970b5fdadba81#file-do-dropletwithfirewall-tf

### Debug Output
First config returns:
'''
Error applying plan:

1 error(s) occurred:

* digitalocean_droplet.web: 1 error(s) occurred:

* digitalocean_droplet.web: Error setting tags: POST https://api.digitalocean.com/v2/tags/web/resources: 404 The resource you were accessing could not be found.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
'''

Second config returns;
Error applying plan:

2 error(s) occurred:

* digitalocean_firewall.web: 1 error(s) occurred:

* digitalocean_firewall.web: unexpected EOF
* digitalocean_droplet.web: 1 error(s) occurred:

* digitalocean_droplet.web: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resourpanic: interface conversion: interface {} is nil, not string
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe:
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe: goroutine 61 [running]:
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe: github.com/terraform-providers/terraform-provider-digitalocean/digitalocean.expandFirewallInboundRules(0xc042032000, 0x0
, 0x0, 0x0)
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe:      /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-digitalocean/digita
locean/resource_digitalocean_firewall.go:313 +0xcb7
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe: github.com/terraform-providers/terraform-provider-digitalocean/digitalocean.firewallRequest(0xc042032000, 0xc042194c00,
0x0, 0x0, 0x0)
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe:      /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-digitalocean/digita
locean/resource_digitalocean_firewall.go:296 +0x485
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe: github.com/terraform-providers/terraform-provider-digitalocean/digitalocean.resourceDigitalOceanFirewallCreate(0xc042032
000, 0xa881e0, 0xc042194c00, 0x0, 0x0)
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe:      /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-digitalocean/digita
locean/resource_digitalocean_firewall.go:156 +0x6c
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe: github.com/terraform-providers/terraform-provider-digitalocean/vendor/github.com/hashicorp/terraform/helper/schema.(*Res
ource).Apply(0xc0423f0360, 0xc0420dc3c0, 0xc0420026a0, 0xa881e0, 0xc042194c00, 0x1, 0x28, 0xc04245f5f0)
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe:      /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-digitalocean/vendor
/github.com/hashicorp/terraform/helper/schema/resource.go:186 +0x494
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe: github.com/terraform-providers/terraform-provider-digitalocean/vendor/github.com/hashicorp/terraform/helper/schema.(*Pro
vider).Apply(0xc042382850, 0xc0420dc280, 0xc0420dc3c0, 0xc0420026a0, 0x220db0, 0x0, 0x0)
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe:      /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-digitalocean/vendor
/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0xa2
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe: github.com/terraform-providers/terraform-provider-digitalocean/vendor/github.com/hashicorp/terraform/plugin.(*ResourcePr
oviderServer).Apply(0xc0423cfd20, 0xc042002320, 0xc04200d490, 0x0, 0x0)
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe:      /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-digitalocean/vendor
/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x5e
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe: reflect.Value.call(0xc04223e0c0, 0xc0420e36f0, 0x13, 0xb293e4, 0x4, 0xc0422abf20, 0x3, 0x3, 0x0, 0x0, ...)
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe:      /usr/local/go/src/reflect/value.go:434 +0x926
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe: reflect.Value.Call(0xc04223e0c0, 0xc0420e36f0, 0x13, 0xc0422abf20, 0x3, 0x3, 0x0, 0x0, 0x0)
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe:      /usr/local/go/src/reflect/value.go:302 +0xab
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe: net/rpc.(*service).call(0xc0423ddfc0, 0xc0423ddf80, 0xc0423ec5b8, 0xc0420e8d00, 0xc04233b2e0, 0xa116a0, 0xc042002320, 0x
16, 0xa116e0, 0xc04200d490, ...)
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe:      /usr/local/go/src/net/rpc/server.go:387 +0x14b
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe: created by net/rpc.(*Server).ServeCodec
2017-09-29T14:38:12.414+0100 [DEBUG] plugin.terraform-provider-digitalocean_v0.1.2_x4.exe:      /usr/local/go/src/net/rpc/server.go:481 +0x40b
2017/09/29 14:38:12 [TRACE] root: eval: *terraform.EvalWriteState
2017/09/29 14:38:12 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2017/09/29 14:38:12 [TRACE] root: eval: *terraform.EvalIf
2017/09/29 14:38:12 [TRACE] root: eval: *terraform.EvalWriteState
2017/09/29 14:38:12 [TRACE] root: eval: *terraform.EvalWriteDiff
2017/09/29 14:38:12 [TRACE] root: eval: *terraform.EvalApplyPost
2017/09/29 14:38:12 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* digitalocean_firewall.web: unexpected EOF
2017/09/29 14:38:12 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* digitalocean_firewall.web: unexpected EOF
2017/09/29 14:38:12 [TRACE] [walkApply] Exiting eval tree: digitalocean_firewall.web
2017/09/29 14:38:12 [TRACE] root: eval: *terraform.EvalWriteState
2017/09/29 14:38:12 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2017/09/29 14:38:12 [TRACE] root: eval: *terraform.EvalIf
2017/09/29 14:38:12 [TRACE] root: eval: *terraform.EvalWriteState
2017/09/29 14:38:12 [TRACE] root: eval: *terraform.EvalWriteDiff
2017/09/29 14:38:12 [TRACE] root: eval: *terraform.EvalApplyPost
2017/09/29 14:38:12 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* digitalocean_droplet.web: unexpected EOF
2017/09/29 14:38:12 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* digitalocean_droplet.web: unexpected EOF
2017/09/29 14:38:12 [TRACE] [walkApply] Exiting eval tree: digitalocean_droplet.web
2017/09/29 14:38:12 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/09/29 14:38:12 [TRACE] dag/walk: upstream errored, not walking "provider.digitalocean (close)"
2017/09/29 14:38:12 [TRACE] dag/walk: upstream errored, not walking "root"
2017/09/29 14:38:12 [TRACE] Preserving existing state lineage "1be62308-8623-4224-b15d-9c662ba2697b"
2017-09-29T14:38:12.424+0100 [DEBUG] plugin: plugin process exited: path=C:\git\terraform\.terraform\plugins\windows_amd64\terraform-provider-digitalocean_v0.1.2_x4.exe
2017/09/29 14:38:12 [TRACE] Preserving existing state lineage "1be62308-8623-4224-b15d-9c662ba2697b"
2017/09/29 14:38:12 [TRACE] Preserving existing state lineage "1be62308-8623-4224-b15d-9c662ba2697b"
2017/09/29 14:38:12 [TRACE] Preserving existing state lineage "1be62308-8623-4224-b15d-9c662ba2697b"
2017/09/29 14:38:12 [DEBUG] plugin: waiting for all plugin processes to complete...
2017-09-29T14:38:12.527+0100 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2017-09-29T14:38:12.549+0100 [DEBUG] plugin: plugin process exited: path=C:\git\terraform\.terraform\plugins\windows_amd64\terraform-provider-http_v1.0.0_x4.exe

ces that successfully compl

e!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
ted. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by matt40k** [comment]
Logged here - https://github.com/terraform-providers/terraform-provider-digitalocean/issues/44

**Comment by radeksimko** [comment]
Hi @matt40k 
thanks for the report.

After further inspection this looks like a core bug involving the `split` function which returns a list of IPs with empty string (b/c of the trailing newline in the output from cloudflare) at the end which then turns into `nil` at some point for some reason, which then causes the crash.

We can fix it in DO provider but it will be rather a workaround for something that should never appear in provider context. With that I'm going to reopen this issue here in core.

Here's a simplified config:

```hcl
data "http" "cf_ip4" {
  url = "https://www.cloudflare.com/ips-v4"
}

resource "digitalocean_tag" "web" {
  name = "web"
}

resource "digitalocean_firewall" "web" {
  depends_on = ["digitalocean_tag.web"]
  name = "onlyCf"
  tags = ["web"]

  inbound_rule {
    protocol         = "tcp"
    port_range       = "22"
    source_addresses = ["${split("\n", data.http.cf_ip4.body)}"]
  }
}
```

The easiest fix for the moment is to strip the trailing newline, i.e.
```hcl
source_addresses = ["${split("\n", trimspace(data.http.cf_ip4.body))}"]
```

**Comment by teamterraform** [comment]
Prior to Terraform 0.12 there were some missing validation rules in the SDK that were causing these crashes. From 0.12 onwards, the type checking validations are handled by Terraform Core itself and so it's no longer possible to hit these crashing codepaths.

The parts of Terraform that deal with validation were changed significantly in Terraform 0.12, so if you see any similar problems with validation rules in Terraform 0.12.0 or later, please open a new issue so we can capture an updated set of debug information about the new situation. Because the codepath that was crashing here should no longer run in Terraform 0.12, we're going to close this now.
