### ISSUE TITLE
`terraform plan` causes SIGSEGV

### ISSUE THREAD

**Issue by koooge** [hashicorp/terraform#16579]
Hi there, I was encountered SIGSEGV.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please try upgrading because your issue may have already been fixed.

### Terraform Configuration Files
- Terraform v0.10.8
- terraform-provider-aws v1.2.0

### Debug Output
I found crash.log but it includes business info, so I report only Crash Output 🙇 

### Crash Output
```
aws_sqs_queue.<sqs-name>: Refreshing state... (ID: https://sqs.ap-northeast-1.amazonaws.co...)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1726bf1]

goroutine 1256 [running]:
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).evalTreeManagedResourceNoState(0xc420270548, 0x3, 0x1)
	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:218 +0x241
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).EvalTree(0xc420270548, 0x3035820, 0xc420270548)
	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:97 +0x71
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x3035820, 0xc420270548, 0x0, 0x0)
	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/hashicorp/terraform/terraform/graph.go:113 +0xa3c
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc42031eb60, 0x3035820, 0xc420270548, 0xc4208a2900)
	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x3c1
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/hashicorp/terraform/dag/walk.go:310 +0x1364
```

### Steps to Reproduce
1. rename aws_instance resource name
2. `$ terraform state mv aws_instance.foo aws_instance.bar`
  - I might type `$ terraform state mv aws_instance.foo <wrong resource such as aws_eip>.bar` 😿 
3. `$ terraform plan`

**Comment by gms-ta-koge** [comment]
I checked my .tfstate and I found something wrong. Resource name is `"aws_eip.bar": {` in spite of `"type": "aws_instance"`.  
Apparently, I typed `$ terraform state mv aws_instance.foo aws_eip.bar` in step2...

```
...
   "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        },
       {
            "path": [
                "root",
                "compute"
            ],
            "outputs": {},
            "resources": {
                "aws_eip.bar": {
                    "type": "aws_instance",
...
```

**Comment by koooge** [comment]
I checked my .tfstate and I found something wrong. Resource name is `"aws_eip.bar": {` in spite of `"type": "aws_instance"`.  
Apparently, I typed `$ terraform state mv aws_instance.foo aws_eip.bar` in step2...

```
...
   "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        },
       {
            "path": [
                "root",
                "compute"
            ],
            "outputs": {},
            "resources": {
                "aws_eip.bar": {
                    "type": "aws_instance",
...
```

**Comment by apparentlymart** [comment]
Thanks for that additional context, @koooge!

Indeed a failure is expected in that case, but we should handle it more elegantly than a panic...

**Comment by gileri** [comment]
Having the same problem, `terraform state rm` on a resource of wrong type (after `terraform mv`) fails silently.
