### ISSUE TITLE
Terraform Crash [unexpected EOF] with chef provisoner, policyfile, & Terraform 0.9.8 - 0.10.8

### ISSUE THREAD

**Issue by chrisanthropic** [hashicorp/terraform#16655]
### Terraform Version
Terraform 0.9.8 - 0.10.8

### Terraform Configuration Files
Relevant block from my module:
```hcl
  provisioner "chef" {
    node_name = "${var.instance_name_prefix}${count.index}"
    server_url = "${var.instance_provisioner_chef_server_url}"
    policy_group = "${var.instance_provisioner_chef_policy_group}"
    policy_name = "${var.instance_provisioner_chef_policy_name}"
    attributes_json = "${var.instance_provisioner_chef_attributes_json}"
    secret_key = "${var.instance_provisioner_chef_secret_key}"
    user_name = "${var.instance_provisioner_chef_user_name}"
    user_key = "${var.instance_provisioner_chef_user_key}"
    version  = "${var.instance_provisioner_chef_version}"
    named_run_list = "${var.instance_provisioner_chef_named_run_list}"
  }
```
Resource block calling the module:
```hcl
module "buggy-thing" {
  source = "../modules/module-pgc2"
  instance_provisioner_chef_server_url        = "https://api.opscode.com/organizations/myorg"
  instance_provisioner_chef_use_policyfile    = true
  instance_provisioner_chef_policy_group      = "staging"
  instance_provisioner_chef_policy_name       = "buggy-thing"
  instance_provisioner_chef_attributes_json = <<-EOS
    {
      "tags": ["dc-${var.region}"],
      "secrets_locker": {
        "default_data_bag_item": "staging"
      }
    }
  EOS
  instance_provisioner_chef_secret_key = "${var.chef_encrypted_data_bag_secret}"
  instance_provisioner_chef_user_name = "FrankOz"
  instance_provisioner_chef_user_key = "${var.chef_validation_key}"
  instance_provisioner_chef_version = "12.14.89"
  instance_provisioner_chef_named_run_list = ""
}
```

### Debug Output
https://gist.github.com/chrisanthropic/e9f6cfb51c0e5a4c2623a0c991e8ccc8

### Crash Output
Please see above.

### Expected Behavior
Terraform plan should execute successfully.

### Actual Behavior
Terraform crash.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform get`
3. `terraform plan`

### Important Factoids
This module works with terraform 0.9.6 - 0.9.7.
From 0.9.8 - .0.10.8 we see the same terraform crash.

Removing `use_policyfile = "${var.instance_provisioner_chef_use_policyfile}"` from the module and `instance_provisioner_chef_use_policyfile` from the resource block (and replacing it with a run_list) results in a successful `terraform apply`.

**Comment by jbardin** [comment]
The relevant stack trace:

```
panic: interface conversion: interface {} is string, not bool

goroutine 11 [running]:
github.com/hashicorp/terraform/builtin/provisioners/chef.validateFn(0xc4202b5290, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/hashicorp/terraform/builtin/provisioners/chef/resource_provisioner.go:378 +0x5c4
github.com/hashicorp/terraform/helper/schema.(*Provisioner).Validate(0xc420348320, 0xc4202b5290, 0xc42005be48, 0xc420313b28, 0x4107b7, 0xc4202b53e0, 0x30, 0x28)
	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/hashicorp/terraform/helper/schema/provisioner.go:198 +0x23d
github.com/hashicorp/terraform/plugin.(*ResourceProvisionerServer).Validate(0xc420332960, 0xc42000cb88, 0xc4202b5320, 0x0, 0x0)
	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/hashicorp/terraform/plugin/resource_provisioner.go:152 +0x59
reflect.Value.call(0xc42005be00, 0xc42000ca00, 0x13, 0x24ff99b, 0x4, 0xc420313f20, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x906
reflect.Value.Call(0xc42005be00, 0xc42000ca00, 0x13, 0xc420035f20, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc42019ba80, 0xc42006be00, 0xc420277100, 0xc42010ad80, 0xc4202b3be0, 0x1d024e0, 0xc42000cb88, 0x16, 0x1d02520, 0xc4202b5320, ...)
	/usr/local/go/src/net/rpc/server.go:381 +0x142
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:475 +0x36b
```

**Comment by chrisanthropic** [comment]
Same behavior in Terraform 0.11.1.
