### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by rapullur** [hashicorp/terraform#16788]
Hi everyone , Please need advice/help. I am getting below error message " !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
" in pre-prod env, however its working fine in other env like ( Prod) . Current installed version Terraform v0.9.11 .

**Comment by jbardin** [comment]
Hi @rapullur,

You need to provide the output from terraform which includes the stack trace from the crash, and the steps used to reproduce the issue. The debug logs may also be of help, see https://www.terraform.io/docs/internals/debugging.html

**Comment by rapullur** [comment]
Thanks for reply @jbardin . 

I tried upgrading the version to v 11 from v0.9.11 but it did not work. I have also tried cloning the source code from the master branch and rerun the terraform plan which was working fine however after importing lambda fuction, it is crashing again. 
Here is the lambda code,
"aws_lambda_function.ckc-preprod-lambda-ec2stopstart": {
                    "type": "aws_lambda_function",
                    "depends_on": [],
                    "primary": {
                        "id": "ckc-preprod-lambda-ec2stopstart",
                        "attributes": {
                            "arn": "arn:aws:lambda:us-east-1:848676982977:function:ckc-preprod-lambda-ec2stopstart",
                            "dead_letter_config.#": "0",
                            "description": "",
                            "environment.#": "0",
                            "function_name": "ckc-preprod-lambda-ec2stopstart",
                            "handler": "lambda_function.lambda_handler",
                            "id": "ckc-preprod-lambda-ec2stopstart",
                            "invoke_arn": "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:848676982977:function:ckc-preprod-lambda-ec2stopstart/invocations",
                            "kms_key_arn": "",
                            "last_modified": "2017-11-13T12:41:51.069+0000",
                            "memory_size": "128",
                            "qualified_arn": "arn:aws:lambda:us-east-1:848676982977:function:ckc-preprod-lambda-ec2stopstart:$LATEST",
                            "role": "arn:aws:iam::848676982977:role/Lambda_Unresponsive_Stop_Start",
                            "runtime": "python2.7",
                            "source_code_hash": "EknlP5BMmkBFc/j8HmOAyZWdMxF0ZhO4qCaXBXI7XuE=",
                            "tags.%": "0",
                            "timeout": "300",
                            "tracing_config.#": "1",
                            "tracing_config.0.mode": "PassThrough",
                            "version": "$LATEST",
                            "vpc_config.#": "0"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": "aws"
                },
Here is the output on terraform crash.

panic: Unknown kind: int
2017-11-29T15:11:05.348-0500 [DEBUG] plugin.terraform-provider-aws_v1.3.1_x4.exe:
2017-11-29T15:11:05.348-0500 [DEBUG] plugin.terraform-provider-aws_v1.3.1_x4.exe: goroutine 217 [running]:
2017-11-29T15:11:05.348-0500 [DEBUG] plugin.terraform-provider-aws_v1.3.1_x4.exe: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.(*ResourceConfig).get(0xc042824180, 0xc042a7ecc0, 0x25, 0xc042824210, 0x80, 0xc042a7ecc0, 0x25)
2017-11-29T15:11:05.348-0500 [DEBUG] plugin.terraform-provider-aws_v1.3.1_x4.exe:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/resource.go:365 +0x985
2017-11-29T15:11:05.348-0500 [DEBUG] plugin.terraform-provider-aws_v1.3.1_x4.exe: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.(*ResourceConfig).IsComputed(0xc042824180, 0xc042a7ecc0, 0x25, 0x3)
2017-11-29T15:11:05.348-0500 [DEBUG] plugin.terraform-provider-aws_v1.3.1_x4.exe:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/resource.go:256 +0x53

**Comment by rapullur** [comment]
@jbardin The root cause of this issue is because of cloudwatch alarm code created in terraform. Need some help on fixing the cloudwatch alarm code addressed here #16795

**Comment by tombuildsstuff** [comment]
the associated HCL Configuration is available in this comment: https://github.com/hashicorp/terraform/issues/16795#issue-277986422
