### ISSUE TITLE
Crash when module source is incorrect

### ISSUE THREAD

**Issue by antonbabenko** [hashicorp/terraform#17119]
### Terraform Version

Terraform v0.11.2

### Terraform Configuration Files
```hcl
provider "aws" {}
module "http_sg" {
  source = "terraform-aws-modules/security-group/aws//modules/http-80"
}
```

### Debug Output
```
$ terraform init
Initializing modules...
- module.http_sg
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1521f06]

goroutine 1 [running]:
github.com/hashicorp/terraform/registry.(*Client).Discover(0xc4203ef180, 0x3343af9, 0x15, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/registry/client.go:70 +0x66
github.com/hashicorp/terraform/registry.(*Client).Versions(0xc4203ef180, 0xc42038edc0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/registry/client.go:83 +0xa2
github.com/hashicorp/terraform/config/module.Storage.findRegistryModule(0xc42034ebc0, 0x12, 0x0, 0x0, 0x0, 0x4abbe00, 0xc420369da0, 0x1, 0xc4203ef180, 0xc420019f81, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:319 +0x6eb
github.com/hashicorp/terraform/config/module.(*Tree).getChildren(0xc420128f00, 0xc42038ed20, 0xc420128f38, 0xc4203ef180, 0xc4203ef180)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:219 +0x493
github.com/hashicorp/terraform/config/module.(*Tree).Load(0xc420128f00, 0xc42038ed20, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:178 +0xab
github.com/hashicorp/terraform/command.getModules(0xc42016ca80, 0xc420018104, 0x2e, 0xc420017b01, 0x23, 0xc420017b60)
	/opt/gopath/src/github.com/hashicorp/terraform/command/get.go:84 +0x135
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc42016ca80, 0xc42000a090, 0x0, 0x0, 0xc42033cd00)
	/opt/gopath/src/github.com/hashicorp/terraform/command/init.go:178 +0xb50
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4202cfcc0, 0xc4202cfcc0, 0xc4201d7d18, 0x1)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:255 +0x1eb
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:214 +0xbda
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:99 +0xbb
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:35 +0x38
```

### Crash Output
https://gist.github.com/antonbabenko/11de9aecb65ba369245011bb2b843f63

### Expected Behavior
Do not panic. Nicer error message.

### Actual Behavior
Panic.

### Steps to Reproduce
1. `terraform init`

**Comment by afeld** [comment]
Having the same problem with [`terraform-aws-modules/vpc/aws`](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/1.14.0), so it's not a case of a missing module. Weirdly, only having a problem on Mac - Linux works fine.

**Comment by sionsmith** [comment]
Have the same issue on OSX 10.13.3 (17D47) Module code is correct and been tested with 11.2 binary MD5 (1bb6e5a842e730991ec9bd52f4872d47) on 10.13.2

**Comment by jbardin** [comment]
Hi @sionsmith,

This fix has not been released yet, and will be in 0.11.3.

**Comment by sionsmith** [comment]
hi @jbardin is there anyway I can build from sources myself?

**Comment by jbardin** [comment]
@sionsmith,

You can follow the directions [here](https://github.com/hashicorp/terraform#developing-terraform), and a single terraform binary can be built locally just using the standard `go` commands. 

However, if you actually have the same issue as above you're still going to get an error, it's just now catching the unexpected nil pointer and returning an error instead.
