### ISSUE TITLE
Terraform refresh crashes

### ISSUE THREAD

**Issue by Mistobaan** [hashicorp/terraform#17152]
### Terraform Version

```
0.11.2
```

### Terraform Configuration Files

```hcl

```

### Crash Output

https://gist.github.com/Mistobaan/64ed7c90e0a8b0ac6e1d497b6195c73d

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x174ade2]

goroutine 1512 [running]:
github.com/hashicorp/terraform/terraform.(*State).Lock(0x0)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/terraform/state.go:95 +0x22
github.com/hashicorp/terraform/terraform.(*State).SameLineage(0x0, 0xc4205f41e0, 0xc420252300)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/terraform/state.go:628 +0x34
github.com/hashicorp/terraform/state/remote.(*State).WriteState(0xc420252300, 0x0, 0x0, 0x0)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/state/remote/state.go:37 +0x10a
github.com/hashicorp/terraform/backend/local.(*Local).opRefresh(0xc4203af970, 0x4acfac0, 0xc420016090, 0xc420213140, 0xc420252030)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/backend/local/backend_refresh.go:115 +0x465
github.com/hashicorp/terraform/backend/local.(*Local).(github.com/hashicorp/terraform/backend/local.opRefresh)-fm(0x4acfac0, 0xc420016090, 0xc420213140, 0xc420252030)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/backend/local/backend.go:230 +0x52
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc4203af970, 0xc4205185f0, 0xc4205185e0, 0x4acfac0, 0xc420016090, 0xc420213140, 0xc420252030)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/backend/local/backend.go:254 +0x9a
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/backend/local/backend.go:251 +0x18a
```

### Expected Behavior

terraform should have refreshed the internal state 
### Actual Behavior

It crashed 
### Steps to Reproduce

not sure how to reproduce.

### Additional Context

I just ran `terraform refresh` from a command line .
I use a non official provider https://github.com/mcuadros/terraform-provider-helm

**Comment by jbardin** [comment]
Hi @Mistobaan,

Thanks for reporting this! This was fixed recently in #17076, and will be included in the next release.
