### ISSUE TITLE
TERRAFORM CRASH 

### ISSUE THREAD

**Issue by mgalezewski** [hashicorp/terraform#17172]
```
2018/01/23 18:31:02 [INFO] Terraform version: 0.11.2  
2018/01/23 18:31:02 [INFO] Go runtime version: go1.9.2
2018/01/23 18:31:02 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.11.2/bin/terraform", "init"}
2018/01/23 18:31:02 [DEBUG] Attempting to open CLI config file: /.terraformrc
2018/01/23 18:31:02 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2018/01/23 18:31:02 [INFO] CLI command args: []string{"init"}
2018/01/23 18:31:02 [TRACE] module source: "terraform-aws-modules/vpc/aws"
2018/01/23 18:31:02 [TRACE] "terraform-aws-modules/vpc/aws" is a registry module
2018/01/23 18:31:02 [INFO] no matching version for "terraform-aws-modules/vpc/aws"<>, no versions found
2018/01/23 18:31:02 [DEBUG] matched "terraform-aws-modules/vpc/aws" version  for 
2018/01/23 18:31:02 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2018/01/23 18:31:06 [WARNING] Failed to request discovery document: Get https://registry.terraform.io/.well-known/terraform.json: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2018/01/23 18:31:06 [DEBUG] plugin: waiting for all plugin processes to complete...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1522896]

goroutine 1 [running]:
github.com/hashicorp/terraform/registry.(*Client).Discover(0xc4203d0220, 0x334498a, 0x15, 0x0)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/registry/client.go:70 +0x66
github.com/hashicorp/terraform/registry.(*Client).Versions(0xc4203d0220, 0xc4202eedc0, 0x0, 0x0, 0x0)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/registry/client.go:83 +0xa2
github.com/hashicorp/terraform/config/module.Storage.findRegistryModule(0xc4205124c0, 0x12, 0x0, 0x0, 0x0, 0x4ad3e00, 0xc4203d1aa0, 0x1, 0xc4203d0220, 0xc42041e561, ...)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/config/module/storage.go:319 +0x6eb
github.com/hashicorp/terraform/config/module.(*Tree).getChildren(0xc42030e180, 0xc4202eed20, 0xc42030e1b8, 0xc4203d0220, 0xc4203d0220)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/config/module/tree.go:219 +0x493
github.com/hashicorp/terraform/config/module.(*Tree).Load(0xc42030e180, 0xc4202eed20, 0x0, 0x0)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/config/module/tree.go:178 +0xab
github.com/hashicorp/terraform/command.getModules(0xc4203ac8c0, 0xc42001a004, 0x29, 0xc4202f5701, 0x23, 0xc4202f5770)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/command/get.go:84 +0x135
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc4203ac8c0, 0xc42000a070, 0x0, 0x0, 0xc4202f14f0)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/command/init.go:178 +0xb50
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc42034fcc0, 0xc42034fcc0, 0xc4201d3d18, 0x1)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:255 +0x1eb
main.wrappedMain(0x0)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/main.go:214 +0xbda
main.realMain(0x0)
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/main.go:99 +0xbb
main.main()
	/private/tmp/terraform-20180110-38003-hqmn1k/terraform-0.11.2/src/github.com/hashicorp/terraform/main.go:35 +0x38
```

**Comment by jbardin** [comment]
closed by #17134
