### ISSUE TITLE
Crash when using `aws_route53_zone`

### ISSUE THREAD

**Issue by shakefu** [hashicorp/terraform#17248]
### Terraform Version

```
$ terraform --version
Terraform v0.11.2
+ provider.aws v1.7.0
+ provider.ignition v1.0.0
+ provider.random v1.1.0

```

### Terraform Configuration Files

```hcl
# dns.tf
data "aws_route53_zone" "domain" {
  name = "domain.io"
}

resource "aws_route53_zone" "vpc" {
  name = "vpc.${data.aws_route53_zone.domain.name}"
  tags = ["${var.tags}"]
}

resource "aws_route53_record" "vpc_ns" {
  zone_id = "${aws_route53_zone.vpc.zone_id}"
  name    = "vpc.${data.aws_route53_zone.domain.name}"
  type    = "NS"
  ttl     = "5"

  // records = ["${aws_route53_zone.vpc.name_servers}"]
  records = [
    "${aws_route53_zone.vpc.name_servers.0}",
    "${aws_route53_zone.vpc.name_servers.1}",
    "${aws_route53_zone.vpc.name_servers.2}",
    "${aws_route53_zone.vpc.name_servers.3}",
  ]
}

# tags.tf
variable "tags" {
  default = {
    environment = "dev"
    phase       = "research"
    provisioner = "terraform"
    unit        = "multi"
  }

  type = "map"
}
```

### Crash Output

https://gist.github.com/shakefu/48cbd993c8b38c023fb8e67efa69fff3

### Expected Behavior

A new plan should be generated including a subdomain zone.

### Actual Behavior

Terraform crashes.

### Steps to Reproduce

(Probably)
1. Create DNS zone with `tags` key.
2. Crash!

### Additional Context

Found this as part of a large configuration. Was able to replicate with the minimal HCL (private domains redacted) above.

**Comment by radeksimko** [comment]
Clipping out the relevant part of crash log:

```
panic: interface conversion: interface {} is string, not map[string]interface {}
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4:
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: goroutine 145 [running]:
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readMap(0xc4208bf800, 0x34f81dc, 0x4, 0xc420b63a40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:170 +0xfb3
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readField(0xc4208bf800, 0xc4202cba80, 0x1, 0x1, 0xc420180f00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:113 +0xd72
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).ReadField(0xc4208bf800, 0xc4202cba80, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:27 +0x110
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*MultiLevelFieldReader).ReadFieldExact(0xc4205d6380, 0xc4202cba80, 0x1, 0x1, 0x34f9c48, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_multi.go:31 +0x12e
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc42060d7a0, 0xc4202cba80, 0x1, 0x1, 0xc4202cba12, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:497 +0x16e
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc42060d7a0, 0x34f81dc, 0x4, 0x1011201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:473 +0x135
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc42060d7a0, 0x34f81dc, 0x4, 0x34f6f55, 0x1, 0xc4204fd2b8, 0x5, 0xc4204fd2a0)
2018-01-30T14:01:12.649-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:450 +0xa5
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diffMap(0xc420861560, 0x34f81dc, 0x4, 0xc420b63a40, 0xc42080b610, 0x4fec000, 0xc42060d7a0, 0x1029100, 0x35914b0, 0xc42004a618)
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:932 +0x115
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc420861560, 0x34f81dc, 0x4, 0xc420b63a40, 0xc4205d6280, 0x4fec000, 0xc42060d7a0, 0x756ea1bb759700, 0x10, 0xca4cf4bf0980aa8b)
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:778 +0x593
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc420861560, 0xc420823b30, 0xc4208bf530, 0x0, 0x30fe7e0, 0xc4201bc500, 0xc42004aa18, 0xc42004aa20, 0xc4204f1514)
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:424 +0x24a
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc420b30e00, 0xc420823b30, 0xc4208bf530, 0x30fe7e0, 0xc4201bc500, 0x1, 0xc4208bf5f0, 0xc4208bf5f0)
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:252 +0x187
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc42060c540, 0xc420823ae0, 0xc420823b30, 0xc4208bf530, 0x5e9d000, 0x0, 0x18)
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:296 +0xa4
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Diff(0xc420876100, 0xc420887d20, 0xc4202cb9f0, 0x0, 0x0)
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:538 +0x57
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: reflect.Value.call(0xc4203c4720, 0xc420180188, 0x13, 0x34f7a78, 0x4, 0xc42004af20, 0x3, 0x3, 0x0, 0x0, ...)
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/usr/local/go/src/reflect/value.go:434 +0x905
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: reflect.Value.Call(0xc4203c4720, 0xc420180188, 0x13, 0xc4203adf20, 0x3, 0x3, 0xc4203a3ce0, 0xc4203a3da0, 0xc4202c26e0)
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: net/rpc.(*service).call(0xc4208d2100, 0xc420822000, 0xc4205d2140, 0xc420820200, 0xc4208761c0, 0x2c730e0, 0xc420887d20, 0x16, 0x2c73120, 0xc4202cb9f0, ...)
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: created by net/rpc.(*Server).ServeCodec
2018-01-30T14:01:12.650-0800 [DEBUG] plugin.terraform-provider-aws_v1.8.0_x4: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
```
