### ISSUE TITLE
terraform crash during cleanup with aviatrix site2cloud resource

### ISSUE THREAD

**Issue by edumanig** [hashicorp/terraform#17584]
Terraform crashed during cleanup "terraform destroy -force"

Version: Terraform v0.11.3

Crash Output
https://gist.github.com/edumanig/0db04fc194ba4eb4de28c3354e06a505#file-crash-log

---------
panic: runtime error: index out of range
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: 
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: goroutine 54 [running]:
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: github.com/terraform-providers/terraform-provider-aviatrix/vendor/github.com/AviatrixSystems/go-aviatrix/goaviatrix.(*Client).GetSite2Cloud(0xc420393500, 0xc42004b938, 0x9, 0xc97240, 0xc42030d6c0)
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: 	/home/ubuntu/work/src/github.com/terraform-providers/terraform-provider-aviatrix/vendor/github.com/AviatrixSystems/go-aviatrix/goaviatrix/site2cloud.go:69 +0x428
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: github.com/terraform-providers/terraform-provider-aviatrix/aviatrix.resourceAviatrixSite2CloudRead(0xc4201353b0, 0xdf1680, 0xc420393500, 0xc4201353b0, 0x0)
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: 	/home/ubuntu/work/src/github.com/terraform-providers/terraform-provider-aviatrix/aviatrix/resource_site2cloud.go:87 +0xe1
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: github.com/terraform-providers/terraform-provider-aviatrix/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc420391730, 0xc420061130, 0xdf1680, 0xc420393500, 0xc42039b0f8, 0xc4203c4c01, 0x80000000018)
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: 	/home/ubuntu/work/src/github.com/terraform-providers/terraform-provider-aviatrix/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:354 +0x17e
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: github.com/terraform-providers/terraform-provider-aviatrix/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4203919d0, 0xc420060be0, 0xc420061130, 0x7f5e8b3cc000, 0x0, 0x18)
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: 	/home/ubuntu/work/src/github.com/terraform-providers/terraform-provider-aviatrix/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: github.com/terraform-providers/terraform-provider-aviatrix/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc42039e400, 0xc42030d160, 0xc42030d230, 0x0, 0x0)
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: 	/home/ubuntu/work/src/github.com/terraform-providers/terraform-provider-aviatrix/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: reflect.Value.call(0xc42030a360, 0xc42000fba8, 0x13, 0xdf588f, 0x4, 0xc4202eff20, 0x3, 0x3, 0x0, 0x0, ...)
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: 	/usr/local/go/src/reflect/value.go:434 +0x905
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: reflect.Value.Call(0xc42030a360, 0xc42000fba8, 0x13, 0xc420028720, 0x3, 0x3, 0xc42047c360, 0xc420028728, 0xc4203ba680)
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: net/rpc.(*service).call(0xc420317f00, 0xc4203b4000, 0xc4203987a8, 0xc4203b6300, 0xc42039e500, 0xc6e2e0, 0xc42030d160, 0x16, 0xc6e320, 0xc42030d230, ...)
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: created by net/rpc.(*Server).ServeCodec
2018-03-14T06:31:01.681-0700 [DEBUG] plugin.terraform-provider-aviatrix: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
2018-03-14T06:31:01.681-0700 [DEBUG] plugin: plugin process exited: path=/home/ubuntu/work/bin/terraform-provider-aviatrix
2018/03/14 06:31:01 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-03-14T06:31:01.684-0700 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2018-03-14T06:31:01.686-0700 [DEBUG] plugin: plugin process exited: path=/home/ubuntu/2freetunnel/.terraform/plugins/linux_amd64/terraform-provider-aws_v1.11.0_x4

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jbardin** [comment]
Hi @edumanig,

Thanks for filing the issue. This is from the aviatrix provider, which is still in development. If you want to report an issue, you can do so in their repository located here: https://github.com/AviatrixSystems/terraform-provider-aviatrix/issues
