### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by mbenkhal27** [hashicorp/terraform#17648]
### Terraform Version

```
Terraform v0.11.4
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

Error: vra7_resource.RHEL_6_Full_Support_nonAA: unexpected EOF

panic: Unknown validation type: 6
2018-03-20T16:40:54.631-0500 [DEBUG] plugin.terraform-provider-vra7: 
2018-03-20T16:40:54.631-0500 [DEBUG] plugin.terraform-provider-vra7: goroutine 30 [running]:
2018-03-20T16:40:54.631-0500 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.validateMapValues(0x19fea2b, 0x16, 0xc4202e7d10, 0xc42038fe00, 0xc4202e7d10, 0xc4202fe6d0, 0x195, 0xc4202e9d60, 0x2328438, 0x0)
2018-03-20T16:40:54.631-0500 [DEBUG] plugin.terraform-provider-vra7: 	/Users/mbenkhal/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/schema.go:1450 +0xc87
2018-03-20T16:40:54.631-0500 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.schemaMap.validateMap(0xc4202e7ad0, 0x19fea2b, 0x16, 0x1882000, 0xc4202fd660, 0xc42038fe00, 0xc4202e7bc0, 0x97, 0x0, 0xc4202fa801, ...)
2018-03-20T16:40:54.631-0500 [DEBUG] plugin.terraform-provider-vra7: 	/Users/mbenkhal/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/schema.go:1402 +0x265
2018-03-20T16:40:54.631-0500 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.schemaMap.validateType(0xc4202e7ad0, 0x19fea2b, 0x16, 0x1882000, 0xc4202fd660, 0xc42038fe00, 0xc4202e7bc0, 0xc4202fa800, 0x0, 0x0, ...)
2018-03-20T16:40:54.631-0500 [DEBUG] plugin.terraform-provider-vra7: 	/Users/mbenkhal/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/schema.go:1601 +0x65f
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.schemaMap.validate(0xc4202e7ad0, 0x19fea2b, 0x16, 0xc42038fe00, 0xc4202e7bc0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: 	/Users/mbenkhal/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/schema.go:1260 +0x20a
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.schemaMap.validateObject(0xc4202e7ad0, 0x0, 0x0, 0xc4202e7ad0, 0xc4202e7bc0, 0xc4202e95c0, 0x100fe44, 0x1985380, 0x192fba0, 0xc4202e95c0, ...)
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: 	/Users/mbenkhal/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/schema.go:1498 +0x1bf
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.schemaMap.Validate(0xc4202e7ad0, 0xc4202e7bc0, 0x192fba0, 0xc4202e95c0, 0x1985380, 0xc4202e7dd0, 0x1985380, 0x100d6f2)
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: 	/Users/mbenkhal/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/schema.go:607 +0x50
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.(*Resource).Validate(0xc4203871f0, 0xc4202e7bc0, 0xc4202fa7f0, 0xd, 0xc420309818, 0xc420328101, 0x0, 0x0)
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: 	/Users/mbenkhal/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/resource.go:270 +0x50
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.(*Provider).ValidateResource(0xc420387260, 0xc4202fa7f0, 0xd, 0xc4202e7bc0, 0xc420318fa8, 0xc4203a4b28, 0x1012397, 0xc4202e7e00, 0x30, 0x28)
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: 	/Users/mbenkhal/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/provider.go:240 +0x1d3
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ValidateResource(0xc4202fd380, 0xc4202fd400, 0xc4202e7d70, 0x0, 0x0)
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: 	/Users/mbenkhal/TerraformPluginProject/src/github.com/hashicorp/terraform/plugin/resource_provider.go:502 +0x6e
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: reflect.Value.call(0xc420318f60, 0xc4202ec088, 0x13, 0x19eea87, 0x4, 0xc4203a4f20, 0x3, 0x3, 0xc42002d6e8, 0xc420398028, ...)
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: 	/usr/local/go/src/reflect/value.go:434 +0x905
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: reflect.Value.Call(0xc420318f60, 0xc4202ec088, 0x13, 0xc42002d720, 0x3, 0x3, 0xc400000002, 0x0, 0x0)
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: net/rpc.(*service).call(0xc4202f41c0, 0xc4202f60a0, 0xc4202f2018, 0xc42032a880, 0xc4202f05e0, 0x1864120, 0xc4202fd400, 0x16, 0x1864160, 0xc4202e7d70, ...)
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: created by net/rpc.(*Server).ServeCodec
2018-03-20T16:40:54.632-0500 [DEBUG] plugin.terraform-provider-vra7: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
2018/03/20 16:40:54 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: [unexpected EOF]
2018/03/20 16:40:54 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: [unexpected EOF]
2018/03/20 16:40:54 [TRACE] [walkValidate] Exiting eval tree: vra7_resource.RHEL_6_Full_Support_nonAA
2018/03/20 16:40:54 [TRACE] dag/walk: walking "provider.vra7 (close)"
2018/03/20 16:40:54 [TRACE] dag/walk: walking "meta.count-boundary (count boundary fixup)"
2018/03/20 16:40:54 [TRACE] vertex 'root.provider.vra7 (close)': walking
2018/03/20 16:40:54 [TRACE] vertex 'root.meta.count-boundary (count boundary fixup)': walking
2018/03/20 16:40:54 [TRACE] vertex 'root.provider.vra7 (close)': evaluating
2018/03/20 16:40:54 [TRACE] vertex 'root.meta.count-boundary (count boundary fixup)': evaluating
2018/03/20 16:40:54 [TRACE] [walkValidate] Entering eval tree: meta.count-boundary (count boundary fixup)
2018/03/20 16:40:54 [TRACE] root: eval: *terraform.EvalCountFixZeroOneBoundaryGlobal
2018/03/20 16:40:54 [TRACE] [walkValidate] Exiting eval tree: meta.count-boundary (count boundary fixup)
2018/03/20 16:40:54 [TRACE] [walkValidate] Entering eval tree: provider.vra7 (close)
2018/03/20 16:40:54 [TRACE] root: eval: *terraform.EvalCloseProvider
2018/03/20 16:40:54 [TRACE] [walkValidate] Exiting eval tree: provider.vra7 (close)
2018/03/20 16:40:54 [TRACE] dag/walk: walking "root"
2018/03/20 16:40:54 [TRACE] vertex 'root.root': walking
2018/03/20 16:40:54 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-03-20T16:40:54.633-0500 [DEBUG] plugin: plugin process exited: path=/Users/mbenkhal/TerraformPluginProject/bin/terraform-provider-vra7
2018-03-20T16:40:54.634-0500 [WARN ] plugin: error closing client during Kill: err="connection is shut down"

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

https://github.com/mbenkhal27/log/blob/master/crash.log

### Steps to Reproduce

terraform plan generates the error

### Additional Context

everything else is regular. Except that i have a VRA provider plugin added to terraform

**Comment by jbardin** [comment]
Hi @mbenkhal27,

You don't seem to have anything here any longer. Is there still an issue?

**Comment by mbenkhal27** [comment]
yes .

**Comment by jbardin** [comment]
Hi @mbenkhal27,

Can you provide some details about the problem you're having?
Feel free to edit the original post and add whatever information you have about the issue.

**Comment by mbenkhal27** [comment]
I have updated the old issue. Sorry for taking too long to reply
.

**Comment by jbardin** [comment]
Hi @mbenkhal27,

This crash is happening inside a provider, specifically one called terraform-provider-vra7.
This isn't a provider we maintain, so I can't migrate the issue automatically, but I think the repo you want is https://github.com/vmware/terraform-provider-vra7

**Comment by mbenkhal27** [comment]
okay
 thanks  alot
