### ISSUE TITLE
Hard crash after moving state

### ISSUE THREAD

**Issue by andyjp94** [hashicorp/terraform#17659]
### Terraform Version

```
Terraform v0.11.4
+ provider.aws v1.11.0
```

### Terraform Configuration Files

https://www.dropbox.com/sh/dyws2tfwn5srmkf/AACIH96m1tMNkJUQCReWuP1ka?dl=0

### Crash Output

https://gist.githubusercontent.com/andyjp94/4bfaff31d0cb8b9eec997878f1c52c73/raw/5a88a97beee5585dfd4649dae835e9e36baa4708/terraform.log
### Expected Behavior

I had several elastic beanstalk applications and environments in one file, decided to move them into a module. This worked, but they were seen as new resources. So I used ```terraform state mv``` to move the resources. I then ran terraform plan to see what it thought the state was. I expected it to show no difference
### Actual Behavior

Hard crash
```
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xaff2fc]

goroutine 9557 [running]:
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).evalTreeManagedResourceNoState(0xc4208fad08, 0x2, 0x2)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:238 +0x34c
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).EvalTree(0xc4208fad08, 0x28ed160, 0xc4208fad08)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:98 +0x6e
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x28ed160, 0xc4208fad08, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:113 +0x98f
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc42095bd50, 0x28ed160, 0xc4208fad08, 0xc420d831c0)
	/opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x3a0
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:310 +0x1248
```

I tried commenting out large sections as a very rudimentary debugging exercise and the problem did not go away.

### Steps to Reproduce

terraform init terraform plan

**Comment by andyjp94** [comment]
If someone is looking into this please could they comment so that I'm aware, really not looking forward to having to wipe the state file and re-import everything which is looking increasingly likely.
