### ISSUE TITLE
Terraform crashing when working with AWS Network LoadBalancers and/or Target Groups

### ISSUE THREAD

**Issue by timecast** [hashicorp/terraform#17798]
Hi, seems there is a regression(?) while working with Network LoadBalancers respective Target groups at AWS

### Terraform Version
Terraform v0.11.5
+ provider.aws v1.9.0

### Terraform Configuration Files
important content of
main.tf:

resource "aws_instance" "ABC-TEST-INSTANCE" {
  count                       = 1
  ami                         = "ami-1caef165"
  instance_type               = "t2.medium"
  associate_public_ip_address = "false"
  subnet_id                   = "${aws_subnet.vpc01subnet.id}"
  vpc_security_group_ids      = ["${aws_security_group.ABCSG01.id}"]
  key_name                    = "key"
  tags {
    "Name"                    = "abc-lab-a-instance"
  }
  root_block_device {
    volume_type               = "gp2"
    volume_size               = "100"
    delete_on_termination     = true
  }
}

resource "aws_lb" "ABC-TEST-NLB" {
  name            = "abc-lab-a-nlb"
  internal        = true
  load_balancer_type = "network"
  subnets         = ["${aws_subnet.vpc01subnet.id}"]
}

resource "aws_lb_target_group" "ABC-TEST-TG" {
  name     = "abc-lab-a-tg"
  port     = 22
  protocol = "TCP"
  vpc_id   = "${module.vpc01.vpc_id}"
}

resource "aws_lb_target_group_attachment" "ABC-TEST-NLB" {
  target_group_arn = "${aws_lb_target_group.ABC-TEST-TG.arn}"
  target_id = "${aws_instance.ABC-TEST-INSTANCE.id}"
  port = "22"
}

resource "aws_lb_listener" "ABC-TEST-LISTENER" {
  load_balancer_arn = "${aws_lb.ABC-TEST-NLB.arn}"
  port = 22
  protocol = "TCP"
  "default_action" {
    target_group_arn = "${aws_lb_target_group.ABC-TEST-TG.arn}"
    type = "forward"
  }
}

resource "aws_vpc_endpoint_service" "ABC-TEST-VPCENDPOINTSERVICE" {
  acceptance_required = false
  network_load_balancer_arns = ["${aws_lb.ABC-TEST-NLB.arn}"]
}

resource "aws_vpc_endpoint" "ABC-TEST" {
  vpc_id            = "${module.vpc02.vpc_id}"
  service_name      = "${aws_vpc_endpoint_service.ABC-TEST-VPCENDPOINTSERVICE.service_name}"
  vpc_endpoint_type = "Interface"
  security_group_ids = ["${aws_security_group.ABCSG02.id}"]
  subnet_ids = ["${aws_subnet.vpc02subnet.id}"]
}

### Debug Output
module.vpc02.aws_default_route_table.default: Creation complete after 1s (ID: rtb-0074477ed7d84fbf5)

Error: Error applying plan:

9 error(s) occurred:

* aws_security_group.ABCSG02: 1 error(s) occurred:

* aws_security_group.ABCSG02: unexpected EOF
* module.vpc02.aws_default_security_group.default: 1 error(s) occurred:

* aws_default_security_group.default: unexpected EOF
* aws_subnet.vpc02subnet: 1 error(s) occurred:

* aws_subnet.vpc02subnet: unexpected EOF
* aws_lb.ABC-TEST-NLB: 1 error(s) occurred:

* aws_lb.ABC-TEST-NLB: unexpected EOF
* module.vpc01.aws_default_network_acl.default: 1 error(s) occurred:

* aws_default_network_acl.default: unexpected EOF
* module.vpc01.aws_default_security_group.default: 1 error(s) occurred:

* aws_default_security_group.default: unexpected EOF
* aws_security_group.ABCSG01: 1 error(s) occurred:

* aws_security_group.ABCSG01: unexpected EOF
* module.vpc02.aws_default_network_acl.default: 1 error(s) occurred:

* aws_default_network_acl.default: unexpected EOF
* aws_lb_target_group.ABC-TEST-TG: 1 error(s) occurred:

* aws_lb_target_group.ABC-TEST-TG: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

panic: runtime error: invalid memory address or nil pointer dereference
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x28ab83d]
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: 
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: goroutine 605 [running]:
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.flattenAwsLbTargetGroupResource(0xc42026a690, 0x31685a0, 0xc420208a00, 0xc420b72090, 0x0, 0xc420b44330)
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_lb_target_group.go:529 +0x62d
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLbTargetGroupRead(0xc42026a690, 0x31685a0, 0xc420208a00, 0x0, 0x0)
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_lb_target_group.go:273 +0x28b
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLbTargetGroupUpdate(0xc42026a690, 0x31685a0, 0xc420208a00, 0x0, 0x0)
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_lb_target_group.go:371 +0x178
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLbTargetGroupCreate(0xc42026a690, 0x31685a0, 0xc420208a00, 0xc42026a690, 0x0)
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_lb_target_group.go:251 +0x8f9
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc42073d420, 0xc42086c280, 0xc42091a8c0, 0x31685a0, 0xc420208a00, 0x1, 0xc420a0c840, 0x1000f0100000000)
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:227 +0x364
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc42073d570, 0xc42086c230, 0xc42086c280, 0xc42091a8c0, 0x5f7a6c8, 0x0, 0x1000)
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa4
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc420484440, 0xc42091a820, 0xc420918670, 0x0, 0x0)
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: reflect.Value.call(0xc4201ca6c0, 0xc420696000, 0x13, 0x3569fe8, 0x4, 0xc420aecf20, 0x3, 0x3, 0x10036d3, 0x1, ...)
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: 	/usr/local/go/src/reflect/value.go:434 +0x905
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: reflect.Value.Call(0xc4201ca6c0, 0xc420696000, 0x13, 0xc4207bcf20, 0x3, 0x3, 0x50a3140, 0xc42060d020, 0xc42033b900)
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: net/rpc.(*service).call(0xc4205ea100, 0xc420884000, 0xc4208fa050, 0xc4205c2000, 0xc420281c40, 0x2cd30a0, 0xc42091a820, 0x16, 0x2cd30e0, 0xc420918670, ...)
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: created by net/rpc.(*Server).ServeCodec
2018-04-06T14:31:20.963+0200 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
2018/04/06 14:31:20 [TRACE] root.vpc02: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root.vpc01: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root.vpc02: eval: *terraform.EvalApplyProvisioners
2018/04/06 14:31:20 [TRACE] root.vpc01: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalIf
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalWriteDiff
2018/04/06 14:31:20 [TRACE] root.vpc01: eval: *terraform.EvalApplyProvisioners
2018/04/06 14:31:20 [TRACE] root.vpc01: eval: *terraform.EvalApplyProvisioners
2018/04/06 14:31:20 [TRACE] root.vpc01: eval: *terraform.EvalIf
2018/04/06 14:31:20 [TRACE] root.vpc01: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root.vpc01: eval: *terraform.EvalWriteDiff
2018/04/06 14:31:20 [TRACE] root.vpc01: eval: *terraform.EvalApplyPost
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [ERROR] root.vpc01: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* aws_default_network_acl.default: unexpected EOF
2018/04/06 14:31:20 [ERROR] root.vpc01: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_default_network_acl.default: unexpected EOF
2018/04/06 14:31:20 [TRACE] [walkApply] Exiting eval tree: module.vpc01.aws_default_network_acl.default
2018/04/06 14:31:20 [TRACE] root.vpc01: eval: *terraform.EvalIf
2018/04/06 14:31:20 [TRACE] root.vpc01: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root.vpc01: eval: *terraform.EvalWriteDiff
2018/04/06 14:31:20 [TRACE] root.vpc01: eval: *terraform.EvalApplyPost
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalIf
2018/04/06 14:31:20 [ERROR] root.vpc01: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* aws_default_security_group.default: unexpected EOF
2018/04/06 14:31:20 [ERROR] root.vpc01: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_default_security_group.default: unexpected EOF
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalWriteDiff
2018/04/06 14:31:20 [TRACE] [walkApply] Exiting eval tree: module.vpc01.aws_default_security_group.default
2018/04/06 14:31:20 [TRACE] root.vpc02: eval: *terraform.EvalIf
2018-04-06T14:31:20.966+0200 [DEBUG] plugin: plugin process exited: path=/Users/foe/Documents/FOE/foe/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.9.0_x4
2018/04/06 14:31:20 [TRACE] root.vpc02: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root.vpc02: eval: *terraform.EvalWriteDiff
2018/04/06 14:31:20 [TRACE] root.vpc02: eval: *terraform.EvalApplyPost
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalIf
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalIf
2018/04/06 14:31:20 [TRACE] root.vpc02: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root.vpc02: eval: *terraform.EvalApplyProvisioners
2018/04/06 14:31:20 [TRACE] root.vpc02: eval: *terraform.EvalIf
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalApplyPost
2018/04/06 14:31:20 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* aws_security_group.ABCSG02: unexpected EOF
2018/04/06 14:31:20 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_security_group.ABCSG02: unexpected EOF
2018/04/06 14:31:20 [TRACE] [walkApply] Exiting eval tree: aws_security_group.ABCSG02
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalIf
2018/04/06 14:31:20 [TRACE] dag/walk: upstream errored, not walking "aws_security_group_rule.OUT02"
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalWriteDiff
2018/04/06 14:31:20 [ERROR] root.vpc02: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* aws_default_network_acl.default: unexpected EOF
2018/04/06 14:31:20 [ERROR] root.vpc02: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_default_network_acl.default: unexpected EOF
2018/04/06 14:31:20 [TRACE] dag/walk: upstream errored, not walking "aws_security_group_rule.IN02"
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalWriteDiff
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalApplyPost
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* aws_subnet.vpc02subnet: unexpected EOF
2018/04/06 14:31:20 [TRACE] root.vpc02: eval: *terraform.EvalWriteState
2018/04/06 14:31:20 [TRACE] root.vpc02: eval: *terraform.EvalWriteDiff
2018/04/06 14:31:20 [TRACE] root.vpc02: eval: *terraform.EvalApplyPost
2018/04/06 14:31:20 [ERROR] root.vpc02: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* aws_default_security_group.default: unexpected EOF
2018/04/06 14:31:20 [ERROR] root.vpc02: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_default_security_group.default: unexpected EOF
2018/04/06 14:31:20 [TRACE] [walkApply] Exiting eval tree: module.vpc02.aws_default_security_group.default
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalWriteDiff
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalApplyPost
2018/04/06 14:31:20 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* aws_lb_target_group.ABC-TEST-TG: unexpected EOF
2018/04/06 14:31:20 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_lb_target_group.ABC-TEST-TG: unexpected EOF
2018/04/06 14:31:20 [TRACE] [walkApply] Exiting eval tree: aws_lb_target_group.ABC-TEST-TG
2018/04/06 14:31:20 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_subnet.vpc02subnet: unexpected EOF
2018/04/06 14:31:20 [TRACE] [walkApply] Exiting eval tree: aws_subnet.vpc02subnet
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalApplyPost
2018/04/06 14:31:20 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* aws_security_group.ABCSG01: unexpected EOF
2018/04/06 14:31:20 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_security_group.ABCSG01: unexpected EOF
2018/04/06 14:31:20 [TRACE] [walkApply] Exiting eval tree: aws_security_group.ABCSG01
2018/04/06 14:31:20 [TRACE] [walkApply] Exiting eval tree: module.vpc02.aws_default_network_acl.default
2018/04/06 14:31:20 [TRACE] dag/walk: upstream errored, not walking "aws_security_group_rule.OUT01"
2018/04/06 14:31:20 [TRACE] root: eval: *terraform.EvalApplyPost
2018/04/06 14:31:20 [TRACE] dag/walk: upstream errored, not walking "aws_instance.ABC-TEST-INSTANCE"
2018/04/06 14:31:20 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* aws_lb.ABC-TEST-NLB: unexpected EOF
2018/04/06 14:31:20 [TRACE] dag/walk: upstream errored, not walking "aws_lb_target_group_attachment.ABC-TEST-NLB"
2018/04/06 14:31:20 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_lb.ABC-TEST-NLB: unexpected EOF
2018/04/06 14:31:20 [TRACE] [walkApply] Exiting eval tree: aws_lb.ABC-TEST-NLB
2018/04/06 14:31:20 [TRACE] dag/walk: upstream errored, not walking "aws_security_group_rule.IN01"
2018/04/06 14:31:20 [TRACE] dag/walk: upstream errored, not walking "aws_vpc_endpoint_service.ABC-TEST-VPCENDPOINTSERVICE"
2018/04/06 14:31:20 [TRACE] dag/walk: upstream errored, not walking "aws_lb_listener.ABC-TEST-LISTENER"
2018/04/06 14:31:20 [TRACE] dag/walk: upstream errored, not walking "aws_vpc_endpoint.ABC-TEST"
2018/04/06 14:31:20 [TRACE] dag/walk: upstream errored, not walking "provider.aws (close)"
2018/04/06 14:31:20 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2018/04/06 14:31:20 [TRACE] dag/walk: upstream errored, not walking "root"
2018/04/06 14:31:20 [TRACE] Preserving existing state lineage "cbfdb538-6457-cffe-4daa-e06525000dc0"
2018/04/06 14:31:20 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-04-06T14:31:20.969+0200 [WARN ] plugin: error closing client during Kill: err="connection is shut down"

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Crash Output
attached
[crash.log](https://github.com/hashicorp/terraform/files/1883957/crash.log)

### Expected Behavior
was working fine before

### Actual Behavior
it crashes as soon as we start working with Network Loadbalancers

### Steps to Reproduce
run terraform apply

**Comment by bflad** [comment]
Hi @timecast :wave: Sorry you ran into trouble here. Due to an ELBv2 service upgrade that started around March 27, 2018, the `aws_lb_target_group` resource you are using requires an update. The fix has been released in [version 1.13.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1130-march-28-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
