### ISSUE TITLE
Terraform crashes when trying to create an Azure VM from a Packer image

### ISSUE THREAD

**Issue by craiger821** [hashicorp/terraform#18204]
### Terraform Version
```
Terraform v0.11.7
+ provider.azurerm v0.3.3
```

### Terraform Configuration Files

```hcl
#Assume that custom image has been already created in the 'customimage' resource group
data "azurerm_image" "image" {
  name                = "CRB-Windows2016-US-IIS-2018-06-01T1826"
  resource_group_name = "PZI-GXUS-N-RGP-CSND-P014"
}

provider "azurerm" {
  subscription_id = "${var.azure_subscription_id}"
  client_id       = "${var.azure_client_id}"
  client_secret   = "${var.azure_client_secret}"
  tenant_id       = "${var.azure_tenant_id}"
  version         = "~> 0.1"
}

resource "azurerm_resource_group" "packer" {
  name     = "PZI-GXUS-N-RGP-CPOC-P008"
  location = "East US"
}

resource "azurerm_virtual_network" "packer" {
  name                = "acctvn"
  address_space       = ["172.168.0.0/16"]
  location            = "${azurerm_resource_group.packer.location}"
  resource_group_name = "${azurerm_resource_group.packer.name}"
}

resource "azurerm_subnet" "app" {
  name                 = "packerappsub"
  resource_group_name  = "${azurerm_resource_group.packer.name}"
  virtual_network_name = "${azurerm_virtual_network.packer.name}"
  address_prefix       = "172.168.2.0/24"
}

resource "azurerm_subnet" "db" {
  name                 = "packerdbsub"
  resource_group_name  = "${azurerm_resource_group.packer.name}"
  virtual_network_name = "${azurerm_virtual_network.packer.name}"
  address_prefix       = "172.168.3.0/24"
}

resource "azurerm_subnet" "web" {
  name                 = "packerwebsub"
  resource_group_name  = "${azurerm_resource_group.packer.name}"
  virtual_network_name = "${azurerm_virtual_network.packer.name}"
  address_prefix       = "172.168.4.0/24"
}

resource "azurerm_network_interface" "web" {
  count               = "${var.web_instance_count}"
  name                = "packerwebnic${count.index+1}"
  location            = "${azurerm_resource_group.packer.location}"
  resource_group_name = "${azurerm_resource_group.packer.name}"

  ip_configuration {
    name                          = "ipconfig1"
    subnet_id                     = "${azurerm_subnet.web.id}"
    private_ip_address_allocation = "dynamic"
  }
}

resource "azurerm_virtual_machine" "web" {
  count                 = "${var.web_instance_count}"
  name                  = "packerwebvm${count.index+1}"
  location              = "${azurerm_resource_group.packer.location}"
  resource_group_name   = "${azurerm_resource_group.packer.name}"
  network_interface_ids = ["${element(azurerm_network_interface.web.*.id, count.index)}"]
  vm_size               = "Standard_DS1_v2"

  # Uncomment this line to delete the OS disk automatically when deleting the VM
  delete_os_disk_on_termination = true

  # Uncomment this line to delete the data disks automatically when deleting the VM
  delete_data_disks_on_termination = true

  storage_image_reference {
    id = "${data.azurerm_image.image.id}"
  }

  storage_os_disk {
    name              = "packerwebvm-osdisk${count.index+1}"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

  # Optional data disks
  storage_data_disk {
    name              = "packerwebvm-datadisk01-${count.index+1}"
    managed_disk_type = "Standard_LRS"
    create_option     = "Empty"
    lun               = 0
    disk_size_gb      = "128"
  }

  os_profile {
    computer_name  = "packerwebvm${count.index+1}"
    admin_username = "testadmin"
    admin_password = "P@ssw0rd12345!"
  }

  os_profile_windows_config {
    provision_vm_agent        = "true"
    enable_automatic_upgrades = "true"
  }

  tags {
    environment = "Packer-Test"
  }
}
```

### Crash Output

```
C:\Tools\terraform>terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.azurerm_image.image: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.azurerm_image.image: 1 error(s) occurred:

* data.azurerm_image.image: data.azurerm_image.image: unexpected EOF


panic: runtime error: index out of range
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe:
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe: goroutine 40 [running]:
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm.flattenAzureRmImageDataDisks(0xc04218a5b0, 0xc0428e4a80, 0x7, 0x13ff8c0, 0xc0428e4b00)
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_image.go:331 +0x529
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm.dataSourceArmImageRead(0xc04218a5b0, 0x1576e20, 0xc0423c0000, 0xc0428e0a70, 0xd)
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/data_source_image.go:119 +0x645
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc0422cf140, 0xc0428e28e0, 0x1576e20, 0xc0423c0000, 0xc0423991a8, 0xc0421e9d01, 0x80000000018)
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:259 +0xb7
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc0422d03f0, 0xc04207c050, 0xc0428e28e0, 0xb0000, 0x0, 0x18)
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:398 +0xa1
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ReadDataApply(0xc0424cd440, 0xc0424d7700, 0xc0424d7870, 0x0, 0x0)
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:565 +0x55
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe: reflect.Value.call(0xc04210d800, 0xc0420053f8, 0x13, 0x162bf71, 0x4, 0xc042445f20, 0x3, 0x3, 0x8, 0x1, ...)
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe:       /usr/local/go/src/reflect/value.go:434 +0x90d
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe: reflect.Value.Call(0xc04210d800, 0xc0420053f8, 0x13, 0xc042445f20, 0x3, 0x3, 0x6, 0x6, 0x1)
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe:       /usr/local/go/src/reflect/value.go:302 +0xab
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe: net/rpc.(*service).call(0xc0421f1e00, 0xc0424ce050, 0xc0422b7b70, 0xc04214e680, 0xc042140fc0, 0x13e0000, 0xc0424d7700, 0x16, 0x13e0040, 0xc0424d7870, ...)
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe:       /usr/local/go/src/net/rpc/server.go:381 +0x149
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe: created by net/rpc.(*Server).ServeCodec
2018-06-07T18:14:42.917Z [DEBUG] plugin.terraform-provider-azurerm_v0.3.3_x4.exe:       /usr/local/go/src/net/rpc/server.go:475 +0x372
2018/06/07 18:14:42 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.azurerm_image.image: unexpected EOF
2018/06/07 18:14:42 [ERROR] root: eval: *terraform.EvalSequence, err: data.azurerm_image.image: unexpected EOF
2018/06/07 18:14:42 [TRACE] [walkRefresh] Exiting eval tree: data.azurerm_image.image
2018/06/07 18:14:42 [TRACE] dag/walk: upstream errored, not walking "provider.azurerm (close)"
2018/06/07 18:14:42 [TRACE] dag/walk: upstream errored, not walking "root"
2018/06/07 18:14:42 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-06-07T18:14:42.919Z [WARN ] plugin: error closing client during Kill: err="stream closed"
2018-06-07T18:14:42.928Z [DEBUG] plugin: plugin process exited: path=C:\Tools\terraform\.terraform\plugins\windows_amd64\terraform-provider-azurerm_v0.3.3_x4.exe



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Expected Behavior
Output plan

### Actual Behavior
Terraform crashed

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by catsby** [comment]
Hello there! 

This panic was fixed in https://github.com/terraform-providers/terraform-provider-azurerm/pull/589 and subsequently released in version 1.0.0 of this Provider.

If possible please upgrade to v1.0.0 or newer to get the fix. 

Thanks! Because this is fixed I'm going to go ahead and close this for now.
