### ISSUE TITLE
fresh Vagrant container cannot successfully pass tests

### ISSUE THREAD

**Issue by 5forcegees** [hashicorp/terraform#18613]
I'm trying to get started with some contributions to terraform and running into some issues with the unchanged code base (as of today).

Three things:
1. The Vagrantfile does not install 'make', which is required to begin doing things
2. The code fails the initial format check
3. The tests do not pass, even without any code changes (some of this is timeouts, which might be ok, but there are also other failing things, hopefully not due to running `make fmt`)

Here is my output from the container (after installing make):

```
vagrant@terraform:/opt/gopath/src/github.com/hashicorp/terraform$ make tools
go get -u github.com/kardianos/govendor
go get -u golang.org/x/tools/cmd/stringer
go get -u golang.org/x/tools/cmd/cover
vagrant@terraform:/opt/gopath/src/github.com/hashicorp/terraform$ make test
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
./terraform/interpolate_test.go
./command/format/plan_test.go
You can use the command: `make fmt` to reformat code.
Makefile:85: recipe for target 'fmtcheck' failed
make: *** [fmtcheck] Error 1
vagrant@terraform:/opt/gopath/src/github.com/hashicorp/terraform$ make fmt
gofmt -w $(find . -name '*.go' | grep -v vendor)
vagrant@terraform:/opt/gopath/src/github.com/hashicorp/terraform$ make test
==> Checking that code complies with gofmt requirements...
go generate ./...
2018/08/06 22:26:40 Generated command/internal_plugin_list.go
go list ./... | xargs -t -n4 go test  -timeout=60s -parallel=4
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform github.com/hashicorp/terraform/backend github.com/hashicorp/terraform/backend/atlas github.com/hashicorp/terraform/backend/init
ok  	github.com/hashicorp/terraform	0.174s
ok  	github.com/hashicorp/terraform/backend	0.024s
2018/08/06 22:31:09 [DEBUG] GET https://atlas.hashicorp.com/api/v1/terraform/state/hashicorp/test-remote-state?atlas_run_id=
2018/08/06 22:31:10 [ERR] GET https://atlas.hashicorp.com/api/v1/terraform/state/hashicorp/test-remote-state?atlas_run_id= request failed: Get https://atlas.hashicorp.com/api/v1/terraform/state/hashicorp/test-remote-state?atlas_run_id=: dial tcp: lookup atlas.hashicorp.com on 192.168.65.1:53: no such host
2018/08/06 22:31:10 [DEBUG] GET https://atlas.hashicorp.com/api/v1/terraform/state/hashicorp/test-remote-state?atlas_run_id=: retrying in 1s (4 left)
--- FAIL: TestStateClient_noRetryOnBadCerts (2.95s)
	state_client_test.go:79: retried after certificate error
2018/08/06 22:31:11 [DEBUG] New state was assigned lineage "b3de74d2-6bf5-07f8-b2fd-90085bd19afd"
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "b3de74d2-6bf5-07f8-b2fd-90085bd19afd"
2018/08/06 22:31:11 [INFO] state modified during read or write. incrementing serial number
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "b3de74d2-6bf5-07f8-b2fd-90085bd19afd"
2018/08/06 22:31:11 [DEBUG] PUT http://127.0.0.1:35379/api/v1/terraform/state/someuser/some-test-remote-state?atlas_run_id=
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [DEBUG] PUT http://127.0.0.1:36661/api/v1/terraform/state/someuser/some-test-remote-state?atlas_run_id=
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [DEBUG] PUT http://127.0.0.1:33079/api/v1/terraform/state/someuser/some-test-remote-state?atlas_run_id=
2018/08/06 22:31:11 [DEBUG] Handling Atlas conflict response: Conflict
2018/08/06 22:31:11 [DEBUG] Atlas reported conflict, checking for equivalent states.
2018/08/06 22:31:11 [DEBUG] GET http://127.0.0.1:33079/api/v1/terraform/state/someuser/some-test-remote-state?atlas_run_id=
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [DEBUG] States are not equivalent, returning conflict.
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [DEBUG] PUT http://127.0.0.1:43555/api/v1/terraform/state/someuser/some-test-remote-state?atlas_run_id=
2018/08/06 22:31:11 [DEBUG] Handling Atlas conflict response: Conflict
2018/08/06 22:31:11 [DEBUG] Atlas reported conflict, checking for equivalent states.
2018/08/06 22:31:11 [DEBUG] GET http://127.0.0.1:43555/api/v1/terraform/state/someuser/some-test-remote-state?atlas_run_id=
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [DEBUG] States are equivalent, incrementing serial and retrying.
2018/08/06 22:31:11 [TRACE] Preserving existing state lineage "c00ad9ac-9b35-42fe-846e-b06f0ef877e9"
2018/08/06 22:31:11 [DEBUG] PUT http://127.0.0.1:43555/api/v1/terraform/state/someuser/some-test-remote-state?atlas_run_id=
2018/08/06 22:31:11 [DEBUG] Handling Atlas conflict response: Conflict
2018/08/06 22:31:11 [DEBUG] Already attempted conflict resolution; returning conflict.
FAIL
FAIL	github.com/hashicorp/terraform/backend/atlas	3.979s
ok  	github.com/hashicorp/terraform/backend/init	1.228s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/backend/legacy github.com/hashicorp/terraform/backend/local github.com/hashicorp/terraform/backend/remote github.com/hashicorp/terraform/backend/remote-state
ok  	github.com/hashicorp/terraform/backend/legacy	0.020s
ok  	github.com/hashicorp/terraform/backend/local	0.521s
ok  	github.com/hashicorp/terraform/backend/remote	11.675s
ok  	github.com/hashicorp/terraform/backend/remote-state	0.021s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/backend/remote-state/azure github.com/hashicorp/terraform/backend/remote-state/consul github.com/hashicorp/terraform/backend/remote-state/etcdv3 github.com/hashicorp/terraform/backend/remote-state/gcs
ok  	github.com/hashicorp/terraform/backend/remote-state/azure	0.014s
ok  	github.com/hashicorp/terraform/backend/remote-state/consul	0.014s
ok  	github.com/hashicorp/terraform/backend/remote-state/etcdv3	0.019s
ok  	github.com/hashicorp/terraform/backend/remote-state/gcs	0.022s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/backend/remote-state/inmem github.com/hashicorp/terraform/backend/remote-state/manta github.com/hashicorp/terraform/backend/remote-state/s3 github.com/hashicorp/terraform/backend/remote-state/swift
ok  	github.com/hashicorp/terraform/backend/remote-state/inmem	0.026s
ok  	github.com/hashicorp/terraform/backend/remote-state/manta	0.017s
ok  	github.com/hashicorp/terraform/backend/remote-state/s3	0.025s
ok  	github.com/hashicorp/terraform/backend/remote-state/swift	0.018s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/builtin/bins/provider-test github.com/hashicorp/terraform/builtin/bins/provisioner-chef github.com/hashicorp/terraform/builtin/bins/provisioner-file github.com/hashicorp/terraform/builtin/bins/provisioner-habitat
?   	github.com/hashicorp/terraform/builtin/bins/provider-test	[no test files]
?   	github.com/hashicorp/terraform/builtin/bins/provisioner-chef	[no test files]
?   	github.com/hashicorp/terraform/builtin/bins/provisioner-file	[no test files]
?   	github.com/hashicorp/terraform/builtin/bins/provisioner-habitat	[no test files]
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/builtin/bins/provisioner-local-exec github.com/hashicorp/terraform/builtin/bins/provisioner-remote-exec github.com/hashicorp/terraform/builtin/bins/provisioner-salt-masterless github.com/hashicorp/terraform/builtin/providers/terraform
?   	github.com/hashicorp/terraform/builtin/bins/provisioner-local-exec	[no test files]
?   	github.com/hashicorp/terraform/builtin/bins/provisioner-remote-exec	[no test files]
?   	github.com/hashicorp/terraform/builtin/bins/provisioner-salt-masterless	[no test files]
ok  	github.com/hashicorp/terraform/builtin/providers/terraform	0.389s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/builtin/providers/test github.com/hashicorp/terraform/builtin/provisioners/chef github.com/hashicorp/terraform/builtin/provisioners/file github.com/hashicorp/terraform/builtin/provisioners/habitat
ok  	github.com/hashicorp/terraform/builtin/providers/test	4.488s
ok  	github.com/hashicorp/terraform/builtin/provisioners/chef	0.059s
ok  	github.com/hashicorp/terraform/builtin/provisioners/file	0.012s
ok  	github.com/hashicorp/terraform/builtin/provisioners/habitat	0.020s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/builtin/provisioners/local-exec github.com/hashicorp/terraform/builtin/provisioners/remote-exec github.com/hashicorp/terraform/builtin/provisioners/salt-masterless github.com/hashicorp/terraform/command
ok  	github.com/hashicorp/terraform/builtin/provisioners/local-exec	0.107s
ok  	github.com/hashicorp/terraform/builtin/provisioners/remote-exec	2.031s
ok  	github.com/hashicorp/terraform/builtin/provisioners/salt-masterless	0.020s
panic: test timed out after 1m0s

goroutine 262 [running]:
testing.startAlarm.func1()
	/opt/go/src/testing/testing.go:1145 +0xf9
created by time.goFunc
	/opt/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc420140d20, 0x308e520, 0x15, 0x3108db0, 0x491a01)
	/opt/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc420140d20)
	/opt/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc420140d20, 0xc4201c3da8)
	/opt/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc420301c00, 0x506bea0, 0x149, 0x149, 0x3)
	/opt/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc420555f18, 0x5095fb0)
	/opt/go/src/testing/testing.go:921 +0x111
github.com/hashicorp/terraform/command.TestMain(0xc4201c3f18)
	/opt/gopath/src/github.com/hashicorp/terraform/command/command_test.go:66 +0x7b
main.main()
	github.com/hashicorp/terraform/command/_test/_testmain.go:698 +0xdb

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/opt/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/opt/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/opt/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 240 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x68c8, 0xc42004d668, 0x1000004, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc420450a20, 0xc420450a20, 0x0, 0x0)
	/opt/go/src/os/wait_waitid.go:31 +0xa5
os.(*Process).wait(0xc420450a20, 0xc42006e500, 0xc420528658, 0x68)
	/opt/go/src/os/exec_unix.go:22 +0x42
os.(*Process).Wait(0xc420450a20, 0x0, 0x0, 0x310cf40)
	/opt/go/src/os/exec.go:115 +0x2b
os/exec.(*Cmd).Wait(0xc420528580, 0x0, 0x0)
	/opt/go/src/os/exec/exec.go:446 +0x62
os/exec.(*Cmd).Run(0xc420528580, 0xc420341f80, 0xc420528580)
	/opt/go/src/os/exec/exec.go:289 +0x5c
os/exec.(*Cmd).CombinedOutput(0xc420528580, 0x2, 0xc420039e60, 0x4, 0x4, 0xc420528580)
	/opt/go/src/os/exec/exec.go:506 +0x127
github.com/hashicorp/terraform/command.testLockState(0x306d780, 0xa, 0xc420450930, 0x2a, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/command_test.go:623 +0x289
github.com/hashicorp/terraform/command.TestApply_lockedState(0xc420141590)
	/opt/gopath/src/github.com/hashicorp/terraform/command/apply_test.go:59 +0x77
testing.tRunner(0xc420141590, 0x3108db0)
	/opt/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/opt/go/src/testing/testing.go:789 +0x2de

goroutine 241 [IO wait]:
internal/poll.runtime_pollWait(0x7f3aa2667f70, 0x72, 0x1)
	/opt/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42006e5b8, 0x72, 0xffffffffffffff01, 0x4f3b2a0, 0x4f2e9a8)
	/opt/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42006e5b8, 0xc420504601, 0x200, 0x200)
	/opt/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42006e5a0, 0xc420504600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/opt/go/src/internal/poll/fd_unix.go:125 +0x18a
os.(*File).read(0xc4202f8568, 0xc420504600, 0x200, 0x200, 0x0, 0xc420522de8, 0x4e9b8b)
	/opt/go/src/os/file_unix.go:216 +0x4e
os.(*File).Read(0xc4202f8568, 0xc420504600, 0x200, 0x200, 0x1, 0x0, 0xc420011a40)
	/opt/go/src/os/file.go:103 +0x6d
bytes.(*Buffer).ReadFrom(0xc420341f80, 0x4f37120, 0xc4202f8568, 0x7f3aa26283c0, 0xc420341f80, 0x1)
	/opt/go/src/bytes/buffer.go:209 +0x177
io.copyBuffer(0x4f30a60, 0xc420341f80, 0x4f37120, 0xc4202f8568, 0x0, 0x0, 0x0, 0xff, 0xc420522f40, 0x45fab6)
	/opt/go/src/io/io.go:386 +0x2bb
io.Copy(0x4f30a60, 0xc420341f80, 0x4f37120, 0xc4202f8568, 0x248c813c00000008, 0x5b68cff3, 0xc420522f98)
	/opt/go/src/io/io.go:362 +0x68
os/exec.(*Cmd).writerDescriptor.func1(0x4fe730, 0xc420141590)
	/opt/go/src/os/exec/exec.go:264 +0x4d
os/exec.(*Cmd).Start.func1(0xc420528580, 0xc4203df7c0)
	/opt/go/src/os/exec/exec.go:380 +0x27
created by os/exec.(*Cmd).Start
	/opt/go/src/os/exec/exec.go:379 +0x646
FAIL	github.com/hashicorp/terraform/command	60.029s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/command/clistate github.com/hashicorp/terraform/command/e2etest github.com/hashicorp/terraform/command/format github.com/hashicorp/terraform/communicator
?   	github.com/hashicorp/terraform/command/clistate	[no test files]
SIGQUIT: quit
PC=0x483af8 m=0 sigcode=0

goroutine 1 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x6f9c, 0xc4201e3b78, 0x1000004, 0x0, 0x0, 0x7f75581beed8, 0x0, 0x0)
	/opt/go/src/syscall/asm_linux_amd64.s:44 +0x5 fp=0xc4201e3b20 sp=0xc4201e3b18 pc=0x483ad5
os.(*Process).blockUntilWaitable(0xc42001c690, 0xc42001c690, 0x0, 0x0)
	/opt/go/src/os/wait_waitid.go:31 +0xa5 fp=0xc4201e3c28 sp=0xc4201e3b20 pc=0x4a61a5
os.(*Process).wait(0xc42001c690, 0xc42006d130, 0xc42009ed38, 0x4)
	/opt/go/src/os/exec_unix.go:22 +0x42 fp=0xc4201e3cb0 sp=0xc4201e3c28 pc=0x49f282
os.(*Process).Wait(0xc42001c690, 0x0, 0x0, 0xd3c2f0)
	/opt/go/src/os/exec.go:115 +0x2b fp=0xc4201e3ce0 sp=0xc4201e3cb0 pc=0x49e7cb
os/exec.(*Cmd).Wait(0xc42009ec60, 0x0, 0x0)
	/opt/go/src/os/exec/exec.go:446 +0x62 fp=0xc4201e3d68 sp=0xc4201e3ce0 pc=0x5577f2
os/exec.(*Cmd).Run(0xc42009ec60, 0x2, 0xc4201e3e00)
	/opt/go/src/os/exec/exec.go:289 +0x5c fp=0xc4201e3d90 sp=0xc4201e3d68 pc=0x556bfc
github.com/hashicorp/terraform/e2e.GoBuild(0xd1d8d8, 0x1e, 0xd0cce0, 0x9, 0x40deba, 0xbcfbc0)
	/opt/gopath/src/github.com/hashicorp/terraform/e2e/e2e.go:245 +0x1a7 fp=0xc4201e3e50 sp=0xc4201e3d90 pc=0xb499d7
github.com/hashicorp/terraform/command/e2etest.setup(0xc4201627b0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/e2etest/main_test.go:36 +0x10f fp=0xc4201e3ee0 sp=0xc4201e3e50 pc=0xb4ec1f
github.com/hashicorp/terraform/command/e2etest.TestMain(0xc4201e3f18)
	/opt/gopath/src/github.com/hashicorp/terraform/command/e2etest/main_test.go:15 +0x22 fp=0xc4201e3f10 sp=0xc4201e3ee0 pc=0xb4eac2
main.main()
	github.com/hashicorp/terraform/command/e2etest/_test/_testmain.go:60 +0xdb fp=0xc4201e3f80 sp=0xc4201e3f10 pc=0xb5181b
runtime.main()
	/opt/go/src/runtime/proc.go:185 +0x20d fp=0xc4201e3fe0 sp=0xc4201e3f80 pc=0x42e97d
runtime.goexit()
	/opt/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4201e3fe8 sp=0xc4201e3fe0 pc=0x45e2e1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/opt/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/opt/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/opt/go/src/os/signal/signal_unix.go:28 +0x41

rax    0xf7
rbx    0x0
rcx    0x483afa
rdx    0xc4201e3b78
rdi    0x1
rsi    0x6f9c
rbp    0xc4201e3c18
rsp    0xc4201e3b18
r8     0x0
r9     0x0
r10    0x1000004
r11    0x212
r12    0x4794d3
r13    0xff
r14    0xff
r15    0x21
rip    0x483af8
rflags 0x212
cs     0x33
fs     0x0
gs     0x0
*** Test killed: ran too long (2m0s).
FAIL	github.com/hashicorp/terraform/command/e2etest	210.373s
ok  	github.com/hashicorp/terraform/command/format	0.017s
ok  	github.com/hashicorp/terraform/communicator	1.056s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/communicator/remote github.com/hashicorp/terraform/communicator/shared github.com/hashicorp/terraform/communicator/ssh github.com/hashicorp/terraform/communicator/winrm
ok  	github.com/hashicorp/terraform/communicator/remote	0.017s [no tests to run]
ok  	github.com/hashicorp/terraform/communicator/shared	0.009s
ok  	github.com/hashicorp/terraform/communicator/ssh	0.445s
ok  	github.com/hashicorp/terraform/communicator/winrm	0.040s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/config github.com/hashicorp/terraform/config/configschema github.com/hashicorp/terraform/config/hcl2shim github.com/hashicorp/terraform/config/module
ok  	github.com/hashicorp/terraform/config	1.327s
ok  	github.com/hashicorp/terraform/config/configschema	0.021s
ok  	github.com/hashicorp/terraform/config/hcl2shim	0.006s
ok  	github.com/hashicorp/terraform/config/module	0.812s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/configs github.com/hashicorp/terraform/configs/configload github.com/hashicorp/terraform/dag github.com/hashicorp/terraform/digraph
ok  	github.com/hashicorp/terraform/configs	0.613s
ok  	github.com/hashicorp/terraform/configs/configload	0.116s
ok  	github.com/hashicorp/terraform/dag	2.480s
ok  	github.com/hashicorp/terraform/digraph	0.009s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/e2e github.com/hashicorp/terraform/flatmap github.com/hashicorp/terraform/helper/acctest github.com/hashicorp/terraform/helper/config
?   	github.com/hashicorp/terraform/e2e	[no test files]
ok  	github.com/hashicorp/terraform/flatmap	0.011s
?   	github.com/hashicorp/terraform/helper/acctest	[no test files]
ok  	github.com/hashicorp/terraform/helper/config	0.019s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/helper/copy github.com/hashicorp/terraform/helper/customdiff github.com/hashicorp/terraform/helper/didyoumean github.com/hashicorp/terraform/helper/diff
?   	github.com/hashicorp/terraform/helper/copy	[no test files]
ok  	github.com/hashicorp/terraform/helper/customdiff	0.021s
ok  	github.com/hashicorp/terraform/helper/didyoumean	0.010s
ok  	github.com/hashicorp/terraform/helper/diff	0.025s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/helper/encryption github.com/hashicorp/terraform/helper/experiment github.com/hashicorp/terraform/helper/hashcode github.com/hashicorp/terraform/helper/hilmapstructure
?   	github.com/hashicorp/terraform/helper/encryption	[no test files]
ok  	github.com/hashicorp/terraform/helper/experiment	0.006s
ok  	github.com/hashicorp/terraform/helper/hashcode	0.016s
?   	github.com/hashicorp/terraform/helper/hilmapstructure	[no test files]
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/helper/logging github.com/hashicorp/terraform/helper/mutexkv github.com/hashicorp/terraform/helper/pathorcontents github.com/hashicorp/terraform/helper/resource
?   	github.com/hashicorp/terraform/helper/logging	[no test files]
ok  	github.com/hashicorp/terraform/helper/mutexkv	0.057s
ok  	github.com/hashicorp/terraform/helper/pathorcontents	0.006s
ok  	github.com/hashicorp/terraform/helper/resource	3.084s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/helper/schema github.com/hashicorp/terraform/helper/shadow github.com/hashicorp/terraform/helper/signalwrapper github.com/hashicorp/terraform/helper/slowmessage
ok  	github.com/hashicorp/terraform/helper/schema	0.123s
ok  	github.com/hashicorp/terraform/helper/shadow	0.172s
ok  	github.com/hashicorp/terraform/helper/signalwrapper	0.029s
ok  	github.com/hashicorp/terraform/helper/slowmessage	0.106s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/helper/structure github.com/hashicorp/terraform/helper/validation github.com/hashicorp/terraform/helper/variables github.com/hashicorp/terraform/helper/wrappedreadline
ok  	github.com/hashicorp/terraform/helper/structure	0.016s
ok  	github.com/hashicorp/terraform/helper/validation	0.020s
ok  	github.com/hashicorp/terraform/helper/variables	0.025s
?   	github.com/hashicorp/terraform/helper/wrappedreadline	[no test files]
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/helper/wrappedstreams github.com/hashicorp/terraform/httpclient github.com/hashicorp/terraform/moduledeps github.com/hashicorp/terraform/plugin
?   	github.com/hashicorp/terraform/helper/wrappedstreams	[no test files]
ok  	github.com/hashicorp/terraform/httpclient	0.012s
ok  	github.com/hashicorp/terraform/moduledeps	0.022s
ok  	github.com/hashicorp/terraform/plugin	0.080s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/plugin/discovery github.com/hashicorp/terraform/registry github.com/hashicorp/terraform/registry/regsrc github.com/hashicorp/terraform/registry/response
ok  	github.com/hashicorp/terraform/plugin/discovery	0.130s
ok  	github.com/hashicorp/terraform/registry	0.177s
ok  	github.com/hashicorp/terraform/registry/regsrc	0.010s
ok  	github.com/hashicorp/terraform/registry/response	0.005s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/registry/test github.com/hashicorp/terraform/repl github.com/hashicorp/terraform/scripts github.com/hashicorp/terraform/state
?   	github.com/hashicorp/terraform/registry/test	[no test files]
ok  	github.com/hashicorp/terraform/repl	0.030s
ok  	github.com/hashicorp/terraform/scripts	0.181s
ok  	github.com/hashicorp/terraform/state	29.152s
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/state/remote github.com/hashicorp/terraform/svchost github.com/hashicorp/terraform/svchost/auth github.com/hashicorp/terraform/svchost/auth/test-helper
ok  	github.com/hashicorp/terraform/state/remote	0.103s
ok  	github.com/hashicorp/terraform/svchost	0.005s
ok  	github.com/hashicorp/terraform/svchost/auth	0.647s
?   	github.com/hashicorp/terraform/svchost/auth/test-helper	[no test files]
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/svchost/disco github.com/hashicorp/terraform/terraform github.com/hashicorp/terraform/tfdiags github.com/hashicorp/terraform/tools/terraform-bundle
ok  	github.com/hashicorp/terraform/svchost/disco	0.048s
ok  	github.com/hashicorp/terraform/terraform	13.213s
ok  	github.com/hashicorp/terraform/tfdiags	0.032s
?   	github.com/hashicorp/terraform/tools/terraform-bundle	[no test files]
go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/tools/terraform-bundle/e2etest github.com/hashicorp/terraform/version
ok  	github.com/hashicorp/terraform/tools/terraform-bundle/e2etest	38.857s
?   	github.com/hashicorp/terraform/version	[no test files]
Makefile:35: recipe for target 'test' failed
make: *** [test] Error 123
```

### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by tmccombs** [comment]
I've noticed that every time I run `make dev`, I then have to run `make fmt` again before any other make command works. I think that the gofmt check is checking generated files that aren't properly formatted or something.
