### ISSUE TITLE
Terraform Crashed When Using New Relic Terraform Provider

### ISSUE THREAD

**Issue by jaloren** [hashicorp/terraform#19090]
### Terraform Version

11.6

### Crash Output

Gist of crash output

https://gist.github.com/jaloren/b50b3276d2c14103d30b88672caae9f1

### Expected Behavior

successfully apply the plan

### Actual Behavior
terraform crashes

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

**Comment by jaloren** [comment]
Hi @bflad,

 I tried running it with parallelism is 1, still got a crash. The rest of the output is similar to the gist I put in the ticket summary

```
jlorenzini@jlorenzini-mb infrastructure$ terraform apply -parallelism=1 -var-file .secrets/secrets.tfvars 
newrelic_alert_policy.system: Refreshing state... (ID: 326011)
newrelic_alert_policy.docker: Refreshing state... (ID: 324754)
newrelic_alert_policy.docker: Refreshing state... (ID: 324750)
newrelic_alert_policy.system: Refreshing state... (ID: 325999)
newrelic_alert_policy.mysql: Refreshing state... (ID: 329329)

Error: Error refreshing state: 5 error(s) occurred:

* module.devqa_docker.newrelic_alert_policy.docker: 1 error(s) occurred:

* module.devqa_docker.newrelic_alert_policy.docker: newrelic_alert_policy.docker: connection is shut down
* module.prod_system.newrelic_alert_policy.system: 1 error(s) occurred:

* module.prod_system.newrelic_alert_policy.system: newrelic_alert_policy.system: connection is shut down
* module.prod_docker.newrelic_alert_policy.docker: 1 error(s) occurred:

* module.prod_docker.newrelic_alert_policy.docker: newrelic_alert_policy.docker: connection is shut down
* module.devqa_system.newrelic_alert_policy.system: 1 error(s) occurred:

* module.devqa_system.newrelic_alert_policy.system: newrelic_alert_policy.system: unexpected EOF
* module.prod_mysql_lead_distribution_rackspace_master.module.mysql_common.newrelic_alert_policy.mysql: 1 error(s) occurred:

* module.prod_mysql_lead_distribution_rackspace_master.module.mysql_common.newrelic_alert_policy.mysql: newrelic_alert_policy.mysql: connection is shut down


panic: Error reading level state: strconv.ParseInt: parsing "2018-10-11T22:23:58Z": invalid syntax
```

**Comment by jaloren** [comment]
Looked in the state file and only found two instances of that timestamp that the panic happened on.

```
    "resources": {
                "newrelic_alert_policy.system": {
                    "type": "newrelic_alert_policy",
                    "depends_on": [],
                    "primary": {
                        "id": "326011",
                        "attributes": {
                            "created_at": "2018-10-11T22:23:58Z",
                            "id": "326011",
                            "incident_preference": "PER_CONDITION_AND_TARGET",
                            "name": "Infra-System-devqa",
                            "updated_at": "2018-10-11T22:23:58Z"
                        },   
                        "meta": {},
                        "tainted": false
                    },   
                    "deposed": [],
                    "provider": "provider.newrelic"
                }
```

**Comment by jaloren** [comment]
Some specific stack trace that would helpful i think:

```
2018-10-16T12:38:56.927-0500 [DEBUG] plugin.terraform-provider-newrelic: 
2018-10-16T12:38:56.927-0500 [DEBUG] plugin.terraform-provider-newrelic: goroutine 120 [running]:
2018-10-16T12:38:56.927-0500 [DEBUG] plugin.terraform-provider-newrelic: github.com/terraform-providers/terraform-provider-newrelic/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc4202302a0, 0xc4205a0500, 0x1, 0x1, 0xc4201b9008, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-10-16T12:38:56.927-0500 [DEBUG] plugin.terraform-provider-newrelic: 	/Volumes/Repositories/go/src/github.com/terraform-providers/terraform-provider-newrelic/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:480 +0x44b
2018-10-16T12:38:56.927-0500 [DEBUG] plugin.terraform-provider-newrelic: github.com/terraform-providers/terraform-provider-newrelic/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).State(0xc4202302a0, 0x15f9d60)
2018-10-16T12:38:56.927-0500 [DEBUG] plugin.terraform-provider-newrelic: 	/Volumes/Repositories/go/src/github.com/terraform-providers/terraform-provider-newrelic/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:285 +0x331
2018-10-16T12:38:56.927-0500 [DEBUG] plugin.terraform-provider-newrelic: github.com/terraform-providers/terraform-provider-newrelic/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc42028baa0, 0xc4200d22d0, 0x15f9d60, 0xc420177880, 0xc4200c15d0, 0x10ba801, 0x15fc660)
2018-10-16T12:38:56.927-0500 [DEBUG] plugin.terraform-provider-newrelic: 	/Volumes/Repositories/go/src/github.com/terraform-providers/terraform-provider-newrelic/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:322 +0x197
2018-10-16T12:38:56.927-0500 [DEBUG] plugin.terraform-provider-newrelic: github.com/terraform-providers/terraform-provider-newrelic/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4201ce000, 0xc4200d2280, 0xc4200d22d0, 0x18, 0x18, 0xc42035c360)
2018-10-16T12:38:56.927-0500 [DEBUG] plugin.terraform-provider-newrelic: 	/Volumes/Repositories/go/src/github.com/terraform-providers/terraform-provider-newrelic/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:284 +0x9a
2018-10-16T12:38:56.927-0500 [DEBUG] plugin.terraform-provider-newrelic: github.com/terraform-providers/terraform-provider-newrelic/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4201769c0, 0xc4204b4010, 0xc4204b4260, 0x0, 0x0)
2018-10-16T12:38:56.927-0500 [DEBUG] plugin.terraform-provider-newrelic: 	/Volumes/Repositories/go/src/github.com/terraform-providers/terraform-provider-newrelic/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
2018-10-16T12:38:56.928-0500 [DEBUG] plugin.terraform-provider-newrelic: reflect.Value.call(0xc42028ac00, 0xc4200d0938, 0x13, 0x172b744, 0x4, 0xc42031ff18, 0x3, 0x3, 0xc4201886c0, 0xc42029d6e8, ...)
2018-10-16T12:38:56.928-0500 [DEBUG] plugin.terraform-provider-newrelic: 	/usr/local/go/src/reflect/value.go:447 +0x969
2018-10-16T12:38:56.928-0500 [DEBUG] plugin.terraform-provider-newrelic: reflect.Value.Call(0xc42028ac00, 0xc4200d0938, 0x13, 0xc42029d718, 0x3, 0x3, 0xc4200b7c50, 0xc400000003, 0x0)
2018-10-16T12:38:56.928-0500 [DEBUG] plugin.terraform-provider-newrelic: 	/usr/local/go/src/reflect/value.go:308 +0xa4
2018-10-16T12:38:56.928-0500 [DEBUG] plugin.terraform-provider-newrelic: net/rpc.(*service).call(0xc420329840, 0xc420172640, 0xc4200c7918, 0xc4200c7930, 0xc42018ba00, 0xc420177600, 0x15fc620, 0xc4204b4010, 0x16, 0x15fc660, ...)
2018-10-16T12:38:56.928-0500 [DEBUG] plugin.terraform-provider-newrelic: 	/usr/local/go/src/net/rpc/server.go:384 +0x14e
2018-10-16T12:38:56.928-0500 [DEBUG] plugin.terraform-provider-newrelic: created by net/rpc.(*Server).ServeCodec
2018-10-16T12:38:56.928-0500 [DEBUG] plugin.terraform-provider-newrelic: 	/usr/local/go/src/net/rpc/server.go:480 +0x43a
2018/10/16 12:38:56 [ERROR] root.prod_docker: eval: *terraform.EvalRefresh, err: newrelic_alert_policy.docker: unexpected EOF
2018/10/16 12:38:56 [ERROR] root.prod_docker: eval: *terraform.EvalSequence, err: newrelic_alert_policy.docker: unexpected EOF
2018/10/16 12:38:56 [TRACE] [walkRefresh] Exiting eval tree: module.prod_docker.newrelic_alert_policy.docker
2018/10/16 12:38:56 [TRACE] root.prod_system: eval: *terraform.EvalSequence

```

**Comment by apparentlymart** [comment]
Hi @jaloren! Sorry for this crash.

From looking at the history of the New Relic provider source code it looks like an earlier version of the provider used integer timestamps here rather than the strings it now expects, and that you have saved in the state file.

That change was made without increasing the "schema version" number on the resource, and so Terraform was unable to detect the problem and advise you to use a newer version of the provider; instead, the the older provider version attempted to parse a state that is incompatible with it, and crashed. (Normally when making a breaking change the provider schema would have its version incremented, which then lets Terraform recognize when the installed provider version is too old and produce an error rather than crashing.)

It seems like using a new version of the provider should help here, since the latest source code in [the provider repository](https://github.com/terraform-providers/terraform-provider-newrelic) shows these two attributes as being defined as strings and handled as timestamps. If that doesn't help, I'd recommend opening an issue in the New Relic provider repository where the maintainers will have deeper knowledge of the provider and the decisions made there and may be able to help further.

Sorry again for this crash!
