### ISSUE TITLE
Terraform crash on plan

### ISSUE THREAD

**Issue by bensojona** [hashicorp/terraform#19134]
### Terraform Version
```
Terraform v0.11.8
+ provider.aws v1.41.0
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.vault v1.1.4
```

### Terraform Configuration Files
This is a private repo - but I'm a Hashi employee so just reach out on Slack (Jon Benson) and I'll point you to the repo.

### Debug Output
https://gist.github.com/bensojona/47cbbc54bd4b3a7d2050ae5809612180

### Crash Output
https://gist.github.com/bensojona/59cbd8909c0ad42c47e182a2c65bbb8f

### Expected Behavior
Successful `terraform plan`

### Actual Behavior
Terraform crashed

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Additional Context
This worked previously, my suspicion is one of the providers I'm using (aws?) is failing. Tried different versions of both `aws` and `vault` provider but couldn't get it to work.

**Comment by bflad** [comment]
Crash portion of the log:

```
2018-10-19T11:01:53.257-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: panic: runtime error: invalid memory address or nil pointer dereference
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2ac1207]
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: 
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: goroutine 4106 [running]:
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.hasLaunchPermission(0xc005a64a80, 0xc0091c9e80, 0x15, 0xc005d43b30, 0xc, 0xc000894d90, 0xc006a73a18, 0x18a6f98)
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ami_launch_permission.go:109 +0x137
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsAmiLaunchPermissionExists(0xc000894d90, 0x37abba0, 0xc00dcd9800, 0xc000894d90, 0x0, 0x0)
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ami_launch_permission.go:41 +0x101
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc00dc91dc0, 0xc00f08e410, 0x37abba0, 0xc00dcd9800, 0xc00a3b8bd8, 0x10bc601, 0x32a2b40)
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:329 +0x314
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc002e909a0, 0xc00f08e3c0, 0xc00f08e410, 0xc00007f400, 0xc000a48480, 0x7b95d80)
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x92
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc00d84b520, 0xc0049d9820, 0xc0049d99d0, 0x0, 0x0)
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: reflect.Value.call(0xc000152960, 0xc018d50990, 0x13, 0x3d09df6, 0x4, 0xc006a73f18, 0x3, 0x3, 0xc00a87c440, 0xc000144c00, ...)
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: 	/opt/goenv/versions/1.11.1/src/reflect/value.go:447 +0x449
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: reflect.Value.Call(0xc000152960, 0xc018d50990, 0x13, 0xc01252e718, 0x3, 0x3, 0x11d710b, 0xc01252e728, 0x100010000)
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: 	/opt/goenv/versions/1.11.1/src/reflect/value.go:308 +0xa4
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: net/rpc.(*service).call(0xc011a26bc0, 0xc00adbdcc0, 0xc0047b9af8, 0xc0047b9b10, 0xc017487c00, 0xc006ca0000, 0x32a2b00, 0xc0049d9820, 0x16, 0x32a2b40, ...)
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: 	/opt/goenv/versions/1.11.1/src/net/rpc/server.go:384 +0x14e
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: created by net/rpc.(*Server).ServeCodec
2018-10-19T11:01:53.258-0700 [DEBUG] plugin.terraform-provider-aws_v1.41.0_x4: 	/opt/goenv/versions/1.11.1/src/net/rpc/server.go:481 +0x47e
```

I'll have our GitHub bot automatically migrate this issue over to https://github.com/terraform-providers/terraform-provider-aws for further triage. 👍
