### ISSUE TITLE
terraform provider crash

### ISSUE THREAD

**Issue by navreddy36** [hashicorp/terraform#19192]
Error: Error applying plan:
 
1 error(s) occurred:
 
* venafi_certificate.webserver: 1 error(s) occurred:
 
* venafi_certificate.webserver: unexpected EOF
 
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
 
 
panic: runtime error: invalid memory address or nil pointer dereference
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc935b3]
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi: 
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi: goroutine 42 [running]:
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi: github.com/Venafi/govcert.(*client).Do(0xc4202a4d80, 0x146daa0, 0xc4200b5140, 0xd3e740, 0xfc63e8, 0x409c01, 0xc42003e8f0)
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi:        /home/centos/go/src/github.com/Venafi/govcert/govcert.go:120 +0x4d3
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi: github.com/Venafi/terraform-provider-venafi/venafi.resourceVenafiCertificateCreate(0xc4201f5ce0, 0xd0ebc0, 0xc4202a4de0, 0xc4201f5ce0, 0x0)
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi:        /home/centos/go/src/github.com/Venafi/terraform-provider-venafi/venafi/resource_venafi_certificate.go:142 +0x699
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4201da880, 0xc4201d06e0, 0xc4202b9780, 0xd0ebc0, 0xc4202a4de0, 0x1, 0xc4202c6570, 0xc4202c6570)
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi:        /home/centos/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:265 +0x376
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4201f4af0, 0xc4201d0690, 0xc4201d06e0, 0xc4202b9780, 0x7f6655e7c000, 0x0, 0x18)
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi:        /home/centos/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa4
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4201cdea0, 0xc4202b9360, 0xc4202c2fd0, 0x0, 0x0)
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi:        /home/centos/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:530 +0x57
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi: reflect.Value.call(0xc420059a40, 0xc42000fd28, 0x13, 0xebd30e, 0x4, 0xc42003ef20, 0x3, 0x3, 0xc42002bee8, 0xc420113918, ...)
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi:        /usr/lib/golang/src/reflect/value.go:434 +0x905
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi: reflect.Value.Call(0xc420059a40, 0xc42000fd28, 0x13, 0xc42002bf20, 0x3, 0x3, 0xc400000004, 0x0, 0x0)
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi:        /usr/lib/golang/src/reflect/value.go:302 +0xa4
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi: net/rpc.(*service).call(0xc4201e9500, 0xc4201d0410, 0xc4202a8320, 0xc4201da980, 0xc4202b8460, 0xd0f900, 0xc4202b9360, 0x16, 0xd0f940, 0xc4202c2fd0, ...)
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi:        /usr/lib/golang/src/net/rpc/server.go:381 +0x142
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi: created by net/rpc.(*Server).ServeCodec
2018-10-25T04:20:35.329Z [DEBUG] plugin.terraform-provider-venafi:        /usr/lib/golang/src/net/rpc/server.go:475 +0x36b
2018-10-25T04:20:35.329Z [DEBUG] plugin: plugin process exited: path=/root/.terraform.d/plugins/terraform-provider-venafi
2018/10/25 04:20:35 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-10-25T04:20:35.330Z [WARN ] plugin: error closing client during Kill: err="connection is shut down"
 
 
 
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.
 
When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.
 
[1]: https://github.com/hashicorp/terraform/issues
 
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jbardin** [comment]
Hi @navreddy36,

Sorry you ran into this, but this is a crash in the "venafi" provider. That provider isn't developed under the Terraform Providers organization, so I can't migrate the issue for you. You can open an issue in their repo, which appears to be located here: https://github.com/Venafi/terraform-provider-venafi.
