### ISSUE TITLE
"Unavailable desc = transport is closing" A

### ISSUE THREAD

**Issue by dgarstang** [hashicorp/terraform#19248]
When I apply JSON template below, I get this:
```
module.shipwire-alpha-legacy.aws_iam_role.iam_role: Modifying... [id=alpha-03]
module.shipwire-alpha-legacy.aws_security_group.security_group: Modifying... [id=sg-04e5bbd8917a71568]
module.shipwire-alpha-legacy.aws_security_group.security_group: Modifications complete after 0s [id=sg-04e5bbd8917a71568]
module.shipwire-alpha-legacy.aws_iam_role.iam_role: Modifications complete after 0s [id=alpha-03]
module.shipwire-alpha-legacy.aws_iam_instance_profile.iam_instance_profile: Modifying... [id=alpha-03]
module.shipwire-alpha-legacy.aws_iam_instance_profile.iam_instance_profile: Modifications complete after 0s [id=alpha-03]
module.shipwire-alpha-legacy.aws_instance.instance[0]: Creating...

Error: rpc error: code = Unavailable desc = transport is closing
```

Some of the details of the template have been obfuscated.
Versions:
Terraform v0.12.0-alpha1
+ provider.aws v1.40.0-5-g4f24bc8b7

```
{
  "variable": {
    "branch": {
      "default": "master"
    },
    "build_user": {
      "default": "jenkins"
    },
    "name": {
      "default": "noname"
    },
    "alpha-noname": {
      "default": "alpha-noname"
    },
    "comment": {
      "default": ""
    },
    "chef_client_version": {
      "default": "12.21.20"
    },
    "chef_run_list": {
      "default": ["role[alpha-web-init]"]
    },
    "chef_secret_key": {
      "default": "changeme"
    },
    "chef_server": {
      "default": "chef-dev1.aws.foocorp.com"
    },
    "created_by": {
      "default": "noone"
    },
    "dns_domain": {
      "default": "aws.foocorp.com"
    },
    "instance_alias": {
      "default": "alpha-noname"
    },
    "instance_count": {
      "default": "1"
    },
    "instance_ami_account_id": {
      "default": "000000000"
    },
    "instance_root_disk_size": {
      "default": "64"
    },
    "instance_root_disk_type": {
      "default": "gp2"
    },
    "instance_ssh_keypair": {
      "default": "was-oregon"
    },
    "instance_type": {
      "default": "t2.micro"
    },
    "chef_environment": {
      "default": "_alphas_php56"
    },
    "chef_org": {
      "default": "alphas"
    },
    "chef_provisioner_user_key": {},
    "chef_provisioner_user_name": {},
    "vpc_id": {
      "default": "vpc-dea168cc"
    }
  },
  "data": {
    "aws_subnet_ids": {
      "public": {
        "vpc_id": "${var.vpc_id}",
        "tags": {
          "Name": "public"
        }
      }
    },
    "aws_ami": {
      "image_id": {
        "most_recent": true,
        "owners": [
          "535472621492"
        ],
        "filter": {
          "name": "name",
          "values": [
            "alpha-L2-custom-${var.name}-*"
          ]
        }
      }
    },
    "aws_iam_policy_document": {
      "assumed_role_policy": {
        "statement": [
          {
            "sid": "",
            "actions": [
              "sts:AssumeRole"
            ],
            "principals": {
              "type": "Service",
              "identifiers": [
                "ec2.amazonaws.com"
              ]
            }
          }
        ]
      },
      "letsencrypt_certs": {
        "statement": [
          {
            "sid": "Stmt1495472332000",
            "actions": [
              "s3:GetObject",
              "s3:ListBucket"
            ],
            "resources": [
              "arn:aws:s3:::foo-letsencrypt-certs/${var.name}.aws.foocorp.com",
              "arn:aws:s3:::foo-letsencrypt-certs/${var.name}.aws.foocorp.com/*"
            ],
            "effect": "Allow"
          }
        ]
      },
      "artifact_store": {
        "statement": [
          {
            "sid": "Stmt1495472332000",
            "actions": [
              "s3:GetObject",
              "s3:ListBucket"
            ],
            "resources": [
              "arn:aws:s3:::foo-artifacts-store",
              "arn:aws:s3:::foo-artifacts-store/*"
            ],
            "effect": "Allow"
          }
        ]
      }
    }
  },
  "resource": {
    "aws_iam_role": {
      "iam_role": {
        "name": "${var.name}",
        "path": "/",
        "assume_role_policy": "${data.aws_iam_policy_document.assumed_role_policy.json}"
      }
    },
    "aws_iam_instance_profile": {
      "iam_instance_profile": {
        "name": "${var.name}",
        "role": "${aws_iam_role.iam_role.name}"
      }
    },
    "aws_iam_role_policy": {
      "letsencrypt_certs": {
        "name": "letsencrypt_certs",
        "role": "${aws_iam_role.iam_role.name}",
        "policy": "${data.aws_iam_policy_document.letsencrypt_certs.json}"
      },
      "artifact_store": {
        "name": "artifact_store",
        "role": "${aws_iam_role.iam_role.name}",
        "policy": "${data.aws_iam_policy_document.artifact_store.json}"
      }
    },
    "aws_security_group": {
      "security_group": {
        "name": "${var.name}",
        "description": "Ingress for Alpha Instance",
        "vpc_id": "${var.vpc_id}",
        "tags": {
          "Name": "${format(\"%s / %s\", var.name, var.instance_alias)}"
        },
        "egress": [
          {
            "from_port": "0",
            "to_port": "0",
            "protocol": "-1",
            "cidr_blocks": [
              "0.0.0.0/0"
            ]
          }
        ],
        "ingress": [
          {
            "description": "Office",
            "from_port": "0",
            "to_port": "0",
            "protocol": "-1",
            "cidr_blocks": [
              "1.1.1.1/32"
            ]
          },
          {
            "description": "bastion",
            "from_port": "0",
            "to_port": "0",
            "protocol": "-1",
            "cidr_blocks": [
              "1.1.1.1/32"
            ]
          },
          {
            "description": "bastion",
            "from_port": "0",
            "to_port": "0",
            "protocol": "-1",
            "cidr_blocks": [
              "1.1.1.1/32"
            ]
          },
          {
            "description": "Jenkins Slave 5",
            "from_port": "0",
            "to_port": "0",
            "protocol": "-1",
            "cidr_blocks": [
              "1.1.1.1/32"
            ]
          }
        ]
      }
    },
    "aws_instance": {
      "instance": {
        "count": "${var.instance_count}",
        "ami": "${data.aws_ami.image_id.id}",
        "instance_type": "${var.instance_type}",
        "key_name": "${var.instance_ssh_keypair}",
        "subnet_id": "subnet-288d284d",
        "user_data": "",
        "iam_instance_profile": "${aws_iam_instance_profile.iam_instance_profile.id}",
        "vpc_security_group_ids": [
          "${aws_security_group.security_group.id}"
        ],
        "root_block_device": {
          "volume_type": "${var.instance_root_disk_type}",
          "volume_size": "${var.instance_root_disk_size}",
          "delete_on_termination": true
        },
        "ephemeral_block_device": [
          {
            "device_name": "/dev/xvdb",
            "virtual_name": "ephemeral0",
            "no_device": "false"
          },
          {
            "device_name": "/dev/xvdc",
            "virtual_name": "ephemeral1",
            "no_device": "false"
          },
          {
            "device_name": "/dev/xvdd",
            "virtual_name": "ephemeral2",
            "no_device": "false"
          },
          {
            "device_name": "/dev/xvde",
            "virtual_name": "ephemeral3",
            "no_device": "false"
          }
        ],
        "volume_tags": {
          "Name": "${format(\"%s / %s\", var.name, var.instance_alias)}",
          "chef_environment": "${var.chef_environment}",
          "team": "SW",
          "terraform": "true",
          "is_alpha": "true",
          "created_by": "${var.created_by}",
          "comment": "${var.comment}"
        },
        "connection": {
          "host": "${self.public_ip}",
          "type": "${var.chef_provisioner_connection_type}",
          "user": "${var.chef_provisioner_connection_user}",
          "agent": "${var.chef_provisioner_connection_use_agent}",
          "timeout": "2m"
        },
        "provisioner": [
          {
            "file": {
              "source": "${path.module}/scripts/setup.sh",
              "destination": "/tmp/setup.sh"
            }
          },
          {
            "file": {
              "source": "${path.module}/scripts/post-install.sh",
              "destination": "/tmp/post-install.sh"
            }
          },
          {
            "remote-exec": {
              "inline": [
                "sudo chmod +x /tmp/setup.sh",
                "sudo chmod +x /tmp/post-install.sh",
                "/tmp/setup.sh ${var.name} ${var.branch}",
                "/tmp/post-install.sh"
              ]
            }
          },
          {
            "local-exec": {
              "command": "sleep 60"
            }
          },
          {
            "chef": {
              "environment": "${var.chef_environment}",
              "run_list": "${var.chef_run_list}",
              "node_name": "${format(\"%s.%s\", var.name, var.dns_domain)}",
              "server_url": "https://${var.chef_server}/organizations/${var.chef_org}",
              "user_name": "${var.chef_provisioner_user_name}",
              "user_key": "${file(var.chef_provisioner_user_key)}",
              "secret_key": "${var.chef_secret_key}",
              "version": "${var.chef_client_version}",
              "recreate_client": true,
              "fetch_chef_certificates": true,
              "skip_install": false
            }
          }
        ]
      }
    }
  }
}
```

**Comment by apparentlymart** [comment]
Hi @dgarstang! Thanks for reporting this.

It looks like the provider process crashed somehow, without producing any panic output. If possible, it'd be helpful to see the full trace log (with the `TF_LOG=trace` environment variable set) for this operation, which will hopefully include information about what crashed in the provider here.

If you're able to capture such a log, please share it as [a gist](https://gist.github.com/) because logs are too long to be readable in a GitHub comment.

**Comment by dgarstang** [comment]
Gist with debug output is at:
https://gist.github.com/dgarstang/5ea1b90f9342c53529fefdf76a06feb9

**Comment by apparentlymart** [comment]
Hi again @dgarstang!

Unfortunately it looks like the log you shared there is not complete because you answered "Yes" (capital Y) to the confirm prompt which Terraform did not interpret as confirmation and instead exited immediately. Would you mind doing that one more time with the apply steps included, since that's where the crash seemed to be in your initial report?

**Comment by dgarstang** [comment]
Sorry, here's another one... https://gist.github.com/dgarstang/8eabb4b3721890889d42a503bb085ee7

**Comment by apparentlymart** [comment]
Thanks @dgarstang! I found the following panic message in the logs:

```
panic: can't use ElementIterator on null value
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4:
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: goroutine 79 [running]:
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: github.com/zclconf/go-cty/cty.Value.ElementIterator(0x40de9c0, 0xc0007f86f0, 0x0, 0x0, 0x3df8b7f, 0x14)
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: 	/opt/gopath/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/zclconf/go-cty/cty/value_ops.go:858 +0xd3
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: github.com/hashicorp/terraform/terraform.newResourceConfigShimmedComputedKeys(0x40dea40, 0xc00000c838, 0x36db980, 0xc0009c7b30, 0xc0007f92d0, 0x0, 0x0, 0x17e7b2f, 0x36d9400, 0xc0009c7c50)
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: 	/opt/gopath/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/resource.go:298 +0xa39
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: github.com/hashicorp/terraform/terraform.NewResourceConfigShimmed(0x40dea40, 0xc00000c838, 0x36db980, 0xc0009c7b30, 0xc0007f92d0, 0xc0007c5040)
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: 	/opt/gopath/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/resource.go:239 +0x10c
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: github.com/hashicorp/terraform/helper/schema.diffFromValues(0x40dea40, 0xc00000c7c8, 0x0, 0x0, 0x40dea40, 0xc00000c838, 0x36db980, 0xc0009c7b30, 0xc00045cb00, 0x0, ...)
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: 	/opt/gopath/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/shims.go:30 +0xbe
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: github.com/hashicorp/terraform/helper/schema.DiffFromValues(0x40dea40, 0xc00000c7c8, 0x0, 0x0, 0x40dea40, 0xc00000c838, 0x36db980, 0xc0009c7b30, 0xc00045cb00, 0x0, ...)
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: 	/opt/gopath/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/shims.go:18 +0xa0
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000146ba0, 0x40dd940, 0xc0009c0930, 0xc000b7ca80, 0xc000146ba0, 0xc0009c08a0, 0x37b19a0)
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: 	/opt/gopath/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:584 +0x4c3
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: github.com/hashicorp/terraform/plugin/proto._Provider_ApplyResourceChange_Handler(0x3d01200, 0xc000146ba0, 0x40dd940, 0xc0009c0930, 0xc0001c1c70, 0x0, 0x0, 0x0, 0x0, 0x0)
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: 	/opt/gopath/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/proto/plugin.pb.go:2974 +0x23e
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004a6300, 0x40e68c0, 0xc00021cf00, 0xc000124d00, 0xc0002d39b0, 0x63e3720, 0x0, 0x0, 0x0)
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: 	/opt/gopath/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:982 +0x4cd
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: google.golang.org/grpc.(*Server).handleStream(0xc0004a6300, 0x40e68c0, 0xc00021cf00, 0xc000124d00, 0x0)
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: 	/opt/gopath/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:1208 +0x1308
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000132050, 0xc0004a6300, 0x40e68c0, 0xc00021cf00, 0xc000124d00)
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: 	/opt/gopath/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:686 +0x9f
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2018-11-02T10:17:07.910-0700 [DEBUG] plugin.terraform-provider-aws_v1.40.0-5-g4f24bc8b7_x4: 	/opt/gopath/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:684 +0xa1
```

This seems to be the same problem as in #19152, which has fortunately since been fixed in `master` and is included in [the subsequent alpha2 builds](https://releases.hashicorp.com/terraform/0.12.0-alpha2/). Hopefully if you repeat this with the alpha2 builds you'll see it work.

(Note that since the alpha builds have provider binaries embedded in them it's important to ensure that the providers from alpha1 are not still in the directory containing the `terraform` executable. The easiest way to ensure that is to extract alpha2 into a different directory, so that it won't be able to find the alpha1 provider builds.)

**Comment by apparentlymart** [comment]
Hi @dgarstang,

Since I didn't hear back from you and the stack trace here looks just like the one from #19152, I'm going to close this out now assuming that this one is also fixed, just to keep things updated here. If you find that isn't true, please let me know!

**Comment by bohdanyurov-gl** [comment]
@apparentlymart Still affects Terraform 0.12.2:

```
2019/06/20 16:49:17 [TRACE] GRPCProvider: ValidateDataSourceConfig
2019-06-20T16:49:17.066+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: panic: value is null
2019-06-20T16:49:17.066+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: 
2019-06-20T16:49:17.066+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: goroutine 383 [running]:
2019-06-20T16:49:17.066+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/zclconf/go-cty/cty.Value.AsString(...)
2019-06-20T16:49:17.066+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/zclconf/go-cty/cty/value_ops.go:1029
2019-06-20T16:49:17.066+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/convert.PathToAttributePath(0xc000998740, 0x4, 0x4, 0xc000a951a0)
2019-06-20T16:49:17.066+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/convert/diagnostics.go:114 +0xa04
2019-06-20T16:49:17.066+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/plugin.validateConfigNulls(0x5236d80, 0xc000840680, 0x48dbf40, 0xc000a948a0, 0xc000998740, 0x3, 0x4, 0x4, 0xc000a948a0, 0x0)
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:1312 +0x417
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/plugin.validateConfigNulls(0x5236d40, 0xc000b8a050, 0x4033f00, 0xc0006d86c0, 0xc000a94f20, 0x2, 0x2, 0x2, 0xc0006d86c0, 0x0)
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:1332 +0x6eb
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/plugin.validateConfigNulls(0x5236cc0, 0xc000840b10, 0x3bb0020, 0xc000a94b40, 0xc000840c50, 0x1, 0x1, 0x1, 0xc000a94b40, 0x0)
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:1317 +0x264
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/plugin.validateConfigNulls(0x5236d40, 0xc000b8a068, 0x4033f00, 0xc0006d8930, 0x0, 0x0, 0x0, 0x4033f00, 0xc0006d8930, 0x0)
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:1332 +0x6eb
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ValidateDataSourceConfig(0xc00000f0f0, 0x5235cc0, 0xc000996480, 0xc0009980c0, 0xc00000f0f0, 0xc000996480, 0xc000746bd0)
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:224 +0x1e1
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ValidateDataSourceConfig_Handler(0x48c5740, 0xc00000f0f0, 0x5235cc0, 0xc000996480, 0xc000156280, 0x0, 0x5235cc0, 0xc000996480, 0xc000dc6500, 0x279)
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:2929 +0x23e
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000588f00, 0x52564e0, 0xc000589800, 0xc000846000, 0xc000653d40, 0x8f21728, 0x0, 0x0, 0x0)
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:966 +0x470
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000588f00, 0x52564e0, 0xc000589800, 0xc000846000, 0x0)
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:1245 +0xd25
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000036f70, 0xc000588f00, 0x52564e0, 0xc000589800, 0xc000846000)
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:685 +0x9f
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: created by github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-06-20T16:49:17.067+0300 [DEBUG] plugin.terraform-provider-aws_v2.15.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:683 +0xa1
2019/06/20 16:49:17 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2019/06/20 16:49:17 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/06/20 16:49:17 [TRACE] [walkRefresh] Exiting eval tree: aws_route53_record.BLABLA-specific-MX[1]
```

**Comment by apparentlymart** [comment]
Hi @bohdanyurov-gl!

That is not the same problem as was fixed by this issue, even though the stack trace has the same function at the top of it. Could you please open a new issue for that and be sure to include all of the information requested by the issue template so that we can try to reproduce it? Thanks!

**Comment by bohdanyurov-gl** [comment]
Additional information:

```
data "aws_iam_policy_document" "ebs-volume-mount" {
  count = var.create ? 1 : 0

  version = "2012-10-17"

  statement {
    effect    = "Allow"
    resources = [
      aws_spot_instance_request.this[0].arn,
      aws_ebs_volume.data[0].arn,
    ]
    actions   = [
      "ec2:AttachVolume",
      "ec2:DetachVolume",
    ]
  }
```

Issue is present after changing **aws_instance** into **aws_spot_instance_request**.
