### ISSUE TITLE
When i'm trying to run terraform init . I get the below error.

### ISSUE THREAD

**Issue by spidermanintegration** [hashicorp/terraform#19458]
When i'm trying to run terraform init . I get the below error.

```
2018/11/24 21:39:45 [INFO] Terraform version: 0.12.0 alpha1 
2018/11/24 21:39:45 [INFO] Go runtime version: go1.11.1
2018/11/24 21:39:45 [INFO] CLI args: []string{"C:\\ProgramData\\chocolatey\\lib\\terraform\\tools\\terraform.exe", "plan"}
2018/11/24 21:39:45 [DEBUG] Attempting to open CLI config file: C:\Users\User\AppData\Roaming\terraform.rc
2018/11/24 21:39:45 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2018/11/24 21:39:45 [INFO] CLI command args: []string{"plan"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x7fb807]

goroutine 1 [running]:
github.com/hashicorp/hcl2/hcl/hclsyntax.(*Body).PartialContent(0x0, 0x5dc3ac0, 0x0, 0x0, 0x30001, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/structure.go:135 +0x87
github.com/hashicorp/terraform/configs.decodeResourceBlock(0xc00026fa00, 0x8, 0x34d9bef, 0x8, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/resource.go:88 +0x188
github.com/hashicorp/terraform/configs.(*Parser).loadConfigFile(0xc00043aa60, 0xc000468040, 0x9, 0x0, 0x0, 0x3824100, 0x9, 0x2)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/parser_config.go:115 +0xe2e
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigFile(0xc00043aa60, 0xc000468040, 0x9, 0x0, 0x0, 0x1, 0xc000468000)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/parser_config.go:22 +0x4b
github.com/hashicorp/terraform/configs.(*Parser).loadFiles(0xc00043aa60, 0xc00040e790, 0x1, 0x1, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/parser_config_dir.go:76 +0x347
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigDir(0xc00043aa60, 0x34d2955, 0x1, 0x0, 0x1, 0xc000411f20, 0x1)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/parser_config_dir.go:36 +0x12b
github.com/hashicorp/terraform/command.(*Meta).loadSingleModule(0xc00044c000, 0x34d2955, 0x1, 0x383dec0, 0xc00040d960, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_config.go:85 +0x15f
github.com/hashicorp/terraform/command.(*Meta).loadBackendConfig(0xc00044c000, 0xc0003d24e0, 0xe, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_config.go:122 +0x46
github.com/hashicorp/terraform/command.(*PlanCommand).Run(0xc00044c000, 0xc0000723f0, 0x0, 0x0, 0xc00040e240)
	/opt/gopath/src/github.com/hashicorp/terraform/command/plan.go:76 +0x7e2
github.com/mitchellh/cli.(*CLI).Run(0xc000412500, 0xc000412500, 0xc0003b9d20, 0x1)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:255 +0x20e
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:222 +0xad3
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:99 +0xbe
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:35 +0x35
```

**Comment by spidermanintegration** [comment]
Re-installed terrraform . Fixed the issue
