### ISSUE TITLE
azurerm_role_assignment: unexpected EOF

### ISSUE THREAD

**Issue by MysticRyuujin** [hashicorp/terraform#19675]
### Terraform Version

```
Terraform v0.11.10
+ provider.azurerm v1.20.0
```

### Terraform Configuration Files

```hcl
provider "azurerm" {
   subscription_id = "${var.subscription_id}"
   tenant_id       = "${var.tenant_id}"
}

resource "azurerm_role_assignment" "AAD_CloudReaders-Reader" {
  scope                = "/subscriptions/${var.subscription_id}"
  role_definition_name = "Reader"
  principal_id         = "643ee4af-520a-4dc8-a5ac-a18a6731eac2" # AAD_CloudReaders
}
```

### Debug Output

[Debug](https://gist.github.com/MysticRyuujin/f527ab141c3e4bf718f7e66899d97442)

### Crash Output

[Crash](https://gist.github.com/MysticRyuujin/71d94e822e6499d9c8c2b38310345553)

### Expected Behavior

Create the assignment, doesn't crash

### Actual Behavior

Creates the assignment, does crash

### Steps to Reproduce

```
az cloud set --name AzureUSGovernment
az login
terraform init
terraform apply
```

### Additional Context

The only other change to my environement is the use of a system proxy using
`set HTTP_PROXY=` and `set HTTPS_PROXY=`

**Comment by bflad** [comment]
Hi @MysticRyuujin 👋 Thanks for reporting this and apologies for the unexpected crash. Due to the crash log output below, the issue appears to be happening in the [Terraform AzureRM provider](https://github.com/terraform-providers/terraform-provider-azurerm/), which lives in a separate codebase from the core of Terraform here.

Snippet from crash log:

```
2018-12-17T11:19:46.759-0600 [DEBUG] plugin.terraform-provider-azurerm_v1.20.0_x4.exe: panic: runtime error: invalid memory address or nil pointer dereference
2018-12-17T11:19:46.759-0600 [DEBUG] plugin.terraform-provider-azurerm_v1.20.0_x4.exe: [signal 0xc0000005 code=0x0 addr=0x10 pc=0x1db229b]
2018-12-17T11:19:46.759-0600 [DEBUG] plugin.terraform-provider-azurerm_v1.20.0_x4.exe: 
2018-12-17T11:19:46.759-0600 [DEBUG] plugin.terraform-provider-azurerm_v1.20.0_x4.exe: goroutine 271 [running]:
2018-12-17T11:19:46.759-0600 [DEBUG] plugin.terraform-provider-azurerm_v1.20.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm.retryRoleAssignmentsClient.func1(0xc0000b6820)
2018-12-17T11:19:46.759-0600 [DEBUG] plugin.terraform-provider-azurerm_v1.20.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_role_assignment.go:192 +0x1db
2018-12-17T11:19:46.759-0600 [DEBUG] plugin.terraform-provider-azurerm_v1.20.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/resource.Retry.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2018-12-17T11:19:46.759-0600 [DEBUG] plugin.terraform-provider-azurerm_v1.20.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/resource/wait.go:22 +0x55
2018-12-17T11:19:46.759-0600 [DEBUG] plugin.terraform-provider-azurerm_v1.20.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState.func1(0xc0007082a0, 0xc00083ebd0, 0xc000716d00, 0xc00006d200, 0xc0006729b8, 0xc0006729b0)
2018-12-17T11:19:46.759-0600 [DEBUG] plugin.terraform-provider-azurerm_v1.20.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/resource/state.go:103 +0x2a5
2018-12-17T11:19:46.759-0600 [DEBUG] plugin.terraform-provider-azurerm_v1.20.0_x4.exe: created by github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState
2018-12-17T11:19:46.759-0600 [DEBUG] plugin.terraform-provider-azurerm_v1.20.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/resource/state.go:80 +0x1c0
```

I'm going to have our GitHub bot automatically migrate this issue so the maintainers of the correct codebase can troubleshoot this issue further. Thanks!
