### ISSUE TITLE
panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'

### ISSUE THREAD

**Issue by ntroast** [hashicorp/terraform#20389]
### Terraform Version

```
Terraform v0.11.11
+ provider.aws v1.59.0
```

### Terraform Configuration Files

```hcl
provider "aws" {
  version = ">= 1.47.0"
  region  = "us-west-2"
}

data "aws_vpcs" "production-vpcs" {}

output "production-vpcs" {
  value = "${data.aws_vpcs.production-vpcs.ids}"
}

data "aws_subnet_ids" "production-subnets" {
  count = "${length(data.aws_vpcs.production-vpcs.ids)}"
  vpc_id = "${data.aws_vpcs.production-vpcs.ids[count.index]}"
}

output "production-subnets" {
  value = "${data.aws_subnet_ids.production-subnets.*.ids}"
}

data "aws_nat_gateway" "production-nat-gateways" {
  count = "${length(data.aws_subnet_ids.production-subnets.*.ids)}"
  subnet_id = "${data.aws_subnet_ids.production-subnets.*.ids[count.index]}"
}

output "production-nat-gateways" {
  value = "${data.aws_nat_gateway.production-nat-gateways.*.ids}"
}
```

### Debug Output

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_vpcs.production-vpcs: Refreshing state...
data.aws_subnet_ids.production-subnets[2]: Refreshing state...
data.aws_subnet_ids.production-subnets[4]: Refreshing state...
data.aws_subnet_ids.production-subnets[0]: Refreshing state...
data.aws_subnet_ids.production-subnets[3]: Refreshing state...
data.aws_subnet_ids.production-subnets[1]: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.aws_nat_gateway.production-nat-gateways: 5 error(s) occurred:

* data.aws_nat_gateway.production-nat-gateways[1]: unexpected EOF
* data.aws_nat_gateway.production-nat-gateways[3]: unexpected EOF
* data.aws_nat_gateway.production-nat-gateways[0]: unexpected EOF
* data.aws_nat_gateway.production-nat-gateways[2]: unexpected EOF
* data.aws_nat_gateway.production-nat-gateways[4]: unexpected EOF


panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'
2019-02-19T18:28:34.693-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4:
2019-02-19T18:28:34.693-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: goroutine 120 [running]:
2019-02-19T18:28:34.693-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc0002d0230, 0xc0008a4f00, 0x1, 0x1, 0xc0008a4f12, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2019-02-19T18:28:34.693-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:509 +0x449
2019-02-19T18:28:34.693-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc0002d0230, 0x474aad2, 0x9, 0xc000ae1201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2019-02-19T18:28:34.693-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:480 +0x122
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc0002d0230, 0x474aad2, 0x9, 0xd0, 0x4370a80, 0x0, 0x0, 0xd0)
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:457 +0x97
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diffString(0xc00090c240, 0x474aad2, 0x9, 0xc0007094a0, 0xc000b91640, 0x4ad2ba0, 0xc0002d0230, 0xc000afc600, 0x0, 0x0)
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1158 +0xa0
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc00090c240, 0x474aad2, 0x9, 0xc0007094a0, 0xc0007be080, 0x4ad2ba0, 0xc0002d0230, 0xfc27e886a2ffce00, 0x0, 0x0)
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:774 +0x436
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc00090c240, 0x0, 0xc000d238f0, 0x0, 0x40679c0, 0xc0003bec00, 0x1032bcc, 0xc0004f2900, 0x1011c01)
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:424 +0x206
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc000704460, 0x0, 0xc000d238f0, 0x40679c0, 0xc0003bec00, 0xc000afcb01, 0x10bddbc, 0x3a05b60)
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:250 +0x17c
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataDiff(0xc000577c70, 0xc00081c460, 0xc000d238f0, 0xc0004f0000, 0xc000afcbf0, 0x955c440)
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:413 +0x9b
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ReadDataDiff(0xc000a5c860, 0xc0008a4c70, 0xc0008a4e40, 0x0, 0x0)
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:593 +0x4e
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: reflect.Value.call(0xc00016c7e0, 0xc00015a0a0, 0x13, 0x47420ad, 0x4, 0xc000afcf18, 0x3, 0x3, 0xc0009da600, 0xc0002ea400, ...)
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/goenv/versions/1.11.5/src/reflect/value.go:447 +0x454
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: reflect.Value.Call(0xc00016c7e0, 0xc00015a0a0, 0x13, 0xc0000d8718, 0x3, 0x3, 0xc000358f00, 0xc00013d101, 0x100000001)
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/goenv/versions/1.11.5/src/reflect/value.go:308 +0xa4
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: net/rpc.(*service).call(0xc0000401c0, 0xc0000a8780, 0xc0000361c0, 0xc0000361f0, 0xc0001c2a00, 0xc00012ff60, 0x3a05b20, 0xc0008a4c70, 0x16, 0x3a05b60, ...)
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/goenv/versions/1.11.5/src/net/rpc/server.go:384 +0x14e
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: created by net/rpc.(*Server).ServeCodec
2019-02-19T18:28:34.694-0800 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/goenv/versions/1.11.5/src/net/rpc/server.go:481 +0x47e
2019/02/19 18:28:34 [ERROR] root: eval: *terraform.EvalReadDataDiff, err: unexpected EOF
2019/02/19 18:28:34 [ERROR] root: eval: *terraform.EvalReadDataDiff, err: unexpected EOF
2019/02/19 18:28:34 [ERROR] root: eval: *terraform.EvalReadDataDiff, err: unexpected EOF
2019/02/19 18:28:34 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2019/02/19 18:28:34 [TRACE] [walkRefresh] Exiting eval tree: data.aws_nat_gateway.production-nat-gateways[1]
2019/02/19 18:28:34 [ERROR] root: eval: *terraform.EvalReadDataDiff, err: unexpected EOF
2019/02/19 18:28:34 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2019/02/19 18:28:34 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2019/02/19 18:28:34 [TRACE] [walkRefresh] Exiting eval tree: data.aws_nat_gateway.production-nat-gateways[3]
2019/02/19 18:28:34 [TRACE] [walkRefresh] Exiting eval tree: data.aws_nat_gateway.production-nat-gateways[0]
2019/02/19 18:28:34 [ERROR] root: eval: *terraform.EvalReadDataDiff, err: unexpected EOF
2019/02/19 18:28:34 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2019/02/19 18:28:34 [TRACE] [walkRefresh] Exiting eval tree: data.aws_nat_gateway.production-nat-gateways[2]
2019/02/19 18:28:34 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2019/02/19 18:28:34 [TRACE] [walkRefresh] Exiting eval tree: data.aws_nat_gateway.production-nat-gateways[4]
2019/02/19 18:28:34 [TRACE] dag/walk: upstream errored, not walking "root"
2019/02/19 18:28:34 [TRACE] dag/walk: upstream errored, not walking "output.production-nat-gateways"
2019/02/19 18:28:34 [TRACE] dag/walk: upstream errored, not walking "provider.aws (close)"
2019/02/19 18:28:34 [TRACE] dag/walk: upstream errored, not walking "root"
2019-02-19T18:28:34.697-0800 [DEBUG] plugin: plugin process exited: path=/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.59.0_x4
2019/02/19 18:28:34 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-02-19T18:28:34.697-0800 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
```

### Crash Output

Cannot post due to sensitive information

### Expected Behavior

It should have given a list of all the nat gateways in every subnet in every vpc

### Actual Behavior

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by lukewest** [comment]
I have a very similar bug when trying to get the vpc's based on a vpc name

vpc_name = "production VPC"

`# get the VPCs
data "aws_vpcs" "foo" {
        tags = {
                Name = "${local.vpc_name}"
        }
}

# get the subnets for the environment
data "aws_subnet_ids" "subnets" {
        vpc_id = "${data.aws_vpcs.foo.ids}"

        tags = {
                Name = "${local.subnet_name}"
        }
}`
