### ISSUE TITLE
Accidently Terraform crash on "terraform plan"

### ISSUE THREAD

**Issue by mpg-duc-dangminh** [hashicorp/terraform#20526]
### Terraform Version
```
terraform v0.11.10
provider.aws: version = "1.59.0"
provider.random: version = "2.0"
provider.template: version = "2.0"
```

### Terraform Configuration Files
This is our firm's private repository

### Debug Output
https://gist.github.com/mpg-duc-dangminh/f2d724cbfdb88c49f272d3c449499db7

### Crash Output

https://gist.github.com/mpg-duc-dangminh/c09eada0dc1b59b260b628c7c7ad7287

### Expected Behavior
Successful `terraform plan`

### Actual Behavior
Terraform crash after `terraform plan`

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### References
This worked fine previously, my suspicion is one of the providers or external module I'm using (aws, terraform-aws-modules) is failing. I did try newest  versions of both `aws` provider and `terraform-aws-modules` but couldn't get it to work.

**Comment by mildwonkey** [comment]
Hi @mpg-duc-dangminh !
I'm sorry you're experience this issue. It's hard to tell what's going on without seeing your terraform configuration files. I completely understand that your configuration is private, but can you provide us a simplified example so we can reproduce your issue?

**Comment by mpg-duc-dangminh** [comment]
Hi!
The configuration is pretty complicated and the debug log seem to be changed every time I try to rerun ```terraform plan```. I did try to simplify to a smaller environment and smaller configuration but unable to reproduce the problem like the original one.

For the big picture, I'm using terraform external modules like ```terraform-aws-modules/vpc/aws``` mixing with common ```resource``` to define my infrastructure.
Ex:
```
module "main_vpc" {
  source = "terraform-aws-modules/vpc/aws"
  # source  = "git@github.com:terraform-aws-modules/terraform-aws-vpc.git"
  version = "v1.57.0"

  name = "${var.name}"
  azs  = "${var.azs}"
  cidr = "${var.cidr}"

  public_subnets  = "${var.public_subnets}"
  private_subnets = "${var.private_subnets}"

  enable_nat_gateway = "true"
  single_nat_gateway = "true"

  enable_dhcp_options      = "true"
  enable_dns_hostnames     = "true"
  dhcp_options_domain_name = "${var.local_domain}"

  tags = {
    Environment = "${terraform.workspace}"
  }
}
```
```
module "sg_ec2" {
  source  = "terraform-aws-modules/security-group/aws"
  version = "2.14.0"

  name        = "${var.name}-sg"
  description = "${var.name}-sg"
  vpc_id      = "${var.vpc_id}"

  ingress_cidr_blocks = "${var.ingress_cidr_blocks}"
  ingress_rules       = ["ssh-tcp"]

  egress_with_cidr_blocks = [
    {
      from_port   = 0
      to_port     = 0
      protocol    = "-1"
      description = "Egress"
      cidr_blocks = "0.0.0.0/0"
    },
  ]

  tags = {
    Name        = "${terraform.workspace}-ec2-sg"
    Environment = "${terraform.workspace}"
  }
}

resource "aws_eip" "ec2_bastion" {
  vpc = true

  lifecycle {
    create_before_destroy = true
  }
}

data "template_file" "user_data_bastion" {
  template = "${file("${path.module}/user_data_bastion.tpl")}"

  vars {
    eip_allocation_id = "${aws_eip.ec2_bastion.id}"

    region       = "${var.region}"
    env          = "${terraform.workspace}"
    name         = "${var.name}"
    local_domain = "${var.local_domain}"
  }
}

# ec2 configuration
resource "aws_launch_configuration" "ec2" {
  name_prefix                 = "test-ec2-launch-configuration"
  image_id                    = "${var.ami_id}"
  instance_type               = "${var.instance_type}"
  key_name                    = "${var.key_name}"
  user_data                   = "${data.template_file.user_data_bastion.rendered}"
  associate_public_ip_address = true
  spot_price                  = "${var.spot_price}"

  security_groups = [
    "${module.sg_ec2.this_security_group_id}",
  ]

  root_block_device {
    volume_size = "8"
    volume_type = "gp2"
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_autoscaling_group" "ec2" {
  name                      = "${var.name}-asg"
  max_size                  = "${var.max_size}"
  min_size                  = "${var.min_size}"
  desired_capacity          = "${var.desired_count}"
  launch_configuration      = "${aws_launch_configuration.ec2.name}"
  health_check_grace_period = 300
  wait_for_capacity_timeout = "5m"
  health_check_type         = "EC2"
  force_delete              = true
  vpc_zone_identifier       = ["${var.public_subnets_ids}"]

  enabled_metrics = [
    "GroupMinSize",
    "GroupMaxSize",
    "GroupDesiredCapacity",
    "GroupInServiceInstances",
    "GroupPendingInstances",
    "GroupStandbyInstances",
    "GroupTerminatingInstances",
    "GroupTotalInstances",
  ]

  tag {
    key                 = "Name"
    value               = "${var.name}"
    propagate_at_launch = true
  }

  tag {
    key                 = "Env"
    value               = "${terraform.workspace}"
    propagate_at_launch = true
  }

  tag {
    key                 = "ManagedBy"
    value               = "terraform"
    propagate_at_launch = true
  }

  lifecycle {
    create_before_destroy = true
  }
}
```
Based on the debug log, mostly the errors are ```unexpected EOF``` or ```connection shutdown```
```
Error: Error refreshing state: 21 error(s) occurred:

* module.ec2.aws_launch_configuration.ec2_bastion: 1 error(s) occurred:

* module.ec2.aws_launch_configuration.ec2_bastion: aws_launch_configuration.ec2_bastion: connection is shut down
* module.codepipeline.aws_codepipeline.deploy: aws_codepipeline.deploy: unexpected EOF
* module.ses.aws_route53_record.dkim_record: 3 error(s) occurred:

* module.ses.aws_route53_record.dkim_record[0]: aws_route53_record.dkim_record.0: connection is shut down
* module.ses.aws_route53_record.dkim_record[1]: aws_route53_record.dkim_record.1: connection is shut down
* module.ses.aws_route53_record.dkim_record[2]: aws_route53_record.dkim_record.2: connection is shut down
* module.elasticsearch.aws_security_group_rule.es_kibana: 1 error(s) occurred:

* module.elasticsearch.aws_security_group_rule.es_kibana: aws_security_group_rule.es_kibana: connection is shut down
* module.acm.aws_route53_record.cert_validation: 1 error(s) occurred:

* module.acm.aws_route53_record.cert_validation: aws_route53_record.cert_validation: unexpected EOF
* module.ec2.aws_route53_record.ec2_bastion: 1 error(s) occurred:

* module.ec2.aws_route53_record.ec2_bastion: aws_route53_record.ec2_bastion: unexpected EOF
* module.ec2.aws_iam_role_policy_attachment.ec2-attach_bastion: 1 error(s) occurred:

* module.ec2.aws_iam_role_policy_attachment.ec2-attach_bastion: aws_iam_role_policy_attachment.ec2-attach_bastion: unexpected EOF
* module.ecs.aws_s3_bucket.lb-log: 1 error(s) occurred:

* module.ecs.aws_s3_bucket.lb-log: aws_s3_bucket.lb-log: connection is shut down
* module.acm.aws_route53_record.cert_validation_alt_1: 1 error(s) occurred:

* module.acm.aws_route53_record.cert_validation_alt_1: aws_route53_record.cert_validation_alt_1: unexpected EOF
* module.database.aws_db_subnet_group.rds-subnet: 1 error(s) occurred:

* module.database.aws_db_subnet_group.rds-subnet: aws_db_subnet_group.rds-subnet: connection is shut down
* module.elasticsearch.aws_security_group_rule.elasticsearch_public: 1 error(s) occurred:

* module.elasticsearch.aws_security_group_rule.elasticsearch_public: aws_security_group_rule.elasticsearch_public: connection is shut down
* module.database.aws_elasticache_subnet_group.redis_subnet: 1 error(s) occurred:

* module.database.aws_elasticache_subnet_group.redis_subnet: aws_elasticache_subnet_group.redis_subnet: connection is shut down
* module.elasticsearch.aws_elasticsearch_domain.elasticsearch: 1 error(s) occurred:

* module.elasticsearch.aws_elasticsearch_domain.elasticsearch: aws_elasticsearch_domain.elasticsearch: connection is shut down
* module.ec2.aws_iam_role_policy_attachment.ec2-attach_bastion_ecr_pull: 1 error(s) occurred:

* module.ec2.aws_iam_role_policy_attachment.ec2-attach_bastion_ecr_pull: aws_iam_role_policy_attachment.ec2-attach_bastion_ecr_pull: unexpected EOF
* module.ecs.aws_iam_role_policy_attachment.ecs_role-attach: 1 error(s) occurred:

* module.ecs.aws_iam_role_policy_attachment.ecs_role-attach: aws_iam_role_policy_attachment.ecs_role-attach: unexpected EOF
* module.elasticsearch.aws_cloudwatch_log_resource_policy.es_cloudwatch: 1 error(s) occurred:

* module.elasticsearch.aws_cloudwatch_log_resource_policy.es_cloudwatch: aws_cloudwatch_log_resource_policy.es_cloudwatch: unexpected EOF
* module.network.module.vpc.aws_route.private_nat_gateway: aws_route.private_nat_gateway: connection is shut down
* module.database.aws_security_group_rule.from_bastion: 1 error(s) occurred:

* module.database.aws_security_group_rule.from_bastion: aws_security_group_rule.from_bastion: connection is shut down
* module.elasticsearch.aws_security_group_rule.elasticsearch: 1 error(s) occurred:

* module.elasticsearch.aws_security_group_rule.elasticsearch: aws_security_group_rule.elasticsearch: connection is shut down
* module.route53.aws_route53_zone.private: 1 error(s) occurred:

* module.route53.aws_route53_zone.private: aws_route53_zone.private: unexpected EOF
* module.codepipeline.aws_iam_policy.codepipeline: aws_iam_policy.codepipeline: unexpected EOF
```

**Comment by mpg-duc-dangminh** [comment]
Hi, any update on this issue?

**Comment by apparentlymart** [comment]
I see the following panic trace in the debug log:

```
2019-03-01T12:19:44.920+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: panic: runtime error: invalid memory address or nil pointer dereference
2019-03-01T12:19:44.921+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x31a957b]
2019-03-01T12:19:44.921+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 
2019-03-01T12:19:44.922+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: goroutine 2168 [running]:
2019-03-01T12:19:44.922+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.flattenAwsCodePipelineArtifactStore(...)
2019-03-01T12:19:44.922+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_codepipeline.go:230
2019-03-01T12:19:44.922+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsCodePipelineRead(0xc0006dc000, 0x40679c0, 0xc00027fc00, 0xc0006dc000, 0x0)
2019-03-01T12:19:44.922+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_codepipeline.go:439 +0x35b
2019-03-01T12:19:44.922+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc000c3e1c0, 0xc000549f40, 0x40679c0, 0xc00027fc00, 0xc000016f70, 0x10bdd01, 0x3a05be0)
2019-03-01T12:19:44.923+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:352 +0x160
2019-03-01T12:19:44.923+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc001304a10, 0xc000549ef0, 0xc000549f40, 0xc000056800, 0xc000b3fbf0, 0x9557d80)
2019-03-01T12:19:44.923+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x92
2019-03-01T12:19:44.923+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc00000b1e0, 0xc0008cba90, 0xc0008cbb60, 0x0, 0x0)
2019-03-01T12:19:44.923+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2019-03-01T12:19:44.923+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: reflect.Value.call(0xc0000a53e0, 0xc0012300c8, 0x13, 0x47420ad, 0x4, 0xc000b3ff18, 0x3, 0x3, 0xc000c13740, 0x0, ...)
2019-03-01T12:19:44.923+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/goenv/versions/1.11.5/src/reflect/value.go:447 +0x454
2019-03-01T12:19:44.923+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: reflect.Value.Call(0xc0000a53e0, 0xc0012300c8, 0x13, 0xc000051f18, 0x3, 0x3, 0x0, 0x0, 0x0)
2019-03-01T12:19:44.923+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/goenv/versions/1.11.5/src/reflect/value.go:308 +0xa4
2019-03-01T12:19:44.923+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: net/rpc.(*service).call(0xc000398200, 0xc0000ac820, 0xc000836078, 0xc000836090, 0xc0001d9b00, 0xc0007fba20, 0x3a05ba0, 0xc0008cba90, 0x16, 0x3a05be0, ...)
2019-03-01T12:19:44.923+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/goenv/versions/1.11.5/src/net/rpc/server.go:384 +0x14e
2019-03-01T12:19:44.923+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: created by net/rpc.(*Server).ServeCodec
2019-03-01T12:19:44.923+0900 [DEBUG] plugin.terraform-provider-aws_v1.59.0_x4: 	/opt/goenv/versions/1.11.5/src/net/rpc/server.go:481 +0x47e
```

This seems to indicate a bug in the implementation of the `aws_codepipeline` resource type in the `aws` provider, which is confusing since I don't see a resource of that type in the configuration you shared, but I assume it was elsewhere in a portion you didn't include.

Since the crash is coming from AWS provider code rather than Terraform Core code, I'm going to have our bot move the issue over into the AWS provider repository.
