### ISSUE TITLE
v0.11.13 (Windows) - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lvets** [hashicorp/terraform#20713]
### Terraform Version
```
C:\Develop\vault-infra\vault-config\terraform\phoenix>C:\Develop\terraform -v
2019/03/15 12:16:06 [INFO] Terraform version: 0.11.13
2019/03/15 12:16:06 [INFO] Go runtime version: go1.11.5
2019/03/15 12:16:06 [INFO] CLI args: []string{"C:\\Develop\\terraform.exe", "-v"}
2019/03/15 12:16:06 [DEBUG] Attempting to open CLI config file: C:\Users\I860560\AppData\Roaming\terraform.rc
2019/03/15 12:16:06 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/03/15 12:16:06 [INFO] CLI command args: []string{"version", "-v"}
Ter2019/03/15 12:16:06 [DEBUG] checking for provider in "."
raf2019/03/15 12:16:06 [DEBUG] checking for provider in "C:\\Develop"
orm v0.11.13
2019/03/15 12:16:06 [DEBUG] checking for provider in ".terraform\\plugins\\windows_amd64"
2019/03/15 12:16:06 [DEBUG] found provider "terraform-provider-vault_v1.6.0_x4.exe"
2019/03/15 12:16:06 [DEBUG] found valid plugin: "vault", "1.6.0", "C:\\Develop\\vault-infra\\vault-config\\terraform\\phoenix\\.terraform\\plugins\\windows_amd64\\terraform-provider-vault_v1.6.0_x4.exe"
2019/03/15 12:16:06 [DEBUG] plugin: waiting for all plugin processes to complete...
+ provider.vault v1.6.0

C:\Develop\vault-infra\vault-config\terraform\phoenix>
```

### Terraform Configuration Files
Not sure which parts I should paste. We have a rather large configuration.

### Debug Output
```
...
2019/03/15 12:12:22 [TRACE] vertex 'root.vault_auth_backend.approle': walking
2019/03/15 12:12:22 [TRACE] vertex 'root.vault_auth_backend.approle': evaluating
2019/03/15 12:12:22 [TRACE] dag/walk: walking "module.common-roles.vault_gepanic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0xb79f0f]

goroutine 7914 [running]:
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).evalTreeManagedResourceNoState(0xc0005f6028, 0x60839e0, 0xc0005d3240)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:238 +0x32f
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).EvalTree(0xc0005f6028, 0x2ffdee0, 0xc0005f6028)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:98 +0x75
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2ffdee0, 0xc0005f6028, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:113 +0x9a9
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00029af50, 0x2ffdee0, 0xc0005f6028, 0xc000044080)
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x36e
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:310 +0x98d
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0xb79f0f]

goroutine 7914 [running]:
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).evalTreeManagedResourceNoState(0xc0005f6028, 0x60839e0, 0xc0005d3240)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:238 +0x32f
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).EvalTree(0xc0005f6028, 0x2ffdee0, 0xc0005f6028)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:98 +0x75
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2ffdee0, 0xc0005f6028, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:113 +0x9a9
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00029af50, 0x2ffdee0, 0xc0005f6028, 0xc000044080)
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x36e
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:310 +0x98d



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

C:\Develop\vault-infra\vault-config\terraform\phoenix>
```

### Crash Output
https://gist.github.com/lvets/42fb27e7524a19c260c4ddb92c7e80b4

### Expected Behavior
Not crash?

### Actual Behavior
Terraform crashed.

### Additional Context
Vault version 1.0.3.

**Comment by lvets** [comment]
Crashes were due to generic resource moves to specific resrouces that resulted in a bad state. Removing the generic resources and importing the specific ones makes Terraform happy.
