### ISSUE TITLE
Terraform Crash: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by seppevs** [hashicorp/terraform#20733]
A collegue of me is using Terraform v0.11.13 on Windows, and it crashes with this error:
````
2019/03/18 17:33:01 [INFO] Terraform version: 0.11.13
2019/03/18 17:33:01 [INFO] Go runtime version: go1.11.5
2019/03/18 17:33:01 [INFO] CLI args: []string{"C:\\Install\\terraform\\terraform.exe", "plan"}
2019/03/18 17:33:01 [DEBUG] Attempting to open CLI config file: C:\Users\user\AppData\Roaming\terraform.rc
2019/03/18 17:33:01 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/03/18 17:33:01 [INFO] CLI command args: []string{"plan"}
2019/03/18 17:33:01 [TRACE] module source: "./media-cloud-uploader"
2019/03/18 17:33:01 [DEBUG] plugin: waiting for all plugin processes to complete...
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/hashicorp/terraform/config/module.Storage.loadManifest(0xc0002f2240, 0x12, 0x33c4180, 0xc0003d2040, 0x0, 0xc0002e6e60, 0xc0002e41e0, 0x180000, 0x0, 0x2b, ...)

       /opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:110 +0x487
github.com/hashicorp/terraform/config/module.Storage.moduleDir(0xc0002f2240, 0x12, 0x33c4180, 0xc0003d2040, 0x0, 0xc0002e6e60, 0xc0002e4210, 0x2d, 0x2, 0x2, ...)
       /opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:185 +0x64
github.com/hashicorp/terraform/config/module.Storage.findModule(0xc0002f2240, 0x12, 0x33c4180, 0xc0003d2040, 0x0, 0xc0002e6e60, 0xc0002e4210, 0x2d, 0x0, 0x0, ...)
       /opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:258 +0x91
github.com/hashicorp/terraform/config/module.(*Tree).getChildren(0xc0003c8200, 0xc0002e23f0, 0xc0003c8238, 0xb28719, 0x300d660)
       /opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:234 +0x155e
github.com/hashicorp/terraform/config/module.(*Tree).Load(0xc0003c8200, 0xc0002e23f0, 0x0, 0x0)
       /opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:178 +0xa5
github.com/hashicorp/terraform/command.(*Meta).Module(0xc0003cf1e0, 0xc000039c00, 0x1b, 0x0, 0x0, 0x0, 0x0)
       /opt/gopath/src/github.com/hashicorp/terraform/command/meta_new.go:57 +0xc2
github.com/hashicorp/terraform/command.(*PlanCommand).Run(0xc0003cf1e0, 0xc0003d2080, 0x2, 0x2, 0xc00005b7e0)
       /opt/gopath/src/github.com/hashicorp/terraform/command/plan.go:77 +0xaf1
github.com/mitchellh/cli.(*CLI).Run(0xc0003b2140, 0xc0003b2140, 0xc0001c5d20, 0x1)
       /opt/gopath/pkg/mod/github.com/mitchellh/cli@v0.0.0-20171129193617-33edc47170b5/cli.go:255 +0x20e
main.wrappedMain(0x0)
       /opt/gopath/src/github.com/hashicorp/terraform/main.go:223 +0xb55
main.realMain(0x0)
       /opt/gopath/src/github.com/hashicorp/terraform/main.go:100 +0xbe
main.main()
       /opt/gopath/src/github.com/hashicorp/terraform/main.go:36 +0x35



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.
````

**Comment by apparentlymart** [comment]
Hi @seppevs! Sorry for this crash and thanks for reporting it.

I think this is the same problem as discussed in #20712, so I'm going to close this one just to consolidate the discussion over there. You can see in some comments on the other issue a workaround that has worked for a couple people already.
