### ISSUE TITLE
Azure: Terraform crash on AKS version upgrade - index out of range

### ISSUE THREAD

**Issue by ahmedig** [hashicorp/terraform#20742]
Hi there,

We are using terraform for azure, version 0.11.13.
Tried to upgrade the AKS version through terraform to the latest version, and we got this crash.
Downgraded Terraform to version 0.11.11, and it worked without any problems

This crash is happening on the plan command. Haven't obviously tried the apply command.

> 2019-03-18T23:02:28.1863020Z Terraform version:
2019-03-18T23:02:29.5522021Z Terraform v0.11.13
2019-03-18T23:02:29.8096003Z + provider.azurerm v1.22.1
2019-03-18T23:02:29.8097080Z 
2019-03-18T23:02:30.5704144Z ##[command]"terraform" init -backend-config="arm_subscription_id=XXXXXXXXXX" -backend-config="arm_tenant_id=***" -backend-config="arm_client_id=***" -backend-config="arm_client_secret=***" -backend-config="resource_group_name=XXXXXXXXXX" -backend-config="storage_account_name=XXXXXXXXX" -backend-config="container_name=XXXXXXXXX" -var-file="prod.tfvars" -backend-config="key=terraform.tfstate" -reconfigure -get-plugins=false -input=false -no-color
2019-03-18T23:02:30.6671234Z Initializing modules...
2019-03-18T23:02:30.6705479Z - module.kubernetesCluster
2019-03-18T23:02:30.6827606Z panic: runtime error: index out of range
2019-03-18T23:02:30.6828056Z 
2019-03-18T23:02:30.6828350Z goroutine 1 [running]:
2019-03-18T23:02:30.6828657Z github.com/hashicorp/terraform/config/module.Storage.loadManifest(0xc000036920, 0x12, 0x33c4180, 0xc0002d3740, 0x1, 0xc000239b20, 0xc0000369e0, 0x1506a0, 0x0, 0x1e, ...)
2019-03-18T23:02:30.6828997Z 	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:110 +0x487
2019-03-18T23:02:30.6829456Z github.com/hashicorp/terraform/config/module.Storage.moduleDir(0xc000036920, 0x12, 0x33c4180, 0xc0002d3740, 0x1, 0xc000239b20, 0xc000036a00, 0x20, 0x2, 0x2, ...)
2019-03-18T23:02:30.6830003Z 	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:185 +0x64
2019-03-18T23:02:30.6830308Z github.com/hashicorp/terraform/config/module.Storage.findModule(0xc000036920, 0x12, 0x33c4180, 0xc0002d3740, 0x1, 0xc000239b20, 0xc000036a00, 0x20, 0x0, 0x0, ...)
2019-03-18T23:02:30.6830639Z 	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:258 +0x91
2019-03-18T23:02:30.6830942Z github.com/hashicorp/terraform/config/module.(*Tree).getChildren(0xc0002e6280, 0xc00008d860, 0xc0002e62b8, 0xb28719, 0x300d660)
2019-03-18T23:02:30.6831423Z 	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:234 +0x155e
2019-03-18T23:02:30.6831864Z github.com/hashicorp/terraform/config/module.(*Tree).Load(0xc0002e6280, 0xc00008d860, 0x0, 0x0)
2019-03-18T23:02:30.6832356Z 	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:178 +0xa5
2019-03-18T23:02:30.6832896Z github.com/hashicorp/terraform/command.getModules(0xc0003cb040, 0xc0000ac230, 0x47, 0xc0003a2b01, 0x17, 0xc0003a4c30)
2019-03-18T23:02:30.6833720Z 	/opt/gopath/src/github.com/hashicorp/terraform/command/get.go:84 +0x127
2019-03-18T23:02:30.6834039Z github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc0003cb040, 0xc0000b0020, 0xc, 0xe, 0xc000049890)
2019-03-18T23:02:30.6834354Z 	/opt/gopath/src/github.com/hashicorp/terraform/command/init.go:179 +0xac7
2019-03-18T23:02:30.6834655Z github.com/mitchellh/cli.(*CLI).Run(0xc00029a500, 0xc00029a500, 0xc0001cfd20, 0x1)
2019-03-18T23:02:30.6834938Z 	/opt/gopath/pkg/mod/github.com/mitchellh/cli@v0.0.0-20171129193617-33edc47170b5/cli.go:255 +0x20e
2019-03-18T23:02:30.6835219Z main.wrappedMain(0x0)
2019-03-18T23:02:30.6835495Z 	/opt/gopath/src/github.com/hashicorp/terraform/main.go:223 +0xb55
2019-03-18T23:02:30.6835738Z main.realMain(0x0)
2019-03-18T23:02:30.6836306Z 	/opt/gopath/src/github.com/hashicorp/terraform/main.go:100 +0xbe
2019-03-18T23:02:30.6836675Z main.main()
2019-03-18T23:02:30.6836933Z 	/opt/gopath/src/github.com/hashicorp/terraform/main.go:36 +0x35
2019-03-18T23:02:30.6837171Z 
2019-03-18T23:02:30.6837502Z 
2019-03-18T23:02:30.6838764Z 
2019-03-18T23:02:30.6839296Z !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
2019-03-18T23:02:30.6839951Z 
2019-03-18T23:02:30.6841027Z Terraform crashed! This is always indicative of a bug within Terraform.
2019-03-18T23:02:30.6841476Z A crash log has been placed at "crash.log" relative to your current
2019-03-18T23:02:30.6841897Z working directory. It would be immensely helpful if you could please
2019-03-18T23:02:30.6842309Z report the crash with Terraform[1] so that we can fix this.
2019-03-18T23:02:30.6842710Z 
2019-03-18T23:02:30.6843221Z When reporting bugs, please include your terraform version. That
2019-03-18T23:02:30.6844269Z information is available on the first line of crash.log. You can also
2019-03-18T23:02:30.6845115Z get it by running 'terraform --version' on the command line.
2019-03-18T23:02:30.6845687Z 
2019-03-18T23:02:30.6846482Z [1]: https://github.com/hashicorp/terraform/issues
2019-03-18T23:02:30.6846954Z 
2019-03-18T23:02:30.6847334Z !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
2019-03-18T23:02:30.6956537Z ##[error] Terraform init failed to execute. Error: 
2019-03-18T23:02:31.1121254Z ##[command]"terraform" plan -var-file="prod.tfvars" -var "agent_pool_profile={pool_count=3}" -target="module.kubernetesCluster" -input=false -no-color
2019-03-18T23:02:31.2176566Z panic: runtime error: index out of range
2019-03-18T23:02:31.2177588Z 
2019-03-18T23:02:31.2177892Z goroutine 1 [running]:
2019-03-18T23:02:31.2178231Z github.com/hashicorp/terraform/config/module.Storage.loadManifest(0xc0003d4a80, 0x12, 0x33c4180, 0xc000396460, 0x0, 0xc0003f49b0, 0xc0003d4ae0, 0x1c06a0, 0x0, 0x1e, ...)
2019-03-18T23:02:31.2178575Z 	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:110 +0x487
2019-03-18T23:02:31.2179748Z github.com/hashicorp/terraform/config/module.Storage.moduleDir(0xc0003d4a80, 0x12, 0x33c4180, 0xc000396460, 0x0, 0xc0003f49b0, 0xc0003d4b00, 0x20, 0x2, 0x2, ...)
2019-03-18T23:02:31.2180097Z 	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:185 +0x64
2019-03-18T23:02:31.2180318Z github.com/hashicorp/terraform/config/module.Storage.findModule(0xc0003d4a80, 0x12, 0x33c4180, 0xc000396460, 0x0, 0xc0003f49b0, 0xc0003d4b00, 0x20, 0x0, 0x0, ...)
2019-03-18T23:02:31.2180530Z 	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:258 +0x91
2019-03-18T23:02:31.2180705Z github.com/hashicorp/terraform/config/module.(*Tree).getChildren(0xc0000ab180, 0xc000393230, 0xc0000ab1b8, 0xb28719, 0x300d660)
2019-03-18T23:02:31.2180898Z 	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:234 +0x155e
2019-03-18T23:02:31.2181081Z github.com/hashicorp/terraform/config/module.(*Tree).Load(0xc0000ab180, 0xc000393230, 0x0, 0x0)
2019-03-18T23:02:31.2181508Z 	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:178 +0xa5
2019-03-18T23:02:31.2181846Z github.com/hashicorp/terraform/command.(*Meta).Module(0xc0003a0820, 0xc0003734a0, 0x47, 0x0, 0x0, 0x0, 0x0)
2019-03-18T23:02:31.2182027Z 	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_new.go:57 +0xc2
2019-03-18T23:02:31.2182248Z github.com/hashicorp/terraform/command.(*PlanCommand).Run(0xc0003a0820, 0xc0000b3e50, 0x5, 0x5, 0xc00030f150)
2019-03-18T23:02:31.2182430Z 	/opt/gopath/src/github.com/hashicorp/terraform/command/plan.go:77 +0xaf1
2019-03-18T23:02:31.2182615Z github.com/mitchellh/cli.(*CLI).Run(0xc000344500, 0xc000344500, 0xc0001cdd20, 0x1)
2019-03-18T23:02:31.2182804Z 	/opt/gopath/pkg/mod/github.com/mitchellh/cli@v0.0.0-20171129193617-33edc47170b5/cli.go:255 +0x20e
2019-03-18T23:02:31.2183176Z main.wrappedMain(0x0)
2019-03-18T23:02:31.2183465Z 	/opt/gopath/src/github.com/hashicorp/terraform/main.go:223 +0xb55
2019-03-18T23:02:31.2183634Z main.realMain(0x0)
2019-03-18T23:02:31.2183780Z 	/opt/gopath/src/github.com/hashicorp/terraform/main.go:100 +0xbe
2019-03-18T23:02:31.2183949Z main.main()
2019-03-18T23:02:31.2184271Z 	/opt/gopath/src/github.com/hashicorp/terraform/main.go:36 +0x35
2019-03-18T23:02:31.2184390Z 
2019-03-18T23:02:31.2184529Z 
2019-03-18T23:02:31.2186441Z 
2019-03-18T23:02:31.2186771Z !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
2019-03-18T23:02:31.2187113Z 
2019-03-18T23:02:31.2188175Z Terraform crashed! This is always indicative of a bug within Terraform.
2019-03-18T23:02:31.2188470Z A crash log has been placed at "crash.log" relative to your current
2019-03-18T23:02:31.2189035Z working directory. It would be immensely helpful if you could please
2019-03-18T23:02:31.2189267Z report the crash with Terraform[1] so that we can fix this.
2019-03-18T23:02:31.2189903Z 
2019-03-18T23:02:31.2190435Z When reporting bugs, please include your terraform version. That
2019-03-18T23:02:31.2190639Z information is available on the first line of crash.log. You can also
2019-03-18T23:02:31.2191308Z get it by running 'terraform --version' on the command line.
2019-03-18T23:02:31.2191459Z 
2019-03-18T23:02:31.2192411Z [1]: https://github.com/hashicorp/terraform/issues
2019-03-18T23:02:31.2192558Z 
2019-03-18T23:02:31.2193025Z !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
2019-03-18T23:02:31.2250945Z ##[error] Terraform failed to execute. Error: 
2019-03-18T23:02:31.2265856Z End of Task Terraform
2019-03-18T23:02:31.2267077Z 
2019-03-18T23:02:31.2267717Z 
2019-03-18T23:02:31.2672440Z ##[section]Finishing: Terraform  Plan

**Comment by bflad** [comment]
Hi @ahmedig! 👋  Sorry for this unexpected behavior and thank you for reporting it.

This appears to be very similar to the report in #20712 from the stacktrace, so I'm going to close issue to consolidate the discussion over there. That issue does have a workaround that has worked for a couple people already if interested.
