### ISSUE TITLE
Local file created from template with undefined variable results in TERRAFORM CRASH

### ISSUE THREAD

**Issue by wesmartin17** [hashicorp/terraform#20832]
This is a minor issue since I found the cause rather quickly but I thought you still might want to be made aware of this.  When creating a .tmpl file and then turning it into a text file with the local_file resource, if one of the template's variable's are not given a value terraform will crash when running plan or apply.
### Terraform Version
```
Terraform v0.12.0-beta1
```

### Terraform Configuration Files
test.tmpl
```hcl
foo=${defined_templ_val}
bar=${not_defined_templ_val}
```
main.tf
```
resource "local_file" "foo" { 
  filename = "test-templ.txt"
  content = templatefile("test.tmpl", { 
    defined_templ_val = "foo_val"
    }
  )
}
```
### Crash Output
```
panic: runtime error: index out of range

goroutine 132 [running]:
github.com/hashicorp/hcl2/hcl/hclsyntax.(*FunctionCallExpr).Value(0xc0001c7e00, 0xc00057b740, 0xc00039e0f8, 0x7, 0xc0007475a8, 0x1, 0x0, 0x0, 0x0)
        /opt/gopath/pkg/mod/github.com/hashicorp/hcl2@v0.0.0-20190226234159-7e26f2f34612/hcl/hclsyntax/expression.go:396 +0x4b98
github.com/hashicorp/hcl2/hcldec.(*AttrSpec).decode(0xc0006f6cc0, 0xc00025ef60, 0x0, 0x0, 0x0, 0xc00057b740, 0xbba1d3, 0x182c2e0, 0x0, 0xc000a24c20, ...)
        /opt/gopath/pkg/mod/github.com/hashicorp/hcl2@v0.0.0-20190226234159-7e26f2f34612/hcldec/spec.go:196 +0xaf
github.com/hashicorp/hcl2/hcldec.ObjectSpec.decode(0xc0006f6420, 0xc00025ef60, 0x0, 0x0, 0x0, 0xc00057b740, 0x0, 0xc0006f6420, 0x17762fa702c6d710, 0x19ac120, ...)
        /opt/gopath/pkg/mod/github.com/hashicorp/hcl2@v0.0.0-20190226234159-7e26f2f34612/hcldec/spec.go:78 +0x240
github.com/hashicorp/hcl2/hcldec.decode(0x1e348a0, 0xc00072ab70, 0x0, 0x0, 0x0, 0xc00057b740, 0x1e358a0, 0xc0006f6420, 0xc0009a2400, 0x0, ...)
        /opt/gopath/pkg/mod/github.com/hashicorp/hcl2@v0.0.0-20190226234159-7e26f2f34612/hcldec/decode.go:21 +0x11f
github.com/hashicorp/hcl2/hcldec.Decode(0x1e348a0, 0xc00072ab70, 0x1e358a0, 0xc0006f6420, 0xc00057b740, 0x1, 0x0, 0x0, 0x0, 0x2cb3de0, ...)
        /opt/gopath/pkg/mod/github.com/hashicorp/hcl2@v0.0.0-20190226234159-7e26f2f34612/hcldec/public.go:15 +0x91
github.com/hashicorp/terraform/lang.(*Scope).EvalBlock(0xc0009a2410, 0x1e348a0, 0xc00072ab70, 0xc000baa040, 0x1, 0x1, 0x0, 0x0, 0x0, 0x30002, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/lang/eval.go:61 +0x2bc
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc00038d450, 0x1e348a0, 0xc00072ab70, 0xc000baa040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:277 +0x2e1
github.com/hashicorp/terraform/terraform.(*EvalValidateResource).Eval(0xc000519f90, 0x1e443e0, 0xc00038d450, 0x2, 0x2, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_validate.go:414 +0x5d4
github.com/hashicorp/terraform/terraform.EvalRaw(0x1e1e700, 0xc000519f90, 0x1e443e0, 0xc00038d450, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x16e
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc00057a380, 0x1e443e0, 0xc00038d450, 0x2, 0x2, 0x2ee9de8, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0x104
github.com/hashicorp/terraform/terraform.EvalRaw(0x1e1e660, 0xc00057a380, 0x1e443e0, 0xc00038d450, 0x181f2c0, 0x2b6b0e5, 0x1794e20, 0xc00037c1c0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x16e
github.com/hashicorp/terraform/terraform.Eval(0x1e1e660, 0xc00057a380, 0x1e443e0, 0xc00038d450, 0xc00057a380, 0x1e1e660, 0xc00057a380, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:35 +0x54
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x1a47be0, 0xc0005f20d0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:90 +0x10d8
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00083fb80, 0x1a47be0, 0xc0005f20d0, 0xc0005a1380)
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x37a
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:314 +0x9d9



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
### Expected Behavior
Probably a way to validate this before attempting to construct the file

### Steps to Reproduce
1. `terraform init`
2. `terraform plan` or `terraform apply`

**Comment by apparentlymart** [comment]
Thanks for reporting this, @wesmartin17!

It looks like you've hit the bug I fixed in #20766. That went in after we cut beta1, so the fix will be included in the forthcoming beta2. We're planning to release beta2 once we have a representative set of providers available for installation via `terraform init` so that the second beta can be used to test the provider auto-installation mechanism along with all of the other configuration language functionality.

Because there's already a fix for this in master I'm going to close this out, but thanks again for reporting it!
