### ISSUE TITLE
Crash when a list is provided

### ISSUE THREAD

**Issue by jglapa** [hashicorp/terraform#20897]
### Terraform Version

```
Terraform v0.11.13
+ provider.aws v2.1.0

```

### Terraform Configuration Files

```hcl
data "aws_lb" "my-lb" {
  name = "${aws_elastic_beanstalk_environment.my-env.load_balancers}"
}

resource "aws_route53_record" "dns-record" {
  zone_id = "${data.aws_route53_zone.my-zone.id}"
  name = "some name"
  type = "A"
  alias {
    evaluate_target_health = false
    name = "${data.aws_lb.my-lb.name}"
    zone_id = "${data.aws_lb.my-lb.zone_id}"
  }
}

```

### Crash Output
```
panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: 
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: goroutine 360 [running]:
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc0002a5730, 0xc000646b10, 0x1, 0x1, 0xc000646b12, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:509 +0x449
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc0002a5730, 0x3b9c8d7, 0x4, 0xc000351201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:480 +0x122
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc0002a5730, 0x3b9c8d7, 0x4, 0xd0, 0x37c3660, 0x1, 0x1000000000000, 0xd0)
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:457 +0x97
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diffString(0xc000085ce0, 0x3b9c8d7, 0x4, 0xc0001c6ff0, 0xc000a37640, 0x3f323e0, 0xc0002a5730, 0xc0000be600, 0x0, 0x0)
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1158 +0xa0
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc000085ce0, 0x3b9c8d7, 0x4, 0xc0001c6ff0, 0xc0004bcfa0, 0x3f323e0, 0xc0002a5730, 0x3fda59888d6f1b00, 0x0, 0x0)
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:774 +0x436
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc000085ce0, 0x0, 0xc000a17920, 0x0, 0x2e3bd20, 0xc00025ec00, 0x71374491428a2f98, 0xe9b5dba5b5c0fbcf, 0x411dd1)
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:424 +0x206
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc0003798f0, 0x0, 0xc000a17920, 0x2e3bd20, 0xc00025ec00, 0xc0000beb01, 0x4c1a0c, 0x2e413e0)
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:250 +0x17c
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataDiff(0xc0005629a0, 0xc00068e0a0, 0xc000a17920, 0xc000396380, 0x53380d134d2c6dfc, 0x7faaf02d5000)
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:413 +0x9b
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ReadDataDiff(0xc00000b8c0, 0xc000646950, 0xc000646a50, 0x0, 0x0)
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:593 +0x4e
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: reflect.Value.call(0xc00046aa20, 0xc00008d368, 0x13, 0x3b9c1f7, 0x4, 0xc0000bef18, 0x3, 0x3, 0xc000790900, 0x0, ...)
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: 	/opt/goenv/versions/1.11.5/src/reflect/value.go:447 +0x454
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: reflect.Value.Call(0xc00046aa20, 0xc00008d368, 0x13, 0xc000363f18, 0x3, 0x3, 0x5d798b, 0xc000363f28, 0x429852)
2019-04-02T15:47:37.951+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: 	/opt/goenv/versions/1.11.5/src/reflect/value.go:308 +0xa4
2019-04-02T15:47:37.952+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: net/rpc.(*service).call(0xc000089e00, 0xc0004beb40, 0xc0000359f8, 0xc000035a10, 0xc000131080, 0xc0006bf5c0, 0x2e413a0, 0xc000646950, 0x16, 0x2e413e0, ...)
2019-04-02T15:47:37.952+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: 	/opt/goenv/versions/1.11.5/src/net/rpc/server.go:384 +0x14e
2019-04-02T15:47:37.952+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: created by net/rpc.(*Server).ServeCodec
2019-04-02T15:47:37.952+0200 [DEBUG] plugin.terraform-provider-aws_v2.1.0_x4: 	/opt/goenv/versions/1.11.5/src/net/rpc/server.go:481 +0x47e
2019/04/02 15:47:37 [ERROR] root: eval: *terraform.EvalReadDataDiff, err: unexpected EOF
2019/04/02 15:47:37 [TRACE] [walkRefresh] Exiting eval tree: data.aws_lb.my-lb
2019/04/02 15:47:37 [TRACE] dag/walk: upstream errored, not walking "aws_route53_record.dns-record"
2019/04/02 15:47:37 [TRACE] dag/walk: upstream errored, not walking "provider.aws (close)"
2019/04/02 15:47:37 [TRACE] dag/walk: upstream errored, not walking "root"
2019/04/02 15:47:37 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-04-02T15:47:37.958+0200 [WARN ] plugin: error closing client during Kill: err="connection is shut down"



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

### Expected Behavior

This should not crash. 
More likely give a warning or simply fail with descriptive message.

`aws_elastic_beanstalk_environment.my-env.load_balancers` returns a list of names which `aws_route53_record` does not deal well

**Comment by jbardin** [comment]
Hi @jglapa,

Thanks for filing the issue. This is particular situation is no longer a concern in the master branch. The new type system in 0.12 validates the configuration types statically, which would catch this early on before making any requests.
