### ISSUE TITLE
Terraform Crash - Resource vault_pki_secret_backend_role

### ISSUE THREAD

**Issue by jahantech** [hashicorp/terraform#20903]
### Terraform Version
```
terraform -v
Terraform v0.11.13
+ provider.aws v2.4.0
+ provider.vault v1.6.0
```

### Terraform Configuration Files

```
resource "vault_pki_secret_backend" "pki" {
  path = "pki"
  default_lease_ttl_seconds = 3600
  max_lease_ttl_seconds = 86400
}

resource "vault_pki_secret_backend_role" "role" {
  backend = "${vault_pki_secret_backend.pki.path}"
  name    = "my_role"
}
```

### Crash Output
```
* vault_pki_secret_backend_role.role: unexpected EOF
2019/04/02 18:10:44 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* vault_pki_secret_backend_role.role: unexpected EOF
2019/04/02 18:10:44 [TRACE] [walkApply] Exiting eval tree: vault_pki_secret_backend_role.role
2019/04/02 18:10:44 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2019/04/02 18:10:44 [TRACE] dag/walk: upstream errored, not walking "provider.vault (close)"
2019/04/02 18:10:44 [TRACE] dag/walk: upstream errored, not walking "root"
2019-04-02T18:10:44.710+0100 [DEBUG] plugin: plugin process exited: path=/Project-Name/terraform/.terraform/plugins/darwin_amd64/terraform-provider-vault_v1.6.0_x4
2019/04/02 18:10:44 [TRACE] Preserving existing state lineage "XXXXXXXX"
2019/04/02 18:10:44 [TRACE] Preserving existing state lineage "XXXXXXXX"
2019/04/02 18:10:44 [TRACE] Preserving existing state lineage "XXXXXXXX"
2019/04/02 18:10:44 [DEBUG] Uploading remote state to S3: {
  Body: buffer(0xc00084cf90),
  Bucket: "xxxxxx",
  ContentLength: 40538,
  ContentType: "application/json",
  Key: "xxxxx/terraform.tfstate"
}
2019/04/02 18:10:44 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-04-02T18:10:44.908+0100 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2019-04-02T18:10:44.909+0100 [DEBUG] plugin.terraform-provider-aws_v2.4.0_x4: 2019/04/02 18:10:44 [ERR] plugin: plugin server: accept unix /var/folders/jv/5jp5y6yj6rv1ydxqx8dc_xf47cp6rq/T/plugin245429485: use of closed network connection
2019-04-02T18:10:44.913+0100 [DEBUG] plugin: plugin process exited: path=/ProjectName/terraform/.terraform/plugins/darwin_amd64/terraform-provider-aws_v2.4.0_x4

```

### Expected Behavior
It should have created a role.

### Actual Behavior
It didn't create the role and crashed.

### Steps to Reproduce
```
terraform init
terraform apply
```

### References
https://www.terraform.io/docs/providers/vault/r/pki_secret_backend_role.html

**Comment by gopisaba** [comment]
I am having similar issue. Did you manage to fix it? @jahantech 

##### Debug message
```
2019-05-16T23:54:56.613+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: 2019/05/16 23:54:56 [DEBUG] Read role from "external/roles/management_external"
2019-05-16T23:54:56.614+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: panic: interface conversion: interface {} is nil, not []interface {}
2019-05-16T23:54:56.614+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4:
2019-05-16T23:54:56.614+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: goroutine 52 [running]:
2019-05-16T23:54:56.614+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: github.com/terraform-providers/terraform-provider-vault/vault.pkiSecretBackendRoleRead(0xc0002da3f0, 0x1d42e60, 0xc0002148c0, 0x2, 0x2)
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vault/resource_pki_secret_backend_role.go:433 +0x216c
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: github.com/terraform-providers/terraform-provider-vault/vault.pkiSecretBackendRoleCreate(0xc0002da3f0, 0x1d42e60, 0xc0002148c0, 0xc0002da3f0, 0x0)
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vault/resource_pki_secret_backend_role.go:383 +0x2254
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc00059cd90, 0xc000438140, 0xc0003f88c0, 0x1d42e60, 0xc0002148c0, 0x100b601, 0xc000411b80, 0x10be02c)
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:225 +0x351
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0004b8150, 0xc0004380f0, 0xc000438140, 0xc0003f88c0, 0xc000078800, 0x18, 0x2ca5440)
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0x9c
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc0004940c0, 0xc0003f84a0, 0xc0003fd710, 0x0, 0x0)
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: reflect.Value.call(0xc0000b4e40, 0xc0000b2038, 0x13, 0x1d5f59e, 0x4, 0xc000411f18, 0x3, 0x3, 0xc000212000, 0x0, ...)
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: 	/opt/goenv/versions/1.11.0/src/reflect/value.go:447 +0x449
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: reflect.Value.Call(0xc0000b4e40, 0xc0000b2038, 0x13, 0xc000520f18, 0x3, 0x3, 0x0, 0x0, 0x0)
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: 	/opt/goenv/versions/1.11.0/src/reflect/value.go:308 +0xa4
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: net/rpc.(*service).call(0xc000154100, 0xc0004e40f0, 0xc00015e188, 0xc00015e1b0, 0xc0001ae000, 0xc0000b1360, 0x1b31f60, 0xc0003f84a0, 0x16, 0x1b31fa0, ...)
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: 	/opt/goenv/versions/1.11.0/src/net/rpc/server.go:384 +0x14e
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: created by net/rpc.(*Server).ServeCodec
2019-05-16T23:54:56.615+0100 [DEBUG] plugin.terraform-provider-vault_v1.8.0_x4: 	/opt/goenv/versions/1.11.0/src/net/rpc/server.go:481 +0x47e
2019/05/16 23:54:56 [TRACE] root: eval: *terraform.EvalWriteState
2019/05/16 23:54:56 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2019/05/16 23:54:56 [TRACE] root: eval: *terraform.EvalIf
2019/05/16 23:54:56 [TRACE] root: eval: *terraform.EvalWriteState
2019/05/16 23:54:56 [TRACE] root: eval: *terraform.EvalWriteDiff
2019/05/16 23:54:56 [TRACE] root: eval: *terraform.EvalApplyPost
2019/05/16 23:54:56 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* vault_pki_secret_backend_role.external: unexpected EOF
2019/05/16 23:54:56 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* vault_pki_secret_backend_role.external: unexpected EOF
2019/05/16 23:54:56 [TRACE] [walkApply] Exiting eval tree: vault_pki_secret_backend_role.external
```

**Comment by apparentlymart** [comment]
Hi @jahantech, @gopisaba! Sorry we didn't spot this the first time around.

Based on the stack trace in that log output, this bug seems to be in the Vault provider rather than in Terraform Core, so it will require a fix in [the Vault provider repository](https://github.com/terraform-providers/terraform-provider-vault). If you open an issue over there then the team that maintains that provider should be able to take a look at it.

**Comment by gopisaba** [comment]
Thanks @apparentlymart 
Opened an issue in Vault provider repository https://github.com/terraform-providers/terraform-provider-vault/issues/419

**Comment by apparentlymart** [comment]
Thanks! In that case, I'm going to close this one out to consolidate the discussion over there for now.
