### ISSUE TITLE
AWS Bucket policy JSON causes terraform crash

### ISSUE THREAD

**Issue by mutt13y** [hashicorp/terraform#21073]
### Terraform Version

```
Terraform v0.12.0-beta2
+ provider.aws v2.7.0

```

### Terraform Configuration Files

```hcl
data "aws_s3_bucket" "logs" {
  bucket = "redacted-logs"
}

resource "aws_s3_bucket_policy" "logs" {
  #count = (local.env == "live" ? 1 : 0)
  bucket = "${data.aws_s3_bucket.logs.id}"

  policy = <<POLICY
{
  "Id": "Policy1429136655941",
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Cloudflare_1",
      "Effect": "Allow",
      "Principal": {
          "AWS": "arn:aws:iam::0000000000:user/cloudflare-logpush"
      },
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::redacted-logs/cloudflare/*"
    }
  ]
}
POLICY
}
```

### Crash Output

 
"https://gist.github.com/mutt13y/635e77d69558e3242ffb6773b08f04c7.js"

### Expected Behavior

Either the JSON should be ignored and sent verbatim or an error stating that Principal should be a list

### Steps to Reproduce

terraform apply
before confirmation prompt
### Additional Context

```
 policy = <<POLICY
{
  "Id": "Policy1429136655941",
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Cloudflare_1",
      "Effect": "Allow",
      "Principal": {
          "AWS": [
                "arn:aws:iam::0000000000:user/cloudflare-logpush"
            ]
      },
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::redacted-logs/cloudflare/*"
    }
  ]
}
POLICY
}
```
works as expected

**Comment by mildwonkey** [comment]
Hi @mutt13y , thank you for reporting this issue to us and I'm sorry you've experienced this.

It looks like the problem lies with terraform's diff printer - here is the relevant log and output: 
https://gist.github.com/mutt13y/635e77d69558e3242ffb6773b08f04c7

```
panic: runtime error: index out of range

goroutine 97 [running]:
github.com/hashicorp/terraform/command/format.ctySequenceDiff(0xc0008cea80, 0x2, 0x2, 0xc0005225e0, 0x1, 0x1, 0x1, 0x1397803, 0xc000f72fc0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format/diff.go:1104 +0xba9
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeValueDiff(0xc00136d718, 0x2a18260, 0xc0009c5e40, 0x234a1c0, 0xc0009c5e60, 0x2a18260, 0xc0005223e0, 0x234a1c0, 0xc000522400, 0x10, ...)
```

**Comment by mildwonkey** [comment]
Hi again @mutt13y !
I am not able to reproduce the crash you experienced with your supplied configuration; can you help me out? 

I am using the configuration you supplied (with my own s3 bucket), no backend configuration (just using the local backend) and the following provider block:

```hcl
provider "aws" {
  version = "v2.7.0"
  region = "us-east-1"
}
```

```
$ ./terraform version
Terraform v0.12.0-beta2
+ provider.aws v2.7.0
```

This is the output from `terraform apply`:
```
$ ./terraform apply -auto-approve

Error: Error putting S3 policy: MalformedPolicy: Invalid principal in policy
	status code: 400, request id: 80E2C4EAD17FD1BF, host id: 0xCus1mhjdebf5a8sC/Pl+sU7DHH0eT9hmjXbiW3CzWPK8KRW1DjWjLjUdw1Yj4lOLaZSlU/j00=

  on json.tf line 10, in resource "aws_s3_bucket_policy" "logs":
  10: resource "aws_s3_bucket_policy" "logs" {
```

Can you let me know if you are able to reproduce the crash using just the configuration you supplied? If so, can you let me know a little more about the rest of your configuration and the commands you are running? 
Thanks!

**Comment by mutt13y** [comment]
Hi @mildwonkey ,
no need to apologise, we know the risks and rewards of using beta. Really like the things you are doing with 0.12 !!!

From what you say the issue could be applying this config to the specific  current state.
So first I am using S3 backend with workspaces (if that makes a difference)

The existing policy was created by the following
I was removing the JIRA part and applying that to a different bucket
```
resource "aws_s3_bucket_policy" "logs" {
  bucket = "${data.aws_s3_bucket.logs.id}"
  policy = <<POLICY

{
  "Id": "Policy1429136655940",
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Jira_ALB_1",
      "Action": [
        "s3:PutObject"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::REDACTED-logs/Jira/AWSLogs/${var.aws_account_id}/*",
      "Principal": {
        "AWS": [
          "${var.aws_ELB_account_id[var.aws_region]}"
        ]
      }
    },
    {
      "Sid": "Cloudflare_1",
      "Effect": "Allow",
      "Principal": {
          "AWS": "arn:aws:iam::0000000000:user/cloudflare-logpush"
      },
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::REDACTED-logs/cloudflare/*"
    }

  ]
}
POLICY
}
```
I can't send you the whole manifest for security reasons
If this does not help I will try to recreate the issue using a minimal configuration.

This principal definitely worked as a singleton. With the AWS Policy editor I can enter either a list or a single value for AWS. Also even if I have a single item list in my TF manifest I end up with a single value on the actual bucket. i.e [ ] were required to make the manifest apply but the actual policy is like the one that caused the crash.

I just noticed that the previous working policy had one as a list and one as a value.
This definitely worked with Beta-1 and the old AWS 1.6 dev provider version 

It has been a bit of a day with things not responding expected :-/

Thanks!

**Comment by masterjg** [comment]
Got a very similar crash:
```
panic: runtime error: index out of range

goroutine 70 [running]:
 github.com/hashicorp/terraform/command/format.ctySequenceDiff(0xc0006f39a0, 0x5, 0x5, 0xc0006f3b80, 0x5, 0x5, 0x5, 0x721536, 0x40388e)
        /home/ubuntu/terraform-dev-snapshots/build/terraform/command/format/diff.go:1104 +0xbb0
#github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeValueDiff(0xc0019bb718, 0x1e513a0, 0xc000406380, 0x1786ba0, 0xc0004063a0, 0x1e513a0, 0xc0004074e0, 0x1786ba0, 0xc000407500, 0x14, ...)
        /home/ubuntu/terraform-dev-snapshots/build/terraform/command/format/diff.go:802 +0x2a6
mgithub.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeValueDiff(0xc0019bb718, 0x1e51320, 0xc0002c25c0, 0x183ea40, 0xc0014f5c80, 0x1e51320, 0xc0002c2610, 0x183ea40, 0xc000d9d890, 0x10, ...)
o       /home/ubuntu/terraform-dev-snapshots/build/terraform/command/format/diff.go:965 +0x1323
dgithub.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeValueDiff(0xc0019bb718, 0x1e513a0, 0xc000406c80, 0x1786ba0, 0xc000406ca0, 0x1e513a0, 0xc000407f80, 0x1786ba0, 0xc000407fa0, 0xc, ...)
u       /home/ubuntu/terraform-dev-snapshots/build/terraform/command/format/diff.go:810 +0x543
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeValueDiff(0xc0019bb718, 0x1e51220, 0xc00007c420, 0x17a5800, 0xc0008b9c90, 0x1e51220, 0xc00007c420, 0x17a5800, 0xc000cdc000, 0x8, ...)
l       /home/ubuntu/terraform-dev-snapshots/build/terraform/command/format/diff.go:655 +0x4f1e
egithub.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeAttrDiff(0xc001279718, 0xc000855d00, 0x15, 0xc000814f00, 0x1e51220, 0xc00007c420, 0x17a5800, 0xc0008b9c90, 0x1e51220, 0xc00007c420, ...)
.       /home/ubuntu/terraform-dev-snapshots/build/terraform/command/format/diff.go:263 +0x4ce
cgithub.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeBlockBodyDiff(0xc0019bb718, 0xc000856d50, 0x1e51320, 0xc0002c2488, 0x183ea40, 0xc0010d0fc0, 0x1e51320, 0xc0002c24e0, 0x183ea40, 0xc001cd2630, ...)
y       /home/ubuntu/terraform-dev-snapshots/build/terraform/command/format/diff.go:196 +0x5de
cgithub.com/hashicorp/terraform/command/format.ResourceChange(0xc0012a7400, 0xc001e5a000, 0xc000856d50, 0xc00033ddc0, 0x4d, 0xc000340680)
l       /home/ubuntu/terraform-dev-snapshots/build/terraform/command/format/diff.go:140 +0x630
ogithub.com/hashicorp/terraform/backend/local.(*Local).renderPlan(0xc0005225b0, 0xc0017aad90, 0xc00052fa30, 0xc0002c08e0)
s       /home/ubuntu/terraform-dev-snapshots/build/terraform/backend/local/backend_plan.go:269 +0x6e3
.github.com/hashicorp/terraform/backend/local.(*Local).opApply(0xc0005225b0, 0x1e4f820, 0xc0002b98c0, 0x1e4f820, 0xc0002b9980, 0xc0003de000, 0xc0002b9800)
a       /home/ubuntu/terraform-dev-snapshots/build/terraform/backend/local/backend_apply.go:111 +0x12b4
wgithub.com/hashicorp/terraform/backend/local.(*Local).opApply-fm(0x1e4f820, 0xc0002b98c0, 0x1e4f820, 0xc0002b9980, 0xc0003de000, 0xc0002b9800)
        /home/ubuntu/terraform-dev-snapshots/build/terraform/backend/local/backend.go:305 +0x6d
sgithub.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc0002c1100, 0xc0002c1110, 0xc0002c1120, 0xc0003de000, 0xc0005225b0, 0xc0002b9800, 0xc0002c10f0, 0x1e4f820, 0xc0002b98c0, 0x1e4f820, ...)
_       /home/ubuntu/terraform-dev-snapshots/build/terraform/backend/local/backend.go:356 +0x13c
ecreated by github.com/hashicorp/terraform/backend/local.(*Local).Operation
c       /home/ubuntu/terraform-dev-snapshots/build/terraform/backend/local/backend.go:340 +0x369
s
_service.service will be updated in-place
```

```
λ terraform -v
Terraform v0.12.0-dev20190415H16
+ provider.aws v1.60.0-dev20190216h00-dev
+ provider.null v2.2.0-dev20190415h16-dev
+ provider.random v2.2.0-dev20190415h16-dev
+ provider.template v2.2.0-dev20190415h16-dev
+ provider.tls v2.0.0-dev20190415h16-dev
```

I think this happens with aws_ecs_task_definition container_definitions part (JSON).

**Comment by jbardin** [comment]
The crash here happens while building the structural diff for a change.
I've narrowed down the case that crashes due,  which I'm just documenting here to work on next week.

The crash is the `ctySequenceDiff` function, which diffs 2 sequences of objects.
If the LCS sequence doesn't start at the beginning of both sequences, we end up sliding past the end of the new sequence by inserting a change from null rather than the old sequence. 

For example; if we have 3 objects, `x`, `y`, and `z`, and 2 sequences, `[x, y]` and `[y, z]`, the LCS is `[y]`. In this case we should probably want a diff of `[x->y, y->z]`. Instead we generate `[x->y, null->z]` and then attempt index `new` out of bounds.

**Comment by apparentlymart** [comment]
IIRC the intent here was to create a diff like this for the scenario you described:

```
- x
  y
+ z
```

...so I think in the notation you were using in your comment that'd be `[x->null, y->y, null->z]`, so that we can show that x was removed, y is unchanged, and z was added, similar to how a line-oriented diff of a string would behave.

**Comment by jbardin** [comment]
Thanks Martin, noting it that way clears things up, since the rendering is going to be 

```
      ~ list {
          ~ attr = "x" -> "y"
        }
      ~ list {
          ~ attr = "y" -> "z"
        }
```

That makes the fix relatively easy, because the NoOps should be coming from the LCS.
