### ISSUE TITLE
0.12-beta2 - Runtime panic calculating diff

### ISSUE THREAD

**Issue by m13t** [hashicorp/terraform#21123]
### Terraform Version

```
Terraform v0.12.0-beta2
+ provider.aws v2.7.0
```

### Terraform Configuration Files

Files enclosed in supplied GPG encrypted archive
### Debug Output

Files enclosed in supplied GPG encrypted archive
### Crash Output

File enclosed in the supplied GPG encrypted archive
### Expected Behavior

Changing a value after an initial apply should result in a correct diff

### Actual Behavior

Changing a value results in a runtime panic during diff calculation

```
  # module.docker_service.aws_ecs_service.this will be updated in-place
  ~ resource "aws_ecs_service" "this" {
        cluster                            = "shop-mgmt"
        deployment_maximum_percent         = 200
        deployment_minimum_healthy_percent = 100
        desired_count                      = 3
        enable_ecs_managed_tags            = true
        health_check_grace_period_seconds  = 0
        id                                 = "arn:aws:ecs:eu-west-2:xxxxxxxxxxxx:service/shop-mgmt/shop-gocd-docker-agent"
        launch_type                        = "EC2"
        name                               = "shop-gocd-docker-agent"
        propagate_tags                     = "TASK_DEFINITION"
        scheduling_strategy                = "REPLICA"
        tags                               = {
            "Account"       = "NONPROD"
            "Environment"   = "MGMT"
            "Generation"    = "3"
            "Name"          = "NONPROD/GOCD-DOCKER-AGENT"
        }
      ~ task_definition                    = "arn:aws:ecs:eu-west-2:xxxxxxxxxxxx:task-definition/shop-mgmt-gocd-docker-agent:1" -> (known after apply)

        deployment_controller {
            type = "ECS"
        }

        ordered_placement_strategy {
            field = "attribute:ecs.availability-zone"
            type  = "spread"
        }
        ordered_placement_strategy {
            field = "instanceId"
            type  = "spread"
        }
    }

panic: runtime error: index out of range

goroutine 14 [running]:
github.com/hashicorp/terraform/command/format.ctySequenceDiff(0xc000bda700, 0x8, 0x8, 0xc000bda900, 0x8, 0x8, 0x8, 0x1328bdf, 0x1003747)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format/diff.go:1104 +0xba9
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeValueDiff(0xc00147f6d0, 0x2a18260, 0xc00101fb00, 0x234a1c0, 0xc00101fb20, 0x2a18260, 0xc0012e0ea0, 0x234a1c0, 0xc0012e0ec0, 0x14, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format/diff.go:802 +0x29f
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeValueDiff(0xc00147f6d0, 0x2a181e0, 0xc0002d4dd8, 0x24029e0, 0xc0016b6270, 0x2a181e0, 0xc0002d4e38, 0x24029e0, 0xc0016b77a0, 0x10, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format/diff.go:965 +0x131c
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeValueDiff(0xc00147f6d0, 0x2a18260, 0xc0012e02e0, 0x234a1c0, 0xc0012e0300, 0x2a18260, 0xc0012e1840, 0x234a1c0, 0xc0012e1860, 0xc, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format/diff.go:810 +0x53c
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeValueDiff(0xc00147f6d0, 0x2a180e0, 0xc00003e590, 0x23691a0, 0xc000c5f5d0, 0x2a180e0, 0xc00003e590, 0x23691a0, 0xc000c5fe40, 0x8, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format/diff.go:655 +0x4f17
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeAttrDiff(0xc00147f6d0, 0xc00070cee0, 0x15, 0xc000e4fda0, 0x2a180e0, 0xc00003e590, 0x23691a0, 0xc000c5f5d0, 0x2a180e0, 0xc00003e590, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format/diff.go:263 +0x4c7
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeBlockBodyDiff(0xc00147f6d0, 0xc000c73af0, 0x2a181e0, 0xc0002d4c68, 0x24029e0, 0xc000ca31d0, 0x2a181e0, 0xc0002d4cb8, 0x24029e0, 0xc0012cc690, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format/diff.go:196 +0x5d7
github.com/hashicorp/terraform/command/format.ResourceChange(0xc000d33200, 0xc000b4ed00, 0xc000c73af0, 0xc000717dc0, 0x4d, 0xc00000e3e0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format/diff.go:140 +0x629
github.com/hashicorp/terraform/backend/local.(*Local).renderPlan(0xc0002ac8f0, 0xc000feb5e0, 0xc00000cdf0, 0xc0002d29a0)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:269 +0x6dc
github.com/hashicorp/terraform/backend/local.(*Local).opPlan(0xc0002ac8f0, 0x2a166e0, 0xc0006f0c00, 0x2a166e0, 0xc0006f0c40, 0xc00074aa80, 0xc0006f0bc0)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:165 +0xabe
github.com/hashicorp/terraform/backend/local.(*Local).opPlan-fm(0x2a166e0, 0xc0006f0c00, 0x2a166e0, 0xc0006f0c40, 0xc00074aa80, 0xc0006f0bc0)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:303 +0x66
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc0005dbe60, 0xc0005dbe70, 0xc0005dbe80, 0xc00074aa80, 0xc0002ac8f0, 0xc0006f0bc0, 0xc0005dbe50, 0x2a166e0, 0xc0006f0c00, 0x2a166e0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:356 +0x135
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:340 +0x362
```
### Steps to Reproduce

1. Run terraform apply
2. change any of the input variables
3. Run terraform plan/apply again

### References

- #20750 (Original issue - partially fixed)

[terraform.zip.gpg](https://github.com/hashicorp/terraform/files/3121747/terraform.zip)

**Comment by jbardin** [comment]
Thanks for the config to reproduce this @m13t! This is the same crash as in #21073.

**Comment by m13t** [comment]
Excellent. Sorry for the duplicate - I did look first but obviously not hard enough.

**Comment by jbardin** [comment]
No problem, thanks for the extra info!
