### ISSUE TITLE
unexpected EOF is in only one of the modules

### ISSUE THREAD

**Issue by jaekim09** [hashicorp/terraform#21287]
### Terraform Version
```
$ terraform -v
Terraform v0.11.11
+ provider.azurerm v1.23.0
+ provider.external v1.1.2
+ provider.null v2.1.2
+ provider.random v2.1.2
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

panic: runtime error: index out of range
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4:
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4: goroutine 477 [running]:
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.flattenApplicationGatewayAuthenticationCertificates(0xc000566960, 0xc0007af0a0, 0x8, 0x2225ae0, 0xc000889360)
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_application_gateway.go:1143 +0x55b
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmApplicationGatewayRead(0xc0007af0a0, 0x2583b20, 0xc0002e0000, 0xc0007af0a0, 0x0)
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_application_gateway.go:988 +0x644
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc000431260, 0xc0004a1db0, 0x2583b20, 0xc0002e0000, 0xc0001563c8, 0x4c3901, 0x21c9900)
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:352 +0x160
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc0000e4a10, 0xc0004a1d60, 0xc0004a1db0, 0xc00006ae00, 0x1000, 0x7fa035d40d80)
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x92
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc00062efc0, 0xc000889870, 0xc000889940, 0x0, 0x0)
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4: reflect.Value.call(0xc00009af60, 0xc000098b98, 0x13, 0x25bb656, 0x4, 0xc0002c4f18, 0x3, 0x3, 0xc0003f8000, 0xc000a4c480, ...)
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4:      /opt/goenv/versions/1.11.5/src/reflect/value.go:447 +0x454
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4: reflect.Value.Call(0xc00009af60, 0xc000098b98, 0x13, 0xc0008f6f18, 0x3, 0x3, 0x0, 0x0, 0xc0008f6fc0)
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4:      /opt/goenv/versions/1.11.5/src/reflect/value.go:308 +0xa4
2019-05-13T16:35:34.203-0400 [DEBUG] plugin: plugin process exited: path=/mnt/c/Users/jaewookkim/Desktop/deltek/AzureInfrastructure/.terraform/plugins/linux_amd64/terraform-provider-azurerm_v1.23.0_x4
2019-05-13T16:35:34.203-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4: net/rpc.(*service).call(0xc0000cdf00, 0xc0000b24b0, 0xc0009881f0, 0xc000988200, 0xc000140800, 0xc0003cf660, 0x21c98c0, 0xc000889870, 0x16, 0x21c9900, ...)
2019-05-13T16:35:34.204-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4:      /opt/goenv/versions/1.11.5/src/net/rpc/server.go:384 +0x14e
2019-05-13T16:35:34.204-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4: created by net/rpc.(*Server).ServeCodec
2019-05-13T16:35:34.204-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.23.0_x4:      /opt/goenv/versions/1.11.5/src/net/rpc/server.go:481 +0x47e
2019/05/13 16:35:34 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-05-13T16:35:34.393-0400 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2019-05-13T16:35:34.396-0400 [DEBUG] plugin.terraform-provider-external_v1.1.2_x4: 2019/05/13 16:35:34 [ERR] plugin: stream copy 'stderr' error: stream closed
2019-05-13T16:35:34.396-0400 [DEBUG] plugin.terraform: local-exec-provisioner (internal) 2019/05/13 16:35:34 [ERR] plugin: plugin server: accept unix /tmp/plugin318360323: use of closed network connection
2019-05-13T16:35:34.396-0400 [DEBUG] plugin.terraform-provider-null_v2.1.2_x4: 2019/05/13 16:35:34 [ERR] plugin: plugin server: accept unix /tmp/plugin091699892: use of closed network connection
2019-05-13T16:35:34.397-0400 [DEBUG] plugin.terraform-provider-random_v2.1.2_x4: 2019/05/13 16:35:34 [ERR] plugin: plugin server: accept unix /tmp/plugin814133098: use of closed network connection
2019-05-13T16:35:34.398-0400 [DEBUG] plugin.terraform: local-exec-provisioner (internal) 2019/05/13 16:35:34 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-05-13T16:35:34.398-0400 [DEBUG] plugin.terraform-provider-external_v1.1.2_x4: 2019/05/13 16:35:34 [ERR] plugin: plugin server: accept unix /tmp/plugin857471873: use of closed network connection
2019-05-13T16:35:34.399-0400 [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform
2019-05-13T16:35:34.400-0400 [DEBUG] plugin: plugin process exited: path=/mnt/c/Users/jaewookkim/Desktop/deltek/AzureInfrastructure/.terraform/plugins/linux_amd64/terraform-provider-external_v1.1.2_x4
2019-05-13T16:35:34.400-0400 [DEBUG] plugin: plugin process exited: path=/mnt/c/Users/jaewookkim/Desktop/deltek/AzureInfrastructure/.terraform/plugins/linux_amd64/terraform-provider-null_v2.1.2_x4
2019-05-13T16:35:34.401-0400 [DEBUG] plugin: plugin process exited: path=/mnt/c/Users/jaewookkim/Desktop/deltek/AzureInfrastructure/.terraform/plugins/linux_amd64/terraform-provider-random_v2.1.2_x4

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
### Expected Behavior
terraform plan or apply should work

### Actual Behavior
crashing

### Steps to Reproduce
terraform init
terraform plan (or apply) -target=module.specificRegionModuleName

### Additional Context
I am currently on WSL Ubuntu image. 
I use terraform to setup 6 regions with AzureRM Provider and all others plan/apply ok, but this one is giving the panic error. i use -target=module.regionName so i can control the deployment. 

So far, I have tried deleting .terraform folder (and whatever's inside) and re init. and I had no luck yet. I can manually configure the actual resource manually while we troubleshoot, but I'd like to help figure out what's going on.

**Comment by apparentlymart** [comment]
Hi @jaekim09! Sorry for this crash.

The stack trace in the error message suggests that it was the Azure provider that crashed, rather than Terraform Core. I'm going to ask our GitHub bot to move this issue over into the Azure provider repository since that is likely where the fix will need to be made.
