### ISSUE TITLE
Terraform crashed while creating virtual-machine (azure provider)

### ISSUE THREAD

**Issue by madhukar32** [hashicorp/terraform#21530]
### Terraform Version

```
$ terraform version
Terraform v0.11.11
+ provider.azurerm v1.29.0
+ provider.null v2.1.2
+ provider.template v2.1.2

```

### Crash Output
https://gist.github.com/madhukar32/f7bf7cff15e140761921a0e7fecf0da3

### Expected Behavior

It should have successfully deployed virtual-machine OR should have failed with an error message

### Actual Behavior

It crashed! Without giving a proper error message

**Comment by mildwonkey** [comment]
The crash appears to be coming from the azure provider, so I will move this to the azure repository:


```
2019-05-31T02:08:34.215Z [DEBUG] plugin.terraform-provider-azurerm_v1.29.0_x4: 2019/05/31 02:08:34 [INFO] preparing arguments for Azure ARM Virtual Machine creation.
2019-05-31T02:08:34.218Z [DEBUG] plugin.terraform-provider-azurerm_v1.29.0_x4: panic: interface conversion: interface {} is nil, not map[string]interface {}
2019-05-31T02:08:34.218Z [DEBUG] plugin.terraform-provider-azurerm_v1.29.0_x4: 
2019-05-31T02:08:34.218Z [DEBUG] plugin.terraform-provider-azurerm_v1.29.0_x4: goroutine 738 [running]:
2019-05-31T02:08:34.218Z [DEBUG] plugin.terraform-provider-azurerm_v1.29.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.expandAzureRmVirtualMachinePlan(0xc000272070, 0x3091307, 0x4, 0x2b72240)
2019-05-31T02:08:34.218Z [DEBUG] plugin.terraform-provider-azurerm_v1.29.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_virtual_machine.go:1294 +0x318
2019-05-31T02:08:34.218Z [DEBUG] plugin.terraform-provider-azurerm_v1.29.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmVirtualMachineCreateUpdate(0xc000272070, 0x2fc95e0, 0xc00086a000, 0x0, 0x0)
2019-05-31T02:08:34.218Z [DEBUG] plugin.terraform-provider-azurerm_v1.29.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_virtual_machine.go:663 +0x107a
```
