### ISSUE TITLE
Strong quoting provider versions causes terraform to crash

### ISSUE THREAD

**Issue by ScriptMyJob** [hashicorp/terraform#21642]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

``` sh
$ terraform version
Terraform v0.12.0
+ provider.aws v2.13.0
```

### Affected Resource(s)

* provider

### Terraform Configuration Files

```hcl
provider "aws" {
    region  = var.region
    version = '2.13.0' # This was a mistake on my part it should have been double quoted
}
```

### Panic Output

``` sh
$ terraform validate
panic: value is unknown

goroutine 1 [running]:
github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty.Value.AsString(...)
        /private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/value_ops.go:1032
github.com/hashicorp/terraform/configs.decodeVersionConstraint(0xc0000d0be0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/configs/version_constraint.go:48 +0x9bf
github.com/hashicorp/terraform/configs.decodeProviderBlock(0xc0005ad6c0, 0x8, 0x27bf1a4, 0x8, 0xffffffffffffffff)
        /private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/configs/provider.go:55 +0x847
github.com/hashicorp/terraform/configs.(*Parser).loadConfigFile(0xc0000c8060, 0xc0000cc530, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/configs/parser_config.go:82 +0x1015
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigFile(...)
        /private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/configs/parser_config.go:22
github.com/hashicorp/terraform/configs.(*Parser).loadFiles(0xc0000c8060, 0xc000428000, 0xa, 0x10, 0x0, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
        /private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/configs/parser_config_dir.go:76 +0x343
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigDir(0xc0000c8060, 0x27b81cd, 0x1, 0x12, 0xc0005378a8, 0x22c5662, 0xc000537870)
        /private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/configs/parser_config_dir.go:36 +0x121
github.com/hashicorp/terraform/configs/configload.(*Loader).LoadConfig(0xc0005b4050, 0x27b81cd, 0x1, 0x0, 0x1, 0x2611d00, 0xc00014c3f0)
        /private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/configs/configload/loader_load.go:22 +0x5d
github.com/hashicorp/terraform/command.(*Meta).loadConfig(0xc00053a900, 0x27b81cd, 0x1, 0x10c72ef, 0xc0005b20a0, 0x16, 0x0)
        /private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/command/meta_config.go:66 +0x132
github.com/hashicorp/terraform/command.(*ValidateCommand).validate(0xc00053a900, 0xc0002b0050, 0x41, 0x0, 0x0, 0x0)
        /private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/command/validate.go:79 +0x5f
github.com/hashicorp/terraform/command.(*ValidateCommand).Run(0xc00053a900, 0xc0000bc010, 0x0, 0x0, 0xc0000c1b50)
        /private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/command/validate.go:70 +0x6c2
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc000592140, 0xc000592140, 0xc000537d90, 0x1)
        /private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:255 +0x1f1
main.wrappedMain(0x0)
        /private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/main.go:223 +0xaff
main.realMain(0x0)
        /private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/main.go:100 +0xb4
main.main()
        /private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/main.go:36 +0x3b



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Expected Behavior

I would expect that this would provide me with a pretty message that would have told something meaningful (like what line I was being a big dummy on) to point me in the right direction.

### Actual Behavior

Terraform Crashed

### Steps to Reproduce

1. `terraform validate` with the above strong quoted version number

**Comment by ScriptMyJob** [comment]
Linked a previous issue that I created under the provider for ease of others to find this issue.

**Comment by jbardin** [comment]
Hi @ScriptMyJob,

Thanks for filing the issue. I confirmed that this is fixed in the latest release. You should now see a more useful error like:

```
Error: Invalid character

  on main.tf line 2, in provider "aws":
   2:   version = '2.13.0'
```
