### ISSUE TITLE
Panic/crash when running 'terraform init'

### ISSUE THREAD

**Issue by brikis98** [hashicorp/terraform#21653]
### Terraform Version

```
Terraform v0.12.0
```

### Terraform Configuration Files

In a folder called `hello-world`, I have a `main.tf` with the contents:

```hcl
data "template_file" "test" {
  template = "${module.hello.hello}, ${var.name}"
}

variable "name" {
  description = "Specify a name"
}

output "test" {
  value = "${data.template_file.test.rendered}"
}

module "hello" {
  source = "./hello"
}

module "remote" {
  source = "github.com/gruntwork-io/terragrunt.git//test/fixture-download/hello-world?ref=v0.9.9"
  name = "${var.name}"
}
```

The module code being downloaded in `source` is this: https://github.com/gruntwork-io/terragrunt/tree/v0.9.9/test/fixture-download/hello-world

### Expected Behavior

I can run `terraform init -from-module=../hello-world .` without errors.

### Actual Behavior

Terraform panics and crashes:

```
Copying configuration from "file:///Users/brikis98/src/github.com/gruntwork-io/terragrunt/test/fixture-download/hello-world"...
Downloading github.com/gruntwork-io/terragrunt.git?ref=v0.9.9 for remote...
panic: Rel: can't make /Users/brikis98/src/github.com/gruntwork-io/terragrunt/test/fixture-download/hello-world/hello relative to 

goroutine 1 [running]:
github.com/hashicorp/terraform/internal/initwd.DirFromModule(0x7ffeefbffa3c, 0x49, 0xc000042280, 0x12, 0x7ffeefbff97c, 0x5f, 0xc000294140, 0x2bcf480, 0xc00000c100, 0x18, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/internal/initwd/from_module.go:269 +0x364c
github.com/hashicorp/terraform/command.(*Meta).initDirFromModule(0xc0000af1e0, 0x7ffeefbffa3c, 0x49, 0x7ffeefbff97c, 0x5f, 0x2bcf480, 0xc00000c100, 0x6, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_config.go:252 +0x194
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc0000af1e0, 0xc00003a0a0, 0x5, 0x6, 0xc0003f00c0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/init.go:148 +0x2992
github.com/mitchellh/cli.(*CLI).Run(0xc00044a500, 0xc00044a500, 0xc000531d90, 0x1)
	/opt/gopath/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:223 +0xaff
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:100 +0xb4
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:36 +0x3b



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Steps to Reproduce

```
terraform init -from-module=../hello-world
```

**Comment by brikis98** [comment]
Update: removing the following fixes the crash:

```hcl
module "hello" {
  source = "./hello"
}
```

So something about calling `init -from-module=foo` on a module `foo` that sets `source` to a relative path.

**Comment by brikis98** [comment]
For context, I'm hitting this as part of upgrading [Terragrunt to work with Terraform 0.12](https://github.com/gruntwork-io/terragrunt/pull/731). Terragrunt uses `terraform init -from-module` extensively, so if that's broken when downloading any module that references other modules, this will be a blocker. I asked in https://github.com/hashicorp/terraform/issues/18460 if it would be better for Terragrunt to use `go-getter` directly to work around another issue with `init -from-module`; perhaps now is the time to do that after all?

**Comment by josh-padnick** [comment]
Try with Terraform 012.1?

**Comment by brikis98** [comment]
Same crash with 0.12.1.

**Comment by pselle** [comment]
Hi @brikis98! When I try to replicate this, I get an error that is the same both with and without the `.` at the end of the command. Please let us know if you're still seeing this, and any further replication if so.

```
$ terraform init -from-module=../hello-world 
The working directory already contains files. The -from-module option requires
an empty directory into which a copy of the referenced module will be placed.

To initialize the configuration already in this working directory, omit the
-from-module option.
```
