### ISSUE TITLE
Terraform crash on plan

### ISSUE THREAD

**Issue by unused1** [hashicorp/terraform#21660]
terraform --version
Terraform v0.12.1
+ provider.aws v2.14.0

2019/06/09 10:36:35 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
panic: inconsistent map element types (cty.Object(map[string]cty.Type{"deploy_tier":cty.String, "ingresscidr":cty.List(cty.Object(map[string]cty.Type{"cidr_blocks":cty.String, "rule":cty.String})), "ingresssg":cty.List(cty.DynamicPseudoType), "name":cty.String, "sg_purpose":cty.String}) then cty.Object(map[string]cty.Type{"deploy_tier":cty.String, "ingresscidr":cty.List(cty.DynamicPseudoType), "ingresssg":cty.List(cty.DynamicPseudoType), "name":cty.String, "sg_purpose":cty.String}))

goroutine 49 [running]:
github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty.MapVal(0xc000242ca0, 0xc000242c00, 0xc0005b321c, 0x3, 0xc000242d98)
        /private/tmp/terraform-20190604-27676-1a0ssfs/terraform-0.12.1/src/github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/value_init.go:207 +0x538
github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert.conversionObjectToMap.func2(0x2bebf60, 0xc0000b05d8, 0x24f0100, 0xc00075ffb0, 0xc0001e7480, 0x3, 0x4, 0x1, 0xc000242ef0, 0x1009538, ...)
        /private/tmp/terraform-20190604-27676-1a0ssfs/terraform-0.12.1/src/github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert/conversion_collection.go:338 +0x6c3
github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert.getConversion.func1(0x2bebf60, 0xc0000b05d8, 0x24f0100, 0xc00075ffb0, 0xc00059f920, 0x2, 0x2, 0x24f0100, 0xc00075ffb0, 0x24321e0, ...)
        /private/tmp/terraform-20190604-27676-1a0ssfs/terraform-0.12.1/src/github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert/conversion.go:34 +0xef
github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert.conversionObjectToObject.func1(0x2bebf60, 0xc0000b05e0, 0x24f0100, 0xc00069e030, 0xc00059f920, 0x2, 0x2, 0xe, 0x100398a, 0xc00003e3d9, ...)
        /private/tmp/terraform-20190604-27676-1a0ssfs/terraform-0.12.1/src/github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert/conversion_object.go:65 +0x49c
github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert.getConversion.func1(0x2bebf60, 0xc0000b05e0, 0x24f0100, 0xc00069e030, 0xc0007159e0, 0x1, 0x1, 0x24f0100, 0xc00069e030, 0xc00040632a, ...)
        /private/tmp/terraform-20190604-27676-1a0ssfs/terraform-0.12.1/src/github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert/conversion.go:34 +0xef
github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert.conversionObjectToMap.func2(0x2bebf60, 0xc0000b0668, 0x24f0100, 0xc00069e690, 0xc0007159e0, 0x1, 0x1, 0x4271b28, 0x0, 0x100be98, ...)
        /private/tmp/terraform-20190604-27676-1a0ssfs/terraform-0.12.1/src/github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert/conversion_collection.go:330 +0x583
github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert.getConversion.func1(0x2bebf60, 0xc0000b0668, 0x24f0100, 0xc00069e690, 0x0, 0x0, 0x0, 0xc00059f8a0, 0xc0007159d0, 0x2bebf20, ...)
        /private/tmp/terraform-20190604-27676-1a0ssfs/terraform-0.12.1/src/github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert/conversion.go:34 +0xef
github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert.retConversion.func1(0x2bebf60, 0xc0000b0668, 0x24f0100, 0xc00069e690, 0xc0007159d0, 0xc0007141f0, 0x2, 0x24eb3c0, 0xc000435278, 0xc000195978)
        /private/tmp/terraform-20190604-27676-1a0ssfs/terraform-0.12.1/src/github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert/conversion.go:141 +0x6b
github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert.Convert(0x2bebf60, 0xc0000b0668, 0x24f0100, 0xc00069e690, 0x2bebf20, 0xc000762700, 0x2bebee0, 0xc0007141f0, 0x24321e0, 0xc0001a7bc0, ...)
        /private/tmp/terraform-20190604-27676-1a0ssfs/terraform-0.12.1/src/github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/convert/public.go:51 +0x1af
github.com/hashicorp/terraform/terraform.checkInputVariables(0xc000654780, 0xc00069f590, 0x8, 0xc000714040, 0x100)
        /private/tmp/terraform-20190604-27676-1a0ssfs/terraform-0.12.1/src/github.com/hashicorp/terraform/terraform/variables.go:255 +0x191
github.com/hashicorp/terraform/terraform.(*Context).Validate(0xc000767ef0, 0x0, 0x0, 0x0)
        /private/tmp/terraform-20190604-27676-1a0ssfs/terraform-0.12.1/src/github.com/hashicorp/terraform/terraform/context.go:656 +0x4d2
github.com/hashicorp/terraform/backend/local.(*Local).context(0xc00032c340, 0xc000200e00, 0x1, 0x1, 0x2, 0xc0004037c0, 0x1, 0x2, 0x0)
        /private/tmp/terraform-20190604-27676-1a0ssfs/terraform-0.12.1/src/github.com/hashicorp/terraform/backend/local/backend_local.go:120 +0x974
github.com/hashicorp/terraform/backend/local.(*Local).opPlan(0xc00032c340, 0x2bea420, 0xc0001b7800, 0x2bea420, 0xc0001b7840, 0xc000200e00, 0xc0001b77c0)
        /private/tmp/terraform-20190604-27676-1a0ssfs/terraform-0.12.1/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:67 +0x2a3
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc0003fe170, 0xc0003fe180, 0xc0003fe190, 0xc000200e00, 0xc00032c340, 0xc0001b77c0, 0xc0003fe160, 0x2bea420, 0xc0001b7800, 0x2bea420, ...)
        /private/tmp/terraform-20190604-27676-1a0ssfs/terraform-0.12.1/src/github.com/hashicorp/terraform/backend/local/backend.go:356 +0x135
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
        /private/tmp/terraform-20190604-27676-1a0ssfs/terraform-0.12.1/src/github.com/hashicorp/terraform/backend/local/backend.go:340 +0x36b

**Comment by unused1** [comment]
it is produced when the "sg" map in the following variable is defined.

variable "XXX_networks" {
  type = map(object({
    name=string, vpcid=string, reqallowdns=list(string), accallowdns=list(string), deploy_zone=string,
    subnets=map(object({ name=string, deploy_tier=string, cidr_block=list(string), vpcpeer_dest=list(string), vpcpeer_mapid=list(string), sn_purpose=string, rt_purpose=string })),
    sg=map(object({ name=string, deploy_tier=string, ingresscidr=list(any), ingresssg=list(any), sg_purpose=string })),
  }))
  description = "Map of XXX network."
}

example of variable set in tfvars:
iexams_networks = {
  iexams_bastion = {
    name = "bastion"
    vpcid = "vpc-fdsagrhdfgfdafds"
    reqallowdns = []
    accallowdns = ["pcx-fdsafeadgsafd"]
    deploy_zone = "ez"
    subnets = {
      vpn = { name="vpn", deploy_tier="ra", cidr_block=["1.2.3.4/28"], vpcpeer_dest=["1.2.3.4/24"], vpcpeer_mapid=["mgmt_bastion"],
        sn_purpose="Public subnet for Bastion tier - vpn.",
        rt_purpose="Route table for public subnet in Bastion tier - vpn."
      },
      jhost = { name="jhost", deploy_tier="ra", cidr_block=["1.2.3.4/28"], vpcpeer_dest=["1.2.3.4/24"], vpcpeer_mapid=["mgmt_bastion"],
        sn_purpose="Private subnet for Bastion tier - bastion.",
        rt_purpose="Route table for private subnet in Bastion tier - bastion."
      },
    },
    sg = {
      jhost = { name="jhost", deploy_tier="ra",
        ingresscidr=[
          {
            rule        = "rdp-tcp"
            cidr_blocks = "1.2.3.4/32,5.6.7.8/32"
          },
          {
            rule        = "winrm-https-tcp"
            cidr_blocks = "1.2.3.4/32,5.6.7.8/32"
          },
        ],
        ingresssg=[
          {
            from_port   = 1234
            to_port     = 1234
            protocol    = "tcp"
            description = "Example port with security group"
            source_security_group_mapid = "mgmt_jhost"
          }
        ],
        sg_purpose="Allowed traffic for bastion server",
      },
  }
}

**Comment by unused1** [comment]
this seems to be triggered when there is a variable that is passed with empty list. e.g.

    s3 = { name="s3", deploy_tier="tmt",
      ingresscidr=[],
      ingresssg=[],
      sg_purpose="Allowed traffic for S3 endpoint",
    },

**Comment by unused1** [comment]
changed to use map(any)

variable "XXX_networks" {
type = map(any)
description = "Map of XXX network."
}
