### ISSUE TITLE
Terraform plan crashes

### ISSUE THREAD

**Issue by Alexey1Gavrilov** [hashicorp/terraform#21832]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1a1b754]

goroutine 251 [running]:
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc000167950, 0x0, 0x0, 0x2dea2a0, 0x3ee48d8, 0xc000096f00, 0x0, 0xc000dc6768, 0x3, 0xc00005b470, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/lang/eval.go:95 +0x194
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateExpr(0xc000260680, 0x0, 0x0, 0x2dea2a0, 0x3ee48d8, 0x0, 0x0, 0x3ec4c60, 0x6b, 0x2a30f70, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:284 +0x1e4
github.com/hashicorp/terraform/terraform.(*EvalWriteOutput).Eval(0xc000b844b0, 0x2e1c120, 0xc000260680, 0x2, 0x2, 0xc000666000, 0x68)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_output.go:48 +0x153
github.com/hashicorp/terraform/terraform.EvalRaw(0x2da8d20, 0xc000b844b0, 0x2e1c120, 0xc000260680, 0x53, 0x0, 0x0, 0x53)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc000b844e0, 0x2e1c120, 0xc000260680, 0x2, 0x2, 0xc000dc6b10, 0x103d4e4)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x4c
github.com/hashicorp/terraform/terraform.EvalRaw(0x2da8ae0, 0xc000b844e0, 0x2e1c120, 0xc000260680, 0x14, 0xbf3b4204eac1b978, 0xd0f91459, 0x53)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc000398140, 0x2e1c120, 0xc000260680, 0x2, 0x2, 0x1abe1c5, 0x2da8ae0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x2da8c20, 0xc000398140, 0x2e1c120, 0xc000260680, 0x2663a20, 0x3d9a405, 0x25d0da0, 0xc000606700)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.Eval(0x2da8c20, 0xc000398140, 0x2e1c120, 0xc000260680, 0xc000398140, 0x2da8c20, 0xc000398140, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x282c680, 0xc0009fd950, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:90 +0xf40
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000144680, 0x282c680, 0xc0009fd950, 0xc000423700)
	/opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x353
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa9b

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Terraform Version
```
Terraform 0.12.2
```

### Crash Output
https://gist.github.com/Alexey1Gavrilov/6b4afeebd90fe336484883a639520649

**Comment by mildwonkey** [comment]
Hi! Thank you for reporting this crash, and I am sorry that you've experienced it.

We'll need some more information to debug this. Can you please update this ticket with the information requested in the [issue template](https://github.com/hashicorp/terraform/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)? Remove any sensitive information first. 

Thanks again!
