### ISSUE TITLE
Terraform v0.12.3 crash when applying terraform plan

### ISSUE THREAD

**Issue by yiweny** [hashicorp/terraform#21878]
Error message is shown as follows. 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1a2c8d4]

goroutine 266 [running]:
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc0003f0870, 0x0, 0x0, 0x2e05780, 0x3f14918, 0xc000b67380, 0x0, 0xc00098b768, 0x3, 0xc000068a70, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/lang/eval.go:95 +0x194
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateExpr(0xc000238000, 0x0, 0x0, 0x2e05780, 0x3f14918, 0x0, 0x0, 0x3ef4ca0, 0x5d, 0x2a3cf80, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:284 +0x1e4
github.com/hashicorp/terraform/terraform.(*EvalWriteOutput).Eval(0xc000bfc4e0, 0x2e377a0, 0xc000238000, 0x2, 0x2, 0xc00099c000, 0x5a)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_output.go:48 +0x153
github.com/hashicorp/terraform/terraform.EvalRaw(0x2dc4300, 0xc000bfc4e0, 0x2e377a0, 0xc000238000, 0x45, 0x0, 0x0, 0x45)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc000bfc540, 0x2e377a0, 0xc000238000, 0x2, 0x2, 0xc00098bb38, 0x102b231)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x4c
github.com/hashicorp/terraform/terraform.EvalRaw(0x2dc40c0, 0xc000bfc540, 0x2e377a0, 0xc000238000, 0x14, 0xbf3cb58c0d1722a0, 0x25e06311, 0x45)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc00069a020, 0x2e377a0, 0xc000238000, 0x2, 0x2, 0x1acf345, 0x2dc40c0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x2dc4200, 0xc00069a020, 0x2e377a0, 0xc000238000, 0x266f240, 0x3dca405, 0x25dc320, 0xc000150550)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.Eval(0x2dc4200, 0xc00069a020, 0x2e377a0, 0xc000238000, 0xc00069a020, 0x2dc4200, 0xc00069a020, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2838060, 0xc0008fad80, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph.go:90 +0xf40
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000577d80, 0x2838060, 0xc0008fad80, 0xc0002b6240)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x353
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa9b
```

**Comment by ashish30jain** [comment]
Same during apply plan init.

019/06/25 23:50:44 [INFO] Terraform version: 0.12.3
2019/06/25 23:50:44 [INFO] Go runtime version: go1.12.4
2019/06/25 23:50:44 [INFO] CLI args: []string{"/usr/bin/terraform12", "apply", "-var", "workspace=development"}
2019/06/25 23:50:44 [DEBUG] Attempting to open CLI config file: /xxxxx/.terraformrc
2019/06/25 23:50:44 Loading CLI configuration from /xxxxx/.terraformrc
2019/06/25 23:50:44 [INFO] CLI command args: []string{"apply", "-var", "workspace=development"}
2019/06/25 23:50:44 [TRACE] Meta.Backend: built configuration for "remote" backend with hash value 2156721850
2019/06/25 23:50:44 [TRACE] Preserving existing state lineage "65e0e276-81f1-4a13-a6c2-7ad237241015"
2019/06/25 23:50:44 [TRACE] Preserving existing state lineage "65e0e276-81f1-4a13-a6c2-7ad237241015"
2019/06/25 23:50:44 [TRACE] Meta.Backend: working directory was previously initialized for "remote" backend
2019/06/25 23:50:44 [TRACE] Meta.Backend: using already-initialized, unchanged "remote" backend configuration
2019/06/25 23:50:44 [DEBUG] Service discovery for app.terraform.io at https://app.terraform.io/.well-known/terraform.json
2019/06/25 23:50:45 [DEBUG] Retrieve version constraints for service tfe.v2.1 and product terraform
2019/06/25 23:50:48 [TRACE] Meta.Backend: instantiated backend of type *remote.Remote
2019/06/25 23:50:48 [DEBUG] checking for provider in "."
2019/06/25 23:50:48 [DEBUG] checking for provider in "/usr/bin"
2019/06/25 23:50:48 [DEBUG] checking for provisioner in "."
2019/06/25 23:50:48 [DEBUG] checking for provisioner in "/usr/bin"
2019/06/25 23:50:48 [INFO] Failed to read plugin lock file .terraform/plugins/linux_amd64/lock.json: open .terraform/plugins/linux_amd64/lock.json: no such file or directory
2019/06/25 23:50:48 [TRACE] Meta.Backend: backend *remote.Remote supports operations
2019/06/25 23:50:49 [INFO] backend/local: starting Apply operation
2019/06/25 23:50:49 [TRACE] backend/local: requesting state manager for workspace "development"
2019/06/25 23:50:49 [TRACE] backend/local: requesting state lock for workspace "development"
2019/06/25 23:50:50 [TRACE] backend/local: reading remote state for workspace "development"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x101b8c0]
https://github.com/hashicorp/terraform/issues/21878

**Comment by dnvikram** [comment]
Similar issue, though I am on **Terraform version 0.12.2**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1ad1ff3]

goroutine 610 [running]:
github.com/hashicorp/terraform/terraform.(*evaluationStateData).getResourceInstancesAll(0xc00015c7e0, 0x4d, 0xc00056d190, 0xf, 0xc00056d186, 0xa, 0xc00046fb90, 0x25, 0xf, 0x12, ...)
 /opt/gopath/src/github.com/hashicorp/terraform/terraform/evaluate.go:704 +0x11a3
github.com/hashicorp/terraform/terraform.(*evaluationStateData).GetResourceInstance(0xc00015c7e0, 0x4d, 0xc00056d190, 0xf, 0xc00056d186, 0xa, 0x0, 0x0, 0xc00046fb90, 0x25, ...)
 /opt/gopath/src/github.com/hashicorp/terraform/terraform/evaluate.go:593 +0x1360
github.com/hashicorp/terraform/lang.(*Scope).evalContext(0xc0011e4c80, 0xc00057c268, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x47a4870)
 /opt/gopath/src/github.com/hashicorp/terraform/lang/eval.go:253 +0xfcc
github.com/hashicorp/terraform/lang.(*Scope).EvalContext(...)
 /opt/gopath/src/github.com/hashicorp/terraform/lang/eval.go:160
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc0011e4c80, 0x4478548, 0xc0003b14a0, 0x2dea2a0, 0x3ee48d8, 0x0, 0x10cf0e0, 0xc000a3d6a7, 0x10348ab, 0xc0009756f0, ...)
 /opt/gopath/src/github.com/hashicorp/terraform/lang/eval.go:87 +0xb3
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateExpr(0xc001208a90, 0x4478548, 0xc0003b14a0, 0x2dea2a0, 0x3ee48d8, 0x0, 0x0, 0xb, 0x2a, 0xc0000c4018, ...)
 /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:284 +0x1e4
github.com/hashicorp/terraform/terraform.(*EvalModuleCallArgument).Eval(0xc000a5d000, 0x2e1c120, 0xc001208a90, 0x2, 0x2, 0xc000ebe000, 0x53)
 /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_variable.go:156 +0xf3
github.com/hashicorp/terraform/terraform.EvalRaw(0x2da8aa0, 0xc000a5d000, 0x2e1c120, 0xc001208a90, 0x3e, 0x0, 0x0, 0x3e)
 /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc0015709f0, 0x2e1c120, 0xc001208a90, 0x2, 0x2, 0xc000975b38, 0x102b231)
 /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x4c
github.com/hashicorp/terraform/terraform.EvalRaw(0x2da8ae0, 0xc0015709f0, 0x2e1c120, 0xc001208a90, 0x14, 0xbf3cb8aa51595090, 0x320ba5ba2, 0x3e)
 /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc0001653a0, 0x2e1c120, 0xc001208a90, 0x2, 0x2, 0x1abe1c5, 0x2da8c40)
 /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x2da8c20, 0xc0001653a0, 0x2e1c120, 0xc001208a90, 0x2663a20, 0x3d9a404, 0x25d0da0, 0xc00167f900)
 /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.Eval(0x2da8c20, 0xc0001653a0, 0x2e1c120, 0xc001208a90, 0xc0001653a0, 0x2da8c20, 0xc0001653a0, 0x0)
 /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x28136e0, 0xc000d23380, 0x0, 0x0, 0x0)
 /opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:90 +0xf40
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00014db80, 0x28136e0, 0xc000d23380, 0xc0006ecc40)
 /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x353
created by github.com/hashicorp/terraform/dag.(*Walker).Update
 /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa9b



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by yiweny** [comment]
The issue was resolved when I roll back to version 0.11.4

**Comment by danieldreier** [comment]
@yiweny are you still encountering this on a recent version of 0.12, like 0.12.26? This was reported without a terraform config file, so it's hard for us to reproduce it (and therefore fix it) because I don't know what to run to trigger this crash.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
