### ISSUE TITLE
panic: AttributeTypes on non-object Type

### ISSUE THREAD

**Issue by urvishhingu** [hashicorp/terraform#21964]
### Terraform Version

```
Terraform v0.12.3
```

### Terraform Configuration Files

```
locals {
 standard_tags = {
    Environment:"test"
  }
}
resource "aws_s3_bucket" "blabla-bucket" {
  bucket = "blabla"
  acl = "public"
  dynamic "tag" {
    for_each = locals.standard_tags
    content {
      key = tag.key
      value = tag.value
    }
  }
}
```

### Crash Output

```
panic: AttributeTypes on non-object Type

goroutine 14 [running]:
github.com/zclconf/go-cty/cty.Type.AttributeTypes(...)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.0.0/cty/object_type.go:134
github.com/hashicorp/terraform/lang/blocktoattr.SchemaForCtyElementType(0x2206c00, 0xc00003e3f0, 0x2206c00)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/lang/blocktoattr/schema.go:108 +0x24d
github.com/hashicorp/terraform/lang/blocktoattr.walkVariables(0x2205880, 0xc00049e210, 0x0, 0xc000341201, 0x2205880, 0xc00049e210, 0xc000464730, 0x0, 0xc001456800, 0xc000341308)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/lang/blocktoattr/variables.go:37 +0x476
github.com/hashicorp/terraform/lang/blocktoattr.ExpandedVariables(...)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/lang/blocktoattr/variables.go:24
github.com/hashicorp/terraform/lang.ReferencesInBlock(0x2205880, 0xc00049e210, 0xc000464730, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0003c8660)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/lang/references.go:68 +0x66
github.com/hashicorp/terraform/terraform.(*NodeAbstractResource).References(0xc00049e630, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/node_resource_abstract.go:190 +0x251
github.com/hashicorp/terraform/terraform.NewReferenceMap(0xc000c926e0, 0x16, 0x16, 0x16)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/transform_reference.go:402 +0x24a
github.com/hashicorp/terraform/terraform.(*ReferenceTransformer).Transform(0x3311ca0, 0xc000452d70, 0x14, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/transform_reference.go:73 +0x71
github.com/hashicorp/terraform/terraform.(*BasicGraphBuilder).Build(0xc000341900, 0x0, 0x0, 0x0, 0x32f1fe0, 0xc000341930, 0x4e5650, 0xc00008c000)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph_builder.go:50 +0x477
github.com/hashicorp/terraform/terraform.(*PlanGraphBuilder).Build(0xc000418150, 0x0, 0x0, 0x0, 0x1, 0x0, 0x1a7b780, 0xc00051fa70)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph_builder_plan.go:65 +0xbc
github.com/hashicorp/terraform/terraform.(*Context).Graph(0xc0004540f0, 0x6, 0xc000341986, 0xc000341a00, 0x1, 0x1, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/context.go:292 +0x1b8
github.com/hashicorp/terraform/terraform.(*Context).Validate(0xc0004540f0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/context.go:670 +0xf3
github.com/hashicorp/terraform/backend/local.(*Local).context(0xc000568000, 0xc00047bc00, 0x1, 0x1, 0x3, 0xc00051e960, 0x1, 0x3, 0xc000430738)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend_local.go:120 +0x974
github.com/hashicorp/terraform/backend/local.(*Local).opApply(0xc000568000, 0x22051c0, 0xc0003f3980, 0x22051c0, 0xc0003f39c0, 0xc00047bc00, 0xc0003f3940)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend_apply.go:53 +0x2e4
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc000490630, 0xc000490640, 0xc000490650, 0xc00047bc00, 0xc000568000, 0xc0003f3940, 0xc000490620, 0x22051c0, 0xc0003f3980, 0x22051c0, ...)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend.go:356 +0x135
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend.go:340 +0x36b

```
### Expected Behavior

- Syntax error at line number x.

### Actual Behavior

- It throws the following error.
**panic: AttributeTypes on non-object Type**
### Steps to Reproduce

- terraform init
- terraform apply

**Comment by jbardin** [comment]
Hi @urvishhingu,

Thanks for reporting this. It appears that adding a dynamic block where no block exists manages to slip through validation. There is no `tag` block for an `aws_s3_bucket`. The docs do show there is a `tags` attribute, which means you have to assign the map using `=`.

**Comment by urvishhingu** [comment]
@jbardin Thanks for the help. I assigned it using the map and it works.
