### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by aktheraja** [hashicorp/terraform#21997]
```
2019/07/07 15:25:11 [INFO] Terraform version: 0.12.0  
2019/07/07 15:25:11 [INFO] Go runtime version: go1.12.4
2019/07/07 15:25:11 [INFO] CLI args: []string{"C:\\Terraform\\terraform.exe", "plan"}
2019/07/07 15:25:11 [DEBUG] Attempting to open CLI config file: C:\Users\akfre\AppData\Roaming\terraform.rc
2019/07/07 15:25:11 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/07/07 15:25:11 [INFO] CLI command args: []string{"plan"}
2019/07/07 15:25:11 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2019/07/07 15:25:11 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2019/07/07 15:25:11 [DEBUG] New state was assigned lineage "b434fd32-69ee-cf8a-d75b-c34d0d9aa66d"
2019/07/07 15:25:11 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2019/07/07 15:25:11 [TRACE] Meta.Backend: instantiated backend of type <nil>
2019/07/07 15:25:11 [DEBUG] checking for provider in "."
2019/07/07 15:25:11 [DEBUG] checking for provider in "C:\\Terraform"
2019/07/07 15:25:11 [DEBUG] checking for provider in ".terraform\\plugins\\windows_amd64"
2019/07/07 15:25:11 [DEBUG] found provider "terraform-provider-aws_v2.17.0_x4.exe"
2019/07/07 15:25:11 [DEBUG] found valid plugin: "aws", "2.17.0", "C:\\Terraform\\Terraform Capstone\\Terraform\\.terraform\\plugins\\windows_amd64\\terraform-provider-aws_v2.17.0_x4.exe"
2019/07/07 15:25:11 [DEBUG] checking for provisioner in "."
2019/07/07 15:25:11 [DEBUG] checking for provisioner in "C:\\Terraform"
2019/07/07 15:25:11 [DEBUG] checking for provisioner in ".terraform\\plugins\\windows_amd64"
2019/07/07 15:25:11 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
2019/07/07 15:25:11 [INFO] backend/local: starting Plan operation
2019/07/07 15:25:11 [TRACE] backend/local: requesting state manager for workspace "default"
2019/07/07 15:25:11 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2019/07/07 15:25:11 [TRACE] backend/local: requesting state lock for workspace "default"
2019/07/07 15:25:11 [TRACE] statemgr.Filesystem: preparing to manage state snapshots at terraform.tfstate
2019/07/07 15:25:11 [TRACE] statemgr.Filesystem: existing snapshot has lineage "34534c50-af22-8866-6007-35fe639944c8" serial 215
2019/07/07 15:25:11 [TRACE] statemgr.Filesystem: locking terraform.tfstate using LockFileEx
2019/07/07 15:25:11 [TRACE] statemgr.Filesystem: writing lock metadata to .terraform.tfstate.lock.info
2019/07/07 15:25:11 [TRACE] backend/local: reading remote state for workspace "default"
2019/07/07 15:25:11 [TRACE] statemgr.Filesystem: reading latest snapshot from terraform.tfstate
2019/07/07 15:25:11 [TRACE] statemgr.Filesystem: read snapshot with lineage "34534c50-af22-8866-6007-35fe639944c8" serial 215
2019/07/07 15:25:11 [TRACE] backend/local: retrieving local state snapshot for workspace "default"
2019/07/07 15:25:11 [TRACE] backend/local: building context for current working directory
2019/07/07 15:25:11 [TRACE] terraform.NewContext: starting
2019/07/07 15:25:11 [TRACE] terraform.NewContext: resolving provider version selections
2019/07/07 15:25:12 [TRACE] terraform.NewContext: loading provider schemas
2019/07/07 15:25:12 [TRACE] LoadSchemas: retrieving schema for provider type "aws"
2019-07-07T15:25:12.066-0600 [INFO]  plugin: configuring client automatic mTLS
2019-07-07T15:25:12.106-0600 [DEBUG] plugin: starting plugin: path="C:\Terraform\Terraform Capstone\Terraform\.terraform\plugins\windows_amd64\terraform-provider-aws_v2.17.0_x4.exe" args=["C:\Terraform\Terraform Capstone\Terraform\.terraform\plugins\windows_amd64\terraform-provider-aws_v2.17.0_x4.exe"]
2019-07-07T15:25:12.120-0600 [DEBUG] plugin: plugin started: path="C:\Terraform\Terraform Capstone\Terraform\.terraform\plugins\windows_amd64\terraform-provider-aws_v2.17.0_x4.exe" pid=16612
2019-07-07T15:25:12.120-0600 [DEBUG] plugin: waiting for RPC address: path="C:\Terraform\Terraform Capstone\Terraform\.terraform\plugins\windows_amd64\terraform-provider-aws_v2.17.0_x4.exe"
2019-07-07T15:25:12.177-0600 [INFO]  plugin.terraform-provider-aws_v2.17.0_x4.exe: configuring server automatic mTLS: timestamp=2019-07-07T15:25:12.177-0600
2019-07-07T15:25:12.213-0600 [DEBUG] plugin.terraform-provider-aws_v2.17.0_x4.exe: plugin address: address=127.0.0.1:10000 network=tcp timestamp=2019-07-07T15:25:12.212-0600
2019-07-07T15:25:12.213-0600 [DEBUG] plugin: using plugin: version=5
2019/07/07 15:25:12 [TRACE] GRPCProvider: GetSchema
2019/07/07 15:25:12 [TRACE] GRPCProvider: Close
2019-07-07T15:25:12.366-0600 [DEBUG] plugin: plugin process exited: path="C:\Terraform\Terraform Capstone\Terraform\.terraform\plugins\windows_amd64\terraform-provider-aws_v2.17.0_x4.exe" pid=16612
2019-07-07T15:25:12.366-0600 [DEBUG] plugin: plugin exited
2019/07/07 15:25:12 [TRACE] terraform.NewContext: complete
2019/07/07 15:25:12 [TRACE] backend/local: finished building terraform.Context
2019/07/07 15:25:12 [TRACE] backend/local: requesting interactive input, if necessary
2019/07/07 15:25:12 [TRACE] Context.Input: Prompting for variables
2019/07/07 15:25:12 [TRACE] Context.Input: Prompting for provider arguments
2019/07/07 15:25:12 [TRACE] Context.Input: Provider provider.aws declared at connection.tf:1,1-15
2019/07/07 15:25:12 [TRACE] Context.Input: Input for provider.aws: map[string]cty.Value{}
2019/07/07 15:25:12 [TRACE] backend/local: running validation operation
2019/07/07 15:25:12 [INFO] terraform: building graph: GraphTypeValidate
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.ConfigTransformer
2019/07/07 15:25:12 [TRACE] ConfigTransformer: Starting for path: 
2019/07/07 15:25:12 [TRACE] Completed graph transform *terraform.ConfigTransformer with new graph:
aws_security_group.private_subnesecurity - *terraform.NodeValidatableResource
aws_security_group.security - *terraform.NodeValidatableResource
aws_subnet.private_subnet1 - *terraform.NodeValidatableResource
aws_subnet.private_subnet2 - *terraform.NodeValidatableResource
aws_subnet.public_subnet1 - *terraform.NodeValidatableResource
aws_subnet.public_subnet2 - *terraform.NodeValidatableResource
aws_vpc.vpc_environment - *terraform.NodeValidatableResource
------
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.LocalTransformer
2019/07/07 15:25:12 [TRACE] Completed graph transform *terraform.LocalTransformer (no changes)
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.OutputTransformer
2019/07/07 15:25:12 [TRACE] Completed graph transform *terraform.OutputTransformer (no changes)
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.OrphanResourceInstanceTransformer
2019/07/07 15:25:12 [TRACE] OrphanResourceInstanceTransformer: adding single-instance orphan node for aws_launch_configuration.autoscale_launch_config
2019/07/07 15:25:12 [TRACE] Completed graph transform *terraform.OrphanResourceInstanceTransformer with new graph:
aws_launch_configuration.autoscale_launch_config - *terraform.NodeAbstractResourceInstance
aws_security_group.private_subnesecurity - *terraform.NodeValidatableResource
aws_security_group.security - *terraform.NodeValidatableResource
aws_subnet.private_subnet1 - *terraform.NodeValidatableResource
aws_subnet.private_subnet2 - *terraform.NodeValidatableResource
aws_subnet.public_subnet1 - *terraform.NodeValidatableResource
aws_subnet.public_subnet2 - *terraform.NodeValidatableResource
aws_vpc.vpc_environment - *terraform.NodeValidatableResource
------
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.StateTransformer
2019/07/07 15:25:12 [TRACE] StateTransformer: creating nodes for deposed instance objects only
2019/07/07 15:25:12 [TRACE] StateTransformer: added *terraform.NodePlanDeposedResourceInstanceObject for aws_launch_configuration.autoscale_launch_config deposed object d98078d2
2019/07/07 15:25:12 [TRACE] Completed graph transform *terraform.StateTransformer with new graph:
aws_launch_configuration.autoscale_launch_config - *terraform.NodeAbstractResourceInstance
aws_launch_configuration.autoscale_launch_config (deposed d98078d2) - *terraform.NodePlanDeposedResourceInstanceObject
aws_security_group.private_subnesecurity - *terraform.NodeValidatableResource
aws_security_group.security - *terraform.NodeValidatableResource
aws_subnet.private_subnet1 - *terraform.NodeValidatableResource
aws_subnet.private_subnet2 - *terraform.NodeValidatableResource
aws_subnet.public_subnet1 - *terraform.NodeValidatableResource
aws_subnet.public_subnet2 - *terraform.NodeValidatableResource
aws_vpc.vpc_environment - *terraform.NodeValidatableResource
------
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.OrphanOutputTransformer
2019/07/07 15:25:12 [TRACE] Completed graph transform *terraform.OrphanOutputTransformer (no changes)
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.AttachResourceConfigTransformer
2019/07/07 15:25:12 [TRACE] AttachResourceConfigTransformer: attaching to "aws_subnet.private_subnet1" (*terraform.NodeValidatableResource) config from resources.tf:14,1-40
2019/07/07 15:25:12 [TRACE] AttachResourceConfigTransformer: attaching to "aws_subnet.private_subnet2" (*terraform.NodeValidatableResource) config from resources.tf:27,1-40
2019/07/07 15:25:12 [TRACE] AttachResourceConfigTransformer: attaching to "aws_security_group.private_subnesecurity" (*terraform.NodeValidatableResource) config from resources.tf:33,1-54
2019/07/07 15:25:12 [TRACE] AttachResourceConfigTransformer: attaching to "aws_subnet.public_subnet1" (*terraform.NodeValidatableResource) config from resources.tf:7,1-39
2019/07/07 15:25:12 [TRACE] AttachResourceConfigTransformer: attaching to "aws_subnet.public_subnet2" (*terraform.NodeValidatableResource) config from resources.tf:20,1-39
2019/07/07 15:25:12 [TRACE] AttachResourceConfigTransformer: attaching to "aws_security_group.security" (*terraform.NodeValidatableResource) config from resources.tf:62,1-41
2019/07/07 15:25:12 [TRACE] AttachResourceConfigTransformer: attaching to "aws_vpc.vpc_environment" (*terraform.NodeValidatableResource) config from resources.tf:1,1-37
2019/07/07 15:25:12 [TRACE] Completed graph transform *terraform.AttachResourceConfigTransformer (no changes)
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.AttachStateTransformer
2019/07/07 15:25:12 [TRACE] Completed graph transform *terraform.AttachStateTransformer (no changes)
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.RootVariableTransformer
2019/07/07 15:25:12 [TRACE] Completed graph transform *terraform.RootVariableTransformer with new graph:
aws_launch_configuration.autoscale_launch_config - *terraform.NodeAbstractResourceInstance
aws_launch_configuration.autoscale_launch_config (deposed d98078d2) - *terraform.NodePlanDeposedResourceInstanceObject
aws_security_group.private_subnesecurity - *terraform.NodeValidatableResource
aws_security_group.security - *terraform.NodeValidatableResource
aws_subnet.private_subnet1 - *terraform.NodeValidatableResource
aws_subnet.private_subnet2 - *terraform.NodeValidatableResource
aws_subnet.public_subnet1 - *terraform.NodeValidatableResource
aws_subnet.public_subnet2 - *terraform.NodeValidatableResource
aws_vpc.vpc_environment - *terraform.NodeValidatableResource
var.ami_key_pair_name - *terraform.NodeRootVariable
------
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.MissingProvisionerTransformer
2019/07/07 15:25:12 [TRACE] Completed graph transform *terraform.MissingProvisionerTransformer (no changes)
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.ProvisionerTransformer
2019/07/07 15:25:12 [TRACE] Completed graph transform *terraform.ProvisionerTransformer (no changes)
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.ModuleVariableTransformer
2019/07/07 15:25:12 [TRACE] Completed graph transform *terraform.ModuleVariableTransformer (no changes)
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.graphTransformerMulti
2019/07/07 15:25:12 [TRACE] (graphTransformerMulti) Executing graph transform *terraform.ProviderConfigTransformer
2019/07/07 15:25:12 [TRACE] ProviderConfigTransformer: attaching to "provider.aws" provider configuration from connection.tf:1,1-15
2019/07/07 15:25:12 [TRACE] (graphTransformerMulti) Completed graph transform *terraform.ProviderConfigTransformer with new graph:
aws_launch_configuration.autoscale_launch_config - *terraform.NodeAbstractResourceInstance
aws_launch_configuration.autoscale_launch_config (deposed d98078d2) - *terraform.NodePlanDeposedResourceInstanceObject
aws_security_group.private_subnesecurity - *terraform.NodeValidatableResource
aws_security_group.security - *terraform.NodeValidatableResource
aws_subnet.private_subnet1 - *terraform.NodeValidatableResource
aws_subnet.private_subnet2 - *terraform.NodeValidatableResource
aws_subnet.public_subnet1 - *terraform.NodeValidatableResource
aws_subnet.public_subnet2 - *terraform.NodeValidatableResource
aws_vpc.vpc_environment - *terraform.NodeValidatableResource
provider.aws - *terraform.NodeApplyableProvider
var.ami_key_pair_name - *terraform.NodeRootVariable
------
2019/07/07 15:25:12 [TRACE] (graphTransformerMulti) Executing graph transform *terraform.MissingProviderTransformer
2019/07/07 15:25:12 [TRACE] (graphTransformerMulti) Completed graph transform *terraform.MissingProviderTransformer (no changes)
2019/07/07 15:25:12 [TRACE] (graphTransformerMulti) Executing graph transform *terraform.ProviderTransformer
2019/07/07 15:25:12 [TRACE] ProviderTransformer: aws_subnet.public_subnet1 is provided by provider.aws or inherited equivalent
2019/07/07 15:25:12 [TRACE] ProviderTransformer: aws_subnet.private_subnet1 is provided by provider.aws or inherited equivalent
2019/07/07 15:25:12 [TRACE] ProviderTransformer: aws_subnet.private_subnet2 is provided by provider.aws or inherited equivalent
2019/07/07 15:25:12 [TRACE] ProviderTransformer: aws_security_group.private_subnesecurity is provided by provider.aws or inherited equivalent
2019/07/07 15:25:12 [TRACE] ProviderTransformer: aws_launch_configuration.autoscale_launch_config is provided by provider.aws exactly
2019/07/07 15:25:12 [TRACE] ProviderTransformer: aws_launch_configuration.autoscale_launch_config (deposed d98078d2) is provided by provider.aws exactly
2019/07/07 15:25:12 [TRACE] ProviderTransformer: aws_vpc.vpc_environment is provided by provider.aws or inherited equivalent
2019/07/07 15:25:12 [TRACE] ProviderTransformer: aws_subnet.public_subnet2 is provided by provider.aws or inherited equivalent
2019/07/07 15:25:12 [TRACE] ProviderTransformer: aws_security_group.security is provided by provider.aws or inherited equivalent
2019/07/07 15:25:12 [TRACE] ProviderTransformer: exact match for provider.aws serving aws_subnet.public_subnet2
2019/07/07 15:25:12 [DEBUG] ProviderTransformer: "aws_subnet.public_subnet2" (*terraform.NodeValidatableResource) needs provider.aws
2019/07/07 15:25:12 [TRACE] ProviderTransformer: exact match for provider.aws serving aws_subnet.public_subnet1
2019/07/07 15:25:12 [DEBUG] ProviderTransformer: "aws_subnet.public_subnet1" (*terraform.NodeValidatableResource) needs provider.aws
2019/07/07 15:25:12 [TRACE] ProviderTransformer: exact match for provider.aws serving aws_subnet.private_subnet1
2019/07/07 15:25:12 [DEBUG] ProviderTransformer: "aws_subnet.private_subnet1" (*terraform.NodeValidatableResource) needs provider.aws
2019/07/07 15:25:12 [TRACE] ProviderTransformer: exact match for provider.aws serving aws_subnet.private_subnet2
2019/07/07 15:25:12 [DEBUG] ProviderTransformer: "aws_subnet.private_subnet2" (*terraform.NodeValidatableResource) needs provider.aws
2019/07/07 15:25:12 [TRACE] ProviderTransformer: exact match for provider.aws serving aws_security_group.private_subnesecurity
2019/07/07 15:25:12 [DEBUG] ProviderTransformer: "aws_security_group.private_subnesecurity" (*terraform.NodeValidatableResource) needs provider.aws
2019/07/07 15:25:12 [TRACE] ProviderTransformer: exact match for provider.aws serving aws_launch_configuration.autoscale_launch_config
2019/07/07 15:25:12 [DEBUG] ProviderTransformer: "aws_launch_configuration.autoscale_launch_config" (*terraform.NodeAbstractResourceInstance) needs provider.aws
2019/07/07 15:25:12 [TRACE] ProviderTransformer: exact match for provider.aws serving aws_launch_configuration.autoscale_launch_config (deposed d98078d2)
2019/07/07 15:25:12 [DEBUG] ProviderTransformer: "aws_launch_configuration.autoscale_launch_config (deposed d98078d2)" (*terraform.NodePlanDeposedResourceInstanceObject) needs provider.aws
2019/07/07 15:25:12 [TRACE] ProviderTransformer: exact match for provider.aws serving aws_vpc.vpc_environment
2019/07/07 15:25:12 [DEBUG] ProviderTransformer: "aws_vpc.vpc_environment" (*terraform.NodeValidatableResource) needs provider.aws
2019/07/07 15:25:12 [TRACE] ProviderTransformer: exact match for provider.aws serving aws_security_group.security
2019/07/07 15:25:12 [DEBUG] ProviderTransformer: "aws_security_group.security" (*terraform.NodeValidatableResource) needs provider.aws
2019/07/07 15:25:12 [TRACE] (graphTransformerMulti) Completed graph transform *terraform.ProviderTransformer with new graph:
aws_launch_configuration.autoscale_launch_config - *terraform.NodeAbstractResourceInstance
  provider.aws - *terraform.NodeApplyableProvider
aws_launch_configuration.autoscale_launch_config (deposed d98078d2) - *terraform.NodePlanDeposedResourceInstanceObject
  provider.aws - *terraform.NodeApplyableProvider
aws_security_group.private_subnesecurity - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
aws_security_group.security - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
aws_subnet.private_subnet1 - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
aws_subnet.private_subnet2 - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
aws_subnet.public_subnet1 - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
aws_subnet.public_subnet2 - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
aws_vpc.vpc_environment - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
provider.aws - *terraform.NodeApplyableProvider
var.ami_key_pair_name - *terraform.NodeRootVariable
------
2019/07/07 15:25:12 [TRACE] (graphTransformerMulti) Executing graph transform *terraform.PruneProviderTransformer
2019/07/07 15:25:12 [TRACE] (graphTransformerMulti) Completed graph transform *terraform.PruneProviderTransformer (no changes)
2019/07/07 15:25:12 [TRACE] (graphTransformerMulti) Executing graph transform *terraform.ParentProviderTransformer
2019/07/07 15:25:12 [TRACE] (graphTransformerMulti) Completed graph transform *terraform.ParentProviderTransformer (no changes)
2019/07/07 15:25:12 [TRACE] Completed graph transform *terraform.graphTransformerMulti with new graph:
aws_launch_configuration.autoscale_launch_config - *terraform.NodeAbstractResourceInstance
  provider.aws - *terraform.NodeApplyableProvider
aws_launch_configuration.autoscale_launch_config (deposed d98078d2) - *terraform.NodePlanDeposedResourceInstanceObject
  provider.aws - *terraform.NodeApplyableProvider
aws_security_group.private_subnesecurity - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
aws_security_group.security - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
aws_subnet.private_subnet1 - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
aws_subnet.private_subnet2 - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
aws_subnet.public_subnet1 - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
aws_subnet.public_subnet2 - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
aws_vpc.vpc_environment - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
provider.aws - *terraform.NodeApplyableProvider
var.ami_key_pair_name - *terraform.NodeRootVariable
------
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.RemovedModuleTransformer
2019/07/07 15:25:12 [TRACE] Completed graph transform *terraform.RemovedModuleTransformer (no changes)
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.AttachSchemaTransformer
2019/07/07 15:25:12 [TRACE] AttachSchemaTransformer: attaching resource schema to aws_subnet.public_subnet2
2019/07/07 15:25:12 [TRACE] AttachSchemaTransformer: attaching resource schema to aws_security_group.security
2019/07/07 15:25:12 [TRACE] AttachSchemaTransformer: attaching resource schema to aws_vpc.vpc_environment
2019/07/07 15:25:12 [TRACE] AttachSchemaTransformer: attaching resource schema to aws_subnet.private_subnet1
2019/07/07 15:25:12 [TRACE] AttachSchemaTransformer: attaching resource schema to aws_subnet.private_subnet2
2019/07/07 15:25:12 [TRACE] AttachSchemaTransformer: attaching resource schema to aws_security_group.private_subnesecurity
2019/07/07 15:25:12 [TRACE] AttachSchemaTransformer: attaching resource schema to aws_launch_configuration.autoscale_launch_config
2019/07/07 15:25:12 [TRACE] AttachSchemaTransformer: attaching resource schema to aws_launch_configuration.autoscale_launch_config (deposed d98078d2)
2019/07/07 15:25:12 [TRACE] AttachSchemaTransformer: attaching provider config schema to provider.aws
2019/07/07 15:25:12 [TRACE] AttachSchemaTransformer: attaching resource schema to aws_subnet.public_subnet1
2019/07/07 15:25:12 [TRACE] Completed graph transform *terraform.AttachSchemaTransformer (no changes)
2019/07/07 15:25:12 [TRACE] Executing graph transform *terraform.ReferenceTransformer
2019/07/07 15:25:12 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2019/07/07 15:25:12 [TRACE] statemgr.Filesystem: unlocked by closing terraform.tfstate
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0xece5a5]

goroutine 4 [running]:
github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).References(0xc0007948f0, 0x1b58f40, 0xc0007948f0, 0x6635790)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_abstract.go:241 +0xb5
github.com/hashicorp/terraform/terraform.NewReferenceMap(0xc00050ae70, 0xb, 0xb, 0xb)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/transform_reference.go:402 +0x251
github.com/hashicorp/terraform/terraform.(*ReferenceTransformer).Transform(0x2f969a8, 0xc0000b0960, 0x14, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/transform_reference.go:73 +0x78
github.com/hashicorp/terraform/terraform.(*BasicGraphBuilder).Build(0xc0007cf8e0, 0x0, 0x0, 0x0, 0x2f78ba0, 0xc0007cf910, 0x4fb747, 0xc0000b0000)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/graph_builder.go:50 +0x47e
github.com/hashicorp/terraform/terraform.(*PlanGraphBuilder).Build(0xc0003f0310, 0x0, 0x0, 0x0, 0x1, 0x0, 0x1923920, 0xc0003e9da0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/graph_builder_plan.go:65 +0xc3
github.com/hashicorp/terraform/terraform.(*Context).Graph(0xc000460000, 0x6, 0xc0007cf966, 0xc0007cfa00, 0x1, 0x1, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/context.go:292 +0x1bf
github.com/hashicorp/terraform/terraform.(*Context).Validate(0xc000460000, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/context.go:670 +0xfa
github.com/hashicorp/terraform/backend/local.(*Local).context(0xc00045dba0, 0xc00024e2a0, 0x1, 0x1, 0x2, 0xc0000048c0, 0x1, 0x2, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_local.go:120 +0x97b
github.com/hashicorp/terraform/backend/local.(*Local).opPlan(0xc00045dba0, 0x201dfa0, 0xc00005e700, 0x201dfa0, 0xc00005e740, 0xc00024e2a0, 0xc00005e6c0)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:67 +0x2aa
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc0003345c0, 0xc0003345d0, 0xc0003345e0, 0xc00024e2a0, 0xc00045dba0, 0xc00005e6c0, 0xc0003345b0, 0x201dfa0, 0xc00005e700, 0x201dfa0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:356 +0x13c
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:340 +0x372
```

**Comment by jbardin** [comment]
This was fixed in the 0.12.1 release. Please upgrade to the current release (0.12.3 at the moment) and let us know if you still have any problems.
