### ISSUE TITLE
Terraform 0.12 plan crashes on value "null\n"

### ISSUE THREAD

**Issue by wmgroot** [hashicorp/terraform#22111]
### Terraform Version
```
$ terraform --version
Terraform v0.12.4
+ provider.local v1.3.0
```

### Terraform Configuration Files
```hcl
# terraform.tf
variable "my_null_var" {
  type = string
}

resource "local_file" "my_file" {
  content  = var.my_null_var
  filename = "test.txt"
}
```
```hcl
# test.tfvars
my_null_var = <<EOL
null
EOL
```

### Crash Output
```
$ terraform plan -var-file=test.tfvars
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

panic: value is null

goroutine 7 [running]:
github.com/zclconf/go-cty/cty.Value.LengthInt(0x2e066e0, 0x3f17938, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.0.1-0.20190708163926-19588f92a98f/cty/value_ops.go:874 +0x253
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeValue(0xc0005f98a8, 0x2e066a0, 0xc0000c8380, 0x25dcf60, 0xc00055a450, 0x2b, 0x8)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/format/diff.go:509 +0x13a8
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeAttrDiff(0xc0005f98a8, 0xc000444418, 0x7, 0xc000438a20, 0x2e066a0, 0xc0000c8380, 0x0, 0x0, 0x2e066a0, 0xc0000c8380, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/format/diff.go:255 +0x370
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeBlockBodyDiff(0xc0005f98a8, 0xc000378150, 0x2e067a0, 0xc0004400a0, 0x0, 0x0, 0x2e067a0, 0xc0004400b0, 0x267f540, 0xc00003ab70, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/format/diff.go:196 +0x5d5
github.com/hashicorp/terraform/command/format.ResourceChange(0xc0001d4200, 0xc000438e00, 0xc000378150, 0xc00055c110, 0xc00044f198, 0x8e)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/format/diff.go:140 +0x5ff
github.com/hashicorp/terraform/backend/local.(*Local).renderPlan(0xc000356c30, 0xc0001ec000, 0xc0000b8748, 0xc00055c6c0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:270 +0x6ad
github.com/hashicorp/terraform/backend/local.(*Local).opPlan(0xc000356c30, 0x2e04c60, 0xc00027a6c0, 0x2e04c60, 0xc00027a700, 0xc00036a000, 0xc00027a680)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:165 +0xb9c
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc00055c4d0, 0xc00055c4e0, 0xc00055c4f0, 0xc00036a000, 0xc000356c30, 0xc00027a680, 0xc00055c4c0, 0x2e04c60, 0xc00027a6c0, 0x2e04c60, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend.go:356 +0x135
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend.go:340 +0x36b



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Expected Behavior
Terraform does not crash when it evaluates a "null\n" value in the formatter.

### Actual Behavior
Here is the relevant source code (command/format/diff.go:~500):
```go
// check for the special case of "null", which decodes to nil,
// and just allow it to be printed out directly
if err == nil && !ty.IsPrimitiveType() && val.AsString() != "null" {
	jv, err := ctyjson.Unmarshal(src, ty)

	if err == nil {
		p.buf.WriteString("jsonencode(")

		if jv.LengthInt() == 0 {  // this line crashes
			p.writeValue(jv, action, 0)
``` 
`jv.LengthInt()` uses `IsNull()` to determine if the value is null, and panics if it is. Currently, `IsNull()` returns true when called on the value "null\n", I assume because it strips any leading or trailing whitespace.

Changing `val.AsString() != "null"` to `val.IsNull()` might be the right fix, but I'm unsure of the implications.

### Steps to Reproduce
`terraform plan -var-file=test.tfvars`

**Comment by danieldreier** [comment]
@wmgroot I really appreciate you reporting this, and I apologize for how long it's taken to get a response. I just successfully reproduced it on terraform 0.12.4, like you did. When I tried to reproduce on 0.12.26 and 0.13.0 beta 1, this crash didn't happen, so I'm going to assume it has been fixed and close it. If it's still happening for you, please let me know at ddreier@hashicorp.com and I'm happy to re-open this and investigate further.

**Comment by wmgroot** [comment]
No worries, glad to hear it's no longer an issue. Took a while to hunt it down and figure out what had happened. Cheers!
