### ISSUE TITLE
TERRAFORM CRASH

### ISSUE THREAD

**Issue by msmrnv1** [hashicorp/terraform#22244]
Terrraform template crashes when submitting multiple schema elements for Okta configuration

Terraform v0.12.5
+ provider.okta v3.0.10

E.g.

resource "okta_user_schema" "schema_uuid" {
  index       = "UserUuid"
  title       =  User UUID"
  type        = "string"
  description = "The  internal user identifier"
  required    = false
  min_length  = 1
  max_length  = 50
  permissions = "READ_ONLY"
  }

resource "okta_user_schema" "schema_google" {
  index       = "googleLinkingId"
  title       = "External Google Identifier"
  type        = "string"
  description = "External SSO Identifier for schema_google"
  required    = false
  min_length  = 1
  max_length  = 50
  permissions = "READ_ONLY"
}

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: invalid memory address or nil pointer dereference
2019-07-29T16:53:30.448-0400 [DEBUG] plugin.terraform-provider-okta_v3.0.10_x5: [signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x1a9b581]
2019-07-29T16:53:30.448-0400 [DEBUG] plugin.terraform-provider-okta_v3.0.10_x5:
2019-07-29T16:53:30.448-0400 [DEBUG] plugin.terraform-provider-okta_v3.0.10_x5: goroutine 43 [running]:
2019-07-29T16:53:30.448-0400 [DEBUG] plugin.terraform-provider-okta_v3.0.10_x5: github.com/articulate/terraform-provider-okta/okta.resourceUserSchemaRead(0xc000180700, 0x1bcac60, 0xc0002d6690, 0x1b6ed60, 0xc0005e93b0)
2019-07-29T16:53:30.448-0400 [DEBUG] plugin.terraform-provider-okta_v3.0.10_x5: 	/Users/CTCT/terraform-provider-okta/okta/resource_user_schema.go:145 +0x101
2019-07-29T16:53:30.448-0400 [DEBUG] plugin.terraform-provider-okta_v3.0.10_x5: github.com/articulate/terraform-provider-okta/okta.resourceUserSchemaCreate(0xc000180700, 0x1bcac60, 0xc0002d6690, 0x2, 0x2858a40)
2019-07-29T16:53:30.448-0400 [DEBUG] plugin.terraform-provider-okta_v3.0.10_x5: 	/Users/CTCT/terraform-provider-okta/okta/resource_user_schema.go:121 +0xd1
2019-07-29T16:53:30.448-0400 [DEBUG] plugin.terraform-provider-okta_v3.0.10_x5: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0004c8380, 0xc0002000a0, 0xc000528200, 0x1bcac60, 0xc0002d6690, 0xc000659201, 0xc00041ea58, 0x1bc2500)
2019-07-29T16:53:30.448-0400 [DEBUG] plugin.terraform-provider-okta_v3.0.10_x5: 	/Users/go/pkg/mod/github.com/hashicorp/terraform@v0.12.0/helper/schema/resource.go:286 +0x3b4
2019-07-29T16:53:30.448-0400 [DEBUG] plugin.terraform-provider-okta_v3.0.10_x5: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0004c9c00, 0xc0003eda58, 0xc0002000a0, 0xc000528200, 0xc0001af288, 0xc0005f6088, 0x1bc4540)
2019-07-29T16:53:30.448-0400 [DEBUG] plugin.terraform-provider-okta_v3.0.10_x5: 	/Users/go/pkg/mod/github.com/hashicorp/terraform@v0.12.0/helper/schema/provider.go:285 +0x18f
2019-07-29T16:53:30.449-0400 [DEBUG] plugin.terraform-provider-okta_v3.0.10_x5: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000010498, 0x1fbea80, 0xc000518000, 0xc00051a000, 0xc000010498, 0x32, 0xc00050fbd0)
2019-07-29T16:53:30.449-0400 [DEBUG] plugin.terraform-provider-okta_v3.0.10_x5: 	/Users/go/pkg/mod/github.com/hashicorp/terraform@v0.12.0/helper/plugin/grpc_provider.go:842 +0x894
2019-07-29T16:53:30.449-0400 [DEBUG] plugin.terraform-provider-okta_v3.0.10_x5: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1d01640, 0xc000010498, 0x1fbea80, 0xc000518000, 0xc000516000, 0x0, 0x1fbea80, 0xc000518000, 0xc000514000, 0x1c1)

**Comment by kmoe** [comment]
It looks like this is an issue with the Okta provider. Please try updating to the latest version of the provider, and file an issue in the Okta provider repo if the problem continues.
