### ISSUE TITLE
Crash aws_iam_role_policy_attachment with for_each toset

### ISSUE THREAD

**Issue by Ptic79** [hashicorp/terraform#22437]
### Terraform Version

```
Terraform v0.12.6
+ provider.aws v2.23.0
```

### Terraform Configuration Files

https://github.com/Ptic79/terraform_crash

### Crash Output

```
module.ECSTaskExecutionRole.data.aws_caller_identity.current: Refreshing state...
module.policy.data.aws_caller_identity.current: Refreshing state...
module.ECSTaskExecutionRole.data.aws_iam_policy_document.ecs-tasks-assume-role-policy: Refreshing state...
module.policy.data.aws_iam_policy_document.parameter-policy-document: Refreshing state...
panic: value is unknown

goroutine 184 [running]:
github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty.Value.AsString(...)
        /private/tmp/terraform-20190731-89888-r3s7an/terraform-0.12.6/src/github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/value_ops.go:1032
github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty.Value.AsValueMap(0x2e29520, 0xc000bbb060, 0x290a0e0, 0xc000698240, 0x2)
        /private/tmp/terraform-20190731-89888-r3s7an/terraform-0.12.6/src/github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/value_ops.go:1095 +0x34e
github.com/hashicorp/terraform/terraform.evaluateResourceForEachExpressionKnown(0x2e28360, 0xc0003a60f0, 0x2e59a00, 0xc000360000, 0x100, 0xc000998600, 0x51, 0x0, 0xc000998600)
        /private/tmp/terraform-20190731-89888-r3s7an/terraform-0.12.6/src/github.com/hashicorp/terraform/terraform/eval_for_each.go:84 +0x5bd
github.com/hashicorp/terraform/terraform.evaluateResourceForEachExpression(0x2e28360, 0xc0003a60f0, 0x2e59a00, 0xc000360000, 0x1, 0x1, 0x0, 0x0)
        /private/tmp/terraform-20190731-89888-r3s7an/terraform-0.12.6/src/github.com/hashicorp/terraform/terraform/eval_for_each.go:17 +0x5c
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResource).DynamicExpand(0xc00000eab8, 0x2e59a00, 0xc000360000, 0x0, 0x0, 0x0)
        /private/tmp/terraform-20190731-89888-r3s7an/terraform-0.12.6/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:42 +0x280
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x28e3560, 0xc00000eab8, 0x0, 0x0, 0x0)
        /private/tmp/terraform-20190731-89888-r3s7an/terraform-0.12.6/src/github.com/hashicorp/terraform/terraform/graph.go:103 +0x8b1
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0001d0c80, 0x28e3560, 0xc00000eab8, 0xc0001b8900)
        /private/tmp/terraform-20190731-89888-r3s7an/terraform-0.12.6/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x353
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /private/tmp/terraform-20190731-89888-r3s7an/terraform-0.12.6/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa9b

```

### Steps to Reproduce

1. `git clone git@github.com:Ptic79/terraform_crash.git`
2. `cd terraform_crash`
3. `terraform init`
4. `terraform refresh`
5. `terraform refresh` - crashing

**Comment by Ptic79** [comment]
I simplify it. This code crashing:
```
resource "aws_iam_role_policy_attachment" "test-attach" {
  for_each = toset([
    aws_iam_policy.policy.arn,
    "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy",
  ])
  role       = "${aws_iam_role.role.name}"
  policy_arn = each.value
}
```
This code working:
```
resource "aws_iam_role_policy_attachment" "test-attach" {
  for_each = toset([
    "arn:aws:iam::aws:policy/test",
    "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy",
  ])
  role       = "${aws_iam_role.role.name}"
  policy_arn = each.value
}
```
And this variant working:
```
resource "aws_iam_role_policy_attachment" "test-attach" {
  role       = "${aws_iam_role.role.name}"
  policy_arn = "${aws_iam_policy.policy.arn}"
}
resource "aws_iam_role_policy_attachment" "test-attach2" {
  role       = "${aws_iam_role.role.name}"
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}
```

**Comment by teamterraform** [comment]
Hi @Ptic79!

It looks like this is caused by Terraform not correctly handling the fact that one of the elements of your set isn't known at plan time. That ought to result in an error stating that the values in the set must all be known (otherwise Terraform can't tell what the instance key ought to be) but it certainly shouldn't crash.

In the mean time I would suggest the following as a workaround, which more directly reflects how Terraform interprets a set as a `for_each` argument:

```hcl
  for_each = {
    for k in [
      aws_iam_policy.policy.arn,
      "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
    ] : k => k
  }
```

This will turn the set of strings into a map whose keys and values are the same, which is essentially what Terraform does internally in order to process a set value. This will likely still result in an error -- the `for_each` value still isn't fully known at plan time -- but it should at least not be a crash, and the error message should advise that you can work around this by doing a one-off apply with just the IAM policy to ensure that the policy ARN is known:

```
terraform apply -target=aws_iam_policy.policy
```

After that succeeds, you can then run another `terraform apply` with no arguments as normal and it should work because the ARN will now be known. This is the `for_each` equivalent of the rule that the `count` value must be known at plan time, so that Terraform can know how many instances it needs to create and what key should be used to identify each of them.

**Comment by pselle** [comment]
Thank you so much for providing a replication repo! This was very valuable for testing your case on the latest Terraform. When I ran `terraform apply`, I got:

```
$ terraform apply
module.ECSTaskExecutionRole.data.aws_caller_identity.current: Refreshing state...
module.policy.data.aws_caller_identity.current: Refreshing state...
module.ECSTaskExecutionRole.data.aws_iam_policy_document.ecs-tasks-assume-role-policy: Refreshing state...
module.policy.data.aws_iam_policy_document.parameter-policy-document: Refreshing state...

Error: Invalid for_each argument

  on modules/role/main.tf line 25, in resource "aws_iam_role_policy_attachment" "role-policy_attachment":
  25:   for_each   = toset(var.policy_attachment)

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

```

Which is in line with what Team Terraform found _should_ be happening, rather than the crash. This was tested on Terraform 0.12.12.
