### ISSUE TITLE
Crash when running `tf show`

### ISSUE THREAD

**Issue by JeffHemmen** [hashicorp/terraform#22477]
### Terraform Version

```
0.12.5
```

### Terraform Configuration Files

```hcl
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "<redacted>"

    workspaces {
      name = "tst-jeff"
    }
  }
}

```

### Debug Output

```
➜  tst-jeff git:(new_env_tst-jeff) ✗  tf show
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1bdcf9e]

goroutine 1 [running]:
github.com/hashicorp/terraform/command/format.formatStateModule(0xc000d88840, 0xc000f0a8c0, 0x0, 0x0, 0x0, 0x0, 0xc000d88270, 0xc000514ef0)
	/private/tmp/terraform-20190718-80638-1i8gj64/terraform-0.12.5/src/github.com/hashicorp/terraform/command/format/state.go:104 +0x2ee
github.com/hashicorp/terraform/command/format.State(0xc000917b28, 0xc000f0a8c0, 0x2998fdd)
	/private/tmp/terraform-20190718-80638-1i8gj64/terraform-0.12.5/src/github.com/hashicorp/terraform/command/format/state.go:55 +0x1c7
github.com/hashicorp/terraform/command.(*ShowCommand).Run(0xc00008d380, 0xc00000c050, 0x0, 0x0, 0xc00016a070)
	/private/tmp/terraform-20190718-80638-1i8gj64/terraform-0.12.5/src/github.com/hashicorp/terraform/command/show.go:172 +0xbd3
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc000378000, 0xc000378000, 0xc000547d90, 0x1)
	/private/tmp/terraform-20190718-80638-1i8gj64/terraform-0.12.5/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/private/tmp/terraform-20190718-80638-1i8gj64/terraform-0.12.5/src/github.com/hashicorp/terraform/main.go:223 +0xaff
main.realMain(0x0)
	/private/tmp/terraform-20190718-80638-1i8gj64/terraform-0.12.5/src/github.com/hashicorp/terraform/main.go:100 +0xb4
main.main()
	/private/tmp/terraform-20190718-80638-1i8gj64/terraform-0.12.5/src/github.com/hashicorp/terraform/main.go:36 +0x3b



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

### Crash Output

```
2019/08/15 11:37:53 [INFO] Terraform version: 0.12.5  
2019/08/15 11:37:53 [INFO] Go runtime version: go1.12.7
2019/08/15 11:37:53 [INFO] CLI args: []string{"/usr/local/bin/terraform", "show"}
2019/08/15 11:37:53 [DEBUG] Attempting to open CLI config file: /Users/jeffhemmen/.terraformrc
2019/08/15 11:37:53 Loading CLI configuration from /Users/jeffhemmen/.terraformrc
2019/08/15 11:37:53 [INFO] CLI command args: []string{"show"}
2019/08/15 11:37:53 [TRACE] Meta.Backend: BackendOpts.Config not set, so using settings loaded from backend.tf:2,3-19
2019/08/15 11:37:53 [TRACE] Meta.Backend: built configuration for "remote" backend with hash value 685890593
2019/08/15 11:37:53 [TRACE] Preserving existing state lineage "1a72d682-003f-6921-063b-1d61041eaaa5"
2019/08/15 11:37:53 [TRACE] Preserving existing state lineage "1a72d682-003f-6921-063b-1d61041eaaa5"
2019/08/15 11:37:53 [TRACE] Meta.Backend: working directory was previously initialized for "remote" backend
2019/08/15 11:37:53 [TRACE] Meta.Backend: using already-initialized, unchanged "remote" backend configuration
2019/08/15 11:37:53 [DEBUG] Service discovery for app.terraform.io at https://app.terraform.io/.well-known/terraform.json
2019/08/15 11:37:54 [DEBUG] Retrieve version constraints for service tfe.v2.1 and product terraform
2019/08/15 11:37:55 [TRACE] Meta.Backend: instantiated backend of type *remote.Remote
2019/08/15 11:37:55 [DEBUG] checking for provider in "."
2019/08/15 11:37:55 [DEBUG] checking for provider in "/usr/local/bin"
2019/08/15 11:37:55 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2019/08/15 11:37:55 [DEBUG] found provider "terraform-provider-aws_v2.21.1_x4"
2019/08/15 11:37:55 [DEBUG] found provider "terraform-provider-local_v1.3.0_x4"
2019/08/15 11:37:55 [DEBUG] found provider "terraform-provider-null_v2.1.2_x4"
2019/08/15 11:37:55 [DEBUG] found valid plugin: "aws", "2.21.1", "/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-aws_v2.21.1_x4"
2019/08/15 11:37:55 [DEBUG] found valid plugin: "local", "1.3.0", "/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-local_v1.3.0_x4"
2019/08/15 11:37:55 [DEBUG] found valid plugin: "null", "2.1.2", "/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-null_v2.1.2_x4"
2019/08/15 11:37:55 [DEBUG] checking for provisioner in "."
2019/08/15 11:37:55 [DEBUG] checking for provisioner in "/usr/local/bin"
2019/08/15 11:37:55 [DEBUG] checking for provisioner in ".terraform/plugins/darwin_amd64"
2019/08/15 11:37:55 [TRACE] Meta.Backend: backend *remote.Remote supports operations
2019/08/15 11:37:55 [TRACE] backend/remote: requesting state manager for workspace "tst-jeff"
2019/08/15 11:37:55 [TRACE] backend/remote: requesting state lock for workspace "tst-jeff"
2019/08/15 11:37:55 [TRACE] backend/remote: reading remote state for workspace "tst-jeff"
2019/08/15 11:38:01 [TRACE] backend/remote: retrieving remote state snapshot for workspace "tst-jeff"
2019/08/15 11:38:01 [TRACE] backend/remote: loading configuration for the current working directory
2019/08/15 11:38:01 [TRACE] backend/remote: retrieving variables from workspace "tst-jeff"
2019/08/15 11:38:01 [TRACE] terraform.NewContext: starting
2019/08/15 11:38:01 [TRACE] terraform.NewContext: resolving provider version selections
2019/08/15 11:38:02 [TRACE] terraform.NewContext: loading provider schemas
2019/08/15 11:38:02 [TRACE] LoadSchemas: retrieving schema for provider type "aws"
2019-08-15T11:38:02.428+0100 [INFO]  plugin: configuring client automatic mTLS
2019-08-15T11:38:02.454+0100 [DEBUG] plugin: starting plugin: path=/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-aws_v2.21.1_x4 args=[/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-aws_v2.21.1_x4]
2019-08-15T11:38:02.474+0100 [DEBUG] plugin: plugin started: path=/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-aws_v2.21.1_x4 pid=6888
2019-08-15T11:38:02.474+0100 [DEBUG] plugin: waiting for RPC address: path=/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-aws_v2.21.1_x4
2019-08-15T11:38:02.499+0100 [INFO]  plugin.terraform-provider-aws_v2.21.1_x4: configuring server automatic mTLS: timestamp=2019-08-15T11:38:02.498+0100
2019-08-15T11:38:02.527+0100 [DEBUG] plugin: using plugin: version=5
2019-08-15T11:38:02.527+0100 [DEBUG] plugin.terraform-provider-aws_v2.21.1_x4: plugin address: address=/var/folders/f_/2n36bj650gq94w7ln6p48vmm0000gn/T/plugin590917079 network=unix timestamp=2019-08-15T11:38:02.527+0100
2019/08/15 11:38:02 [TRACE] GRPCProvider: GetSchema
2019/08/15 11:38:02 [TRACE] GRPCProvider: Close
2019-08-15T11:38:02.625+0100 [DEBUG] plugin: plugin process exited: path=/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-aws_v2.21.1_x4 pid=6888
2019-08-15T11:38:02.625+0100 [DEBUG] plugin: plugin exited
2019/08/15 11:38:02 [TRACE] LoadSchemas: retrieving schema for provider type "local"
2019-08-15T11:38:02.625+0100 [INFO]  plugin: configuring client automatic mTLS
2019-08-15T11:38:02.652+0100 [DEBUG] plugin: starting plugin: path=/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-local_v1.3.0_x4 args=[/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-local_v1.3.0_x4]
2019-08-15T11:38:02.656+0100 [DEBUG] plugin: plugin started: path=/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-local_v1.3.0_x4 pid=6889
2019-08-15T11:38:02.656+0100 [DEBUG] plugin: waiting for RPC address: path=/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-local_v1.3.0_x4
2019-08-15T11:38:02.665+0100 [INFO]  plugin.terraform-provider-local_v1.3.0_x4: configuring server automatic mTLS: timestamp=2019-08-15T11:38:02.665+0100
2019-08-15T11:38:02.691+0100 [DEBUG] plugin: using plugin: version=5
2019-08-15T11:38:02.691+0100 [DEBUG] plugin.terraform-provider-local_v1.3.0_x4: plugin address: network=unix address=/var/folders/f_/2n36bj650gq94w7ln6p48vmm0000gn/T/plugin868402604 timestamp=2019-08-15T11:38:02.691+0100
2019/08/15 11:38:02 [TRACE] GRPCProvider: GetSchema
2019/08/15 11:38:02 [TRACE] GRPCProvider: Close
2019-08-15T11:38:02.747+0100 [DEBUG] plugin: plugin process exited: path=/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-local_v1.3.0_x4 pid=6889
2019-08-15T11:38:02.747+0100 [DEBUG] plugin: plugin exited
2019/08/15 11:38:02 [TRACE] LoadSchemas: retrieving schema for provider type "null"
2019-08-15T11:38:02.747+0100 [INFO]  plugin: configuring client automatic mTLS
2019-08-15T11:38:02.771+0100 [DEBUG] plugin: starting plugin: path=/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-null_v2.1.2_x4 args=[/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-null_v2.1.2_x4]
2019-08-15T11:38:02.775+0100 [DEBUG] plugin: plugin started: path=/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-null_v2.1.2_x4 pid=6890
2019-08-15T11:38:02.775+0100 [DEBUG] plugin: waiting for RPC address: path=/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-null_v2.1.2_x4
2019-08-15T11:38:02.783+0100 [INFO]  plugin.terraform-provider-null_v2.1.2_x4: configuring server automatic mTLS: timestamp=2019-08-15T11:38:02.782+0100
2019-08-15T11:38:02.809+0100 [DEBUG] plugin: using plugin: version=5
2019-08-15T11:38:02.809+0100 [DEBUG] plugin.terraform-provider-null_v2.1.2_x4: plugin address: address=/var/folders/f_/2n36bj650gq94w7ln6p48vmm0000gn/T/plugin355928665 network=unix timestamp=2019-08-15T11:38:02.809+0100
2019/08/15 11:38:02 [TRACE] GRPCProvider: GetSchema
2019/08/15 11:38:02 [TRACE] GRPCProvider: Close
2019-08-15T11:38:02.863+0100 [DEBUG] plugin: plugin process exited: path=/Users/jeffhemmen/<redacted>/repos/terraform.config/gbr/tst-jeff/.terraform/plugins/darwin_amd64/terraform-provider-null_v2.1.2_x4 pid=6890
2019-08-15T11:38:02.863+0100 [DEBUG] plugin: plugin exited
2019/08/15 11:38:02 [TRACE] LoadSchemas: retrieving schema for provisioner "local-exec"
2019-08-15T11:38:02.863+0100 [DEBUG] plugin: starting plugin: path=/usr/local/bin/terraform args=[/usr/local/bin/terraform, internal-plugin, provisioner, local-exec]
2019-08-15T11:38:02.866+0100 [DEBUG] plugin: plugin started: path=/usr/local/bin/terraform pid=6891
2019-08-15T11:38:02.866+0100 [DEBUG] plugin: waiting for RPC address: path=/usr/local/bin/terraform
2019-08-15T11:38:02.879+0100 [DEBUG] plugin.terraform: 2019/08/15 11:38:02 [INFO] Terraform version: 0.12.5  
2019-08-15T11:38:02.879+0100 [DEBUG] plugin.terraform: 2019/08/15 11:38:02 [INFO] Go runtime version: go1.12.7
2019-08-15T11:38:02.879+0100 [DEBUG] plugin.terraform: 2019/08/15 11:38:02 [INFO] CLI args: []string{"/usr/local/bin/terraform", "internal-plugin", "provisioner", "local-exec"}
2019-08-15T11:38:02.879+0100 [DEBUG] plugin.terraform: 2019/08/15 11:38:02 [DEBUG] Attempting to open CLI config file: /Users/jeffhemmen/.terraformrc
2019-08-15T11:38:02.879+0100 [DEBUG] plugin.terraform: 2019/08/15 11:38:02 Loading CLI configuration from /Users/jeffhemmen/.terraformrc
2019-08-15T11:38:02.880+0100 [DEBUG] plugin.terraform: 2019/08/15 11:38:02 [INFO] CLI command args: []string{"internal-plugin", "provisioner", "local-exec"}
2019-08-15T11:38:02.880+0100 [DEBUG] plugin.terraform: local-exec-provisioner (internal) 2019/08/15 11:38:02 [INFO] Starting provisioner plugin local-exec
2019-08-15T11:38:02.881+0100 [DEBUG] plugin: using plugin: version=5
2019-08-15T11:38:02.881+0100 [DEBUG] plugin.terraform: plugin address: address=/var/folders/f_/2n36bj650gq94w7ln6p48vmm0000gn/T/plugin253028350 network=unix timestamp=2019-08-15T11:38:02.880+0100
2019-08-15T11:38:02.884+0100 [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform pid=6891
2019-08-15T11:38:02.884+0100 [DEBUG] plugin: plugin exited
2019/08/15 11:38:02 [TRACE] terraform.NewContext: complete
2019/08/15 11:38:02 [TRACE] backend/remote: finished building terraform.Context
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1bdcf9e]

goroutine 1 [running]:
github.com/hashicorp/terraform/command/format.formatStateModule(0xc000d88840, 0xc000f0a8c0, 0x0, 0x0, 0x0, 0x0, 0xc000d88270, 0xc000514ef0)
	/private/tmp/terraform-20190718-80638-1i8gj64/terraform-0.12.5/src/github.com/hashicorp/terraform/command/format/state.go:104 +0x2ee
github.com/hashicorp/terraform/command/format.State(0xc000917b28, 0xc000f0a8c0, 0x2998fdd)
	/private/tmp/terraform-20190718-80638-1i8gj64/terraform-0.12.5/src/github.com/hashicorp/terraform/command/format/state.go:55 +0x1c7
github.com/hashicorp/terraform/command.(*ShowCommand).Run(0xc00008d380, 0xc00000c050, 0x0, 0x0, 0xc00016a070)
	/private/tmp/terraform-20190718-80638-1i8gj64/terraform-0.12.5/src/github.com/hashicorp/terraform/command/show.go:172 +0xbd3
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc000378000, 0xc000378000, 0xc000547d90, 0x1)
	/private/tmp/terraform-20190718-80638-1i8gj64/terraform-0.12.5/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/private/tmp/terraform-20190718-80638-1i8gj64/terraform-0.12.5/src/github.com/hashicorp/terraform/main.go:223 +0xaff
main.realMain(0x0)
	/private/tmp/terraform-20190718-80638-1i8gj64/terraform-0.12.5/src/github.com/hashicorp/terraform/main.go:100 +0xb4
main.main()
	/private/tmp/terraform-20190718-80638-1i8gj64/terraform-0.12.5/src/github.com/hashicorp/terraform/main.go:36 +0x3b
```

### Expected Behavior

An empty state should have been shown.
`terraform show` should have exited cleanly.

### Actual Behavior

Crash.

### Steps to Reproduce

Unknown how I attained this corrupted state, but previous actions include:

* repeated failing `tf destroy`s (bug relating to non-existing NACLs / NACL rules)
* manually deleting AWS resources, inc. entire VPC
* `tf state rm module.VPC` (one of two modules, containing entire VPC)
* successful `tf destroy`

Then, crashes on `tf show`.

Subsequent `tf init`, `tf refresh` succeed but don't resolve the issue.  
`tf apply` + `yes` succeeds and fixes the issue.

### Additional Context

Local `terraform.tfstate`:
```{
  "version": 4,
  "terraform_version": "0.12.5",
  "serial": 1014,
  "lineage": "4a1f1cbe-346c-e0c4-8277-dda6759bcba6",
  "outputs": {},
  "resources": []
}
```

Remote state on app.terraform.io:
```{
  "version": 4,
  "terraform_version": "0.12.5",
  "serial": 18,
  "lineage": "d3ea910c-0b3b-f208-0840-250fce564091",
  "outputs": {},
  "resources": [
    {
      "module": "module.EKS",
      "mode": "managed",
      "type": "aws_eks_cluster",
      "name": "eks-cluster",
      "provider": "provider.aws",
      "instances": [
        {
          "deposed": "c8325af3",
          "schema_version": 0,
          "attributes": null,
          "private": "<redacted, base 64>",
          "depends_on": [
            "aws_iam_role.eks-cluster",
            "aws_iam_role_policy_attachment.eks-cluster-AmazonEKSClusterPolicy",
            "aws_iam_role_policy_attachment.eks-cluster-AmazonEKSServicePolicy",
            "aws_security_group.eks-cluster"
          ]
        }
      ]
    }
  ]
}
```

**Comment by danieldreier** [comment]
@JeffHemmen I want to apologize for how long it's taken to respond to this. I'm working through our backlog of crashes, and I just tried to reproduce this on 0.12.26 and 0.13.0 beta 1 and didn't get the same crash. Can you please try again on your side with a newer TF version, just to make sure I'm not missing a reproduction detail?
