### ISSUE TITLE
panic: Call to function "flatten" failed: panic in function implementation: can't use ElementIterator on null value

### ISSUE THREAD

**Issue by dekimsey** [hashicorp/terraform#22840]
### Terraform Version
```
terraform -v
Terraform v0.12.9
+ provider.aws v2.28.1
+ provider.azuread v0.3.1
+ provider.null v2.1.2
+ provider.random v2.1.2
+ provider.template v2.1.2
+ provider.tls v2.0.1
```

### Terraform Configuration Files

Our module is a thin wrapper over the ec2-instance one from the terraform registry. Here's our invocation of the module.

```hcl
module "this" {
  source  = "terraform-aws-modules/ec2-instance/aws"
  version = "~> 2.8.0"
  name    = local.cluster_name

  ami           = coalesce(var.app_ami, data.aws_ami.centos7.id)
  instance_type = var.app_instance_type

  subnet_ids = var.app_subnets

  monitoring     = "true"
  use_num_suffix = "true"

  vpc_security_group_ids = concat(
    var.app_security_groups,
    [aws_security_group.this-app.id],
)

  iam_instance_profile = aws_iam_instance_profile.this.id
  user_data            = coalesce(var.user_data, data.template_file.cloudinit.rendered)
  key_name             = var.prov_key_name

  instance_count = var.app_instance_count

  ebs_optimized    = substr(var.app_instance_type, 0, 1) != "t" ? true : false
  ebs_block_device = var.ebs_block_device

  root_block_device = [
    {
      # CentOS doesn't delete volumes by default, let's add that.
      volume_size           = var.root_volume_size
      volume_type           = "gp2"
      delete_on_termination = true
    },
  ]

  tags = {
    ansible_group = var.name
    namespace     = var.namespace
    terraform     = "true"
  }
}
```

### Crash Output

No crash.log file generated

### Expected Behavior
The aws_instance resource should have been successfully imported (or gracefully failed). 

### Actual Behavior
```
$ terraform import module.elasticsearch-high-node.module.this.aws_instance.this[0] i-04935a3a14146c837
module.elasticsearch-high-node.module.this.aws_instance.this[0]: Importing from ID "i-04935a3a14146c837"...
module.elasticsearch-high-node.module.this.aws_instance.this[0]: Import prepared!
  Prepared aws_instance for import
module.elasticsearch-high-node.module.this.aws_instance.this[0]: Refreshing state... [id=i-04935a3a14146c837]

Error: Error in function call

  on .terraform/modules/elasticsearch-high-master.this/terraform-aws-modules-terraform-aws-ec2-instance-9fe491f/outputs.tf line 14, in locals:
  14:   this_credit_specification         = flatten(aws_instance.this.*.credit_specification)
    |----------------
    | aws_instance.this is tuple with 3 elements

Call to function "flatten" failed: panic in function implementation: can't use
ElementIterator on null value
goroutine 7956 [running]:
runtime/debug.Stack(0xc004e65eb0, 0x25e08a0, 0x2d9a450)
        /opt/goenv/versions/1.12.9/src/runtime/debug/stack.go:24 +0x9d
github.com/zclconf/go-cty/cty/function.errorForPanic(...)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.0.1-0.20190708163926-19588f92a98f/cty/function/error.go:44
github.com/zclconf/go-cty/cty/function.Function.ReturnTypeForValues.func1(0xc004e663a8,
0xc004e663b8)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.0.1-0.20190708163926-19588f92a98f/cty/function/function.go:193
+0x79
panic(0x25e08a0, 0x2d9a450)
        /opt/goenv/versions/1.12.9/src/runtime/panic.go:522 +0x1b5
github.com/zclconf/go-cty/cty.Value.ElementIterator(0x2e0e7e0, 0xc005466420,
0x0, 0x0, 0x100be98, 0x30)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.0.1-0.20190708163926-19588f92a98f/cty/value_ops.go:922
+0xd5
github.com/hashicorp/terraform/lang/funcs.flattener(0x2e0e7e0, 0xc005466420,
0x0, 0x0, 0xc006f56ff0, 0x2e0e7e0, 0xc005466420, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/lang/funcs/collection.go:488
+0x8c
github.com/hashicorp/terraform/lang/funcs.flattener(0x2e0e8e0, 0xc002c20460,
0x25bcb40, 0xc002c204a0, 0x1, 0x3, 0xc002c204a0, 0xc004e661a8)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/lang/funcs/collection.go:495
+0x28f
github.com/hashicorp/terraform/lang/funcs.glob..func19(0xc002c20440, 0x1, 0x1,
0xc004e663b8, 0xc004e661f8, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/lang/funcs/collection.go:457
+0xa7
github.com/zclconf/go-cty/cty/function.Function.ReturnTypeForValues(0xc0004768a0,
0xc002c20440, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.0.1-0.20190708163926-19588f92a98f/cty/function/function.go:197
+0x282
github.com/zclconf/go-cty/cty/function.Function.Call(0xc0004768a0,
0xc002c20440, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.0.1-0.20190708163926-19588f92a98f/cty/function/function.go:204
+0x9d
github.com/hashicorp/hcl2/hcl/hclsyntax.(*FunctionCallExpr).Value(0xc000ec9a40,
0xc002712a00, 0x0, 0xc004e67700, 0x1, 0x1, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/hcl2@v0.0.0-20190821123243-0c888d1241f6/hcl/hclsyntax/expression.go:385
+0x10c8
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc004e34550, 0x2e0d520,
0xc000ec9a40, 0x2e0e7a0, 0x3f3e6a0, 0x0, 0x0, 0xc0067ff908, 0x1, 0x1, ...)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/lang/eval.go:95
+0x1b3
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateExpr(0xc0030cea90,
0x2e0d520, 0xc000ec9a40, 0x2e0e7a0, 0x3f3e6a0, 0x0, 0x0, 0x0, 0xc007be3080,
0x0, ...)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:279
+0x1e4
github.com/hashicorp/terraform/terraform.(*EvalLocal).Eval(0xc0024a42c0,
0x2e40020, 0xc0030cea90, 0x2, 0x2, 0x1b353dd, 0x26f2820)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_local.go:43
+0x73a
github.com/hashicorp/terraform/terraform.EvalRaw(0x2dcd080, 0xc0024a42c0,
0x2e40020, 0xc0030cea90, 0x2675140, 0x3df3767, 0x25e08a0, 0xc002bcadc0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57
+0x131
github.com/hashicorp/terraform/terraform.Eval(0x2dcd080, 0xc0024a42c0,
0x2e40020, 0xc0030cea90, 0xc0024a42c0, 0x2dcd080, 0xc0024a42c0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:35
+0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2803980,
0xc003afcd50, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph.go:90
+0xf40
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00306c180,
0x2803980, 0xc003afcd50, 0xc004422d40)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:392
+0x353
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:314
+0xa9b
.
```

### Steps to Reproduce

$ terraform import module.elasticsearch-high-node.module.this.aws_instance.this[0] i-04935a3a14146c837

### Additional Context

I'm in the midst of a 0.12 upgrade. All instances of this module trigger the exception during the import/state refresh. Manually commenting out this one case seems to address it. I'm guessing this is an error in the module too. But functions generating panic's seem odd

### References

https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/tree/v2.8.0

**Comment by teamterraform** [comment]
Hi @dekimsey! Sorry for this crash and thanks for reporting it.

Indeed, this should not be reported as a crash. It looks like this might be a situation where the function ought to report a _proper_ error though: some of the lists in the given list seem to be null, and thus cannot be flattened.

In order to avoid that problem (whether it's reported as a crash or as a proper error), you could try using a `for` expression to filter out the nulls, if skipping them is an appropriate result in your case:

```hcl
  this_credit_specification         = flatten([
    for cs in aws_instance.this.*.credit_specification : cs if cs != null
  ])
```

...though we understand that this problem is coming from a child module that you might not be able to edit directly yourself.

When we look into this bug we'll consider whether it would be safe and clear for `flatten` to consider a null list as being the same as an empty list, which might avoid the need for that explicit filter. We tend to be cautious about special implicit behavior like that because it can make Terraform's behavior feel unpredictable and surprising to those who aren't aware of the details, but the tradeoff might be worth it in this case if real-world resource types tend to be returning null lists rather than empty lists.

(This might instead be considered an SDK bug... if `credit_specification` is a block type, then our usual convention would be for it to never be null and always be a list. Terraform 0.11 didn't _have_ `null`, so we expected that forcing all block types to appear in expressions as non-null lists would be the most compatible with Terraform 0.11, but that's only true if the SDK preserves to that assumption. We'll investigate _that_ when we look into this, too.)

**Comment by dekimsey** [comment]
Thanks for the evaluation @teamterraform! I too felt like there may be more than one issue here. :) Sorry I couldn't provide a more streamlined test. It seems to only happen during an import. State refreshing worked fine.
