### ISSUE TITLE
Terraform crash after canceling run

### ISSUE THREAD

**Issue by geertn** [hashicorp/terraform#22988]
### Terraform Version
Terraform v0.12.9

### Crash Output
```
module.tf-azurerm-activitylog.azurerm_template_deployment.azure_activitylog: Still destroying... [id=/subscriptions/cc5b3222-fac1-4d55-904c-...urces/deployments/ctr-mgt-activity-arm, 20s elapsed]

Error: rpc error: code = Canceled desc = context canceled


panic: runtime error: invalid memory address or nil pointer dereference
2019-10-03T14:08:48.974+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x2fd58b2]
2019-10-03T14:08:48.974+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: 
2019-10-03T14:08:48.974+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: goroutine 138 [running]:
2019-10-03T14:08:48.974+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.templateDeploymentStateStatusCodeRefreshFunc.func1(0xc0011bdf50, 0xc0011bdeb0, 0x2, 0x1, 0x1, 0x0)
2019-10-03T14:08:48.974+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_template_deployment.go:308 +0x1f2
2019-10-03T14:08:48.974+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState.func1(0xc00121e480, 0xc0001d3030, 0xc000d34b00, 0xc00122ef00, 0xc000ad0a08, 0xc000ad0a00)
2019-10-03T14:08:48.974+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/resource/state.go:103 +0x292
2019-10-03T14:08:48.974+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: created by github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState
2019-10-03T14:08:48.974+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/resource/state.go:80 +0x1bf
2019-10-03T14:08:48.979+0200 [DEBUG] plugin: plugin process exited: path=/home/geertn/work-fl/castor/edc-private-instance-infrastructure/terraform/environments/mgt/global/.terraform/plugins/linux_amd64/terraform-provider-azurerm_v1.34.0_x4 pid=24764 error="exit status 2"
2019/10/03 14:08:48 [DEBUG] module.tf-azurerm-activitylog.azurerm_template_deployment.azure_activitylog: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2019/10/03 14:08:48 [TRACE] module.tf-azurerm-activitylog: eval: *terraform.EvalWriteState
2019/10/03 14:08:48 [TRACE] EvalWriteState: writing current state object for module.tf-azurerm-activitylog.azurerm_template_deployment.azure_activitylog
2019/10/03 14:08:48 [TRACE] module.tf-azurerm-activitylog: eval: *terraform.EvalApplyPost
2019/10/03 14:08:48 [WARN] Early exit triggered by hook: *terraform.stopHook
2019/10/03 14:08:48 [TRACE] module.tf-azurerm-activitylog: eval: *terraform.EvalApplyPost, early exit err: early exit
2019/10/03 14:08:48 [TRACE] module.tf-azurerm-activitylog: eval: *terraform.EvalSequence, early exit err: early exit
2019/10/03 14:08:48 [TRACE] module.tf-azurerm-activitylog: eval: *terraform.EvalOpFilter, early exit err: early exit
2019/10/03 14:08:48 [TRACE] [walkApply] Exiting eval tree: module.tf-azurerm-activitylog.azurerm_template_deployment.azure_activitylog (destroy)
2019/10/03 14:08:48 [TRACE] vertex "module.tf-azurerm-activitylog.azurerm_template_deployment.azure_activitylog (destroy)": visit complete
2019/10/03 14:08:48 [TRACE] dag/walk: visiting "module.tf-azurerm-activitylog.azurerm_log_analytics_workspace.activitylog_workspace (destroy)"
2019/10/03 14:08:48 [TRACE] vertex "module.tf-azurerm-activitylog.azurerm_log_analytics_workspace.activitylog_workspace (destroy)": starting visit (*terraform.NodeDestroyResourceInstance)
2019/10/03 14:08:48 [TRACE] vertex "module.tf-azurerm-activitylog.azurerm_log_analytics_workspace.activitylog_workspace (destroy)": evaluating
2019/10/03 14:08:48 [TRACE] [walkApply] Entering eval tree: module.tf-azurerm-activitylog.azurerm_log_analytics_workspace.activitylog_workspace (destroy)
2019/10/03 14:08:48 [TRACE] module.tf-azurerm-activitylog: eval: *terraform.EvalOpFilter
2019/10/03 14:08:48 [TRACE] module.tf-azurerm-activitylog: eval: *terraform.EvalSequence
2019/10/03 14:08:48 [TRACE] module.tf-azurerm-activitylog: eval: *terraform.EvalGetProvider
2019/10/03 14:08:48 [TRACE] module.tf-azurerm-activitylog: eval: *terraform.EvalReadDiff
2019/10/03 14:08:48 [TRACE] EvalReadDiff: Read DeleteThenCreate change from plan for module.tf-azurerm-activitylog.azurerm_log_analytics_workspace.activitylog_workspace
2019/10/03 14:08:48 [TRACE] module.tf-azurerm-activitylog: eval: *terraform.EvalReduceDiff
2019/10/03 14:08:48 [TRACE] EvalReduceDiff: azurerm_log_analytics_workspace.activitylog_workspace change simplified from DeleteThenCreate to Delete for destroy node
2019/10/03 14:08:48 [TRACE] module.tf-azurerm-activitylog: eval: *terraform.EvalIf
2019/10/03 14:08:48 [TRACE] module.tf-azurerm-activitylog: eval: terraform.EvalNoop
2019/10/03 14:08:48 [TRACE] module.tf-azurerm-activitylog: eval: *terraform.EvalReadState
2019/10/03 14:08:48 [TRACE] EvalReadState: reading state for module.tf-azurerm-activitylog.azurerm_log_analytics_workspace.activitylog_workspace
2019/10/03 14:08:48 [TRACE] UpgradeResourceState: schema version of module.tf-azurerm-activitylog.azurerm_log_analytics_workspace.activitylog_workspace is still 0; calling provider "azurerm" for any other minor fixups
2019/10/03 14:08:48 [TRACE] GRPCProvider: UpgradeResourceState
2019/10/03 14:08:48 [ERROR] module.tf-azurerm-activitylog: eval: *terraform.EvalReadState, err: rpc error: code = Canceled desc = context canceled
2019/10/03 14:08:48 [ERROR] module.tf-azurerm-activitylog: eval: *terraform.EvalSequence, err: rpc error: code = Canceled desc = context canceled
2019/10/03 14:08:48 [ERROR] module.tf-azurerm-activitylog: eval: *terraform.EvalOpFilter, err: rpc error: code = Canceled desc = context canceled
2019/10/03 14:08:48 [TRACE] [walkApply] Exiting eval tree: module.tf-azurerm-activitylog.azurerm_log_analytics_workspace.activitylog_workspace (destroy)
2019/10/03 14:08:48 [TRACE] vertex "module.tf-azurerm-activitylog.azurerm_log_analytics_workspace.activitylog_workspace (destroy)": visit complete
2019/10/03 14:08:48 [TRACE] dag/walk: upstream of "module.tf-azurerm-activitylog.azurerm_resource_group.activitylog_law (destroy)" errored, so skipping
2019/10/03 14:08:48 [TRACE] dag/walk: upstream of "module.tf-azurerm-activitylog.azurerm_resource_group.activitylog_law" errored, so skipping
2019/10/03 14:08:48 [TRACE] dag/walk: upstream of "module.tf-azurerm-activitylog.azurerm_log_analytics_workspace.activitylog_workspace" errored, so skipping
2019/10/03 14:08:48 [TRACE] dag/walk: upstream of "module.tf-azurerm-activitylog.azurerm_log_analytics_solution.activitylog" errored, so skipping
2019/10/03 14:08:48 [TRACE] dag/walk: upstream of "module.tf-azurerm-activitylog.azurerm_template_deployment.azure_activitylog" errored, so skipping
2019/10/03 14:08:48 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2019/10/03 14:08:48 [TRACE] dag/walk: upstream of "provider.azurerm (close)" errored, so skipping
2019/10/03 14:08:48 [TRACE] dag/walk: upstream of "root" errored, so skipping
2019/10/03 14:08:48 [WARN] terraform: stop complete
2019/10/03 14:08:48 [TRACE] backend/local: graceful stop has completed
2019-10-03T14:08:49.230+0200 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by geertn** [comment]
[crash.log](https://github.com/hashicorp/terraform/files/3685943/crash.log)

Attached crash.log
