### ISSUE TITLE
panic in jsonstate/state.go

### ISSUE THREAD

**Issue by alexodle** [hashicorp/terraform#23009]
### Terraform Version

```
0.12.9
```

### Terraform Configuration Files

```hcl
...
```

### Debug Output

Just posting a snippet from the end here, but I can go digging for more info if I get a better idea of what I'm looking for.

```
2019/10/05 01:08:34 [TRACE] GRPCProvider: GetSchema
2019/10/05 01:08:34 [TRACE] GRPCProvider: Close
2019-10-05T01:08:34.836Z [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform-provider-template_v2.1.2_x4 pid=2530
2019-10-05T01:08:34.836Z [DEBUG] plugin: plugin exited
2019/10/05 01:08:34 [TRACE] LoadSchemas: retrieving schema for provisioner "local-exec"
2019-10-05T01:08:34.837Z [DEBUG] plugin: starting plugin: path=/usr/local/bin/terraform args=[/usr/local/bin/terraform, internal-plugin, provisioner, local-exec]
2019-10-05T01:08:34.837Z [DEBUG] plugin: plugin started: path=/usr/local/bin/terraform pid=2569
2019-10-05T01:08:34.837Z [DEBUG] plugin: waiting for RPC address: path=/usr/local/bin/terraform
2019-10-05T01:08:34.849Z [DEBUG] plugin.terraform: 2019/10/05 01:08:34 [INFO] Terraform version: 0.12.9  
2019-10-05T01:08:34.849Z [DEBUG] plugin.terraform: 2019/10/05 01:08:34 [INFO] Go runtime version: go1.12.9
2019-10-05T01:08:34.849Z [DEBUG] plugin.terraform: 2019/10/05 01:08:34 [INFO] CLI args: []string{"/usr/local/bin/terraform", "internal-plugin", "provisioner", "local-exec"}
2019-10-05T01:08:34.849Z [DEBUG] plugin.terraform: 2019/10/05 01:08:34 [DEBUG] Attempting to open CLI config file: /tmp/cli.tfrc
2019-10-05T01:08:34.849Z [DEBUG] plugin.terraform: 2019/10/05 01:08:34 Loading CLI configuration from /tmp/cli.tfrc
2019-10-05T01:08:34.850Z [DEBUG] plugin.terraform: 2019/10/05 01:08:34 [INFO] CLI command args: []string{"internal-plugin", "provisioner", "local-exec"}
2019-10-05T01:08:34.850Z [DEBUG] plugin.terraform: local-exec-provisioner (internal) 2019/10/05 01:08:34 [INFO] Starting provisioner plugin local-exec
2019-10-05T01:08:34.850Z [DEBUG] plugin.terraform: plugin address: address=/tmp/plugin267804509 network=unix timestamp=2019-10-05T01:08:34.850Z
2019-10-05T01:08:34.850Z [DEBUG] plugin: using plugin: version=5
2019-10-05T01:08:34.853Z [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform pid=2569
2019-10-05T01:08:34.854Z [DEBUG] plugin: plugin exited
2019/10/05 01:08:34 [TRACE] terraform.NewContext: complete
2019/10/05 01:08:34 [TRACE] backend/remote: finished building terraform.Context
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18088e0]

goroutine 1 [running]:
github.com/hashicorp/terraform/command/jsonstate.marshalResources(0xc001b53380, 0xc002528df0, 0x1, 0xc003282b00, 0x16, 0xc001653530, 0xc002565f00)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/jsonstate/state.go:277 +0x2a0
github.com/hashicorp/terraform/command/jsonstate.marshalModules(0xc00000f928, 0xc002528df0, 0xc0034de780, 0xb, 0x10, 0xc001653530, 0x1, 0x2, 0xe09ba1, 0xc00278f230, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/jsonstate/state.go:224 +0x199
github.com/hashicorp/terraform/command/jsonstate.marshalRootModule(0xc00000f928, 0xc002528df0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/jsonstate/state.go:207 +0x3c5
github.com/hashicorp/terraform/command/jsonstate.(*state).marshalStateValues(0xc00278f1a0, 0xc00000f928, 0xc002528df0, 0x0, 0x2)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/jsonstate/state.go:156 +0x139
github.com/hashicorp/terraform/command/jsonstate.Marshal(0xc0026a0180, 0xc002528df0, 0x0, 0x0, 0x0, 0x2e, 0x1fa3c)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/jsonstate/state.go:136 +0x9e
github.com/hashicorp/terraform/command/jsonplan.Marshal(0xc0011b12b0, 0xc003479880, 0xc0026a0180, 0xc002528df0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/jsonplan/plan.go:123 +0x75d
github.com/hashicorp/terraform/command.(*ShowCommand).Run(0xc00047a4e0, 0xc00003a0a0, 0x2, 0x2, 0xc000244210)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/show.go:145 +0x90e
github.com/mitchellh/cli.(*CLI).Run(0xc00043f680, 0xc00043f680, 0xc000565d90, 0x1)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:235 +0xb66
main.realMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:100 +0xb4
main.main()
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:36 +0x3b
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18088e0]

goroutine 1 [running]:
github.com/hashicorp/terraform/command/jsonstate.marshalResources(0xc001b53380, 0xc002528df0, 0x1, 0xc003282b00, 0x16, 0xc001653530, 0xc002565f00)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/jsonstate/state.go:277 +0x2a0
github.com/hashicorp/terraform/command/jsonstate.marshalModules(0xc00000f928, 0xc002528df0, 0xc0034de780, 0xb, 0x10, 0xc001653530, 0x1, 0x2, 0xe09ba1, 0xc00278f230, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/jsonstate/state.go:224 +0x199
github.com/hashicorp/terraform/command/jsonstate.marshalRootModule(0xc00000f928, 0xc002528df0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/jsonstate/state.go:207 +0x3c5
github.com/hashicorp/terraform/command/jsonstate.(*state).marshalStateValues(0xc00278f1a0, 0xc00000f928, 0xc002528df0, 0x0, 0x2)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/jsonstate/state.go:156 +0x139
github.com/hashicorp/terraform/command/jsonstate.Marshal(0xc0026a0180, 0xc002528df0, 0x0, 0x0, 0x0, 0x2e, 0x1fa3c)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/jsonstate/state.go:136 +0x9e
github.com/hashicorp/terraform/command/jsonplan.Marshal(0xc0011b12b0, 0xc003479880, 0xc0026a0180, 0xc002528df0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/jsonplan/plan.go:123 +0x75d
github.com/hashicorp/terraform/command.(*ShowCommand).Run(0xc00047a4e0, 0xc00003a0a0, 0x2, 0x2, 0xc000244210)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/show.go:145 +0x90e
github.com/mitchellh/cli.(*CLI).Run(0xc00043f680, 0xc00043f680, 0xc000565d90, 0x1)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:235 +0xb66
main.realMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:100 +0xb4
main.main()
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:36 +0x3b



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by teamterraform** [comment]
Hi @alexodle , thank you for reporting this and I'm sorry you've experienced this crash!
A PR ([#23027](https://github.com/hashicorp/terraform/pull/23027)) was just merged that will fix this, and it will be included in the next release.
