### ISSUE TITLE
Panic in plan output when string contains "null" with whitespace

### ISSUE THREAD

**Issue by simonbrady** [hashicorp/terraform#23100]
### Terraform Version

```
Terraform v0.12.10
```
Also reproducible on v0.12.11-dev (commit a7af2a40)

### Terraform Configuration Files

```hcl
provider "aws" {
  version = "~>2"
  region  = "us-east-1"
}

resource "aws_s3_bucket" "test" {
  bucket = "null "
}
```
This is a contrived minimal example - the bug is independent of provider and was first observed with the Azure provider.

### Crash Output

```
panic: value is null

goroutine 14 [running]:
github.com/zclconf/go-cty/cty.Value.LengthInt(0x22a47a0, 0x3416fd0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.1.0/cty/value_ops.go:874 +0x253
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeValue(0xc0005df8a8, 0x22a4760, 0xc00003c460, 0x1a639e0, 0xc00102cbd0, 0x2b, 0x8)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/format/diff.go:509 +0x13a8
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeAttrDiff(0xc0005df8a8, 0xc00051d2e8, 0x6, 0xc000b3d4a0, 0x22a4760, 0xc00003c460, 0x0, 0x0, 0x22a4760, 0xc00003c460, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/format/diff.go:255 +0x370
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeBlockBodyDiff(0xc0005df8a8, 0xc000af5570, 0x22a4860, 0xc0004570f8, 0x0, 0x0, 0x22a4860, 0xc000457310, 0x1b08d40, 0xc000a38f90, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/format/diff.go:196 +0x5d5
github.com/hashicorp/terraform/command/format.ResourceChange(0xc000bf8200, 0xc0008c9400, 0xc000af5570, 0xc0003a5130, 0xc000a8b860, 0x8e)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/format/diff.go:140 +0x5ff
github.com/hashicorp/terraform/backend/local.(*Local).renderPlan(0xc00018a410, 0xc0002540e0, 0xc000457180, 0xc000454080)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:270 +0x6ad
github.com/hashicorp/terraform/backend/local.(*Local).opPlan(0xc00018a410, 0x22a2ae0, 0xc00026d8c0, 0x22a2ae0, 0xc00026d900, 0xc0002a28c0, 0xc00026d880)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:165 +0xb9c
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc0003a5900, 0xc0003a5910, 0xc0003a5920, 0xc0002a28c0, 0xc00018a410, 0xc00026d880, 0xc0003a58f0, 0x22a2ae0, 0xc00026d8c0, 0x22a2ae0, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend.go:356 +0x135
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend.go:340 +0x36b
```
[Full log](https://gist.github.com/simonbrady/77c719927fc57c98eab9a33a6ccc450d)

### Expected Behavior

Output of `terraform plan` should include the literal string `"null "`.

### Actual Behavior

The above crash occurs consistently.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### References

- Fix in PR #23102

**Comment by mildwonkey** [comment]
The fix was merged, so I'm going to close this - please open a new issue if you see any further problems!
