### ISSUE TITLE
rpc error: code = Unavailable desc = transport is closing - attaching cloudfront to s3 policy

### ISSUE THREAD

**Issue by ginski47** [hashicorp/terraform#23326]
I keep getting the following error when i try attaching a bucket policy with cloudfront origin access identity. this is  my code snippet:, 

I'm using provider version: 2.30.0 still getting the error. crash log says:

Panic says:  panic: interface conversion: interface {} is []interface {}, not string

```
`{
    "Version": "2012-10-17",
    "Id": "S3_Cloudfront_Policy",
    "Statement": [
        {
            "Sid": "Stmt1552079734001",
            "Effect": "Allow",
            "Principal": {
                "AWS": ${key_users}
            },
            "Action": [
                "s3:Get*",
                "s3:List*",
                "s3:Put*",
                "s3:Delete*"
            ],
            "Resource": ${bucket_resources}
        },
        {
            "Sid": "Stmt1552079734002",
            "Effect": "Allow",
            "Principal": {
                "CanonicalUser": ${cloudfront_origin_access_identity}
            },
            "Action": [
                "s3:Get*",
                "s3:List*",
                "s3:Put*",
                "s3:Delete*"
            ],
            "Resource": ${bucket_resources}
        }
    ]
}`
```

**AND THIS IS MY ERROR I keep getting.** At this point it doesnt even create a new bucket when I attach it to a different policy it just keeps TERRAFORM CRASH and gives me this:

```
`Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing


panic: interface conversion: interface {} is []interface {}, not string
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: goroutine 81 [running]:
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: github.com/jen20/awspolicyequivalence.newAWSStringSet(0x3cf4f00, 0xc000b61880, 0xc000654e60, 0x3, 0xc000655098)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/jen20/awspolicyequivalence@v1.0.0/aws_policy_equivalence.go:386 +0x212
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: github.com/jen20/awspolicyequivalence.newAWSPrincipalStringSet(...)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/jen20/awspolicyequivalence@v1.0.0/aws_policy_equivalence.go:395
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: github.com/jen20/awspolicyequivalence.mapPrincipalsEqual(0x41e2a80, 0xc0006ad230, 0x41e2a80, 0xc0006ad440, 0x0)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/jen20/awspolicyequivalence@v1.0.0/aws_policy_equivalence.go:229 +0x4b2
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: github.com/jen20/awspolicyequivalence.(*awsPolicyStatement).equals(0xc00041cc60, 0xc00041cf30, 0x0)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/jen20/awspolicyequivalence@v1.0.0/aws_policy_equivalence.go:195 +0x490
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: github.com/jen20/awspolicyequivalence.(*awsPolicyDocument).equals(0xc000872900, 0xc000872980, 0x0)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/jen20/awspolicyequivalence@v1.0.0/aws_policy_equivalence.go:114 +0xea
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: github.com/jen20/awspolicyequivalence.PoliciesAreEquivalent(0xc000b4d400, 0x4f0, 0xc00060d500, 0xa0e, 0x40eac3, 0xc000655428, 0xc0006ad020)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/jen20/awspolicyequivalence@v1.0.0/aws_policy_equivalence.go:50 +0x361
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.suppressEquivalentAwsPolicyDiffs(0x4c5589e, 0x6, 0xc000b4d400, 0x4f0, 0xc00060d500, 0xa0e, 0xc0003184d0, 0x42d200)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/diff_suppress_funcs.go:15 +0x49
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.schemaMap.diff(0xc0001a2750, 0x4c5589e, 0x6, 0xc0001ad100, 0xc000b61460, 0x5503a00, 0xc0003184d0, 0x0, 0x0, 0x0)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.2.0/helper/schema/schema.go:893 +0x37c
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.schemaMap.Diff(0xc0001a2750, 0xc000c6bcc0, 0xc0006ac8d0, 0x0, 0x3c9e900, 0xc000439200, 0x54f0400, 0xc000b6a590, 0x0, 0x0)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.2.0/helper/schema/schema.go:491 +0x215
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).simpleDiff(0xc0001a1280, 0xc000c6bcc0, 0xc0006ac8d0, 0x3c9e900, 0xc000439200, 0xc0006ac801, 0x0, 0x0)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.2.0/helper/schema/resource.go:351 +0x85
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).SimpleDiff(0xc000695d00, 0xc0004c9978, 0xc000c6bcc0, 0xc0006ac8d0, 0xc000b9eba0, 0xc0006ac8d0, 0x0)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.2.0/helper/schema/provider.go:321 +0x99
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).PlanResourceChange(0xc00000f760, 0x54ef580, 0xc0005beb40, 0xc0009c9e00, 0xc00000f760, 0xc0005beb40, 0xc000d5ba80)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.2.0/internal/helper/plugin/grpc_provider.go:633 +0x765
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_PlanResourceChange_Handler(0x4b34400, 0xc00000f760, 0x54ef580, 0xc0005beb40, 0xc0009c9da0, 0x0, 0x54ef580, 0xc0005beb40, 0xc00062a000, 0x1cc1)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.2.0/internal/tfplugin5/tfplugin5.pb.go:3171 +0x217
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000a4000, 0x550e6e0, 0xc000010180, 0xc0008d8500, 0xc0006ace10, 0x7ea3708, 0x0, 0x0, 0x0)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:995 +0x460
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: google.golang.org/grpc.(*Server).handleStream(0xc0000a4000, 0x550e6e0, 0xc000010180, 0xc0008d8500, 0x0)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1275 +0xd97
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000384a0, 0xc0000a4000, 0x550e6e0, 0xc000010180, 0xc0008d8500)
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:710 +0xbb
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2019-11-08T16:47:27.434-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:708 +0xa1
2019-11-08T16:47:27.434-0500 [DEBUG] plugin: plugin process exited: path=/home/SILVER/c91002/opportunity-etl/deploy/s3_pceg/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.35.0_x4 pid=23197 error="exit status 2"
2019/11/08 16:47:27 [ERROR] module.front-code-s3: eval: *terraform.EvalDiff, err: rpc error: code = Unavailable desc = transport is closing
2019/11/08 16:47:27 [ERROR] module.front-code-s3: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/11/08 16:47:27 [TRACE] [walkPlan] Exiting eval tree: module.front-code-s3.aws_s3_bucket.this
2019/11/08 16:47:27 [TRACE] vertex "module.front-code-s3.aws_s3_bucket.this": visit complete
2019/11/08 16:47:27 [TRACE] vertex "module.front-code-s3.aws_s3_bucket.this": dynamic subgraph encountered errors
2019/11/08 16:47:27 [TRACE] vertex "module.front-code-s3.aws_s3_bucket.this": visit complete
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.front-code-s3.output.s3_bucket_arn" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "output.front-code-s3-arn" errored, so skipping
2019/11/08 16:47:27 [ERROR] module.front-code-s3: eval: *terraform.EvalDiff, err: rpc error: code = Unavailable desc = transport is closing
2019/11/08 16:47:27 [ERROR] module.front-code-s3: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/11/08 16:47:27 [TRACE] [walkPlan] Exiting eval tree: module.front-code-s3.aws_kms_alias.key_alias
2019/11/08 16:47:27 [TRACE] vertex "module.front-code-s3.aws_kms_alias.key_alias": visit complete
2019/11/08 16:47:27 [TRACE] vertex "module.front-code-s3.aws_kms_alias.key_alias": dynamic subgraph encountered errors
2019/11/08 16:47:27 [TRACE] vertex "module.front-code-s3.aws_kms_alias.key_alias": visit complete
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.front-code-s3.output.kms_key_alias_id" errored, so skipping
2019/11/08 16:47:27 [ERROR] module.input-s3: eval: *terraform.EvalDiff, err: rpc error: code = Unavailable desc = transport is closing
2019/11/08 16:47:27 [ERROR] module.input-s3: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/11/08 16:47:27 [TRACE] [walkPlan] Exiting eval tree: module.input-s3.aws_kms_key.key
2019/11/08 16:47:27 [TRACE] vertex "module.input-s3.aws_kms_key.key": visit complete
2019/11/08 16:47:27 [TRACE] vertex "module.input-s3.aws_kms_key.key": dynamic subgraph encountered errors
2019/11/08 16:47:27 [TRACE] vertex "module.input-s3.aws_kms_key.key": visit complete
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.input-s3.output.kms_key_arn" errored, so skipping
2019/11/08 16:47:27 [ERROR] module.output-s3: eval: *terraform.EvalDiff, err: rpc error: code = Unavailable desc = transport is closing
2019/11/08 16:47:27 [ERROR] module.output-s3: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/11/08 16:47:27 [TRACE] [walkPlan] Exiting eval tree: module.output-s3.aws_kms_key.key
2019/11/08 16:47:27 [TRACE] vertex "module.output-s3.aws_kms_key.key": visit complete
2019/11/08 16:47:27 [TRACE] vertex "module.output-s3.aws_kms_key.key": dynamic subgraph encountered errors
2019/11/08 16:47:27 [TRACE] vertex "module.output-s3.aws_kms_key.key": visit complete
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.output-s3.aws_kms_alias.key_alias" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.output-s3.output.kms_key_alias_id" errored, so skipping
2019/11/08 16:47:27 [ERROR] module.logs-s3: eval: *terraform.EvalDiff, err: rpc error: code = Unavailable desc = transport is closing
2019/11/08 16:47:27 [ERROR] module.logs-s3: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/11/08 16:47:27 [TRACE] [walkPlan] Exiting eval tree: module.logs-s3.aws_kms_key.key
2019/11/08 16:47:27 [TRACE] vertex "module.logs-s3.aws_kms_key.key": visit complete
2019/11/08 16:47:27 [TRACE] vertex "module.logs-s3.aws_kms_key.key": dynamic subgraph encountered errors
2019/11/08 16:47:27 [TRACE] vertex "module.logs-s3.aws_kms_key.key": visit complete
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.logs-s3.output.kms_key_arn" errored, so skipping
2019/11/08 16:47:27 [ERROR] module.code-s3: eval: *terraform.EvalDiff, err: rpc error: code = Unavailable desc = transport is closing
2019/11/08 16:47:27 [ERROR] module.code-s3: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/11/08 16:47:27 [TRACE] [walkPlan] Exiting eval tree: module.code-s3.aws_kms_key.key
2019/11/08 16:47:27 [TRACE] vertex "module.code-s3.aws_kms_key.key": visit complete
2019/11/08 16:47:27 [TRACE] vertex "module.code-s3.aws_kms_key.key": dynamic subgraph encountered errors
2019/11/08 16:47:27 [TRACE] vertex "module.code-s3.aws_kms_key.key": visit complete
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.code-s3.output.kms_key_id" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.front-code-s3.aws_s3_bucket_policy.s3_bucket_policy" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.front-code-s3.aws_cloudwatch_metric_alarm.s3_alarm_5xx" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.front-code-s3.aws_cloudwatch_metric_alarm.s3_alarm_4xx" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.front-code-s3.output.s3_bucket_id" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "output.front-code-s3-id" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.front-code-s3.aws_s3_bucket_metric.s3_bucket_metric" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.front-code-s3.output.kms_key_alias_arn" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.input-s3.aws_kms_alias.key_alias" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.input-s3.output.kms_key_alias_id" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.input-s3.output.kms_key_id" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.output-s3.output.kms_key_arn" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.output-s3.output.kms_key_id" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.output-s3.output.kms_key_alias_arn" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.logs-s3.output.kms_key_id" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.logs-s3.aws_kms_alias.key_alias" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.logs-s3.output.kms_key_alias_id" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.code-s3.output.kms_key_arn" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.code-s3.aws_kms_alias.key_alias" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.code-s3.output.kms_key_alias_id" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.input-s3.output.kms_key_alias_arn" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.logs-s3.output.kms_key_alias_arn" errored, so skipping
2019/11/08 16:47:27 [TRACE] dag/walk: upstream of "module.code-s3.output.kms_key_alias_arn" errored, so skipping
2019/11/08 16:47:27 [TRACE] [walkPlan] Exiting eval tree: module.output-s3.provider.aws.replication_region
2019/11/08 16:47:27 [TRACE] vertex "module.output-s3.provider.aws.replication_region": visit complete
2019/11/08 16:47:27 [TRACE] dag/walk: visiting "module.output-s3.aws_s3_bucket.replicated_bucket"
2019/11/08 16:47:27 [TRACE] vertex "module.output-s3.aws_s3_bucket.replicated_bucket": starting visit (*terraform.NodePlannableResource)
2019/11/08 16:47:27 [TRACE] vertex "module.output-s3.aws_s3_bucket.replicated_bucket": evaluating
2019/11/08 16:47:27 [TRACE] [walkPlan] Entering eval tree: module.output-s3.aws_s3_bucket.replicated_bucket
2019/11/08 16:47:27 [TRACE] module.output-s3: eval: *terraform.EvalWriteResourceState
2019/11/08 16:47:27 [TRACE] [walkPlan] Exiting eval tree: module.output-s3.aws_s3_bucket.replicated_bucket
2019/11/08 16:47:27 [TRACE] vertex "module.output-s3.aws_s3_bucket.replicated_bucket": expanding dynamic subgraph
2019/11/08 16:47:27 [TRACE] Executing graph transform *terraform.ResourceCountTransformer
2019/11/08 16:47:27 [TRACE] Completed graph transform *terraform.ResourceCountTransformer (no changes)
2019/11/08 16:47:27 [TRACE] Executing graph transform *terraform.OrphanResourceCountTransformer
2019/11/08 16:47:27 [TRACE] Completed graph transform *terraform.OrphanResourceCountTransformer (no changes)
2019/11/08 16:47:27 [TRACE] Executing graph transform *terraform.AttachStateTransformer
2019/11/08 16:47:27 [TRACE] Completed graph transform *terraform.AttachStateTransformer (no changes)
2019/11/08 16:47:27 [TRACE] Executing graph transform *terraform.TargetsTransformer
2019/11/08 16:47:27 [TRACE] Completed graph transform *terraform.TargetsTransformer (no changes)
2019/11/08 16:47:27 [TRACE] Executing graph transform *terraform.ReferenceTransformer
2019/11/08 16:47:27 [TRACE] Completed graph transform *terraform.ReferenceTransformer (no changes)
2019/11/08 16:47:27 [TRACE] Executing graph transform *terraform.RootTransformer
2019/11/08 16:47:27 [TRACE] Completed graph transform *terraform.RootTransformer with new graph:
root - terraform.graphNodeRoot
`
```

**Comment by ginski47** [comment]
This was fixed due to a bug in my Principal. I was referencing 

```
            "Principal": {
                "AWS": ${key_users}
```

key_users in my main.tf was supposd to be a list and instead i put [  ] over it. making it a double list giving a panic error. hence the crash.
