### ISSUE TITLE
invalid memory address or nil pointer dereference when updating resource

### ISSUE THREAD

**Issue by dawidpogorzelski** [hashicorp/terraform#23522]
### Terraform Version

```
0.12.16
```

### Terraform Configuration Files

```hcl
variable "test" {
  default = "a"
}

resource "google_compute_instance_template" "asd" {
  for_each    = signum(length(var.asd.a.servers) + length(var.asd.b.servers) + length(var.asd.c.servers) + length(var.asd.d.servers)) > 0 ? local.somethings : toset([])
  name_prefix = terraform.workspace
  tags = [
    terraform.workspace,
    "${terraform.workspace}-asd",
    "${terraform.workspace}-asd-${each.key}"
  ]

  labels = {
    something = "${each.key}"
    role      = "asd"
    workspace = terraform.workspace
  }

  machine_type = var.asd.size

  scheduling {
    automatic_restart = true
  }

  disk {
    source_image = var.test != "" ? "debian-10" : "debian-9"
    auto_delete  = true
    boot         = true
    disk_type    = "pd-ssd"
  }

  network_interface {
    network = var.network.vpc
    access_config {
      nat_ip = ""
    }
  }

  metadata = {
    something           = "${each.key}"
    role                = "asd"
    workspace           = terraform.workspace
    sshKeys             = join("\n", var.ssh_keys)
    startup-script-url  = "gs://${var.storage.scripts_bucket}/${var.storage.startup_script}"
    shutdown-script-url = "gs://${var.storage.scripts_bucket}/${var.storage.shutdown_script}"
  }

  service_account {
    scopes = [
      "storage-ro",
      "logging-write",
      "monitoring-write",
      "service-management",
      "service-control",
      "trace-append",
    ]
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "google_compute_region_instance_group_manager" "asd_c" {
  for_each = var.asd.c.servers
  name     = "${terraform.workspace}-${each.key}-asd-c"

  base_instance_name = terraform.workspace
  region             = each.key

  target_size = each.value

  update_policy {
    type                         = "PROACTIVE"
    instance_redistribution_type = "NONE"
    minimal_action               = "REPLACE"
    max_surge_fixed              = 3
    max_unavailable_fixed        = 3
    min_ready_sec                = 480
  }

  version {
    name              = "current"
    instance_template = google_compute_instance_template.asd["c"].self_link
  }
}
```

### Crash Output

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1abb0a3]

goroutine 241 [running]:
github.com/hashicorp/terraform/terraform.(*evaluationStateData).getResourceInstancesAll(0xc0000c41b0, 0x4d, 0xc000044c00, 0x20, 0xc0000430a4, 0x3, 0xc0000425cc, 0x4, 0x8f, 0x19, ...)
	/private/tmp/terraform-20191119-99583-jc7irh/terraform-0.12.16/src/github.com/hashicorp/terraform/terraform/evaluate.go:724 +0x483
github.com/hashicorp/terraform/terraform.(*evaluationStateData).GetResource(0xc0000c41b0, 0x4d, 0xc000044c00, 0x20, 0xc0000430a4, 0x3, 0xc0000425cc, 0x4, 0x8f, 0x19, ...)
	/private/tmp/terraform-20191119-99583-jc7irh/terraform-0.12.16/src/github.com/hashicorp/terraform/terraform/evaluate.go:560 +0x85a
github.com/hashicorp/terraform/lang.(*Scope).evalContext(0xc00018e690, 0xc000869800, 0x6, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100c688)
	/private/tmp/terraform-20191119-99583-jc7irh/terraform-0.12.16/src/github.com/hashicorp/terraform/lang/eval.go:278 +0x2d2c
github.com/hashicorp/terraform/lang.(*Scope).EvalContext(...)
	/private/tmp/terraform-20191119-99583-jc7irh/terraform-0.12.16/src/github.com/hashicorp/terraform/lang/eval.go:160
github.com/hashicorp/terraform/lang.(*Scope).EvalBlock(0xc00018e690, 0x2e89700, 0xc0008527b0, 0xc000251240, 0x1, 0x1, 0x0, 0x0, 0x0, 0x26b6dc0, ...)
	/private/tmp/terraform-20191119-99583-jc7irh/terraform-0.12.16/src/github.com/hashicorp/terraform/lang/eval.go:52 +0xf1
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc000b78680, 0x2e89700, 0xc0008527b0, 0xc000251240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/terraform-20191119-99583-jc7irh/terraform-0.12.16/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:272 +0x2b4
github.com/hashicorp/terraform/terraform.(*EvalDiff).Eval(0xc000b5f200, 0x2eba080, 0xc000b78680, 0x2, 0x2, 0x0, 0x0)
	/private/tmp/terraform-20191119-99583-jc7irh/terraform-0.12.16/src/github.com/hashicorp/terraform/terraform/eval_diff.go:138 +0x226
github.com/hashicorp/terraform/terraform.EvalRaw(0x2e47e00, 0xc000b5f200, 0x2eba080, 0xc000b78680, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/terraform-20191119-99583-jc7irh/terraform-0.12.16/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc00086cba0, 0x2eba080, 0xc000b78680, 0x2, 0x2, 0x1aa95d5, 0x2e48180)
	/private/tmp/terraform-20191119-99583-jc7irh/terraform-0.12.16/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x2e48140, 0xc00086cba0, 0x2eba080, 0xc000b78680, 0x26a8240, 0x3c66b81, 0x2612b40, 0xc000811ee0)
	/private/tmp/terraform-20191119-99583-jc7irh/terraform-0.12.16/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.Eval(0x2e48140, 0xc00086cba0, 0x2eba080, 0xc000b78680, 0xc00086cba0, 0x2e48140, 0xc00086cba0, 0x0)
	/private/tmp/terraform-20191119-99583-jc7irh/terraform-0.12.16/src/github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x299cb60, 0xc000c465a0, 0x0, 0x0, 0x0)
	/private/tmp/terraform-20191119-99583-jc7irh/terraform-0.12.16/src/github.com/hashicorp/terraform/terraform/graph.go:90 +0xf7e
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000860500, 0x299cb60, 0xc000c465a0, 0xc000ca8080)
	/private/tmp/terraform-20191119-99583-jc7irh/terraform-0.12.16/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x377
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/private/tmp/terraform-20191119-99583-jc7irh/terraform-0.12.16/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xaa7
```

### Expected Behavior

A new template should have been created and `google_compute_region_instance_group_manager` updated accordingly

### Steps to Reproduce

1. Create the resources above
2. Change variable's `test` value and `terraform apply` again

### Additional Context

Plan
```hcl
+/- resource "google_compute_instance_template" "asd" {
        can_ip_forward       = false
      ~ id                   = "projects/someproject/global/instanceTemplates/default20191128160228051400000002" -> (known after apply)
        labels               = {
            "role"      = "asd"
            "something" = "a"
            "workspace" = "default"
        }
        machine_type         = "n1-highmem-8"
        metadata             = {
            "role"                = "asd"
            "shutdown-script-url" = "gs:///"
            "something"           = "a"
            "sshKeys"             = ""
            "startup-script-url"  = "gs:///"
            "workspace"           = "default"
        }
      ~ metadata_fingerprint = "h65o9TxHOc4=" -> (known after apply)
      ~ name                 = "default20191128160228051400000002" -> (known after apply)
        name_prefix          = "default"
      ~ project              = "someproject" -> (known after apply)
      + region               = (known after apply)
      ~ self_link            = "https://www.googleapis.com/compute/beta/projects/someproject/global/instanceTemplates/default20191128160228051400000002" -> (known after apply)
        tags                 = [
            "default",
            "default-asd",
            "default-asd-a",
            "default-game-service",
        ]
      + tags_fingerprint     = (known after apply)

      ~ disk {
            auto_delete  = true
            boot         = true
          ~ device_name  = "persistent-disk-0" -> (known after apply)
          - disk_size_gb = 0 -> null
            disk_type    = "pd-ssd"
          ~ interface    = "SCSI" -> (known after apply)
          - labels       = {} -> null
          ~ mode         = "READ_WRITE" -> (known after apply)
          ~ source_image = "projects/debian-cloud/global/images/family/debian-10" -> "debian-9" # forces replacement
          ~ type         = "PERSISTENT" -> (known after apply)
        }

      ~ network_interface {
          ~ network            = "https://www.googleapis.com/compute/v1/projects/someproject/global/networks/mynet" -> "mynet"
          + subnetwork         = (known after apply)
          + subnetwork_project = (known after apply)

          ~ access_config {
              + nat_ip       = (known after apply)
              ~ network_tier = "PREMIUM" -> (known after apply)
            }
        }

      ~ scheduling {
            automatic_restart   = true
          ~ on_host_maintenance = "MIGRATE" -> (known after apply)
            preemptible         = false
        }

      ~ service_account {
          ~ email  = "default" -> (known after apply)
            scopes = [
                "https://www.googleapis.com/auth/devstorage.read_only",
                "https://www.googleapis.com/auth/logging.write",
                "https://www.googleapis.com/auth/monitoring.write",
                "https://www.googleapis.com/auth/service.management.readonly",
                "https://www.googleapis.com/auth/servicecontrol",
                "https://www.googleapis.com/auth/trace.append",
            ]
        }
    }

  # google_compute_instance_template.asd["b"] must be replaced
+/- resource "google_compute_instance_template" "asd" {
        can_ip_forward       = false
      ~ id                   = "projects/someproject/global/instanceTemplates/default20191128160228076600000003" -> (known after apply)
        labels               = {
            "role"      = "asd"
            "something" = "b"
            "workspace" = "default"
        }
        machine_type         = "n1-highmem-8"
        metadata             = {
            "role"                = "asd"
            "shutdown-script-url" = "gs:///"
            "something"           = "b"
            "sshKeys"             = ""
            "startup-script-url"  = "gs:///"
            "workspace"           = "default"
        }
      ~ metadata_fingerprint = "IpDI9lytJa0=" -> (known after apply)
      ~ name                 = "default20191128160228076600000003" -> (known after apply)
        name_prefix          = "default"
      ~ project              = "someproject" -> (known after apply)
      + region               = (known after apply)
      ~ self_link            = "https://www.googleapis.com/compute/beta/projects/someproject/global/instanceTemplates/default20191128160228076600000003" -> (known after apply)
        tags                 = [
            "default",
            "default-asd",
            "default-asd-b",
            "default-game-service",
        ]
      + tags_fingerprint     = (known after apply)

      ~ disk {
            auto_delete  = true
            boot         = true
          ~ device_name  = "persistent-disk-0" -> (known after apply)
          - disk_size_gb = 0 -> null
            disk_type    = "pd-ssd"
          ~ interface    = "SCSI" -> (known after apply)
          - labels       = {} -> null
          ~ mode         = "READ_WRITE" -> (known after apply)
          ~ source_image = "projects/debian-cloud/global/images/family/debian-10" -> "debian-9" # forces replacement
          ~ type         = "PERSISTENT" -> (known after apply)
        }

      ~ network_interface {
          ~ network            = "https://www.googleapis.com/compute/v1/projects/someproject/global/networks/mynet" -> "mynet"
          + subnetwork         = (known after apply)
          + subnetwork_project = (known after apply)

          ~ access_config {
              + nat_ip       = (known after apply)
              ~ network_tier = "PREMIUM" -> (known after apply)
            }
        }

      ~ scheduling {
            automatic_restart   = true
          ~ on_host_maintenance = "MIGRATE" -> (known after apply)
            preemptible         = false
        }

      ~ service_account {
          ~ email  = "default" -> (known after apply)
            scopes = [
                "https://www.googleapis.com/auth/devstorage.read_only",
                "https://www.googleapis.com/auth/logging.write",
                "https://www.googleapis.com/auth/monitoring.write",
                "https://www.googleapis.com/auth/service.management.readonly",
                "https://www.googleapis.com/auth/servicecontrol",
                "https://www.googleapis.com/auth/trace.append",
            ]
        }
    }

  # google_compute_instance_template.asd["c"] must be replaced
+/- resource "google_compute_instance_template" "asd" {
        can_ip_forward       = false
      ~ id                   = "projects/someproject/global/instanceTemplates/default20191128160228194200000004" -> (known after apply)
        labels               = {
            "role"      = "asd"
            "something" = "c"
            "workspace" = "default"
        }
        machine_type         = "n1-highmem-8"
        metadata             = {
            "role"                = "asd"
            "shutdown-script-url" = "gs:///"
            "something"           = "c"
            "sshKeys"             = ""
            "startup-script-url"  = "gs:///"
            "workspace"           = "default"
        }
      ~ metadata_fingerprint = "5rpIRd9ihE8=" -> (known after apply)
      ~ name                 = "default20191128160228194200000004" -> (known after apply)
        name_prefix          = "default"
      ~ project              = "someproject" -> (known after apply)
      + region               = (known after apply)
      ~ self_link            = "https://www.googleapis.com/compute/beta/projects/someproject/global/instanceTemplates/default20191128160228194200000004" -> (known after apply)
        tags                 = [
            "default",
            "default-asd",
            "default-asd-c",
            "default-game-service",
        ]
      + tags_fingerprint     = (known after apply)

      ~ disk {
            auto_delete  = true
            boot         = true
          ~ device_name  = "persistent-disk-0" -> (known after apply)
          - disk_size_gb = 0 -> null
            disk_type    = "pd-ssd"
          ~ interface    = "SCSI" -> (known after apply)
          - labels       = {} -> null
          ~ mode         = "READ_WRITE" -> (known after apply)
          ~ source_image = "projects/debian-cloud/global/images/family/debian-10" -> "debian-9" # forces replacement
          ~ type         = "PERSISTENT" -> (known after apply)
        }

      ~ network_interface {
          ~ network            = "https://www.googleapis.com/compute/v1/projects/someproject/global/networks/mynet" -> "mynet"
          + subnetwork         = (known after apply)
          + subnetwork_project = (known after apply)

          ~ access_config {
              + nat_ip       = (known after apply)
              ~ network_tier = "PREMIUM" -> (known after apply)
            }
        }

      ~ scheduling {
            automatic_restart   = true
          ~ on_host_maintenance = "MIGRATE" -> (known after apply)
            preemptible         = false
        }

      ~ service_account {
          ~ email  = "default" -> (known after apply)
            scopes = [
                "https://www.googleapis.com/auth/devstorage.read_only",
                "https://www.googleapis.com/auth/logging.write",
                "https://www.googleapis.com/auth/monitoring.write",
                "https://www.googleapis.com/auth/service.management.readonly",
                "https://www.googleapis.com/auth/servicecontrol",
                "https://www.googleapis.com/auth/trace.append",
            ]
        }
    }

  # google_compute_instance_template.asd["d"] must be replaced
+/- resource "google_compute_instance_template" "asd" {
        can_ip_forward       = false
      ~ id                   = "projects/someproject/global/instanceTemplates/default20191128160228027500000001" -> (known after apply)
        labels               = {
            "role"      = "asd"
            "something" = "d"
            "workspace" = "default"
        }
        machine_type         = "n1-highmem-8"
        metadata             = {
            "role"                = "asd"
            "shutdown-script-url" = "gs:///"
            "something"           = "d"
            "sshKeys"             = ""
            "startup-script-url"  = "gs:///"
            "workspace"           = "default"
        }
      ~ metadata_fingerprint = "OZI4l7YZISU=" -> (known after apply)
      ~ name                 = "default20191128160228027500000001" -> (known after apply)
        name_prefix          = "default"
      ~ project              = "someproject" -> (known after apply)
      + region               = (known after apply)
      ~ self_link            = "https://www.googleapis.com/compute/beta/projects/someproject/global/instanceTemplates/default20191128160228027500000001" -> (known after apply)
        tags                 = [
            "default",
            "default-asd",
            "default-asd-d",
            "default-game-service",
        ]
      + tags_fingerprint     = (known after apply)

      ~ disk {
            auto_delete  = true
            boot         = true
          ~ device_name  = "persistent-disk-0" -> (known after apply)
          - disk_size_gb = 0 -> null
            disk_type    = "pd-ssd"
          ~ interface    = "SCSI" -> (known after apply)
          - labels       = {} -> null
          ~ mode         = "READ_WRITE" -> (known after apply)
          ~ source_image = "projects/debian-cloud/global/images/family/debian-10" -> "debian-9" # forces replacement
          ~ type         = "PERSISTENT" -> (known after apply)
        }

      ~ network_interface {
          ~ network            = "https://www.googleapis.com/compute/v1/projects/someproject/global/networks/mynet" -> "mynet"
          + subnetwork         = (known after apply)
          + subnetwork_project = (known after apply)

          ~ access_config {
              + nat_ip       = (known after apply)
              ~ network_tier = "PREMIUM" -> (known after apply)
            }
        }

      ~ scheduling {
            automatic_restart   = true
          ~ on_host_maintenance = "MIGRATE" -> (known after apply)
            preemptible         = false
        }

      ~ service_account {
          ~ email  = "default" -> (known after apply)
            scopes = [
                "https://www.googleapis.com/auth/devstorage.read_only",
                "https://www.googleapis.com/auth/logging.write",
                "https://www.googleapis.com/auth/monitoring.write",
                "https://www.googleapis.com/auth/service.management.readonly",
                "https://www.googleapis.com/auth/servicecontrol",
                "https://www.googleapis.com/auth/trace.append",
            ]
        }
    }

  # google_compute_region_instance_group_manager.asd_c["europe-west1"] will be updated in-place
  ~ resource "google_compute_region_instance_group_manager" "asd_c" {
        base_instance_name        = "default"
        distribution_policy_zones = [
            "europe-west1-b",
            "europe-west1-c",
            "europe-west1-d",
        ]
        fingerprint               = "sgRCc75Md1s="
        id                        = "projects/someproject/regions/europe-west1/instanceGroupManagers/default-europe-west1-asd-c"
        instance_group            = "https://www.googleapis.com/compute/v1/projects/someproject/regions/europe-west1/instanceGroups/default-europe-west1-asd-c"
        name                      = "default-europe-west1-asd-c"
        project                   = "someproject"
        region                    = "europe-west1"
        self_link                 = "https://www.googleapis.com/compute/v1/projects/someproject/regions/europe-west1/instanceGroupManagers/default-europe-west1-asd-c"
        target_pools              = []
        target_size               = 1
        wait_for_instances        = false

        update_policy {
            instance_redistribution_type = "NONE"
            max_surge_fixed              = 3
            max_surge_percent            = 0
            max_unavailable_fixed        = 3
            max_unavailable_percent      = 0
            min_ready_sec                = 480
            minimal_action               = "REPLACE"
            type                         = "PROACTIVE"
        }

      ~ version {
          ~ instance_template = "https://www.googleapis.com/compute/v1/projects/someproject/global/instanceTemplates/default20191128160228194200000004" -> (known after apply)
            name              = "current"
        }
    }

Plan: 4 to add, 1 to change, 4 to destroy.
```

**Comment by dawidpogorzelski** [comment]
Forgot to mention that the crash seems to be triggered by the 
```hcl
lifecycle {
    create_before_destroy = true
  }
```
block
