### ISSUE TITLE
terraform show -no-color crashed.

### ISSUE THREAD

**Issue by ronjarrell** [hashicorp/terraform#23614]
### Terraform Version
0.12.17

```
...
```

### Crash Output

https://gist.github.com/ronjarrell/243956dff54feb3fa9ac7ffbb5e58144

### Expected Behavior
Dump the remote state...

### Actual Behavior

Crash.

### Steps to Reproduce

Suddenly it happens every time I do a show!

**Comment by Lirt** [comment]
Similar issue here after update.

```bash
$ terraform show -no-color ${PLAN} | grep -E "^[[:space:]]*[-+/~]+ resource " | sed 's/ {$//g' >> plan.txt || exit 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x720776]

goroutine 1 [running]:
github.com/zclconf/go-cty/cty/set.Set.Has(0x0, 0x0, 0x0, 0x1d1e620, 0xc000a12b40, 0xc00188c0b3)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.1.0/cty/set/ops.go:54 +0x26
github.com/zclconf/go-cty/cty.PathSet.Has(...)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.1.0/cty/path_set.go:53
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).pathForcesNewResource(0xc001ff15a8, 0xc000dce090, 0x1, 0x3, 0x34f6040)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/format/diff.go:1036 +0xb9
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeValueDiff(0xc001ff15a8, 0x2358840, 0xc000048419, 0x1aa29c0, 0xc000965d30, 0x2358840, 0xc000048419, 0x1b631c0, 0x34f6040, 0x8, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/format/diff.go:1005 +0xf9b
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeAttrDiff(0xc001ff15a8, 0xc0025189e0, 0x12, 0xc0043de450, 0x2358840, 0xc000048419, 0x1aa29c0, 0xc000965d30, 0x2358840, 0xc000048419, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/format/diff.go:263 +0x4c4
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeBlockBodyDiff(0xc001ff15a8, 0xc00097d700, 0x2358940, 0xc005252150, 0x1b492a0, 0xc0034dc6c0, 0x2358940, 0xc0052521e0, 0x1b492a0, 0xc0033d0120, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/format/diff.go:196 +0x5d5
github.com/hashicorp/terraform/command/format.ResourceChange(0xc000736a00, 0x0, 0xc00097d700, 0xc002913210, 0x4d, 0xc0058457c0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/format/diff.go:140 +0x5ff
github.com/hashicorp/terraform/backend/local.RenderPlan(0xc002888000, 0xc005252020, 0xc003e00b20, 0x236c840, 0xc000369f40, 0xc002913210)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:288 +0x68c
github.com/hashicorp/terraform/command.(*ShowCommand).Run(0xc000568ea0, 0xc00003a0a0, 0x1, 0x2, 0xc000162140)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/show.go:165 +0xb04
github.com/mitchellh/cli.(*CLI).Run(0xc00035e280, 0xc00035e280, 0xc000535d90, 0x1)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:238 +0xc34
main.realMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:102 +0xb4
main.main()
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:38 +0x3b
```

**Comment by Lirt** [comment]
Possibly fixed in https://github.com/hashicorp/terraform/issues/23377.

**Comment by pselle** [comment]
@Lirt That just went out earlier today -- if you'd like to re-test with 0.12.18, I'd be grateful to know that we can close this issue (and happy to dig in if it's still present).

**Comment by Lirt** [comment]
Works correctly in my case. Thank you.

**Comment by ronjarrell** [comment]
Did a plan on my configuration.  A "terraform show -no-color planfile" seemed to consistently crash.  Installed 0.12.18 and reran the same plan step, and did the show on the new file, and it displayed normally.
I'll let you know i I run into this again today, but it's definitely seems improved, since I did the plan/show cycle three times in a row and it consistently crashed out with 12.17

**Comment by pselle** [comment]
Thanks so much for trying it out @Lirt and @ronjarrell! I'm going to close this, will re-open if there's another report, or would be interested in a new issue.

**Comment by ronjarrell** [comment]
The crash came back, the very next day...

https://gist.github.com/ronjarrell/a03f433032d36015fd70ca20805bb603

**Comment by pselle** [comment]
@ronjarrell Thanks Ron -- would you mind opening a new issue, completing the issue template? (that is, include a config, which will help with reproduction?)

**Comment by ronjarrell** [comment]
@pselle I can open a new issue, but I'm not sure I can provide a config - our tf projects are huge multi-repo things, and certain combinations of actions seem to cause the state file to make the cli blow chunks.
