### ISSUE TITLE
discovery plugin LegacyString calls cause panics

### ISSUE THREAD

**Issue by dreamlibrarian** [hashicorp/terraform#23652]
### Terraform Version

```
0.12.18
...
```

### Terraform Configuration Files

```hcl

# https://releases.hashicorp.com/terraform/
terraform {
  version = "0.12.17"
}

# Any that aren't staged in plugins/ need to be available here: https://releases.hashicorp.com/
providers {
  # Plugins available on releases.hashicorp.com
  aws      = ["~> 2.12"]
  azurerm  = ["~> 1.29"]
  archive  = ["~> 1.2"]
  dome9    = ["~> 1.14"]
}
...
```

### Debug Output

```
 terraform-bundle package -os=linux -arch=amd64 ./terraform_0.12.hcl
Fetching Terraform 0.12.17 core package...
Fetching 3rd party plugins in directory: ./plugins
- Resolving "dome9" provider (~> 1.14)...
- Checking for provider plugin on https://releases.hashicorp.com...
panic: not a legacy Provider

goroutine 1 [running]:
github.com/hashicorp/terraform/addrs.Provider.LegacyString(...)
        /home/tsmith/go/src/github.com/hashicorp/terraform/addrs/provider.go:46
github.com/hashicorp/terraform/plugin/discovery.(*ProviderInstaller).Get(0xc0004bdc08, 0xc0003ed0a0, 0x5, 0x0, 0x0, 0x0, 0x0, 0xc000010058, 0x1, 0x1, ...)
        /home/tsmith/go/src/github.com/hashicorp/terraform/plugin/discovery/get.go:235 +0x1c42
main.(*PackageCommand).Run(0xc0003a4a40, 0xc000032070, 0x3, 0x3, 0x0)
        /home/tsmith/go/src/github.com/hashicorp/terraform/tools/terraform-bundle/package.go:185 +0xef3
github.com/mitchellh/cli.(*CLI).Run(0xc00032f2c0, 0xc00034db90, 0xe6318c, 0x7)
        /home/tsmith/go/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1da
main.main()
        /home/tsmith/go/src/github.com/hashicorp/terraform/tools/terraform-bundle/main.go:75 +0x2e6
```
### Expected Behavior

terraform bundle should build a bundle

### Actual Behavior

terraform bundle panicked and crashed.

### Steps to Reproduce

1.  terraform-bundle package -os=linux -arch=amd64 ./{hcl file above}

### Additional Context

https://travis-ci.org/hashicorp/terraform/builds/622755699 appears to show the commit adding the call failed tests with a similar error.

**Comment by ghouscht** [comment]
Samme issue here, with `terraform-bundle` version 0.12.18:
```
terraform-bundle package bundle.hcl
Fetching Terraform 0.12.16 core package...
Fetching 3rd party plugins in directory: ./plugins
plugin: ad (0.2.1)
plugin: aixboms (1.1.1)
plugin: burger (0.0.2)
plugin: foreman (0.3.1)
plugin: pfnetman (0.3.0)
plugin: sap (0.2.0)
plugin: uam (0.0.6)
- Resolving "bigip" provider (0.12.3)...
- Checking for provider plugin on https://releases.hashicorp.com...
panic: not a legacy Provider

goroutine 1 [running]:
github.com/hashicorp/terraform/addrs.Provider.LegacyString(...)
        /work/go/goroot/pkg/mod/github.com/hashicorp/terraform@v0.12.18/addrs/provider.go:46
github.com/hashicorp/terraform/plugin/discovery.(*ProviderInstaller).Get(0xc000665c08, 0xc0003f7035, 0x5, 0x0, 0x0, 0x0, 0x0, 0xc000010050, 0x1, 0x1, ...)
        /work/go/goroot/pkg/mod/github.com/hashicorp/terraform@v0.12.18/plugin/discovery/get.go:235 +0x1c42
main.(*PackageCommand).Run(0xc0003aca40, 0xc0000321a0, 0x1, 0x1, 0x0)
        /work/go/goroot/pkg/mod/github.com/hashicorp/terraform@v0.12.18/tools/terraform-bundle/package.go:185 +0xef3
github.com/mitchellh/cli.(*CLI).Run(0xc0003392c0, 0xc000357bf0, 0xe63eec, 0x7)
        /work/go/goroot/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1da
main.main()
        /work/go/goroot/pkg/mod/github.com/hashicorp/terraform@v0.12.18/tools/terraform-bundle/main.go:75 +0x2e6
```

`terraform-bundle` version 0.12.17 seems to be ok

**Comment by mildwonkey** [comment]
Hi all 👋 , thanks for reporting this! Sorry for the crash; I've opened a PR that should fix this. If you're interested, you could build terraform from the branch to test it locally; otherwise this fix will be in the next release.
