### ISSUE TITLE
Terraform Crashed post-destroy

### ISSUE THREAD

**Issue by cdelorme** [hashicorp/terraform#2387]
Running terraform 0.5.3 (b62875a0f01db282a536404b876430ae8e4c1a48+CHANGES) on a jenkins server, crashed while/after running `destroy` from the cli.  It spat out the errors from the destroy beforehand, so it may be related to saving the state to a remote source (s3).

I don't see a place to attach the crash.log, the upload only supports images?

**Comment by phinze** [comment]
@cdelorme can you post the crash log as a [gist](https://gist.github.com)?

**Comment by cdelorme** [comment]
Sure thing: https://gist.github.com/cdelorme/1e4663287abefd890bde

Thanks for the suggestion, I was struggling with the best place to upload it.

**Comment by phinze** [comment]
Relevant backtrace:

```
2015/06/17 19:33:39 terraform-provider-aws: 2015/06/17 19:33:39 [DEBUG] launch configuration describe configuration: autoscaling.DescribeLaunchConfigurationsInput{LaunchConfigurationNames:[]*string{(*string)(0xc208345ae0)}, MaxRecords:(*int64)(nil), NextToken:(*string)(nil), metadataDescribeLaunchConfigurationsInput:autoscaling.metadataDescribeLaunchConfigurationsInput{SDKShapeTraits:false}}
2015/06/17 19:33:39 [DEBUG] root: eval: *terraform.EvalWriteState
2015/06/17 19:33:39 [DEBUG] root: eval: terraform.EvalNoop
2015/06/17 19:33:39 [DEBUG] root: eval: terraform.EvalNoop
2015/06/17 19:33:39 [DEBUG] root: eval: terraform.EvalNoop
2015/06/17 19:33:39 terraform-provider-aws: panic: runtime error: invalid memory address or nil pointer dereference
2015/06/17 19:33:39 terraform-provider-aws: [signal 0xb code=0x1 addr=0x10 pc=0x5323d6]
2015/06/17 19:33:39 terraform-provider-aws: 
2015/06/17 19:33:39 terraform-provider-aws: goroutine 71 [running]:
2015/06/17 19:33:39 terraform-provider-aws: github.com/awslabs/aws-sdk-go/aws.ValidateResponseHandler(0xc20833ee00)
2015/06/17 19:33:39 terraform-provider-aws: 	/opt/gopath/src/github.com/awslabs/aws-sdk-go/aws/handler_functions.go:91 +0x26
2015/06/17 19:33:39 terraform-provider-aws: github.com/awslabs/aws-sdk-go/aws.(*HandlerList).Run(0xc20833ee68, 0xc20833ee00)
2015/06/17 19:33:39 terraform-provider-aws: 	/opt/gopath/src/github.com/awslabs/aws-sdk-go/aws/handlers.go:83 +0x6e
2015/06/17 19:33:39 terraform-provider-aws: github.com/awslabs/aws-sdk-go/aws.(*Request).Send(0xc20833ee00, 0x0, 0x0)
2015/06/17 19:33:39 terraform-provider-aws: 	/opt/gopath/src/github.com/awslabs/aws-sdk-go/aws/request.go:209 +0x1e6
2015/06/17 19:33:39 terraform-provider-aws: github.com/awslabs/aws-sdk-go/service/ec2.(*EC2).DescribeRouteTables(0xc20803b240, 0xc2083d8e40, 0x1, 0x0, 0x0)
2015/06/17 19:33:39 terraform-provider-aws: 	/opt/gopath/src/github.com/awslabs/aws-sdk-go/service/ec2/api.go:3889 +0x5c
2015/06/17 19:33:39 terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.funcÂ·047(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2015/06/17 19:33:39 terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route_table.go:393 +0x19d
2015/06/17 19:33:39 terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsRouteTableRead(0xc20836de60, 0x9501e0, 0xc2080fb110, 0x0, 0x0)
2015/06/17 19:33:39 terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route_table.go:120 +0xfa
2015/06/17 19:33:39 terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc208176b40, 0xc208352810, 0x9501e0, 0xc2080fb110, 0xc20817ec20, 0x0, 0x0)
2015/06/17 19:33:39 terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:209 +0x475
2015/06/17 19:33:39 terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc208174e40, 0xc2083d8040, 0xc208352810, 0x951560, 0x0, 0x0)
2015/06/17 19:33:39 terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:180 +0x1c7
2015/06/17 19:33:39 terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Refresh(0xc20814a0a0, 0xc2083791d0, 0xc208379510, 0x0, 0x0)
2015/06/17 19:33:39 terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/rpc/resource_provider.go:341 +0x73
```

This is an upstream issue, but the good news is that we have already worked with aws-sdk-go maintaners to get it fixed. https://github.com/aws/aws-sdk-go/pull/273

So the next release of Terraform will not crash like this. :+1:
