### ISSUE TITLE
panic: interface conversion: interface {} is nil, not *cloudflare.API

### ISSUE THREAD

**Issue by hazcod** [hashicorp/terraform#23892]
Used v2.3.0 version of provider via terraformer (all):
`CLOUDFLARE_EMAIL='xxx' CLOUDFLARE_TOKEN='xxx' ./terraformer-all-darwin-amd64 import cloudflare --resources='firewall,dns,access' --compact --path-pattern 'cfgenerated/' --verbose`

```
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: panic: interface conversion: interface {} is nil, not *cloudflare.API
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: goroutine 40 [running]:
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/cloudflare.resourceCloudflareAccessRuleRead(0xc0002b43f0, 0x0, 0x0, 0xc0002b43f0, 0x0)
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/cloudflare/resource_cloudflare_access_rule.go:107 +0xdd4
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000135380, 0xc0001624b0, 0x0, 0x0, 0xc00046b7a0, 0xc0001624b0, 0x0)
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:455 +0x119
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0000a8a80, 0x1f36640, 0xc0003ae2a0, 0xc0001622d0, 0xc0000a8a80, 0xc0003ae2a0, 0xc00029dbd0)
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d7
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1c605e0, 0xc0000a8a80, 0x1f36640, 0xc0003ae2a0, 0xc00007e360, 0x0, 0x1f36640, 0xc0003ae2a0, 0xc000142000, 0x88)
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3153 +0x23e
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000de000, 0x1f42960, 0xc00055e780, 0xc00014c400, 0xc000146390, 0x28458f0, 0x0, 0x0, 0x0)
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:995 +0x466
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0000de000, 0x1f42960, 0xc00055e780, 0xc00014c400, 0x0)
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:1275 +0xda6
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000360d0, 0xc0000de000, 0x1f42960, 0xc00055e780, 0xc00014c400)
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:710 +0x9f
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: created by github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2020-01-19T16:00:20.051+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020/01/19 16:00:20 rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: write unix ->/var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin476821522: write: broken pipe"
2020/01/19 16:00:20 rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: write unix ->/var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin476821522: write: broken pipe"
2020/01/19 16:00:20 rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: write unix ->/var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin476821522: write: broken pipe"
2020/01/19 16:00:20 rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: write unix ->/var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin476821522: write: broken pipe"
```

**Comment by hazcod** [comment]
Not sure if related, but if I only use resource `dns`:
```
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: panic: interface conversion: interface {} is nil, not *cloudflare.API
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: goroutine 43 [running]:
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/cloudflare.resourceCloudflareRecordRead(0xc00017e850, 0x0, 0x0, 0xc00017e850, 0x0)
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/cloudflare/resource_cloudflare_record.go:357 +0xae5
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004b0100, 0xc0005d0370, 0x0, 0x0, 0xc000094ea0, 0xc0005d0370, 0x0)
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:455 +0x119
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0000aea70, 0x1f36640, 0xc0000947e0, 0xc0005d0190, 0xc0000aea70, 0xc0000947e0, 0xc0001a9bd0)
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d7
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1c605e0, 0xc0000aea70, 0x1f36640, 0xc0000947e0, 0xc0000b0360, 0x0, 0x1f36640, 0xc0000947e0, 0xc00003c0e0, 0xdd)
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3153 +0x23e
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000de000, 0x1f42960, 0xc00055ea80, 0xc00016a300, 0xc000144360, 0x28458f0, 0x0, 0x0, 0x0)
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:995 +0x466
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0000de000, 0x1f42960, 0xc00055ea80, 0xc00016a300, 0x0)
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:1275 +0xda6
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000c0080, 0xc0000de000, 0x1f42960, 0xc00055ea80, 0xc00016a300)
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:710 +0x9f
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: created by github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2020-01-19T16:06:24.682+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudflare/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020-01-19T16:06:24.684+0100 [DEBUG] plugin: plugin process exited: path=/Users/niels/.terraform.d/plugins/darwin_amd64/terraform-provider-cloudflare_v2.3.0_x4 pid=24515 error="exit status 2"
2020/01/19 16:06:24 rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin936353246: connect: connection refused"
2020/01/19 16:06:24 rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin936353246: connect: connection refused"
2020/01/19 16:06:24 Refreshing state... cloudflare_zone.tfer--ironpeak-002E-services
2020/01/19 16:06:24 Refreshing state... cloudflare_record.tfer--TXT_ironpeak-002E-be_fc0a2cd4ceb7818b8db7c4b4b98bb870
2020/01/19 16:06:24 rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin936353246: connect: connection refused"
2020/01/19 16:06:24 Refreshing state... cloudflare_record.tfer--A_ironpeak-002E-services_e469584fda2002ffaf88ffa02c3fbac0
2020/01/19 16:06:24 rpc error: code = Canceled desc = context canceled
2020/01/19 16:06:24 Refreshing state... cloudflare_record.tfer--CNAME_ironpeak-002E-services_0265e587a4902e479bda11421475326d
2020/01/19 16:06:24 rpc error: code = Canceled desc = context canceled
2020/01/19 16:06:24 rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin936353246: connect: connection refused"
2020/01/19 16:06:24 rpc error: code = Canceled desc = context canceled
2020/01/19 16:06:24 rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin936353246: connect: connection refused"
2020/01/19 16:06:24 rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin936353246: connect: connection refused"
2020/01/19 16:06:24 rpc error: code = Canceled desc = latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin936353246: connect: connection refused"
2020/01/19 16:06:24 rpc error: code = Canceled desc = latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin936353246: connect: connection refused"
2020/01/19 16:06:24 rpc error: code = Canceled desc = latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin936353246: connect: connection refused"
2020/01/19 16:06:24 rpc error: code = Canceled desc = latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin936353246: connect: connection refused"
2020/01/19 16:06:24 rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin936353246: connect: connection refused"
2020/01/19 16:06:24 rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin936353246: connect: connection refused"
2020/01/19 16:06:24 rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin936353246: connect: connection refused"
2020/01/19 16:06:24 rpc error: code = Canceled desc = context canceled
2020/01/19 16:06:24 rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin936353246: connect: connection refused"
2020/01/19 16:06:24 rpc error: code = Canceled desc = latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/plugin936353246: connect: connection refused"
```
