### ISSUE TITLE
go 1.14 compatibility issue

### ISSUE THREAD

**Issue by chenrui333** [hashicorp/terraform#24309]
### Current issue with build terraform with go1.14

Right now, the terraform build failed on Majove and HighSierra machines (PR ref, https://github.com/Homebrew/homebrew-core/pull/51172).

<details>
<summary>Runtime failure after build with go1.14 on Mojave machine</summary>
$ terraform version
runtime: netpoll: break fd ready for -2
fatal error: runtime: netpoll: break fd ready for something unexpected

runtime stack:
runtime.throw(0x2996440, 0x39)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:1112 +0x72
runtime.netpoll(0x11d1dc, 0xc000054001)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/netpoll_kqueue.go:140 +0x30a
runtime.findrunnable(0xc00005e000, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:2323 +0x72b
runtime.schedule()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:2520 +0x2fc
runtime.goschedImpl(0xc000000a80)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:2705 +0xd6
runtime.gosched_m(0xc000000a80)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:2713 +0x34
runtime.mcall(0x80000)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [runnable, locked to thread]:
github.com/ChrisTrenkamp/goxpath/parser.init()
	/private/tmp/terraform-20200306-3557-1qol1ba/terraform-0.12.23/pkg/mod/github.com/!chris!trenkamp/goxpath@v0.0.0-20170922090931-c385f95c6022/parser/parser.go:48 +0x5ef

goroutine 18 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00009ee60)
	/private/tmp/terraform-20200306-3557-1qol1ba/terraform-0.12.23/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
	/private/tmp/terraform-20200306-3557-1qol1ba/terraform-0.12.23/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:32 +0x57
  1 pick c2e735fd951 terraform 0.12.23¬
  5 # This is a combination of 2 commits.¬
</details>

### Expectation

Fix the golang build compatibility issue with go 1.14

**Comment by chenrui333** [comment]
duplicates #24287
