### ISSUE TITLE
Error: rpc error: code = Unavailable desc = transport is closing / DNS

### ISSUE THREAD

**Issue by jenslink** [hashicorp/terraform#24749]
### Terraform Version

```
terraform -v
Terraform v0.12.24
+ provider.aws v2.58.0
+ provider.dns v2.2.0
```

### Terraform Configuration Files

This happens with a freshly "installed" terraform. No special config

```hcl
...
```

### Debug Output

dns_a_record_set.test5: Creating...

Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: invalid memory address or nil pointer dereference
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe484d9]
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: 
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: goroutine 44 [running]:
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: github.com/terraform-providers/terraform-provider-dns/vendor/github.com/miekg/dns.(*Msg).Insert(0xc0000bb708, 0xc0000bb5e8, 0x1, 0x1)
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-dns/vendor/github.com/miekg/dns/update.go:71 +0x89
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: github.com/terraform-providers/terraform-provider-dns/dns.resourceDnsARecordSetUpdate(0xc0002e4230, 0xf0cba0, 0xc00060c1e0, 0x114ba00, 0xc0000cdca0)
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-dns/dns/resource_dns_a_record_set.go:114 +0x783
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: github.com/terraform-providers/terraform-provider-dns/dns.resourceDnsARecordSetCreate(0xc0002e4230, 0xf0cba0, 0xc00060c1e0, 0x2, 0x1cec220)
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-dns/dns/resource_dns_a_record_set.go:54 +0x5b
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: github.com/terraform-providers/terraform-provider-dns/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc00015ef00, 0xc000163d60, 0xc0000cdca0, 0xf0cba0, 0xc00060c1e0, 0xc000390101, 0xc0003b4bf8, 0xf94320)
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-dns/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:286 +0x3b4
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: github.com/terraform-providers/terraform-provider-dns/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc00015f400, 0xc0000bba58, 0xc000163d60, 0xc0000cdca0, 0xc000123b88, 0xc0000c2658, 0xf962a0)
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-dns/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:285 +0x18f
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: github.com/terraform-providers/terraform-provider-dns/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00015c548, 0x1378300, 0xc0003898c0, 0xc00008ae40, 0xc00015c548, 0xc0003898c0, 0xc00057cbd0)
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-dns/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:885 +0x894
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: github.com/terraform-providers/terraform-provider-dns/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10c8520, 0xc00015c548, 0x1378300, 0xc0003898c0, 0xc0001639f0, 0x0, 0x1378300, 0xc0003898c0, 0xc00003c0a0, 0x9d)
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-dns/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3217 +0x23e
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: github.com/terraform-providers/terraform-provider-dns/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000552900, 0x13848c0, 0xc000096f00, 0xc000475800, 0xc00014eea0, 0x1cc0ae0, 0x0, 0x0, 0x0)
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-dns/vendor/google.golang.org/grpc/server.go:966 +0x470
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: github.com/terraform-providers/terraform-provider-dns/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000552900, 0x13848c0, 0xc000096f00, 0xc000475800, 0x0)
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-dns/vendor/google.golang.org/grpc/server.go:1245 +0xd25
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: github.com/terraform-providers/terraform-provider-dns/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00003a1f0, 0xc000552900, 0x13848c0, 0xc000096f00, 0xc000475800)
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-dns/vendor/google.golang.org/grpc/server.go:685 +0x9f
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: created by github.com/terraform-providers/terraform-provider-dns/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-dns/vendor/google.golang.org/grpc/server.go:683 +0xa1
2020-04-23T13:20:56.418+0200 [DEBUG] plugin: plugin process exited: path=/home/jens/test/.terraform/plugins/linux_amd64/terraform-provider-dns_v2.2.0_x4 pid=19943 error="exit status 2"
2020/04/23 13:20:56 [DEBUG] dns_a_record_set.test5: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/04/23 13:20:56 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/04/23 13:20:56 [TRACE] EvalMaybeTainted: dns_a_record_set.test5 encountered an error during creation, so it is now marked as tainted
2020/04/23 13:20:56 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/04/23 13:20:56 [TRACE] EvalWriteState: removing state object for dns_a_record_set.test5
2020/04/23 13:20:56 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2020/04/23 13:20:56 [TRACE] EvalApplyProvisioners: dns_a_record_set.test5 has no state, so skipping provisioners
2020/04/23 13:20:56 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/04/23 13:20:56 [TRACE] EvalMaybeTainted: dns_a_record_set.test5 encountered an error during creation, so it is now marked as tainted
2020/04/23 13:20:56 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/04/23 13:20:56 [TRACE] EvalWriteState: removing state object for dns_a_record_set.test5
2020/04/23 13:20:56 [TRACE] <root>: eval: *terraform.EvalIf
2020/04/23 13:20:56 [TRACE] <root>: eval: *terraform.EvalIf
2020/04/23 13:20:56 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2020/04/23 13:20:56 [TRACE] <root>: eval: *terraform.EvalApplyPost
2020/04/23 13:20:56 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/04/23 13:20:56 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/04/23 13:20:56 [TRACE] [walkApply] Exiting eval tree: dns_a_record_set.test5
2020/04/23 13:20:56 [TRACE] vertex "dns_a_record_set.test5": visit complete
2020/04/23 13:20:56 [TRACE] dag/walk: upstream of "provider.dns (close)" errored, so skipping
2020/04/23 13:20:56 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/04/23 13:20:56 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/04/23 13:20:56 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2020/04/23 13:20:56 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2020/04/23 13:20:56 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2020/04/23 13:20:56 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/04/23 13:20:56 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2020-04-23T13:20:56.424+0200 [DEBUG] plugin: plugin exited

### Crash Output

See https://gist.github.com/jenslink/185a380a26701a27b466d849f922a52d

### Expected Behavior

No crash and the DNS record added to the zone update.  Or at least some clear output what  went wrong. 

### Actual Behavior

terraform crashes

### Additional Context

I'm quite new to terraform and what I'm trying to steup some AWS instances and put the public
IP address into DNS using the DNS module. It doesn't even try to connect to the DNS Server. 

When I'm using a IP Address instead of a variable it works.

**Comment by jenslink** [comment]
Found the reason for the crash:  I didn't apply a public IP address to the ec2 instance so it looks like the variable was empty / undefined. Still shouldn't crash and provide a proper error message.

**Comment by danieldreier** [comment]
Thanks for reporting this! I looked at the log output you provided, and the crash you are showing seems to happening in the DNS provider rather than Terraform core:

```shellsession
panic: runtime error: invalid memory address or nil pointer dereference
2020-04-23T13:20:56.416+0200 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe484d9]
```

The `plugin.terraform-provider-dns_v2.2.0_x4` part tells me that the DNS provider binary crashed, so I'm going to label it as a provider issue, and the HashiBot will shortly migrate it over to the provider's repository so that they can investigate it.

Thanks again for reporting this, and please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
