### ISSUE TITLE
panic: invalid specification "~>1.16": a space separator is required after the operator "~>"

### ISSUE THREAD

**Issue by wdec** [hashicorp/terraform#25177]
### Terraform Version

```
0.13.0-beta1
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 0.13.0"
#  experiments = [variable_validation]
}

provider "vsphere" {
  user           = var.vCentreDC.vCentreUser
  password       = var.vCentreDC.vCentrePassword
  vsphere_server = var.vCentreDC.vCentreAddress

  # If you have a self-signed cert
  allow_unverified_ssl = true
  version = "~>1.16"
}
```

### Crash Output

```
Initializing the backend...
panic: invalid specification "~>1.16": a space separator is required after the operator "~>"

goroutine 1 [running]:
github.com/hashicorp/terraform/internal/getproviders.MustParseVersionConstraints(0xc00012c10a, 0x6, 0x1, 0xc00012c10a, 0x6)
	/home/circleci/project/project/internal/getproviders/types.go:96 +0x80
github.com/hashicorp/terraform/configs.(*Config).addProviderRequirements(0xc000501520, 0xc00011a9f0, 0x100, 0xc000030000, 0x100)
	/home/circleci/project/project/configs/config.go:233 +0x8d1
github.com/hashicorp/terraform/configs.(*Config).ProviderRequirements(...)
	/home/circleci/project/project/configs/config.go:177
github.com/hashicorp/terraform/command.(*InitCommand).getProviders(0xc00014f340, 0xc000501520, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/command/init.go:416 +0x77
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc00014f340, 0xc00003a1a0, 0x1, 0x1, 0xc00007ee40)
	/home/circleci/project/project/command/init.go:282 +0x12f7
github.com/mitchellh/cli.(*CLI).Run(0xc00003c8c0, 0xc00003c8c0, 0xc00063fd48, 0x1)
	/home/circleci/project/project/vendor/github.com/mitchellh/cli/cli.go:255 +0x1da
main.wrappedMain(0x0)
	/home/circleci/project/project/main.go:275 +0xc90
main.realMain(0x0)
	/home/circleci/project/project/main.go:106 +0xde
main.main()
	/home/circleci/project/project/main.go:42 +0x3a
```

### Expected Behavior
Shouldn't crash. v.0.12.x accepts the version without the space.

### Actual Behavior
Terraform crashed

### Steps to Reproduce

1. `terraform init` with the above config

**Comment by apparentlymart** [comment]
Thanks for reporting this, @wdec!

It looks like that was intended to be a normal error message rather than a "panic", but it _panicking_ is definitely a bug.

**Comment by apparentlymart** [comment]
Having looked a bit deeper, I see that this is happening because there is some disagreement in our `configs` package about which version constraint parser is being used. Some parts are using the new parser which produces better error messages but is also slightly stricter, while other parts are still using the old parser which produces low-quality error messages and is more permissive.

I have a quick fix to get rid of the panic and return a real error message in that codepath, but I think the better answer here is to make all of the provider version constraint parsing use the same parser and consistently return the same error messages.
