### ISSUE TITLE
Terraform crash on version validation

### ISSUE THREAD

**Issue by quentin9696** [hashicorp/terraform#25231]
### Terraform Version

```
Terraform v0.13.0-beta1
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.12.24"

  required_providers {
    aws = "~>2.54"
  }
}

```

### Crash Output

```
panic: invalid specification "~>2.54": a space separator is required after the operator "~>"

goroutine 1 [running]:
github.com/hashicorp/terraform/internal/getproviders.MustParseVersionConstraints(0xc00070c380, 0x6, 0x1, 0xc00070c380, 0x6)
    /home/circleci/project/project/internal/getproviders/types.go:96 +0x80
github.com/hashicorp/terraform/configs.(*Config).addProviderRequirements(0xc000d3ec30, 0xc004186240, 0x5, 0x0, 0x195e553)
    /home/circleci/project/project/configs/config.go:201 +0x188
github.com/hashicorp/terraform/configs.(*Config).ProviderRequirements(...)
    /home/circleci/project/project/configs/config.go:177
github.com/hashicorp/terraform/command.(*InitCommand).getProviders(0xc0005a8a80, 0xc000d3ec30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/circleci/project/project/command/init.go:416 +0x77
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc0005a8a80, 0xc00012c030, 0x0, 0x0, 0xc000116e80)
    /home/circleci/project/project/command/init.go:282 +0x12f7
github.com/mitchellh/cli.(*CLI).Run(0xc000164640, 0xc000164640, 0xc0006bfd48, 0x1)
    /home/circleci/project/project/vendor/github.com/mitchellh/cli/cli.go:255 +0x1da
main.wrappedMain(0x0)
    /home/circleci/project/project/main.go:275 +0xc90
main.realMain(0x0)
    /home/circleci/project/project/main.go:106 +0xde
main.main()
    /home/circleci/project/project/main.go:42 +0x3a
```
### Expected Behavior

It should display only a warn message, or an error, not a `panic`.

### Steps to Reproduce

1. `terraform init`

**Comment by jbardin** [comment]
Thanks for filing the issue @quentin9696, we're tracking this in #25177
