### ISSUE TITLE
0.13.0-beta2 crash report

### ISSUE THREAD

**Issue by tycarac** [hashicorp/terraform#25366]
### Terraform Version

``` 
Terraform v0.13.0-beta2
```

### Terraform Configuration Files

```
hcl https://1drv.ms/u/s!AjA715bdFDs48CF142ZuUVD1IpOW?e=7nuVZT
```

### Crash Output

Placed two crash logs with two different command line inputs to test if crash is repeatable.  It was.

### Steps to Reproduce

terraform init
### Additional Context

I am just learning Terraform and so may have invalid syntax.

**Comment by alisdair** [comment]
crash.log:

```
2020/06/24 16:57:43 [INFO] Terraform version: 0.13.0 beta2 
2020/06/24 16:57:43 [INFO] Go runtime version: go1.14.2
2020/06/24 16:57:43 [INFO] CLI args: []string{"C:\\Bin\\terraform.exe", "init", "--upgrade"}
2020/06/24 16:57:43 [DEBUG] Attempting to open CLI config file: C:\Users\Chris\AppData\Roaming\terraform.rc
2020/06/24 16:57:43 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/06/24 16:57:43 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/06/24 16:57:43 [DEBUG] ignoring non-existing provider search directory C:\Users\Chris\AppData\Roaming\terraform.d\plugins
2020/06/24 16:57:43 [DEBUG] ignoring non-existing provider search directory C:\Users\Chris\AppData\Roaming\HashiCorp\Terraform\plugins
2020/06/24 16:57:43 [INFO] CLI command args: []string{"init", "--upgrade"}
panic: not a string

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.AsString(0x2d28f40, 0x4167678, 0x231ba40, 0x4167200, 0x27131ae, 0x6)
	/home/circleci/project/project/vendor/github.com/zclconf/go-cty/cty/value_ops.go:1181 +0x1aa
github.com/hashicorp/terraform/configs.decodeRequiredProvidersBlock(0xc000360000, 0x272c6da, 0x12, 0x1, 0x0)
	/home/circleci/project/project/configs/provider_requirements.go:75 +0xe2a
github.com/hashicorp/terraform/configs.(*Parser).loadConfigFile(0xc00035e0a0, 0xc0004e8788, 0x7, 0x0, 0x1, 0x0, 0x0, 0x4)
	/home/circleci/project/project/configs/parser_config.go:76 +0x1b83
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigFile(...)
	/home/circleci/project/project/configs/parser_config.go:22
github.com/hashicorp/terraform/configs.(*Parser).loadFiles(0xc00035e0a0, 0xc00035e140, 0x2, 0x2, 0x0, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/configs/parser_config_dir.go:77 +0x349
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigDir(0xc00035e0a0, 0x270e485, 0x1, 0x0, 0x1, 0x2, 0x0)
	/home/circleci/project/project/configs/parser_config_dir.go:37 +0x128
github.com/hashicorp/terraform/command.(*Meta).loadSingleModule(0xc0000a8000, 0x270e485, 0x1, 0x0, 0x0, 0x0, 0xe)
	/home/circleci/project/project/command/meta_config.go:113 +0x13c
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc0000a8000, 0xc0000560a0, 0x1, 0x2, 0xc0002cb560)
	/home/circleci/project/project/command/init.go:151 +0xa59
github.com/mitchellh/cli.(*CLI).Run(0xc000453b80, 0xc000453b80, 0xc00063fd48, 0x1)
	/home/circleci/project/project/vendor/github.com/mitchellh/cli/cli.go:255 +0x1e1
main.wrappedMain(0x0)
	/home/circleci/project/project/main.go:275 +0xc97
main.realMain(0x0)
	/home/circleci/project/project/main.go:106 +0xe5
main.main()
	/home/circleci/project/project/main.go:42 +0x41
```

main.tf:

```hcl
/* Bootstrap terraform with creating the AWS S3 resources needed for tracking/maintaining state.
 */
terraform {
  required_version = '~> 0.13.0'
  required_providers {
    aws = {
      source  = 'hashicorp/aws'
      version = '~> 2.67'
    }
  }
}

provider 'aws' {
  region = var.region
}

resource 'aws_s3_bucket_public_access_block' 'terraform_state' {
  bucket              = aws_s3_bucket.terraform_state.id
  block_public_acls   = true
  block_public_policy = true
  tags = {
    Name = 'table-locks'
    duty = 'devops'
  }
}

resource 'aws_s3_bucket_public_access_block' 'log_sink' {
  bucket              = aws_s3_bucket.log-sink.id
  block_public_acls   = true
  block_public_policy = true
}

resource 'aws_s3_bucket' 'terraform_state' {
  bucket = 'tycarac-devops'
  acl    = 'private'
  lifecycle {
    prevent_destroy = true
  }
  versioning {
    enabled    = true
    mfa_delete = false
  }
  logging {
    target_bucket = aws_s3_bucket.log-sink.id
    target_prefix = 'log/'
  }
  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = 'AES256'
      }
    }
  }
}

resource 'aws_s3_bucket' 'log-sink' {
  bucket = 'tycarac-logging'
  acl    = 'log-delivery-write'
  lifecycle {
    prevent_destroy = true
  }
  lifecycle_rule {
    id      = 'log'
    enabled = true
    prefix  = 'log/'
    expiration {
      days = 65
    }
    tags = {
      product   = 'devops'
      autoclean = true
    }
  }
  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = 'AES256'
      }
    }
  }
}

resource 'aws_dynamodb_table' 'tycarac-devops-locks' {
   name = 'terraform-lock'
   hash_key = 'LockID'
   read_capacity = 5
   write_capacity = 5

   attribute {
      name = 'LockID'
      type = 'S'
   }

   tags = {
     Name = 'Terraform Lock Table'
   }
}
```

**Comment by alisdair** [comment]
Thanks for reporting this crash! There's a PR fixing it at #25369.

The underlying problem here is that your configuration is using single quotes instead of double quotes for strings. This is not valid HCL. If you switch to double quoted strings, hopefully you should be able to make some progress.

**Comment by tycarac** [comment]
Thanks for the feedback.
