### ISSUE TITLE
Crash when overriding the back-end locally

### ISSUE THREAD

**Issue by sdebruyn** [hashicorp/terraform#25953]
### Terraform Version
```
➜ terraform -v
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/azuread v0.11.0
+ provider registry.terraform.io/hashicorp/azurerm v2.23.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
```

### Terraform Configuration Files
```terraform
terraform {
  backend "azurerm" {}
}
```

### Debug Output
```
Initializing modules...

Initializing the backend...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2bfc6e5]

goroutine 1 [running]:
github.com/hashicorp/terraform/command.(*InitCommand).backendConfigOverrideBody(0xc0005abc00, 0x32d6bbd, 0xf, 0xc000225f80, 0xc000915530, 0xc00059b650, 0x29, 0x0, 0x0, 0x17762fa700000000)
	github.com/hashicorp/terraform/command/init.go:862 +0x8b5
github.com/hashicorp/terraform/command.(*InitCommand).initBackend(0xc0005abc00, 0xc0009ab4d0, 0x32d6bbd, 0xf, 0xc000225f80, 0x1, 0x0, 0x0, 0x0, 0xc000121500, ...)
	github.com/hashicorp/terraform/command/init.go:374 +0x4a6
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc0005abc00, 0xc0001101a0, 0x1, 0x1, 0xc0007900f0)
	github.com/hashicorp/terraform/command/init.go:227 +0xeb1
github.com/mitchellh/cli.(*CLI).Run(0xc0000ca140, 0xc0000ca140, 0xc0004e7d48, 0x1)
	github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1da
main.wrappedMain(0x0)
	github.com/hashicorp/terraform/main.go:275 +0xc90
main.realMain(0x0)
	github.com/hashicorp/terraform/main.go:106 +0xde
main.main()
	github.com/hashicorp/terraform/main.go:42 +0x3a



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Crash Output
https://gist.github.com/sdebruyn/a56224ba20d511c38747b77c4de51e5a

### Expected Behavior
Terraform initialized

### Actual Behavior
Crash

### Steps to Reproduce
1. Create a file with the back-end config for azurerm like below
1. `terraform init -backend-config=path/to/file`

```
resource_group_name = "rgname"
storage_account_name = "saname"
container_name = "containername"
key = "filename"
````

**Comment by alisdair** [comment]
This bug should be fixed as part of #25960 and will be released as part of Terraform 0.13.1.
