### ISSUE TITLE
terraform crash on Datadog provider import 

### ISSUE THREAD

**Issue by agupt** [hashicorp/terraform#26012]
### Version 

```
Terraform v0.12.29
+ provider.datadog v2.12.1

Your version of Terraform is out of date! The latest version
is 0.13.1. You can update by downloading from https://www.terraform.io/downloads.html
```

### Error Log

```
Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1bddcf1]
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1:
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: goroutine 25 [running]:
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: github.com/terraform-providers/terraform-provider-datadog/datadog.buildTerraformTemplateVariables(0xc0004598b0, 0x1fa2ab9)
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: 	github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_dashboard.go:296 +0x291
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: github.com/terraform-providers/terraform-provider-datadog/datadog.resourceDatadogDashboardRead(0xc0000f8070, 0x1d14040, 0xc00009e980, 0x1922c30, 0xc0000f8070)
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: 	github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_dashboard.go:152 +0x463
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: github.com/terraform-providers/terraform-provider-datadog/datadog.resourceDatadogDashboardImport(0xc0000f8070, 0x1d14040, 0xc00009e980, 0x11, 0xc000033d58, 0x307b701, 0x0, 0x8)
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: 	github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_dashboard.go:184 +0x43
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ImportState(0xc0000f2000, 0xc000799ad0, 0xc0004ac100, 0xb, 0x13bcd14, 0xc0002102c0, 0x20, 0x20, 0x1efd540)
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: 	github.com/hashicorp/terraform-plugin-sdk@v1.10.0/helper/schema/provider.go:390 +0x28b
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ImportResourceState(0xc0001140b8, 0x2252480, 0xc00089c060, 0xc000118140, 0xc0001140b8, 0xc00089c060, 0xc00083eb78)
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: 	github.com/hashicorp/terraform-plugin-sdk@v1.10.0/internal/helper/plugin/grpc_provider.go:953 +0xec
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ImportResourceState_Handler(0x1f3fa00, 0xc0001140b8, 0x2252480, 0xc00089c060, 0xc00010c420, 0x0, 0x2252480, 0xc00089c060, 0xc0002102c0, 0x20)
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: 	github.com/hashicorp/terraform-plugin-sdk@v1.10.0/internal/tfplugin5/tfplugin5.pb.go:3323 +0x217
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000782c00, 0x225e8e0, 0xc000783980, 0xc0007ac200, 0xc000203d70, 0x2cca4f8, 0x0, 0x0, 0x0)
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: 	google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
2020-08-26T17:14:54.325-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: google.golang.org/grpc.(*Server).handleStream(0xc000782c00, 0x225e8e0, 0xc000783980, 0xc0007ac200, 0x0)
2020-08-26T17:14:54.326-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: 	google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
2020-08-26T17:14:54.326-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000036530, 0xc000782c00, 0x225e8e0, 0xc000783980, 0xc0007ac200)
2020-08-26T17:14:54.326-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: 	google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
2020-08-26T17:14:54.326-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-08-26T17:14:54.326-0700 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: 	google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
2020-08-26T17:14:54.328-0700 [DEBUG] plugin: plugin process exited: path=/Users/amgupta/code/flex-datadog/flex_runtime/dashboards/hosted_flex/.terraform/plugins/darwin_amd64/terraform-provider-datadog_v2.12.1 pid=78308 error="exit status 2"
2020/08/26 17:14:54 [ERROR] <root>: eval: *terraform.EvalImportState, err: rpc error: code = Unavailable desc = transport is closing
2020/08/26 17:14:54 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/08/26 17:14:54 [TRACE] [walkImport] Exiting eval tree: datadog_dashboard.runtime_hosted_flex_alb (import id "9ge-4n4-2rt")
2020/08/26 17:14:54 [TRACE] vertex "datadog_dashboard.runtime_hosted_flex_alb (import id \"[dashboard id redacted]\")": visit complete
2020/08/26 17:14:54 [TRACE] dag/walk: upstream of "provider.datadog (close)" errored, so skipping
2020/08/26 17:14:54 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/08/26 17:14:54 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2020-08-26T17:14:54.330-0700 [DEBUG] plugin: plugin exited
```

**Comment by alisdair** [comment]
Hi @agupt, thanks for reporting this crash. It looks like it's coming from the `datadog` provider rather than Terraform itself, so [please report it at the provider repository here](https://github.com/DataDog/terraform-provider-datadog/issues/new). I'm closing this issue as I believe this is not a Terraform core bug.
