### ISSUE TITLE
Crash when using depends_on with data source

### ISSUE THREAD

**Issue by alisdair** [hashicorp/terraform#26300]
### Terraform Version

Build from commit 6d7904c

```
Terraform v0.14.0-dev
+ provider registry.terraform.io/hashicorp/archive v1.3.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
```

### Terraform Configuration Files

```terraform
resource "null_resource" "create_file" {
  provisioner "local-exec" {
    command = "mkdir -p files && echo foo > files/test.txt"
  }
}

data "archive_file" "foo" {
  depends_on = [null_resource.create_file]
  type        = "zip"
  source_dir  = "files"
  output_path = "files.zip"
}
```

### Debug Output

[Gist](https://gist.github.com/alisdair/41b3d884a275f3d15b44dcd746d8fd01)

### Crash Output

[Gist](https://gist.github.com/alisdair/41b3d884a275f3d15b44dcd746d8fd01)

### Expected Behavior

I get a nice zip file

### Actual Behavior

Crash:

```
panic: Failed to serialize resource instance in state: Instance data.archive_file.foo has status ObjectPlanned, which cannot be saved in state.

goroutine 8 [running]:
github.com/hashicorp/terraform/states/statefile.StatesMarshalEqual(0xc0000101b0, 0xc0000101a0, 0x0)
	/Users/alisdair/code/terraform/states/statefile/marshal_equal.go:31 +0x23b
github.com/hashicorp/terraform/states/statemgr.(*Filesystem).writeState(0xc000216600, 0xc000010170, 0x0, 0x0, 0x0)
	/Users/alisdair/code/terraform/states/statemgr/filesystem.go:201 +0x507
github.com/hashicorp/terraform/states/statemgr.(*Filesystem).WriteState(0xc000216600, 0xc000010170, 0x0, 0x0)
	/Users/alisdair/code/terraform/states/statemgr/filesystem.go:136 +0x7f
github.com/hashicorp/terraform/states/statemgr.WriteAndPersist(0xd4a8f90, 0xc000216600, 0xc000010170, 0xd4a8f90, 0xc000216600)
	/Users/alisdair/code/terraform/states/statemgr/helper.go:48 +0x3f
github.com/hashicorp/terraform/backend/local.(*Local).opApply(0xc000120f70, 0x38d6dc0, 0xc0002a7480, 0x38d6dc0, 0xc0002a74c0, 0xc0005b6460, 0xc0002a7440)
	/Users/alisdair/code/terraform/backend/local/backend_apply.go:171 +0x733
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc0006002f0, 0xc000600300, 0xc000600310, 0xc000120f70, 0xc0006002e0, 0x38d6dc0, 0xc0002a7480, 0x38d6dc0, 0xc0002a74c0, 0xc0005b6460, ...)
	/Users/alisdair/code/terraform/backend/local/backend.go:340 +0xe8
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
	/Users/alisdair/code/terraform/backend/local/backend.go:334 +0x366
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -auto-approve`

### Additional Context

Hi @jbardin 

### References

Discovered when reproducing #26298. This configuration works with 0.13.3.

**Comment by alisdair** [comment]
Same stack trace as #25463, so probably related.

**Comment by jbardin** [comment]
I don't think this is related to 25463.
I already have this fixed in a working branch, so assigning to myself, as it will be fixed as part of a larger change.

**Comment by jbardin** [comment]
Fixed in master
