### ISSUE TITLE
Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by UltTransformer** [hashicorp/terraform#26349]
panic: runtime error: invalid memory address or nil pointer dereference
2020-09-23T11:18:54.400+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1337a8e]
2020-09-23T11:18:54.400+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: 
2020-09-23T11:18:54.400+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: goroutine 67 [running]:
2020-09-23T11:18:54.400+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: net/http.(*Client).do(0xc0002622e0, 0x0, 0x0, 0x0, 0x0)
2020-09-23T11:18:54.400+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1:     net/http/client.go:595 +0xae
2020-09-23T11:18:54.400+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: net/http.(*Client).Do(...)
2020-09-23T11:18:54.400+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1:     net/http/client.go:586
2020-09-23T11:18:54.400+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client.(*RestConnector).Invoke(0xc0002622d0, 0x2815a7d, 0x44, 0x27be708, 0x4, 0x2a398c0, 0xc000163ee0, 0xc000579830, 0x0, 0x0, ...)
2020-09-23T11:18:54.400+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1:     github.com/vmware/vsphere-automation-sdk-go/runtime@v0.3.1/protocol/client/RestConnector.go:232 +0x40c
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/sites/enforcement_points.(*DefaultTransportZonesClient).Invoke(0xc0000c8000, 0xc000579830, 0x2815a7d, 0x44, 0x27be708, 0x4, 0x2a398c0, 0xc000163ee0, 0x0, 0x0, ...)
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1:     github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.4.0/infra/sites/enforcement_points/DefaultTransportZonesClient.go:154 +0xc2
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/sites/enforcement_points.(*DefaultTransportZonesClient).List(0xc0000c8000, 0x27c1adf, 0x7, 0xc0007181a0, 0x14, 0x0, 0xc0006c46a0, 0x0, 0x0, 0xc0006c46a0, ...)
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1:     github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.4.0/infra/sites/enforcement_points/DefaultTransportZonesClient.go:135 +0x6f8
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: github.com/vmware/terraform-provider-nsxt/nsxt.dataSourceNsxtPolicyTransportZoneRead(0xc00015a3f0, 0x272f540, 0xc0005f6720, 0xc00015a3f0, 0x0)
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1:     github.com/vmware/terraform-provider-nsxt/nsxt/data_source_nsxt_policy_transport_zone.go:115 +0xc1a
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc000471050, 0xc00031ca20, 0x272f540, 0xc0005f6720, 0xc0003eba30, 0x1, 0x0)
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1:     github.com/hashicorp/terraform-plugin-sdk@v1.12.0/helper/schema/resource.go:403 +0x88
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc0000bc000, 0xc0000e1ad0, 0xc00031ca20, 0xc00031ca20, 0x0, 0x0)
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1:     github.com/hashicorp/terraform-plugin-sdk@v1.12.0/helper/schema/provider.go:451 +0x8f
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc0000a2620, 0x2a63b20, 0xc000266720, 0xc0002a43c0, 0xc0000a2620, 0xc000266720, 0xc0007ccb78)
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1:     github.com/hashicorp/terraform-plugin-sdk@v1.12.0/internal/helper/plugin/grpc_provider.go:1036 +0x42d
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler(0x2751b80, 0xc0000a2620, 0x2a63b20, 0xc000266720, 0xc0005f6ae0, 0x0, 0x2a63b20, 0xc000266720, 0xc000040300, 0x7b)
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1:     github.com/hashicorp/terraform-plugin-sdk@v1.12.0/internal/tfplugin5/tfplugin5.pb.go:3341 +0x214
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00008af00, 0x2a709a0, 0xc00008b680, 0xc000184500, 0xc000173a40, 0x3248b30, 0x0, 0x0, 0x0)
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1:     google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: google.golang.org/grpc.(*Server).handleStream(0xc00008af00, 0x2a709a0, 0xc00008b680, 0xc000184500, 0x0)
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1:     google.golang.org/grpc@v1.27.1/server.go:1313 +0xd34
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00009c400, 0xc00008af00, 0x2a709a0, 0xc00008b680, 0xc000184500)
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1:     google.golang.org/grpc@v1.27.1/server.go:722 +0xa5
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-09-23T11:18:54.401+0200 [DEBUG] plugin.terraform-provider-nsxt_v3.0.1:     google.golang.org/grpc@v1.27.1/server.go:720 +0xa5
2020-09-23T11:18:54.403+0200 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/terraform-providers/nsxt/3.0.1/darwin_amd64/terraform-provider-nsxt_v3.0.1 pid=2514 error="exit status 2"
2020/09/23 11:18:54 [ERROR] eval: *terraform.evalReadDataRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/09/23 11:18:54 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/09/23 11:18:54 [TRACE] [walkRefresh] Exiting eval tree: data.nsxt_policy_transport_zone.TZ
2020/09/23 11:18:54 [TRACE] vertex "data.nsxt_policy_transport_zone.TZ": visit complete
2020/09/23 11:18:54 [TRACE] vertex "data.nsxt_policy_transport_zone.TZ": dynamic subgraph encountered errors
2020/09/23 11:18:54 [TRACE] vertex "data.nsxt_policy_transport_zone.TZ": visit complete
2020/09/23 11:18:54 [TRACE] vertex "data.nsxt_policy_transport_zone.TZ (expand)": dynamic subgraph encountered errors
2020/09/23 11:18:54 [TRACE] vertex "data.nsxt_policy_transport_zone.TZ (expand)": visit complete
2020/09/23 11:18:54 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/terraform-providers/nsxt\"] (close)" errored, so skipping
2020/09/23 11:18:54 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/09/23 11:18:54 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/09/23 11:18:54 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2020-09-23T11:18:54.404+0200 [DEBUG] plugin: plugin exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by qlikcoe** [comment]
Hmm, this is close to what we're getting for the `hashicorp/random`: 

```
Failed to retrieve schema from provider
"registry.terraform.io/hashicorp/random": rpc error: code = Unavailable desc =
connection error: desc = "transport: authentication handshake failed: read
unix @->/tmp/plugin711995525: read: connection reset by peer"
```

**Comment by pselle** [comment]
Hello,
Apologies for the delay. To better understand the issue & make it easier to reproduce for anyone else would you mind sharing more details? e.g.

 - version of Terrafom
 - full output (stdout + stderr) from terraform commands you ran (minus any secrets)
 - [debug log](https://github.com/hashicorp/terraform/blob/master/website/source/docs/internals/debugging.html.md#debugging-terraform) from terraform commands you ran (minus any secrets)
 - reproduction steps

The issue template has these details to help us replicate issues to work towards solving them. I'm not sure how this issue didn't get tagged with `bug` (maybe because the issue template wasn't used?).

Thanks.
