### ISSUE TITLE
Teraform plan fails with azurerm and site_config in function_app resource v.0.14.0-beta1

### ISSUE THREAD

**Issue by romeomorcia** [hashicorp/terraform#26633]
### Terraform Version
```
Terraform v0.14.0-beta1
+ provider registry.terraform.io/hashicorp/azurerm v2.31.0
```

### Terraform Configuration Files

```terraform
variable "sensitiveString" {
  type = string
  default = "thisIsNothing"
  sensitive = true
}

resource "azurerm_function_app" "afapp" {
  name                      = "someName"
  location                  = azurerm_resource_group.rg.location
  resource_group_name       = azurerm_resource_group.rg.name
  app_service_plan_id       = azurerm_app_service_plan.appsp.id
  storage_connection_string = azurerm_storage_account.stacc.primary_connection_string
  version                   = "~3"

  identity {
    type = "SystemAssigned"
  }

  app_settings = {
    "_ReleaseName" = ""
    "_BuildName"   = ""
    "_BuildID"     = ""

    "stringFromKeyvault" = azurerm_key_vault_secret.keyvault_var.value

    "newStringSecret" = var.sensitiveString # ---> If this is here, it crashes the execution
  }

  lifecycle {
    ignore_changes = [
      app_settings["_BuildID"],
      app_settings["_BuildName"],
      app_settings["_ReleaseName"]
    ]
  }
}
```
### Crash Output
```
panic: value is marked, so must be unmarked first

goroutine 364 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.6.2-0.20201013200640-e5225636c8c2/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.True(0x2f283c0, 0xc000050a71, 0x284b120, 0xc0009c79e0, 0xc00142f560)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.6.2-0.20201013200640-e5225636c8c2/cty/value_ops.go:360 +0x59
github.com/zclconf/go-cty/cty.Value.False(0x2f283c0, 0xc000050a71, 0x284b120, 0xc0009c79e0, 0x2f28301)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.6.2-0.20201013200640-e5225636c8c2/cty/value_ops.go:369 +0x50
github.com/zclconf/go-cty/cty.Value.Equals(0x2f28480, 0xc001644b60, 0x275a740, 0xc001294c60, 0x2f28480, 0xc000e08340, 0x275a740, 0xc00142f050, 0xc000e08340, 0x275a740, ...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.6.2-0.20201013200640-e5225636c8c2/cty/value_ops.go:315 +0x1686
github.com/hashicorp/terraform/terraform.processIgnoreChangesIndividual(0x2f284c0, 0xc0016454d0, 0x275a740, 0xc001295560, 0x2f284c0, 0xc000e08380, 0x275a740, 0xc00142f110, 0xc0007c02a0, 0x3, ...)
	/home/circleci/project/project/terraform/eval_diff.go:650 +0x635
github.com/hashicorp/terraform/terraform.(*EvalDiff).processIgnoreChanges(0xc0009d1a98, 0x2f284c0, 0xc0016454d0, 0x275a740, 0xc001295560, 0x2f284c0, 0xc000e08380, 0x275a740, 0xc00142f110, 0x0, ...)
	/home/circleci/project/project/terraform/eval_diff.go:575 +0x249
github.com/hashicorp/terraform/terraform.(*EvalDiff).Eval(0xc0009d1a98, 0x2f62560, 0xc000dce340, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/eval_diff.go:210 +0x669
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc0016bb8a0, 0x2f62560, 0xc000dce340, 0x0, 0xc00083c000, 0x8a)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:207 +0x5b3
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).Execute(0xc0016bb8a0, 0x2f62560, 0xc000dce340, 0xc000032002, 0x27a77a0, 0x2aa4140)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:39 +0xf9
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc000726c30, 0x2f62560, 0xc000dce340, 0x1c7f3bbec20, 0xc0016bb8a0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xc3
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2aa4140, 0xc0016bb8a0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:59 +0x97e
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000306ba0, 0x2aa4140, 0xc0016bb8a0, 0xc00065c980)
	/home/circleci/project/project/dag/walk.go:387 +0x375
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:309 +0x1246
```

### Expected Behavior
sensitive value should've been added to function app

### Actual Behavior
terraform crashed

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by alisdair** [comment]
Thanks for reporting this! I can reproduce the issue with this configuration:

```hcl
variable "password" {
  type      = string
  sensitive = true
  default   = "hunter2"
}

resource "random_pet" "pet" {
  prefix = var.password
  lifecycle {
    ignore_changes = [
      prefix
    ]
  }
}
```

Running `terraform apply -auto-approve` twice causes the same crash in processing the `ignore_changes` block.

**Comment by alisdair** [comment]
Thanks again for reporting this! The bug fix will be release as part of the upcoming 0.14.0-beta2.
