### ISSUE TITLE
Azure Devops Plan Crash

### ISSUE THREAD

**Issue by amarkulis** [hashicorp/terraform#26985]
I get the error below running this:
data "azuredevops_project" "foundation" {
  project_name = "PCET-AZR-NEW"
}

resource "azuredevops_variable_group" "variablegroup" {
  project_id   = data.azuredevops_project.foundation.id
  name         = "Test Variable Group"
  description  = "Test Variable Group Description"
  allow_access = true

    variable {
    name  = "key"
    value = "value"
  }

Error: rpc error: code = Canceled desc = context canceled

panic: runtime error: invalid memory address or nil pointer dereference
2020-11-19T22:03:01.587Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe5ee6c]
2020-11-19T22:03:01.587Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 
2020-11-19T22:03:01.587Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: goroutine 43 [running]:
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/taskagent.flattenVariableGroup(0xc0001ecee0, 0xc000269320, 0xc00069f3e0, 0xc00069f3e0, 0xc00046f800)
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/taskagent/resource_variable_group.go:361 +0x2c
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/taskagent.resourceVariableGroupRead(0xc0001ecee0, 0xee91e0, 0xc0002b8300, 0xc0001ecee0, 0x0)
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/taskagent/resource_variable_group.go:192 +0x465
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000111700, 0xc000118730, 0xee91e0, 0xc0002b8300, 0xc00000e968, 0x0, 0x0)
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:455 +0x119
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00010a5b0, 0x137d860, 0xc00026e450, 0xc000118460, 0xc00010a5b0, 0xc00026e450, 0xc00076aa48)
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d8
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x10c2d20, 0xc00010a5b0, 0x137d860, 0xc00026e450, 0xc0002680c0, 0x0, 0x137d860, 0xc00026e450, 0xc000696000, 0x3c1)
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3153 +0x217
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00028c000, 0x138ab80, 0xc00034cd80, 0xc000114200, 0xc000103080, 0x1af81d0, 0x0, 0x0, 0x0)
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:995 +0x460
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: google.golang.org/grpc.(*Server).handleStream(0xc00028c000, 0x138ab80, 0xc00034cd80, 0xc000114200, 0x0)
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:1275 +0xd3d
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00010c200, 0xc00028c000, 0x138ab80, 0xc00034cd80, 0xc000114200)
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:710 +0xa1
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-11-19T22:03:01.588Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020-11-19T22:03:01.590Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/terraform-providers/azuredevops/0.0.1/linux_amd64/terraform-provider-azuredevops_v0.0.1_x4 pid=10049 error="exit status 2"
2020/11/19 22:03:01 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Canceled desc = context canceled
2020/11/19 22:03:01 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Canceled desc = context canceled
2020/11/19 22:03:01 [TRACE] [walkRefresh] Exiting eval tree: azuredevops_variable_group.variablegroup
2020/11/19 22:03:01 [TRACE] vertex "azuredevops_variable_group.variablegroup": visit complete
2020/11/19 22:03:01 [TRACE] vertex "azuredevops_variable_group.variablegroup": dynamic subgraph encountered errors

**Comment by jbardin** [comment]
Hi @amarkulis 

This appears to be a crash in the `azuredevops` provider, not in terraform itself.
Please file the issue that project's github repo, which I believe is https://github.com/microsoft/terraform-provider-azuredevops/issue for this provider.

Thanks!
