### ISSUE TITLE
`anytrue` function failing when using boolean variables

### ISSUE THREAD

**Issue by marcincuber** [hashicorp/terraform#27236]
### Terraform Version

```
0.14.2
```

### Terraform Configuration Files

```terraform
variable "enable_auth" {
  type    = bool
  default = false
}

variable "enable_ui" {
  type    = bool
  default = false
}

module "waf" {
  source = "../.."
  count = anytrue([var.enable_auth, var.enable_ui]) ? 1 : 0
  ...
}

```

### Debug Output

```
Call to function "anytrue" failed: panic in function implementation: interface
conversion: interface {} is *cty.unknownType, not bool
goroutine 2002 [running]:
runtime/debug.Stack(0xc00368d960, 0x308eb60, 0xc0020200c0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/zclconf/go-cty/cty/function.errorForPanic(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/function/error.go:44
github.com/zclconf/go-cty/cty/function.Function.Call.func1(0xc00368dea8,
0xc00368dec8)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/function/function.go:291
+0x95
panic(0x308eb60, 0xc0020200c0)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/zclconf/go-cty/cty.Value.True(0x384eec0, 0xc000134381, 0x3022360,
0x4936e40, 0x384eec0)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/value_ops.go:364 +0x136
github.com/hashicorp/terraform/lang/funcs.glob..func8(0xc001789ea0, 0x1, 0x1,
0x384eec0, 0xc000134381, 0xc0011e3fb0, 0x2f25420, 0xc0008bafe0, 0xc001873050,
0xc001861140, ...)
...
```

### Actual Behavior
I would expect true of false evaluation of the count.

### Additional Context

I am not fully sure whether this is a bug or not. But `anytrue` function should simply be `or` `||` statements. So I would expect it to evaluate booleans in the list just fine. However, I am getting an error and maybe I am using the function incorrectly. Is this desired?

**Comment by alisdair** [comment]
Hi @marcincuber, thanks for reporting this! I'm able to confirm the issue in 0.14.2 and on the main branch. I don't believe this behaviour is correct and there's a proposed fix in #27237.

With a build from that branch, here's a similar reproduction to your example above:

```hcl
variable "enable_auth" {
  type    = bool
  default = false
}

variable "enable_ui" {
  type    = bool
  default = false
}

output "count" {
  value = anytrue([var.enable_auth, var.enable_ui]) ? 1 : 0
}
```

```shellsession
$ terraform apply -auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

count = 0
$ terraform apply -auto-approve -var enable_ui=true

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

count = 1
```
