### ISSUE TITLE
tf plan/refresh crashes (altered state)

### ISSUE THREAD

**Issue by nikopen** [hashicorp/terraform#27367]
tf version 0.14.3

may be duplicate of https://github.com/hashicorp/terraform/issues/26702 (or specific to k8s provider)

repro:  
1) tf creates AWS nodes, k8s cluster and k8s resources
2) k8s cluster manually deleted
3) tf refresh/plan causes crash - cannot connect to k8s (doesn't exist)

stacktrace: 

```
❯ tf refresh
tls_private_key.global_key: Refreshing state... [id=fa4f5aace6d8d7410da9ca5f9ef95c3bafecaf1f]
aws_key_pair.quickstart_key_pair: Refreshing state... [id=quickstart-rancher-20201224171825917400000001]
aws_security_group.rancher_sg_allowall: Refreshing state... [id=sg-0fecfc8a12c01f5f3]
aws_instance.rancher_server: Refreshing state... [id=i-0a01db9eee069eb20]
module.rancher_common.rke_cluster.rancher_cluster: Refreshing state... [id=1368332c-c81d-44b4-abc6-3d453a7c20da]
module.rancher_common.k8s_manifest.cert_manager_crds[5]: Refreshing state... [id=::apiextensions.k8s.io/v1::CustomResourceDefinition::orders.acme.cert-manager.io]
module.rancher_common.k8s_manifest.cert_manager_crds[0]: Refreshing state... [id=::apiextensions.k8s.io/v1::CustomResourceDefinition::certificaterequests.cert-manager.io]
module.rancher_common.k8s_manifest.cert_manager_crds[1]: Refreshing state... [id=::apiextensions.k8s.io/v1::CustomResourceDefinition::certificates.cert-manager.io]

Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x16cfbce]
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: goroutine 42 [running]:
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).RESTMapping.func1(0xc0000b7300, 0x40cb68)
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/client/apiutil/dynamicrestmapper.go:277 +0x3e
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).checkAndReload.func1(0xc0008438b0, 0xc0000b73b0, 0x0, 0x0)
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/client/apiutil/dynamicrestmapper.go:179 +0x6d
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).checkAndReload(0xc0008438b0, 0x1f533c0, 0xc0001c6780, 0xc0000b73b0, 0x0, 0x0)
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/client/apiutil/dynamicrestmapper.go:180 +0x8c
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).RESTMapping(0xc0008438b0, 0xc00063c040, 0x14, 0xc00004c2bb, 0x18, 0xc00089e160, 0x1, 0x1, 0xc00067a6c0, 0x3, ...)
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/client/apiutil/dynamicrestmapper.go:275 +0x15d
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: sigs.k8s.io/controller-runtime/pkg/client.(*clientCache).newResource(0xc000d380a0, 0xc00063c040, 0x14, 0xc00063c055, 0x2, 0xc00004c2bb, 0x18, 0xc00004c200, 0x18, 0x0, ...)
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/client/client_cache.go:63 +0x277
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: sigs.k8s.io/controller-runtime/pkg/client.(*clientCache).getResource(0xc000d380a0, 0x1f65a20, 0xc00000e278, 0x0, 0x0, 0x0)
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/client/client_cache.go:91 +0x241
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: sigs.k8s.io/controller-runtime/pkg/client.(*unstructuredClient).Get(0xc0008deb88, 0x1f96d20, 0xc0001241f8, 0x0, 0x0, 0xc00004c2d5, 0x23, 0x1f65a20, 0xc00000e278, 0x0, ...)
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/client/unstructured_client.go:175 +0x14c
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: sigs.k8s.io/controller-runtime/pkg/client.(*client).Get(0xc0008deb70, 0x1f96d20, 0xc0001241f8, 0x0, 0x0, 0xc00004c2d5, 0x23, 0x1f65a20, 0xc00000e278, 0x23, ...)
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/client/client.go:163 +0xa7
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: github.com/banzaicloud/terraform-provider-k8s/k8s.resourceK8sManifestRead(0xc0003af110, 0x1888140, 0xc000b39400, 0xc0003af110, 0x0)
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/src/github.com/banzaicloud/terraform-provider-k8s/k8s/resource_k8s_manifest.go:237 +0x568
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004aed80, 0xc000b3c500, 0x1888140, 0xc000b39400, 0xc00000e268, 0x0, 0x0)
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:460 +0x119
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000a84d60, 0x1f96da0, 0xc000872b40, 0xc000a08900, 0xc000a84d60, 0xc000872b40, 0xc0005d7b78)
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:525 +0x3d8
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1b4ee40, 0xc000a84d60, 0x1f96da0, 0xc000872b40, 0xc000a088a0, 0x0, 0x1f96da0, 0xc000872b40, 0xc00045c000, 0x9597)
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3269 +0x217
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000702f00, 0x1fae200, 0xc000703b00, 0xc00033e000, 0xc0007c74d0, 0x2d9b490, 0x0, 0x0, 0x0)
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: google.golang.org/grpc.(*Server).handleStream(0xc000702f00, 0x1fae200, 0xc000703b00, 0xc00033e000, 0x0)
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000a88240, 0xc000702f00, 0x1fae200, 0xc000703b00, 0xc00033e000)
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2:      /Users/nandi/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
2020/12/25 03:56:52 [TRACE] vertex "module.rancher_common.k8s_manifest.cert_manager_crds[2]": visit complete
2020/12/25 03:56:52 [TRACE] vertex "module.rancher_common.k8s_manifest.cert_manager_crds[3]": visit complete
2020/12/25 03:56:52 [TRACE] vertex "module.rancher_common.k8s_manifest.cert_manager_crds[1]": visit complete
2020/12/25 03:56:52 [TRACE] vertex "module.rancher_common.k8s_manifest.cert_manager_crds[4]": visit complete
2020/12/25 03:56:52 [TRACE] vertex "module.rancher_common.k8s_manifest.cert_manager_crds[0]": visit complete
2020/12/25 03:56:52 [TRACE] vertex "module.rancher_common.k8s_manifest.cert_manager_crds[5]": visit complete
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020-12-25T03:56:52.265+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/banzaicloud/k8s/0.8.2/linux_amd64/terraform-provider-k8s_v0.8.2 pid=2029 error="exit status 2"
2020/12/25 03:56:52 [TRACE] vertex "module.rancher_common.k8s_manifest.cert_manager_crds": dynamic subgraph encountered errors
2020/12/25 03:56:52 [TRACE] vertex "module.rancher_common.k8s_manifest.cert_manager_crds": visit complete
2020-12-25T03:56:52.265+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020/12/25 03:56:52 [TRACE] vertex "module.rancher_common.k8s_manifest.cert_manager_crds (expand)": dynamic subgraph encountered errors
2020/12/25 03:56:52 [TRACE] vertex "module.rancher_common.k8s_manifest.cert_manager_crds (expand)": visit complete
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "module.rancher_common.provider[\"registry.terraform.io/banzaicloud/k8s\"] (close)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "module.rancher_common.helm_release.cert_manager (expand)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "module.rancher_common.helm_release.rancher_server (expand)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "module.rancher_common.rancher2_bootstrap.admin (expand)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "module.rancher_common.provider[\"registry.terraform.io/rancher/rancher2\"].bootstrap (close)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "module.rancher_common.provider[\"registry.terraform.io/rancher/rancher2\"].admin" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "module.rancher_common.provider[\"registry.terraform.io/hashicorp/helm\"] (close)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "module.rancher_common.rancher2_cluster.quickstart_workload (expand)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "module.rancher_common.output.custom_cluster_command (expand)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "aws_instance.quickstart_node (expand)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "output.workload_node_ip" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "module.rancher_common.provider[\"registry.terraform.io/rancher/rancher2\"].admin (close)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "module.rancher_common.output.custom_cluster_windows_command (expand)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "module.rancher_common.local_file.kube_config_workload_yaml (expand)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "module.rancher_common (close)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "module.rancher_common.provider[\"registry.terraform.io/hashicorp/local\"] (close)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/12/25 03:56:52 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/12/25 03:56:52 [INFO] backend/local: refresh calling Refresh
2020-12-25T03:56:52.267+0200 [DEBUG] plugin: plugin exited
2020-12-25T03:56:52.268+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020-12-25T03:56:52.268+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020-12-25T03:56:52.268+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020-12-25T03:56:52.268+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020-12-25T03:56:52.268+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020-12-25T03:56:52.269+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/local/2.0.0/linux_amd64/terraform-provider-local_v2.0.0_x5 pid=1946
2020-12-25T03:56:52.269+0200 [DEBUG] plugin: plugin exited
2020-12-25T03:56:52.270+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/helm/1.3.2/linux_amd64/terraform-provider-helm_v1.3.2_x4 pid=2046
2020-12-25T03:56:52.270+0200 [DEBUG] plugin: plugin exited
2020-12-25T03:56:52.270+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/rancher/rancher2/1.10.6/linux_amd64/terraform-provider-rancher2_v1.10.6 pid=2005
2020-12-25T03:56:52.270+0200 [DEBUG] plugin: plugin exited
2020-12-25T03:56:52.271+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/3.12.0/linux_amd64/terraform-provider-aws_v3.12.0_x5 pid=1974
2020-12-25T03:56:52.271+0200 [DEBUG] plugin: plugin exited
2020-12-25T03:56:52.271+0200 [DEBUG] plugin: plugin process exited: path=/bin/tf pid=1889
2020-12-25T03:56:52.271+0200 [DEBUG] plugin: plugin exited
2020-12-25T03:56:52.272+0200 [DEBUG] plugin: plugin process exited: path=/bin/tf pid=1716
2020-12-25T03:56:52.272+0200 [DEBUG] plugin: plugin exited
```

**Comment by danieldreier** [comment]
@nikopen thanks for reporting this! It's possible I'm misunderstand, but based on the following line in your output, I think that this is from the k8s provider crashing rather than a bug in Terraform Core:
```
2020-12-25T03:56:52.264+0200 [DEBUG] plugin.terraform-provider-k8s_v0.8.2: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x16cfbce]
```

That shows a crash in plugin.terraform-provider-k8s_v0.8.2, and I'm assuming the RPC error happens because the provider crashed and can no longer communicate with Terraform Core. I'm going to label this as a kubernetes provider issue, and our bot will close this issue and open it again at https://github.com/hashicorp/terraform-provider-kubernetes. If they determine that work in Terraform Core is needed I'm happy to re-open this.
