### ISSUE TITLE
Terraform Cloud crash on previously good repo: panic: value is marked, so must be unmarked first

### ISSUE THREAD

**Issue by synesthesia** [hashicorp/terraform#27529]
```
Terraform v0.14.2
Configuring remote state backend...
Initializing Terraform configuration...
[0m[1mazurerm_resource_group.rg: Refreshing state... [id=REDACTED][0m
[0m[1mazurerm_storage_account.storagefa: Refreshing state... [id=REDACTED][0m
[0m[1mazurerm_key_vault.kv: Refreshing state... [id=REDACTED][0m
[0m[1mazurerm_application_insights.ai: Refreshing state... [id=REDACTED][0m
[0m[1mazurerm_app_service_plan.aspfa: Refreshing state... [id=REDACTED][0m


!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
panic: value is marked, so must be unmarked first

goroutine 185 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.AsString(0x2c50ee0, 0xc000126369, 0x2547ae0, 0xc0005b3e80, 0x2c50e01, 0xc000126369)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/value_ops.go:1229 +0x4f
github.com/hashicorp/hcl/v2/hclsyntax.(*ObjectConsExpr).Value(0xc0000a6460, 0xc0005b35a0, 0x0, 0xc00099aa80, 0x0, 0x0, 0x0, 0x0, 0xa)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.8.0/hclsyntax/expression.go:844 +0xbe5
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc0000100f0, 0xc0005b35a0, 0x0, 0x4, 0xc00163e4a0, 0xc000126301, 0x2c50ee0, 0xc000126369, 0x23733e0)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.8.0/hclsyntax/expression.go:404 +0x260c
github.com/hashicorp/hcl/v2/hcldec.(*AttrSpec).decode(0xc001773170, 0xc000089e60, 0x0, 0x0, 0x0, 0xc0005b35a0, 0x2c50ee0, 0xc00012636a, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.8.0/hcldec/spec.go:205 +0x2ac
github.com/hashicorp/hcl/v2/hcldec.ObjectSpec.decode(0xc001773050, 0xc000089e60, 0x0, 0x0, 0x0, 0xc0005b35a0, 0xc0011faf60, 0x20, 0x20, 0xc0005b3c00, ...)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.8.0/hcldec/spec.go:79 +0x237
github.com/hashicorp/hcl/v2/hcldec.decode(0x2c4fe60, 0xc0005b3c00, 0x0, 0x0, 0x0, 0xc0005b35a0, 0x2c50ca0, 0xc001773050, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.8.0/hcldec/decode.go:21 +0x11b
github.com/hashicorp/hcl/v2/hcldec.Decode(...)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.8.0/hcldec/public.go:15
github.com/hashicorp/terraform/lang.(*Scope).EvalBlock(0xc0004bbd60, 0x2c4f6e0, 0xc001bb5a70, 0xc0011fafc0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/lang/eval.go:67 +0x2ac
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc000d74750, 0x2c4f6e0, 0xc001bb5a70, 0xc0011fafc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/terraform/eval_context_builtin.go:280 +0x1ad
github.com/hashicorp/terraform/terraform.(*EvalDiff).Eval(0xc000973a98, 0x2c8c480, 0xc000d74750, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/eval_diff.go:156 +0x27c
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc00129bdb0, 0x2c8c480, 0xc000d74750, 0x0, 0x2a80)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:207 +0x58d
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).Execute(0xc00129bdb0, 0x2c8c480, 0xc000d74750, 0xc00003a002, 0x24a0780, 0x27afe80)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:39 +0xd2
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc000df95f0, 0x2c8c480, 0xc000d74750, 0x7f145890e140, 0xc00129bdb0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbc
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x27afe80, 0xc00129bdb0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:59 +0x962
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000012a80, 0x27afe80, 0xc00129bdb0, 0xc0002f2f80)
	/home/circleci/project/project/dag/walk.go:387 +0x375
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:309 +0x1246

Failed running command "cd '/terraform/infra' && envdir /env terraform show -json /terraform/terraform.tfplan" (exit 1)
Output: [31mTerraform couldn't read the given file as a state or plan file.
The errors while attempting to read the file as each format are
shown below.

State read error: Error loading statefile: open /terraform/terraform.tfplan: no such file or directory

Plan read error: open /terraform/terraform.tfplan: no such file or directory[0m[0m
```

**Comment by synesthesia** [comment]
Looking at #27403 I too have sensitive variables configured in the Terrraform Cloud workspace for this project

**Comment by jbardin** [comment]
Hi @synesthesia 

There have been many improvement to the new sensitive data handling features in the 0.14 release Can you try to replicate the issue with the latest release (0.14.4 as of now)? If the problem is still present, we would need a minimal, reproducible example to investigate the issue.

Thanks!

**Comment by synesthesia** [comment]
Hi @jbardin if I update the settings in the Terraform Cloud workspace  to 0.14.5 the plan phase runs as expected.

**Comment by synesthesia** [comment]
Problem resolved by upgrading Terraform Cloud workspace to 0.14.5
