### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Nuru** [hashicorp/terraform#27878]
### Terraform Version
```
0.13.6
```

### Terraform Configuration Files
Not sure what caused this. 

### Crash Output
<details><summary>crash.log</summary>

```
2021/02/23 01:19:17 [INFO] Terraform version: 0.13.6  
2021/02/23 01:19:17 [INFO] Go runtime version: go1.14.7
2021/02/23 01:19:17 [INFO] CLI args: []string{"/usr/share/terraform/0.13/bin/terraform", "init"}
2021/02/23 01:19:17 [DEBUG] Attempting to open CLI config file: /conf/.terraformrc
2021/02/23 01:19:17 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021/02/23 01:19:17 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021/02/23 01:19:17 [DEBUG] ignoring non-existing provider search directory /conf/.terraform.d/plugins
2021/02/23 01:19:17 [DEBUG] ignoring non-existing provider search directory /usr/share/xdg_data_home/terraform/plugins
2021/02/23 01:19:17 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2021/02/23 01:19:17 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2021/02/23 01:19:17 [INFO] CLI command args: []string{"init"}
panic: value is unknown

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.AsString(0x2cf1860, 0xc000136390, 0x22d9ce0, 0x4123860, 0x26d5600, 0x7)
	/home/circleci/project/project/vendor/github.com/zclconf/go-cty/cty/value_ops.go:1187 +0x16b
github.com/hashicorp/terraform/configs.decodeRequiredProvidersBlock(0xc00045d930, 0x26ec418, 0x12, 0x1, 0x0)
	/home/circleci/project/project/configs/provider_requirements.go:68 +0x1864
github.com/hashicorp/terraform/configs.(*Parser).loadConfigFile(0xc00051e040, 0xc0005861b0, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/configs/parser_config.go:76 +0x1b7c
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigFile(...)
	/home/circleci/project/project/configs/parser_config.go:22
github.com/hashicorp/terraform/configs.(*Parser).loadFiles(0xc00051e040, 0xc0001de000, 0x9, 0x10, 0x0, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/configs/parser_config_dir.go:77 +0x342
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigDir(0xc00051e040, 0x26ce845, 0x1, 0x0, 0x1, 0x9, 0x0)
	/home/circleci/project/project/configs/parser_config_dir.go:37 +0x121
github.com/hashicorp/terraform/command.(*Meta).loadSingleModule(0xc000348fc0, 0x26ce845, 0x1, 0x0, 0x0, 0x0, 0xe)
	/home/circleci/project/project/command/meta_config.go:113 +0x135
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc000348fc0, 0xc00012c030, 0x0, 0x0, 0xc0002c4a60)
	/home/circleci/project/project/command/init.go:170 +0xb24
github.com/mitchellh/cli.(*CLI).Run(0xc0000d1540, 0xc0000d1540, 0xc00063fd48, 0x1)
	/home/circleci/project/project/vendor/github.com/mitchellh/cli/cli.go:255 +0x1da
main.wrappedMain(0x0)
	/home/circleci/project/project/main.go:275 +0xc90
main.realMain(0x0)
	/home/circleci/project/project/main.go:106 +0xde
main.main()
	/home/circleci/project/project/main.go:42 +0x3a
```

</details>

### Steps to Reproduce
Not sure exactly. Maybe:
1. `terraform init`
2. Edit `versions.tf`, remove some providers from `required_providers` 
1. `terraform init`

**Comment by jbardin** [comment]
Hi @Nuru 

Thanks for reporting the crash. The code paths here are quite different in current releases, so does not apply to the code as it exists now. If you can reproduce this with the latest development release, please file a new issue with all the reproduction steps, including the configuration and trace logs.

Thanks!
