### ISSUE TITLE
Go Compiler Segmentation Fault while compiling for 32-bit x86 platforms

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#27891]
Intermittently since upgrading to Go 1.16 (in #27876) we've been seeing Go compiler crashes only for the various `_386` targets when trying to compile to run tests in CircleCI. The exact package seems to vary but packages under the `k8s.io/` prefix seem to commonly appear in these error messages.

Here's the output for the latest failure I've seen as of opening this issue:

```
./scripts/build.sh
==> Removing old directory...
==> Building...
Number of parallel builds: 35

-->     freebsd/386: github.com/hashicorp/terraform
-->     windows/386: github.com/hashicorp/terraform
-->       linux/386: github.com/hashicorp/terraform
-->     openbsd/386: github.com/hashicorp/terraform

4 errors occurred:
--> openbsd/386 error: exit status 2
Stderr: go build k8s.io/api/auditregistration/v1alpha1: /usr/local/go/pkg/tool/linux_amd64/compile: exit status 253
go build github.com/ugorji/go/codec: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
# k8s.io/api/authentication/v1
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x4504ec]

runtime stack:
runtime.throw(0xcba73c, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x2e5
runtime.stackpoolalloc(0x11e0700, 0xc000480000)
	/usr/local/go/src/runtime/stack.go:204 +0xcc
runtime.stackcacherefill(0x7fb0530cc5b8, 0xc94300)
	/usr/local/go/src/runtime/stack.go:273 +0x5f
runtime.stackalloc(0x800, 0xc94320, 0x1)
	/usr/local/go/src/runtime/stack.go:375 +0x170
runtime.malg.func1()
	/usr/local/go/src/runtime/proc.go:3948 +0x31
runtime.malg(0xc000000800, 0x0)
	/usr/local/go/src/runtime/proc.go:3947 +0xac
runtime.newproc1(0xcc8e48, 0xc000106c10, 0x0, 0xc000000180, 0x41d497, 0xc000106b6f)
	/usr/local/go/src/runtime/proc.go:4021 +0x3e9
runtime.newproc.func1()
	/usr/local/go/src/runtime/proc.go:3979 +0x53
runtime.systemstack(0x46d334)
	/usr/local/go/src/runtime/asm_amd64.s:379 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1246

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:339 fp=0xc000106bb8 sp=0xc000106bb0 pc=0x46d460
runtime.newproc(0x0, 0xcc8e48)
	/usr/local/go/src/runtime/proc.go:3978 +0x6e fp=0xc000106c00 sp=0xc000106bb8 pc=0x44276e
runtime.gcBgMarkStartWorkers()
	/usr/local/go/src/runtime/mgc.go:1835 +0x37 fp=0xc000106c28 sp=0xc000106c00 pc=0x41d497
runtime.gcStart(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/mgc.go:1358 +0x1ca fp=0xc000106ca0 sp=0xc000106c28 pc=0x41be8a
runtime.mallocgc(0xf70, 0xc5f100, 0x7fb02c419a01, 0x203000)
	/usr/local/go/src/runtime/malloc.go:1166 +0x495 fp=0xc000106d28 sp=0xc000106ca0 pc=0x40d9d5
runtime.newarray(0xc5f100, 0x13, 0xe8)
	/usr/local/go/src/runtime/malloc.go:1199 +0x65 fp=0xc000106d58 sp=0xc000106d28 pc=0x40e085
runtime.makeBucketArray(0xc358a0, 0x4, 0x0, 0xc79da0, 0x1)
	/usr/local/go/src/runtime/map.go:362 +0x199 fp=0xc000106d90 sp=0xc000106d58 pc=0x40eff9
runtime.hashGrow(0xc358a0, 0xc00048ef90)
	/usr/local/go/src/runtime/map.go:1036 +0x89 fp=0xc000106de0 sp=0xc000106d90 pc=0x410ca9
runtime.mapassign_faststr(0xc358a0, 0xc00048ef90, 0x7fb02c3ef6b8, 0xa, 0x11e1ac0)
	/usr/local/go/src/runtime/map_faststr.go:272 +0x10a fp=0xc000106e48 sp=0xc000106de0 pc=0x41428a
cmd/compile/internal/types.(*Pkg).LookupOK(...)
	/usr/local/go/src/cmd/compile/internal/types/pkg.go:107
cmd/compile/internal/types.(*Pkg).Lookup(...)
	/usr/local/go/src/cmd/compile/internal/types/pkg.go:83
cmd/compile/internal/gc.iimport(0xc00047c410, 0xc00044d8a0, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/iimport.go:162 +0x671 fp=0xc000107078 sp=0xc000106e48 pc=0xa8f651
cmd/compile/internal/gc.importfile(0xc000107488, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/main.go:1320 +0x7d5 fp=0xc0001073f0 sp=0xc000107078 pc=0xab1575
cmd/compile/internal/gc.(*noder).importDecl(0xc0003a4120, 0xc0003eaa00)
	/usr/local/go/src/cmd/compile/internal/gc/noder.go:334 +0xba fp=0xc0001074a8 sp=0xc0001073f0 pc=0xab957a
cmd/compile/internal/gc.(*noder).decls(0xc0003a4120, 0xc00041a000, 0x5d, 0x80, 0xc000056000, 0xc00001c418, 0x170e)
	/usr/local/go/src/cmd/compile/internal/gc/noder.go:302 +0x2a8 fp=0xc000107578 sp=0xc0001074a8 pc=0xab9148
cmd/compile/internal/gc.(*noder).node(0xc0003a4120)
	/usr/local/go/src/cmd/compile/internal/gc/noder.go:257 +0x105 fp=0xc000107658 sp=0xc000107578 pc=0xab85e5
cmd/compile/internal/gc.parseFiles(0xc0000107b0, 0x6, 0x7, 0x2)
	/usr/local/go/src/cmd/compile/internal/gc/noder.go:63 +0x369 fp=0xc000107760 sp=0xc000107658 pc=0xab7329
cmd/compile/internal/gc.Main(0xcc8650)
	/usr/local/go/src/cmd/compile/internal/gc/main.go:578 +0x2837 fp=0xc000107f10 sp=0xc000107760 pc=0xaaaef7
main.main()
	/usr/local/go/src/cmd/compile/main.go:52 +0xb1 fp=0xc000107f88 sp=0xc000107f10 pc=0xbf90d1
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc000107fe0 sp=0xc000107f88 pc=0x439d76
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000107fe8 sp=0xc000107fe0 pc=0x46f161

goroutine 8 [runnable]:
cmd/compile/internal/syntax.(*parser).pexpr(0xc000152580, 0xc63e01, 0x7fb0530cc108, 0xc00048f3e0)
	/usr/local/go/src/cmd/compile/internal/syntax/parser.go:1024 +0xb9e
cmd/compile/internal/syntax.(*parser).unaryExpr(0xc000152580, 0xc0004773a0, 0xc000038800)
	/usr/local/go/src/cmd/compile/internal/syntax/parser.go:792 +0x193
cmd/compile/internal/syntax.(*parser).binaryExpr(0xc000152580, 0x0, 0x203000, 0x2c)
	/usr/local/go/src/cmd/compile/internal/syntax/parser.go:689 +0x2f
cmd/compile/internal/syntax.(*parser).expr(...)
	/usr/local/go/src/cmd/compile/internal/syntax/parser.go:682
cmd/compile/internal/syntax.(*parser).exprList(0xc000152580, 0x40, 0xc000038800)
	/usr/local/go/src/cmd/compile/internal/syntax/parser.go:2298 +0x49
cmd/compile/internal/syntax.(*parser).stmtOrNil(0xc000152580, 0xc0004751a0, 0x6)
	/usr/local/go/src/cmd/compile/internal/syntax/parser.go:2095 +0x8d3
cmd/compile/internal/syntax.(*parser).stmtList(0xc000152580, 0xc000472fc0, 0xc00000ed00, 0xc000045d30)
	/usr/local/go/src/cmd/compile/internal/syntax/parser.go:2195 +0x93
cmd/compile/internal/syntax.(*parser).blockStmt(0xc000152580, 0x0, 0x0, 0x1)
	/usr/local/go/src/cmd/compile/internal/syntax/parser.go:1802 +0xa8
cmd/compile/internal/syntax.(*parser).funcBody(0xc000152580, 0xc000472f40)
	/usr/local/go/src/cmd/compile/internal/syntax/parser.go:661 +0x4a
cmd/compile/internal/syntax.(*parser).funcDeclOrNil(0xc000152580, 0xc00046a400)
	/usr/local/go/src/cmd/compile/internal/syntax/parser.go:652 +0x15b
cmd/compile/internal/syntax.(*parser).fileOrNil(0xc000152580, 0xc00048f050)
	/usr/local/go/src/cmd/compile/internal/syntax/parser.go:421 +0x38f
cmd/compile/internal/syntax.Parse(0xc00048f050, 0xdbcfe0, 0xc00000eca8, 0xc00044d8f0, 0xc00044d900, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/compile/internal/syntax/syntax.go:81 +0xeb
cmd/compile/internal/gc.parseFiles.func1(0xc00001c300, 0xc0003a41b0, 0x7ffee8099582, 0x57)
	/usr/local/go/src/cmd/compile/internal/gc/noder.go:53 +0x22e
created by cmd/compile/internal/gc.parseFiles
	/usr/local/go/src/cmd/compile/internal/gc/noder.go:40 +0x216

goroutine 9 [semacquire]:
cmd/compile/internal/syntax.(*source).init(...)
	/usr/local/go/src/cmd/compile/internal/syntax/source.go:65
cmd/compile/internal/syntax.(*scanner).init(0xc000152700, 0xdbcfe0, 0xc00000ecb0, 0xc00000d6b0, 0x2)
	/usr/local/go/src/cmd/compile/internal/syntax/scanner.go:47 +0xf0
cmd/compile/internal/syntax.(*parser).init(0xc0001526e0, 0xc00048f080, 0xdbcfe0, 0xc00000ecb0, 0xc00044d910, 0xc00044d920, 0x1)
	/usr/local/go/src/cmd/compile/internal/syntax/parser.go:39 +0xd2
cmd/compile/internal/syntax.Parse(0xc00048f080, 0xdbcfe0, 0xc00000ecb0, 0xc00044d910, 0xc00044d920, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/compile/internal/syntax/syntax.go:79 +0xcb
cmd/compile/internal/gc.parseFiles.func1(0xc00001c300, 0xc0003a4240, 0x7ffee80995da, 0x54)
	/usr/local/go/src/cmd/compile/internal/gc/noder.go:53 +0x22e
created by cmd/compile/internal/gc.parseFiles
	/usr/local/go/src/cmd/compile/internal/gc/noder.go:40 +0x216

goroutine 10 [runnable]:
cmd/compile/internal/syntax.(*scanner).next(0xc000152860)
	/usr/local/go/src/cmd/compile/internal/syntax/scanner.go:88 +0xbdb
cmd/compile/internal/syntax.(*parser).got(...)
	/usr/local/go/src/cmd/compile/internal/syntax/parser.go:183
cmd/compile/internal/syntax.(*parser).fileOrNil(0xc000152840, 0xc00048f0b0)
	/usr/local/go/src/cmd/compile/internal/syntax/parser.go:385 +0xc5
cmd/compile/internal/syntax.Parse(0xc00048f0b0, 0xdbcfe0, 0xc00000ecb8, 0xc00044d930, 0xc00044d940, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/compile/internal/syntax/syntax.go:81 +0xeb
cmd/compile/internal/gc.parseFiles.func1(0xc00001c300, 0xc0003a42d0, 0x7ffee809962f, 0x6a)
	/usr/local/go/src/cmd/compile/internal/gc/noder.go:53 +0x22e
created by cmd/compile/internal/gc.parseFiles
	/usr/local/go/src/cmd/compile/internal/gc/noder.go:40 +0x216
# github.com/hashicorp/terraform/terraform
compile: writing output: write $WORK/b306/_pkg_.a: cannot allocate memory

--> windows/386 error: exit status 1
Stderr: go build k8s.io/apimachinery/pkg/runtime/serializer/protobuf: /usr/local/go/pkg/tool/linux_amd64/compile: signal: segmentation fault (core dumped)
go build github.com/ugorji/go/codec: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed

--> linux/386 error: exit status 1
Stderr: go build k8s.io/api/authorization/v1: /usr/local/go/pkg/tool/linux_amd64/compile: signal: segmentation fault (core dumped)
go build github.com/ugorji/go/codec: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed

--> freebsd/386 error: exit status 1
Stderr: go build k8s.io/api/node/v1alpha1: /usr/local/go/pkg/tool/linux_amd64/compile: exit status 1
```

So far I've only seen this happen with the `build-386` portion of the test process, and each time I've resolved it by asking Circle-CI to re-run that job, suggesting that it's intermittent and possibly related to resource exhaustion in the test workers. (note that one of the many error messages here is "compile: writing output: write $WORK/b306/_pkg_.a: cannot allocate memory".)

**Comment by apparentlymart** [comment]
We haven't seen this occur for a long time now, and we've long moved on from Go 1.16, so I'm going to assume this was a toolchain bug that has since been fixed and close it now.
