### ISSUE TITLE
fluke crash ... while checking available plugins : panic, runtime error, invalid memory address or nil pointer dereference, signal SIGSEGV,  segmentation violation code

### ISSUE THREAD

**Issue by cmorley-chwy** [hashicorp/terraform#28030]
### Terraform Version
```
required_version = ">= 0.12"
```

### Terraform Configuration Files

```terraform
terraform {
  backend "s3" {}
  required_version = ">= 0.12"

  required_providers {
    aws = ">= 2.60.0"
  }
}

provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
}

provider "aws" {
  alias  = "us-east-2"
  region = "us-east-2"
}

module "ims_us_east_1" {
  source = "REDACTED"

  ...REDACTED...

  providers = {
    aws = aws.us-east-1
  }

  parameters = var.parameters
}

module "ims_us_east_2" {
  source = "REDACTED"

  ...REDACTED...

  providers = {
    aws = aws.us-east-2
  }

  parameters = var.parameters
}
```

### Debug Output
```
13:41:42  Started by user [REDACTED]
13:41:42  Running as [REDACTED]
13:41:42  Running in Durability level: PERFORMANCE_OPTIMIZED
13:41:42  [Pipeline] Start of Pipeline
13:41:42  [Pipeline] node
13:41:42  Running on EC2 (jenkins-agents) - deploy agent (i-[REDACTED]) in /var/lib/jenkins/jenkins-agent/workspace/[REDACTED]
13:41:42  [Pipeline] {
13:41:42  [Pipeline] stage
13:41:42  [Pipeline] { (create versions files on dev)
13:41:42  Stage "create versions files on dev" skipped due to when conditional
13:41:42  [Pipeline] }
13:41:42  [Pipeline] // stage
13:41:42  [Pipeline] stage
13:41:42  [Pipeline] { (copy versions files from previous env build)
13:41:42  [Pipeline] copyArtifacts
13:41:43  Copied 2 artifacts from "[REDACTED]" build number 178
13:41:43  [Pipeline] }
13:41:43  [Pipeline] // stage
13:41:43  [Pipeline] stage
13:41:43  [Pipeline] { (display versions to the console)
13:41:43  [Pipeline] script
13:41:43  [Pipeline] {
13:41:43  [Pipeline] sh
13:41:43  
13:41:43  **** Versions ****
13:41:43  [REDACTED]="0.17.0"
13:41:43  [REDACTED]="0.35.0"
13:41:43  [REDACTED]=0.41.0
13:41:43  
13:41:43  [Pipeline] }
13:41:43  [Pipeline] // script
13:41:43  [Pipeline] }
13:41:43  [Pipeline] // stage
13:41:43  [Pipeline] stage
13:41:43  [Pipeline] { (deploy)
13:41:43  [Pipeline] script
13:41:43  [Pipeline] {
13:41:43  [Pipeline] readProperties
13:41:43  [Pipeline] }
13:41:43  [Pipeline] // script
13:41:43  [Pipeline] withAWS
13:41:43  Requesting assume role
13:41:43  Assuming role ARN is arn:aws:iam::[REDACTED]:role/[REDACTED] role arn:aws:sts::[REDACTED]:[REDACTED]/[REDACTED]/[REDACTED] with id [REDACTED]:Jenkins-deploy-[REDACTED]
13:41:43  [Pipeline] {
13:41:43  [Pipeline] sh
13:41:44  WARNING! Using --password via the CLI is insecure. Use --password-stdin.
13:41:44  WARNING! Your password will be stored unencrypted in .docker/config.json.
13:41:44  Configure a credential helper to remove this warning. See
13:41:44  https://docs.docker.com/engine/reference/commandline/login/#credentials-store
13:41:44  
13:41:44  Login Succeeded
13:41:44  [Pipeline] sh
13:41:44  Unable to find image '[REDACTED]:0.41.0' locally
13:41:44  0.41.0: Pulling from demm/search-ingest-terraform
13:41:44  c9b1b535fdd9: Already exists
13:41:44  2e6efbb09be4: Already exists
13:41:44  d5eeca0eed63: Already exists
13:41:44  ad0aa6e211e4: Already exists
13:41:44  75d57694c5be: Already exists
13:41:44  62c5641b7a79: Already exists
13:41:44  50e7ca02dad6: Already exists
13:41:44  260b70193339: Pulling fs layer
13:41:44  ffcc2832f25d: Pulling fs layer
13:41:44  0e1b0bb54ca6: Pulling fs layer
13:41:45  ffcc2832f25d: Verifying Checksum
13:41:45  ffcc2832f25d: Download complete
13:41:45  0e1b0bb54ca6: Verifying Checksum
13:41:45  0e1b0bb54ca6: Download complete
13:41:45  260b70193339: Verifying Checksum
13:41:45  260b70193339: Download complete
13:41:45  260b70193339: Pull complete
13:41:45  ffcc2832f25d: Pull complete
13:41:45  0e1b0bb54ca6: Pull complete
13:41:45  Digest: sha256:[REDACTED]
13:41:45  Status: Downloaded newer image for [REDACTED].dkr.ecr.us-east-1.amazonaws.com/[REDACTED]:0.41.0
13:41:46  Initializing modules...
13:41:46  
13:41:46  Initializing the backend...
13:41:46  
13:41:46  Successfully configured the backend "s3"! Terraform will automatically
13:41:46  use this backend unless the backend configuration changes.
13:41:47  
13:41:47  Initializing provider plugins...
13:41:47  - Checking for available provider plugins...
13:42:09  panic: runtime error: invalid memory address or nil pointer dereference
13:42:09  [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd0c90a]
13:42:09  
13:42:09  goroutine 1 [running]:
13:42:09  github.com/hashicorp/terraform/registry.maxRetryErrorHandler(0x0, 0x232e4e0, 0xc0010a38c0, 0x2, 0x3, 0x3, 0x232e4e0)
13:42:09  	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/registry/client.go:422 +0xea
13:42:09  github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc000f42cc0, 0xc00067a050, 0x1e8df81, 0x13, 0xc0000f4b88)
13:42:09  	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/go-retryablehttp@v0.5.2/client.go:452 +0x706
13:42:09  github.com/hashicorp/terraform/registry.(*Client).TerraformProviderVersions(0xc000568640, 0xc000f3af00, 0x0, 0x0, 0x0)
13:42:09  	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/registry/client.go:305 +0x467
13:42:09  github.com/hashicorp/terraform/plugin/discovery.(*ProviderInstaller).listProviderVersions(0xc00003a7e0, 0xc00022c529, 0x3, 0x1e7474c, 0x1, 0x1e92a34, 0x15, 0xc000050570, 0xc000050500, 0xc0001feca8)
13:42:09  	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/plugin/discovery/get.go:477 +0x7e
13:42:09  github.com/hashicorp/terraform/plugin/discovery.(*ProviderInstaller).Get(0xc00003a7e0, 0xc00022c529, 0x3, 0x1e7474c, 0x1, 0x1e92a34, 0x15, 0xc0000acb88, 0x1, 0x1, ...)
13:42:09  	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/plugin/discovery/get.go:125 +0xde
13:42:09  github.com/hashicorp/terraform/command.(*InitCommand).getProviders(0xc000486380, 0xc000298a80, 0xc0000ac0b8, 0x0, 0xc001062320, 0x0, 0x0, 0x0)
13:42:09  	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/init.go:530 +0x4c5
13:42:09  github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc000486380, 0xc0000b2020, 0x5, 0x5, 0xc0003b80c0)
13:42:09  	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/init.go:347 +0x102d
13:42:09  github.com/mitchellh/cli.(*CLI).Run(0xc000350280, 0xc000350280, 0xc00051fd90, 0x1)
13:42:09  	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
13:42:09  main.wrappedMain(0x0)
13:42:09  	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:239 +0xc33
13:42:09  main.realMain(0x0)
13:42:09  	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:103 +0xb4
13:42:09  main.main()
13:42:09  	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:39 +0x3b
13:42:09  
13:42:09  
13:42:09  
13:42:09  !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
13:42:09  
13:42:09  Terraform crashed! This is always indicative of a bug within Terraform.
13:42:09  A crash log has been placed at "crash.log" relative to your current
13:42:09  working directory. It would be immensely helpful if you could please
13:42:09  report the crash with Terraform[1] so that we can fix this.
13:42:09  
13:42:09  When reporting bugs, please include your terraform version. That
13:42:09  information is available on the first line of crash.log. You can also
13:42:09  get it by running 'terraform --version' on the command line.
13:42:09  
13:42:09  SECURITY WARNING: the "crash.log" file that was created may contain 
13:42:09  sensitive information that must be redacted before it is safe to share 
13:42:09  on the issue tracker.
13:42:09  
13:42:09  [1]: https://github.com/hashicorp/terraform/issues
13:42:09  
13:42:09  !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
13:42:09  
13:42:09  Error: Could not satisfy plugin requirements
13:42:09  
13:42:09  
13:42:09  Plugin reinitialization required. Please run "terraform init".
13:42:09  
13:42:09  Plugins are external binaries that Terraform uses to access and manipulate
13:42:09  resources. The configuration provided requires plugins which can't be located,
13:42:09  don't satisfy the version constraints, or are otherwise incompatible.
13:42:09  
13:42:09  Terraform automatically discovers provider requirements from your
13:42:09  configuration, including providers used in child modules. To see the
13:42:09  requirements and constraints from each module, run "terraform providers".
13:42:09  
13:42:09  
13:42:09  
13:42:09  Error: provider.template: no suitable version installed
13:42:09    version requirements: "(any version)"
13:42:09    versions installed: none
13:42:09  
13:42:09  
13:42:09  
13:42:09  Error: provider.aws: no suitable version installed
13:42:09    version requirements: ">= 2.60.0"
13:42:09    versions installed: none
13:42:09  
13:42:09  
13:42:09  [Pipeline] }
13:42:09  [Pipeline] // withAWS
13:42:09  [Pipeline] }
13:42:09  [Pipeline] // stage
13:42:09  [Pipeline] }
13:42:09  [Pipeline] // node
13:42:09  [Pipeline] End of Pipeline
13:42:09  ERROR: script returned exit code 1
13:42:09  Finished: FAILURE
```

### Crash Output
```
2021/03/09 18:41:46 [INFO] Terraform version: 0.12.23
2021/03/09 18:41:46 [INFO] Go runtime version: go1.12.13
2021/03/09 18:41:46 [INFO] CLI args: []string{"/bin/terraform", "init", "-backend-config=bucket=[REDACTED]", "-backend-config=dynamodb_table=[REDACTED]", "-backend-config=key=[REDACTED]", "-backend-config=region=us-east-1", "."}
2021/03/09 18:41:46 [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2021/03/09 18:41:46 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021/03/09 18:41:46 [INFO] CLI command args: []string{"init", "-backend-config=bucket=[REDACTED]", "-backend-config=dynamodb_table=[REDACTED]", "-backend-config=key=[REDACTED]", "-backend-config=region=us-east-1", "."}
2021/03/09 18:41:46 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED] <nil> already installed in modules/[REDACTED]-cluster
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED] <nil> already installed in .terraform/modules/[REDACTED]/terraform
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_asg
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_asg <nil> already installed in .terraform/modules/[REDACTED]_asg/terraform
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_asg.alb
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_asg.alb <nil> already installed in .terraform/modules/[REDACTED]_asg.alb/terraform
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_asg.alb.[REDACTED]
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_asg.alb.[REDACTED] <nil> already installed in .terraform/modules/[REDACTED]_asg.alb.[REDACTED]/terraform
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_iam
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_iam <nil> already installed in modules/iam
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_iam.dataimport_lambda_iam_role
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_iam.dataimport_lambda_iam_role <nil> already installed in .terraform/modules/[REDACTED]_iam.dataimport_lambda_iam_role/terraform/modules/iam-role
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_iam.[REDACTED]_node_iam_role
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_iam.[REDACTED]_node_iam_role <nil> already installed in .terraform/modules/[REDACTED]_iam.[REDACTED]_node_iam_role/terraform/modules/iam-role
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_s3
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_s3 <nil> already installed in modules/s3
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_s3.app_data
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_s3.app_data <nil> already installed in .terraform/modules/REDACTED]_s3.app_data/terraform
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_scheduler
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_scheduler <nil> already installed in modules/scheduler
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_security
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_security <nil> already installed in modules/security
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED].parameters
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED].parameters <nil> already installed in modules/parameters
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_lambda
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_lambda <nil> already installed in modules/lambda
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_lambda.dataimport_lambda
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer:
REDACTED]_lambda.dataimport_lambda <nil> already installed in .terraform/modules/[REDACTED]_lambda.dataimport_lambda/terraform/modules/lambda-function
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_lambda.dataimport_lambda.lambda_iam_role
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_lambda.dataimport_lambda.lambda_iam_role <nil> already installed in .terraform/modules/[REDACTED]_lambda.dataimport_lambda.lambda_iam_role/terraform/modules/iam-role
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_east_2
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_us_east_2 <nil> already installed in modules/[REDACTED]-cluster
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED] <nil> already installed in .terraform/modules/[REDACTED]/terraform
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_asg
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_asg <nil> already installed in .terraform/modules/[REDACTED]_asg/terraform
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_asg.alb
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_asg.alb <nil> already installed in .terraform/modules/[REDACTED]_asg.alb/terraform
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_asg.alb.core_info
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_asg.alb.core_info <nil> already installed in .terraform/modules/[REDACTED]_asg.alb.core_info/terraform
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_iam
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_iam <nil> already installed in modules/iam
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_iam.dataimport_lambda_iam_role
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_iam.dataimport_lambda_iam_role <nil> already installed in .terraform/modules/[REDACTED]_iam.dataimport_lambda_iam_role/terraform/modules/iam-role
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_iam.[REDACTED]_node_iam_role
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_iam.[REDACTED]_node_iam_role <nil> already installed in .terraform/modules/[REDACTED]_node_iam_role/terraform/modules/iam-role
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_s3
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_s3 <nil> already installed in modules/s3
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_s3.app_data
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_s3.app_data <nil> already installed in .terraform/modules/[REDACTED]_s3.app_data/terraform
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_scheduler
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_scheduler <nil> already installed in modules/scheduler
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_security
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_security <nil> already installed in modules/security
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED].parameters
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED].parameters <nil> already installed in modules/parameters
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_lambda
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_lambda <nil> already installed in modules/lambda
2021/03/09 18:41:46 [DEBUG] Module installer: begin [REDACTED]_lambda.dataimport_lambda
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: [REDACTED]_lambda.dataimport_lambda <nil> already installed in .terraform/modules/[REDACTED]_lambda.dataimport_lambda/terraform/modules/lambda-function
2021/03/09 18:41:46 [DEBUG] Module installer: begin REDACTED]_lambda.dataimport_lambda.lambda_iam_role
2021/03/09 18:41:46 [TRACE] ModuleInstaller: Module installer: REDACTED]_lambda.dataimport_lambda.lambda_iam_role <nil> already installed in .terraform/modules/REDACTED]_lambda.dataimport_lambda.lambda_iam_role/terraform/modules/iam-role
2021/03/09 18:41:46 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json
2021/03/09 18:41:46 [TRACE] Meta.Backend: merging -backend-config=... CLI overrides into backend configuration
2021/03/09 18:41:46 [TRACE] Meta.Backend: built configuration for "s3" backend with hash value [REDACTED]
2021/03/09 18:41:46 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2021/03/09 18:41:46 [DEBUG] New state was assigned lineage "[REDACTED]"
2021/03/09 18:41:46 [TRACE] Meta.Backend: moving from default local state only to "s3" backend
2021/03/09 18:41:46 [INFO] Setting AWS metadata API timeout to 100ms
2021/03/09 18:41:46 [INFO] AWS EC2 instance detected via default metadata API endpoint, EC2RoleProvider added to the auth chain
2021/03/09 18:41:46 [INFO] AWS Auth provider used: "EnvProvider"
2021/03/09 18:41:46 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/03/09 18:41:46 [DEBUG] checking for provider in "."
2021/03/09 18:41:46 [DEBUG] checking for provider in "/bin"
2021/03/09 18:41:46 [DEBUG] checking for provisioner in "."
2021/03/09 18:41:46 [DEBUG] checking for provisioner in "/bin"
2021/03/09 18:41:46 [INFO] Failed to read plugin lock file .terraform/plugins/linux_amd64/lock.json: open .terraform/plugins/linux_amd64/lock.json: no such file or directory
2021/03/09 18:41:46 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2021/03/09 18:41:46 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2021/03/09 18:41:46 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2021/03/09 18:41:46 [TRACE] statemgr.Filesystem: read nil snapshot
2021/03/09 18:41:46 [TRACE] Meta.Backend: ignoring local "default" workspace because its state is empty
2021/03/09 18:41:46 [DEBUG] New state was assigned lineage "[REDACTED]"
2021/03/09 18:41:46 [TRACE] Preserving existing state lineage "[REDACTED]"
2021/03/09 18:41:46 [TRACE] Meta.Backend: instantiated backend of type *s3.Backend
2021/03/09 18:41:46 [DEBUG] checking for provider in "."
2021/03/09 18:41:46 [DEBUG] checking for provider in "/bin"
2021/03/09 18:41:46 [DEBUG] checking for provisioner in "."
2021/03/09 18:41:46 [DEBUG] checking for provisioner in "/bin"
2021/03/09 18:41:46 [INFO] Failed to read plugin lock file .terraform/plugins/linux_amd64/lock.json: open .terraform/plugins/linux_amd64/lock.json: no such file or directory
2021/03/09 18:41:46 [TRACE] Meta.Backend: backend *s3.Backend does not support operations, so wrapping it in a local backend
2021/03/09 18:41:47 [DEBUG] checking for provider in "."
2021/03/09 18:41:47 [DEBUG] checking for provider in "/bin"
2021/03/09 18:41:47 [DEBUG] plugin requirements: "template"=""
2021/03/09 18:41:47 [DEBUG] plugin requirements: "aws"=">= 2.60.0"
2021/03/09 18:41:47 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2021/03/09 18:41:47 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
2021/03/09 18:41:47 [DEBUG] fetching provider versions from "https://registry.terraform.io/v1/providers/-/aws/versions"
2021/03/09 18:41:47 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/-/aws/versions
2021/03/09 18:41:58 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/-/aws/versions
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd0c90a]

goroutine 1 [running]:
github.com/hashicorp/terraform/registry.maxRetryErrorHandler(0x0, 0x232e4e0, 0xc0010a38c0, 0x2, 0x3, 0x3, 0x232e4e0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/registry/client.go:422 +0xea
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc000f42cc0, 0xc00067a050, 0x1e8df81, 0x13, 0xc0000f4b88)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/go-retryablehttp@v0.5.2/client.go:452 +0x706
github.com/hashicorp/terraform/registry.(*Client).TerraformProviderVersions(0xc000568640, 0xc000f3af00, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/registry/client.go:305 +0x467
github.com/hashicorp/terraform/plugin/discovery.(*ProviderInstaller).listProviderVersions(0xc00003a7e0, 0xc00022c529, 0x3, 0x1e7474c, 0x1, 0x1e92a34, 0x15, 0xc000050570, 0xc000050500, 0xc0001feca8)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/plugin/discovery/get.go:477 +0x7e
github.com/hashicorp/terraform/plugin/discovery.(*ProviderInstaller).Get(0xc00003a7e0, 0xc00022c529, 0x3, 0x1e7474c, 0x1, 0x1e92a34, 0x15, 0xc0000acb88, 0x1, 0x1, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/plugin/discovery/get.go:125 +0xde
github.com/hashicorp/terraform/command.(*InitCommand).getProviders(0xc000486380, 0xc000298a80, 0xc0000ac0b8, 0x0, 0xc001062320, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/init.go:530 +0x4c5
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc000486380, 0xc0000b2020, 0x5, 0x5, 0xc0003b80c0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/init.go:347 +0x102d
github.com/mitchellh/cli.(*CLI).Run(0xc000350280, 0xc000350280, 0xc00051fd90, 0x1)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:239 +0xc33
main.realMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:103 +0xb4
main.main()
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:39 +0x3b
```

### Expected Behavior
Build completes. (On immediate subsequent run, no changes, works fine. Has worked dozens of times prior, also.) Fluke issue.

### Actual Behavior
Terraform crashed during build.

### Steps to Reproduce
Promoted build from lower environment, repeated less than 1 minute later and it worked fine.

### Additional Context
No one has ever seen this before on this system.

### References
None known.

**Comment by apparentlymart** [comment]
Hi @cmorley-chwy! Sorry for this crash, and thanks for reporting it.

This seems like a relatively straightforward implementation error in some code that was intending to just present an error message anyway, and so even if it hadn't panicked it would still have failed with an error message promptly afterwards:

https://github.com/hashicorp/terraform/blob/85024d3100126de36331c6982bfaac02cdab9e76/registry/client.go#L410-L425

I think the problem here is that in some situations `resp` can be `nil`, as we can see on line 412, but then the error message formatter on line 421/422 unconditionally tries to access a `.StatusCode` field from it, which will fail as you reported here if `resp` is `nil`.

The specific source location mentioned in this stack trace no longer exists in Terraform v0.13 or later because we refactored the provider installer as part of introducing support for automatic installation of third-party providers, but it looks like this same function exists as part of the new installer:

https://github.com/hashicorp/terraform/blob/e5538693ced0dc42bb90a3919875cb8bbd625736/internal/getproviders/registry_client.go#L470-L493

Fortunately, it seems like this new version no longer has the bug you encountered: it checks whether `resp != nil` and uses a different strategy to build the error message when it's `nil`.

Since the bug seems to already be fixed in modern Terraform, we're no longer actively maintaining v0.12, and the panic is just masking a situation where Terraform would've failed with an error message anyway, I'm going to close this. Thanks again for reporting it, though! It's nice to confirm that the bug was already fixed in an earlier commit.

**Comment by cmorley-chwy** [comment]
Thanks!
