### ISSUE TITLE
Encountering a crash with Terraform cloud

### ISSUE THREAD

**Issue by chrisuehlinger** [hashicorp/terraform#28045]
I've been using Terraform cloud for the past several months fairly successfully. This afternoon I changed a vairable from true to false (and changed nothing else) and started encountering crashes. I was using 0.14.4, and after the crashes started I tried updating to 0.14.8 (which also crashed with the same message). Here's an output that I copied from the console (which indicated I should file an issue here)

```
Terraform v0.14.4
Configuring remote state backend...
Initializing Terraform configuration...
cloudflare_zone.show_dns_zone: Refreshing state... [id=b383eaa2ecadfdfdb70fd3c49a3b6513]
random_password.jwt_secret: Refreshing state... [id=none]
random_password.stream_secret: Refreshing state... [id=none]
random_password.mongo_password: Refreshing state... [id=none]
random_password.janus_api_key: Refreshing state... [id=none]
module.janus[0].aws_iam_role.janus_role: Refreshing state... [id=hotel-janus-role]
aws_key_pair.show_key_pair: Refreshing state... [id=hotel-key]
module.s3_resources.aws_s3_bucket_object.live_folder: Refreshing state... [id=live/]
module.s3_resources.aws_s3_bucket.secrets: Refreshing state... [id=hotel-secret]
module.janus[0].aws_security_group.janus_security_group: Refreshing state... [id=sg-00b952d55e06efebc]
module.s3_resources.aws_s3_bucket.show_site_bucket: Refreshing state... [id=hotelfantastic.live]
module.s3_resources.cloudflare_page_rule.media_permacache_rule: Refreshing state... [id=18a892318bca1a7f6545e8f19aeb609e]
cloudflare_zone_settings_override.show_cdn_settings: Refreshing state... [id=b383eaa2ecadfdfdb70fd3c49a3b6513]
module.s3_resources.cloudflare_page_rule.html_noncache_rule: Refreshing state... [id=682ebd6239f61ca7c67ad18865930d38]
module.s3_resources.cloudflare_page_rule.stream_permacache_rule: Refreshing state... [id=3d1d3b800d5f20928b3ba5301b610e5f]
module.janus[0].aws_iam_instance_profile.janus_profile: Refreshing state... [id=hotel-janus-profile]
module.s3_resources.cloudflare_record.show_domain_record: Refreshing state... [id=6c468e793278f92b758c04d711aeb2de]
module.janus[0].aws_s3_bucket_object.janus_config["janus.jcfg.sample.in"]: Refreshing state... [id=/janus-conf/janus.jcfg.sample.in]
module.janus[0].aws_s3_bucket_object.janus_config["janus.transport.nanomsg.jcfg.sample"]: Refreshing state... [id=/janus-conf/janus.transport.nanomsg.jcfg.sample]
module.janus[0].aws_s3_bucket_object.janus_config["janus.plugin.lua.jcfg.sample.in"]: Refreshing state... [id=/janus-conf/janus.plugin.lua.jcfg.sample.in]
module.janus[0].aws_s3_bucket_object.janus_config["janus.plugin.videocall.jcfg"]: Refreshing state... [id=/janus-conf/janus.plugin.videocall.jcfg]
module.janus[0].aws_s3_bucket_object.janus_config["janus.logger.jsonlog.jcfg.sample"]: Refreshing state... [id=/janus-conf/janus.logger.jsonlog.jcfg.sample]
module.janus[0].aws_iam_role_policy.janus_policy: Refreshing state... [id=hotel-janus-role:hotel-janus-policy]
module.janus[0].aws_s3_bucket_object.janus_config["janus.eventhandler.sampleevh.jcfg.sample"]: Refreshing state... [id=/janus-conf/janus.eventhandler.sampleevh.jcfg.sample]
module.janus[0].aws_s3_bucket_object.janus_config["janus.transport.rabbitmq.jcfg.sample"]: Refreshing state... [id=/janus-conf/janus.transport.rabbitmq.jcfg.sample]
module.janus[0].aws_s3_bucket_object.janus_config["janus.plugin.recordplay.jcfg.sample.in"]: Refreshing state... [id=/janus-conf/janus.plugin.recordplay.jcfg.sample.in]
module.janus[0].aws_s3_bucket_object.janus_config["janus.plugin.voicemail.jcfg.sample.in"]: Refreshing state... [id=/janus-conf/janus.plugin.voicemail.jcfg.sample.in]
module.janus[0].aws_s3_bucket_object.janus_config["janus.plugin.nosip.jcfg.sample"]: Refreshing state... [id=/janus-conf/janus.plugin.nosip.jcfg.sample]
module.janus[0].aws_s3_bucket_object.janus_config["janus.jcfg"]: Refreshing state... [id=/janus-conf/janus.jcfg]
module.janus[0].aws_s3_bucket_object.janus_config["janus.eventhandler.wsevh.jcfg.sample"]: Refreshing state... [id=/janus-conf/janus.eventhandler.wsevh.jcfg.sample]
module.janus[0].aws_s3_bucket_object.janus_config["janus.plugin.textroom.jcfg.sample"]: Refreshing state... [id=/janus-conf/janus.plugin.textroom.jcfg.sample]
module.janus[0].aws_s3_bucket_object.janus_config["janus.transport.mqtt.jcfg.sample"]: Refreshing state... [id=/janus-conf/janus.transport.mqtt.jcfg.sample]
module.janus[0].aws_s3_bucket_object.janus_config["janus.transport.http.jcfg"]: Refreshing state... [id=/janus-conf/janus.transport.http.jcfg]
module.janus[0].aws_s3_bucket_object.janus_config["janus.plugin.duktape.jcfg.sample.in"]: Refreshing state... [id=/janus-conf/janus.plugin.duktape.jcfg.sample.in]
module.janus[0].aws_s3_bucket_object.janus_config["janus.plugin.audiobridge.jcfg"]: Refreshing state... [id=/janus-conf/janus.plugin.audiobridge.jcfg]
module.janus[0].aws_s3_bucket_object.janus_config["janus.transport.pfunix.jcfg.sample"]: Refreshing state... [id=/janus-conf/janus.transport.pfunix.jcfg.sample]
module.janus[0].aws_s3_bucket_object.janus_config["janus.plugin.sip.jcfg.sample"]: Refreshing state... [id=/janus-conf/janus.plugin.sip.jcfg.sample]
module.janus[0].aws_s3_bucket_object.janus_config["janus.plugin.echotest.jcfg.sample"]: Refreshing state... [id=/janus-conf/janus.plugin.echotest.jcfg.sample]
module.janus[0].aws_s3_bucket_object.janus_config["janus.eventhandler.nanomsgevh.jcfg.sample"]: Refreshing state... [id=/janus-conf/janus.eventhandler.nanomsgevh.jcfg.sample]
module.janus[0].aws_s3_bucket_object.janus_config["janus.eventhandler.mqttevh.jcfg.sample"]: Refreshing state... [id=/janus-conf/janus.eventhandler.mqttevh.jcfg.sample]
module.janus[0].aws_s3_bucket_object.janus_config["janus.plugin.streaming.jcfg"]: Refreshing state... [id=/janus-conf/janus.plugin.streaming.jcfg]
module.janus[0].aws_s3_bucket_object.janus_config["janus.plugin.videoroom.jcfg"]: Refreshing state... [id=/janus-conf/janus.plugin.videoroom.jcfg]
module.janus[0].aws_s3_bucket_object.janus_config["janus.transport.websockets.jcfg"]: Refreshing state... [id=/janus-conf/janus.transport.websockets.jcfg]
module.janus[0].aws_s3_bucket_object.janus_config["janus.eventhandler.rabbitmqevh.jcfg.sample"]: Refreshing state... [id=/janus-conf/janus.eventhandler.rabbitmqevh.jcfg.sample]
aws_s3_bucket_object.promenade_config: Refreshing state... [id=service-secrets/promenade-config.json]
module.janus[0].aws_spot_instance_request.janus_service[0]: Refreshing state... [id=sir-62csj9hk]

Error: rpc error: code = Canceled desc = context canceled



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Canceled desc = context canceled



Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x103cdac]
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: goroutine 60 [running]:
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareRecordRead(0xc0000edb20, 0x13417c0, 0xc0005560c0, 0xc0000edb20, 0x0)
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_record.go:442 +0xacc
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0000eac60, 0xc00049b680, 0x13417c0, 0xc0005560c0, 0xc0000adac0, 0x0, 0x0)
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema/resource.go:460 +0x129
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0000acc28, 0x1516240, 0xc000738e10, 0xc000730480, 0xc0000acc28, 0xc000738e10, 0xc000016ba0)
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/helper/plugin/grpc_provider.go:525 +0x3dd
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x12fd8c0, 0xc0000acc28, 0x1516240, 0xc000738e10, 0xc000730420, 0x0, 0x1516240, 0xc000738e10, 0xc00072ad80, 0x232)
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/tfplugin5/tfplugin5.pb.go:3269 +0x214
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000330c40, 0x1521a00, 0xc000001980, 0xc000109300, 0xc00065ab40, 0x1c0c510, 0x0, 0x0, 0x0)
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	google.golang.org/grpc@v1.30.0/server.go:1171 +0x522
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: google.golang.org/grpc.(*Server).handleStream(0xc000330c40, 0x1521a00, 0xc000001980, 0xc000109300, 0x0)
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	google.golang.org/grpc@v1.30.0/server.go:1494 +0xcc5
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000036200, 0xc000330c40, 0x1521a00, 0xc000001980, 0xc000109300)
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	google.golang.org/grpc@v1.30.0/server.go:834 +0xa5
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-03-11T01:19:43.972Z [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	google.golang.org/grpc@v1.30.0/server.go:832 +0x1fd
2021-03-11T01:19:43.974Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/2.19.1/linux_amd64/terraform-provider-cloudflare_v2.19.1 pid=1700 error="exit status 2"
2021/03/11 01:19:43 [TRACE] vertex "cloudflare_zone_settings_override.show_cdn_settings": visit complete
2021/03/11 01:19:43 [TRACE] vertex "cloudflare_zone_settings_override.show_cdn_settings": dynamic subgraph encountered errors
2021/03/11 01:19:43 [TRACE] vertex "cloudflare_zone_settings_override.show_cdn_settings": visit complete
2021/03/11 01:19:43 [TRACE] vertex "cloudflare_zone_settings_override.show_cdn_settings (expand)": dynamic subgraph encountered errors
2021/03/11 01:19:43 [TRACE] vertex "cloudflare_zone_settings_override.show_cdn_settings (expand)": visit complete
2021/03/11 01:19:43 [TRACE] vertex "module.s3_resources.cloudflare_record.show_domain_record": visit complete
2021/03/11 01:19:43 [TRACE] vertex "module.s3_resources.cloudflare_record.show_domain_record": dynamic subgraph encountered errors
2021/03/11 01:19:43 [TRACE] vertex "module.s3_resources.cloudflare_record.show_domain_record": visit complete
2021/03/11 01:19:43 [TRACE] vertex "module.s3_resources.cloudflare_record.show_domain_record (expand)": dynamic subgraph encountered errors
2021/03/11 01:19:43 [TRACE] vertex "module.s3_resources.cloudflare_record.show_domain_record (expand)": visit complete
2021/03/11 01:19:43 [TRACE] dag/walk: upstream of "module.s3_resources (close)" errored, so skipping
2021-03-11T01:19:43.974Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-03-11T01:19:44.204Z [INFO]  plugin.terraform-provider-aws_v3.31.0_x5: 2021/03/11 01:19:44 [DEBUG] Setting Security Group IDs: []string{"sg-00b952d55e06efebc"}: timestamp=2021-03-11T01:19:44.204Z
2021-03-11T01:19:44.204Z [INFO]  plugin.terraform-provider-aws_v3.31.0_x5: 2021/03/11 01:19:44 [DEBUG] Setting Security Group Names: []string{"hotel_janus_service_sg"}: timestamp=2021-03-11T01:19:44.204Z
2021/03/11 01:19:44 [TRACE] EvalWriteState: using RefreshState for module.janus[0].aws_spot_instance_request.janus_service[0]
2021/03/11 01:19:44 [TRACE] EvalWriteState: writing current state object for module.janus[0].aws_spot_instance_request.janus_service[0]
2021/03/11 01:19:44 [TRACE] EvalWriteDiff: recorded Delete change for module.janus[0].aws_spot_instance_request.janus_service[0]
2021/03/11 01:19:44 [TRACE] EvalWriteState: removing state object for module.janus[0].aws_spot_instance_request.janus_service[0]
2021/03/11 01:19:44 [TRACE] vertex "module.janus[0].aws_spot_instance_request.janus_service[0] (orphan)": visit complete
2021/03/11 01:19:44 [TRACE] vertex "module.janus.aws_spot_instance_request.janus_service (expand)": dynamic subgraph completed successfully
2021/03/11 01:19:44 [TRACE] vertex "module.janus.aws_spot_instance_request.janus_service (expand)": visit complete
2021/03/11 01:19:44 [TRACE] dag/walk: visiting "module.janus.cloudflare_record.janus (expand)"
2021/03/11 01:19:44 [TRACE] dag/walk: visiting "module.janus.cloudflare_record.janus_numbered (expand)"
2021/03/11 01:19:44 [TRACE] vertex "module.janus.cloudflare_record.janus (expand)": starting visit (*terraform.nodeExpandPlannableResource)
2021/03/11 01:19:44 [TRACE] vertex "module.janus.cloudflare_record.janus_numbered (expand)": starting visit (*terraform.nodeExpandPlannableResource)
2021/03/11 01:19:44 [TRACE] vertex "module.janus.cloudflare_record.janus (expand)": expanding dynamic subgraph
2021/03/11 01:19:44 [TRACE] vertex "module.janus.cloudflare_record.janus_numbered (expand)": expanding dynamic subgraph
2021/03/11 01:19:44 [TRACE] vertex "module.janus.cloudflare_record.janus (expand)": entering dynamic subgraph
2021/03/11 01:19:44 [TRACE] vertex "module.janus.cloudflare_record.janus_numbered (expand)": entering dynamic subgraph
2021/03/11 01:19:44 [TRACE] dag/walk: visiting "module.janus[0].cloudflare_record.janus (orphan)"
2021/03/11 01:19:44 [TRACE] vertex "module.janus[0].cloudflare_record.janus (orphan)": starting visit (*terraform.NodePlannableResourceInstanceOrphan)
2021/03/11 01:19:44 [TRACE] dag/walk: visiting "module.janus[0].cloudflare_record.janus_numbered[0] (orphan)"
2021/03/11 01:19:44 [TRACE] vertex "module.janus[0].cloudflare_record.janus_numbered[0] (orphan)": starting visit (*terraform.NodePlannableResourceInstanceOrphan)
2021/03/11 01:19:44 [TRACE] ReadResourceInstanceState: reading state for module.janus[0].cloudflare_record.janus
2021/03/11 01:19:44 [TRACE] dag/walk: visiting "provider[\"registry.terraform.io/hashicorp/aws\"] (close)"
2021/03/11 01:19:44 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/aws\"] (close)": starting visit (*terraform.graphNodeCloseProvider)
2021/03/11 01:19:44 [TRACE] GRPCProvider: Close
2021/03/11 01:19:44 [TRACE] UpgradeResourceState: schema version of module.janus[0].cloudflare_record.janus is still 1; calling provider "cloudflare" for any other minor fixups
2021/03/11 01:19:44 [TRACE] GRPCProvider: UpgradeResourceState
2021/03/11 01:19:44 [TRACE] vertex "module.janus[0].cloudflare_record.janus (orphan)": visit complete
2021/03/11 01:19:44 [TRACE] vertex "module.janus.cloudflare_record.janus (expand)": dynamic subgraph encountered errors
2021/03/11 01:19:44 [TRACE] vertex "module.janus.cloudflare_record.janus (expand)": visit complete
2021-03-11T01:19:44.208Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-03-11T01:19:44.211Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/3.31.0/linux_amd64/terraform-provider-aws_v3.31.0_x5 pid=1707
2021-03-11T01:19:44.211Z [DEBUG] plugin: plugin exited
2021/03/11 01:19:44 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/aws\"] (close)": visit complete
2021/03/11 01:19:44 [TRACE] ReadResourceInstanceState: reading state for module.janus[0].cloudflare_record.janus_numbered[0]
2021/03/11 01:19:44 [TRACE] UpgradeResourceState: schema version of module.janus[0].cloudflare_record.janus_numbered[0] is still 1; calling provider "cloudflare" for any other minor fixups
2021/03/11 01:19:44 [TRACE] GRPCProvider: UpgradeResourceState
2021/03/11 01:19:44 [TRACE] vertex "module.janus[0].cloudflare_record.janus_numbered[0] (orphan)": visit complete
2021/03/11 01:19:44 [TRACE] vertex "module.janus.cloudflare_record.janus_numbered (expand)": dynamic subgraph encountered errors
2021/03/11 01:19:44 [TRACE] vertex "module.janus.cloudflare_record.janus_numbered (expand)": visit complete
2021/03/11 01:19:44 [TRACE] dag/walk: upstream of "module.janus (close)" errored, so skipping
2021/03/11 01:19:44 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/03/11 01:19:44 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/cloudflare/cloudflare\"] (close)" errored, so skipping
2021/03/11 01:19:44 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/03/11 01:19:44 [INFO] backend/local: plan operation completed
2021-03-11T01:19:44.212Z [DEBUG] plugin: plugin exited
2021-03-11T01:19:44.213Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-03-11T01:19:44.215Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-03-11T01:19:44.217Z [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform pid=1610
2021-03-11T01:19:44.217Z [DEBUG] plugin: plugin exited
2021-03-11T01:19:44.218Z [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform pid=1670
2021-03-11T01:19:44.218Z [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

A bit of context: I use a flag variable I call `run_janus` to determine whether my Janus WebRTC servers (and their associated config files in S3) should be deployed or not.

**Comment by jbardin** [comment]
Hi @chrisuehlinger 

Thanks for filing the issue. The stack trace indicates this is a problem with the cloudflare provider. You can file an issue with that provider here: https://github.com/cloudflare/terraform-provider-cloudflare/issues

Thanks!
