### ISSUE TITLE
etcdv3 backend acceptance tests fail due to invalid type conversion

### ISSUE THREAD

**Issue by jasons42** [hashicorp/terraform#28096]
### Test Failure Output
```
FAIL: TestBackend (0.04s)
    backend_test.go:40: Cleaned up 0 keys.
    backend_test.go:40: Cleaned up 0 keys.
panic: can't convert []string{"http://127.0.0.1:2379"} to cty.Value [recovered]
        panic: can't convert []string{"http://127.0.0.1:2379"} to cty.Value

goroutine 7 [running]:
testing.tRunner.func1.2(0x19a5aa0, 0xc0004d9150)
        /usr/local/Cellar/go/1.16.2/libexec/src/testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc000412300)
        /usr/local/Cellar/go/1.16.2/libexec/src/testing/testing.go:1147 +0x4b6
panic(0x19a5aa0, 0xc0004d9150)
        /usr/local/Cellar/go/1.16.2/libexec/src/runtime/panic.go:965 +0x1b9
github.com/hashicorp/terraform/configs/hcl2shim.HCL2ValueFromConfigValue(0x196bda0, 0xc000482120, 0x1ac52cf, 0x6, 0xc0001e5d40, 0xc0004d9130)
        /Users/jsmith/dev/github.com/terraform/configs/hcl2shim/values.go:228 +0x7f7
github.com/hashicorp/terraform/configs/hcl2shim.HCL2ValueFromConfigValue(0x19b8060, 0xc0004a24b0, 0x2500000000000000, 0xc0001e5ea0, 0x25653c42b032cb7b, 0x10)
        /Users/jsmith/dev/github.com/terraform/configs/hcl2shim/values.go:222 +0x1d7
github.com/hashicorp/terraform/backend.TestWrapConfig(0xc0004a24b0, 0xc0004a24b0, 0x1ac52cf)
        /Users/jsmith/dev/github.com/terraform/backend/testing.go:66 +0x3b
github.com/hashicorp/terraform/backend/remote-state/etcdv3.TestBackend(0xc000412300)
        /Users/jsmith/dev/github.com/terraform/backend/remote-state/etcdv3/backend_test.go:62 +0x27d
testing.tRunner(0xc000412300, 0x1b0d508)
        /usr/local/Cellar/go/1.16.2/libexec/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
        /usr/local/Cellar/go/1.16.2/libexec/src/testing/testing.go:1239 +0x2b3
FAIL    github.com/hashicorp/terraform/backend/remote-state/etcdv3      0.481s
FAIL
```

### Expected Behavior
Acceptance tests should pass when run against a fresh etcdv3 instance.

### Actual Behavior
Acceptance tests fail due to an invalid type conversion.

### Steps to Reproduce
1. `helm install etcd bitnami/etcd --set auth.rbac.enabled=false` (installed in Minikube)
2. `kubectl port-forward --namespace default svc/etcd 2379:2379`
2. `TF_ACC=1 TF_ETCDV3_ENDPOINTS=http://127.0.0.1:2379 go test ./backend/remote-state/etcdv3`

**Comment by jasons42** [comment]
Also as a sidenote, is it expected that the etcdv3 acceptance tests do not run when opening a PR that modifies the etcd package?
