### ISSUE TITLE
Inconsistent list element types

### ISSUE THREAD

**Issue by michaelazhang** [hashicorp/terraform#28171]
### Terraform Version

0.12.29

### Terraform Configuration Files

main.tf:

```
8501 0c03 5185 2d87 348f fc4c 0107 fd13
b0b0 001f d585 e431 b602 cb49 620f ab87
5346 144b f05e 3478 a130 4674 1c56 2c2e
c0a1 fcc8 4510 15d9 bf52 a7e8 cd40 429a
fffb dc2c af12 6500 3c53 7dcc 63f6 c64b
67f9 ed8c 433d 785b e8e4 cc7b c2ad f176
96b7 a6f3 b608 8b9e 4e04 f835 f715 d858
8183 3c00 0d51 6a2a 31db d5ad 9b22 b490
7a05 43ae 7190 d8ff 3906 91f2 18e5 8c08
7edd 2316 ab9d de19 3ac2 3d09 d823 b471
7b89 77ba 6e1a 9d9f 6ff7 c888 1bd4 30b2
4682 8ae2 9a9a 1097 179d 7da8 f557 e1f6
cc9f e4c7 f7d0 a272 41bc a101 4fed e022
b5bd fc5b 7991 6663 c09e 06b1 03d7 c89a
4c5a a7e8 ea43 63a8 c44d e2f4 8f09 79ef
0d37 534c 6b49 8ee2 3e91 a3d8 d560 4ba2
9525 2092 8a76 71dd 75fe fd39 bfa0 04d2
c281 01bf ab88 8a7b 306c 5913 9950 31b7
b4e2 c1a4 aff0 476d 877d 1a17 5473 b329
8e75 0cae fa13 f060 808a c8e8 e110 7f87
246a 90d4 fb40 7d12 81e2 662b 1cd9 4eb8
d012 c7b4 5ee1 dd1b 1931 921f 9d3f 042f
93ef fbbb 5399 b429 8bd9 c837 1810 d3de
b3ea 789c b3f8 55d2 46ab f044 be5b 28c7
c64b 443f 0474 78ce 9405 6f77 e846 1b64
58ae 5fc3 7d54 ae00 f33c fffe d623 7fbf
00e1 4d17 e256 7b64 1f8a cdea 7ba8 6ce1
c8a5 80c5 930d 2986 2f76 2579 a779 85e9
e2e2 f0d2 d7cd 5690 873b eef2 e646 bd6a
eb45 9ae1 28df 2400 bb20 ff08 7796 5e10
c2aa 9d27 77a6 c816 7171 0ff5 5e53 ffe1
6af4 6feb 3632 2709 a4a1 36d1 cc62 7da0
ae83 ae18 84fb 3ba0 8fdf a9f0 9434 6ab6
605a 04d2 dd4e d999 b5de ed0c 50da bd0e
4049 90cc b995 81c8 2330 f605 071a 85be
c182 9cb0 992b 8857 3a1c 95ab 0924 19e8
d572 f712 fa1d 7d17 5818 d912 4eb3 3bab
7695 9b00 84db 8315 fabb a782 f761 a7d6
d8f8 315d d1ed cae2 08a5 86f2 1b30 c732
5f9d 05ca 52f6 a2f0 12d8 7236 6726 b267
ed16 e250 295c 40be 5395 aa54 5b00 f9f0
c807 3505 8f03 4725 e9c4 d83a 090a 7807
d355 df1f 3dc3 fb80 9b08 2fcb 4025 0a63
9fb9 e239 97fb db95 5c25 c122 6061 8b2c
5c0d 9a8c 7188 7969 2c0e 4b43 f41a af23
c28e 2a2e 7954 6c9b 8179 e81e 3f9e b3b3
2f93 cb0a 79fb 75f8 83fb 38ed 7dc2 fc93
aa9a 994c d022 bb40 ed46 4172 5470 a7f5
11f7 3e87 a41b 610b e4f5 4fc5 6410 0cad
b46a b8fb 3169 2b43 62b0 4e79 6572 bb60
7c98 eab0 7163 c303 64a3 120f c59d b339
4090 4c77 b5af 557c 1e02 3c76 7e8a c1ed
1704 d6fd ebd0 dcfa ec4f a5aa b061 bbde
9e66 4c69 294e f429 e371 eaaa 497f 4f0d
c43d 91f8 85b9 6cde 447f 00c7 11d4 1540
2774 04da f7ed 7230 0553 b529 c05e d206
d6d3 2044 2d00 9839 b10b cb1d ec57 fe32
3285 2fb1 9e56 1f70 7dee bdf7 491a 8bc2
f46b 6ecd 8aa5 ba8d f08f ec84 4622 e117
a19a e6a6 e1dc 5afa 90c3 abb0 0efd 5b95
81ea 0f93 a266 0c72 4d22 40c4 4635 d7d5
6a62 ab90 9474 d715 3ace afce 181b ae41
f17a 7297 68fb 7584 2202 1e0e 7948 a49a
b3b9 b8dc 7bc5 c221 2358 52a7 97a5 0907
53e2 6366 86c3 6188 9239 69ba 4a52 ea74
e1b0 6492 7b16 a58d 9d5e 0ff6 ce71 7403
51ab 4737 62d3 44d1 599e 389e f1dd acc8
4db8 85e5 bfce df74 fcc3 0c02 da10 83a9
c04e 6247 629f c351 4804 ceb0 6113 b07b
cea7 cc
```

definitions.json:
```
8501 0c03 5185 2d87 348f fc4c 0107 fb06
1f50 fc6f b518 8873 a594 d315 0365 4e31
1c4a 3839 6071 a9c7 41a3 75c3 09ca d382
7581 1ea3 4b29 29dc ba9d 67df 2c0a 83ae
08a6 b228 e18a 490d 4d09 33a7 55e6 de7d
d012 df88 8c06 29d9 6550 072b 677c 4284
706a 5a75 adb0 4d1f bdcf 0bdf 72ec 4d9a
1533 a24b 3a86 7cdf 29af 8bb1 b321 a8ce
a9c4 4273 6f34 5040 3e01 2631 7f79 ecdc
59c4 38c7 037f 9aa8 05d0 35fc f4b6 838e
fc8d 2b11 f01d 0336 0ecd a6bb 3e59 c0cd
2287 006b 0204 2110 089f 21dd 0c57 4841
9b9b cbe9 a23d 08ec b778 7b04 e8a7 fca9
d2db b3c7 0bd0 60f8 2943 2d75 035f 9e74
a130 dc1a 9564 66bc 3b17 6981 5e1c a780
4dcf 8274 c419 9b1a 894c aea5 8b73 7701
a24a dbe9 ee45 fe66 63f9 e50f e05f 39d2
c121 0128 7380 62a5 fce3 8d97 c5ef 94ff
5c93 9cdc e4d0 90c8 10cd 681d e076 246d
c913 b11b 9017 7174 7b05 e108 6cf7 84a0
8df7 e855 5eb4 9cb5 4e85 d61a 7066 828e
f00f ce33 fb76 08a6 179c 8b39 40af 7fef
9eb9 9142 d544 7532 ee9c 0dad 69e2 9578
f9ae 859f 0749 5b28 93cb 544a ca45 9864
2bb0 7f7c 2507 1f22 405d fab6 1e00 80db
5d91 59ae ccae fd1b 566f 701c e07d b07a
681d 6c17 9aa4 23da ec0d 2ffa 569f 5ffd
b30b c8eb 9061 5762 f83b dabf 31e4 8221
4add 6b12 1c2d eadb 3e52 2021 25e5 cf0d
103b 8440 d564 3818 61e3 0667 0161 3be1
f46c c06e fa5f 0d2c 882d 1400 c3ca d011
f55a 0681 7a09 d2d5 eb04 16ee a0e2 7712
a016 71d6 2e82 95be dece 3048 93b0 1e8a
8aef af35 0d0c 5f5c 79ed 8328 4b7c 7092
fd83 9fed ed6c bf42 c408 449b 0f47 761c
cdce 7d9b 7ef2 d6c4 8ba0 2a8d d11a ef10
5600 3355 412e fd69 ad8d 6d2e 7987 db86
4bc0 bcad 4f15 c633 1f34 430b b4b7 a57f
bd65 1c4a ba73 2262 a76d e5c1 b70d 6d3a
dfc2 4e0e cda1 86e4 deff fbe3 87c5 e72d
2048 e5df df12 4449 20b0 1d7c ac01 e35f
c72d 2665 6a9d fd10 0d47 7bd7 8dda 0f90
2888 16be 7369 2b9e 70b8 c27e e9fd 8f55
3dc0 bfd2 df27 0b3b c0cc f795 a0aa 345c
3358 58cd cae5 3e8d 8241 2a03 a06e a0c7
1657 8c9f d717 2226 870d 4cff 4d60 f5dc
786c a2de d419 7cdb 506a 7637 b08c 609e
8e97 f9
```

### Debug Output

```
2021-03-23T06:51:55.741Z
Starting regional planning   
   
2021-03-23T06:52:16.100Z
Running command [/bin/chown-and-run.sh, /usr/bin/terraform, init, -plugin-dir, /var/shepherd/plugins/, -no-color] on shepherd-worker-02303.node.ad2.r2   
   
2021-03-23T06:52:25.216Z
Initializing modules...   
- cavium-rules in modules/cavium-rules   
- images in modules/images   
- kaas in modules/kaas   
- limit_overrides in modules/limit_overrides   
- limits_definitions in modules/limits_definitions   
- limits_groups in modules/limits_groups   
- limits_values in modules/limits_values   
- lumberjack in modules/lumberjack   
- ob3_jump in modules/ob3-jump   
- pki in modules/pki   
- properties_definitions in modules/properties_definitions   
- properties_values in modules/properties_values   
- rqs in modules/rqs   
- secret_service in modules/secret_service   
- secret_vault in modules/secret-vault   
- service_instances_api in modules/instances   
- service_vcn in modules/service-vcn   
- service_vcn.private_lb in modules/load-balancer   
- service_vcn.service_lb in modules/load-balancer   
- splat in modules/splat   
- vcn-peering in modules/vcn-peering   
- wfaas in modules/wfaas   
   
Initializing the backend...   
   
Initializing provider plugins...   
   
The following providers do not have any version constraints in configuration,   
so the latest version was installed.   
   
To prevent automatic upgrades to new major versions that may contain breaking   
changes, it is recommended to add version = "..." constraints to the   
corresponding provider blocks in configuration, with the constraint strings   
suggested below.   
   
* provider.ad: version = "~> 1.0"   
* provider.capability: version = "~> 1.0"   
* provider.certificate: version = "~> 1.0"   
* provider.computeimagingadmin: version = "~> 1.0"   
* provider.consolefeature: version = "~> 1.0"   
* provider.dbcps: version = "~> 1.0"   
* provider.dns: version = "~> 1.0"   
* provider.flamingo: version = "~> 1.0"   
* provider.gate: version = "~> 1.0"   
* provider.grafana: version = "~> 1.5"   
* provider.internalbscp: version = "~> 1.0"   
* provider.internalcompute: version = "~> 1.0"   
* provider.jira: version = "~> 1.0"   
* provider.kaas: version = "~> 1.0"   
* provider.limit: version = "~> 1.0"   
* provider.lumberjack: version = "~> 1.0"   
* provider.netplan: version = "~> 1.0"   
* provider.oci: version = "~> 3.94"   
* provider.ocir: version = "~> 1.0"   
* provider.odo: version = "~> 1.0"   
* provider.okecluster: version = "~> 1.0"   
* provider.privateaccess: version = "~> 1.0"   
* provider.property: version = "~> 1.0"   
* provider.rqs: version = "~> 1.0"   
* provider.scanplatform: version = "~> 1.0"   
* provider.sccp: version = "~> 1.0"   
* provider.serviceprincipal: version = "~> 1.0"   
* provider.sms: version = "~> 1.0"   
* provider.splat: version = "~> 1.0"   
* provider.telemetry: version = "~> 1.0"   
* provider.tenancylookup: version = "~> 1.0"   
* provider.wfaas: version = "~> 1.0"   
   
Terraform has been successfully initialized!   
   
You may now begin working with Terraform. Try running "terraform plan" to see   
any changes that are required for your infrastructure. All Terraform commands   
should now work.   
   
If you ever set or change modules or backend configuration for Terraform,   
rerun this command to reinitialize your working directory. If you forget, other   
commands will detect it and remind you to do so if necessary.   
   
2021-03-23T06:52:25.394Z
Running command [/bin/chown-and-run.sh, /usr/bin/terraform, refresh, -input=false, -state, start.tfstate, -state-out, fresh.tfstate, -no-color] on shepherd-worker-02303.node.ad2.r2   
   
```
### Crash Output

```
panic: inconsistent list element types (cty.Object(map[string]cty.Type{"bypass_type_enforcement":cty.Bool, "default_max":cty.Number, "default_min":cty.Number, "default_value":cty.String, "description":cty.String, "group":cty.String, "is_quota":cty.Bool, "is_staged":cty.Bool, "name":cty.String, "options":cty.DynamicPseudoType, "public_name":cty.String, "scope":cty.String, "service":cty.String, "type":cty.String}) then cty.Object(map[string]cty.Type{"bypass_type_enforcement":cty.Bool, "default_max":cty.Number, "default_min":cty.Number, "default_value":cty.String, "description":cty.String, "group":cty.String, "is_quota":cty.Bool, "is_staged":cty.Bool, "name":cty.String, "options":cty.Tuple([]cty.Type{cty.String, cty.String}), "public_name":cty.String, "scope":cty.String, "service":cty.String, "type":cty.String}))   
   
goroutine 2226 [running]:   
github.com/zclconf/go-cty/cty.ListVal(0xc00082df40, 0x5, 0x5, 0xc001636360, 0xc000a31b10, 0x1, 0x1)   
/go/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/value_init.go:166 +0x4bf   
github.com/zclconf/go-cty/cty/convert.conversionTupleToList.func2(0x246a0c0, 0xc00244aba0, 0x1afe600, 0xc00244abc0, 0xc000a31b10, 0x1, 0x1, 0xc0000ce380, 0xc00219a050, 0xc0000cd950, ...)   
/go/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/convert/conversion_collection.go:267 +0x54a   
github.com/zclconf/go-cty/cty/convert.getConversion.func1(0x246a0c0, 0xc00244aba0, 0x1afe600, 0xc00244abc0, 0x0, 0x0, 0x0, 0x1b0f5a0, 0x3530781, 0x2469f40, ...)   
/go/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/convert/conversion.go:46 +0x1ad   
github.com/zclconf/go-cty/cty/convert.retConversion.func1(0x246a0c0, 0xc00244aba0, 0x1afe600, 0xc00244abc0, 0x0, 0x0, 0x0, 0x0, 0x1b0f5a0, 0x3530781)   
/go/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/convert/conversion.go:179 +0x6b   
github.com/hashicorp/hcl/v2/hclsyntax.(*ConditionalExpr).Value(0xc0005a82a0, 0xc0018e0880, 0x0, 0xc001ac1700, 0x1, 0x1, 0x0, 0x0, 0x0)   
/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/hclsyntax/expression.go:574 +0x11ea   
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc000fe3ae0, 0x2468e80, 0xc0005a82a0, 0x2469f80, 0x367d188, 0x0, 0x0, 0xc001ac1908, 0x1, 0x1, ...)   
/home/circleci/project/project/lang/eval.go:95 +0x1b3   
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateExpr(0xc00174d040, 0x2468e80, 0xc0005a82a0, 0x2469f80, 0x367d188, 0x0, 0x0, 0x0, 0xc00148b9f0, 0x434e2c, ...)   
/home/circleci/project/project/terraform/eval_context_builtin.go:279 +0x1e4   
github.com/hashicorp/terraform/terraform.(*EvalLocal).Eval(0xc00155e320, 0x249fea0, 0xc00174d040, 0x2, 0x2, 0xfb980d, 0x1c46ec0)   
/home/circleci/project/project/terraform/eval_local.go:43 +0x73a   
github.com/hashicorp/terraform/terraform.EvalRaw(0x24249c0, 0xc00155e320, 0x249fea0, 0xc00174d040, 0x1bc1420, 0x3530784, 0x1b24b60, 0xc00174f0f0)   
/home/circleci/project/project/terraform/eval.go:57 +0x131   
github.com/hashicorp/terraform/terraform.Eval(0x24249c0, 0xc00155e320, 0x249fea0, 0xc00174d040, 0xc00155e320, 0x24249c0, 0xc00155e320, 0x0)   
/home/circleci/project/project/terraform/eval.go:35 +0x4d   
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x1d680c0, 0xc0010a1bc0, 0x0, 0x0, 0x0)   
/home/circleci/project/project/terraform/graph.go:90 +0xf40   
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc002444e80, 0x1d680c0, 0xc0010a1bc0, 0xc000e99b80)   
/home/circleci/project/project/dag/walk.go:392 +0x353   
created by github.com/hashicorp/terraform/dag.(*Walker).Update   
/home/circleci/project/project/dag/walk.go:314 +0xa9b   
   
   
   
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!   
```

### Expected Behavior

There should be two kinds of limits. NUMERIC limits will not have options, set to be null. ENUM limits will have 2 options, each as a String.

### Actual Behavior

Plan failed with crash.

### Steps to Reproduce

terraform plan

### Additional Context

This is running in OCI Shepherd. Previously the config worked. It crashed after I added the Ternary operator `regional_values = var.execution_target.region.public_name == var.execution_target.additional_locals.home_region?... `. This is to ensure only to create resources in home regions.

**Comment by mildwonkey** [comment]
Hi @michaelazhang ! 
We aren't working on issues that are only present in terraform v0.12 (or v0.13) anymore. If this behavior in still present in the latest 0.14 release, please open a new issue with a simplified reproduction configuration so we can take a look - we've addressed a number of similar-looking panics and I'm hopeful that this has since been resolved. Thanks!

As a side note, I do not know how to read the configuration you've included in this issue. It's best if you can reproduce the problem in a simpler configuration that you can share directly in the issue, or as a gist.
