### ISSUE TITLE
Terraform crashes importing resource

### ISSUE THREAD

**Issue by derekgreer** [hashicorp/terraform#28197]
I received an error:

```
A resource with the ID "/subscriptions/ee5e21a4-eabf-4433-b676-e77f214d87f0/resourceGroups/in1_rsg_ep_auth_request/providers/Microsoft.Web/serverfarms/eharin1ue2apiasp" already exists
```

although this resource is no where to be found in the azure portal.  It's like it's in limbo or something.

When I try to import it, terraform crashes.

### Terraform Version

```
$ terraform --version
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/azurerm v2.52.0
```

### Terraform Configuration Files

```terraform
resource "azurerm_app_service_plan" "api" {
  name                        = local.app_service_plan_name
  location                    = module.region.location
  resource_group_name         = data.azurerm_resource_group.resource_group.name
  kind                        = "Linux"
  reserved                    = true
  app_service_environment_id = var.app_service_plan_id

  sku {
    tier     = "Isolated"
    size     = "I1"
    capacity  = 2
  }

  lifecycle {
    ignore_changes = [
      tags,
    ]
  }

  timeouts {
    create = "6h"
    update = "4h"
    delete = "4h"
  }
}
```

### Crash Output
[crash.log](https://github.com/hashicorp/terraform/files/6205003/crash.log)

### Actual Behavior
```
$ terraform import azurerm_app_service_plan.api '/subscriptions/ee5e21a4-eabf-4433-b676-e77f214d87f0/resourceGroups/in1_
rsg_ep_auth_request/providers/Microsoft.Web/serverfarms/eharin1ue2apiasp'
Acquiring state lock. This may take a few moments...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x1a412f1]

goroutine 16 [running]:
github.com/hashicorp/terraform/backend/remote-state/azure.(*RemoteClient).Lock(0xc0005500f0, 0xc000117b00, 0xc0005500f0, 0x186742d04c0, 0xc0005500f0, 0x1)
        /home/circleci/project/project/backend/remote-state/azure/client.go:154 +0x291
github.com/hashicorp/terraform/states/remote.(*State).Lock(0xc00064d3e0, 0xc000117b00, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/states/remote/state.go:208 +0xc4
github.com/hashicorp/terraform/states/statemgr.LockWithContext(0x33bc900, 0xc00064d440, 0x186742d0498, 0xc00064d3e0, 0xc000117b00, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/states/statemgr/locker.go:76 +0x88
github.com/hashicorp/terraform/command/clistate.(*locker).Lock.func1(0x0, 0x0)
        /home/circleci/project/project/command/clistate/state.go:116 +0x65
github.com/hashicorp/terraform/helper/slowmessage.Do.func1(0xc00064d4a0, 0xc00053b140)
        /home/circleci/project/project/helper/slowmessage/slowmessage.go:20 +0x2e
created by github.com/hashicorp/terraform/helper/slowmessage.Do
        /home/circleci/project/project/helper/slowmessage/slowmessage.go:19 +0x7e



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by Tbohunek** [comment]
@derekgreer do you successfully list the resource with Az CLI `az appservice plan show`?

**Comment by arielrolfo** [comment]
I'm facing the same situation with Terraform v0.14.6, I'm not using any azure resource other than the backend to store my tfstate.
