### ISSUE TITLE
rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by tonijofiu** [hashicorp/terraform#28196]
### Terraform Version

``` 
> terraform --version
0.13.5
```

### Terraform (and AzureRM Provider) Version

``` 
2.21.0
```

### Crash Output
```
rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: [signal 0xc0000005 code=0x0 addr=0x8 pc=0x330749a]
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: 
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: goroutine 665 [running]:
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure.FlattenArmFrontDoorCustomHttpsConfiguration(0xc000bf9310, 0xc00109a3f0, 0xc0009616a0, 0xc, 0xc0014b8548, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure/frontdoor_custom_https_configuration.go:67 +0x67a
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/frontdoor.flattenArmFrontDoorFrontendEndpoint(0x4e692a0, 0xc0012dc180, 0xc000bf94f0, 0xc000d6c1f3, 0x15, 0xc000960210, 0xe, 0x3fecfc0, 0xc000a52f00, 0xc000bae870, ...)
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/frontdoor/frontdoor_resource.go:1251 +0x3f4
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/frontdoor.flattenArmFrontDoorFrontendEndpoints(0x4e692a0, 0xc0012dc180, 0xc0015bf4a0, 0xc000d6c1f3, 0x15, 0xc000960210, 0xe, 0x3fecfc0, 0xc000a52f00, 0x6fc23ac00, ...)
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/frontdoor/frontdoor_resource.go:1198 +0x18f
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/frontdoor.resourceArmFrontDoorRead(0xc0005ce930, 0x3fecfc0, 0xc000a52f00, 0x0, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/frontdoor/frontdoor_resource.go:637 +0xdbb
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004fa990, 0xc0012fc6e0, 0x3fecfc0, 0xc000a52f00, 0xc0000cb4b8, 0x0, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:460 +0x120
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000006f90, 0x4e692e0, 0xc001aaeab0, 0xc000cf4c60, 0xc000006f90, 0xc001aaeab0, 0xc001d49b78)
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3df
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x43e2c20, 0xc000006f90, 0x4e692e0, 0xc001aaeab0, 0xc000cf4c00, 0x0, 0x4e692e0, 0xc001aaeab0, 0xc0017d0000, 0x14cd)
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3269 +0x21e
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000502c00, 0x4ea6b00, 0xc000184300, 0xc000134600, 0xc000812120, 0x7c96a10, 0x0, 0x0, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1024 +0x508
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: google.golang.org/grpc.(*Server).handleStream(0xc000502c00, 0x4ea6b00, 0xc000184300, 0xc000134600, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1313 +0xd44
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000a5c1b0, 0xc000502c00, 0x4ea6b00, 0xc000184300, 0xc000134600)
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:722 +0xa8
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:720 +0xa8
[ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
[ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
[TRACE] [walkRefresh] Exiting eval tree: azurerm_frontdoor.example-fd
[TRACE] vertex "azurerm_frontdoor.example-fd": visit complete
[TRACE] vertex "azurerm_frontdoor.example-fd": dynamic subgraph encountered errors
[TRACE] vertex "azurerm_frontdoor.example-fd": visit complete
[TRACE] vertex "azurerm_frontdoor.example-fd (expand)": dynamic subgraph encountered errors
[TRACE] vertex "azurerm_frontdoor.example-fd (expand)": visit complete
[TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)" errored, so skipping
[TRACE] dag/walk: upstream of "root" errored, so skipping
[DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/azurerm/2.21.0/windows_amd64/terraform-provider-azurerm_v2.21.0_x5.exe pid=3504 error="exit status 2"
[DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

 Terraform crashed! This is always indicative of a bug within Terraform.
 A crash log has been placed at "crash.log" relative to your current
 working directory. It would be immensely helpful if you could please
 report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
 sensitive information that must be redacted before it is safe to share 
on the issue tracker.
 
[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

[crash.log](https://github.com/hashicorp/terraform/files/6204663/crash.log)

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

or
1. `terraform init`
2. `terraform apply`

### Additional Context
I tested it on Azure Devops vs2017-win2016 agent and from my local ubuntu 20.04 environment.
The end result is the same.

**Comment by apparentlymart** [comment]
Hi @tonijofiu! Sorry for this crash, and thanks for reporting it.

Unfortunately in this case it seems that Terraform incorrectly attributed this crash to itself, because I can see in the panic stack trace that the problem originated in the AzureRM provider instead of in Terraform core:

```
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure.FlattenArmFrontDoorCustomHttpsConfiguration(0xc000bf9310, 0xc00109a3f0, 0xc0009616a0, 0xc, 0xc0014b8548, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.21.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure/frontdoor_custom_https_configuration.go:67 +0x67a
```

That code belongs to [the AzureRM provider repository](https://github.com/terraform-providers/terraform-provider-azurerm) rather than to this repository. It'd be very helpful if you would open a similar issue over in that repository so that the AzureRM provider team can review it. When I searched in that repository I only saw one issue related to the "frontdoor" service and it didn't seem related to this crash, so I think this is a new problem that hasn't been reported there before.

Since there is nothing we could change in _this_ repository to avoid the crash you saw here, I'm going to close this issue. Thanks again!
