### ISSUE TITLE
SSM Crash on sensitive list of SSM parameters.

### ISSUE THREAD

**Issue by dbteku** [hashicorp/terraform#28469]
I'm getting crashes when using the sensitive keyword on this variable: 

```hcl
variable parameter_values {
  type        = list(object({
      name        = string
      description = string
      decrypted   = string
  }))
  description = "The values to apply to the parameter store entries for slyce applications."
  sensitive   = true
}
```

This is the resrouce I am using it on:
```hcl
resource "aws_ssm_parameter" "cforce_ssm_entries" {
    count = length(var.parameter_values)

    name        = "${var.module}.${var.parameter_values[count.index].name}"
    description = var.parameter_values[count.index].description
    type        = "SecureString"
    value       = var.parameter_values[count.index].decrypted

    tags = {
        Name        = "slyce-ssm-cforce-${var.environment}"
        Environment = var.environment
        Terraform   = "modules/ssm/cforce"
    }
}
```

Here is the output:

And for the crash log => [Click Here](https://pastebin.com/PhqvaV11)

```bash
[terragrunt] [/mnt/c/Users/dboyce/Documents/nexio/devops/terraform/deploys/us-east-1/devopslocal/ssm/cforce] 2021/04/21 09:47:59 Running command: terraform init -lock-timeout=20m

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Installing hashicorp/aws v3.37.0...
- Installed hashicorp/aws v3.37.0 (signed by HashiCorp)

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
[terragrunt] 2021/04/21 09:48:05 Running command: terraform plan -lock-timeout=20m -out=tf.plan
panic: value is marked, so must be unmarked first

goroutine 184 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.AsBigFloat(0x2c50ee0, 0xc00005041f, 0x2547ae0, 0xc000578640, 0x2c50e01)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/value_ops.go:1249 +0x4f
github.com/zclconf/go-cty/cty/gocty.fromCtyNumber(0x2c50ee0, 0xc00005041f, 0x2547ae0, 0xc000578640, 0x2370b60, 0xc001e50080, 0x182, 0xc002237518, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/gocty/out.go:124 +0x4d
github.com/zclconf/go-cty/cty/gocty.fromCtyValue(0x2c50ee0, 0xc00005041f, 0x2547ae0, 0xc000578640, 0x22ee000, 0xc001e50080, 0x16, 0xc002237518, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/gocty/out.go:85 +0x965
github.com/zclconf/go-cty/cty/gocty.FromCtyValue(0x2c50ee0, 0xc00005041f, 0x2547ae0, 0xc000578640, 0x22ee000, 0xc001e50080, 0x0, 0x0)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/gocty/out.go:43 +0x114
github.com/hashicorp/terraform/terraform.evaluateCountExpressionValue(0x2c4fa60, 0xc000716000, 0x2c8c480, 0xc001fee0d0, 0x26102c0, 0x1, 0xc001fab860, 0xc0000c7918, 0x985f8b, 0x26102c0, ...)
        /home/circleci/project/project/terraform/eval_count.go:78 +0x49c
github.com/hashicorp/terraform/terraform.evaluateCountExpression(0x2c4fa60, 0xc000716000, 0x2c8c480, 0xc001fee0d0, 0x0, 0x0, 0x4ee3ce, 0xc00023c0b2)
        /home/circleci/project/project/terraform/eval_count.go:23 +0x67
github.com/hashicorp/terraform/terraform.(*NodeAbstractResource).writeResourceState(0xc0008e8e00, 0x2c8c480, 0xc001fee0d0, 0x0, 0x0, 0x0, 0x4d, 0xc000054f40, 0x11, 0xc000054fc0, ...)
        /home/circleci/project/project/terraform/node_resource_abstract.go:320 +0x616
github.com/hashicorp/terraform/terraform.(*NodePlannableResource).Execute(0xc00022a2a0, 0x2c8c480, 0xc001fee0d0, 0x3d35402, 0x0, 0x0)
        /home/circleci/project/project/terraform/node_resource_plan.go:188 +0xce
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc001f9b5f0, 0x2c8c480, 0xc001fee0d0, 0x7f652014acb0, 0xc00022a2a0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbc
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x27a7560, 0xc00022a2a0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph.go:59 +0x962
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0005f2d80, 0x27a7560, 0xc00022a2a0, 0xc000b545c0)
        /home/circleci/project/project/dag/walk.go:387 +0x375
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /home/circleci/project/project/dag/walk.go:309 +0x1246



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by dbteku** [comment]
Ah it looks like I was using v `14.6`. I upgraded to terraform 15 and it fixed the issue. I apologize.

**Comment by alisdair** [comment]
No problem, thanks for responding!
