### ISSUE TITLE
Missing closing quote after resource type crashes 0.15.1

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform#28587]
### Terraform Version

Originally https://github.com/hashicorp/terraform-provider-aws/issues/19189.

```
Terraform v0.15.1
on darwin_amd64
```

### Terraform Configuration Files

N.B. Missing closing `"` after resource type.

```terraform
resource "aws_cloudwatch_log_group "test" {
    name = "test"
}
```

### Crash Output

```console
% terraform plan   
panic: runtime error: slice bounds out of range [:-135]

goroutine 1 [running]:
github.com/hashicorp/terraform/command/format.appendSourceSnippets(0xc0008ec2a0, 0xc0003187d0, 0xc0003a0870)
	/home/circleci/project/project/command/format/diagnostic.go:243 +0xa70
github.com/hashicorp/terraform/command/format.DiagnosticFromJSON(0xc0003187d0, 0xc0003a0870, 0xc8, 0xc0003187d0, 0xc00086fb60)
	/home/circleci/project/project/command/format/diagnostic.go:77 +0x225
github.com/hashicorp/terraform/command/format.Diagnostic(0x3835bc8, 0xc0003186e0, 0xc00086fb60, 0xc0003a0870, 0xc8, 0x1fb, 0x0)
	/home/circleci/project/project/command/format/diagnostic.go:30 +0x65
github.com/hashicorp/terraform/command/views.(*View).Diagnostics(0xc000480440, 0xc0005ffe00, 0x6, 0x6)
	/home/circleci/project/project/command/views/view.go:91 +0x3da
github.com/hashicorp/terraform/command/views.(*PlanHuman).Diagnostics(0xc0003a0e90, 0xc0005ffe00, 0x6, 0x6)
	/home/circleci/project/project/command/views/plan.go:61 +0x4c
github.com/hashicorp/terraform/command.(*PlanCommand).Run(0xc0003a8540, 0xc00004c030, 0x0, 0x0, 0xc0003a0990)
	/home/circleci/project/project/command/plan.go:69 +0x969
github.com/mitchellh/cli.(*CLI).Run(0xc00087e140, 0xc0003a4f60, 0x33b7c41, 0x4)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
main.wrappedMain(0x0)
	/home/circleci/project/project/main.go:384 +0x1112
main.realMain(0x0)
	/home/circleci/project/project/main.go:115 +0x554
main.main()
	/home/circleci/project/project/main.go:58 +0x25
```

**Comment by alisdair** [comment]
Thanks for reporting this, @ewbankkit! There's a pending fix in #28598.
