### ISSUE TITLE
Terraform crashes when using a custom working directory in Terraform Cloud

### ISSUE THREAD

**Issue by jstachowiak** [hashicorp/terraform#28631]
### Terraform Version

```
Terraform v0.15.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.57.0
```

### Crash Output

```
Failed running command "cd '/terraform/1-control-plane' && envdir /env terraform show -json /terraform/terraform.tfplan" (exit 2)
Output: panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.GetAttr(0x2c6b4b0, 0xc0003247f0, 0x0, 0x0, 0xc00095f8e0, 0x19, 0x1, 0x2, 0x203000, 0x203000)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.8.3/cty/value_ops.go:760 +0x416
github.com/hashicorp/terraform/configs/configschema.(*Block).ValueMarks(0xc000ca9c20, 0x2c6b4b0, 0xc0003247f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40, 0x0, ...)
        /home/circleci/project/project/configs/configschema/marks.go:33 +0x545
github.com/hashicorp/terraform/command/jsonplan.(*plan).marshalResourceChanges(0xc000974a80, 0xc000fa6750, 0xc000802160, 0x0, 0x0)
        /home/circleci/project/project/command/jsonplan/plan.go:218 +0x1825
github.com/hashicorp/terraform/command/jsonplan.Marshal(0xc000743e10, 0xc0006b6990, 0xc000fa7c80, 0xc000802160, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/command/jsonplan/plan.go:124 +0x23f
github.com/hashicorp/terraform/command.(*ShowCommand).Run(0xc000396000, 0xc000130070, 0x1, 0x2, 0xc000336ab0)
        /home/circleci/project/project/command/show.go:152 +0x966
github.com/mitchellh/cli.(*CLI).Run(0xc0003743c0, 0xc000378480, 0x27e9055, 0x4)
        /go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
main.wrappedMain(0x0)
        /home/circleci/project/project/main.go:384 +0x1112
main.realMain(0x0)
        /home/circleci/project/project/main.go:115 +0x554
main.main()
        /home/circleci/project/project/main.go:58 +0x25




!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.639870799.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.639870799.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

There was no `crash.639870799.log` file.

### Steps to Reproduce

1. terraform plan

### Additional Context

Using Terraform Cloud as the backend.

**Comment by jbardin** [comment]
Closed via #28624
