### ISSUE TITLE
Crash when using bastion_port

### ISSUE THREAD

**Issue by bokysan** [hashicorp/terraform#28658]
Terraform crashes when using `bastion_port`.

### Terraform Configuration Files

```
terraform {
  required_version = ">= 0.15.3"
  required_providers {
    null = {
      source  = "hashicorp/null"
      version = ">=2.1.2"
    }
  }
}

resource "null_resource" "attach_volume" {
  count       = 3

  connection {
    bastion_host        = "bastion.example.org"
    bastion_port        = "20022"
    bastion_user        = "aaa"
    host                = "127.0.0.1"
    user                = "root"
    password            = "hello_world"
  }

  provisioner "file" {
    content     = "Hello world"
    destination = "/tmp/test.txt"
  }
}
```

## Stacktrace

```
panic: not a string

goroutine 338 [running]:
github.com/zclconf/go-cty/cty.Value.AsString(0x386d0f0, 0xc0001ae36f, 0x33c9f20, 0xc000ae3170, 0xc000227e00, 0x1d)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.8.3/cty/value_ops.go:1256 +0x1a5
github.com/hashicorp/terraform/communicator/ssh.decodeConnInfo(0x386d1d0, 0xc0008cca80, 0x3021c80, 0xc000ae35f0, 0xc000ae3590, 0x0, 0x0)
        /home/circleci/project/project/communicator/ssh/provisioner.go:130 +0x7fa
github.com/hashicorp/terraform/communicator/ssh.parseConnectionInfo(0x386d1d0, 0xc0008cc760, 0x3021c80, 0xc000ae3590, 0x4, 0xc000324878, 0xc0001ae380)
        /home/circleci/project/project/communicator/ssh/provisioner.go:150 +0xe5
github.com/hashicorp/terraform/communicator/ssh.New(0x386d1d0, 0xc0008cc760, 0x3021c80, 0xc000ae3590, 0x0, 0x0, 0x0)
        /home/circleci/project/project/communicator/ssh/communicator.go:90 +0x8e
github.com/hashicorp/terraform/communicator.New(0x386d1d0, 0xc0008cc370, 0x3021c80, 0xc000ae3500, 0x386d100, 0x55838f0, 0x8, 0x8)
        /home/circleci/project/project/communicator/communicator.go:62 +0x195
github.com/hashicorp/terraform/builtin/provisioners/file.(*provisioner).ProvisionResource(0xc0005fe7b0, 0x386d1d0, 0xc0008cc040, 0x3021c80, 0xc000ae3470, 0x386d1d0, 0xc0008cc370, 0x3021c80, 0xc000ae3500, 0x3812c60, ...)
        /home/circleci/project/project/builtin/provisioners/file/resource_provisioner.go:82 +0xde
github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).applyProvisioners(0xc000030a80, 0x38a3bc0, 0xc00071cfc0, 0xc0004d1620, 0x1, 0xc000cf0d80, 0x2, 0x2, 0x0, 0x47dec60)
        /home/circleci/project/project/terraform/node_resource_abstract_instance.go:1792 +0x895
github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).evalApplyProvisioners(0xc000030a80, 0x38a3bc0, 0xc00071cfc0, 0xc0004d1620, 0x1, 0x1, 0x0, 0xd, 0x385f418)
        /home/circleci/project/project/terraform/node_resource_abstract_instance.go:1643 +0x225
github.com/hashicorp/terraform/terraform.(*NodeApplyableResourceInstance).managedResourceExecute(0xc000ba9880, 0x38a3bc0, 0xc00071cfc0, 0x226100, 0x493b8e0, 0x0)
        /home/circleci/project/project/terraform/node_resource_apply_instance.go:295 +0x1145
github.com/hashicorp/terraform/terraform.(*NodeApplyableResourceInstance).Execute(0xc000ba9880, 0x38a3bc0, 0xc00071cfc0, 0x308b3501, 0xc000c54ce8, 0x100b805, 0x306cf20)
        /home/circleci/project/project/terraform/node_resource_apply_instance.go:135 +0xbc
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc00077f860, 0x38a3bc0, 0xc00071cfc0, 0x308b3518, 0xc000ba9880, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph_walk_context.go:129 +0xbf
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x33bffa0, 0xc000ba9880, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph.go:59 +0xbd3
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00009c600, 0x33bffa0, 0xc000ba9880, 0xc000944280)
        /home/circleci/project/project/dag/walk.go:381 +0x288
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /home/circleci/project/project/dag/walk.go:304 +0x1246
```

### Terraform Version

```
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Debug Output

Attached output of `env TF_LOG=trace terraform apply`: https://gist.github.com/bokysan/87a7ffdffee327a4f69867f16a3722e2

### Crash Output

Here: https://gist.github.com/bokysan/1675ef725c48dc687aa491b08e2c7b85

### Expected Behavior

`bastion_port` works.

### Actual Behavior

Terraform crashes whenever `bastion_port` is defined. Crash not observed without `bastion_port` parameter. Any other combination (e.g. adding/removing `port`, `type`, `password`) does not affect this crash. 

### Steps to Reproduce

```
terraform init
terraform apply
```

**Comment by alisdair** [comment]
The fix for this bug is merged and will go out in 0.15.4. Thanks again for the report.

**Comment by bokysan** [comment]
Welcome. Thanks for the quick fix.
