### ISSUE TITLE
Error: The terraform-provider-azurerm_v2.58.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by superlooper615** [hashicorp/terraform#28697]
Terraform version: Terraform v0.15.1

Got this error while destroying resources in Azure:
```

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.58.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x4d3f1cd]

goroutine 155 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/resource.resourceResourceGroupDelete(0xc0004b89a0, 0x5344020, 0xc0003c0300, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/resource/resource_group_resource.go:129 +0x20d
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000a499a0, 0xc0011e66e0, 0xc001cecce0, 0x5344020, 0xc0003c0300, 0x40e101, 0xc001208120, 0x56bfea0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:293 +0x4a6
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000314680, 0xc001197a38, 0xc0011e66e0, 0xc001cecce0, 0x95a36a0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000308658, 0x61f2570, 0xc00197e450, 0xc0004b8070, 0xc000308658, 0xc00197e450, 0xc001892ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:895 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x58165c0, 0xc000308658, 0x61f2570, 0xc00197e450, 0xc0011cc240, 0x0, 0x61f2570, 0xc00197e450, 0xc00139e000, 0x16f)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000235500, 0x6236818, 0xc001cda300, 0xc0000aa700, 0xc001880990, 0x9561240, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000235500, 0x6236818, 0xc001cda300, 0xc0000aa700, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000a4c240, 0xc000235500, 0x6236818, 0xc001cda300, 0xc0000aa700)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:857 +0x1fd

Error: The terraform-provider-azurerm_v2.58.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by jbardin** [comment]
Hi @superlooper615,

As indicated in the error output, the crash happened in the azurerm provider.
It would be helpful to file an issue with that provider so that they can work on resolving the problem.

Thanks!
