### ISSUE TITLE
Terraform crash » Terraform v0.15.4 on linux_amd64 (docker: 

### ISSUE THREAD

**Issue by jufemaiz** [hashicorp/terraform#28763]
### Terraform Version

```
Terraform v0.15.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

Note: using container `hashicorp/terraform:light` or `hashicorp/terraform:0.15.4`

### Terraform Configuration Files

```terraform
...
```

### Debug Output

```
$ terraform -chdir=. plan -var "assume_role_arn=$TF_ASSUME_ROLE_ARN" -var "remote_state_token=$TF_TOKEN" -var-file=production.tfvars $OUTPUT
```

```
Acquiring state lock. This may take a few moments...
--
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xbdf185]
 
goroutine 1516 [running]:
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).planDestroy(0xc0011b56c0, 0x2cef4c0, 0xc001a847e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/circleci/project/project/internal/terraform/node_resource_abstract_instance.go:402 +0x185
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc00295a5e0, 0x2cef4c0, 0xc001a847e0, 0x296a1b8, 0xc000066800, 0xc0021b1c50)
/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:126 +0x538
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0xc00295a5e0, 0x2cef4c0, 0xc001a847e0, 0xc000100002, 0xc0021b1ce8, 0x40bb05, 0x24a95e0)
/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0xb3
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc00272aa90, 0x2cef4c0, 0xc001a847e0, 0x7fbc71dde0a0, 0xc00295a5e0, 0x0, 0x0, 0x0)
/home/circleci/project/project/internal/terraform/graph_walk_context.go:129 +0xbf
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1(0x27fd220, 0xc00295a5e0, 0x0, 0x0, 0x0)
/home/circleci/project/project/internal/terraform/graph.go:59 +0xbd3
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc00038bb00, 0x27fd220, 0xc00295a5e0, 0xc000965680)
/home/circleci/project/project/internal/dag/walk.go:381 +0x288
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
/home/circleci/project/project/internal/dag/walk.go:304 +0x1246
 
 
 
 
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.020280254.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.
 
When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.
 
SECURITY WARNING: the "crash.020280254.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.
 
[1]: https://github.com/hashicorp/terraform/issues
 
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Crash Output

Please provide a private channel for `crash.*.log` file.

### Expected Behavior

The plan will plan.

### Actual Behavior

Crashed and told to contact.

Note: works on v0.14.11 and v0.15.3.

### Additional Context

Docker container `hashicorp/terraform:light` in CI/CD.

**Comment by jbardin** [comment]
Thanks @jufemaiz, the stack trace above was actually sufficient to find the root cause here!
