### ISSUE TITLE
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x157d737]

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/terraform#28789]
### Terraform Version

```
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/vault v2.20.0
+ provider registry.terraform.io/nolte/awx v0.2.2
```

### Terraform Configuration Files

```terraform
terraform {
  backend "s3" {}
}

provider "vault" {
  address = var.VAULT_ADDR
}

data "vault_generic_secret" "aws" {
  path = var.vault_path_aws_keys
}

provider "aws" {
  region     = var.aws_region
  access_key = data.vault_generic_secret.aws.data["access_key"]
  secret_key = data.vault_generic_secret.aws.data["secret_key"]
}

data "aws_vpc" "main" {
  filter {
    name   = "tag:Name"
    values = [var.vpc-name]
  }
}
```

### Crash Output
```
2021-05-24T14:55:50.371+0100 [TRACE] Re-validating config for "aws_route53_record.dns[\"DOMAIN1\"]"
2021-05-24T14:55:50.371+0100 [TRACE] GRPCProvider: ValidateResourceConfig
2021-05-24T14:55:50.371+0100 [INFO]  provider.terraform-provider-aws_v3.42.0_x5: 2021/05/24 14:55:50 [WARN] Truncating attribute path of 0 diagnostics for TypeSet: timestamp=2021-05-24T14:55:50.371+0100
2021-05-24T14:55:50.372+0100 [TRACE] GRPCProvider: PlanResourceChange
2021-05-24T14:55:50.373+0100 [WARN]  Provider "registry.terraform.io/hashicorp/aws" produced an invalid plan for aws_route53_record.dns["DOMAIN1"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .set_identifier: planned value cty.StringVal("") for a non-computed attribute
      - .ttl: planned value cty.NumberIntVal(0) for a non-computed attribute
      - .health_check_id: planned value cty.StringVal("") for a non-computed attribute
      - .records: planned value cty.SetValEmpty(cty.String) for a non-computed attribute
2021-05-24T14:55:50.373+0100 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to workingState for aws_route53_record.dns["DOMAIN1"]
2021-05-24T14:55:50.373+0100 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: writing state object for aws_route53_record.dns["DOMAIN1"]
2021-05-24T14:55:50.373+0100 [TRACE] writeChange: recorded NoOp change for aws_route53_record.dns["DOMAIN1"]
2021-05-24T14:55:50.373+0100 [TRACE] vertex "aws_route53_record.dns[\"DOMAIN1\"]": visit complete
2021-05-24T14:55:50.423+0100 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to refreshState for aws_route53_record.dns["DOMAIN2"]
2021-05-24T14:55:50.423+0100 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: writing state object for aws_route53_record.dns["DOMAIN2"]
2021-05-24T14:55:50.424+0100 [TRACE] Re-validating config for "aws_route53_record.dns[\"DOMAIN2\"]"
2021-05-24T14:55:50.424+0100 [TRACE] GRPCProvider: ValidateResourceConfig
2021-05-24T14:55:50.424+0100 [INFO]  provider.terraform-provider-aws_v3.42.0_x5: 2021/05/24 14:55:50 [WARN] Truncating attribute path of 0 diagnostics for TypeSet: timestamp=2021-05-24T14:55:50.424+0100
2021-05-24T14:55:50.424+0100 [TRACE] GRPCProvider: PlanResourceChange
2021-05-24T14:55:50.425+0100 [WARN]  Provider "registry.terraform.io/hashicorp/aws" produced an invalid plan for aws_route53_record.dns["DOMAIN2"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .ttl: planned value cty.NumberIntVal(0) for a non-computed attribute
      - .health_check_id: planned value cty.StringVal("") for a non-computed attribute
      - .records: planned value cty.SetValEmpty(cty.String) for a non-computed attribute
      - .set_identifier: planned value cty.StringVal("") for a non-computed attribute
XXX
2021-05-24T14:55:50.615+0100 [TRACE] vertex "meta.count-boundary (EachMode fixup)": starting visit (*terraform.NodeCountBoundary)
2021-05-24T14:55:50.615+0100 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/aws\"] (close)": starting visit (*terraform.graphNodeCloseProvider)
2021-05-24T14:55:50.615+0100 [TRACE] GRPCProvider: Close
2021-05-24T14:55:50.615+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-05-24T14:55:50.616+0100 [TRACE] vertex "meta.count-boundary (EachMode fixup)": visit complete
2021-05-24T14:55:50.621+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/3.42.0/darwin_amd64/terraform-provider-aws_v3.42.0_x5 pid=72967
2021-05-24T14:55:50.621+0100 [DEBUG] provider: plugin exited
2021-05-24T14:55:50.621+0100 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/aws\"] (close)": visit complete
2021-05-24T14:55:50.621+0100 [TRACE] vertex "root": starting visit (*terraform.nodeCloseModule)
2021-05-24T14:55:50.621+0100 [TRACE] vertex "root": visit complete

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x157d737]

goroutine 65 [running]:
github.com/hashicorp/terraform/internal/states.(*ResourceInstanceObjectSrc).Decode(0x0, 0x38b7cb8, 0xc001f46300, 0xc003904690, 0x0, 0x0)
	/home/circleci/project/project/internal/states/instance_object_src.go:77 +0x37
github.com/hashicorp/terraform/internal/command/format.ResourceInstanceDrift(0xc000ba3680, 0x2, 0x2, 0x4d, 0xc00072be78, 0x18, 0xc000c796c0, 0x4, 0x38a9dd8, 0x484e100, ...)
	/home/circleci/project/project/internal/command/format/diff.go:224 +0x465
github.com/hashicorp/terraform/internal/command/views.renderChangesDetectedByRefresh(0xc0012c8a90, 0xc0012c8a98, 0xc0011019e0, 0xc0001bf300, 0xc0009fe340)
	/home/circleci/project/project/internal/command/views/plan.go:382 +0x674
github.com/hashicorp/terraform/internal/command/views.renderPlan(0xc001f68f00, 0xc0011019e0, 0xc0001bf300)
	/home/circleci/project/project/internal/command/views/plan.go:100 +0x70
github.com/hashicorp/terraform/internal/command/views.(*OperationHuman).Plan(0xc000a84920, 0xc001f68f00, 0xc0011019e0)
	/home/circleci/project/project/internal/command/views/operation.go:89 +0x45
github.com/hashicorp/terraform/internal/backend/local.(*Local).opApply(0xc000c200a0, 0x38b5ef8, 0xc000b900c0, 0x38b5ef8, 0xc000b90100, 0xc000652240, 0xc000b90000)
	/home/circleci/project/project/internal/backend/local/backend_apply.go:78 +0xedd
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1(0xc000a84ed0, 0xc000a84ee0, 0xc000a84ef0, 0xc000c200a0, 0xc000a84ec0, 0x38b5ef8, 0xc000b900c0, 0x38b5ef8, 0xc000b90100, 0xc000652240, ...)
	/home/circleci/project/project/internal/backend/local/backend.go:321 +0xe8
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
	/home/circleci/project/project/internal/backend/local/backend.go:315 +0x2f2
```

### Expected Behavior
for DNSs to be created

### Actual Behavior
crash

### Steps to Reproduce
terraform apply -compact-warnings  -parallelism=300 -var-file=global-dev.tfvars -var-file=dev.tfvars

**Comment by jbardin** [comment]
Hi @FernandoMiguel,

Thanks for filing the issue. The expected behavior, and the log output both refer to other resource like `aws_route53_record.dns`, but they are not present in the configuration. Do you have a complete configuration and steps that can reproduce the issue?

Thanks!

**Comment by FernandoMiguel** [comment]
All of it is quite specific to our org with identifiers in the resource names, and I'm not allowed to share (publicly).
Reverting to 0.15.3 made this work again.

The DNS records you mention come from a module.
If there is anything specific you would like to know, let me know, and I'll try to share a redacted version @jbardin

**Comment by jbardin** [comment]
Thanks @FernandoMiguel, I don't think the redacted config would help in this case, since I would need a way to reproduce this in full. I have a good idea where this is coming from, so may be able to reproduce it in isolation.

**Comment by FernandoMiguel** [comment]
@jbardin sorry for not being more helpful.
It's sadly a very large piece of code which touches 3 modules, one of them that calls another module itself.
The crash log is a huge file.
I did a quick pass to try to redact it but would consume a lot of my working time.
And still I couldn't redact the code for this.

Again, if you need a particular part of the crash log or the resources involved, I can try to sanitise it

**Comment by jbardin** [comment]
Thanks, I have a reproduction with the same stack trace, so I'm fairly confident that I'm going to catch the error you've encountered as well. I would like to fully understand _how_ we got here though, my reproduction is hitting deposed instances in order to cause the panic. Can you check your logs and/or state to see if you have any instances marked as `deposed`?

**Comment by FernandoMiguel** [comment]
I can check tomorrow. I'm off work now (GMT tz).
I already applied dev and do need to apply preprod and prod ASAP, so I might not have a massive amount of time to check this.
The one thing I was working here was to remove a acme module.
That in place would required the ASG to update to due changes in the user data.
I honestly don't know why route53 was invoked here, as I don't expect any changes to it.

But ASG change to lead to depose resources since the launch template is replaced.

**Comment by FernandoMiguel** [comment]
looking for deposed i found this
```hcl
2021-05-24T18:54:06.683+0100 [TRACE] StateTransformer: creating nodes for deposed instance objects only

2021-05-24T18:54:06.684+0100 [TRACE] StateTransformer: added *terraform.NodePlanDeposedResourceInstanceObject for module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] deposed object a308e859

  module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

  module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

2021-05-24T18:54:06.687+0100 [TRACE] AttachResourceConfigTransformer: attaching to "module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859)" (*terraform.NodePlanDeposedResourceInstanceObject) config from .terraform/modules/aws.ec2-asg-with-launch-config/main.tf:4,1-43

2021-05-24T18:54:06.687+0100 [TRACE] AttachResourceConfigTransformer: attaching provider meta configs to module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859)

  module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

  module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

2021-05-24T18:54:06.691+0100 [TRACE] ProviderTransformer: looking for module.aws.provider["registry.terraform.io/hashicorp/aws"] to serve module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859)

2021-05-24T18:54:06.691+0100 [TRACE] ProviderTransformer: module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) uses inherited configuration provider["registry.terraform.io/hashicorp/aws"]

2021-05-24T18:54:06.691+0100 [DEBUG] ProviderTransformer: "module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859)" (*terraform.NodePlanDeposedResourceInstanceObject) needs provider["registry.terraform.io/hashicorp/aws"]

  module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

  module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

  module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

2021-05-24T18:54:06.697+0100 [TRACE] AttachSchemaTransformer: attaching resource schema to module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859)

2021-05-24T18:54:06.700+0100 [TRACE] ModuleExpansionTransformer: module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) must wait for expansion of module.aws.module.ec2-asg-with-launch-config

    module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

  module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

2021-05-24T18:54:06.708+0100 [DEBUG] ReferenceTransformer: "module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859)" references: []

    module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

  module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

    module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

    module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

  module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

    module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

    module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

  module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

    module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

    module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

    module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

  module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

    module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

    module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

  module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

    module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859) - *terraform.NodePlanDeposedResourceInstanceObject

2021-05-24T18:54:11.752+0100 [TRACE] dag/walk: vertex "module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859)" is waiting for "provider[\"registry.terraform.io/hashicorp/aws\"]"

2021-05-24T18:54:12.687+0100 [TRACE] vertex "module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859)": starting visit (*terraform.NodePlanDeposedResourceInstanceObject)

2021-05-24T18:54:12.687+0100 [TRACE] NodePlanDeposedResourceInstanceObject: planning module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] deposed object a308e859

2021-05-24T18:54:12.687+0100 [TRACE] readResourceInstanceStateDeposed: reading state for module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] deposed object a308e859

2021-05-24T18:54:12.690+0100 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceStateDeposed to prevRunState for module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed key a308e859)

2021-05-24T18:54:12.690+0100 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceStateDeposed to refreshState for module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed key a308e859)

2021-05-24T18:54:12.690+0100 [TRACE] NodeAbstractResourceInstance.refresh for module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed object a308e859)

2021-05-24T18:54:13.912+0100 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceStateDeposed to refreshState for module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed key a308e859)

2021-05-24T18:54:13.913+0100 [TRACE] writeChange: recorded Delete change for module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] deposed object a308e859

2021-05-24T18:54:13.913+0100 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceStateDeposed to workingState for module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed key a308e859)

2021-05-24T18:54:13.913+0100 [TRACE] vertex "module.aws.module.ec2-asg-with-launch-config.aws_launch_configuration.this[0] (deposed a308e859)": visit complete
```

seems i was right, it is the ASG / launch config

**Comment by jbardin** [comment]
Thanks @FernandoMiguel! that confirms the test case I had matches the issue
