### ISSUE TITLE
NPE Panic in planDestroy/node_resource_abstract_instance.go

### ISSUE THREAD

**Issue by kevinburkemeter** [hashicorp/terraform#28829]
Here's the crash log:

```
module.scheduler.module.dequeuer_svc.aws_autoscaling_group.default (deposed object e15cda0a): Refreshing state...
module.api.module.svc.aws_autoscaling_group.default (deposed object 24297987): Refreshing state...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x17e49c5]

goroutine 8532 [running]:
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).planDestroy(0xc003b0cc40, 0x38f6e40, 0xc002466fc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform/internal/terraform/node_resource_abstract_instance.go:402 +0x185
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc003b20510, 0x38f6e40, 0xc002466fc0, 0x3570150, 0xc00007b800, 0xc003abbc50)
	github.com/hashicorp/terraform/internal/terraform/node_resource_plan_orphan.go:126 +0x538
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0xc003b20510, 0x38f6e40, 0xc002466fc0, 0xc0000b6002, 0xc003abbce8, 0x100d305, 0x30aec40)
	github.com/hashicorp/terraform/internal/terraform/node_resource_plan_orphan.go:49 +0xb3
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0033b44e0, 0x38f6e40, 0xc002466fc0, 0xd990a18, 0xc003b20510, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform/internal/terraform/graph_walk_context.go:129 +0xbf
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1(0x3403400, 0xc003b20510, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform/internal/terraform/graph.go:59 +0xbd3
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc005738c60, 0x3403400, 0xc003b20510, 0xc00429ff00)
	github.com/hashicorp/terraform/internal/dag/walk.go:381 +0x288
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	github.com/hashicorp/terraform/internal/dag/walk.go:304 +0x1246
```

I'm running these versions:

```
$ terraform --version
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.40.0
+ provider registry.terraform.io/hashicorp/github v4.8.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

I installed Terraform from Homebrew. 

If this isn't enough information to track down the issue, I can email the crash log to someone but I'm hesitant to paste it on the issue tracker.

**Comment by kevinburkemeter** [comment]
Looks like a dupe of #28792
