### ISSUE TITLE
Terraform is crushing with F5 plugin..

### ISSUE THREAD

**Issue by f5killer** [hashicorp/terraform#28861]
Terraform is cursing itself. when using below code. See below details. 
root@NAP:/home/xxxx/xxx/as3# terraform plan

root@NAP:/home/xxxxx/terraform-aws-bigip-module/as3# cat as3.tf
terraform {
  required_providers {
    bigip = {
      source = "F5Networks/bigip"
      version = "1.9.0"
    }
  }
}

resource "bigip_bigiq_as3" "exampletask" {
bigiq_address = "xx.xx.xx.xx"
bigiq_user = "userroot"
bigiq_password = "xxxxxxx"
as3_json = file("as3_waf.json")
}
root@NAP:/home/xxxxx/terraform-aws-bigip-module/as3#
Error: Missing newline after argument

  on as3.tf line 19, in resource "bigip_bigiq_as3" "exampletask":
  19: as3_json = "file("as3_waf.json")"

An argument definition must end with a newline.

root@NAP:/home/xxxx/terraform-aws-bigip-module/as3# vi as3.tf
root@NAP:/home/xxxx/terraform-aws-bigip-module/as3# terraform plan

Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: index out of range [0] with length 0
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0:
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0: goroutine 25 [running]:
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0: github.com/f5devcentral/go-bigip.(*BigIP).APICall(0xc000106bd0, 0xc00008f5e0, 0x0, 0x0, 0x0, 0x0, 0x0)
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0:        github.com/f5devcentral/go-bigip@v0.0.0-20210512151832-8b6cab64b5f3/bigip.go:211 +0x13a5
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0: github.com/f5devcentral/go-bigip.(*BigIP).getForEntity(0xc000106bd0, 0xf1aca0, 0xc00000d638, 0xc00008f680, 0x2, 0x2, 0xc0004a0101, 0xc000582d80, 0xc00008f6f8)
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0:        github.com/f5devcentral/go-bigip@v0.0.0-20210512151832-8b6cab64b5f3/bigip.go:451 +0xe6
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0: github.com/f5devcentral/go-bigip.(*BigIP).SelfIPs(0xc000106bd0, 0xc00008f6f8, 0x50044c, 0x15)
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0:        github.com/f5devcentral/go-bigip@v0.0.0-20210512151832-8b6cab64b5f3/net.go:376 +0xb0
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0: github.com/F5Networks/terraform-provider-bigip/bigip.(*Config).validateConnection(0xc00008f840, 0xc000106bd0, 0x0, 0x0)
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0:        github.com/F5Networks/terraform-provider-bigip/bigip/config.go:51 +0x2f
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0: github.com/F5Networks/terraform-provider-bigip/bigip.(*Config).Client(0xc00008f840, 0x10d1f42, 0xa, 0xf3f320)
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0:        github.com/F5Networks/terraform-provider-bigip/bigip/config.go:41 +0x24c
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0: github.com/F5Networks/terraform-provider-bigip/bigip.providerConfigure(0xc000106a80, 0xc0005e7918, 0x6, 0xc000106a80, 0x0, 0x0, 0x0)
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0:        github.com/F5Networks/terraform-provider-bigip/bigip/provider.go:154 +0x26b
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0: github.com/F5Networks/terraform-provider-bigip/bigip.Provider.func1(0xc000106a80, 0x0, 0xc000639360, 0xc000106a80, 0x0)
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0:        github.com/F5Networks/terraform-provider-bigip/bigip/provider.go:139 +0x58
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Configure(0xc000500580, 0xc000138870, 0xf8f180, 0xc0001387e0)
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0:        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/provider.go:275 +0xfc
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).Configure(0xc0004941b8, 0x1274ad0, 0xc0001383c0, 0xc000599280, 0xc0004941b8, 0xc0001383c0, 0xc000532a50)
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0:        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:487 +0x2ee
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_Configure_Handler(0x1084f80, 0xc0004941b8, 0x1274ad0, 0xc0001383c0, 0xc000136cc0, 0x0, 0x1274ad0, 0xc0001383c0, 0xc000162080, 0x73)
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0:        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3135 +0x214
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000ee160, 0x127d4b8, 0xc000482a80, 0xc0005c0f00, 0xc000431110, 0x18318b8, 0x0, 0x0, 0x0)
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0:        google.golang.org/grpc@v1.23.0/server.go:995 +0x482
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0: google.golang.org/grpc.(*Server).handleStream(0xc0000ee160, 0x127d4b8, 0xc000482a80, 0xc0005c0f00, 0x0)
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0:        google.golang.org/grpc@v1.23.0/server.go:1275 +0xd2c
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00049c1d0, 0xc0000ee160, 0x127d4b8, 0xc000482a80, 0xc0005c0f00)
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0:        google.golang.org/grpc@v1.23.0/server.go:710 +0xab
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-06-02T13:31:45.999Z [DEBUG] plugin.terraform-provider-bigip_v1.9.0:        google.golang.org/grpc@v1.23.0/server.go:708 +0xa5
2021-06-02T13:31:46.000Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/f5networks/bigip/1.9.0/linux_amd64/terraform-provider-bigip_v1.9.0 pid=6927 error="exit status 2"
2021/06/02 13:31:46 [TRACE] vertex "provider[\"registry.terraform.io/f5networks/bigip\"]": visit complete
2021/06/02 13:31:46 [TRACE] dag/walk: upstream of "bigip_bigiq_as3.exampletask (expand)" errored, so skipping
2021/06/02 13:31:46 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/f5networks/bigip\"] (close)" errored, so skipping
2021/06/02 13:31:46 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/06/02 13:31:46 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/06/02 13:31:46 [INFO] backend/local: plan operation completed
2021/06/02 13:31:46 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/06/02 13:31:46 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-06-02T13:31:46.001Z [DEBUG] plugin: plugin exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
root@NAP:/home/xxxx/terraform-aws-bigip-module/as3#

**Comment by jbardin** [comment]
Hi @f5killer,

This appears to be an issue with an F5 provider, not with terraform itself. Please verify that you have the latest version, and report the crash in the provider's issue tracker.

Thanks!
