### ISSUE TITLE
TF CLI: Crash in 12.31 when accessing a function in the JSON format

### ISSUE THREAD

**Issue by misterkbar-terraform** [hashicorp/terraform#28867]
Am currently getting the "!!!! TERRAFORM CRASH !!!!" error. I am attaching the crash log below. 

This is starting to become a bit of a pain point, so any suggestions are welcome.

Effectively, it appears to be due to the use of a function inside of the following (correct) JSON formatted terraform. It is *NOT* germane to the `abs` function, it can be ANY function, even simple `foobar_not_a_real_function()`  It is ALSO not germane to formatting. Two crash logs are included, one from a formatted JSON file, one from a one-line JSON file. They look almost exactly the same.

The following things fix the issue/do not exhibit the problem:

- Switching `abs(1)` to `1` (i.e. removing the function call)
- Running in "terraform console" command.
    - this requires fixing the state first to get the console command working
    - must be fed in a one-line json blob
    - output is shown below.
- Converting to "standard terraform format" as below 

```terraform
resource "null_resource" "that_is_a_thing" {   
    foo = abs(1)
}
```

Here is the output of the terraform console run:
```
# terraform console
> { "resource": {"data": { "null_resource": { "that_is_a_thing": { "foo":  abs(1) } } } }}
{
  "resource" = { 
    "data" = {
      "null_resource" = {
        "that_is_a_thing" = {
          "foo" = 1
        }
      }
    }
  }
}
```

### Terraform Version
```
0.12.31
```

### Terraform Configuration Files

```terraform
{ 
  "resource": {
    "data": { 
      "null_resource": { 
        "that_is_a_thing": { 
          "foo":  abs(1) 
        } 
      }
    } 
  } 
}
```

### Debug Output
Doesn't even get that far. It just crashes. Poof.

### Crash Output
They're just 61 lines long each, will put them here:
Formatted version of the file:
```
2021/06/02 23:18:05 [INFO] Terraform version: 0.12.31
2021/06/02 23:18:05 [INFO] Go runtime version: go1.12.13
2021/06/02 23:18:05 [INFO] CLI args: []string{"/usr/bin/terraform", "init"}
2021/06/02 23:18:05 [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2021/06/02 23:18:05 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021/06/02 23:18:05 [INFO] CLI command args: []string{"init"}
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/hcl/v2/json.(*peeker).Read(...)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/peeker.go:20
github.com/hashicorp/hcl/v2/json.parseObject.func1(0x0, 0xc0001a406f, 0x1, 0x226, 0xc0003974f0, 0xb, 0x6, 0x16, 0x6f, 0x6, ...)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:127 +0xb0
github.com/hashicorp/hcl/v2/json.parseObject(0xc0004b48a0, 0xc0000805a0, 0xc00046d4f0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:233 +0xcb2
github.com/hashicorp/hcl/v2/json.parseValue(0xc0004b48a0, 0xc000080540, 0x0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:45 +0x70b
github.com/hashicorp/hcl/v2/json.parseObject(0xc0004b48a0, 0xc0000803c0, 0xc00046d4a0, 0x0, 0x200000000, 0x2000)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:188 +0x43c
github.com/hashicorp/hcl/v2/json.parseValue(0xc0004b48a0, 0xc000080360, 0x0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:45 +0x70b
github.com/hashicorp/hcl/v2/json.parseObject(0xc0004b48a0, 0xc0004c1e60, 0xc00046d450, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:188 +0x43c
github.com/hashicorp/hcl/v2/json.parseValue(0xc0004b48a0, 0xc0004c1e00, 0x0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:45 +0x70b
github.com/hashicorp/hcl/v2/json.parseObject(0xc0004b48a0, 0xc0004c1c80, 0xc00046c410, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:188 +0x43c
github.com/hashicorp/hcl/v2/json.parseValue(0xc0004b48a0, 0xc0004c1c20, 0x0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:45 +0x70b
github.com/hashicorp/hcl/v2/json.parseObject(0xc0004b48a0, 0xc0004c1aa0, 0xc0003974f0, 0xb, 0x6, 0xb)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:188 +0x43c
github.com/hashicorp/hcl/v2/json.parseValue(0xc0004b48a0, 0xc0004b48a0, 0x226, 0xc0003974f0, 0xb, 0x6)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:45 +0x70b
github.com/hashicorp/hcl/v2/json.parseFileContent(0xc0001a4000, 0x95, 0x295, 0xc0003974f0, 0xb, 0x0, 0x0, 0xc0004c19e0, 0x7f6f48de4a28, 0x45)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:21 +0x155
github.com/hashicorp/hcl/v2/json.Parse(0xc0001a4000, 0x95, 0x295, 0xc0003974f0, 0xb, 0xc0001a4000, 0x95, 0x295, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/public.go:21 +0x77
github.com/hashicorp/hcl/v2/hclparse.(*Parser).ParseJSON(0xc0004a8038, 0xc0001a4000, 0x95, 0x295, 0xc0003974f0, 0xb, 0x295, 0x0, 0x0, 0xc0004a8060)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/hclparse/parser.go:91 +0xae
github.com/hashicorp/terraform/configs.(*Parser).LoadHCLFile(0xc0004b4740, 0xc0003974f0, 0xb, 0x0, 0x1, 0xc0004a8060, 0x0, 0x1)
    /home/circleci/project/project/configs/parser.go:66 +0xfa
github.com/hashicorp/terraform/configs.(*Parser).loadConfigFile(0xc0004b4740, 0xc0003974f0, 0xb, 0x0, 0x1, 0xc0004a8068, 0x0, 0x1)
    /home/circleci/project/project/configs/parser_config.go:34 +0x5d
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigFile(...)
    /home/circleci/project/project/configs/parser_config.go:22
github.com/hashicorp/terraform/configs.(*Parser).loadFiles(0xc0004b4740, 0xc0004b47e0, 0x2, 0x2, 0x0, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
    /home/circleci/project/project/configs/parser_config_dir.go:77 +0x343
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigDir(0xc0004b4740, 0x1f1514d, 0x1, 0x0, 0x1, 0x2, 0x0)
    /home/circleci/project/project/configs/parser_config_dir.go:37 +0x121
github.com/hashicorp/terraform/command.(*Meta).loadSingleModule(0xc000444540, 0x1f1514d, 0x1, 0x0, 0x0, 0x0, 0xe)
    /home/circleci/project/project/command/meta_config.go:113 +0x136
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc000444540, 0xc0000ac030, 0x0, 0x0, 0xc0000a15a0)
    /home/circleci/project/project/command/init.go:182 +0xad4
github.com/mitchellh/cli.(*CLI).Run(0xc000378280, 0xc000378280, 0xc000539d90, 0x1)
    /go/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
    /home/circleci/project/project/main.go:251 +0xc8a
main.realMain(0x0)
    /home/circleci/project/project/main.go:106 +0xb4
main.main()
    /home/circleci/project/project/main.go:42 +0x3b
```

Crash log of the one-line version:
```
2021/06/02 23:19:33 [INFO] Terraform version: 0.12.31
2021/06/02 23:19:33 [INFO] Go runtime version: go1.12.13
2021/06/02 23:19:33 [INFO] CLI args: []string{"/usr/bin/terraform", "init"}
2021/06/02 23:19:33 [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2021/06/02 23:19:33 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021/06/02 23:19:33 [INFO] CLI command args: []string{"init"}
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/hcl/v2/json.(*peeker).Read(...)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/peeker.go:20
github.com/hashicorp/hcl/v2/json.parseObject.func1(0x0, 0xc0003c02cd, 0x1, 0x20e, 0xc0000b4610, 0xb, 0x1, 0x4e, 0x4d, 0x1, ...)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:127 +0xb0
github.com/hashicorp/hcl/v2/json.parseObject(0xc0004c5180, 0xc0005591a0, 0xc00010cb90, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:233 +0xcb2
github.com/hashicorp/hcl/v2/json.parseValue(0xc0004c5180, 0xc000559140, 0x0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:45 +0x70b
github.com/hashicorp/hcl/v2/json.parseObject(0xc0004c5180, 0xc000558fc0, 0xc00010cb40, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:188 +0x43c
github.com/hashicorp/hcl/v2/json.parseValue(0xc0004c5180, 0xc000558f60, 0x0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:45 +0x70b
github.com/hashicorp/hcl/v2/json.parseObject(0xc0004c5180, 0xc000558de0, 0xc00010caf0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:188 +0x43c
github.com/hashicorp/hcl/v2/json.parseValue(0xc0004c5180, 0xc000558d80, 0x0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:45 +0x70b
github.com/hashicorp/hcl/v2/json.parseObject(0xc0004c5180, 0xc000558c00, 0xc00010caa0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:188 +0x43c
github.com/hashicorp/hcl/v2/json.parseValue(0xc0004c5180, 0xc000558ba0, 0x0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:45 +0x70b
github.com/hashicorp/hcl/v2/json.parseObject(0xc0004c5180, 0xc000558a20, 0xc0000b4610, 0xb, 0x1, 0x43)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:188 +0x43c
github.com/hashicorp/hcl/v2/json.parseValue(0xc0004c5180, 0xc0004c5180, 0x20e, 0xc0000b4610, 0xb, 0x1)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:45 +0x70b
github.com/hashicorp/hcl/v2/json.parseFileContent(0xc0003c0280, 0x5b, 0x25b, 0xc0000b4610, 0xb, 0x0, 0x0, 0xc000558960, 0x7f76329b2230, 0x19)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:21 +0x155
github.com/hashicorp/hcl/v2/json.Parse(0xc0003c0280, 0x5b, 0x25b, 0xc0000b4610, 0xb, 0xc0003c0280, 0x5b, 0x25b, 0x0)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/public.go:21 +0x77
github.com/hashicorp/hcl/v2/hclparse.(*Parser).ParseJSON(0xc0001260c8, 0xc0003c0280, 0x5b, 0x25b, 0xc0000b4610, 0xb, 0x25b, 0x0, 0x0, 0xc000126478)
    /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/hclparse/parser.go:91 +0xae
github.com/hashicorp/terraform/configs.(*Parser).LoadHCLFile(0xc0004c5020, 0xc0000b4610, 0xb, 0x0, 0x1, 0xc000126478, 0x0, 0x1)
    /home/circleci/project/project/configs/parser.go:66 +0xfa
github.com/hashicorp/terraform/configs.(*Parser).loadConfigFile(0xc0004c5020, 0xc0000b4610, 0xb, 0x0, 0x1, 0xc0001266a8, 0x0, 0x1)
    /home/circleci/project/project/configs/parser_config.go:34 +0x5d
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigFile(...)
    /home/circleci/project/project/configs/parser_config.go:22
github.com/hashicorp/terraform/configs.(*Parser).loadFiles(0xc0004c5020, 0xc0004c50c0, 0x2, 0x2, 0x0, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
    /home/circleci/project/project/configs/parser_config_dir.go:77 +0x343
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigDir(0xc0004c5020, 0x1f1514d, 0x1, 0x0, 0x1, 0x2, 0x0)
    /home/circleci/project/project/configs/parser_config_dir.go:37 +0x121
github.com/hashicorp/terraform/command.(*Meta).loadSingleModule(0xc00045a540, 0x1f1514d, 0x1, 0x0, 0x0, 0x0, 0xe)
    /home/circleci/project/project/command/meta_config.go:113 +0x136
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc00045a540, 0xc0000c6010, 0x0, 0x0, 0xc0000a1460)
    /home/circleci/project/project/command/init.go:182 +0xad4
github.com/mitchellh/cli.(*CLI).Run(0xc00010e640, 0xc00010e640, 0xc000541d90, 0x1)
    /go/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
    /home/circleci/project/project/main.go:251 +0xc8a
main.realMain(0x0)
    /home/circleci/project/project/main.go:106 +0xb4
main.main()
    /home/circleci/project/project/main.go:42 +0x3b
```

### Expected Behavior
Something
### Actual Behavior
Absolutely nothing, other than a crash
### Steps to Reproduce
1. `terraform init`
2. BAM!

**Comment by jbardin** [comment]
Hi @misterkbar-terraform,

Thanks for filing the issue. We are no longer developing the 0.12 release of terraform. This crash on invalid input was fixed in one of the subsequent releases since then, so I'm going to close it out.

Thanks!

**Comment by alisdair** [comment]
To add a little context: the JSON configuration you provided is not valid JSON. GitHub's syntax highlighting points this out:

```json
```json
{ 
  "resource": {
    "data": { 
      "null_resource": { 
        "that_is_a_thing": { 
          "foo":  abs(1) 
        } 
      }
    } 
  } 
}
```

It is also not valid Terraform configuration JSON. Function calls are not directly representable in JSON syntax, and the only way to call functions is to use string interpolation.

Here is a modified JSON configuration which is valid and roughly equivalent to your sample:

```json
{ 
  "resource": {
    "null_resource": { 
      "that_is_a_thing": { 
        "triggers": {
          "foo": "${abs(-1)}"
        }
      } 
    } 
  } 
}
```

This works correctly with Terraform 0.12.31 and later.

**Comment by misterkbar-terraform** [comment]
Correct. It's **_NOT_** valid json. Frankly, I was assuming that "json format" wasn't completely json. There is no need to send it as data for an http post request or something, and the fact that `terraform console` accepted it seemed to back this up.

Printing an error to the sense of "No, we don't actually accept this, that is an error" would be an acceptable fix to the "!!!!!! TERRAFORM CRASHED !!!!!" issue, in addition to being consistent in Terraform console, as that is where one typically tries things out.

**Comment by jbardin** [comment]
@misterkbar-terraform, For reference, current versions of terraform return return more precise errors like the following from the CLI.

```
╷
│ Error: Invalid JSON keyword
│
│   on json.tf.json line 6:
│    6:           "foo":  abs(1)
│
│ "abs" is not a valid JSON keyword.
╵
```
