### ISSUE TITLE
Terraform Crashed after doing a destroy

### ISSUE THREAD

**Issue by rjwil35** [hashicorp/terraform#28952]
[crash.548368963.log](https://github.com/hashicorp/terraform/files/6648532/crash.548368963.log)
My Version of Terraform CLI is: Terraform v0.15.3
on darwin_amd64

**Comment by jbardin** [comment]
Adding the relevant stack trace

```
2021-06-09T14:27:11.763-0400 [DEBUG] Request to https://flixtubestratistier.blob.core.windows.net/terraform-tfstate/terraform.tfstate completed with no response

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1fed9e3]

goroutine 36 [running]:
github.com/hashicorp/terraform/backend/remote-state/azure.(*RemoteClient).Put(0xc0001ea870, 0xc00178e000, 0x9c, 0x9c, 0x0, 0xc00119a270)
        /home/circleci/project/project/backend/remote-state/azure/client.go:89 +0x263
github.com/hashicorp/terraform/states/remote.(*State).PersistState(0xc0008460c0, 0x0, 0x0)
        /home/circleci/project/project/states/remote/state.go:181 +0x228
github.com/hashicorp/terraform/states/statemgr.WriteAndPersist(0x66c7738, 0xc0008460c0, 0xc001114010, 0x66c7738, 0xc0008460c0)
        /home/circleci/project/project/states/statemgr/helper.go:52 +0x79
github.com/hashicorp/terraform/backend/local.(*Local).opApply(0xc0007e12c0, 0x386b4b8, 0xc00084e5c0, 0x386b4b8, 0xc00084e600, 0xc000868000, 0xc00084e580)
        /home/circleci/project/project/backend/local/backend_apply.go:170 +0x6fc
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc00083b6a0, 0xc00083b6b0, 0xc00083b6c0, 0xc0007e12c0, 0xc00083b690, 0x386b4b8, 0xc00084e5c0, 0x386b4b8, 0xc00084e600, 0xc000868000, ...)
        /home/circleci/project/project/backend/local/backend.go:321 +0xe8
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
        /home/circleci/project/project/backend/local/backend.go:315 +0x2f2
```

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of #36258. Please upgrade to the latest version (v1.11.2) for the fix. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
