### ISSUE TITLE
Error strconv.ParseInt - AWS data-size EFS output 

### ISSUE THREAD

**Issue by gerardgorrion** [hashicorp/terraform#28992]
We are using some resources into AWS, like a EFS deployed with terrafom IaC. Latest update of version (0.11 to 0.12, then to 0.13, 0.14 and now 0.15.5) report an error to manage the EFS created by terraform version ago (0.12). Problem is, on last version, show that can't parseint the data-size attribute output (default output of [aws_efs_file_system](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system)).

### Terraform Version
```
Terraform v0.15.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.45.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Terraform Configuration Files

```terraform
resource "aws_efs_file_system" "efs-service" {
  creation_token = "efs-service"
  encrypted = "true"

  tags = merge(
    var.default_tags,
    {
      Name = "efs-service"
      environment = var.environment
    },
  )
}

```

### Crash Output
```
Stack trace from the terraform-provider-aws_v3.45.0_x5 plugin:

panic: Error reading level state: strconv.ParseInt: parsing "84850493440": value out of range

goroutine 166 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x12f521e0, 0x12f42e98, 0x1, 0x1, 0x12f5e108, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource_data.go:553 +0x2ba
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x12f521e0, 0x12f521e0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource_data.go:351 +0x288
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x12244fc0, 0xde4dcfc, 0x12f42528, 0xc67f460, 0x12f31720, 0xde4dcfc, 0x12f42528, 0xc67f460)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:260 +0x191
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x12abbc20, 0xde4d65c, 0x12f31260, 0x12f312a0, 0x12f31260, 0x8051776, 0xd204a20)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:550 +0x1ea
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0x12ac6b28, 0xde4d6bc, 0x12f31260, 0x12f34780, 0x12ac6b28, 0x12f01101, 0x12f44318)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0xd4
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0xd3f0cc0, 0x12ac6b28, 0xde4d6bc, 0x12f44318, 0x12f34750, 0x0, 0xde4d6bc, 0x12f44318, 0x12f01180, 0x324)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x199
google.golang.org/grpc.(*Server).processUnaryRPC(0x1246e5a0, 0xde635b4, 0x12157c00, 0x12f298c0, 0x12ac6b70, 0x10f36508, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x4ea
google.golang.org/grpc.(*Server).handleStream(0x1246e5a0, 0xde635b4, 0x12157c00, 0x12f298c0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xa71
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x12a0c980, 0x1246e5a0, 0xde635b4, 0x12157c00, 0x12f298c0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x92
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1b0

Error: The terraform-provider-aws_v3.45.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior
That new version of terraform (0.15.5) should be manage the services deployed by the same terraform code.

### Actual Behavior
The terraform plan crash and show error of the resources below of efs in terarform state.

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`

### References
- #8415

**Comment by jbardin** [comment]
This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
