### ISSUE TITLE
azurerm invalid memory address or nil pointer dereference v2.63, 2.64 and 2.65

### ISSUE THREAD

**Issue by luis-serra-ki** [hashicorp/terraform#29060]
Hello guys,

I'm facing some bug using azurerm plugin and I don't know what's happening. I'm trying to perform terraform apply, and already tried with version 2.63, 2.64 and 2.65 and I have always the same problem.

### Terraform Version
```
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.21.0
+ provider registry.terraform.io/hashicorp/azuread v1.5.1
+ provider registry.terraform.io/hashicorp/azurerm v2.65.0
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Crash Output
```
module.databricks_etl_jobs.azurerm_monitor_diagnostic_setting.etl_jobs_platform: Creating...
module.analysis_services.azurerm_analysis_services_server.as_server: Modifying... [id=/subscriptions/AZ_SUBSCRIPTION_ID/resourceGroups/staging-data-rg/providers/Microsoft.AnalysisServices/servers/staginganalysisservicesserver]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with azurerm_management_lock.data-resource-group-level,
│   on locks.tf line 13, in resource "azurerm_management_lock" "data-resource-group-level":
│   13: resource "azurerm_management_lock" "data-resource-group-level" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.analysis_services.azurerm_analysis_services_server.as_server,
│   on ../modules/analysis_services/main.tf line 41, in resource "azurerm_analysis_services_server" "as_server":
│   41: resource "azurerm_analysis_services_server" "as_server" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.databricks_etl_jobs.azurerm_monitor_diagnostic_setting.etl_jobs_platform,
│   on ../modules/databricks/main.tf line 42, in resource "azurerm_monitor_diagnostic_setting" "etl_jobs_platform":
│   42: resource "azurerm_monitor_diagnostic_setting" "etl_jobs_platform" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.seller_storage_account.azurerm_storage_container.blob[2],
│   on ../modules/storage_account/main.tf line 19, in resource "azurerm_storage_container" "blob":
│   19: resource "azurerm_storage_container" "blob" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Stack trace from the terraform-provider-azurerm_v2.65.0_x5 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x4dc4937]
goroutine 103 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/mysql.resourceMySqlServerDelete(0xc0013e7580, 0x5518280, 0xc0013df500, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/mysql/mysql_server_resource.go:751 +0x2d7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0xc000612e00, 0x6428568, 0xc0014b3000, 0xc0013e7580, 0x5518280, 0xc0013df500, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:369 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000612e00, 0x6428568, 0xc0014b3000, 0xc00085a770, 0xc0019cd040, 0x5518280, 0xc0013df500, 0x0, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:428 +0x8f7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000c540d8, 0x6428568, 0xc0014b3000, 0xc00107f270, 0xc0014b3000, 0x59cb2a0, 0xc000168500)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00120df20, 0x6428610, 0xc0014b3000, 0xc00085a5b0, 0xc00120df20, 0xc000168570, 0xc00127fba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x59cb2a0, 0xc00120df20, 0x6428610, 0xc000168570, 0xc001495c80, 0x0, 0x6428610, 0xc000168570, 0xc0014fa000, 0x454)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00037a380, 0x6470798, 0xc001c66180, 0xc000f78d00, 0xc001282540, 0x98b55a0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00037a380, 0x6470798, 0xc001c66180, 0xc000f78d00, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000b92a40, 0xc00037a380, 0x6470798, 0xc001c66180, 0xc000f78d00)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:857 +0x1fd
Error: The terraform-provider-azurerm_v2.65.0_x5 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce
```
1. `terraform init`
2. `terraform apply`
```

**Comment by jbardin** [comment]
This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
