### ISSUE TITLE
crash when provisioning a machine via VMware vsphere

### ISSUE THREAD

**Issue by mattpep** [hashicorp/terraform#2906]
I get a stack trace when trying to provision a single machine. 

Gist containing command output, crash.log and my config: https://gist.github.com/mattpep/05c80244a3ae47d71241
Version number: Terraform v0.6.1

 To explain the setup:
I have a vCenter Server 5 Standard cluster which contains just one hypervisor host. It has numerous VMs on it. It is accessed via a VPN. The provision command is run from an Ubuntu 14.04 machine (itself built from the same image I'm trying to use for the VM) with 8G ram, 8G swap, 20G disk, and this machine has external internet access.

I'm not sure if this is a Terraform issue, or an issue with the provider I'm using.  I'm raising the issue here because the bottom of the output says `Terraform crashed! This is always indicative of a bug within Terraform.`, though I apologise if this would be better dealt with by that provider's author. (For reference it's https://github.com/rakutentech/terraform-provider-vsphere/)

Thanks for any insight you can offer.

**Comment by radeksimko** [comment]
I'm inclined to think that it's the provider's bug, consider the following part of log:

```
2015/07/31 16:33:44 terraform-provider-vsphere: panic: runtime error: invalid memory address or nil pointer dereference
2015/07/31 16:33:44 terraform-provider-vsphere: [signal 0xb code=0x1 addr=0x20 pc=0x44f323]
2015/07/31 16:33:44 terraform-provider-vsphere: 
2015/07/31 16:33:44 terraform-provider-vsphere: goroutine 63 [running]:
2015/07/31 16:33:44 terraform-provider-vsphere: github.com/rakutentech/terraform-provider-vsphere/vsphere.findDatastore(0xc2081f8670, 0xc2088ae600, 0xc20828a840, 0xc2088c84c0, 0xc2081bb110, 0xb, 0x7f8e1716a550, 0x0, 0x0)
2015/07/31 16:33:44 terraform-provider-vsphere: 	/home/ubuntu/go/src/github.com/rakutentech/terraform-provider-vsphere/vsphere/virtual_machine.go:402 +0x283
2015/07/31 16:33:44 terraform-provider-vsphere: github.com/rakutentech/terraform-provider-vsphere/vsphere.(*virtualMachine).deployVirtualMachine(0xc2080d8500, 0xc2081f8670, 0x0, 0x0)
2015/07/31 16:33:44 terraform-provider-vsphere: 	/home/ubuntu/go/src/github.com/rakutentech/terraform-provider-vsphere/vsphere/virtual_machine.go:271 +0x256c
2015/07/31 16:33:44 terraform-provider-vsphere: github.com/rakutentech/terraform-provider-vsphere/vsphere.resourceVSphereVirtualMachineCreate(0xc2081a81e0, 0xffe120, 0xc2081f8670, 0x0, 0x0)
2015/07/31 16:33:44 terraform-provider-vsphere: 	/home/ubuntu/go/src/github.com/rakutentech/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machine.go:275 +0x1be3
2015/07/31 16:33:44 terraform-provider-vsphere: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc208177840, 0xc20806b200, 0xc2081baf20, 0xffe120, 0xc2081f8670, 0x1, 0x0, 0x0)
2015/07/31 16:33:44 terraform-provider-vsphere: 	/home/ubuntu/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:145 +0x2c1
2015/07/31 16:33:44 terraform-provider-vsphere: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc20812fb90, 0xc208176380, 0xc20806b200, 0xc2081baf20, 0xab7e20, 0x0, 0x0)
2015/07/31 16:33:44 terraform-provider-vsphere: 	/home/ubuntu/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:162 +0x1da
2015/07/31 16:33:44 terraform-provider-vsphere: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Apply(0xc2081ad2c0, 0xc2081bc140, 0xc2081bb170, 0x0, 0x0)
2015/07/31 16:33:44 terraform-provider-vsphere: 	/home/ubuntu/go/src/github.com/hashicorp/terraform/rpc/resource_provider.go:323 +0x7f
2015/07/31 16:33:44 terraform-provider-vsphere: reflect.Value.call(0xd0fb80, 0xfcaaa0, 0x13, 0x101b6b0, 0x4, 0xc20841ff28, 0x3, 0x3, 0x0, 0x0, ...)
2015/07/31 16:33:44 terraform-provider-vsphere: 	/usr/local/go/src/reflect/value.go:419 +0x10e5
2015/07/31 16:33:44 terraform-provider-vsphere: reflect.Value.Call(0xd0fb80, 0xfcaaa0, 0x13, 0xc20841ff28, 0x3, 0x3, 0x0, 0x0, 0x0)
2015/07/31 16:33:44 terraform-provider-vsphere: 	/usr/local/go/src/reflect/value.go:296 +0xbc
2015/07/31 16:33:44 terraform-provider-vsphere: net/rpc.(*service).call(0xc2081778c0, 0xc208177880, 0xc20800aee8, 0xc208104b00, 0xc2081add40, 0xab7dc0, 0xc2081bc140, 0x16, 0xab7e20, 0xc2081bb170, ...)
2015/07/31 16:33:44 terraform-provider-vsphere: 	/usr/local/go/src/net/rpc/server.go:382 +0x1f7
2015/07/31 16:33:44 terraform-provider-vsphere: created by net/rpc.(*Server).ServeCodec
2015/07/31 16:33:44 terraform-provider-vsphere: 	/usr/local/go/src/net/rpc/server.go:476 +0x44a
```

If another maintainer agrees, I'd close this and recommend reporting it to the provider's repository.

**Comment by radeksimko** [comment]
That said, considering all of the above, the error message and/or error handling of errors coming from external providers could be improved:

```
Terraform crashed! This is always indicative of a bug within Terraform
```

As we can see, it's not always the case.

**Comment by mkuzmin** [comment]
This issue can be closed, it was resolved in https://github.com/rakutentech/terraform-provider-vsphere/issues/28.

**Comment by chrislovecnm** [comment]
@phinze @jen20 @catsby @stack72 can we get a close?

**Comment by jen20** [comment]
@chrislovecnm that looks like it was a pull-request to a different project? Are we sure this bug is fixed?

**Comment by chrislovecnm** [comment]
@jen20 let me double check

**Comment by chrislovecnm** [comment]
@jen20 please close, stack trace is from another project
