### ISSUE TITLE
Error: The terraform-provider-azurerm_v2.67.0_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by nietakipawel** [hashicorp/terraform#29146]
Hi there,
### Terraform Version
```
Terraform v0.15.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.67.0
```
### Debug Output
```
Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.67.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0x547fe04]

goroutine 98 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/privatedns.resourcePrivateDnsZoneDelete(0xc001a50880, 0x5b4a6e0, 0xc001249880, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/privatedns/private_dns_zone_resource.go:269 +0x244
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0xc000dbb960, 0x6aa2b48, 0xc001b1a180, 0xc001a50880, 0x5b4a6e0, 0xc001249880, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:369 +0x1fb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000dbb960, 0x6aa2b48, 0xc001b1a180, 0xc0010801c0, 0xc0015004a0, 0x5b4a6e0, 0xc001249880, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:428 +0x8f7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000004810, 0x6aa2b48, 0xc001b1a180, 0xc00166a640, 0xc001b1a180, 0x6014a20, 0xc000ba5d00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000b8ea80, 0x6aa2bf0, 0xc001b1a180, 0xc001080000, 0xc000b8ea80, 0xc000ba5d70, 0xc0019f1ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb6
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x6014a20, 0xc000b8ea80, 0x6aa2bf0, 0xc000ba5d70, 0xc001b22060, 0x0, 0x6aa2bf0, 0xc000ba5d70, 0xc0001d6a80, 0x326)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000254a80, 0x6aed098, 0xc000071800, 0xc001b24000, 0xc00129af60, 0x9fe1ae0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000254a80, 0x6aed098, 0xc000071800, 0xc001b24000, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00091f8a0, 0xc000254a80, 0x6aed098, 0xc000071800, 0xc001b24000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.67.0_x5.exe plugin crashed!
```
### Expected Behavior
Private DNS zone is destroyed

### Actual Behavior
Cannot destroy private DNS zone.

### Steps to Reproduce
1. `terraform destroy`

### Additional info

Azure activity log shows:
```
Can not delete resource before nested resources are deleted.
```

**Comment by jbardin** [comment]
This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
