### ISSUE TITLE
Terraform Crash 

### ISSUE THREAD

**Issue by rumetix** [hashicorp/terraform#29276]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

### References

[crash.769144250.log](https://github.com/hashicorp/terraform/files/6908039/crash.769144250.log)
2021-07-30T09:37:56.848-0400 [INFO]  Terraform version: 1.0.3
2021-07-30T09:37:56.849-0400 [INFO]  Go runtime version: go1.16.4
2021-07-30T09:37:56.849-0400 [INFO]  CLI args: []string{"C:\\Terraform\\terraform.exe", "plan"}
2021-07-30T09:37:56.851-0400 [TRACE] Stdout is a terminal of width 94
2021-07-30T09:37:56.851-0400 [TRACE] Stderr is a terminal of width 94
2021-07-30T09:37:56.851-0400 [TRACE] Stdin is a terminal
2021-07-30T09:37:56.854-0400 [DEBUG] Attempting to open CLI config file: C:\Users\User\AppData\Roaming\terraform.rc
2021-07-30T09:37:56.854-0400 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021-07-30T09:37:56.855-0400 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021-07-30T09:37:56.855-0400 [DEBUG] ignoring non-existing provider search directory C:\Users\User\AppData\Roaming\terraform.d\plugins
2021-07-30T09:37:56.856-0400 [DEBUG] ignoring non-existing provider search directory C:\Users\User\AppData\Roaming\HashiCorp\Terraform\plugins
2021-07-30T09:37:56.856-0400 [INFO]  CLI command args: []string{"plan"}

panic: runtime error: slice bounds out of range [:-2]

goroutine 1 [running]:
github.com/hashicorp/terraform/internal/command/format.appendSourceSnippets(0x15a8f638, 0x1561ae10, 0x1580c3a8)
	/home/circleci/project/project/internal/command/format/diagnostic.go:253 +0x8e1
github.com/hashicorp/terraform/internal/command/format.DiagnosticFromJSON(0x1561ae10, 0x1580c3a8, 0x5e, 0x1561ae10, 0x1586eea0)
	/home/circleci/project/project/internal/command/format/diagnostic.go:77 +0x1cc
github.com/hashicorp/terraform/internal/command/format.Diagnostic(0x2342f1c, 0x15617f50, 0x1586eea0, 0x1580c3a8, 0x5e, 0x1df, 0x0)
	/home/circleci/project/project/internal/command/format/diagnostic.go:30 +0x4d
github.com/hashicorp/terraform/internal/command/views.(*View).Diagnostics(0x15404a60, 0x15744d70, 0x2, 0x2)
	/home/circleci/project/project/internal/command/views/view.go:114 +0x2c9
github.com/hashicorp/terraform/internal/command/views.(*PlanHuman).Diagnostics(0x1580c6b8, 0x15744d70, 0x2, 0x2)
	/home/circleci/project/project/internal/command/views/plan.go:65 +0x3b
github.com/hashicorp/terraform/internal/command.(*PlanCommand).Run(0x15aaa4b0, 0x154940d8, 0x0, 0x0, 0x1580c438)
	/home/circleci/project/project/internal/command/plan.go:69 +0x770
github.com/mitchellh/cli.(*CLI).Run(0x156213f0, 0x1556ede0, 0x1f1c232, 0x4)
	/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x336
main.wrappedMain(0x0)
	/home/circleci/project/project/main.go:384 +0x1014
main.realMain(0x0)
	/home/circleci/project/project/main.go:115 +0x475
main.main()
	/home/circleci/project/project/main.go:58 +0x1a

**Comment by jbardin** [comment]
Closed via #29277
