### ISSUE TITLE
Terraform crash when refreshing state of security group rule

### ISSUE THREAD

**Issue by jasonl** [hashicorp/terraform#2947]
This occurred after manually deleting a security group through the EC2 web interface, and running `terraform plan -module-depth=-1`

Terraform output:
```
Refreshing Terraform state prior to plan...

aws_security_group_rule.rabbit_mq_ssl_ingress: Refreshing state... (ID: sg-1046853502)
aws_volume_attachment.admin_rundeck: Refreshing state... (ID: vai-201243404)
aws_route53_record.sensu: Refreshing state... (ID: ZR3TFVWJ2331M_sensu-01_A)
aws_key_pair.admin: Refreshing state... (ID: Administration)
aws_vpc.xxxxxxx: Refreshing state... (ID: vpc-0fad0b6a)
aws_ebs_volume.logging_es.2: Refreshing state... (ID: vol-4df93f5a)
aws_ebs_volume.logging_es.0: Refreshing state... (ID: vol-4ff93f58)
aws_ebs_volume.logging_es.1: Refreshing state... (ID: vol-40f93f57)
aws_instance.admin_jumpbox: Refreshing state... (ID: i-9fb06841)
aws_route_table.xxxxxxx_public: Refreshing state... (ID: rtb-6de05008)
aws_instance.admin_nat: Refreshing state... (ID: i-cbb16915)
aws_instance.logging_es.0: Refreshing state... (ID: i-39d70ce7)
aws_instance.consul_server.0: Refreshing state... (ID: i-60d70cbe)
aws_instance.admin_haproxy: Refreshing state... (ID: i-cab16914)
aws_instance.logging_es.1: Refreshing state... (ID: i-38d70ce6)
aws_instance.consul_server.1: Refreshing state... (ID: i-3fd70ce1)
aws_instance.logging_es.2: Refreshing state... (ID: i-65d70cbb)
aws_instance.consul_server.2: Refreshing state... (ID: i-7fd60da1)
aws_instance.admin_rundeck: Refreshing state... (ID: i-826cb65c)
aws_main_route_table_association.xxxxxxx: Refreshing state... (ID: rtbassoc-958139f0)
Error refreshing state: 13 error(s) occurred:

* unexpected EOF
* unexpected EOF
* unexpected EOF
* 1 error(s) occurred:

* unexpected EOF
* 3 error(s) occurred:

* unexpected EOF
* unexpected EOF
* unexpected EOF
* 1 error(s) occurred:

* connection is shut down
* 1 error(s) occurred:

* connection is shut down
* 1 error(s) occurred:

* connection is shut down
* 1 error(s) occurred:

* connection is shut down
* 3 error(s) occurred:

* connection is shut down
* connection is shut down
* connection is shut down
* 3 error(s) occurred:

* connection is shut down
* connection is shut down
* connection is shut down
* 1 error(s) occurred:

* connection is shut down
* 1 error(s) occurred:

* connection is shut down
```

Go stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
2015/08/06 10:51:28 terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x103f29]
2015/08/06 10:51:28 terraform-provider-aws:
2015/08/06 10:51:28 terraform-provider-aws: goroutine 74 [running]:
2015/08/06 10:51:28 terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsSecurityGroupRuleRead(0x209314ba0, 0x6ac760, 0x2092f0360, 0x0, 0x0)
2015/08/06 10:51:28 terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_security_group_rule.go:164 +0xa29
2015/08/06 10:51:28 terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0x20944b600, 0x209394b70, 0x6ac760, 0x2092f0360, 0x2093253d8, 0x0, 0x0)
2015/08/06 10:51:28 terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:209 +0x475
2015/08/06 10:51:28 terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0x2093a90e0, 0x209439280, 0x209394b70, 0x6adba0, 0x0, 0x0)
2015/08/06 10:51:28 terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:187 +0x1c7
2015/08/06 10:51:28 terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Refresh(0x20942c120, 0x209421fe0, 0x2093906f0, 0x0, 0x0)
2015/08/06 10:51:28 terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/rpc/resource_provider.go:345 +0x73
2015/08/06 10:51:28 terraform-provider-aws: reflect.Value.call(0x860200, 0xa416a0, 0x13, 0xaadc60, 0x4, 0x209731f28, 0x3, 0x3, 0x0, 0x0, ...)
2015/08/06 10:51:28 terraform-provider-aws: 	/opt/go/src/reflect/value.go:419 +0x10e5
2015/08/06 10:51:28 terraform-provider-aws: reflect.Value.Call(0x860200, 0xa416a0, 0x13, 0x209731f28, 0x3, 0x3, 0x0, 0x0, 0x0)
2015/08/06 10:51:28 terraform-provider-aws: 	/opt/go/src/reflect/value.go:296 +0xbc
2015/08/06 10:51:28 terraform-provider-aws: net/rpc.(*service).call(0x20944bbc0, 0x20944bb40, 0x209420148, 0x209330300, 0x20942c140, 0x6adb40, 0x209421fe0, 0x16, 0x6adba0, 0x2093906f0, ...)
2015/08/06 10:51:28 terraform-provider-aws: 	/opt/go/src/net/rpc/server.go:382 +0x1f7
2015/08/06 10:51:28 terraform-provider-aws: created by net/rpc.(*Server).ServeCodec
2015/08/06 10:51:28 terraform-provider-aws: 	/opt/go/src/net/rpc/server.go:476 +0x44a
```

Version:
```
$ terraform --version
Terraform v0.6.1
```

I've kept the crash logs and can provide any additional information via email, as I'm unable to post too much information about our infrastructure publicly.

**Comment by jasonl** [comment]
I was able to "resolve" this by manually removing the (single) "aws_security_group_rule" stanza from `terraform.tfstate`, and incrementing the serial number therein to get around the conflict resolution checking. So my hypothesis is that Terraform is crashing because it assumes that when a security group rule exists in `terraform.tfstate`, then the security group itself must actually exist.

**Comment by catsby** [comment]
Hey @jasonl – thanks for opening this. I believe it was fixed in https://github.com/hashicorp/terraform/pull/2897 , which went out with v0.6.2. Let me know if you find otherwise.


Thanks!
