### ISSUE TITLE
Error: Plugin did not respond panic: interface conversion: interface {} is nil, not *aws.AWSClient

### ISSUE THREAD

**Issue by alexgdmx** [hashicorp/terraform#29590]
```
│ Error: Plugin did not respond
│
│   with module.bastion.aws_autoscaling_group.bastion,
│   on modules/bastion/main.tf line 318, in resource "aws_autoscaling_group" "bastion":
│  318: resource "aws_autoscaling_group" "bastion" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain
│ more details.
╵

Stack trace from the terraform-provider-aws_v3.45.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 38 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsAutoscalingGroupRead(0xc001b1cc00, 0x0, 0x0, 0xb41f4c0, 0xc000100000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_autoscaling_group.go:842 +0x270f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0008a1a40, 0x7c5a368, 0xc0021c4280, 0xc001b1cc00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0008a1a40, 0x7c5a368, 0xc0021c4280, 0xc001b12150, 0x0, 0x0, 0xc0021ee870, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000124e70, 0x7c5a368, 0xc0021c4280, 0xc0021c4340, 0xc0021c4280, 0x40b965, 0x6c20b20)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc000e9eb80, 0x7c5a410, 0xc0021c4280, 0xc0021ca1e0, 0xc000e9eb80, 0xc002136a50, 0xc002097ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x6ef0f20, 0xc000e9eb80, 0x7c5a410, 0xc002136a50, 0xc0021ca180, 0x0, 0x7c5a410, 0xc002136a50, 0xc001d80000, 0x589)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001416c0, 0x7c7bed8, 0xc0013a9800, 0xc001614000, 0xc000f949f0, 0xb3de810, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001416c0, 0x7c7bed8, 0xc0013a9800, 0xc001614000, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0013842c0, 0xc0001416c0, 0x7c7bed8, 0xc0013a9800, 0xc001614000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.45.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
