### ISSUE TITLE
"panic: runtime error: invalid memory address or nil pointer dereference" error when I run "terraform init"

### ISSUE THREAD

**Issue by aurelioacn** [hashicorp/terraform#29617]
Hello

I just downloaded terraform in my WSL Ubuntu 18.04 and when I run terraform init it triggers the bellow error. 
Same error is showed with sudo.
Looks like it is trying to use a null variable or something like that.

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.276792345.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.276792345.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**"crash.276792345.log":**
2021-09-21T08:20:57.857+0200 [INFO]  Terraform version: 1.0.7
2021-09-21T08:20:57.857+0200 [INFO]  Go runtime version: go1.16.4
2021-09-21T08:20:57.857+0200 [INFO]  CLI args: []string{"/usr/local/bin/terraform", "init"}
2021-09-21T08:20:57.857+0200 [TRACE] Stdout is a terminal of width 120
2021-09-21T08:20:57.857+0200 [TRACE] Stderr is a terminal of width 120
2021-09-21T08:20:57.857+0200 [TRACE] Stdin is a terminal
2021-09-21T08:20:57.857+0200 [DEBUG] Attempting to open CLI config file: /home/aurelio/.terraformrc
2021-09-21T08:20:57.857+0200 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021-09-21T08:20:57.857+0200 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021-09-21T08:20:57.857+0200 [DEBUG] ignoring non-existing provider search directory /home/aurelio/.terraform.d/plugins
2021-09-21T08:20:57.857+0200 [DEBUG] ignoring non-existing provider search directory /home/aurelio/.local/share/terraform/plugins
2021-09-21T08:20:57.857+0200 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2021-09-21T08:20:57.857+0200 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2021-09-21T08:20:57.857+0200 [DEBUG] ignoring non-existing provider search directory /var/lib/snapd/desktop/terraform/plugins
2021-09-21T08:20:57.858+0200 [INFO]  CLI command args: []string{"init"}
2021-09-21T08:20:57.972+0200 [TRACE] Meta.Backend: built configuration for "oss" backend with hash value 3941258732
2021-09-21T08:20:57.973+0200 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2021-09-21T08:20:57.974+0200 [DEBUG] New state was assigned lineage "8a1ce8a2-c8d8-3ce6-316d-09f10575accb"
2021-09-21T08:20:57.974+0200 [TRACE] Meta.Backend: moving from default local state only to "oss" backend

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1e6d918]

goroutine 1 [running]:
github.com/hashicorp/terraform/internal/backend/remote-state/oss.(*Backend).configure(0xc0002e9cb0, 0x2bb2aa0, 0xc0002d4090, 0x22a7b20, 0xc000457d70)
	/home/circleci/project/project/internal/backend/remote-state/oss/backend.go:323 +0xad8
github.com/hashicorp/terraform/internal/legacy/helper/schema.(*Backend).Configure(0xc0008753f8, 0x2bb46d8, 0xc000720e60, 0x2383620, 0xc00011dad0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/internal/legacy/helper/schema/backend.go:169 +0x2c9
github.com/hashicorp/terraform/internal/command.(*Meta).backendInitFromConfig(0xc00079a8c0, 0xc000538280, 0x0, 0x0, 0x0, 0x23789a0, 0xc000197650, 0xc0000f3dd0, 0xc0000f3dd0, 0x0, ...)
	/home/circleci/project/project/internal/command/meta_backend.go:1111 +0x55d
github.com/hashicorp/terraform/internal/command.(*Meta).backend_C_r_s(0xc00079a8c0, 0xc000538280, 0xeaead5ec, 0xc0003b4b40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/internal/command/meta_backend.go:746 +0x7f
github.com/hashicorp/terraform/internal/command.(*Meta).backendFromConfig(0xc00079a8c0, 0xc000a25540, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/internal/command/meta_backend.go:547 +0x7e5
github.com/hashicorp/terraform/internal/command.(*Meta).Backend(0xc00079a8c0, 0xc000b5d540, 0x0, 0xc000a25500, 0x1, 0x1, 0x0)
	/home/circleci/project/project/internal/command/meta_backend.go:88 +0x63d
github.com/hashicorp/terraform/internal/command.(*InitCommand).initBackend(0xc00079a8c0, 0xc00071e000, 0x273c795, 0xf, 0xc0002565a0, 0x1, 0x0, 0x0, 0x0, 0x9, ...)
	/home/circleci/project/project/internal/command/init.go:401 +0x158
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc00079a8c0, 0xc000140010, 0x0, 0x0, 0xc0005620c0)
	/home/circleci/project/project/internal/command/init.go:216 +0xe17
github.com/mitchellh/cli.(*CLI).Run(0xc00077cdc0, 0xc000536030, 0x2725f08, 0x4)
	/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
main.wrappedMain(0x0)
	/home/circleci/project/project/main.go:384 +0x1112
main.realMain(0x0)
	/home/circleci/project/project/main.go:115 +0x554
main.main()
	/home/circleci/project/project/main.go:58 +0x25

**Comment by alisdair** [comment]
Thanks for reporting this. I can reproduce the crash with the following config:

```hcl
terraform {
  backend "oss" {
    bucket = "test"
  }
}
```

**Comment by alisdair** [comment]
@xiaozhu36 I think this may have been introduced with #29167, could you take a look?

**Comment by xiaozhu36** [comment]
@alisdair Got it. I will check it.

**Comment by xiaozhu36** [comment]
Hi @gothrek22 If you setting the profile in the oss backend or by `ALICLOUD_PROFILE `, the oss provider will get access key and secret key from the profile automatically.
