### ISSUE TITLE
Terraform segfaults during apply

### ISSUE THREAD

**Issue by jbg** [hashicorp/terraform#29707]
### Terraform Version
```
Terraform v1.0.8
on linux_arm64
+ provider registry.terraform.io/chilicat/pkcs12 v0.0.7
+ provider registry.terraform.io/cyrilgdn/postgresql v1.14.0
+ provider registry.terraform.io/gavinbunney/kubectl v1.11.3
+ provider registry.terraform.io/grafana/grafana v1.14.0
+ provider registry.terraform.io/hashicorp/aws v3.61.0
+ provider registry.terraform.io/hashicorp/google v3.87.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.5.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/integrations/github v4.16.0
+ provider registry.terraform.io/linode/linode v1.21.0
+ provider registry.terraform.io/vancluever/acme v2.5.3
```

### Crash Output
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0xaaaae9b17d18]

goroutine 25658 [running]:
github.com/hashicorp/terraform/internal/plans.(*ResourceInstanceChange).Simplify(0x0, 0x1)
	/home/buildozer/aports/community/terraform/src/src/github.com/hashicorp/terraform/internal/plans/changes.go:236 +0x28
github.com/hashicorp/terraform/internal/terraform.reducePlan({{}, {{}, 0x4d, {0x400173fde0, 0xb}, {0x400173fdf0, 0x4}}, {0xaaaaec63b618, 0x401389af90}}, 0x0, ...)
	/home/buildozer/aports/community/terraform/src/src/github.com/hashicorp/terraform/internal/terraform/reduce_plan.go:23 +0x30
github.com/hashicorp/terraform/internal/terraform.(*NodeDestroyResourceInstance).managedResourceExecute(0x400cde3e48, {0xaaaaec6b6040, 0x401d9abb20})
	/home/buildozer/aports/community/terraform/src/src/github.com/hashicorp/terraform/internal/terraform/node_resource_destroy.go:173 +0x2a8
github.com/hashicorp/terraform/internal/terraform.(*NodeDestroyResourceInstance).Execute(0x400cde3e48, {0xaaaaec6b6040, 0x401d9abb20}, 0x1)
	/home/buildozer/aports/community/terraform/src/src/github.com/hashicorp/terraform/internal/terraform/node_resource_destroy.go:140 +0x94
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x401443dad0, {0xaaaaec6b6040, 0x401d9abb20}, {0xffff5a747b40, 0x400cde3e48})
	/home/buildozer/aports/community/terraform/src/src/github.com/hashicorp/terraform/internal/terraform/graph_walk_context.go:129 +0x9c
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0xaaaaec5ace20, 0x400cde3e48})
	/home/buildozer/aports/community/terraform/src/src/github.com/hashicorp/terraform/internal/terraform/graph.go:59 +0x224
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x4009190960, {0xaaaaec5ace20, 0x400cde3e48}, 0x401c3dd700)
	/home/buildozer/aports/community/terraform/src/src/github.com/hashicorp/terraform/internal/dag/walk.go:381 +0x318
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/home/buildozer/aports/community/terraform/src/src/github.com/hashicorp/terraform/internal/dag/walk.go:304 +0xe34
```

### Steps to Reproduce
This crash has been happening to us intermittently, a few times a day in our CI, during the last few 1.0.x versions. I occasionally reproduce it on my development laptop (darwin_arm64) too.

Running `force-unlock` (because it leaves the state locked when it crashes) and then `apply` again with no changes always works.

There does not seem to be any consistency about which provider it's applying changes using when it crashes.

The stacktrace is very similar to the one reported in #26346.

**Comment by jbardin** [comment]
Thanks @jbg,

I can see the logic error leading to this panic, so the fix is relatively straightforward; however I would really like to understand how the situation arises in the first place.

Any chance you could share a trace log from the crash? Using `TF_LOG_CORE=trace` will skip all the provider logs, and reduce the amount of data that may need to be redacted if any. 

Thanks!
