### ISSUE TITLE
Terraform crash: invalid memory address or nil pointer dereferencegoroutine 2061 [running]

### ISSUE THREAD

**Issue by dvalemark** [hashicorp/terraform#30125]
### Terraform Version

```
1.1.0
```

### Terraform Configuration Files

No changes to files that has deployed fine earlier today.

### Debug Output
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereferencegoroutine 2061 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:44 +0xb5
panic({0x221d240, 0x3ed5b10})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/instances.(*expanderModule).onlyResourceInstances(0xc002363270, {{}, 0x4d, {0xc0008c4cf0, 0x16}, {0xc0008d4c48, 0x8}}, {0xc00170f700, 0x30, 0x4})
	/home/circleci/project/project/internal/instances/expander.go:392 +0x95
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x42, {0xc00080a4a0, 0x0, 0xc0005f8000}, {{}, 0x4d, {0xc0008c4cf0, 0x16}, {0xc0008d4c48, 0x8}}, ...)
	/home/circleci/project/project/internal/instances/expander.go:387 +0x2e5
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc0010ac498, {0xc00080a4a0, 0x1, 0x1}, {{}, 0x4d, {0xc0008c4cf0, 0x16}, {0xc0008d4c48, 0x8}}, ...)
	/home/circleci/project/project/internal/instances/expander.go:385 +0x293
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0xc001607cc0, {{}, {0xc00080a4a0, 0x1, 0x1}, {{}, 0x4d, {0xc0008c4cf0, 0x16}, {0xc0008d4c48, ...}}})
	/home/circleci/project/project/internal/instances/expander.go:157 +0x16f
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0xc003986610, {0x2aecc00, 0xc00129aa80})
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:182 +0x445
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc003986610, {0x2aecc00, 0xc00129aa80})
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:140 +0x58c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x0, {0x2aecc00, 0xc00129aa80}, 0xc0)
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc000cfa1c0, {0x2aecc00, 0xc00129aa80}, {0x7f221214ecf0, 0xc003986610})
	/home/circleci/project/project/internal/terraform/graph_walk_context.go:133 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2553ec0, 0xc003986610})
	/home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000036b40, {0x2553ec0, 0xc003986610}, 0xc003dc8f00)
	/home/circleci/project/project/internal/dag/walk.go:381 +0x2f1
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/home/circleci/project/project/internal/dag/walk.go:304 +0xf85
Error: Terraform exited with code 11.
Error: Process completed with exit code 1.

**Comment by alisdair** [comment]
Hi @dvalemark, thanks for reporting this. It looks like the same bug as #30110, so I'm closing this issue as a duplicate.

If you can share any details about your configuration, that might help us fix the issue quicker!
