### ISSUE TITLE
Crash during `terraform plan`

### ISSUE THREAD

**Issue by malte-ehrlen** [hashicorp/terraform#30161]
### Terraform Version

```
Terraform v1.1.0
on linux_amd64
+ provider registry.terraform.io/datadog/datadog v3.2.0
+ provider registry.terraform.io/hashicorp/google v3.90.1
+ provider registry.terraform.io/hashicorp/google-beta v3.90.1
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.4
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.3.2
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```
### Output
```terraform plan
[...]
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereferencegoroutine 5976 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:44 +0xb5
panic({0x221d240, 0x3ed5b10})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/instances.(*expanderModule).onlyResourceInstances(0xc00563f270, {{}, 0x4d, {0xc0012252a0, 0x19}, {0xc000a62e30, 0xf}}, {0xc0049cf980, 0x30, 0x4})
	/home/circleci/project/project/internal/instances/expander.go:392 +0x95
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x4f, {0xc000d09a60, 0x0, 0xc000fccc00}, {{}, 0x4d, {0xc0012252a0, 0x19}, {0xc000a62e30, 0xf}}, ...)
	/home/circleci/project/project/internal/instances/expander.go:387 +0x2e5
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc001d3bd28, {0xc000d09a60, 0x1, 0x1}, {{}, 0x4d, {0xc0012252a0, 0x19}, {0xc000a62e30, 0xf}}, ...)
	/home/circleci/project/project/internal/instances/expander.go:385 +0x293
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0xc000b0bf60, {{}, {0xc000d09a60, 0x1, 0x1}, {{}, 0x4d, {0xc0012252a0, 0x19}, {0xc000a62e30, ...}}})
	/home/circleci/project/project/internal/instances/expander.go:157 +0x16f
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0xc0044b4050, {0x2aecc00, 0xc00004b180})
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:182 +0x445
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc0044b4050, {0x2aecc00, 0xc00004b180})
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:140 +0x58c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x0, {0x2aecc00, 0xc00004b180}, 0x30)
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc000ea01c0, {0x2aecc00, 0xc00004b180}, {0x7ff705311938, 0xc0044b4050})
	/home/circleci/project/project/internal/terraform/graph_walk_context.go:133 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2553ec0, 0xc0044b4050})
	/home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000aed860, {0x2553ec0, 0xc0044b4050}, 0xc0054ee800)
	/home/circleci/project/project/internal/dag/walk.go:381 +0x2f1
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/home/circleci/project/project/internal/dag/walk.go:304 +0xf85

```

### Expected Behavior
terraform generates a plan

### Actual Behavior
terraform crashes with NPE

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Additional Context
Issue happens during one of many `Refreshing state...` outputs. Reproducible, I cannot get this version to work in fact. I cannot share the context or output of the previous lines, so I guess close the ticket if it is not useful without that information.

**Comment by malte-ehrlen** [comment]
Downgrading to 1.0.5 mitigates the issue

**Comment by aschleck** [comment]
Terraform 1.1 from Homebrew (M1) was working for me yesterday (last usage at 23:32), today I get this error.

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereferencegoroutine 3864 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x88
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x20
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        github.com/hashicorp/terraform/internal/logging/panic.go:44 +0xe0
panic({0x10309c660, 0x10484cb10})
        runtime/panic.go:1038 +0x21c
github.com/hashicorp/terraform/internal/instances.(*expanderModule).onlyResourceInstances(0x0, {{}, 0x4d, {0x14000ab7e30, 0xc}, {0x14000ab7e28, 0x4}}, {0x14002d01180, 0x4, 0x4})
        github.com/hashicorp/terraform/internal/instances/expander.go:392 +0x44
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x0, {0x14000e838e0, 0x0, 0x0}, {{}, 0x4d, {0x14000ab7e30, 0xc}, {0x14000ab7e28, 0x4}}, ...)
        github.com/hashicorp/terraform/internal/instances/expander.go:387 +0x26c
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x14003fcfc98, {0x14000e838e0, 0x1, 0x1}, {{}, 0x4d, {0x14000ab7e30, 0xc}, {0x14000ab7e28, 0x4}}, ...)
        github.com/hashicorp/terraform/internal/instances/expander.go:385 +0x204
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x140035c31a0, {0x14000e838c0, 0x2, 0x2}, {{}, 0x4d, {0x14000ab7e30, 0xc}, {0x14000ab7e28, 0x4}}, ...)
        github.com/hashicorp/terraform/internal/instances/expander.go:385 +0x204
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x14002bfc000, {0x14000e838a0, 0x3, 0x3}, {{}, 0x4d, {0x14000ab7e30, 0xc}, {0x14000ab7e28, 0x4}}, ...)
        github.com/hashicorp/terraform/internal/instances/expander.go:385 +0x204
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x14002203128, {0x14000e83880, 0x4, 0x4}, {{}, 0x4d, {0x14000ab7e30, 0xc}, {0x14000ab7e28, 0x4}}, ...)
        github.com/hashicorp/terraform/internal/instances/expander.go:385 +0x204
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0x14001bb6fe0, {{}, {0x14000e83880, 0x4, 0x4}, {{}, 0x4d, {0x14000ab7e30, 0xc}, {0x14000ab7e28, ...}}})
        github.com/hashicorp/terraform/internal/instances/expander.go:157 +0x11c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0x14001763a60, {0x1034fed60, 0x14002999340})
        github.com/hashicorp/terraform/internal/terraform/node_resource_plan_orphan.go:182 +0x2c0
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0x14001763a60, {0x1034fed60, 0x14002999340})
        github.com/hashicorp/terraform/internal/terraform/node_resource_plan_orphan.go:140 +0x640
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x14001763a60, {0x1034fed60, 0x14002999340}, 0x2)
        github.com/hashicorp/terraform/internal/terraform/node_resource_plan_orphan.go:49 +0x94
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x14000f5a8c0, {0x1034fed60, 0x14002999340}, {0x12e5165d8, 0x14001763a60})
        github.com/hashicorp/terraform/internal/terraform/graph_walk_context.go:133 +0x9c
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x1033c5140, 0x14001763a60})
        github.com/hashicorp/terraform/internal/terraform/graph.go:74 +0x244
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x14000e36480, {0x1033c5140, 0x14001763a60}, 0x140056dbbc0)
        github.com/hashicorp/terraform/internal/dag/walk.go:381 +0x31c
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
        github.com/hashicorp/terraform/internal/dag/walk.go:304 +0xe0c
```

```
Terraform v1.1.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.69.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```
