### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bwmetcalf** [hashicorp/terraform#30184]
### Terraform Version
```
$ terraform -version
Terraform v1.1.1
on darwin_amd64
```
This first occurred with v1.1.0.

### Terraform Configuration Files
```
terraform plan -target=module.path.module.path.module.s3.module.s3_bucket.data.aws_partition.current
```
The module above uses https://github.com/cloudposse/terraform-aws-s3-bucket.  A top level plan does not crash.

We can reproduce this with other targets.  Unfortunately, I am not able to share specific code examples.

### Actual Behavior
The target above results in
```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

no expansion has been registered for module.environment
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
```
Another target results in the following output.
```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

no expansion has been registered for module.environment.module.vpn
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereferencegoroutine 67 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /Users/distiller/project/project/internal/logging/panic.go:44 +0xb5
panic({0x2e23ee0, 0x4ae90d0})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0x0)
        /Users/distiller/project/project/internal/plans/plan.go:70 +0x19
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc0009280a0, {0x367f918, 0xc000a94280}, {0x367f918, 0xc000a942c0}, 0xc000e1e7e0, 0xc000a94240)
        /Users/distiller/project/project/internal/backend/local/backend_plan.go:105 +0x4b8
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
        /Users/distiller/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
        /Users/distiller/project/project/internal/backend/local/backend.go:316 +0x445
goroutine 143266 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /Users/distiller/project/project/internal/logging/panic.go:44 +0xb5
panic({0x2d2b860, 0xc02042fc80})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/instances.(*expanderModule).moduleInstances(0xc04c685dd0, {0xc011394950, 0x3, 0x3}, {0xc01ba42bc0, 0x1, 0x4})
        /Users/distiller/project/project/internal/instances/expander.go:354 +0x874
github.com/hashicorp/terraform/internal/instances.(*expanderModule).moduleInstances(0xc0240f6000, {0xc011394940, 0x4, 0x4}, {0xc01ed7cbc0, 0x0, 0x4})
        /Users/distiller/project/project/internal/instances/expander.go:366 +0x619
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandModule(0xc00bc30af0, {0xc011394940, 0x4, 0x0})
        /Users/distiller/project/project/internal/instances/expander.go:116 +0x130
github.com/hashicorp/terraform/internal/instances.Set.InstancesForModule(...)
        /Users/distiller/project/project/internal/instances/set.go:50
github.com/hashicorp/terraform/internal/refactoring.ValidateMoves({0xc04e6af600, 0x8, 0x2}, 0xc01ba43c70, {0x1})
        /Users/distiller/project/project/internal/refactoring/move_validate.go:76 +0xd5c
github.com/hashicorp/terraform/internal/terraform.(*Context).postPlanValidateMoves(...)
        /Users/distiller/project/project/internal/terraform/context_plan.go:392
github.com/hashicorp/terraform/internal/terraform.(*Context).planWalk(0x40, 0xc000c201c0, 0xc04ea02480, 0xc04e520a20, 0xc00efbd540)
        /Users/distiller/project/project/internal/terraform/context_plan.go:430 +0x42c
github.com/hashicorp/terraform/internal/terraform.(*Context).plan(0x0, 0x0, 0x0, 0xc02b039e30, 0x1)
        /Users/distiller/project/project/internal/terraform/context_plan.go:182 +0x2b
github.com/hashicorp/terraform/internal/terraform.(*Context).Plan(0x320e1e0, 0xc000c201c0, 0xc00accda80, 0xc00efbd540)
        /Users/distiller/project/project/internal/terraform/context_plan.go:128 +0x5bc
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan.func2()
        /Users/distiller/project/project/internal/backend/local/backend_plan.go:86 +0xaa
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan
        /Users/distiller/project/project/internal/backend/local/backend_plan.go:82 +0x351
```

**Comment by alisdair** [comment]
Hi @bwmetcalf, thanks for reporting this! I'm having trouble to reproduce it.

I know you can't share specific code examples, but can you say anything about the configuration? A few questions which would help us figure out what's happening:

- Are you using `moved` statements at all?
- Do any of the modules in the path to the target use `for_each` or `count`?
- What are the changes you are trying to apply at the target?

**Comment by dannyleesmith** [comment]
[module_example.zip](https://github.com/hashicorp/terraform/files/7729466/module_example.zip)

Attached should be a zip that I think gives a working example, certainly for my issue at least but it feels related to the opening comment. If it is not related when OP gives their answers to their questions or mod feels its a separate issue I can open a new issue if required.

For the example given:

- main.tf with dirs to act as v1 and v2 modules
- `terraform init` and `terraform apply` to get your random_pet
- change source of module to `./module_v2`; v2 has `moved` the naming of the `random_pet`
- `terraform apply` to see that `moved` has worked
- `terraform destroy` gave me `Destroy complete! Resources: 0 destroyed.`
- `terraform state list` gave me: `module.example.random_pet.this`
- a further `terraform destroy` gave me: 

```
$ terraform destroy
module.example.random_pet.this: Refreshing state... [id=quickly-delicate-tadpole]

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

no expansion has been registered for module.example
Destroy complete! Resources: 0 destroyed.
```

**Comment by bwmetcalf** [comment]
We are now seeing this from a top level apply.

* _Are you using moved statements at all?_  Yes
* _Do any of the modules in the path to the target use for_each or count?_ Yes
* _What are the changes you are trying to apply at the target?_ It's just a plan against the `aws_partition` data source

We are removing the `moved` blocks and will report back with the results.

**Comment by bwmetcalf** [comment]
After removing the `moved` blocks, the target in my original post no longer crashes.

**Comment by freakinhippie** [comment]
I'm seeing this issue as well. Should I post in here or create a separate issue?

**Comment by freakinhippie** [comment]
```
Terraform v1.1.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.69.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/vault v3.0.1
```

**Comment by freakinhippie** [comment]
I should mention that I'm also seeing it on a Linux system as well.

**Comment by lafentres** [comment]
Using information from the duplicate issue #30186, I was able to reproduce the "no expansion has been registered for module.<etc>" error.

I ran `terraform apply` and then `terraform apply -destroy -target=module.local-tfe[0]` with the following config:

#### local module code at ./modules/terraform-tfe-module
```terraform
// ./modules/terraform-tfe-module/main.tf

resource "tfe_organization" "test-org" {
  name  = "test-org"
  email = "<your-email>"
}

resource "tfe_workspace" "workspace1" {
  name         = "module-workspace1"
  organization = tfe_organization.test-org.name
}

moved {
  from = tfe_workspace.workspace
  to   = tfe_workspace.workspace1
}

resource "tfe_variable" "test-var1" {
  key          = "test-var1"
  value        = "test-value1"
  category     = "terraform"
  workspace_id = tfe_workspace.workspace1.id
}

resource "tfe_variable" "test-var2" {
  key          = "test-var2"
  value        = "test-value2"
  category     = "terraform"
  workspace_id = tfe_workspace.workspace1.id
}

resource "tfe_notification_configuration" "test-notification1" {
  name             = "my-test-notification-configuration1"
  enabled          = true
  destination_type = "generic"
  triggers         = ["run:created"]
  url              = "https://example.com"
  workspace_id     = tfe_workspace.workspace1.id
}
```

#### main config:
```terraform
// ./main.tf
terraform {
  required_providers {
    tfe = {
      source  = "hashicorp/tfe"
    }
  }
}

module "local-tfe" {
  source = "./modules/terraform-tfe-module"
}
```

**Comment by adamhorden** [comment]
We are seeing this on multiple projects on CICD as well. Reverting the Terraform version used worked. We was using Terraform v1.1.0 and now Terraform v1.0.10.

**Adam Horden**

**Comment by alisdair** [comment]
@dannyleesmith Thank you for the reproduction case for the crash you're seeing! While the panic is definitely in the same area of code, I'd like to make sure we validate that any fix addresses both issues. If you could file the same information in a separate issue that would be very helpful.
