### ISSUE TITLE
Crash with "no expansion has been registered"

### ISSUE THREAD

**Issue by tmccombs** [hashicorp/terraform#30186]
### Terraform Version

```
Terraform v1.1.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.63.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

I'm not really sure what is relevant and the full configuration is pretty large and complicated.

### Expected Behavior
terraform should not crash

### Actual Behavior
terraform crashed with the output:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

no expansion has been registered for module.commongoroutine 5557 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:44 +0xb5
panic({0x21283e0, 0xc00842c320})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/instances.(*expanderModule).moduleInstances(0xc008e08090, {0xc00075ac60, 0x1, 0x1}, {0xc007eb0b00, 0x0, 0x4})
	/home/circleci/project/project/internal/instances/expander.go:354 +0x874
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandModule(0xc000331ea0, {0xc00075ac60, 0x1, 0x6f6e2e6d726f6661})
	/home/circleci/project/project/internal/instances/expander.go:116 +0x130
github.com/hashicorp/terraform/internal/instances.Set.InstancesForModule(...)
	/home/circleci/project/project/internal/instances/set.go:50
github.com/hashicorp/terraform/internal/refactoring.ValidateMoves({0xc000938f00, 0xe, 0x0}, 0xc007eb1bb0, {0x1})
	/home/circleci/project/project/internal/refactoring/move_validate.go:76 +0xd5c
github.com/hashicorp/terraform/internal/terraform.(*Context).postPlanValidateMoves(...)
	/home/circleci/project/project/internal/terraform/context_plan.go:392
github.com/hashicorp/terraform/internal/terraform.(*Context).planWalk(0x40, 0xc0013e42a0, 0xc008780200, 0xc0065c9aa0, 0xc0024dc680)
	/home/circleci/project/project/internal/terraform/context_plan.go:430 +0x42c
github.com/hashicorp/terraform/internal/terraform.(*Context).plan(0x0, 0x0, 0x0, 0xc0032ebd70, 0x1)
	/home/circleci/project/project/internal/terraform/context_plan.go:182 +0x2b
github.com/hashicorp/terraform/internal/terraform.(*Context).Plan(0x2656a35, 0xc0013e42a0, 0xc003f06550, 0xc0024dc680)
	/home/circleci/project/project/internal/terraform/context_plan.go:128 +0x5bc
github.com/hashicorp/terraform/internal/terraform.(*Context).Refresh(0xc0063b1400, 0x1e6f960, 0xc00361c00c, 0x1e6f9c0)
	/home/circleci/project/project/internal/terraform/context_refresh.go:31 +0xcf
github.com/hashicorp/terraform/internal/backend/local.(*Local).opRefresh.func2()
	/home/circleci/project/project/internal/backend/local/backend_refresh.go:83 +0x88
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).opRefresh
	/home/circleci/project/project/internal/backend/local/backend_refresh.go:80 +0x431
```

### Additional Context
I got this while running a targeted refresh, shortly after applying a change using the new `moved` blocks.

**Comment by tmccombs** [comment]
Possibly related to https://github.com/hashicorp/terraform/issues/30184

**Comment by grimm26** [comment]
I got this while trying to destroy two specific targets in a state file, both were mentioned in a `moved` block but that move had already happened previously.

**Comment by lafentres** [comment]
Hello @tmccombs! 

Thanks for reporting this. Just to make sure I fully understand: 
When you're running a targeted refresh, are you targeting resources not mentioned by the `moved` blocks in your module (basically what @grimm26 describes, but with refresh instead of destroy)?

**Comment by tmccombs** [comment]
yes, I am targetting resources not mentioned by the moved blocks. 

I also just got the same crash when doing a targeted plan (there are moved blocks, which have already been applied, but are not part of the targeted plan).

**Comment by tmccombs** [comment]
After removing the `moved` blocks, the targetted plan succeeds without crashing.

**Comment by lafentres** [comment]
@tmccombs and @grimm26 after further investigation, I can confirm that this issue is the same as #30184 that @tmccombs mentioned. I'm going to go ahead and close this as a duplicate so we can keep all conversation and reproduction cases in one place. 

Thank you both again for your reports. It has helped me craft a simple reproduction case, which I'll post on the other issue.
