### ISSUE TITLE
provider crash 2.85.0 for create : azurerm_machine_learning_compute_instance

### ISSUE THREAD

**Issue by aziz-zaroual** [hashicorp/terraform#30301]
hello all

i cant create my azure ML compute instance , the provider crash on the Terraform validate

i use the terraform 0.14.6 and i have this error 

>  !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
> Terraform crashed! This is always indicative of a bug within Terraform.
 > A crash log has been placed at "crash.log" relative to your current
 > working directory. It would be immensely helpful if you could please
 > report the crash with Terraform[1] so that we can fix this.
 
 > When reporting bugs, please include your terraform version. That
 > information is available on the first line of crash.log. You can also
 > get it by running 'terraform --version' on the command line.
 
 > SECURITY WARNING: the "crash.log" file that was created may contain 
 > sensitive information that must be redacted before it is safe to share 
 > on the issue tracker.
 
 > [1]: https://github.com/hashicorp/terraform/issues
 
 > !!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

and i use the 0.15.5 and 1.1.0 and i have this error 

``` 
on .terraform/modules/mod-azurerm-compute-std-compute-instance/main.tf line 113, in resource "azurerm_machine_learning_compute_instance" "compute_instance":
113: resource "azurerm_machine_learning_compute_instance" "compute_instance" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
more details.

Stack trace from the terraform-provider-azurerm_v2.85.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1139 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/machinelearning.expandComputePersonalComputeInstanceSetting(...)
   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/machinelearning/machine_learning_compute_instance_resource.go:293
github.com/hashicorp/terraform-provider-azurerm/internal/services/machinelearning.resourceComputeInstanceCreate(0xc00177da00, 0x5ee1820, 0xc0016ed880, 0x0, 0x0)
   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/machinelearning/machine_learning_compute_instance_resource.go:189 +0x1a47
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000e467e0, 0x6fcf388, 0xc001b57980, 0xc00177da00, 0x5ee1820, 0xc0016ed880, 0x0, 0x0, 0x0)
   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000e467e0, 0x6fcf388, 0xc001b57980, 0xc0019a1ad0, 0xc00177d780, 0x5ee1820, 0xc0016ed880, 0x0, 0x0, 0x0, ...)
   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000dd58, 0x6fcf388, 0xc001b57980, 0xc002c74640, 0xc001b57980, 0x641d0c0, 0xc0029abd00)
   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:977 +0xacf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001e80000, 0x6fcf430, 0xc001b57980, 0xc0003adab0, 0xc001e80000, 0xc0029abd40, 0xc0016c0ba0)
   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x641d0c0, 0xc001e80000, 0x6fcf430, 0xc0029abd40, 0xc001ee1e60, 0x0, 0x6fcf430, 0xc0029abd40, 0xc002213900, 0x1030)
   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000234a80, 0x7023fd8, 0xc000fbc180, 0xc00132a000, 0xc001395470, 0xad6ece0, 0x0, 0x0, 0x0)
   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000234a80, 0x7023fd8, 0xc000fbc180, 0xc00132a000, 0x0)
   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000f9aa40, 0xc000234a80, 0x7023fd8, 0xc000fbc180, 0xc00132a000)
   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.85.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

##[error]Error: The process '/opt/hostedtoolcache/terraform/0.15.5/x64/terraform' failed with exit code 1````

**Comment by aziz-zaroual** [comment]
hello 

when i put an instance name with 16 caracters i have a provider crash , i open a crash case : [https://github.com/hashicorp/terraform/issues/30301](url)

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by aziz-zaroual** [comment]
thanks for your recommendation, i will open this issue on AzureRM provider page
