### ISSUE TITLE
Getting an error and Terraform crash when trying to create a Grafana dashboard using Terraform

### ISSUE THREAD

**Issue by smecaly** [hashicorp/terraform#30321]
I am trying to create a Grafana dashboard using terraform and it keeps throwing the below error when i try to do terraform apply. It seems to be a bug with the Grafana terraform provider but not sure and  just wanted to check if anyone out there is experiencing the same issue. 

running "/home/atlantis/.atlantis/bin/terraform0.13.5 apply -input=false -no-color \"/home/atlantis/.atlantis/repos/omfterraform/network/223/default/baseline/aws/omfcardsdev/us-east-1/cluster-vpc/default.tfplan\"" in "/home/atlantis/.atlantis/repos/omfterraform/network/223/default/baseline/aws/omfcardsdev/us-east-1/cluster-vpc": exit status 1
grafana_dashboard.tgwmetrics: Creating...
grafana_dashboard.tgwmetrics: Still creating... [10s elapsed]
grafana_dashboard.tgwmetrics: Still creating... [20s elapsed]
grafana_dashboard.tgwmetrics: Still creating... [30s elapsed]
grafana_dashboard.tgwmetrics: Still creating... [40s elapsed]
grafana_dashboard.tgwmetrics: Still creating... [50s elapsed]
grafana_dashboard.tgwmetrics: Still creating... [1m0s elapsed]
grafana_dashboard.tgwmetrics: Still creating... [1m10s elapsed]
grafana_dashboard.tgwmetrics: Still creating... [1m20s elapsed]
grafana_dashboard.tgwmetrics: Still creating... [1m30s elapsed]
grafana_dashboard.tgwmetrics: Still creating... [1m40s elapsed]
grafana_dashboard.tgwmetrics: Still creating... [1m50s elapsed]
grafana_dashboard.tgwmetrics: Still creating... [2m0s elapsed]
grafana_dashboard.tgwmetrics: Still creating... [2m10s elapsed]

Error: rpc error: code = Canceled desc = context canceled

panic: runtime error: invalid memory address or nil pointer dereference
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8fbf2b]
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: 
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: goroutine 38 [running]:
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: github.com/grafana/grafana-api-golang-client.(*Client).request(0xc0002a6a90, 0xde76cb, 0x4, 0xdf23f2, 0x12, 0x0, 0xeec6c0, 0xc0005c1b00, 0xc873e0, 0xc00000ebf0, ...)
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: 	github.com/grafana/grafana-api-golang-client@v0.1.2/client.go:114 +0x26b
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: github.com/grafana/grafana-api-golang-client.(*Client).NewDashboard(0xc0002a6a90, 0x0, 0x0, 0x0, 0x0, 0xc0002151a0, 0x0, 0x0, 0x0, 0x0, ...)
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: 	github.com/grafana/grafana-api-golang-client@v0.1.2/dashboard.go:65 +0x1d9
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: github.com/grafana/terraform-provider-grafana/grafana.CreateDashboard(0xeffb08, 0xc00023e240, 0xc000432480, 0xc8d320, 0xc0004f33d0, 0xc000140880, 0x6e81ea, 0xc000432280)
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: 	github.com/grafana/terraform-provider-grafana/grafana/resource_dashboard.go:169 +0xfa
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0000f4a80, 0xeffa98, 0xc0002b6680, 0xc000432480, 0xc8d320, 0xc0004f33d0, 0x0, 0x0, 0x0)
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:341 +0x17f
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000f4a80, 0xeffa98, 0xc0002b6680, 0xc0002a6b60, 0xc000432280, 0xc8d320, 0xc0004f33d0, 0x0, 0x0, 0x0, ...)
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:467 +0x67b
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000d290, 0xeffa98, 0xc0002b6680, 0xc0004c8820, 0xdf2482, 0x12, 0x0)
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/grpc_provider.go:977 +0xacf
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000e2680, 0xeffb40, 0xc0002b6680, 0xc0000bd1f0, 0x0, 0x0, 0x0)
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: 	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x465
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xdb06e0, 0xc0000e2680, 0xeffb40, 0xc00049e8d0, 0xc000496300, 0x0, 0xeffb40, 0xc00049e8d0, 0xc000758000, 0x7e4f9)
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: 	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fec40, 0xf07218, 0xc000420600, 0xc0005b8000, 0xc0002965d0, 0x13bc700, 0x0, 0x0, 0x0)
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: 	google.golang.org/grpc@v1.42.0/server.go:1282 +0x52b
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: google.golang.org/grpc.(*Server).handleStream(0xc0001fec40, 0xf07218, 0xc000420600, 0xc0005b8000, 0x0)
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: 	google.golang.org/grpc@v1.42.0/server.go:1616 +0xd0c
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0004e2030, 0xc0001fec40, 0xf07218, 0xc000420600, 0xc0005b8000)
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: 	google.golang.org/grpc@v1.42.0/server.go:921 +0xab
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-01-06T00:28:08.936Z [DEBUG] plugin.terraform-provider-grafana_v1.17.0: 	google.golang.org/grpc@v1.42.0/server.go:919 +0x1fd
2022-01-06T00:28:08.938Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/grafana/grafana/1.17.0/linux_amd64/terraform-provider-grafana_v1.17.0 pid=12055 error="exit status 2"
2022/01/06 00:28:08 [DEBUG] grafana_dashboard.tgwmetrics: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Canceled desc = context canceled
2022/01/06 00:28:08 [TRACE] eval: *terraform.EvalMaybeTainted
2022/01/06 00:28:08 [TRACE] EvalMaybeTainted: grafana_dashboard.tgwmetrics encountered an error during creation, so it is now marked as tainted
2022/01/06 00:28:08 [TRACE] eval: *terraform.EvalWriteState
2022/01/06 00:28:08 [TRACE] EvalWriteState: removing state object for grafana_dashboard.tgwmetrics
2022/01/06 00:28:08 [TRACE] eval: *terraform.EvalApplyProvisioners
2022/01/06 00:28:08 [TRACE] EvalApplyProvisioners: grafana_dashboard.tgwmetrics has no state, so skipping provisioners
2022/01/06 00:28:08 [TRACE] eval: *terraform.EvalMaybeTainted
2022/01/06 00:28:08 [TRACE] EvalMaybeTainted: grafana_dashboard.tgwmetrics encountered an error during creation, so it is now marked as tainted
2022/01/06 00:28:08 [TRACE] eval: *terraform.EvalWriteState
2022/01/06 00:28:08 [TRACE] EvalWriteState: removing state object for grafana_dashboard.tgwmetrics
2022/01/06 00:28:08 [TRACE] eval: *terraform.EvalIf
2022/01/06 00:28:08 [TRACE] eval: *terraform.EvalIf
2022/01/06 00:28:08 [TRACE] eval: *terraform.EvalWriteDiff
2022/01/06 00:28:08 [TRACE] eval: *terraform.EvalApplyPost
2022/01/06 00:28:08 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Canceled desc = context canceled
2022/01/06 00:28:08 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Canceled desc = context canceled
2022/01/06 00:28:08 [TRACE] [walkApply] Exiting eval tree: grafana_dashboard.tgwmetrics
2022/01/06 00:28:08 [TRACE] vertex "grafana_dashboard.tgwmetrics": visit complete
2022/01/06 00:28:08 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/grafana/grafana\"].grafana (close)" errored, so skipping
2022-01-06T00:28:08.938Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Canceled desc = context canceled"
2022/01/06 00:28:08 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2022/01/06 00:28:08 [TRACE] dag/walk: upstream of "root" errored, so skipping
2022-01-06T00:28:09.015Z [DEBUG] plugin: plugin exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by smecaly** [comment]
grafana = {
      source = "grafana/grafana"
      version = "1.17.0"
