### ISSUE TITLE
Terraform-provider-azurerm_v2.93.0_x5 plugin crashed

### ISSUE THREAD

**Issue by manfred0191** [hashicorp/terraform#30387]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

### Actual Behavior

terraform plan produced a crash in the plugin:

```
[0KRunning with gitlab-runner 14.6.0 (5316d4ac)[0;m
[0K  on fits-shared-runner 06b8e6b3[0;m
section_start:1642752360:prepare_executor
[0K[0K[36;1mPreparing the "docker" executor[0;m[0;m
[0KUsing Docker executor with image registry.fits.cloud/cloud-public/images/gitlab-terraform:v0.24.0 ...[0;m
[0KPulling docker image registry.fits.cloud/cloud-public/images/gitlab-terraform:v0.24.0 ...[0;m
[0KUsing docker image sha256:d3dd647faaf650ade5445c415db4715e0866296f5cce2d0b2047d15964c30a9b for registry.fits.cloud/cloud-public/images/gitlab-terraform:v0.24.0 with digest registry.fits.cloud/cloud-public/images/gitlab-terraform@sha256:4472f740720492d147c2ac61fbd02a185172b588f71feb02fcc4b6b89352855c ...[0;m
section_end:1642752364:prepare_executor
[0Ksection_start:1642752364:prepare_script
[0K[0K[36;1mPreparing environment[0;m[0;m
Running on runner-06b8e6b3-project-9200-concurrent-0 via 91b3433b6048...
section_end:1642752365:prepare_script
[0Ksection_start:1642752365:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m[0;m
[32;1mFetching changes with git depth set to 50...[0;m
Reinitialized existing Git repository in /builds/cloud-hub/microsoft/core-landing-zone-04/.git/
[32;1mChecking out 067f6404 as main...[0;m
Removing CoreLandingZone/.terraform.lock.hcl
Removing CoreLandingZone/.terraform/

[32;1mSkipping Git submodules setup[0;m
section_end:1642752366:get_sources
[0Ksection_start:1642752366:restore_cache
[0K[0K[36;1mRestoring cache[0;m[0;m
[32;1mChecking cache for CoreLandingZone...[0;m
No URL provided, cache will not be downloaded from shared cache server. Instead a local version of cache will be extracted.[0;m 
[32;1mSuccessfully extracted cache[0;m
section_end:1642752371:restore_cache
[0Ksection_start:1642752371:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m[0;m
[0KUsing docker image sha256:d3dd647faaf650ade5445c415db4715e0866296f5cce2d0b2047d15964c30a9b for registry.fits.cloud/cloud-public/images/gitlab-terraform:v0.24.0 with digest registry.fits.cloud/cloud-public/images/gitlab-terraform@sha256:4472f740720492d147c2ac61fbd02a185172b588f71feb02fcc4b6b89352855c ...[0;m
[32;1m$ cd ${TF_ROOT}[0;m
[32;1m$ gitlab-terraform plan -lock=false[0;m

[0m[1mInitializing the backend...[0m
[0m[32m
Successfully configured the backend "http"! Terraform will automatically
use this backend unless the backend configuration changes.[0m
2022/01/21 08:06:13 [DEBUG] GET https://git.f-i-ts.de/api/v4/projects/9200/terraform/state/Core_Landing_Zone_State

[0m[1mInitializing provider plugins...[0m
- Finding hashicorp/azurerm versions matching ">= 2.66.0"...
- Finding latest version of hashicorp/random...
- Finding latest version of hashicorp/template...
- Installing hashicorp/azurerm v2.93.0...
- Installed hashicorp/azurerm v2.93.0 (signed by HashiCorp)
- Installing hashicorp/random v3.1.0...
- Installed hashicorp/random v3.1.0 (signed by HashiCorp)
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (signed by HashiCorp)

Terraform has created a lock file [1m.terraform.lock.hcl[0m to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.[0m

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
2022/01/21 08:06:21 [DEBUG] GET https://git.f-i-ts.de/api/v4/projects/9200/terraform/state/Core_Landing_Zone_State
[0m[1mrandom_id.storage_account: Refreshing state... [id=qfhJPnM][0m
[0m[1mazurerm_resource_group.windowsvm_1: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vm-windows-002][0m
[0m[1mazurerm_resource_group.linuxvm_1: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vm-linux-002][0m
[0m[1mazurerm_route_table.test0234u: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vnet-spoke-002/providers/Microsoft.Network/routeTables/acceptanceSecurityGroup2][0m
[0m[1mazurerm_resource_group.storage_1: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-storage-account-002][0m
[0m[1mazurerm_resource_group.bastian: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-bastian-host-002][0m
[0m[1mazurerm_resource_group.corelandingzone: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vnet-spoke-002][0m
[0m[1mazurerm_security_center_auto_provisioning.example: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/providers/Microsoft.Security/autoProvisioningSettings/default][0m
[0m[1mazurerm_resource_group.monitoring: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-azr-mon-002][0m
[0m[1mazurerm_resource_group.windowsvm_2: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vm-windows-003][0m
[0m[1mazurerm_public_ip.bastian: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-bastian-host-002/providers/Microsoft.Network/publicIPAddresses/bastianpip][0m
[0m[1mazurerm_network_security_group.backend-nsg: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vnet-spoke-002/providers/Microsoft.Network/networkSecurityGroups/backend-nsg][0m
[0m[1mazurerm_network_security_group.applayer-nsg: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vnet-spoke-002/providers/Microsoft.Network/networkSecurityGroups/applayer-nsg][0m
[0m[1mazurerm_network_security_group.frontend-nsg: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vnet-spoke-002/providers/Microsoft.Network/networkSecurityGroups/frontend-nsg][0m
[0m[1mazurerm_storage_account.example: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-storage-account-002/providers/Microsoft.Storage/storageAccounts/fitsstoragea9f8493e73][0m
[0m[1mazurerm_virtual_network.spoke-vnet: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vnet-spoke-002/providers/Microsoft.Network/virtualNetworks/vnet-spoke-westeurope-001][0m
[0m[1mazurerm_network_interface.linuxvm_1: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vm-linux-002/providers/Microsoft.Network/networkInterfaces/vm-ub-lx-002_nic01][0m
[0m[1mazurerm_network_interface.windowsvm_1: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vm-windows-002/providers/Microsoft.Network/networkInterfaces/vm-win-iis-002_nic01][0m
[0m[1mazurerm_virtual_network_peering.spoke1-hub-peer[0]: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vnet-spoke-002/providers/Microsoft.Network/virtualNetworks/vnet-spoke-westeurope-001/virtualNetworkPeerings/spoke1-hub-peer][0m
[0m[1mazurerm_network_interface.windowsvm_2: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vm-windows-003/providers/Microsoft.Network/networkInterfaces/vm-win-iis-003_nic01][0m
[0m[1mazurerm_virtual_network_peering.hub-spoke1-peer[0]: Refreshing state... [id=/subscriptions/0869dede-9085-4a8a-8f4a-02cdc31e4717/resourceGroups/mk-04-connectivity-westeurope/providers/Microsoft.Network/virtualNetworks/mk-04-hub-westeurope/virtualNetworkPeerings/hub-spoke1-peer][0m
[0m[1mazurerm_subnet_route_table_association.UDR_DG: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vnet-spoke-002/providers/Microsoft.Network/virtualNetworks/vnet-spoke-westeurope-001/subnets/frontend][0m
[0m[1mazurerm_windows_virtual_machine.windowsvm_2: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vm-windows-003/providers/Microsoft.Compute/virtualMachines/vm-win-iis-003][0m
[0m[1mazurerm_linux_virtual_machine.linuxvm: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vm-linux-002/providers/Microsoft.Compute/virtualMachines/vm-ub-lx-002][0m
[0m[1mazurerm_windows_virtual_machine.windowsvm_1: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vm-windows-002/providers/Microsoft.Compute/virtualMachines/vm-win-iis-002][0m
[0m[1mazurerm_virtual_machine_extension.vm_extension_install_ii2: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vm-windows-003/providers/Microsoft.Compute/virtualMachines/vm-win-iis-003/extensions/vm_extension_install_ii2][0m
[0m[1mazurerm_bastion_host.bastian: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-bastian-host-002/providers/Microsoft.Network/bastionHosts/bastianbastion][0m
[0m[1mazurerm_virtual_machine_extension.vm_extension_install_iis: Refreshing state... [id=/subscriptions/44c58568-57ff-461a-8c8e-79c396be29c2/resourceGroups/rg-vm-windows-002/providers/Microsoft.Compute/virtualMachines/vm-win-iis-002/extensions/vm_extension_install_iis][0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with azurerm_bastion_host.bastian,
[31m│[0m [0m  on Bastian_Host.tf line 15, in resource "azurerm_bastion_host" "bastian":
[31m│[0m [0m  15: resource "azurerm_bastion_host" "bastian" [4m{[0m[0m
[31m│[0m [0m
[31m│[0m [0mThe plugin encountered an error, and failed to respond to the
[31m│[0m [0mplugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
[31m│[0m [0mdetails.
[31m╵[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with azurerm_virtual_machine_extension.vm_extension_install_iis,
[31m│[0m [0m  on WindowsServer.tf line 52, in resource "azurerm_virtual_machine_extension" "vm_extension_install_iis":
[31m│[0m [0m  52: resource "azurerm_virtual_machine_extension" "vm_extension_install_iis" [4m{[0m[0m
[31m│[0m [0m
[31m│[0m [0mThe plugin encountered an error, and failed to respond to the
[31m│[0m [0mplugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
[31m│[0m [0mdetails.
[31m╵[0m[0m

Stack trace from the terraform-provider-azurerm_v2.93.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45a1c7d]

goroutine 740 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.resourceBastionHostRead(0xc001755680, {0x559a880, 0xc001cb6e00})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/network/bastion_host_resource.go:255 +0x5dd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x5e760e3, {0x657f318, 0xc001a87c80}, 0x24, {0x559a880, 0xc001cb6e00})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00105b420, {0x657f318, 0xc001a87c80}, 0xc000cc1520, {0x559a880, 0xc001cb6e00})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000764528, {0x657f318, 0xc001a87c80}, 0xc001a87d00)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000127d80, {0x657f3c0, 0xc001705050}, 0xc0010a0a80)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x5adac20, 0xc000127d80}, {0x657f3c0, 0xc001705050}, 0xc0010a0a20, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001a1340, {0x65cdac8, 0xc0008f4000}, 0xc002238b40, 0xc0013bb800, 0xab3d910, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc0001a1340, {0x65cdac8, 0xc0008f4000}, 0xc002238b40, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x294

Error: The terraform-provider-azurerm_v2.93.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with azurerm_virtual_machine_extension.vm_extension_install_ii2,
[31m│[0m [0m  on WindowsServer_copy.tf line 51, in resource "azurerm_virtual_machine_extension" "vm_extension_install_ii2":
[31m│[0m [0m  51: resource "azurerm_virtual_machine_extension" "vm_extension_install_ii2" [4m{[0m[0m
[31m│[0m [0m
[31m│[0m [0mThe plugin encountered an error, and failed to respond to the
[31m│[0m [0mplugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
[31m│[0m [0mdetails.
[31m╵[0m[0m
section_end:1642752395:step_script
[0Ksection_start:1642752395:upload_artifacts_on_failure
[0K[0K[36;1mUploading artifacts for failed job[0;m[0;m
[32;1mUploading artifacts...[0;m
[0;33mWARNING: CoreLandingZone/plan.json: no matching files[0;m 
[31;1mERROR: No files to upload                         [0;m 
section_end:1642752396:upload_artifacts_on_failure
[0Ksection_start:1642752396:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1642752397:cleanup_file_variables
[0K[31;1mERROR: Job failed: exit code 1
[0;m
```

**Comment by kmoe** [comment]
Thanks for the report. As indicated in the logs you posted, this is more likely a bug in the azurerm provider:
```
Error: The terraform-provider-azurerm_v2.93.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

I am migrating this issue to that provider's repository. Please fill in the `Terraform Version` section with the Terraform and provider version, and provide a minimal reproduction config, in order that the provider maintainers might reproduce your issue.
