### ISSUE TITLE
Terraform azurerm plugin() crash

### ISSUE THREAD

**Issue by anujmittalaws** [hashicorp/terraform#30705]
### Terraform Version

```
$ terraform version
Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.98.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

```terraform
data "azurerm_client_config" "current" {
}

### STEP 3: Create and configure your Azure Synapse Workspace ###

# resource "azurerm_storage_account" "storage_account" {
#   name                     = var.synapse_storage_account_name
#   resource_group_name      = var.synapse_resource_group_name
#   location                 = var.synapse_workspace_location
#   account_tier             = "Standard"
#   account_replication_type = "LRS"
#   account_kind             = "StorageV2"
#   is_hns_enabled           = "true"
# }

# locals{

# [for list in var.storage_account_names : data_in_list]

#     # storage_account_name = {
#     #   for name, stg_acc_name in var.storage_account_names : name => stg_acc_name
#     #   if stg_acc_name.is_synapse
#     # }

#   #  for stg_acc in var.storage_account_names : lookup(stg_acc,"for_synapse",[]) => stg_acc

# }

# locals{
#   storage_accounts = var.storage_account_names
#   [for storage_account in local.storage_accounts : storage_account ]
# }

data "azurerm_storage_account" "storage_account" {
  for_each            = { for stg_acc in var.storage_account_names : stg_acc.name => stg_acc if stg_acc.is_synapse == true }
  name                = each.value.name
  resource_group_name = var.synapse_resource_group_name
}

resource "azurerm_storage_data_lake_gen2_filesystem" "adl_filesystem" {
  # count = length(var.synapse_workspace_filesystem_name)
  for_each           = data.azurerm_storage_account.storage_account
  name               = var.synapse_workspace_filesystem_name
  storage_account_id = each.value.id
  # storage_account_id = azurerm_storage_account.storage_account.id
  depends_on = [
    data.azurerm_storage_account.storage_account
  ]
}

# data "azuread_group" "ad-group-lookup" {
#   for_each     = lookup(element(var.synapse_workspace_otherfilesystem_name,key.index),"ace",[])
#   display_name = lookup(var.folder-ad-group, each.key)
# }

# data "azurerm_storage_account" "storage_account_otherfilesystem" {
#   for_each            = { for stg_acc in var.synapse_workspace_otherfilesystem_name : stg_acc.storage_account => stg_acc }
#   name                = each.value.storage_account
#   resource_group_name = var.synapse_resource_group_name
# }

resource "azurerm_storage_data_lake_gen2_filesystem" "adl_otherfilesystems" {
  count              = length(var.synapse_workspace_otherfilesystem_name)
  name               = lookup(element(var.synapse_workspace_otherfilesystem_name, count.index), "name", [])
  # storage_account_id = azurerm_storage_account.storage_account.id
  storage_account_id = lookup(element(var.synapse_workspace_otherfilesystem_name, count.index), "storage_account_id")
  # storage_account_id = module.storage.azurerm_storage_account.storage_account[lookup(element(var.synapse_workspace_otherfilesystem_name, count.index), "name", [])].id
  # storage_account_id = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/resourceGroups/${var.synapse_resource_group_name}/providers/Microsoft.Storage/storageAccounts/${var.synapse_storage_account_name}"
  dynamic "ace" {
    for_each = lookup(element(var.synapse_workspace_otherfilesystem_name, count.index), "ace", [])
    content {
      scope       = ace.value.scope
      type        = ace.value.type
      id          = ace.value.id
      permissions = ace.value.permissions
    }
  }

  # depends_on = [
  #   azurerm_storage_account.storage_account
  # ]

}

# resource "azurerm_storage_data_lake_gen2_filesystem" "adl_otherfilesystems" {
#   for_each = {for fs_name in var.synapse_workspace_otherfilesystem_name : fs_name.name => fs_name}
#   name               = each.value.name
#   storage_account_id = azurerm_storage_account.storage_account.id
#   depends_on = [
#     azurerm_storage_account.storage_account
#   ]

#   # dynamic "ace" {
#   #   for_each = lookup(,"ace",[])
#   #   scope =
#   #   type =
#   #   id =
#   #   permissions =
#   # }

# }

# resource "azurerm_storage_data_lake_gen2_filesystem" "adl_otherfilesystems" {
#   count = length(var.synapse_workspace_otherfilesystem_name)
#   name               = var.synapse_workspace_otherfilesystem_name[count.index]
#   storage_account_id = azurerm_storage_account.storage_account.id
#   depends_on = [
#     azurerm_storage_account.storage_account
#   ]

#   # dynamic "ace" {
#   #   scope =
#   #   type =
#   #   id =
#   #   permissions =
#   # }
# }


resource "azurerm_storage_data_lake_gen2_path" "adl_filesystem_folder" {
  count              = length(var.adl_filesystem_folder)
  path               = lookup(element(var.adl_filesystem_folder, count.index), "path", [])
  filesystem_name    = lookup(element(var.adl_filesystem_folder, count.index), "filesystem_name", [])
  storage_account_id = lookup(element(var.synapse_workspace_otherfilesystem_name, count.index), "storage_account_id")
  # storage_account_id = azurerm_storage_account.storage_account.id
  resource           = lookup(element(var.adl_filesystem_folder, count.index), "resource", [])
  dynamic "ace" {
    for_each = lookup(element(var.adl_filesystem_folder, count.index), "ace", [])
    content {
      scope       = ace.value.scope
      type        = ace.value.type
      id          = ace.value.id
      permissions = ace.value.permissions
    }
  }

  # depends_on = [
  #   resource.azurerm_storage_data_lake_gen2_filesystem.adl_filesystem,
  #   resource.azurerm_storage_data_lake_gen2_filesystem.adl_otherfilesystems

  # ]
}

resource "random_password" "password" {
  length           = 16
  special          = true
  override_special = "!$#%"
  min_special      = 1
  upper            = true
  min_upper        = 1
  lower            = true
  min_lower        = 1
  number           = true
  min_numeric      = 1

}

resource "azurerm_synapse_workspace" "synapse_workspace" {
  # for_each = azurerm_storage_data_lake_gen2_filesystem.adl_filesystem
  name                                 = var.synapse_workspace_name
  resource_group_name                  = var.synapse_resource_group_name
  managed_resource_group_name          = var.synapse_managed_resource_group_name
  location                             = var.synapse_workspace_location
  storage_data_lake_gen2_filesystem_id = azurerm_storage_data_lake_gen2_filesystem.adl_filesystem["${var.synapse_storage_account_name}"].id // hardcode
  sql_administrator_login              = "sqladmin"
  sql_administrator_login_password     = random_password.password.result
  managed_virtual_network_enabled      = true
  # linking_allowed_for_aad_tenant_ids   = var.allowed_tenants
  public_network_access_enabled = true  #needs to be turned off

  # aad_admin {
  #   login     = "AzureAD Admin"
  #   object_id = "${var.aad_principal[0]}"
  #   tenant_id = "${data.azurerm_client_config.current.tenant_id}"
  # }

  # identity{
  #   type = "SystemAssigned"
  # }

  tags = var.tags
}

resource "azurerm_synapse_firewall_rule" "synapse_firewall_rule" {
  # for_each = azurerm_synapse_workspace.synapse_workspace
  name                 = "AllowAll"
  synapse_workspace_id = azurerm_synapse_workspace.synapse_workspace.id
  start_ip_address     = "0.0.0.0"
  end_ip_address       = "255.255.255.255"

  depends_on = [
    resource.azurerm_synapse_workspace.synapse_workspace
  ]
}

resource "azurerm_synapse_sql_pool" "synapse_sql_pool" {
  #  for_each = azurerm_synapse_workspace.synapse_workspace
  name                 = var.synapse_sql_pool_name
  synapse_workspace_id = azurerm_synapse_workspace.synapse_workspace.id
  sku_name             = var.synapse_sql_sku_name
  create_mode          = "Default"
  depends_on = [
    azurerm_synapse_workspace.synapse_workspace
  ]
}

# Need to be uncommented once the AD groups are available
resource "azurerm_synapse_role_assignment" "synapse_role_assignment" {
  # count = length(var.aad_principal_roles)
  for_each = var.aad_principal_roles
  synapse_workspace_id = azurerm_synapse_workspace.synapse_workspace.id
  # role_name            = lookup({for item in var.aad_principal_roles : item.access=>item  if item.ad_group == each.value.name},"access")
  # principal_id         = "${var.aad_principal[index(var.aad_principal, each.value)+1]}"
  role_name = each.key
  principal_id = each.value.id
  # role_name = var.aad_principal_roles[*].access
  # principal_id = "${var.aad_principal_roles[*].id}"
  depends_on = [resource.azurerm_synapse_firewall_rule.synapse_firewall_rule]
}


# data "azuread_group" "ad_groups" {
#   for_each = { for item in var.aad_principal_roles : item.ad_group => item}
#   display_name     = each.value.ad_group
#   # security_enabled = true
# }

#  locals {
#    ad = flatten([
#      for ad_id in data.azuread_group.ad_groups :[
#        for k,v in var.aad_principal_roles :{
#          id = ad_id.id
#          role = 
#          access = 
#        }
#      ]
#    ])
#  }

# resource "azurerm_synapse_role_assignment" "synapse_role_assignment" {
#   # count = length(var.aad_principal_roles)
#   for_each = data.azuread_group.ad_groups
#   synapse_workspace_id = azurerm_synapse_workspace.synapse_workspace.id
#   role_name            = lookup({for item in var.aad_principal_roles : item.access=>item  if item.ad_group == each.value.name},"access")
#   # principal_id         = "${var.aad_principal[index(var.aad_principal, each.value)+1]}"
#   principal_id = each.value.id

#   depends_on = [resource.azurerm_synapse_firewall_rule.synapse_firewall_rule]
# }



# ####

# ### STEP 4: Grant the workspace MSI access to the default storage container ###


resource "azurerm_role_assignment" "assign_role_storage_blob_synapse_managed_identity" {
  # count = length(var.aad_principal)
  scope                = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/resourceGroups/${var.synapse_resource_group_name}/providers/Microsoft.Storage/storageAccounts/${var.synapse_storage_account_name}"
  role_definition_name = "Storage Blob Data Contributor"
  # principal_id         = "${var.aad_principal[count.index]}"
  principal_id = azurerm_synapse_workspace.synapse_workspace.identity[0]["principal_id"]
  depends_on = [
    resource.azurerm_synapse_workspace.synapse_workspace
  ]
}

# ###

# for_each            = { for stg_acc in var.storage_account_names : stg_acc.name => stg_acc if stg_acc.is_synapse == true }
#   name                = each.value.name
#   resource_group_name = var.synapse_resource_group_name

# ### STEP 5: Grant Synapse administrators the Azure Contributor role on the workspace ###

resource "azurerm_role_assignment" "assign_synapse_admin" {
  for_each = {for k,v in var.aad_principal_roles: k => v if k == "Synapse Administrator"}
  scope = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/resourceGroups/${var.synapse_resource_group_name}/providers/Microsoft.Synapse/workspaces/${var.synapse_workspace_name}"
  # role_definition_name = "Owner"
  role_definition_name = "Contributor"
  # principal_id         = "${var.aad_principal[count.index]}"
  # principal_id = var.aad_principal[0]
  principal_id = each.value.id
  depends_on = [
    resource.azurerm_synapse_workspace.synapse_workspace
  ]
}

# ####

### STEP 6: Assign SQL Active Directory Admin role ###
 resource "azurerm_synapse_workspace_aad_admin" "assign_synapse-aad_admin" {
   for_each = {for k,v in var.aad_principal_roles: k => v if k == "Synapse SQL Administrator"}
   synapse_workspace_id = azurerm_synapse_workspace.synapse_workspace.id
   login                = "SQL_AD_Admin"
   # object_id            = var.aad_principal[4]
   object_id = each.value.id
   tenant_id            = data.azurerm_client_config.current.tenant_id
   depends_on = [
     resource.azurerm_synapse_workspace.synapse_workspace
   ]
 }

# ####

resource "azurerm_role_assignment" "assign_role_storage_owner" {
  # count = length(var.aad_principal)
  for_each = {for k,v in var.aad_principal_roles: k => v if k == "Synapse Administrator"}
  scope                = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/resourceGroups/${var.synapse_resource_group_name}/providers/Microsoft.Storage/storageAccounts/${var.synapse_storage_account_name}"
  role_definition_name = "Owner"
  # principal_id         = "${var.aad_principal[count.index]}"
  principal_id = each.value.id
  # principal_id = var.aad_principal[0]
  depends_on = [
    resource.azurerm_storage_data_lake_gen2_filesystem.adl_filesystem
  ]
}






# # resource "azurerm_synapse_role_assignment" "synapse_role_assignment" {
# #   for_each = var.aad_principal_roles
# #   # for_each = {for i, b in var.aad_principal_roles : b => {index = i}}
# #   synapse_workspace_id = azurerm_synapse_workspace.synapse_workspace.id
# #   role_name            = "${each.value}"
# #   # principal_id         = "${var.aad_principal[index(var.aad_principal, each.value)+1]}"
# #   principal_id         = "${var.aad_principal[0]}"

# #   depends_on = [resource.azurerm_synapse_workspace.synapse_workspace]
# # }

# # resource "azurerm_synapse_role_assignment" "synapse_role_assignment1" {
# #   synapse_workspace_id = azurerm_synapse_workspace.synapse_workspace.id
# #   role_name            = "Synapse Administrator"
# #   principal_id         = "${var.aad_principal[0]}"

# #   depends_on = [resource.azurerm_synapse_workspace.synapse_workspace]
# # }

# # resource "azurerm_synapse_role_assignment" "synapse_role_assignment2" {
# #   synapse_workspace_id = azurerm_synapse_workspace.synapse_workspace.id
# #   role_name            = "Synapse Contributor"
# #   principal_id         = "${var.aad_principal[1]}"

# #   depends_on = [resource.azurerm_synapse_workspace.synapse_workspace]
# # }

# # resource "azurerm_synapse_role_assignment" "synapse_role_assignment3" {
# #   synapse_workspace_id = azurerm_synapse_workspace.synapse_workspace.id
# #   role_name            = "Synapse SQL Administrator"
# #   principal_id         = "${var.aad_principal[2]}"

# #   depends_on = [resource.azurerm_synapse_workspace.synapse_workspace]
# # }

# # resource "azurerm_synapse_role_assignment" "synapse_role_assignment" {
# #   synapse_workspace_id = azurerm_synapse_workspace.synapse_workspace.id
# #   role_name            = "Synapse SQL Administrator"
# #   principal_id         = "${var.aad_principal[3]}"

# #   depends_on = [azurerm_synapse_firewall_rule.example]
# # }




# ###STEP 2: Prepare your ADLS Gen2 storage account ###
resource "azurerm_role_assignment" "assign_role_storage_blob_admin" {
  # count = length(var.aad_principal)
  for_each = {for k,v in var.aad_principal_roles: k => v if k == "Synapse Administrator"}
  scope                = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/resourceGroups/${var.synapse_resource_group_name}/providers/Microsoft.Storage/storageAccounts/${var.synapse_storage_account_name}"
  role_definition_name = "Storage Blob Data Contributor"
  # principal_id         = "${var.aad_principal[count.index]}"
  principal_id = each.value.id
  depends_on = [
    resource.azurerm_storage_data_lake_gen2_filesystem.adl_filesystem
  ]
}

resource "azurerm_role_assignment" "assign_role_storage_blob_contributor" {
  # count = length(var.aad_principal)
  for_each = {for k,v in var.aad_principal_roles: k => v if k == "Synapse Contributor"}
  scope                = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/resourceGroups/${var.synapse_resource_group_name}/providers/Microsoft.Storage/storageAccounts/${var.synapse_storage_account_name}"
  role_definition_name = "Storage Blob Data Contributor"
  # principal_id         = "${var.aad_principal[count.index]}"
  principal_id = each.value.id
  depends_on = [
    resource.azurerm_storage_data_lake_gen2_filesystem.adl_filesystem
  ]
}

resource "azurerm_role_assignment" "assign_role_storage_blob_compute_operator" {
  # count = length(var.aad_principal)
  for_each = {for k,v in var.aad_principal_roles: k => v if k == "Synapse Compute Operator"}
  scope                = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/resourceGroups/${var.synapse_resource_group_name}/providers/Microsoft.Storage/storageAccounts/${var.synapse_storage_account_name}"
  role_definition_name = "Storage Blob Data Contributor"
  principal_id = each.value.id
  # principal_id         = "${var.aad_principal[count.index]}"
  # principal_id = var.aad_principal[2]
  depends_on = [
    resource.azurerm_storage_data_lake_gen2_filesystem.adl_filesystem
  ]
}

# ###

# count              = length(var.adl_filesystem_folder)
#   path               = lookup(element(var.adl_filesystem_folder, count.index), "path", [])
#   filesystem_name    = lookup(element(var.adl_filesystem_folder, count.index), "filesystem_name", [])

#### Private Endpoint###
resource "azurerm_synapse_managed_private_endpoint" "private_endpoint" {
  count              = length(var.synapse_private_endpoints)
  name                 = lookup(element(var.synapse_private_endpoints, count.index), "name", [])
  synapse_workspace_id = azurerm_synapse_workspace.synapse_workspace.id
  target_resource_id   = lookup(element(var.synapse_private_endpoints, count.index), "target_resource_id", [])
  subresource_name     = lookup(element(var.synapse_private_endpoints, count.index), "subresource_name", [])

  depends_on = [resource.azurerm_synapse_firewall_rule.synapse_firewall_rule]
}

# # resource "azurerm_synapse_managed_private_endpoint" "private_endpoint" {
# #   count                = length(var.private_endpoint)
# #   name                 = lookup(element(var.private_endpoint, count.index), "name", [])
# #   synapse_workspace_id = azurerm_synapse_workspace.synapse_workspace.id
# #   target_resource_id   = lookup(element(var.private_endpoint, count.index), "target_resource_id", []).id
# #   subresource_name     = lookup(element(var.private_endpoint, count.index), "subresource_name", [])

# #   depends_on = [resource.azurerm_synapse_firewall_rule.synapse_firewall_rule]
# # }



# # resource "azurerm_storage_data_lake_gen2_path" "adl_filesystem_folder" {
# #   count              = length(var.adl_filesystem_folder)
# #   path               = lookup(element(var.adl_filesystem_folder, count.index), "path", [])
# #   filesystem_name    = lookup(element(var.adl_filesystem_folder, count.index), "filesystem_name", [])
# #   storage_account_id = azurerm_storage_account.storage_account.id
# #   resource           = lookup(element(var.adl_filesystem_folder, count.index), "resource", [])
# #   dynamic "ace" {
# #     for_each = lookup(element(var.adl_filesystem_folder, count.index), "ace", [])
# #     content {
# #       scope       = ace.value.scope
# #       type        = ace.value.type
# #       id          = ace.value.id
# #       permissions = ace.value.permissions
# #     }
# #   }

# #   depends_on = [
# #     resource.azurerm_storage_data_lake_gen2_filesystem.adl_filesystem,
# #     resource.azurerm_storage_data_lake_gen2_filesystem.adl_otherfilesystems

# #   ]
# # }

```

### Debug Output

```
module.synapse.azurerm_synapse_workspace_aad_admin.assign_synapse-aad_admin["Synapse SQL Administrator"]: Refreshing state... [id=/subscriptions/671778bf-19a4-44d6-b64e-80defb9d0dc4/resourceGroups/rg-adh-infrastructure-dev-001/providers/Microsoft.Synapse/workspaces/synw-adh-dev-001/administrators/activeDirectory]
module.synapse.random_password.password: Refreshing state... [id=none]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The     
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.98.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x5dd1190]

goroutine 937 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/synapse.resourceSynapseWorkspaceAADAdminRead(0xc00105cc00, {0x62663c0, 0xc0013ca380})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/synapse/synapse_workspace_aad_admin_resource.go:120 +0x550
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x6b621fc, {0x7293898, 0xc000068f00}, 0x24, {0x62663c0, 0xc0013ca380})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000ee1dc0, {0x7293898, 0xc000068f00}, 0xc001870dd0, {0x62663c0, 0xc0013ca380})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000423a40, {0x7293898, 0xc000068f00}, 0xc000068f80)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0000baa00, {0x7293940, 0xc00156c300}, 0xc000156ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x67bb3a0, 0xc0000baa00}, {0x7293940, 0xc00156c300}, 0xc000156ae0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170        
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000243340, {0x72e4508, 0xc000b86000}, 0xc0013ce240, 0xc0010b2e70, 0xb9423d0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc000243340, {0x72e4508, 0xc000b86000}, 0xc0013ce240, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x294

Error: The terraform-provider-azurerm_v2.98.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.



```
### Expected Behavior

```
should be able to create the resources
```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
