### ISSUE TITLE
Terraform cloud crash with v1.1.7

### ISSUE THREAD

**Issue by prullanferragut** [hashicorp/terraform#30727]
ahoy! I am reporting this crash occurred in the Terraform cloud UI but cannot show you much more information - the next plan worked smoothly and do not have any extra traces.

### Terraform Version

```
Terraform v1.1.7
on linux_amd64
```

### Debug Output

```
Terraform v1.1.7
on linux_amd64
Initializing plugins and modules...
{"@level":"info","@message":"Terraform 1.1.7","@module":"terraform.ui","@timestamp":"2022-03-23T09:00:11.015725-07:00","terraform":"1.1.7","type":"version","ui":"1.0"}

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x154
panic({0x2250d80, 0x401aac0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/hashicorp/terraform/internal/cloud.(*Cloud).Operation(0xc0001beb00, {0x2b4fbf0, 0xc000130008}, 0xc000646240)
	/home/circleci/project/project/internal/cloud/backend.go:607 +0x4a
github.com/hashicorp/terraform/internal/command.(*Meta).RunOperation(0xc000112ea0, {0x7f14ec4ccf68, 0xc0001beb00}, 0xc000646240)
	/home/circleci/project/project/internal/command/meta.go:401 +0xde
github.com/hashicorp/terraform/internal/command.(*ApplyCommand).Run(0xc000112ea0, {0xc000100070, 0x0, 0x0})
	/home/circleci/project/project/internal/command/apply.go:121 +0x59b
github.com/mitchellh/cli.(*CLI).Run(0xc0007008c0)
	/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
main.realMain()
	/home/circleci/project/project/main.go:309 +0x1509
main.main()
	/home/circleci/project/project/main.go:58 +0x19
Operation failed: failed running terraform apply (exit 11)
```

**Comment by alisdair** [comment]
Thanks for reporting this! The stack trace makes it look like this is the same as #30646, which we as yet don't have a reproduction for. I'm closing this issue as duplicate.
