### ISSUE TITLE
Message: This is always indicative of a bug within the plugin

### ISSUE THREAD

**Issue by carmelBearrr** [hashicorp/terraform#30729]
### Terraform Version

```
1.0.11 and 1.1.7

AzureRM Provider 2.89.0 and 2.99.0
```

### Terraform Configuration Files

```terraform
variables:
 cosmos_serverless  = false
cosmos_auto_scale_max_throughput  = 4000
variable "indexing_policy" {
  type = object({
    indexing_mode     = string
    included_paths    = list(string)
    excluded_paths    = list(string)
    composite_indexes = list(list(object({ path = string, order = string })))
  })
  default = null
}

variable "unique_key_paths" {
  type        = list(string)
  description = "A list of paths to use for the unique key."
  default     = null
}

locals {
  offer_type              = "Standard"
  kind                    = "GlobalDocumentDB"
  consistency_level       = "BoundedStaleness"
  max_interval_in_seconds = 5
  max_staleness_prefix    = 100
  capabilities            = var.cosmos_serverless ? [{ name = "EnableServerless" }] : []  
  autoscale_settings      = var.cosmos_serverless ? [] : [{ max_throughput = var.cosmos_auto_scale_max_throughput }]
  indexing_policies       = var.indexing_policy == null ? [] : [var.indexing_policy]
  is_keys_null            = var.unique_key_paths == null
  is_keys_empty           = var.unique_key_paths == null ? true : length(var.unique_key_paths) <= 0
  add_unique_keys         = local.is_keys_null || local.is_keys_empty ? [] : [var.unique_key_paths]
  cosmos_name             = "cosmos_name"
}

resource "azurerm_cosmosdb_account" "cosmos_account" {
  name                            = local.cosmos_name
  location                        = "East US 2"
  resource_group_name             =  "resource_group_name"
  offer_type                      = local.offer_type
  kind                            = local.kind
  enable_multiple_write_locations = false
  key_vault_key_id                = data.azurerm_key_vault_key.module.versionless_id

  tags = {}

  consistency_policy {
    consistency_level       = local.consistency_level
    max_interval_in_seconds = local.max_interval_in_seconds
    max_staleness_prefix    = local.max_staleness_prefix
  }

  enable_automatic_failover = false

  geo_location {
    location          = "East US 2"
    failover_priority = 0
  }

  dynamic "capabilities" {
    for_each = local.capabilities

    content {
      name = capabilities.value.name
    }
  }

  dynamic "geo_location" {
    for_each = []

    content {
      prefix            = "${local.cosmos_name}-${geo_location.value.location}"
      location          = geo_location.value.location
      failover_priority = geo_location.value.failover_priority
    }
  }

  is_virtual_network_filter_enabled = true
  public_network_access_enabled     = true
  ip_range_filter                   = "ips including microsoft portal with commas separating"

  virtual_network_rule {
    id = "subnet_id"
  }

  lifecycle {
    ignore_changes = [
      tags,
    ]
    prevent_destroy = true
  }

  depends_on = [
    azurerm_key_vault.module
  ]
}

```

### Expected Behavior

``` Finished creating cosmos db account ```

### Actual Behavior

```
azurerm_cosmosdb_account.cosmos_account: Still creating... [11m0s elapsed]
azurerm_cosmosdb_account.cosmos_account: Still creating... [11m10s elapsed]
azurerm_cosmosdb_account.cosmos_account: Still creating... [11m20s elapsed]
azurerm_cosmosdb_account.cosmos_account: Still creating... [11m30s elapsed]
azurerm_cosmosdb_account.cosmos_account: Still creating... [11m40s elapsed]
╷
│ Error: Plugin did not respond
│ 
│   on cosmosPersistence.tf line 27, in resource "azurerm_cosmosdb_account" "cosmos_account":
│   27: resource "azurerm_cosmosdb_account" "cosmos_account" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.99.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x4f9d151]

goroutine 244 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/cosmos.resourceCosmosDbAccountApiUpsert.func1()
	/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/cosmos/cosmosdb_account_resource.go:1204 +0x1b1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1()
       /src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource/state.go:110 +0x21f
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
	/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource/state.go:83 +0x1dd

Error: The terraform-provider-azurerm_v2.99.0_x5.exe plugin crashed!
```

### Additional Context

``` Previously deleted the azure cosmos db account to recreate as autoscale ```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
