### ISSUE TITLE
Terraform crash when trying to plan for configuration (v0.14.11)

### ISSUE THREAD

**Issue by guidodl** [hashicorp/terraform#30842]
### Terraform Version

```
$ terraform0_14.exe --version
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/google v4.17.0

Your version of Terraform is out of date! The latest version
is 1.1.8. You can update by downloading from https://www.terraform.io/downloads.html
...
```
Hi everybody,

I am trying to plan for a terraform configuration which has already been applied by a colleague of my team. 
I encountered the following error:

```
module.external-glb.google_compute_health_check.lb_http_hc_443: Refreshing state... [id=projects/infoblu-access-prod/global/healthChecks/prod-external-armor-lb-http-hc-443]
module.external-glb.google_compute_global_address.lb_external_addr: Refreshing state... [id=projects/infoblu-access-prod/global/addresses/prod-external-armor-lb-ext-addr]
module.external-glb.panic: Error reading level state: strconv.ParseInt: parsing "8168926262889361640": value out of range
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: goroutine 120 [running]:
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x152afb30, 0x154920c8, 0x1, 0x1, 0x1491db08, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource_data.go:553 +0x2ba
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x152afb30, 0x152afb30)
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource_data.go:351 +0x288
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x14b837a0, 0x2c336dc, 0x14d2f8d0, 0x2403700, 0x1548c960, 0x2c336dc, 0x14d2f8d0, 0x2403700)
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:263 +0x191
2022-04-12T10:29:34.844+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14db29c0, 0x2c3323c, 0x14d30c40, 0x14d30ca0, 0x27baa12, 0x12, 0x0)
2022-04-12T10:29:34.844+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:550 +0x1ea
2022-04-12T10:29:34.844+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x14894280, 0x2c3329c, 0x14d30c40, 0x1488f950, 0x0, 0x0, 0x0)      
2022-04-12T10:29:34.844+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x288
2022-04-12T10:29:34.844+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x2770ba0, 0x14894280, 0x2c3329c, 0x15062870, 0x1488f920, 0x0, 0x2c3329c, 0x15062870, 0x15482000, 0x2f0)
2022-04-12T10:29:34.844+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x199
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0x1491c120, 0x2c47708, 0x1491c240, 0x148e85a0, 0x14c98858, 0x3986908, 0x0, 0x0, 0x0)
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   google.golang.org/grpc@v1.44.0/server.go:1282 +0x4ea
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: google.golang.org/grpc.(*Server).handleStream(0x1491c120, 0x2c47708, 0x1491c240, 0x148e85a0, 0x0)
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   google.golang.org/grpc@v1.44.0/server.go:1616 +0xa71
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14a0e140, 0x1491c120, 0x2c47708, 0x1491c240, 0x148e85a0)
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   google.golang.org/grpc@v1.44.0/server.go:921 +0x92
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   google.golang.org/grpc@v1.44.0/server.go:919 +0x1b0
2022-04-12T10:29:34.848+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_url_map.lb_http_url_map": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_network.network": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_network.network": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_network.network": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_image.ntt-eap": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_image.ntt-eap": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_image.ntt-eap": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_image.ntt-eap (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_image.ntt-eap (expand)": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_subnetwork.network": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_subnetwork.network": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_subnetwork.network": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_80": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_80": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_global_address.lb_external_addr": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_url_map.lb_http_url_map": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_url_map.lb_http_url_map": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_443": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_url_map.lb_http_url_map (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_url_map.lb_http_url_map (expand)": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_security_policy.policy[0]": visit complete
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.google_compute_target_http_proxy.lb_http_target_proxy (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_security_policy.policy": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_security_policy.policy": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_network.network (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_subnetwork.network (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_subnetwork.network (expand)": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_project.project": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_project.project": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_project.project": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_default_service_account.default": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_project.project (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_default_service_account.default": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_default_service_account.default": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_default_service_account.default (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_default_service_account.default (expand)": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_project.project (expand)": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_global_address.lb_external_addr": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_global_address.lb_external_addr": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_global_address.lb_external_addr (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_global_address.lb_external_addr (expand)": visit complete
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.google_compute_global_forwarding_rule.lb_http_fw_rule (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_443": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_443": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_443 (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_443 (expand)": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_security_policy.policy (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_security_policy.policy (expand)": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_network.network (expand)": visit complete
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-proxy-armor.google_compute_instance_template.instance_template (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-proxy-armor.google_compute_region_instance_group_manager.default (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-proxy-armor.output.migSelfLink (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.var.igs (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_80": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_80 (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_80 (expand)": visit complete
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.google_compute_backend_service.lb_be_svc_80 (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-proxy-armor (close)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.google_compute_backend_service.lb_be_svc_443 (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.google_compute_url_map.lb_url_map (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.google_compute_target_https_proxy.lb_https_target_proxy (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.google_compute_global_forwarding_rule.lb_https_fw_rule (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/google\"] (close)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb (close)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "root" errored, so skipping
2022/04/12 10:29:34 [INFO] backend/local: plan operation completed
2022/04/12 10:29:34 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2022/04/12 10:29:34 [TRACE] statemgr.Filesystem: unlocked by closing terraform.tfstate
2022-04-12T10:29:34.865+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/google/4.17.0/windows_386/terraform-provider-google_v4.17.0_x5.exe pid=11024 error="exit status 2"
2022-04-12T10:29:34.865+0200 [DEBUG] plugin: plugin exited

google_compute_health_check.lb_http_hc_80: Refreshing state... [id=projects/infoblu-access-prod/global/healthChecks/prod-external-armor-lb-http-hc-80]

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!


module.external-glb.google_compute_url_map.lb_http_url_map: Refreshing state... [id=projects/infoblu-access-prod/global/urlMaps/prod-external-armor-lb-http-url-map]
Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing

```

I attach also the crash.log generated.

[crash.log](https://github.com/hashicorp/terraform/files/8471232/crash.log)
Thanks,
Guido

**Comment by apparentlymart** [comment]
Hi @guidodl! Sorry for this crash, and thank you for reporting it.

In this case it seems to have been the Google Cloud Platform provider that crashed, rather than Terraform itself, and so I would suggest opening this issue in [the provider's repository](https://github.com/hashicorp/terraform-provider-google) instead.

Unfortunately this older version of Terraform CLI you are using tends to incorrectly detect provider crashes as ots own crashes and thus suggest to open them in this repository, but the code that crashed here is in the external plugin instead and so Terraform was incorrect to suggest opening an issue here. I'm sorry for the misdirection!

Since there isn't anything we could change in this repository to avoid the crash (and newer versions of Terraform don't incorrectly classify provider crashes as Terraform Core bugs), I'm going to close this. Thanks again!

**Comment by melinath** [comment]
@apparentlymart hey, here from the google provider team - just want to confirm that you think this is actually a provider bug?

It looks like the important part of the error is:

```
module.external-glb.panic: Error reading level state: strconv.ParseInt: parsing "8168926262889361640": value out of range
```

It looks like this is probably caused by using a 64-bit terraform (or provider?) binary on a 32-bit system - see https://github.com/hashicorp/terraform-plugin-sdk/issues/469

Can you confirm?

**Comment by apparentlymart** [comment]
Hi @melinath!

My response here was based on the fact that the panic seems to have originated in the `terraform-provider-google_v4.17.0_x5.exe` process rather than the main Terraform Core process. I think you are right that it's the SDK library embedded in the provider that _actually_ raised this panic, and so I think it's reasonable to treat upgrading to a newer version of the SDK which no longer has this bug and then releasing a new provider version as a valid solution. If there isn't yet a new SDK version which addresses this crash then I'd suggest reporting it upstream in the SDK repository.

I'm classifying this as a bug to be fixed because the expected contract is for providers to indicate invalid user input by returning an error, not by crashing altogether. For example, the SDK working on the provider's behalf could potentially return a real error saying that the value must be within the range of the target type.

However, whether that behavior would be acceptable will depend on the situation. It appears that this problem _might_ be happening due to data in the remote system or prior state rather than data in the configuration, in which case returning a validation error may not be appropriate; a user should typically not be blocked from applying a change because a _remote system_ is in an invalid state, because the user may be attempting to apply the change in order to get the system back into a suitable state.

I suggest discussing this with the SDK team to see whether it can be fixed in the SDK alone or if it would also require some changes to the design of this resource type to e.g. use a string instead of an architecture-specific integer type to store this value, so that it would be compatible for both 64-bit and 32-bit builds of your provider.
