### ISSUE TITLE
during plan: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jbg** [hashicorp/terraform#30894]
### Terraform Version
```
Terraform v1.1.8
on darwin_arm64
+ provider registry.terraform.io/aliyun/alicloud v1.164.0
+ provider registry.terraform.io/chilicat/pkcs12 v0.0.7
+ provider registry.terraform.io/cyrilgdn/postgresql v1.15.0
+ provider registry.terraform.io/ekristen/pgp v0.2.4
+ provider registry.terraform.io/exoscale/exoscale v0.34.0
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/grafana/grafana v1.21.1
+ provider registry.terraform.io/hashicorp/aws v4.10.0
+ provider registry.terraform.io/hashicorp/google v4.18.0
+ provider registry.terraform.io/hashicorp/google-beta v4.17.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.10.0
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/tls v3.3.0
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.35.1
+ provider registry.terraform.io/integrations/github v4.23.0
+ provider registry.terraform.io/ojford/wireguard v0.2.1+1
+ provider registry.terraform.io/vancluever/acme v2.8.0
```

### Terraform Configuration Files
Our configuration is non-public and over 50k LOC, and the crash output does not provide any indication of what triggers the error. If we can narrow that down, I am happy to post the relevant part.

### Crash
The following crash happens about 20% of the time for us when running `terraform plan` on an M1 Macbook. Notably, it has never happened to us when running Terraform in CI (`linux_arm64`) as we normally do; it's only when we need to run locally (`darwin_arm64`) for some reason or other that it happens.

After the crash, the state is left locked and after a `force-unlock` we are usually able to successfully plan immediately afterward.

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 47694 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x88
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x20
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        github.com/hashicorp/terraform/internal/logging/panic.go:55 +0x1a0
panic({0x1025effa0, 0x103e10a70})
        runtime/panic.go:1038 +0x21c
github.com/hashicorp/terraform/internal/addrs.Module.String({0x0, 0x1, 0x1})
        github.com/hashicorp/terraform/internal/addrs/module.go:37 +0x58
github.com/hashicorp/terraform/internal/addrs.ConfigResource.String({{}, {0x0, 0x1, 0x1}, {{}, 0x44, {0x14005f8b110, 0x15}, {0x14006359ad0, 0x8}}})
        github.com/hashicorp/terraform/internal/addrs/resource.go:380 +0x78
github.com/hashicorp/terraform/internal/states.(*ResourceInstanceObject).Encode.func1(0x0, 0x91)
        github.com/hashicorp/terraform/internal/states/instance_object.go:118 +0x7c
sort.doPivot_func({0x1402338d4b8, 0x1401ac58a50}, 0x0, 0x159)
        sort/zfuncversion.go:89 +0x248
sort.quickSort_func({0x1402338d4b8, 0x1401ac58a50}, 0x0, 0x159, 0x12)
        sort/zfuncversion.go:143 +0x80
sort.Slice({0x1024a28c0, 0x14036b181b0}, 0x1402338d4b8)
        sort/slice.go:20 +0xdc
github.com/hashicorp/terraform/internal/states.(*ResourceInstanceObject).Encode(0x14005f264e0, {{0x1029ebcb8, 0x1403e48a2b0}}, 0x2)
        github.com/hashicorp/terraform/internal/states/instance_object.go:118 +0x134
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).writeResourceInstanceStateImpl(0x1403fc3dc00, {0x102a56c40, 0x1400aa4ee00}, {0x0, 0x0}, 0x14005f264e0, 0x1)
        github.com/hashicorp/terraform/internal/terraform/node_resource_abstract_instance.go:368 +0x6c8
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).writeResourceInstanceState(...)
        github.com/hashicorp/terraform/internal/terraform/node_resource_abstract_instance.go:278
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0x1402c371080, {0x102a56c40, 0x1400aa4ee00})
        github.com/hashicorp/terraform/internal/terraform/node_resource_plan_instance.go:222 +0xb08
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x1402c371080, {0x102a56c40, 0x1400aa4ee00}, 0x2)
        github.com/hashicorp/terraform/internal/terraform/node_resource_plan_instance.go:54 +0x94
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x14001b6ac40, {0x102a56c40, 0x1400aa4ee00}, {0x12e4bb028, 0x1402c371080})
        github.com/hashicorp/terraform/internal/terraform/graph_walk_context.go:133 +0x9c
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x10291a1a0, 0x1402c371080})
        github.com/hashicorp/terraform/internal/terraform/graph.go:74 +0x244
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x1400a619920, {0x10291a1a0, 0x1402c371080}, 0x1402d811b00)
        github.com/hashicorp/terraform/internal/dag/walk.go:381 +0x31c
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
        github.com/hashicorp/terraform/internal/dag/walk.go:304 +0xe0c
```

### Additional Context
We often run with `-refresh=false`. I think the crash happens just as much either way though.

**Comment by jbardin** [comment]
Hi @jbg, thanks for filing the issue!

I'm not able to come up with any hypothesis here other than a data race, but even that isn't leading to any possible sources. What we somehow have here is the `String()` method being called on a corrupted `addrs.Module` (with the underlying type of `[]string`) with no backing array. We don't have any unsafe code in Terraform which could generate that structure, so a data race is the most likely culprit.

Would it be possible for you to build a Terraform binary with the race detector enabled to see if you can trigger this?
The build process should be easy if you have Go installed, from the root of the terraform repo you can run `go build -race` to get a terraform binary instrumented to detect data races. If you can detect a race using the `main` branch it would be better, since that is where current development is happening. If that doesn't produce any results, using the `v1.1` branch is where your version was released from, but may contain errors already fixed in `main`. 

Thanks!

**Comment by jbg** [comment]
Thanks for the analysis, I'll try to reproduce it with the race detector enabled!
