### ISSUE TITLE
TERRAFORM CRASH

### ISSUE THREAD

**Issue by YaminiDevi90** [hashicorp/terraform#30933]
>terraform init
Initializing modules...
Downloading s3::https://s3-us-east-1.amazonaws.com/ for s3...

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: index out of range [2] with length 2
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x154
panic({0x245f900, 0xc00066cac8})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/hashicorp/go-getter.(*S3Getter).parseUrl(0x30, 0xc00010ac60)
        /home/circleci/go/pkg/mod/github.com/hashicorp/go-getter@v1.5.9/get_s3.go:243 +0xa25
github.com/hashicorp/go-getter.(*S3Getter).Get(0xc0001ac378, {0xc00066ca98, 0x15}, 0x8)
        /home/circleci/go/pkg/mod/github.com/hashicorp/go-getter@v1.5.9/get_s3.go:69 +0x85
github.com/hashicorp/go-getter.(*Client).Get(0xc00097ea50)
        /home/circleci/go/pkg/mod/github.com/hashicorp/go-getter@v1.5.9/client.go:299 +0xf07
github.com/hashicorp/terraform/internal/getmodules.reusingGetter.getWithGoGetter(0xc00011ac60, {0x2b894b8, 0xc00081fd40}, {0xc00066ca98, 0x15}, {0xc0009cf050, 0x27})
        /home/circleci/project/project/internal/getmodules/getter.go:150 +0x4bb
github.com/hashicorp/terraform/internal/getmodules.(*PackageFetcher).FetchPackage(...)
        /home/circleci/project/project/internal/getmodules/installer.go:43
github.com/hashicorp/terraform/internal/initwd.(*ModuleInstaller).installGoGetterModule(0x2, {0x2b894b8, 0xc00081fd40}, 0xc0002ff570, {0xc00064ec2a, 0x2}, {0xc00066ca98, 0x15}, 0xc00071ed38, {0x2b5ccb0, ...}, ...)
        /home/circleci/project/project/internal/initwd/module_install.go:555 +0x305
github.com/hashicorp/terraform/internal/initwd.(*ModuleInstaller).installDescendentModules.func1(0xc0002ff570)
        /home/circleci/project/project/internal/initwd/module_install.go:220 +0xb50
github.com/hashicorp/terraform/internal/earlyconfig.ModuleWalkerFunc.LoadModule(0xc0009cf050, 0xc000999230)
        /home/circleci/project/project/internal/earlyconfig/config_build.go:155 +0x1f
github.com/hashicorp/terraform/internal/earlyconfig.buildChildModules(0xc0002ff500, {0x2b3fe80, 0xc0003a7040})
        /home/circleci/project/project/internal/earlyconfig/config_build.go:80 +0x755
github.com/hashicorp/terraform/internal/earlyconfig.BuildConfig(0xc00010f900, {0x2b3fe80, 0xc0003a7040})
        /home/circleci/project/project/internal/earlyconfig/config_build.go:22 +0x79
github.com/hashicorp/terraform/internal/initwd.(*ModuleInstaller).installDescendentModules(0xc00047fc20, {0x2b894b8, 0xc00081fd40}, 0x31d234, {0x25eae2b, 0x1}, 0xc00011abd0, 0x0, {0x2b5ccb0, 0xc000999050}, ...)
        /home/circleci/project/project/internal/initwd/module_install.go:120 +0x2b9
github.com/hashicorp/terraform/internal/initwd.(*ModuleInstaller).InstallModules(0xc00047fc20, {0x2b894b8, 0xc00081fd40}, {0x25eae2b, 0x1}, 0x80, {0x2b5ccb0, 0xc000999050})
        /home/circleci/project/project/internal/initwd/module_install.go:99 +0x36e
github.com/hashicorp/terraform/internal/command.(*Meta).installModules(0xc0005856c0, {0xc0009ceab0, 0x41258a0}, 0x38, {0x2b5ccb0, 0xc000999050})
        /home/circleci/project/project/internal/command/meta_config.go:188 +0x1de
github.com/hashicorp/terraform/internal/command.(*InitCommand).getModules(0xc0005856c0, {0xc0009ceab0, 0x1e}, 0x26187ee, 0x0)
        /home/circleci/project/project/internal/command/init.go:361 +0x145
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc0005856c0, {0xc000184230, 0x0, 0x0})
        /home/circleci/project/project/internal/command/init.go:192 +0xca8
github.com/mitchellh/cli.(*CLI).Run(0xc0008412c0)
        /home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
main.realMain()
        /home/circleci/project/project/main.go:309 +0x1509
main.main()
        /home/circleci/project/project/main.go:58 +0x19

**Comment by apparentlymart** [comment]
Hi @YaminiDevi90!

Since we didn't hear from you again after my previous question, I'm going to close this issue. Unless we can reproduce the issue on our own development systems, it isn't possible for us to prove that we've addressed the issue with a fix.

If you are able to provider more information as I requested in my previous comment then please leave a comment here and we can reopen the issue. Our issue locking bot will lock the issue after 30 days but until then you'll still be able to leave a comment and we will reopen the issue to prevent it from becoming locked. Thanks!
