### ISSUE TITLE
Terraform Crash: runtime error: invalid memory address or nil pointer dereferencegoroutine 13606 [running]

### ISSUE THREAD

**Issue by alexsanderp** [hashicorp/terraform#30950]
Same problem reported in the issue https://github.com/hashicorp/terraform/issues/30162 

Using version: 1.1.9

In version 1.1.8 this doesn`t happen...
Problem removing a module that used for_each...

```

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereferencegoroutine 13606 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:44 +0xb5
panic({0x221d240, 0x3ed5b10})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/instances.(*expanderModule).onlyResourceInstances(0x4de2e7, {{}, 0x4d, {0xc0008c2fb0, 0xf}, {0xc0008c2fc0, 0x4}}, {0xc00533e000, 0x380, 0x4})
        /home/circleci/project/project/internal/instances/expander.go:392 +0x95
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x7f8eb036d750, {0xc000b9f2e0, 0x0, 0xa8b}, {{}, 0x4d, {0xc0008c2fb0, 0xf}, {0xc0008c2fc0, 0x4}}, ...)
        /home/circleci/project/project/internal/instances/expander.go:387 +0x2e5
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc004295d28, {0xc000b9f2e0, 0x1, 0x1}, {{}, 0x4d, {0xc0008c2fb0, 0xf}, {0xc0008c2fc0, 0x4}}, ...)
        /home/circleci/project/project/internal/instances/expander.go:385 +0x293
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc001f8f3e0, {0xc000b9f2c0, 0x2, 0x2}, {{}, 0x4d, {0xc0008c2fb0, 0xf}, {0xc0008c2fc0, 0x4}}, ...)
        /home/circleci/project/project/internal/instances/expander.go:385 +0x293
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0xc0028833c0, {{}, {0xc000b9f2c0, 0x2, 0x2}, {{}, 0x4d, {0xc0008c2fb0, 0xf}, {0xc0008c2fc0, ...}}})
        /home/circleci/project/project/internal/instances/expander.go:157 +0x16f
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0xc003d39e30, {0x2aecc00, 0xc006d02540})
        /home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:204 +0x23b
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc003d39e30, {0x2aecc00, 0xc006d02540})
        /home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:140 +0x58c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x0, {0x2aecc00, 0xc006d02540}, 0x80)
        /home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0026830a0, {0x2aecc00, 0xc006d02540}, {0x7f8eb0775740, 0xc003d39e30})
        /home/circleci/project/project/internal/terraform/graph_walk_context.go:133 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2553ec0, 0xc003d39e30})
        /home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc001d06960, {0x2553ec0, 0xc003d39e30}, 0xc0068e59c0)
        /home/circleci/project/project/internal/dag/walk.go:381 +0x2f1
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
        /home/circleci/project/project/internal/dag/walk.go:304 +0xf85
```

**Comment by alisdair** [comment]
Hi @alexsanderp, thanks for reporting this. Can you provide a sample configuration with reproduction steps? The issue you linked to has already been reproduced, fixed, and confirmed as part of #30110 (PR in #30151), so we need more information to be able to investigate this further.

**Comment by jbardin** [comment]
Hi @alexsanderp,

The stack trace shown does not align with the source either v1.1.8 or v1.1.9. That output can only come from v1.1.0, I would first verify that you are executing the version you think you have installed with `terraform version`. If you can reproduce this with v1.1.9, please attach the stack trace from that version of Terraform.

Thanks!

**Comment by alisdair** [comment]
Closing as stale due to lack of reproduction.
