### ISSUE TITLE
An empty string in schema.TypeList of type string unexpectedly nil on resource creation

### ISSUE THREAD

**Issue by marcinwyszynski** [hashicorp/terraform#31025]
I created a [minimal repro](https://github.com/marcinwyszynski/terraform-provider-stringlistrepro/commit/6d31551f4a3ea1d1a6be09ec978b7a621fba68c1) on top of the provider scaffold.

The test fails as expected with:

```
panic: interface conversion: interface {} is nil, not string

goroutine 254 [running]:
github.com/hashicorp/terraform-provider-scaffolding/internal/provider.resourceScaffoldingCreate({0x1a3b168, 0xc0000b4d20}, 0x1808080?, {0xc000166ed0?, 0x5f7265706c65682e?})
	/Users/marcinw/Code/spacelift/experiments/terraform-provider-stringlistrepro/internal/provider/resource_scaffolding.go:42 +0x154
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0001140e0, {0x1a3b1a0, 0xc0001667b0}, 0xd?, {0x17b06e0, 0x1f79360})
	/usr/local/gocode/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.15.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001140e0, {0x1a3b1a0, 0xc0001667b0}, 0xc0002a1790, 0xc0004a9000, {0x17b06e0, 0x1f79360})
	/usr/local/gocode/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.15.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00028c990, {0x1a3b0f8?, 0xc00013fe80?}, 0xc0006fa0f0)
	/usr/local/gocode/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.15.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0005bcfa0, {0x1a3b1a0?, 0xc000166030?}, 0xc0003217a0)
	/usr/local/gocode/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x18c7ce0?, 0xc0005bcfa0}, {0x1a3b1a0, 0xc000166030}, 0xc00070dc20, 0x0)
	/usr/local/gocode/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000316540, {0x1a3df20, 0xc0002d1ba0}, 0xc0002bf440, 0xc000792f90, 0x1f3b0e0, 0x0)
	/usr/local/gocode/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000316540, {0x1a3df20, 0xc0002d1ba0}, 0xc0002bf440, 0x0)
	/usr/local/gocode/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/usr/local/gocode/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/usr/local/gocode/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x28a
FAIL	github.com/hashicorp/terraform-provider-scaffolding/internal/provider	0.821s
FAIL
```

This does not happen on update, provided that the list for the existing resource is not empty, as per [this repro](https://github.com/marcinwyszynski/terraform-provider-stringlistrepro/commit/a2769e16de75cc129f0180673269721711391c00#diff-9d419d265c786b68c127655f2050da71ecfa65a4df3968dc7d580c60bee3c013R33-R50).

**Comment by apparentlymart** [comment]
Hi @marcinwyszynski! Sorry for this surprising behavior.

It seems like what you are describing here happened on the plugin side of the provider plugin protocol, and so is the responsibility of [the plugin SDK](https://github.com/hashicorp/terraform-plugin-sdk) rather than Terraform Core.

For that reason, I'd suggest opening an issue there so that the SDK maintainers can investigate it and see whether a nil value is expected in that context, and if not hopefully determine why it is there and fix it.

Thanks!
