### ISSUE TITLE
Call to function "flatten" failed: panic in function implementation: value is marked, so must be unmarked first

### ISSUE THREAD

**Issue by stevo-f3** [hashicorp/terraform#31148]
### Terraform Version

```
Terraform v0.14.11
```

### Terraform Configuration Files

[```terraform
...
```](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v17.24.0/workers.tf#L213-L221)

### Debug Output
<!--
Full debug output can be obtained by running Terraform with the environment variable `TF_LOG=trace`. Please create a GitHub Gist containing the debug output. Please do _not_ paste the debug output in the issue, since debug output is long.

Debug output may contain sensitive information. Please review it before posting publicly, and if you are concerned feel free to encrypt the files using the HashiCorp security public key.
-->

### Expected Behavior
<!--
What should have happened?
-->

### Actual Behavior
<!--
What actually happened?
-->

```
Call to function "flatten" failed: panic in function implementation: value is
marked, so must be unmarked first
goroutine 97630 [running]:
runtime/debug.Stack(0xc013ae4228, 0x23d80e0, 0x2c42790)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/zclconf/go-cty/cty/function.errorForPanic(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.0/cty/function/error.go:44
github.com/zclconf/go-cty/cty/function.Function.ReturnTypeForValues.func1(0xc013ae4810,
0xc013ae4820)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.0/cty/function/function.go:217
+0x7f
panic(0x23d80e0, 0x2c42790)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.0/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.ElementIterator(0x2cebc80, 0xc00bf9ca40,
0x25b4900, 0xc00d715ca0, 0x2cebb01, 0xc0001b6368)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.0/cty/value_ops.go:1111 +0x4f
github.com/zclconf/go-cty/cty/function/stdlib.flattener(0x2cebc80,
0xc00bf9ca40, 0x25b4900, 0xc00d715ca0, 0xc01980a201, 0x2cebc80, 0xc00bf9ca40,
0x25b4900)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.0/cty/function/stdlib/collection.go:516
+0xfb
github.com/zclconf/go-cty/cty/function/stdlib.flattener(0x2cebc80,
0xc00d715cc0, 0x238cda0, 0xc00d715ce0, 0x1, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.0/cty/function/stdlib/collection.go:523
+0x20a
github.com/zclconf/go-cty/cty/function/stdlib.glob..func22(0xc00d7158c0, 0x1,
0x1, 0x3e017e0, 0xc013ae4660, 0x0, 0x0)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.0/cty/function/stdlib/collection.go:480
+0xa9
github.com/zclconf/go-cty/cty/function.Function.ReturnTypeForValues(0xc000199a70,
0xc00d7158c0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.0/cty/function/function.go:221
+0x454
github.com/zclconf/go-cty/cty/function.Function.Call(0xc000199a70,
0xc00d7158c0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.0/cty/function/function.go:228
+0xb5
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc00372c5a0,
0xc00c3a3c60, 0x0, 0xf, 0xc01f11c8b0, 0xc01d5bfd01, 0x10, 0x283c520,
0xc01a988f01)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.9.1/hclsyntax/expression.go:442
+0x10c5
github.com/hashicorp/hcl/v2/hcldec.(*AttrSpec).decode(0xc009aabdd0,
0xc0051b4c60, 0x0, 0x0, 0x0, 0xc00c3a3c60, 0x2cebb80, 0xc0141b2040, 0x238cda0,
0xc00d7158a0, ...)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.9.1/hcldec/spec.go:205 +0x2ac
github.com/hashicorp/hcl/v2/hcldec.ObjectSpec.decode(0xc009aabce0,
0xc0051b4c60, 0x0, 0x0, 0x0, 0xc00c3a3c60, 0xc00bf53f70, 0x7f5b9b4fc820, 0x20,
0x20, ...)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.9.1/hcldec/spec.go:79 +0x237
github.com/hashicorp/hcl/v2/hcldec.decode(0x2ceaa80, 0xc00cb09ca0, 0x0, 0x0,
0x0, 0xc00c3a3c60, 0x2ceb8c0, 0xc009aabce0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.9.1/hcldec/decode.go:21 +0x11b
github.com/hashicorp/hcl/v2/hcldec.Decode(...)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.9.1/hcldec/public.go:15
github.com/hashicorp/terraform/lang.(*Scope).EvalBlock(0xc01bbca050,
0x2cea300, 0xc01bf7a9c0, 0xc00bfc34a0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/lang/eval.go:67 +0x2ac
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc01749fba0,
0x2cea300, 0xc01bf7a9c0, 0xc00bfc34a0, 0x0, 0x0, 0x2cebb00, 0xc0001b6368,
0x28743c0, 0xc015dfbf80, ...)
	/home/circleci/project/project/terraform/eval_context_builtin.go:280 +0x1ad
github.com/hashicorp/terraform/terraform.(*EvalDiff).Eval(0xc013ae7a98,
0x2d278e0, 0xc01749fba0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/eval_diff.go:155 +0x27c
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc01e813da0,
0x2d278e0, 0xc01749fba0, 0x438cc5, 0x29cfed0)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:207
+0x58d
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).Execute(0xc01e813da0,
0x2d278e0, 0xc01749fba0, 0xc01aca2002, 0x250b240, 0x2825d00)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:39
+0xd2
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc01b88c1a0,
0x2d278e0, 0xc01749fba0, 0x7f5b999d76f8, 0xc01e813da0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbc
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2825d00,
0xc01e813da0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:59 +0x962
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0033b3740,
0x2825d00, 0xc01e813da0, 0xc013812c80)
	/home/circleci/project/project/dag/walk.go:387 +0x375
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:309 +0x1246
.
```

### Steps to Reproduce
<!--
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`
-->

### Additional Context
<!--
Are there anything atypical about your situation that we should know? For example: is Terraform running in a wrapper script or in a CI system? Are you passing any unusual command line options or environment variables to opt-in to non-default behavior?
-->

### References
<!--
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

- #6017

-->

**Comment by kmoe** [comment]
Thanks for the bug report. This looks likely to be a problem in the underlying go-cty library, which has had several bug fixes in this area since Terraform v0.14.11. Are you able to try with a later Terraform version? Even [upgrading to Terraform v0.15](https://www.terraform.io/language/upgrade-guides/0-15) may well fix this if you are not able to upgrade to Terraform v1.0+.

**Comment by stevo-f3** [comment]
@kmoe thanks for your reply. I'm in the process of upgrading from 0.13 to latest, and have to do it one by one minor version, so next one is 0.14 and this bug is preventing me from applying plan at least once with 0.14 before upgrading to 0.15

**Comment by stevo-f3** [comment]
Upgrade from 0.13 to 0.15 actually worked, and fixed the issue. It's fine by me for this issue to be closed.

**Comment by kmoe** [comment]
That's great to hear - thanks.
