### ISSUE TITLE
terraform crash on apply

### ISSUE THREAD

**Issue by alebricio** [hashicorp/terraform#31248]
👋🏼 If anyone can help with pointers on which additional info you'd need - will be happy to provide, but for now just the stack trace.

### Terraform Version

```
terraform version
Terraform v1.1.0
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.18.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.5.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/tls v3.4.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```

### Debug Output
```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereferencegoroutine 12502 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/distiller/project/project/internal/logging/panic.go:44 +0xb5
panic({0x2e20fa0, 0x4ae4070})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x0, {0xc0013896c0, 0x1, 0x2}, {{}, 0x4d, {0xc000d86fc0, 0xc}, {0xc000d86fb7, 0x5}}, ...)
	/Users/distiller/project/project/internal/instances/expander.go:376 +0xc3
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc00197de18, {0xc0013896a0, 0x2, 0x3}, {{}, 0x4d, {0xc000d86fc0, 0xc}, {0xc000d86fb7, 0x5}}, ...)
	/Users/distiller/project/project/internal/instances/expander.go:385 +0x293
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc00197d3b0, {0xc001389680, 0x3, 0x4}, {{}, 0x4d, {0xc000d86fc0, 0xc}, {0xc000d86fb7, 0x5}}, ...)
	/Users/distiller/project/project/internal/instances/expander.go:385 +0x293
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0xc002201ec0, {{}, {0xc001389680, 0x3, 0x4}, {{}, 0x4d, {0xc000d86fc0, 0xc}, {0xc000d86fb7, ...}}})
	/Users/distiller/project/project/internal/instances/expander.go:157 +0x16f
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0xc004c32300, {0x36f1e20, 0xc006969960})
	/Users/distiller/project/project/internal/terraform/node_resource_plan_orphan.go:182 +0x445
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc004c32300, {0x36f1e20, 0xc006969960})
	/Users/distiller/project/project/internal/terraform/node_resource_plan_orphan.go:140 +0x58c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x0, {0x36f1e20, 0xc006969960}, 0x20)
	/Users/distiller/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc001546380, {0x36f1e20, 0xc006969960}, {0xcbc7660, 0xc004c32300})
	/Users/distiller/project/project/internal/terraform/graph_walk_context.go:133 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x3158c00, 0xc004c32300})
	/Users/distiller/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc0010876e0, {0x3158c00, 0xc004c32300}, 0xc00637b1c0)
	/Users/distiller/project/project/internal/dag/walk.go:381 +0x2f1
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/Users/distiller/project/project/internal/dag/walk.go:304 +0xf85
ERRO[0031] 1 error occurred:
	* exit status 11
```

**Comment by jbardin** [comment]
Hi @alebricio,

Thanks for reporting the crash. There have been many patch releases since v1.1.0, can you confirm if this still happens with a current release of Terraform?

Thanks!

**Comment by alebricio** [comment]
Hey @jbardin, updating to `1.1.9` did the trick. Thank you for looking into this! 😀
