### ISSUE TITLE
terraform crashed on a plan

### ISSUE THREAD

**Issue by favoretti** [hashicorp/terraform#31243]
Terraform crashed on a plan, so far not sure I understand why. 

```
terraform version
Terraform v1.2.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azuread v2.23.0
+ provider registry.terraform.io/hashicorp/azurerm v3.10.0
+ provider registry.terraform.io/hashicorp/helm v2.5.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/random v3.3.1
+ provider registry.terraform.io/microsoft/azuredevops v0.2.1
+ provider registry.terraform.io/winebarrel/mysql v1.10.6
```

If anyone can help with pointers on which additional info you'd need - will be happy to provide, but for now just the stack trace.

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 12965 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x68
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x20
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/distiller/project/project/internal/logging/panic.go:55 +0x174
panic({0x10294db80, 0x10402c2e0})
	/usr/local/go/src/runtime/panic.go:838 +0x204
github.com/hashicorp/terraform/internal/addrs.Module.String({0x0?, 0x1, 0x14005a0b038?})
	/Users/distiller/project/project/internal/addrs/module.go:37 +0x5c
github.com/hashicorp/terraform/internal/addrs.ConfigResource.String({{}, {0x0, 0x1, 0x1}, {{}, 0x44, {0x140005df350, 0x25}, {0x14000753cb8, 0x4}}})
	/Users/distiller/project/project/internal/addrs/resource.go:389 +0x74
github.com/hashicorp/terraform/internal/terraform.depsEqual.func1.1(0x14001b44a00?, 0x27)
	/Users/distiller/project/project/internal/terraform/node_resource_plan_instance.go:396 +0xd4
sort.insertionSort_func({0x1400625d9c0?, 0x14008e4e300?}, 0x22, 0x2b)
	/usr/local/go/src/sort/zfuncversion.go:12 +0xc4
sort.quickSort_func({0x1400625d9c0?, 0x14008e4e300?}, 0xa?, 0x2b?, 0x102baf460?)
	/usr/local/go/src/sort/zfuncversion.go:158 +0x158
sort.quickSort_func({0x1400625d9c0?, 0x14008e4e300?}, 0x0?, 0x0?, 0x14005a0b2f8?)
	/usr/local/go/src/sort/zfuncversion.go:148 +0xc4
sort.Slice({0x1027f5f60, 0x140005cdae8}, 0x2b?)
	/usr/local/go/src/sort/slice.go:20 +0xac
github.com/hashicorp/terraform/internal/terraform.depsEqual({0x14004c4f400?, 0x2b, 0x2b}, {0x14000a26400?, 0x2b, 0x2b})
	/Users/distiller/project/project/internal/terraform/node_resource_plan_instance.go:401 +0xc8
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0x1400701c400, {0x102d241d8, 0x140016a82a0})
	/Users/distiller/project/project/internal/terraform/node_resource_plan_instance.go:263 +0xc90
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x0?, {0x102d241d8?, 0x140016a82a0?}, 0xe0?)
	/Users/distiller/project/project/internal/terraform/node_resource_plan_instance.go:60 +0x7c
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x1400067a3c0, {0x102d241d8, 0x140016a82a0}, {0x10bb4e4e0, 0x1400701c400})
	/Users/distiller/project/project/internal/terraform/graph_walk_context.go:135 +0xac
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x102c9c060, 0x1400701c400})
	/Users/distiller/project/project/internal/terraform/graph.go:74 +0x20c
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x140031bbe00, {0x102c9c060, 0x1400701c400}, 0x1400701c800)
	/Users/distiller/project/project/internal/dag/walk.go:381 +0x2ec
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/Users/distiller/project/project/internal/dag/walk.go:304 +0xc00
```

**Comment by favoretti** [comment]
@jbardin that's a very good question. From what I see last successful apply was on 1.2.1.
