### ISSUE TITLE
Crash due to invalid provider address

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#31572]
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```
must contain only letters, digits, and dashes, and may not use leading or trailing dashes
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x2468940, 0xc00050d0c0})
        /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/hashicorp/terraform/internal/addrs.MustParseProviderPart({0xc0004ab150?, 0x0?})
        /home/circleci/project/project/internal/addrs/provider.go:449 +0x4c
github.com/hashicorp/terraform/internal/addrs.NewDefaultProvider(...)
        /home/circleci/project/project/internal/addrs/provider.go:122
github.com/hashicorp/terraform/internal/addrs.ImpliedProviderForUnqualifiedType({0xc0004ab150?, 0xc0004ab150?})
        /home/circleci/project/project/internal/addrs/provider.go:114 +0x11b
github.com/hashicorp/terraform/internal/configs.validateProviderConfigs.func1(0xc000630090?)
        /home/circleci/project/project/internal/configs/provider_validation.go:161 +0x145
github.com/hashicorp/terraform/internal/configs.validateProviderConfigs(0x0, 0xc000184b60, 0x0)
        /home/circleci/project/project/internal/configs/provider_validation.go:180 +0x14bd
github.com/hashicorp/terraform/internal/configs.BuildConfig(0xc0000a0790, {0x2eae200, 0xc00050d020})
        /home/circleci/project/project/internal/configs/config_build.go:34 +0xf0
github.com/hashicorp/terraform/internal/configs/configload.(*Loader).LoadConfig(0xc0005f8550, {0x29034ee?, 0x23?})
        /home/circleci/project/project/internal/configs/configload/loader_load.go:33 +0xfd
github.com/hashicorp/terraform/internal/command.(*Meta).loadConfig(0x0?, {0xc00087a270?, 0x0?})
        /home/circleci/project/project/internal/command/meta_config.go:47 +0x98
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc0001044e0, {0xc0000623f0, 0x0, 0x0})
        /home/circleci/project/project/internal/command/init.go:207 +0x139d
github.com/mitchellh/cli.(*CLI).Run(0xc0000a52c0)
        /home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.4/cli.go:262 +0x5f8
main.realMain()
        /home/circleci/project/project/main.go:312 +0x15d4
main.main()
        /home/circleci/project/project/main.go:58 +0x19
```

Terraform v1.2.6
on windows_amd64

i created a file  with .tf and run CMD  terraform plan 

after that i delete the file. again run the cmd it was through this error.

_Originally posted by @tthakre in https://github.com/hashicorp/terraform/issues/31557#issuecomment-1205188376_

**Comment by radeksimko** [comment]
This appears to be related to https://github.com/hashicorp/terraform/pull/28338 so I'm going to look into it.

**Comment by radeksimko** [comment]
To clarify this is actually _not_ directly related to #28338 since that PR was merged only recently and didn't make it to `1.2.6`
https://github.com/hashicorp/terraform/commit/7feef1c4aa5b408989e945fb83bfa65b631081f7

**Comment by radeksimko** [comment]
@tthakre Would you mind sharing the config used? Specifically we'd be interested in any `resource "..." "..." {` and `provider "..." {` lines.

Also I'm assuming that you get this crash when running `terraform init`, correct?

**Comment by radeksimko** [comment]
As far as I can tell this is triggered by configuration which is able to pass through this point 

https://github.com/hashicorp/terraform/blob/54f3e20305c0a08f3e5e8e655024d6fbec1259b5/internal/configs/configload/loader_load.go#L22-L33

but all combinations I have tried would be caught as the diagnostics received are treated as errors:

```hcl
provider "-test" {
}
```

```hcl
resource "-test_foo" "name" {
}
```

In other words I was not able to reproduce it.

**Comment by radeksimko** [comment]
Upon a closer look at the above code I can see that we treat submodules differently than the root module, so I was able to reproduce it using the following:

```hcl
module "test" {
  source = "./sub"
}
```
**`./sub/main.tf`**
```
resource "-test_test" "name" {
}
```
```sh
$ terraform init # in root
```
```
Initializing modules...

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

must contain only letters, digits, and dashes, and may not use leading or trailing dashes
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.18.5/libexec/src/runtime/debug/stack.go:24 +0x68
runtime/debug.PrintStack()
	/opt/homebrew/Cellar/go/1.18.5/libexec/src/runtime/debug/stack.go:16 +0x20
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform/internal/logging/panic.go:55 +0x174
panic({0x1064e4860, 0x140003c2cb0})
	/opt/homebrew/Cellar/go/1.18.5/libexec/src/runtime/panic.go:844 +0x258
github.com/hashicorp/terraform/internal/addrs.MustParseProviderPart({0x14000616590?, 0x5?})
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform/internal/addrs/provider.go:188 +0x58
github.com/hashicorp/terraform/internal/addrs.NewDefaultProvider(...)
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform/internal/addrs/provider.go:86
github.com/hashicorp/terraform/internal/addrs.ImpliedProviderForUnqualifiedType({0x14000616590?, 0x14000616590?})
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform/internal/addrs/provider.go:78 +0xe0
github.com/hashicorp/terraform/internal/configs.validateProviderConfigs.func1(0x14000616159?)
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform/internal/configs/provider_validation.go:161 +0xf0
github.com/hashicorp/terraform/internal/configs.validateProviderConfigs(0x140005dc780, 0x140005fc460, 0x0)
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform/internal/configs/provider_validation.go:180 +0xed8
github.com/hashicorp/terraform/internal/configs.validateProviderConfigs(0x0, 0x140005fc380, 0x0)
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform/internal/configs/provider_validation.go:50 +0x414
github.com/hashicorp/terraform/internal/configs.BuildConfig(0x140009de0b0, {0x10696e000, 0x140003c2bf0})
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform/internal/configs/config_build.go:34 +0x10c
github.com/hashicorp/terraform/internal/configs/configload.(*Loader).LoadConfig(0x140000603c0, {0x105da1c65?, 0x16?})
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform/internal/configs/configload/loader_load.go:33 +0x10c
github.com/hashicorp/terraform/internal/command.(*Meta).loadConfig(0x0?, {0x14000056024?, 0x0?})
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform/internal/command/meta_config.go:47 +0x94
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0x14000603a00, {0x140001b8010, 0x0, 0x0})
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform/internal/command/init.go:207 +0xf90
github.com/mitchellh/cli.(*CLI).Run(0x140009c4140)
	/Users/radeksimko/gopath/pkg/mod/github.com/mitchellh/cli@v1.1.4/cli.go:262 +0x4cc
main.realMain()
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform/main.go:315 +0x12dc
main.main()
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform/main.go:58 +0x20
```

---

It is still reproducible in the latest `main` revision (e57e721c8e48048053c62a110d912fe4afcc7f62).
