### ISSUE TITLE
Terraform crash

### ISSUE THREAD

**Issue by goshipra** [hashicorp/terraform#31656]
Terraform v1.1.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.15.1

Replication of issue:
1. I created 4 AWS Ec2 instances, s3 bucket and dynamodb table to create a backend to store tf.state file in s3.
2. It was continuously giving me plugin not available error but after pushing command 2-3 times it works. 
3. I pushed 3-4 times terraform destroy command and it crashed terraform and gave me below logs:

Plugin did not respond: The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).GetProviderSchema call. The plugin logs may contain more details.
goroutine 79 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	github.com/hashicorp/terraform/internal/logging/panic.go:55 +0x153
panic({0x314e540, 0xc002986270})
	runtime/panic.go:838 +0x207
github.com/hashicorp/terraform/internal/plugin.(*GRPCProvider).getSchema(0xc002e66c80)
	github.com/hashicorp/terraform/internal/plugin/grpc_provider.go:83 +0x2e5
github.com/hashicorp/terraform/internal/plugin.(*GRPCProvider).getResourceSchema(0xc0000b79e0?, {0xc0003af050, 0xd})
	github.com/hashicorp/terraform/internal/plugin/grpc_provider.go:92 +0x3b
github.com/hashicorp/terraform/internal/plugin.(*GRPCProvider).UpgradeResourceState(0xc002e66c80, {{0xc0003af050, 0xd}, 0x0, {0xc0000e7500, 0x371, 0x371}, 0x0})
	github.com/hashicorp/terraform/internal/plugin/grpc_provider.go:255 +0xcb
github.com/hashicorp/terraform/internal/terraform.upgradeResourceState({{}, {0x0, 0x0, 0x0}, {{}, {{}, 0x4d, {0xc0003af050, 0xd}, {0xc0003af060, ...}}, ...}}, ...)
	github.com/hashicorp/terraform/internal/terraform/upgrade_resource_state.go:87 +0x44e
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResource).readResourceInstanceState(0xc002ca4a80, {0x381e9c8, 0xc002070380}, {{}, {0x0, 0x0, 0x0}, {{}, {{}, 0x4d, ...}, ...}})
	github.com/hashicorp/terraform/internal/terraform/node_resource_abstract.go:372 +0x3b1
github.com/hashicorp/terraform/internal/terraform.(*NodePlanDestroyableResourceInstance).Execute(0xc002104ba0, {0x381e9c8, 0xc002070380}, 0x0?)
	github.com/hashicorp/terraform/internal/terraform/node_resource_plan_destroy.go:48 +0x9e
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc00039f260, {0x381e9c8, 0xc002070380}, {0x2fd55e58, 0xc002104ba0})
	github.com/hashicorp/terraform/internal/terraform/graph_walk_context.go:133 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x3218a20, 0xc002104ba0})
	github.com/hashicorp/terraform/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc002932360, {0x3218a20, 0xc002104ba0}, 0xc002e1b3c0)
	github.com/hashicorp/terraform/internal/dag/walk.go:381 +0x2f1
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	github.com/hashicorp/terraform/internal/dag/walk.go:304 +0xf45

**Comment by jbardin** [comment]
Duplicate of #30655
