### ISSUE TITLE
TF 1.3.2: crash with: inconsistent map element types 

### ISSUE THREAD

**Issue by stuart12** [hashicorp/terraform#31962]
### Terraform Version

```shell
Terraform v1.3.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.28.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Terraform Configuration Files

```
variable "s3" {
  type = map(object({
    name_package_environment_prefix = bool
    name                            = string
    sse_algorithm                   = string
    lifecycle_rule = optional(list(object({
      id      = string
      enabled = bool
      abort_incomplete_multipart_upload_days = optional(number)
      tags                                   = map(string)
      expiration = optional(object({
        days                         = number
        expired_object_delete_marker = bool
      }))
      transition = optional(list(object({
        days          = number
        storage_class = string
      })))
    })), [])
  }))
```

### Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

inconsistent map element types (cty.Object(map[string]cty.Type{"lifecycle_rule":cty.List(cty.ObjectWithOptionalAttrs(map[string]cty.Type{"abort_incomplete_multipart_upload_days":cty.Number, "enabled":cty.Bool, "expiration":cty.Object(map[string]cty.Type{"days":cty.Number, "expired_object_delete_marker":cty.Bool}), "id":cty.String, "tags":cty.Map(cty.String), "transition":cty.List(cty.Object(map[string]cty.Type{"days":cty.Number, "storage_class":cty.String}))}, []string{"abort_incomplete_multipart_upload_days", "expiration", "transition"})), "name":cty.String, "name_package_environment_prefix":cty.Bool, "sse_algorithm":cty.String}) then cty.Object(map[string]cty.Type{"lifecycle_rule":cty.List(cty.Object(map[string]cty.Type{"abort_incomplete_multipart_upload_days":cty.Number, "enabled":cty.Bool, "expiration":cty.Object(map[string]cty.Type{"days":cty.Number, "expired_object_delete_marker":cty.Bool}), "id":cty.String, "tags":cty.Map(cty.String), "transition":cty.List(cty.Object(map[string]cty.Type{"days":cty.Number, "storage_class":cty.String}))})), "name":cty.String, "name_package_environment_prefix":cty.Bool, "sse_algorithm":cty.String}))
goroutine 5071 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x21e0160, 0xc0030a9340})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/zclconf/go-cty/cty.MapVal(0xc003b0ac80)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.11.0/cty/value_init.go:221 +0x47f
github.com/zclconf/go-cty/cty.transform({0x0?, 0x0, 0x0}, {{{0x2b66868?, 0xc00164af30?}}, {0x2218580?, 0xc001966270?}}, {0x2b4dc40, 0xc0029e2db8})
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.11.0/cty/walk.go:204 +0xc3e
github.com/zclconf/go-cty/cty.TransformWithTransformer(...)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.11.0/cty/walk.go:130
github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults).Apply(0xc00148b140?, {{{0x2b66868?, 0xc00164af30?}}, {0x2218580?, 0xc001966270?}})
        /home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.14.1/ext/typeexpr/defaults.go:38 +0xa7
github.com/hashicorp/terraform/internal/terraform.prepareFinalInputVariableValue({{0xc001806140, 0x1, 0x1}, {{}, {0xc00069954c, 0x2}}}, 0xc00380da58, 0xc000acab60)
        /home/circleci/project/project/internal/terraform/eval_variable.go:98 +0xacd
github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).evalModuleVariable(0xc001616f00?, {0x2b7cd18?, 0xc0012dc540?}, 0x5d?)
        /home/circleci/project/project/internal/terraform/node_module_variable.go:239 +0x545
github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).Execute(0xc001616f00, {0x2b7cd18, 0xc0012dc540}, 0x2)
        /home/circleci/project/project/internal/terraform/node_module_variable.go:155 +0x172
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0012c6ff0, {0x2b7cd18, 0xc0012dc540}, {0x7f894883e960, 0xc001616f00})
        /home/circleci/project/project/internal/terraform/graph_walk_context.go:136 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x23aeac0, 0xc001616f00})
        /home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc001616f60, {0x23aeac0, 0xc001616f00}, 0xc004b20240)
        /home/circleci/project/project/internal/dag/walk.go:381 +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
        /home/circleci/project/project/internal/dag/walk.go:304 +0xf65
```

### Expected Behavior

`terraform -chdir=/home/s.pook/git/xxx-dsp-kubernetes/cluster plan -var 'dns={private_zone_name="private.uxbridge.xxx.org",public_zone_name="uxbridge.xxx.org"}' -var s3_kubeconfig_key=dsp-development-k8s-config-uxbridge -var s3_kubeconfig_bucket=k8s-state-store-xxx-development-clusters -var environment=uxbridge -var-file=/home/s.pook/git/xxx-dsp-kubernetes/cluster/development/development.tfvars -compact-warnings` should not crash

### Actual Behavior

Terraform crashes when I add the `[]` argument to `optional` in the second last line of the extract from my terraform configuration given above. If I remove the `, []`, TF 1.3.2 does not crash.

### Steps to Reproduce

`terraform -chdir=/home/s.pook/git/xxx-dsp-kubernetes/cluster plan -var 'dns={private_zone_name="private.uxbridge.xxx.org",public_zone_name="uxbridge.xxx.org"}' -var s3_kubeconfig_key=dsp-development-k8s-config-uxbridge -var s3_kubeconfig_bucket=k8s-state-store-xxx-development-clusters -var environment=uxbridge -var-file=/home/s.pook/git/xxx-dsp-kubernetes/cluster/development/development.tfvars -compact-warnings`

### Additional Context

I'm porting pre-1.3 code that used [module_variable_optional_attrs](https://www.terraform.io/language/upgrade-guides#concluding-the-optional-attributes-experiment) to 1.3. Perhaps the code that is causing terraform 1.3.2 to crash is illegal. I had the same crash with terraform 1.3.1. If I replace the `[]` with `{}`, I get the error message: `This default value is not compatible with the attribute's type constraint: list of object required.` I presume that `{}` is what I should use as the default value but please correct me if I am wrong. I will provide more information if you ask.

### References

I saw https://github.com/hashicorp/terraform/issues/31844 but the fix https://github.com/hashicorp/terraform/pull/31855 targeted 1.3.1 so I should have this fix in TF 1.3.2.

**Comment by stuart12** [comment]
hi! I am sorry but I no longer know how to reproduce this bug. My changes to other parts of the code mean that terraform no longer crashes.

**Comment by jbardin** [comment]
Thanks @stuart12. There may be a patch in an upcoming release which may address the issue. If not we can wait for a new issue to be filed.

Thanks
