### ISSUE TITLE
"checkable object status report for unexpected checkable object" for output value when running `terraform console`

### ISSUE THREAD

**Issue by mg-8** [hashicorp/terraform#31994]
### Terraform Version

```shell
Terraform v1.3.2
on windows_amd64
+ provider registry.terraform.io/azure/azapi v1.0.0       
+ provider registry.terraform.io/hashicorp/azuread v2.26.1
+ provider registry.terraform.io/hashicorp/azurerm v3.26.0
+ provider registry.terraform.io/hashicorp/http v3.0.1    
+ provider registry.terraform.io/hashicorp/local v2.2.3   
+ provider registry.terraform.io/hashicorp/null v3.1.1    
+ provider registry.terraform.io/hashicorp/random v3.4.3  
+ provider registry.terraform.io/hashicorp/time v0.8.0
+ provider registry.terraform.io/microsoft/azuredevops v0.2.2
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

checkable object status report for unexpected checkable object module.naming.output.management_group
goroutine 237 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x2521420, 0xc000c66c20})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/checks.(*State).reportCheckResult(0xc0007602d0, {0x2f5e350, 0xc001af9e90}, 0x8b8ae0?, 0x0, 0x50)
        /home/circleci/project/project/internal/checks/state_report.go:103 +0x346
github.com/hashicorp/terraform/internal/checks.(*State).ReportCheckResult(0x2a0fc03?, {0x2f5e350?, 0xc001af9e90?}, 0xc001933920?, 0x1?, 0x0?)
        /home/circleci/project/project/internal/checks/state_report.go:68 +0xd0
github.com/hashicorp/terraform/internal/terraform.evalCheckRules(0xc00180a628?, {0xc00014a930, 0x1, 0x8a841f?}, {0x2f70498, 0xc0007c4540}, {0x2f5e350, 0xc001af9e90}, {{{{0x0, 0x0}}, ...}, ...}, ...)
        /home/circleci/project/project/internal/terraform/eval_conditions.go:58 +0x417
github.com/hashicorp/terraform/internal/terraform.(*NodeApplyableOutput).Execute(0xc00129e740, {0x2f70498, 0xc0007c4540}, 0x0?)
        /home/circleci/project/project/internal/terraform/node_output.go:327 +0x265
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc000faaf00, {0x2f70498, 0xc0007c4540}, {0x1c87b77c2e0, 0xc00129e740})
        /home/circleci/project/project/internal/terraform/graph_walk_context.go:136 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2819500, 0xc00129e740})
        /home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc0007aa540, {0x2819500, 0xc00129e740}, 0xc00129e7c0)
        /home/circleci/project/project/internal/dag/walk.go:381 +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
        /home/circleci/project/project/internal/dag/walk.go:304 +0xf65
```

### Expected Behavior

Should not have crashed

### Actual Behavior

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

checkable object status report for unexpected checkable object module.naming.output.management_group
goroutine 237 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x2521420, 0xc000c66c20})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/checks.(*State).reportCheckResult(0xc0007602d0, {0x2f5e350, 0xc001af9e90}, 0x8b8ae0?, 0x0, 0x50)
        /home/circleci/project/project/internal/checks/state_report.go:103 +0x346
github.com/hashicorp/terraform/internal/checks.(*State).ReportCheckResult(0x2a0fc03?, {0x2f5e350?, 0xc001af9e90?}, 0xc001933920?, 0x1?, 0x0?)
        /home/circleci/project/project/internal/checks/state_report.go:68 +0xd0
github.com/hashicorp/terraform/internal/terraform.evalCheckRules(0xc00180a628?, {0xc00014a930, 0x1, 0x8a841f?}, {0x2f70498, 0xc0007c4540}, {0x2f5e350, 0xc001af9e90}, {{{{0x0, 0x0}}, ...}, ...}, ...)
        /home/circleci/project/project/internal/terraform/eval_conditions.go:58 +0x417
github.com/hashicorp/terraform/internal/terraform.(*NodeApplyableOutput).Execute(0xc00129e740, {0x2f70498, 0xc0007c4540}, 0x0?)
        /home/circleci/project/project/internal/terraform/node_output.go:327 +0x265
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc000faaf00, {0x2f70498, 0xc0007c4540}, {0x1c87b77c2e0, 0xc00129e740})
        /home/circleci/project/project/internal/terraform/graph_walk_context.go:136 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2819500, 0xc00129e740})
        /home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc0007aa540, {0x2819500, 0xc00129e740}, 0xc00129e7c0)
        /home/circleci/project/project/internal/dag/walk.go:381 +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
        /home/circleci/project/project/internal/dag/walk.go:304 +0xf65
```

### Steps to Reproduce

terraform console

**Comment by apparentlymart** [comment]
Hi @mg-8! Thanks for reporting this.

Unfortunately it seems like you didn't fill out the "Terraform Configuration Files" section, and so there isn't sufficient information here for us to reproduce it just by running `terraform console` as you suggested. Can you share at least some subset of your configuration that is sufficient to make this crash occur? Thanks!

**Comment by mg-8** [comment]
> Hi @mg-8! Thanks for reporting this.
> 
> Unfortunately it seems like you didn't fill out the "Terraform Configuration Files" section, and so there isn't sufficient information here for us to reproduce it just by running `terraform console` as you suggested. Can you share at least some subset of your configuration that is sufficient to make this crash occur? Thanks!

Apologies for missing the configuration file...please see below; 

...terraform config...

### root module - main.tf
module "naming" {
  source = "../"

  application           = "app"
  application_sub_types = ["test"]
  environment           = "non"
  region                = "syd"
  service               = "any"
 }

### child module - main.tf
locals {
    provider = "xxx"
}

locals {
  prefix_with_sub_type = length(var.application_sub_types) > 0 ? {
    for s in var.application_sub_types :
    s => format(
      "%s%s%s%s%s%s%s",
      local.provider,
      format("-%s", var.region),
      format("-%s", var.environment),
      format("-%s", var.service),
      format("-%s", var.application),
      length(var.build_number) > 0 ? format("-%s", var.build_number) : "",
      format("-%s", s)
    )
  } : {}
}

locals {
  management_group = format(
    "mg%s%s",
    var.with_environment ? format("-%s", var.environment) : "",
    format("-%s", var.service)
  )
}

output "management_group" {
  value = local.management_group

  precondition {
    condition     = length(local.management_group) <= 88
    error_message = "Err: the name cannot exceed 90 characters."
  }
}

**Comment by suprememoocow** [comment]
We're also experiencing this:

```console
$ terraform version                                                                                                                                                                                                                                 Terraform v1.3.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.34.0
+ provider registry.terraform.io/hashicorp/time v0.9.0
+ provider registry.terraform.io/hashicorp/tls v4.0.3
+ provider registry.terraform.io/phillbaker/elasticsearch v2.0.5
+ provider registry.terraform.io/scottwinkler/shell v1.7.10
```

We're experiencing it on `terraform destroy` 

```console
$ terraform destroy --auto-approve
...
2022-10-14T12:23:13.836+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.data.aws_secretsmanager_secret_version.secret_item (expand)": starting visit (*terraform.nodeExpandApplyableResource)
2022-10-14T12:23:13.836+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.data.aws_secretsmanager_secret_version.secret_item (expand)": expanding dynamic subgraph
2022-10-14T12:23:13.836+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.data.aws_secretsmanager_secret_version.secret_item (expand)": entering dynamic subgraph
2022-10-14T12:23:13.836+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.data.aws_secretsmanager_secret_version.secret_item": starting visit (*terraform.NodeApplyableResource)
2022-10-14T12:23:13.836+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.data.aws_secretsmanager_secret_version.secret_item": visit complete
2022-10-14T12:23:13.836+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.data.aws_secretsmanager_secret_version.secret_item (expand)": dynamic subgraph completed successfully
2022-10-14T12:23:13.836+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.data.aws_secretsmanager_secret_version.secret_item (expand)": visit complete
2022-10-14T12:23:13.836+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.output.secrets (expand)": starting visit (*terraform.nodeExpandOutput)
2022-10-14T12:23:13.836+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.output.secrets (expand)": expanding dynamic subgraph
2022-10-14T12:23:13.836+0200 [TRACE] Expanding output: adding module.provisional_regional_r0.module.secret_reader.output.secrets as *terraform.NodeApplyableOutput
2022-10-14T12:23:13.836+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.output.secrets (expand)": entering dynamic subgraph
2022-10-14T12:23:13.836+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.output.secrets": starting visit (*terraform.NodeApplyableOutput)
2022-10-14T12:23:13.837+0200 [TRACE] evalCheckRules: module.provisional_regional_r0.module.secret_reader.output.secrets status is now StatusPass
2022-10-14T12:23:13.837+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.output.secrets": visit complete

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

checkable object status report for unexpected checkable object module.provisional_regional_r0.module.secret_reader.output.secrets
goroutine 11532 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x1c
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/distiller/project/project/internal/logging/panic.go:55 +0x170
panic({0x104399b00, 0x140026bd870})
	/usr/local/go/src/runtime/panic.go:884 +0x204
github.com/hashicorp/terraform/internal/checks.(*State).reportCheckResult(0x14007c788d0, {0x104842470, 0x14006ffa990}, 0x140064fd7a0?, 0x0, 0x50)
	/Users/distiller/project/project/internal/checks/state_report.go:103 +0x294
github.com/hashicorp/terraform/internal/checks.(*State).ReportCheckResult(0x103cc5a0b?, {0x104842470?, 0x14006ffa990?}, 0x140064fd8f8?, 0x1?, 0x0?)
	/Users/distiller/project/project/internal/checks/state_report.go:68 +0xd8
github.com/hashicorp/terraform/internal/terraform.evalCheckRules(0x140039a29d8?, {0x14000a09228, 0x1, 0x104295e0a?}, {0x1048522f8, 0x140036407e0}, {0x104842470, 0x14006ffa990}, {{{{0x0, 0x0}}, ...}, ...}, ...)
	/Users/distiller/project/project/internal/terraform/eval_conditions.go:58 +0x2cc
github.com/hashicorp/terraform/internal/terraform.(*NodeApplyableOutput).Execute(0x1400adf2e00, {0x1048522f8, 0x140036407e0}, 0xc0?)
	/Users/distiller/project/project/internal/terraform/node_output.go:327 +0x1d8
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x140019245a0, {0x1048522f8, 0x140036407e0}, {0x10e2d5128, 0x1400adf2e00})
	/Users/distiller/project/project/internal/terraform/graph_walk_context.go:136 +0xa8
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x1046908e0, 0x1400adf2e00})
	/Users/distiller/project/project/internal/terraform/graph.go:74 +0x208
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x1400813a540, {0x1046908e0, 0x1400adf2e00}, 0x1400adf2e80)
	/Users/distiller/project/project/internal/dag/walk.go:381 +0x2e0
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/Users/distiller/project/project/internal/dag/walk.go:304 +0xbf0
```

This is part of a very large project, so providing all configurations, or a recreateable subset is going to be tricky.

Reverting to Terraform 1.3.1 fixes the problem.

**Comment by suprememoocow** [comment]
Just a heads up: in my [previous report](https://github.com/hashicorp/terraform/issues/31994#issuecomment-1278828610), I noted that it reverting to Terraform 1.3.1 fixed the problem, and that we had only been seeing the problem on destroys. However, this is no longer the case. This panic happened on `terraform apply` with Terraform v1.3.1.

The error message isn't quite the same, but is happening on the same resource and appears to be related.

```console
$ terraform version
FATAL: Found legacy version file 'main.tf' with unsupported required
version constraint expression: '~>1.2'. This
plugin only supports strict equality.

Terraform v1.3.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.34.0
+ provider registry.terraform.io/hashicorp/time v0.9.0
+ provider registry.terraform.io/hashicorp/tls v4.0.3

Your version of Terraform is out of date! The latest version
is 1.3.2. You can update by downloading from https://www.terraform.io/downloads.html
$ terraform apply -parallelism=1
...
2022-10-18T08:16:07.732+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket.gitlab_backup_object_storage_buckets[\"terraform-state\"]": visit complete
2022-10-18T08:16:07.732+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_public_access_block.gitlab_backup_object_storage_buckets[\"uploads\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.732+0200 [TRACE] vertex "module.provisional_regional_r0.module.multi_region_kms.local.enable_customer_log_access": visit complete
2022-10-18T08:16:07.732+0200 [TRACE] vertex "module.provisional_regional_r0.module.multi_region_kms.local.enable_customer_log_access (expand)": dynamic subgraph completed successfully
2022-10-18T08:16:07.732+0200 [TRACE] vertex "module.provisional_regional_r0.module.multi_region_kms.local.enable_customer_log_access (expand)": visit complete
2022-10-18T08:16:07.737+0200 [TRACE] vertex "module.provisional_regional_r0.module.multi_region_kms.module.item.var.definitions (expand)": starting visit (*terraform.nodeExpandModuleVariable)
2022-10-18T08:16:07.737+0200 [TRACE] vertex "module.provisional_regional_r0.module.multi_region_kms.module.item.var.definitions (expand)": expanding dynamic subgraph
2022-10-18T08:16:07.738+0200 [TRACE] vertex "module.provisional_regional_r0.module.multi_region_kms.module.item.var.definitions (expand)": entering dynamic subgraph
2022-10-18T08:16:07.738+0200 [TRACE] vertex "module.provisional_regional_r0.module.multi_region_kms.module.item.var.definitions": starting visit (*terraform.nodeModuleVariable)
2022-10-18T08:16:07.738+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_public_access_block.gitlab_backup_object_storage_buckets[\"packages\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.738+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_lifecycle_configuration.gitlab_backup_object_storage_buckets[\"packages\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.738+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_versioning.gitlab_backup_object_storage_buckets[\"logs\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.738+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_lifecycle_configuration.gitlab_backup_object_storage_buckets[\"uploads\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.738+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_public_access_block.gitlab_backup_object_storage_buckets[\"dependency-proxy\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.738+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_public_access_block.gitlab_backup_object_storage_buckets[\"registry\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.738+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_public_access_block.gitlab_backup_object_storage_buckets[\"terraform-state\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.738+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_versioning.gitlab_backup_object_storage_buckets[\"terraform-state\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.738+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_lifecycle_configuration.gitlab_backup_object_storage_buckets[\"dependency-proxy\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.738+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_public_access_block.gitlab_backup_object_storage_buckets[\"backups\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.739+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_versioning.gitlab_backup_object_storage_buckets[\"artifacts\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.739+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_versioning.gitlab_backup_object_storage_buckets[\"uploads\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.739+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_lifecycle_configuration.gitlab_backup_object_storage_buckets[\"terraform-state\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.739+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_public_access_block.gitlab_backup_object_storage_buckets[\"lfs\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.739+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_versioning.gitlab_backup_object_storage_buckets[\"registry\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.739+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_public_access_block.gitlab_backup_object_storage_buckets[\"logs\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.740+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_lifecycle_configuration.gitlab_backup_object_storage_buckets[\"logs\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.740+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_versioning.gitlab_backup_object_storage_buckets[\"mr-diffs\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.740+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_versioning.gitlab_backup_object_storage_buckets[\"lfs\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.740+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_lifecycle_configuration.gitlab_backup_object_storage_buckets[\"lfs\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.740+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_lifecycle_configuration.gitlab_backup_object_storage_buckets[\"registry\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.740+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_public_access_block.gitlab_backup_object_storage_buckets[\"mr-diffs\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.740+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_lifecycle_configuration.gitlab_backup_object_storage_buckets[\"mr-diffs\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.740+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_versioning.gitlab_backup_object_storage_buckets[\"dependency-proxy\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.740+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_versioning.gitlab_backup_object_storage_buckets[\"packages\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.741+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_lifecycle_configuration.gitlab_backup_object_storage_buckets[\"backups\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.741+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_versioning.gitlab_backup_object_storage_buckets[\"backups\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.741+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_public_access_block.gitlab_backup_object_storage_buckets[\"artifacts\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.741+0200 [TRACE] vertex "module.provisional_regional_r0.aws_s3_bucket_lifecycle_configuration.gitlab_backup_object_storage_buckets[\"artifacts\"]": starting visit (*terraform.NodeApplyableResourceInstance)
2022-10-18T08:16:07.741+0200 [TRACE] setValue: Saving Create change for module.provisional_regional_r0.module.secret_reader.module.secret_definitions.output.secret_definitions in changeset
2022-10-18T08:16:07.741+0200 [TRACE] setValue: Saving value for module.provisional_regional_r0.module.secret_reader.module.secret_definitions.output.secret_definitions in state
2022-10-18T08:16:07.741+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.module.secret_definitions.output.secret_definitions": visit complete
2022-10-18T08:16:07.741+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.module.secret_definitions.output.secret_definitions (expand)": dynamic subgraph completed successfully
2022-10-18T08:16:07.741+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.module.secret_definitions.output.secret_definitions (expand)": visit complete
2022-10-18T08:16:07.741+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.output.secrets (expand)": starting visit (*terraform.nodeExpandOutput)
2022-10-18T08:16:07.743+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.output.secrets (expand)": expanding dynamic subgraph
2022-10-18T08:16:07.743+0200 [TRACE] Expanding output: adding module.provisional_regional_r0.module.secret_reader.output.secrets as *terraform.NodeApplyableOutput
2022-10-18T08:16:07.743+0200 [TRACE] vertex "module.provisional_regional_r0.module.secret_reader.output.secrets (expand)": visit complete

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

duplicate checkable objects report for module.provisional_regional_r0.module.secret_reader.output.secrets
goroutine 10941 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x1c
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/distiller/project/project/internal/logging/panic.go:55 +0x170
panic({0x102b25b00, 0x14006660bb0})
	/usr/local/go/src/runtime/panic.go:884 +0x204
github.com/hashicorp/terraform/internal/checks.(*State).ReportCheckableObjects(0x102de0da0?, {0x102fc9c60?, 0x14008ee84b0}, 0x140010d59e0?)
	/Users/distiller/project/project/internal/checks/state_report.go:29 +0x3b8
github.com/hashicorp/terraform/internal/terraform.(*nodeExpandOutput).DynamicExpand(0x14009c3d480, {0x102fde2b8, 0x14000de5260})
	/Users/distiller/project/project/internal/terraform/node_output.go:102 +0x204
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x102df1680, 0x14009c3d480})
	/Users/distiller/project/project/internal/terraform/graph.go:84 +0x2e4
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x14002088a80, {0x102df1680, 0x14009c3d480}, 0x14003a78300)
	/Users/distiller/project/project/internal/dag/walk.go:381 +0x2e0
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/Users/distiller/project/project/internal/dag/walk.go:304 +0xbf0
```

**Comment by Vince-Chenal** [comment]
Hey @apparentlymart,
The files I shared [here](https://github.com/hashicorp/terraform/issues/31846#issuecomment-1261061365) also have the problem with `terraform console` if it can help.
