### ISSUE TITLE
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by mrexhepi** [hashicorp/terraform#32318]
### Terraform Version

```shell
1.3.4
```

### Actual Behavior 

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

attempt to write nil state to file
goroutine 88 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x2143f40, 0x2b43210})
/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/states/statefile.writeStateV4(0xc00061da8c?, {0x2b46420?, 0xc004a604b0?})
/home/circleci/project/project/internal/states/statefile/version4.go:322 +0x15f8
github.com/hashicorp/terraform/internal/states/statefile.Write(0xc00061dc50?, {0x2b46420?, 0xc004a604b0?})
/home/circleci/project/project/internal/states/statefile/write.go:15 +0x45
github.com/hashicorp/terraform/internal/plans/planfile.Create({0x7f981012bf32?, 0x60?}, {0xc0002d04f0, 0xc00061de30, 0xc0049316e0, 0xc004d39930, 0xc0006ad908})
/home/circleci/project/project/internal/plans/planfile/writer.go:103 +0x670
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc00030bf40, {0x2b6adb8, 0xc00071dfc0}, {0x2b6adb8, 0xc0002ae000}, 0xc0004d4d80, 0xc00071df80)
/home/circleci/project/project/internal/backend/local/backend_plan.go:138 +0x905
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
/home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
/home/circleci/project/project/internal/backend/local/backend.go:316 +0x44a
Operation failed: failed running terraform plan (exit 11)
```

### Debug Output

n/a

### Expected Behavior

Destroy current infra

### Steps to Reproduce

Terraform destroy under Terraform cloud

**Comment by kmoe** [comment]
Thanks for the bug report. This is certainly concerning: unfortunately it's going to be hard for us to investigate without knowing what Terraform configuration or other circumstances produced this.

1. Can you provide some configuration that reproduces this?
2. Does this happen every time you run destroy, or only sometimes?
3. Does a normal plan against the same config/state succeed?

**Comment by mrexhepi** [comment]
Thanks for quick response, 
This was happening once I initiate destroy of tf cloud . But just after I was able to plan and apply successfully, looks good now.
 Will let you know if this reappeared.
