### ISSUE TITLE
Terraform crashes by destroying aks-cluster

### ISSUE THREAD

**Issue by STaegtmeier** [hashicorp/terraform#32341]
### Terraform Version

```shell
Terraform v1.3.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.34.0
+ provider registry.terraform.io/hashicorp/helm v2.7.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.16.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

### Terraform Configuration Files

```terraform
module "aks" {
  source  = "Azure/aks/azurerm"
  version = "6.2.0"

  private_cluster_enabled = false
}
```

### Debug Output

N/A

### Expected Behavior

Changed "private_cluster_enabled" from true to false.
Terraform should not crash. The aks should be replaced.

### Actual Behavior

module.aks.azurerm_kubernetes_cluster.main: Still destroying... [id=/subscriptions/1234-abcd/containerService/managedClusters/dev-aks, 9m50s elapsed]

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
runtime error: invalid memory address or nil pointer dereference
goroutine 82 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x1face60, 0x3bceda0})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/backend/remote-state/azure.(*RemoteClient).Put(0xc0000e02d0, {0xc000ff2000, 0xa356, 0xc000})
        /home/circleci/project/project/internal/backend/remote-state/azure/client.go:88 +0x583
github.com/hashicorp/terraform/internal/states/remote.(*State).PersistState(0xc0009624e0, 0x21dc320?)
        /home/circleci/project/project/internal/states/remote/state.go:196 +0x3bf
github.com/hashicorp/terraform/internal/states/statemgr.WriteAndPersist({0x1e9abfad3d0, 0xc0009624e0}, 0x1?, 0xc000de1e90?)
        /home/circleci/project/project/internal/states/statemgr/helper.go:53 +0x53
github.com/hashicorp/terraform/internal/backend/local.(*Local).opApply(0x0?, {0x28ef758, 0xc000b166c0}, {0x28ef758, 0xc000b16700}, 0xc0008ac480, 0xc000b16680)
        /home/circleci/project/project/internal/backend/local/backend_apply.go:201 +0x1075
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
        /home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
        /home/circleci/project/project/internal/backend/local/backend.go:316 +0x44a

### Steps to Reproduce

1. terraform init --backend-config=./env/dev_backend.tfvars
2. terraform plan -var-file ./env/dev.tfvars -var-file ./env/dev_backend.tfvars -input=false -out=".plan.cache"
3. terraform apply -input=false ".plan.cache"

### Additional Context

terraform is running directly in powershell. Second run finished successfully.

**Comment by kmoe** [comment]
@hashicorp/terraform-azure, it looks like this may be a mishandled error in the Azure backend client.
