### ISSUE TITLE
Terraform Crash reported when Internet tanked

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/terraform#32600]
### Terraform Version

```shell
$ terraform version
Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/azure/azapi v1.2.0
+ provider registry.terraform.io/hashicorp/azurerm v3.38.0
+ provider registry.terraform.io/hashicorp/external v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

### Terraform Configuration Files

```terraform
Does is really matter ?  
```

### Debug Output

```
Plan: 0 to add, 4 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

Releasing state lock. This may take a few moments...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 71 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/distiller/project/project/internal/logging/panic.go:55 +0x153
panic({0x2e413c0, 0x4a45130})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/backend/remote-state/azure.(*RemoteClient).Put(0xc00022e780, {0xc0048de000, 0x172be, 0x18000})
	/Users/distiller/project/project/internal/backend/remote-state/azure/client.go:88 +0x583
github.com/hashicorp/terraform/internal/states/remote.(*State).PersistState(0xc00059a2a0, 0x306f960?)
	/Users/distiller/project/project/internal/states/remote/state.go:196 +0x3bf
github.com/hashicorp/terraform/internal/states/statemgr.WriteAndPersist({0xda1cf18, 0xc00059a2a0}, 0x4?, 0xc002631e90?)
	/Users/distiller/project/project/internal/states/statemgr/helper.go:53 +0x53
github.com/hashicorp/terraform/internal/backend/local.(*Local).opApply(0xc0009dd9d8?, {0x3772eb8, 0xc000bb0b40}, {0x3772eb8, 0xc000bb0b80}, 0xc000b80c60, 0xc000bb0b00)
	/Users/distiller/project/project/internal/backend/local/backend_apply.go:201 +0x1075
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
	/Users/distiller/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
	/Users/distiller/project/project/internal/backend/local/backend.go:316 +0x44a
```

### Expected Behavior

terraform not to crash ?  Just reporting what happened when my internet connection went down.

### Actual Behavior

Terraform locked up, then reported it crashed

### Steps to Reproduce

Terraform apply,

Yank ethernet cord out of wall.

**Comment by crw** [comment]
Thanks for this report. I've added it to the Azure backend triage list.
