### ISSUE TITLE
TERRAFORM CRASH

### ISSUE THREAD

**Issue by Park-Seaweed** [hashicorp/terraform#32850]
### Terraform Version

```shell
1.4.0
```

### Terraform Configuration Files

I don't know where it's related.

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 76 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x23441a0, 0x406fc90})
/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0x0?)
/home/circleci/project/project/internal/plans/plan.go:100 +0x18
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc000c0c280, {0x2ccf8f8, 0xc00096fa80}, {0x2ccf8f8, 0xc00096fac0}, 0xc000290c60, 0xc00096fa40)
/home/circleci/project/project/internal/backend/local/backend_plan.go:104 +0x690
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
/home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
/home/circleci/project/project/internal/backend/local/backend.go:316 +0x44a
Operation failed: failed running terraform plan (exit 11)

### Expected Behavior

I should have been destroyed, but there was an error like that on the plan.

### Actual Behavior

error...

### Steps to Reproduce

When pushed from GitHub, it was distributed by planning and applying with the trigger, but the problem occurred when it was destroyed.

**Comment by palotasb-booking** [comment]
We just hit this bug too.

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.
When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.
[1]: https://github.com/hashicorp/terraform/issues
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
runtime error: invalid memory address or nil pointer dereference
goroutine 130 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x23441a0, 0x406fc90})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0x0?)
	/home/circleci/project/project/internal/plans/plan.go:100 +0x18
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc000efd9a0, {0x2ccf8f8, 0xc00071ec40}, {0x2ccf8f8, 0xc00071ec80}, 0xc000ae30e0, 0xc00071ec00)
	/home/circleci/project/project/internal/backend/local/backend_plan.go:104 +0x690
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
	/home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
	/home/circleci/project/project/internal/backend/local/backend.go:316 +0x44a
```

**Comment by jbardin** [comment]
Duplicate of #32810
