### ISSUE TITLE
Terraform Crash (reporting per instructions) 

### ISSUE THREAD

**Issue by jdmcd** [hashicorp/terraform#32956]
### Terraform Version

```shell
latest
```

### Terraform Configuration Files

I cannot share these unfortunately - I am reporting this issue because the CLI told me to. 

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```
value is marked, so must be unmarked first
goroutine 15182 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/logging/panic.go:55 +0x153
panic({0x227e900, 0x2d48890})
	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/panic.go:890 +0x262
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.True({{{0x2d74140?, 0xc000054332?}}, {0x2462280?, 0xc0046af488?}})
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/value_ops.go:363 +0x52
github.com/zclconf/go-cty/cty.IndexStep.Apply({{}, {{{0x2d74140?, 0xc000054331?}}, {0x227e900?, 0xc003c25800?}}}, {{{0x2d741e8?, 0xc003d98de0?}}, {0x2462280?, 0xc0041f7fc8?}})
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/path.go:232 +0x335
github.com/zclconf/go-cty/cty.Path.Apply({0xc0043ce1e0?, 0x2, 0x40e4e5?}, {{{0x2d74220?, 0xc003d98e10?}}, {0x2360480?, 0xc0047b69f0?}})
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/path.go:[147](https://github.com/gotranseo/infrastructure/actions/runs/4568783625/jobs/8064535561#step:7:148) +0xad
github.com/hashicorp/terraform/internal/terraform.filterMarks({{{0x2d74220?, 0xc003d98e10?}}, {0x2360480?, 0xc0047b69f0?}}, {0xc00403cb80?, 0x3, 0x2360480?})
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/terraform/marks.go:19 +0x14f
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).plan(0xc007df81e0, {0x2d8bfb8, 0xc000df4b60}, 0x0, 0xc000c72ae0, 0x1, {0x0, 0x0, 0xc001f68a01?})
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/terraform/node_resource_abstract_instance.go:1084 +0x2d8d
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc001b9edc0, {0x2d8bfb8, 0xc000df4b60})
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/terraform/node_resource_plan_instance.go:223 +0xdae
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x0?, {0x2d8bfb8?, 0xc000df4b60?}, 0xc0?)
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/terraform/node_resource_plan_instance.go:60 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc003ca4ff0, {0x2d8bfb8, 0xc000df4b60}, {0x7f4ef4ffb2a0, 0xc001b9edc0})
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/terraform/graph_walk_context.go:136 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x26e9960, 0xc001b9edc0})
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/terraform/graph.go:75 +0x315
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc0008ad8c0, {0x26e9960, 0xc001b9edc0}, 0xc001b9f[180](https://github.com/gotranseo/infrastructure/actions/runs/4568783625/jobs/8064535561#step:7:181))
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/dag/walk.go:381 +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/dag/walk.go:304 +0xf65
```

### Expected Behavior

The `terraform apply` script finishes successfully 

### Actual Behavior

It crashes with the linked stacktrace 

### Steps to Reproduce

Here are the relevant sections from the Github Actions workflow file: 

```yaml
    - name: Terraform Init
      env:
        PROD_AWS_STATE_BUCKET: ${{ secrets.PROD_AWS_STATE_BUCKET }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: terraform init -backend-config="region=${{ env.AWS_DEFAULT_REGION }}" -backend-config="profile=prod" -backend-config="bucket=${{ env.PROD_AWS_STATE_BUCKET }}" -backend-config="dynamodb_table=tf-lock"

    - name: Terraform Apply
      env:
        SOPS_AGE_KEY_FILE: ${{ runner.temp }}/sops/keys.txt
      run: terraform apply -var aws_profile="prod" -var running_ci="true" -no-color -input=false -auto-approve
```

### Additional Context

This is running on a self-hosted runner via Github Actions

**Comment by LipuFei** [comment]
I have the same issue since v1.4.3 and v1.4.4

**Comment by Karthik-Chowdary** [comment]
` % terraform --version
Terraform v1.4.0
on darwin_arm64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/archive v2.3.0
+ provider registry.terraform.io/hashicorp/aws v4.60.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.18.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/hashicorp/vault v3.13.0

Your version of Terraform is out of date! The latest version
is 1.4.2. You can update by downloading from https://www.terraform.io/downloads.html
 % terraform plan

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 69 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x1c
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/distiller/project/project/internal/logging/panic.go:55 +0x170
panic({0x103178560, 0x1048b2e00})
	/usr/local/go/src/runtime/panic.go:884 +0x204
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0x140033f6f10?)
	/Users/distiller/project/project/internal/plans/plan.go:100 +0x18
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0x14000a48460, {0x103558cb8, 0x14000ccadc0}, {0x103558cb8, 0x14000ccae00}, 0x14000c7cc60, 0x14000ccad80)
	/Users/distiller/project/project/internal/backend/local/backend_plan.go:104 +0x4d4
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
	/Users/distiller/project/project/internal/backend/local/backend.go:323 +0xd8
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
	/Users/distiller/project/project/internal/backend/local/backend.go:316 +0x440`

**Comment by jbardin** [comment]
@Karthik-Chowdary, that is a different crash from a different version, which is resolved in v1.4.2
