### ISSUE TITLE
Terraform crash on version 1.4.4

### ISSUE THREAD

**Issue by ofiry-tm** [hashicorp/terraform#32966]
### Terraform Version

```shell
Terraform v1.4.4
on linux_amd64
```

### Terraform Configuration Files

no relevant files, its a general issue

### Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

value is marked, so must be unmarked first
goroutine 2511 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/runner/work/terraform/terraform/internal/logging/panic.go:55 +0x153
panic({0x227e900, 0x2d48890})
	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/panic.go:890 +0x262
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.True({{{0x2d74140?, 0xc00005c342?}}, {0x2462280?, 0xc005f541c8?}})
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/value_ops.go:363 +0x52
github.com/zclconf/go-cty/cty.IndexStep.Apply({{}, {{{0x2d74140?, 0xc00005c341?}}, {0x227e900?, 0xc005eb8ce0?}}}, {{{0x2d741e8?, 0xc005f247e0?}}, {0x2462280?, 0xc005ed6ca8?}})
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/path.go:232 +0x335
github.com/zclconf/go-cty/cty.Path.Apply({0xc00956e660?, 0x2, 0x40e4e5?}, {{{0x2d74220?, 0xc005f24830?}}, {0x2360480?, 0xc00967a7e0?}})
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/path.go:147 +0xad
github.com/hashicorp/terraform/internal/terraform.filterMarks({{{0x2d74220?, 0xc005f24830?}}, {0x2360480?, 0xc00967a7e0?}}, {0xc00586e680?, 0x4, 0x2360480?})
	/home/runner/work/terraform/terraform/internal/terraform/marks.go:19 +0x14f
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).plan(0xc0086a8d20, {0x2d8bfb8, 0xc0087e81c0}, 0x0, 0xc000c76de0, 0x0, {0x0, 0x0, 0x758101?})
	/home/runner/work/terraform/terraform/internal/terraform/node_resource_abstract_instance.go:1084 +0x2d8d
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc003a869c0, {0x2d8bfb8, 0xc0087e81c0})
	/home/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:223 +0xdae
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x0?, {0x2d8bfb8?, 0xc0087e81c0?}, 0x78?)
	/home/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:60 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc00159da40, {0x2d8bfb8, 0xc0087e81c0}, {0x7efe934386c0, 0xc003a869c0})
	/home/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:136 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x26e9960, 0xc003a869c0})
	/home/runner/work/terraform/terraform/internal/terraform/graph.go:75 +0x315
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000b16840, {0x26e9960, 0xc003a869c0}, 0xc003a87280)
	/home/runner/work/terraform/terraform/internal/dag/walk.go:381 +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/home/runner/work/terraform/terraform/internal/dag/walk.go:304 +0xf65

```

### Expected Behavior

to run terraform apply successfully

### Actual Behavior

the crash above

### Steps to Reproduce

terraform apply

**Comment by jbg** [comment]
Happening here (darwin_arm64 and linux_amd64) on every apply, with multiple completely different TF configs. Downgrade to 1.4.2 fixes the issue, have not been able to test 1.4.3 yet.

**Comment by liamcervante** [comment]
Thanks for the report! I believe this is a duplicate of #32956, and should be fixed in v1.4.5.
