### ISSUE TITLE
Attaching to a local debug provider causes a crash and dumps a stack trace

### ISSUE THREAD

**Issue by ddaws** [hashicorp/terraform#32976]
### Terraform Version

```shell
Terraform v1.4.2
on linux_amd64
+ provider registry.terraform.io/gitlabhq/gitlab v15.10.0
+ provider registry.terraform.io/hashicorp/aws v4.22.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/nomad v1.4.19
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/vault v3.14.0
```

### Terraform Configuration Files

In this case I am just attempting to connect to a debug instance of the Nomad provider

```terraform
terraform {
  required_version = "~> 1.4.2"
}

provider "nomad" {}

data "nomad_deployments" "example" {}
```

### Debug Output

```
$ TF_LOG=trace tf apply 
2023-04-04T19:22:10.188+0800 [INFO]  Terraform version: 1.4.2
2023-04-04T19:22:10.188+0800 [DEBUG] using github.com/hashicorp/go-tfe v1.18.0
2023-04-04T19:22:10.188+0800 [DEBUG] using github.com/hashicorp/hcl/v2 v2.16.2
2023-04-04T19:22:10.188+0800 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2023-04-04T19:22:10.188+0800 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.0
2023-04-04T19:22:10.188+0800 [DEBUG] using github.com/zclconf/go-cty v1.12.1
2023-04-04T19:22:10.188+0800 [INFO]  Go runtime version: go1.19.6
2023-04-04T19:22:10.188+0800 [INFO]  CLI args: []string{"/var/lib/tfenv/versions/1.4.2/terraform", "apply"}
2023-04-04T19:22:10.188+0800 [TRACE] Stdout is a terminal of width 172
2023-04-04T19:22:10.188+0800 [TRACE] Stderr is a terminal of width 172
2023-04-04T19:22:10.188+0800 [TRACE] Stdin is a terminal
2023-04-04T19:22:10.188+0800 [DEBUG] Attempting to open CLI config file: /home/dawson/.terraformrc
2023-04-04T19:22:10.188+0800 [INFO]  Loading CLI configuration from /home/dawson/.terraformrc
2023-04-04T19:22:10.188+0800 [DEBUG] checking for credentials in "/home/dawson/.terraform.d/plugins"
2023-04-04T19:22:10.188+0800 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-04-04T19:22:10.189+0800 [DEBUG] will search for provider plugins in /home/dawson/.terraform.d/plugins
2023-04-04T19:22:10.189+0800 [DEBUG] ignoring non-existing provider search directory /home/dawson/.local/share/terraform/plugins
2023-04-04T19:22:10.189+0800 [DEBUG] ignoring non-existing provider search directory /usr/share/i3/terraform/plugins
2023-04-04T19:22:10.189+0800 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2023-04-04T19:22:10.189+0800 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2023-04-04T19:22:10.189+0800 [DEBUG] ignoring non-existing provider search directory /var/lib/snapd/desktop/terraform/plugins
2023-04-04T19:22:10.189+0800 [INFO]  CLI command args: []string{"apply"}
2023-04-04T19:22:10.189+0800 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2023-04-04T19:22:10.189+0800 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2023-04-04T19:22:10.189+0800 [DEBUG] New state was assigned lineage "4fb1f043-2b73-a313-7bdb-f66acf1fd5ff"
2023-04-04T19:22:10.189+0800 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2023-04-04T19:22:10.189+0800 [TRACE] Meta.Backend: instantiated backend of type <nil>
2023-04-04T19:22:10.189+0800 [DEBUG] Provider registry.terraform.io/hashicorp/nomad is overridden as an "unmanaged provider"
2023-04-04T19:22:10.190+0800 [DEBUG] checking for provisioner in "."
2023-04-04T19:22:10.190+0800 [DEBUG] checking for provisioner in "/var/lib/tfenv/versions/1.4.2"
2023-04-04T19:22:10.190+0800 [DEBUG] checking for provisioner in "/home/dawson/.terraform.d/plugins"
2023-04-04T19:22:10.190+0800 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
2023-04-04T19:22:10.190+0800 [DEBUG] Provider registry.terraform.io/hashicorp/nomad is overridden as an "unmanaged provider"
2023-04-04T19:22:10.190+0800 [INFO]  backend/local: starting Apply operation
2023-04-04T19:22:10.190+0800 [TRACE] backend/local: requesting state manager for workspace "default"
2023-04-04T19:22:10.190+0800 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2023-04-04T19:22:10.190+0800 [TRACE] backend/local: requesting state lock for workspace "default"
2023-04-04T19:22:10.190+0800 [TRACE] statemgr.Filesystem: preparing to manage state snapshots at terraform.tfstate
2023-04-04T19:22:10.190+0800 [TRACE] statemgr.Filesystem: no previously-stored snapshot exists
2023-04-04T19:22:10.190+0800 [TRACE] statemgr.Filesystem: locking terraform.tfstate using fcntl flock
2023-04-04T19:22:10.190+0800 [TRACE] statemgr.Filesystem: writing lock metadata to .terraform.tfstate.lock.info
2023-04-04T19:22:10.190+0800 [TRACE] backend/local: reading remote state for workspace "default"
2023-04-04T19:22:10.190+0800 [TRACE] statemgr.Filesystem: reading latest snapshot from terraform.tfstate
2023-04-04T19:22:10.190+0800 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2023-04-04T19:22:10.190+0800 [TRACE] statemgr.Filesystem: read nil snapshot
2023-04-04T19:22:10.190+0800 [TRACE] backend/local: populating backend.LocalRun for current working directory
2023-04-04T19:22:10.190+0800 [DEBUG] Config.VerifyDependencySelections: skipping registry.terraform.io/hashicorp/nomad because it's overridden by a special configuration setting
2023-04-04T19:22:10.190+0800 [TRACE] terraform.NewContext: starting
2023-04-04T19:22:10.190+0800 [TRACE] terraform.NewContext: complete
2023-04-04T19:22:10.190+0800 [TRACE] backend/local: requesting interactive input, if necessary
2023-04-04T19:22:10.190+0800 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/hashicorp/nomad"
2023-04-04T19:22:10.190+0800 [TRACE] terraform.contextPlugins: Initializing provider "registry.terraform.io/hashicorp/nomad" to read its schema
2023-04-04T19:22:10.190+0800 [DEBUG] created provider logger: level=trace

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
goroutine 27 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x2383220, 0x4135cf0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/plugin.(*GRPCProviderPlugin).Client(0x7fe3ab441e18?, 0xc0005f6000?, 0x12?)
	<autogenerated>:1 +0x24
github.com/hashicorp/go-plugin.(*RPCClient).Dispense(0xc0005abd40, {0x273f5ec, 0x8})
	/home/circleci/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.3/rpc_client.go:159 +0x193
github.com/hashicorp/terraform/internal/command.unmanagedProviderFactory.func1()
	/home/circleci/project/project/internal/command/meta_providers.go:448 +0x472
github.com/hashicorp/terraform/internal/terraform.(*contextPlugins).NewProviderInstance(0x280785e?, {{0xc000058918, 0x5}, {0x274147d, 0x9}, {0x2762eb6, 0x15}})
	/home/circleci/project/project/internal/terraform/context_plugins.go:57 +0x264
github.com/hashicorp/terraform/internal/terraform.(*contextPlugins).ProviderSchema(0xc0008ee420, {{0xc000058918, 0x5}, {0x274147d, 0x9}, {0x2762eb6, 0x15}})
	/home/circleci/project/project/internal/terraform/context_plugins.go:91 +0x20a
github.com/hashicorp/terraform/internal/terraform.loadProviderSchemas.func1({{0xc000058918, 0x5}, {0x274147d, 0x9}, {0x2762eb6, 0x15}})
	/home/circleci/project/project/internal/terraform/schemas.go:109 +0x31a
github.com/hashicorp/terraform/internal/terraform.loadProviderSchemas(0x1b?, 0x40?, 0x0, 0x40d63f?)
	/home/circleci/project/project/internal/terraform/schemas.go:130 +0x1eb
github.com/hashicorp/terraform/internal/terraform.loadSchemas(0xc0008e1298?, 0x40d987?, 0xc0008e1298?)
	/home/circleci/project/project/internal/terraform/schemas.go:90 +0xa5
github.com/hashicorp/terraform/internal/terraform.(*Context).Schemas(0xc000820300?, 0x3?, 0x4?)
	/home/circleci/project/project/internal/terraform/context.go:155 +0x2a
github.com/hashicorp/terraform/internal/terraform.(*Context).Input(0xc000820300, 0xc00023e700, 0x1)
	/home/circleci/project/project/internal/terraform/context_input.go:48 +0x9e
github.com/hashicorp/terraform/internal/backend/local.(*Local).localRun(0xc000679d60, 0xc000466000)
	/home/circleci/project/project/internal/backend/local/backend_local.go:113 +0x877
github.com/hashicorp/terraform/internal/backend/local.(*Local).opApply(0x0?, {0x2d72678, 0xc0005ab880}, {0x2d72678, 0xc0005ab8c0}, 0xc000466000, 0xc0005ab840)
	/home/circleci/project/project/internal/backend/local/backend_apply.go:50 +0x19c
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
	/home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
	/home/circleci/project/project/internal/backend/local/backend.go:316 +0x44a
```

### Expected Behavior

I expect to be able to run a the Nomad provider in debug mode locally and export the `TF_REATTACH_PROVIDERS` envvar to tell Terraform to attach to the local provider instance. 

### Actual Behavior

Exporting `TF_REATTACH_PROVIDERS` to tell Terraform to attach to a local provider causes Terraform to crash and print a stack trace. This is blocking me from debugging problems with the Terraform Nomad provider.

### Steps to Reproduce

1. Clone the Nomad Terraform provider 
2. Apply the following patch to add support for debugging

```
diff --git a/main.go b/main.go
index 3c2b116..1aa0ec5 100644
--- a/main.go
+++ b/main.go
@@ -1,14 +1,31 @@
 package main
 
 import (
+	"context"
+	"flag"
+	"log"
+
 	"github.com/hashicorp/terraform-plugin-sdk/plugin"
 	"github.com/hashicorp/terraform-plugin-sdk/terraform"
-
 	"github.com/hashicorp/terraform-provider-nomad/nomad"
 )
 
 func main() {
-	plugin.Serve(&plugin.ServeOpts{
+	var debugMode bool
+	flag.BoolVar(&debugMode, "debug", false, "set to true to run the provider with support for debuggers like delve")
+	flag.Parse()
+
+	opts := &plugin.ServeOpts{
 		ProviderFunc: func() terraform.ResourceProvider { return nomad.Provider() },
-	})
+	}
+
+	if debugMode {
+		err := plugin.Debug(context.Background(), "hashicorp/nomad", opts)
+		if err != nil {
+			log.Fatal(err.Error())
+		}
+		return
+	}
+
+	plugin.Serve(opts)
 }
```

3. Build the provider in debug mode

```
go build -o nomad-provider -gcflags "all=-N -l" main.go
```

4. Run the provider using `dlv`

```
dlv --listen=127.0.0.1:43227 --headless=true --api-version=2 --check-go-version=false --only-same-user=false exec nomad-provider -- --debug
```

**Note: I am doing this through GoLand making it much simpler. I have not fully tested running this from command line directly.**

5. Export the `TF_REATTACH_PROVIDERS` variable 

```
export TF_REATTACH_PROVIDERS='{"hashicorp/nomad":{"Protocol":"netrpc","Pid":122018,"Test":true,"Addr":{"Network":"unix","String":"/tmp/plugin3049762698"}}}'
```

7. Attempt to init and apply the example Terraform main.tf

```
terraform init
terraform apply
```

**Comment by kmoe** [comment]
Thanks. The nomad provider is unfortunately using an old version of the SDK (v1.17) which does not support TF_REATTACH_PROVIDERS. This will be the case until https://github.com/hashicorp/terraform-provider-nomad/issues/231 is closed.

I'm curious as to how you determined the values for `TF_REATTACH_PROVIDERS` in step 5, since running the provider (either via dlv or with `./nomad-provider --debug` does not produce this string.

**Comment by kmoe** [comment]
The correct place to request that SDKv1 providers support reattach would be github.com/hashicorp/terraform-provider-sdk, but I think it is unlikely that this functionality will be backported, and you will instead need to wait for the nomad provider to upgrade.
