### ISSUE TITLE
Terraform crash report

### ISSUE THREAD

**Issue by JamesCalleja** [hashicorp/terraform#33052]
### Terraform Version

```shell
tf --version
Terraform v1.4.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.60.0
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4

Your version of Terraform is out of date! The latest version
is 1.4.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 69 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x1c
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /Users/distiller/project/project/internal/logging/panic.go:55 +0x170

### Expected Behavior

show a tf plan

### Actual Behavior

crashed

### Steps to Reproduce

terraform init 
terraform plan --var-file=<path to file>

**Comment by jbardin** [comment]
Hi @JamesCalleja,

Thanks for filing the issue. You truncated the stack trace, so it's not showing where the crash originated. You are however not using the current patch release, so there's a good change that this is fixed in the current version. Can you confirm that this is still present in v1.4.5 or later?

Thanks!

**Comment by JamesCalleja** [comment]
Updating to 1.4.5 and a git pull has fixed the issue. 

Thanks
