### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by Luca-Castelnuovo** [hashicorp/terraform#33050]
### Terraform Version

```shell
Terraform v1.4.5
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.3.0
+ provider registry.terraform.io/digitalocean/digitalocean v2.27.1
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.63.0
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/http v3.2.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.19.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">=1.3.9"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.0"
    }
  }

  cloud {
    organization = "XXX"

    workspaces {
      name = "terraform"
    }
  }
}

# Providers
provider "aws" {
  access_key = var.aws_access_key
  secret_key = var.aws_access_secret
}

provider "cloudflare" {
  api_token = var.cf_api_token
}

provider "digitalocean" {
  token             = var.do_token
  spaces_access_id  = var.do_spaces_key
  spaces_secret_key = var.do_spaces_secret
}
```

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 83 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x23441a0, 0x406fc90})
/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0x0?)
/home/circleci/project/project/internal/plans/plan.go:100 +0x18
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc0009981e0, {0x2ccf8f8, 0xc0007e2b40}, {0x2ccf8f8, 0xc0007e2b80}, 0xc0005f1e60, 0xc0007e2b00)
/home/circleci/project/project/internal/backend/local/backend_plan.go:104 +0x690
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
/home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
/home/circleci/project/project/internal/backend/local/backend.go:316 +0x44a
Operation failed: failed running terraform plan (exit 11)

### Expected Behavior

should run command successfully and create a plan

### Actual Behavior

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 83 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x23441a0, 0x406fc90})
/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0x0?)
/home/circleci/project/project/internal/plans/plan.go:100 +0x18
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc0009981e0, {0x2ccf8f8, 0xc0007e2b40}, {0x2ccf8f8, 0xc0007e2b80}, 0xc0005f1e60, 0xc0007e2b00)
/home/circleci/project/project/internal/backend/local/backend_plan.go:104 +0x690
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
/home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
/home/circleci/project/project/internal/backend/local/backend.go:316 +0x44a
Operation failed: failed running terraform plan (exit 11)

### Steps to Reproduce

1. terraform init
2. terraform apply

**Comment by jbardin** [comment]
Hi @Luca-Castelnuovo,

The crash shown here cannot come from Terraform v1.4.5, I would verify that you have actually upgraded Terraform where it is executing. The stack trace is from version v1.4.0, original issue is at #32810.

Thanks!

**Comment by Luca-Castelnuovo** [comment]
Thank you for pointing that out. My local version was indeed 1.4.5 but my Terraform Cloud version was still at 1.4.0. After updating that and changing my version contstraint to >=1.4.5 I got an error message that actually makes sense.
