### ISSUE TITLE
"Error: The terraform-provider-docker_v3.0.1 plugin crashed!" made by "docker_logs" data

### ISSUE THREAD

**Issue by callmefish** [hashicorp/terraform#33086]
### Terraform Version

```shell
1.3.5
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0"
    }
  }
}

resource "docker_container" "example" {
  # ... a container running a bash script ...
  # ... the script only contains some curl requests ...
}

resource "time_sleep" "wait_30" {
  depends_on = [
    docker_container.example
  ]
  create_duration = "30s"
}

data "docker_logs" "my_logs" {
  depends_on = [
    time_sleep.wait_30
  ]
  name = docker_container.example.name
  tail         = 30
}

output "output_logs" {
  value = data.docker_logs.my_logs.logs_list_string
}
```

### Debug Output

```
╷
│ Error: Plugin did not respond
│ 
│   with module.xxx.data.docker_logs.my_logs,
│   on .terraform/modules/xxx/main.tf line 106, in data "docker_logs" "my_logs":
│  106: data "docker_logs" "my_logs" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-docker_v3.0.1 plugin:

panic: runtime error: slice bounds out of range [8:7]

goroutine 434 [running]:
github.com/terraform-providers/terraform-provider-docker/internal/provider.dataSourceDockerLogsRead({0xfc47b0, 0xc000610900}, 0x0?, {0xce8260?, 0xc0003be240?})
        github.com/terraform-providers/terraform-provider-docker/internal/provider/data_source_docker_logs.go:118 +0x893
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0004bab60, {0xfc47e8, 0xc000590c90}, 0xd?, {0xce8260, 0xc0003be240})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0004bab60, {0xfc47e8, 0xc000590c90}, 0xc0001e8a00, {0xce8260, 0xc0003be240})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc00000d710, {0xfc47e8?, 0xc000590b70?}, 0xc00061c140)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1179 +0x38f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0003ea140, {0xfc47e8?, 0xc000590360?}, 0xc0005f4320)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:658 +0x3ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0xe20de0?, 0xc0003ea140}, {0xfc47e8, 0xc000590360}, 0xc00033a770, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000003c0, {0xfc7960, 0xc000583d40}, 0xc0006e4240, 0xc0004c5da0, 0x1557c50, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000003c0, {0xfc7960, 0xc000583d40}, 0xc0006e4240, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-docker_v3.0.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

The "docker_logs" read all stdout result from the docker container after 30 seconds.

### Actual Behavior

Failed, and show the above debug output.

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`
3. `terraform apply -auto-approve`

### Additional Context

I also try the 3.0.2 version of docker provider, it shows the similar error information

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
