### ISSUE TITLE
azurerm_local_network_gateway fails to create when bgp settings are supplied

### ISSUE THREAD

**Issue by shardebeck** [hashicorp/terraform#33093]
### Terraform Version

```shell
Terraform v1.4.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.53.0
```

### Terraform Configuration Files

```
resource "azurerm_local_network_gateway" "local-gw-primary" {
  name                = "vnet-lng-vxprimary"
  resource_group_name = data.azurerm_resource_group.network-rg.name
  location            = data.azurerm_resource_group.network-rg.location
  gateway_address     = local.lng_ip_pri
  address_space       = [""]
  bgp_settings {
     asn                 = local.lng_bgp_asn_pri
     bgp_peering_address = local.lng_bgp_peering_address_pri
  }
  
  lifecycle {
    ignore_changes     = [address_space]
  }
}
```

### Debug Output

```
azurerm_local_network_gateway.local-gw-primary: Creating...
╷
│ Error: Plugin did not respond
│
│   with azurerm_local_network_gateway.local-gw-primary,
│   on main.tf line 136, in resource "azurerm_local_network_gateway" "local-gw-primary":
│  136: resource "azurerm_local_network_gateway" "local-gw-primary" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.53.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 150 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.expandLocalNetworkGatewayAddressSpaces(0xc00144d7a0?)
        github.com/hashicorp/terraform-provider-azurerm/internal/services/network/local_network_gateway_resource.go:271 +0x1d4
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.resourceLocalNetworkGatewayCreateUpdate(0xc00222ba80, {0x6167c60?, 0xc0019dec00})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/network/local_network_gateway_resource.go:160 +0xb25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x75cb7e0?, {0x75cb7e0?, 0xc00293eb70?}, 0xd?, {0x6167c60?, 0xc0019dec00?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0013ea380, {0x75cb7e0, 0xc00293eb70}, 0xc002049e10, 0xc00222b900, {0x6167c60, 0xc0019dec00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0006e5890, {0x75cb7e0?, 0xc00293ea50?}, 0xc0017c5720)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001a095e0, {0x75cb7e0?, 0xc00293e1b0?}, 0xc002171650)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x68ed9a0?, 0xc001a095e0}, {0x75cb7e0, 0xc00293e1b0}, 0xc0021715e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000014000, {0x75dadc0, 0xc0010be1a0}, 0xc002058360, 0xc001262270, 0xbaafac0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc000014000, {0x75dadc0, 0xc0010be1a0}, 0xc002058360, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.53.0_x5 plugin crashed!
```

### Expected Behavior

Resource is created with BGP Settings applied

### Actual Behavior

Receive a message that the provider has crashed. I can see in the crash log that it appears to be looking for the resource, as if it should already exist.

If I apply the resource without BPG settings, it applies just fine. And if I add the BGP settings and apply the changes, it works just fine. It just does not apply the first time with the BGP settings.

### Steps to Reproduce

terraform init
terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by shardebeck** [comment]
Thank you! I have submitted a ticket for the provider.
