### ISSUE TITLE
Import block with id of "" causes plan to error

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform#33505]
Undefined behaviour when an `import` block `id` is empty string `""`.

An empty import ID is not valid, and Terraform should print a friendly error message in this case.

### Config

```hcl
import {
  to = null_resource.foo
  id = ""
}
```

#### Normal plan

```
$ terraform plan

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Resource has no configuration
│ 
│ Terraform attempted to process a resource at null_resource.foo that has no configuration. This is a bug in Terraform; please report it!
╵
```

#### Genconfig plan

```
$  terraform plan -generate-config-out=t.tf

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 101 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/debug/stack.go:16 +0x1c
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/katy/dev/go/src/github.com/hashicorp/terraform/internal/logging/panic.go:58 +0x170
panic({0x104813ba0, 0x105fa1fc0})
	/opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/panic.go:890 +0x258
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0x140009a20b0, {0x104c16018, 0x140004cc7e0})
	/Users/katy/dev/go/src/github.com/hashicorp/terraform/internal/terraform/node_resource_plan_instance.go:288 +0xf30
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x0?, {0x104c16018?, 0x140004cc7e0?}, 0x80?)
	/Users/katy/dev/go/src/github.com/hashicorp/terraform/internal/terraform/node_resource_plan_instance.go:74 +0x7c
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x14000b25200, {0x104c16018, 0x140004cc7e0}, {0x10e10ecd0, 0x140009a20b0})
	/Users/katy/dev/go/src/github.com/hashicorp/terraform/internal/terraform/graph_walk_context.go:143 +0xa8
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x104b83ce0, 0x140009a20b0})
	/Users/katy/dev/go/src/github.com/hashicorp/terraform/internal/terraform/graph.go:78 +0x238
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x14000656120, {0x104b83ce0, 0x140009a20b0}, 0x14000674200)
	/Users/katy/dev/go/src/github.com/hashicorp/terraform/internal/dag/walk.go:384 +0x2e0
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/Users/katy/dev/go/src/github.com/hashicorp/terraform/internal/dag/walk.go:307 +0xbf0
```

### Expected behaviour

A nicer error message.

**Comment by GOTAM672** [comment]
Hey, I want to contribute to this project. Is this a good issue to start with as a beginner?

**Comment by kmoe** [comment]
@GOTAM672 yeah! Check out `decodeImportBlock()` in `terraform/internal/configs/import.go`. That function needs to return a diagnostic with a good error message if the import id is `""`. Add a test in `configs/import_test.go` for this case as well.

**Comment by GOTAM672** [comment]
Thanks @kmoe for guiding. what should be the message?

**Comment by kmoe** [comment]
Let's use something like the following for now.

```go
Summary: "Import ID cannot be blank",
Detail: "The id argument of the import block must be a non-empty string. Please see the resource documentation for how to find the import ID."
```

We can tweak it later if it doesn't look right.

**Comment by GOTAM672** [comment]
Hi @kmoe , I implemented that error message but I have doubts while adding the test in `configs/import_test.go`, should I open a draft PR so that we can discuss those doubts over there?

**Comment by kmoe** [comment]
@GOTAM672 Yes, go ahead
