### ISSUE TITLE
terraform crash, unable to generate website

### ISSUE THREAD

**Issue by hmlanigan** [hashicorp/terraform#33550]
### Terraform Version

```shell
Terraform v1.5.3
on linux_amd64
```

### Terraform Configuration Files

NA

### Debug Output

NA

### Expected Behavior

Docs should have been generated

### Actual Behavior

go version 1.20.6

~/work/src/github.com/juju/terraform-provider-juju$ go generate ./...
rendering website for provider "terraform-provider-juju" (as "terraform-provider-juju")
copying any existing content to tmp dir
exporting schema from Terraform
compiling provider "juju"
using Terraform CLI binary from PATH if available, otherwise downloading latest Terraform CLI binary
running terraform init
getting provider schema
Error executing command: unable to generate website: exit status 11

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
	/snap/go/current/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/snap/go/current/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/build/terraform/parts/terraform/build/internal/logging/panic.go:58 +0x153
panic({0x2440000, 0x41eadf0})
	/snap/go/current/src/runtime/panic.go:890 +0x263
github.com/hashicorp/terraform/internal/plugin/convert.ProtoToConfigSchema(0x0)
	/build/terraform/parts/terraform/build/internal/plugin/convert/schema.go:107 +0x52
github.com/hashicorp/terraform/internal/plugin/convert.ProtoToProviderSchema(...)
	/build/terraform/parts/terraform/build/internal/plugin/convert/schema.go:95
github.com/hashicorp/terraform/internal/plugin.(*GRPCProvider).GetProviderSchema(0xc000c80630)
	/build/terraform/parts/terraform/build/internal/plugin/grpc_provider.go:129 +0x5af
github.com/hashicorp/terraform/internal/terraform.(*contextPlugins).ProviderSchema(0xc000b0d530, {{0xc00041e020, 0x4}, {0x27ff34e, 0x9}, {0x2821029, 0x15}})
	/build/terraform/parts/terraform/build/internal/terraform/context_plugins.go:100 +0x30b
github.com/hashicorp/terraform/internal/terraform.loadProviderSchemas.func1({{0xc00041e020, 0x4}, {0x27ff34e, 0x9}, {0x2821029, 0x15}})
	/build/terraform/parts/terraform/build/internal/terraform/schemas.go:112 +0x13f
github.com/hashicorp/terraform/internal/terraform.loadProviderSchemas(0xc0005b2410?, 0x26686e0?, 0x0, 0x0?)
	/build/terraform/parts/terraform/build/internal/terraform/schemas.go:133 +0xf6
github.com/hashicorp/terraform/internal/terraform.loadSchemas(0x0?, 0x0?, 0x0?)
	/build/terraform/parts/terraform/build/internal/terraform/schemas.go:93 +0xa5
github.com/hashicorp/terraform/internal/terraform.(*Context).Schemas(0x0?, 0x0?, 0x0?)
	/build/terraform/parts/terraform/build/internal/terraform/context.go:158 +0x2a
github.com/hashicorp/terraform/internal/command.(*ProvidersSchemaCommand).Run(0xc0002edc00, {0xc0000500d0?, 0xffffffffffffffff?, 0x0?})
	/build/terraform/parts/terraform/build/internal/command/providers_schema.go:103 +0x8fe
github.com/mitchellh/cli.(*CLI).Run(0xc000a88b40)
	/root/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5f8
main.realMain()
	/build/terraform/parts/terraform/build/main.go:318 +0x1729
main.main()
	/build/terraform/parts/terraform/build/main.go:61 +0x19

exit status 1
main.go:26: running "go": exit status 1

### Steps to Reproduce

go generate ./...

From this PR https://github.com/juju/terraform-provider-juju/pull/248, though the PR might change over time. Hopefully the nil pointer panic trace is sufficient. We will be looking to see what is wrong in the PR code to produce this.

**Comment by crw** [comment]
Thanks for this report!

**Comment by lbhattvida** [comment]
Getting similar error - 
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 30 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x23441a0, 0x406fc90})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0x0?)
	/home/circleci/project/project/internal/plans/plan.go:100 +0x[18](https://github.com/VIDADiagnostics/portal-infrastructure/actions/runs/5724268892/job/15510431798?pr=505#step:10:19)
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc001673040, {0x2ccf8f8, 0xc000e84780}, {0x2ccf8f8, 0xc000e847c0}, 0xc0014d01[20](https://github.com/VIDADiagnostics/portal-infrastructure/actions/runs/5724268892/job/15510431798?pr=505#step:10:21), 0xc000e84740)
	/home/circleci/project/project/internal/backend/local/backend_plan.go:104 +0x690
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
	/home/circleci/project/project/internal/backend/local/backend.go:3[23](https://github.com/VIDADiagnostics/portal-infrastructure/actions/runs/5724268892/job/15510431798?pr=505#step:10:24) +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
	/home/circleci/project/project/internal/backend/local/backend.go:[31](https://github.com/VIDADiagnostics/portal-infrastructure/actions/runs/5724268892/job/15510431798?pr=505#step:10:32)6 +0x[44](https://github.com/VIDADiagnostics/portal-infrastructure/actions/runs/5724268892/job/15510431798?pr=505#step:10:45)a
Error: Terraform exited with code 11.
Error: Process completed with exit code 1.

**Comment by liamcervante** [comment]
Hi @hmlanigan, thanks for filing this! Based on the stack trace the crash is originating [here](https://github.com/hashicorp/terraform/blob/v1.5.3/internal/plugin/convert/schema.go#L107). This suggests that your provider was passing in the schema as `nil`, and then when Terraform tries reads from it we get our crash. It seems like an easy fix would be for us to just check for `nil` before processing that.

What I'm curious about is how it's actually possible for Terraform to be receiving a `nil` schema - did you ever manage to figure out what was causing the crash from within your PR?

**Comment by liamcervante** [comment]
Hi @lbhattvida, I think your stack trace is a bit different to the one provided initially. Did this also trigger while generating the docs for a provider? If not, it might be best for you to file that as a separate issue and provide the configuration you were planning or applying, or the commands you ran to trigger it. Thanks!

**Comment by hmlanigan** [comment]
@liamcervante the code is working now and not panicking. Unfortunately I'm not sure exactly what the change to resolve it was. We've been on a steep learning curve on how terraform works in general while migration from using the SDK to the Framework.

**Comment by liamcervante** [comment]
Okay, thanks! I'm concerned we have a bug in the provider SDK that is causing it to send invalid schema. With that in mind, I'm tempted to not fix this right now and hope we can reproduce it again another time. This would allow us to both fix up the SDK and Terraform itself. If we just made Terraform more robust, we might not discover the issue in the SDK.
