### ISSUE TITLE
Terraform Crashed

### ISSUE THREAD

**Issue by Ashish07Wiz** [hashicorp/terraform#33606]
### Terraform Version

```shell
Terraform v1.5.3
on windows_amd64
```

### Terraform Configuration Files

```terraform
...terraform config...
```runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.20.0/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.20.0/x64/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x153
panic({0x2e80560, 0x4c4ae50})
        /opt/hostedtoolcache/go/1.20.0/x64/src/runtime/panic.go:890 +0x263
github.com/hashicorp/terraform/internal/configs.NewModule({0xc0009247e0, 0x4, 0x0?}, {0x0, 0x0, 0x1c7b0b6?})
        /home/runner/work/terraform/terraform/internal/configs/module.go:127 +0xa18
github.com/hashicorp/terraform/internal/configs.(*Parser).LoadConfigDir(0xc0002ebc00?, {0x380e2e0, 0x1})
        /home/runner/work/terraform/terraform/internal/configs/parser_config_dir.go:45 +0x265
github.com/hashicorp/terraform/internal/command.(*Meta).loadSingleModule(0xc0005023c0?, {0xc0005023c0?, 0xc0002ebda4?})
        /home/runner/work/terraform/terraform/internal/command/meta_config.go:71 +0x9b
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc0002ebc00, {0xc0000903d0, 0x0, 0x0})
        /home/runner/work/terraform/terraform/internal/command/init.go:161 +0xe8b
github.com/mitchellh/cli.(*CLI).Run(0xc0001f7680)
        /home/runner/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5f8
main.realMain()
        /home/runner/work/terraform/terraform/main.go:318 +0x1749
main.main()
        /home/runner/work/terraform/terraform/main.go:61 +0x19


### Debug Output

it is not recognized in it.

### Expected Behavior

Terraform init was to be executed

### Actual Behavior

terraform is getting crashed.

### Steps to Reproduce

'terraform init'

### Additional Context

I think terraform installation failure.

### References

_No response_

**Comment by kmoe** [comment]
Thanks for the bug report. Could you share your Terraform configuration (or any shorter configuration that also causes a crash) so we can reproduce the issue?

**Comment by lbhattvida** [comment]
Getting same error on on plan, needs a speedy resolution.

**Comment by jbardin** [comment]
@lbhattvida, that is a different stack trace, I suggest updating to the latest release to fix the issue.

**Comment by kmoe** [comment]
@lbhattvida This is a panic from a different part of the code, but we'd still appreciate a reproduction case. Please open a new issue with the configuration that causes this crash.

**Comment by crw** [comment]
I am cleaning up old issues. I am going to close this as it has not received a response to the previous comment. Thanks!
