### ISSUE TITLE
Getting error like Error: The terraform-provider-catchpoint_v0.2.1.exe plugin crashed!

### ISSUE THREAD

**Issue by vikashkuma** [hashicorp/terraform#33980]
### Terraform Version

```shell
1.5.7
```

### Terraform Configuration Files

```terraform
required_providers {
    catchpoint = {
      source = "catchpoint/catchpoint"
      version = "0.2.1"
    }
  }
```

### Debug Output

Stack trace from the terraform-provider-catchpoint_v0.2.1.exe plugin:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x9e504b]

goroutine 11 [running]:
catchpoint-provider/catchpoint.flattenTest(0x1214a200)
        catchpoint-provider/catchpoint/flatten_all_test_type.go:279 +0x193b
catchpoint-provider/catchpoint.resourceTestRead(0x12209090, {0xc485e0, 0x124091d0})
        catchpoint-provider/catchpoint/resource_web_test_type.go:1055 +0x2ab
catchpoint-provider/catchpoint.resourceTestCreate(0x12209090, {0xc485e0, 0x124091d0})
        catchpoint-provider/catchpoint/resource_web_test_type.go:1030 +0x1fdd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x123b8460, {0xe57df8, 0x1208a3f0}, 0x12209090, {0xc485e0, 0x124091d0})      
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:695 +0x166
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x123b8460, {0xe57df8, 0x1208a3f0}, 0x1203ad20, 0x12208000, {0xc485e0, 0x124091d0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:837 +0xa92
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1228f2f0, {0xe57d98, 0x121de510}, 0x121de540)       
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/grpc_provider.go:1021 +0xfa4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x122f6870, {0xe57df8, 0x1208a108}, 0x124fe140)
        github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:812 +0x540
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd1c780, 0x122f6870}, {0xe57df8, 0x1208a108}, 0x121de090, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x12392120, {0xe596a0, 0x122a6300}, 0x121e20a0, 0x12287e90, 0x12af620, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1283 +0xc37
google.golang.org/grpc.(*Server).handleStream(0x12392120, {0xe596a0, 0x122a6300}, 0x121e20a0, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1620 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.46.0/server.go:922 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.46.0/server.go:920 +0x25f

Error: The terraform-provider-catchpoint_v0.2.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

it should not throw invalid memory error and plugin crashed related error

### Actual Behavior

getting two errors 
panic: runtime error: invalid memory address or nil pointer dereference error in terraform
Error: The terraform-provider-catchpoint_v0.2.1.exe plugin crashed!

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by crw** [comment]
Hi @vikashkuma, this appears to be a bug in the `catchpoint` provider. Please see https://registry.terraform.io/providers/catchpoint/catchpoint/latest for more information about this provider, including how to file an issue. Please file this issue with that provider, so that the provider's maintainers can triage the problem. Thanks for the report!
