### ISSUE TITLE
terraform crash

### ISSUE THREAD

**Issue by rbtcollins** [hashicorp/terraform#34041]
### Terraform Version

```shell
1.5.3
```

### Terraform Configuration Files

I can't tell whats relevant, and our configuration is uhm, sizeable. Also internal.

### Debug Output

.

### Expected Behavior

Terraform should not have crashed.

### Actual Behavior

```
running "/atlantis/bin/terraform1.5.3 init -input=false -upgrade" in "/atlantis/repos/cognitedata/terraform/8272/default/cdf/greenfield": exit status 11

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.20.0/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.20.0/x64/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x153
panic({0x242c520, 0x41dc420})
	/opt/hostedtoolcache/go/1.20.0/x64/src/runtime/panic.go:890 +0x263
github.com/hashicorp/terraform/internal/addrs.(*MoveEndpoint).String(...)
	/home/runner/work/terraform/terraform/internal/addrs/move_endpoint.go:54
github.com/hashicorp/terraform/internal/configs.(*Module).appendFile(0xc000b01d40, 0xc000164c00)
	/home/runner/work/terraform/terraform/internal/configs/module.go:443 +0x3dd8
github.com/hashicorp/terraform/internal/configs.NewModule({0xc00013e3e0, 0x4, 0x0?}, {0x0, 0x0, 0x122f616?})
	/home/runner/work/terraform/terraform/internal/configs/module.go:154 +0x475
github.com/hashicorp/terraform/internal/configs.(*Parser).LoadConfigDir(0xc000154000?, {0x2db13b8, 0x1})
	/home/runner/work/terraform/terraform/internal/configs/parser_config_dir.go:45 +0x265
github.com/hashicorp/terraform/internal/command.(*Meta).loadSingleModule(0xc000064234?, {0xc000064234?, 0xc0001541a4?})
	/home/runner/work/terraform/terraform/internal/command/meta_config.go:71 +0x9b
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc000154000, {0xc0000500a0, 0x2, 0x2})
	/home/runner/work/terraform/terraform/internal/command/init.go:161 +0xe8b
github.com/mitchellh/cli.(*CLI).Run(0xc00013c280)
	/home/runner/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5f8
main.realMain()
	/home/runner/work/terraform/terraform/main.go:318 +0x1729
main.main()
	/home/runner/work/terraform/terraform/main.go:61 +0x19

```

### Steps to Reproduce

terraform1.5.3 init -input=false -upgrade

**Comment by jbardin** [comment]
Hi @rbtcollins,

Thanks for filing the issue! Can you verify that the crash still happens in a current release version, to make sure it hasn't already been patched? I'm not sure what would trigger this yet, but my first guess us that there is a moved block with an invalid `to` or `from` address that somehow slips through.

Thanks!

**Comment by rbtcollins** [comment]
```
running "/atlantis/bin/terraform1.6.1 init -input=false -upgrade" in "/atlantis/repos/....": exit status 11

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x13
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x13b
panic({0x2cd7d40?, 0x50ab790?})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x270
github.com/hashicorp/terraform/internal/addrs.(*MoveEndpoint).String(...)
	/home/runner/work/terraform/terraform/internal/addrs/move_endpoint.go:54
github.com/hashicorp/terraform/internal/configs.(*Module).appendFile(0xc0005771e0, 0xc000574180)
	/home/runner/work/terraform/terraform/internal/configs/module.go:456 +0x3d75
github.com/hashicorp/terraform/internal/configs.NewModule({0xc0002e1f00, 0x5, 0x1?}, {0x0, 0x0, 0x1?})
	/home/runner/work/terraform/terraform/internal/configs/module.go:167 +0x4d5
github.com/hashicorp/terraform/internal/configs.NewModuleWithTests(...)
	/home/runner/work/terraform/terraform/internal/configs/module.go:100
github.com/hashicorp/terraform/internal/configs.(*Parser).LoadConfigDirWithTests(0xc000996e00?, {0x38bf420, 0x1}, {0x317b3ae?, 0x41?})
	/home/runner/work/terraform/terraform/internal/configs/parser_config_dir.go:73 +0x3a5
github.com/hashicorp/terraform/internal/command.(*Meta).loadSingleModuleWithTests(0xc000062234?, {0xc000062234?, 0xc0009a9c20?}, {0x317b3ae, 0x5})
	/home/runner/work/terraform/terraform/internal/command/meta_config.go:108 +0xac
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc000996e00, {0xc0000500a0, 0x2, 0x2})
	/home/runner/work/terraform/terraform/internal/command/init.go:176 +0x125a
github.com/mitchellh/cli.(*CLI).Run(0xc0002fc3c0)
	/home/runner/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5b8
main.realMain()
	/home/runner/work/terraform/terraform/main.go:339 +0x1eab
main.main()
	/home/runner/work/terraform/terraform/main.go:64 +0x13
```

**Comment by rbtcollins** [comment]
Yes, I have a move block. I'm refactoring a configuration from:

root module 
+- childone
+- childtwo

to 
root module
+ unify
  + childone with count=0/1 conditional
  + childtwo

in order to remove highly duplicated code in our fleet - we have many root modules that are 99% identical code (providers, marshalling outputs of childone to childtwo).


```
moved {
  from = "module.childone"
  to   = "module.unify.module.childone[0]"
}
moved {
  from = "module.childtwo"
  to   = "module.unify.module.childtwo"
}
```

**Comment by rbtcollins** [comment]
Just finding my way at the moment,

```
=> 421:         m.Moved = append(m.Moved, file.Moved...)
   422:
   423:         for _, i := range file.Import {
   424:                 for _, mi := range m.Import {
   425:                         if i.To.Equal(mi.To) {
   426:                                 diags = append(diags, &hcl.Diagnostic{
(dlv) p file.Moved
[]*github.com/hashicorp/terraform/internal/configs.Moved len: 2, cap: 2, [
        *{
                From: *github.com/hashicorp/terraform/internal/addrs.MoveEndpoint nil,
                To: *github.com/hashicorp/terraform/internal/addrs.MoveEndpoint nil,
                DeclRange: (*"github.com/hashicorp/hcl/v2.Range")(0xc0000c3230),},
        *{
                From: *github.com/hashicorp/terraform/internal/addrs.MoveEndpoint nil,
                To: *github.com/hashicorp/terraform/internal/addrs.MoveEndpoint nil,
                DeclRange: (*"github.com/hashicorp/hcl/v2.Range")(0xc0000c3280),},
]
```

This seems very wrong - it is as far as I can tell the right file - it has the module invocation in it; the code looks like that in my previous comment, but has endpoint values of nil

**Comment by rbtcollins** [comment]
The problem was the quotation marks around the resource addresses. Removing them prevented the crash. I can't offer a patch - nothing ideological, just the overheads of a CLA for a one-off don't add up; I would suggest that both the parser extracting addresses and the appendFile method that is consuming the slice of Moved's should be validating the datastructure's basic properies. E.g. pre conditions or other such assertions (since golang doesn't permit encoding this in the type system).

**Comment by jbardin** [comment]
No worries @rbtcollins, thanks for adding the configuration example!

**Comment by kiweezi** [comment]
Can confirm this still is a bug in v1.8.0.

## Terraform Version

```
Terraform v1.8.0
on linux_amd64
```

## Terraform Configuration Files

```terraform
# main.tf
resource "azurerm_resource_group" "common" {
  name     = "rg-common"
  location = "eastus"
}

moved {
  from = azurerm_resource_group.common
  # there is no sub-module "bar"
  to     = module.bar.azurerm_resource_group.common
}

# foo/main.tf
resource "azurerm_resource_group" "common" {
  name     = "rg-common"
  location = "eastus"
}
```

## Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

panic: runtime error: invalid memory address or nil pointer dereference
goroutine 3042 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.22.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/runner/work/terraform/terraform/internal/logging/panic.go:84 +0x18b
panic({0x2f6ff80?, 0x577c150?})
        /opt/hostedtoolcache/go/1.22.1/x64/src/runtime/panic.go:770 +0x132
github.com/hashicorp/terraform/internal/refactoring.findMoveStatements(0xc000b4a000, {0x0?, 0xc002c05700?, 0x10?})
        /home/runner/work/terraform/terraform/internal/refactoring/move_statement.go:73 +0x387
github.com/hashicorp/terraform/internal/refactoring.findMoveStatements(0xc0002249a0, {0x0?, 0xc003f103f0?, 0xc0030bfac0?})
        /home/runner/work/terraform/terraform/internal/refactoring/move_statement.go:96 +0x5f7
github.com/hashicorp/terraform/internal/refactoring.FindMoveStatements(...)
        /home/runner/work/terraform/terraform/internal/refactoring/move_statement.go:45
github.com/hashicorp/terraform/internal/terraform.(*Context).prePlanFindAndApplyMoves(0xc001644280, 0xc0002249a0, 0xc003f10c78)
        /home/runner/work/terraform/terraform/internal/terraform/context_plan.go:508 +0x3f
github.com/hashicorp/terraform/internal/terraform.(*Context).planWalk(0xc001644280, 0xc0002249a0, 0xc000a85e18, 0xc0001cbb90)
        /home/runner/work/terraform/terraform/internal/terraform/context_plan.go:632 +0x11b
github.com/hashicorp/terraform/internal/terraform.(*Context).plan(0x0?, 0x0?, 0x0?, 0xc002c05e10?)
        /home/runner/work/terraform/terraform/internal/terraform/context_plan.go:372 +0x1c
github.com/hashicorp/terraform/internal/terraform.(*Context).PlanAndEval(0xc001644280, 0xc0002249a0, 0xc000a85e18, 0xc0001cbb90)
        /home/runner/work/terraform/terraform/internal/terraform/context_plan.go:247 +0x837
github.com/hashicorp/terraform/internal/terraform.(*Context).Plan(...)
        /home/runner/work/terraform/terraform/internal/terraform/context_plan.go:140
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan.func2()
        /home/runner/work/terraform/terraform/internal/backend/local/backend_plan.go:108 +0xe9
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan in goroutine 9
        /home/runner/work/terraform/terraform/internal/backend/local/backend_plan.go:104 +0x7b7
ERRO[0002] terraform invocation failed in /workspaces/iac/environments/terraform 
ERRO[0002] 1 error occurred:
        * [/workspaces/iac/environments/terraform] exit status 11
```

## Expected Behavior

Fail, then print an error message like: `the resource path to move to did not exist`.

## Actual Behavior

Terraform panic.

## Steps to Reproduce

1. Add a resource `a` to your terraform configuration
2. Add a module with an identical resource `b` in there too
3. Add a moved block at the root after resource `a`
4. Populate the moved block `from` to point at the resource `a`
5. Populate the moved block `to` field with a path that does not exist, such as a sub module which does not exist
6. Run `terraform plan`

## Additional Context

The debug output is from our much larger internal project, rather than the example.

**Comment by jbardin** [comment]
Hi @kiweezi,

This issue is about incorrectly quoted arguments, which are not present in your configuration. The fact that module doesn't exist, along with the matching stack trace indicate that the problem was the same as issue #34995.

Thanks!

**Comment by kiweezi** [comment]
Hey @jbardin sorry for getting that mixed up!
I'll remove the comment :).

**Comment by MunemHashmi** [comment]
**Proposed solution for the nil pointer panic:**

After investigating the crash, the root cause is in `decodeMovedBlock` (`internal/configs/moved.go`). When a `moved` block contains invalid addresses (quoted strings like `"module.foo"` or unqualified names like `bar`), `hcl.AbsTraversalForExpr` or `addrs.ParseMoveEndpoint` fails and the `From`/`To` fields remain `nil`. However, `decodeMovedBlock` still returns the incomplete `Moved` struct. This struct propagates through to `findMoveStatements` (`internal/refactoring/move_statement.go`), which calls methods on the nil `From`/`To` fields, causing the panic.

**The fix:** Return `nil` early from `decodeMovedBlock` when `diags.HasErrors()`. The diagnostic errors for the invalid addresses are already produced by the HCL parser — the user sees clear error messages like "Invalid expression" or "Invalid address". Returning `nil` simply prevents the incomplete struct from entering the module config, which is consistent with how other decoders in the codebase handle errors (e.g. `decodeRemovedBlock`, `decodeResourceBlock`, etc. all have early `return nil, diags` paths).

No additional error surfacing is needed because the existing diagnostics already tell the user exactly what's wrong. The caller in `parser_config.go` already checks `if cfg != nil` before appending, so this is a one-line change in the decoder.

PR: #38235

Happy to adjust the approach based on your feedback.

**Comment by radeksimko** [comment]
Whilst I could reproduce this with the mentioned version 1.5.3 and 1.6.x, I believe this was fixed in v1.7.0 and therefore I'm going to close this. I cannot pinpoint the specific fix from the [Changelog](https://github.com/hashicorp/terraform/releases/tag/v1.7.0) but the issue is no longer reproducible with that version (nor the latest version at the time of writing).

```hcl
terraform {
  required_providers {
    null = {
      source = "hashicorp/null"
    }
  }
}

moved {
  to = null_resource.foo
  from = "null_resource.bar"
}

import {
  id = ""
  to = null_resource.foo
}
```

```
$ terraform version && terraform init
```
```
Terraform v1.7.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/http v3.5.0

Your version of Terraform is out of date! The latest version
is 1.14.7. You can update by downloading from https://www.terraform.io/downloads.html

Initializing the backend...
Terraform encountered problems during initialisation, including problems
with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Invalid expression
│
│   on main.tf line 11, in moved:
│   11:   from = "null_resource.bar"
│
│ A single static variable reference is required: only attribute access and indexing with constant keys. No calculations, function calls,
│ template expressions, etc are allowed here.
╵

╷
│ Error: Invalid expression
│
│   on main.tf line 11, in moved:
│   11:   from = "null_resource.bar"
│
│ A single static variable reference is required: only attribute access and indexing with constant keys. No calculations, function calls,
│ template expressions, etc are allowed here.
╵
```

The diagnostic duplication bug was also addressed in later versions.
