### ISSUE TITLE
Upgrading from v0.13.7 to 0.14.11

### ISSUE THREAD

**Issue by tipirnenichowdary** [hashicorp/terraform#34171]
### Terraform Version

```shell
0.14.11
```

### Terraform Configuration Files

```terraform
Cannot provide config files
```

### Debug Output

panic: value is marked, so must be unmarked first

goroutine 21444 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.0/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.LengthInt(0x2cebc40, 0xc012e04980, 0x25b4900, 0xc00654ea00, 0xc005085400)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.0/cty/value_ops.go:1045 +0x4f
github.com/hashicorp/terraform/plans/objchange.proposedNewObject(0xc0017a8c60, 0x2cebc00, 0xc00e63fe00, 0x248e380, 0x3e01300, 0x2cebc00, 0xc012e04990, 0x24bc420, 0xc014f83d70, 0x82, ...)
	/home/circleci/project/project/plans/objchange/objchange.go:241 +0x18a5
github.com/hashicorp/terraform/plans/objchange.PlannedDataResourceObject(0xc0017a8c60, 0x2cebc00, 0xc012e04990, 0x24bc420, 0xc014f83d70, 0x1, 0x0, 0x0, 0x0)
	/home/circleci/project/project/plans/objchange/objchange.go:64 +0x89
github.com/hashicorp/terraform/terraform.(*evalReadDataPlan).Eval(0xc0087b7a90, 0x2d278e0, 0xc00fdaa1a0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/eval_read_data_plan.go:70 +0x952
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).dataResourceExecute(0xc0123921f0, 0x2d278e0, 0xc00fdaa1a0, 0x0, 0x380000)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:87 +0x4b4
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).Execute(0xc0123921f0, 0x2d278e0, 0xc00fdaa1a0, 0xc00e808002, 0x250b240, 0x2825d00)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:41 +0x11f
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc017700680, 0x2d278e0, 0xc00fdaa1a0, 0x7fb952edc450, 0xc0123921f0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbc
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2825d00, 0xc0123921f0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:59 +0x962
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc004bd60c0, 0x2825d00, 0xc0123921f0, 0xc00e65fac0)
	/home/circleci/project/project/dag/walk.go:387 +0x375
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:309 +0x1246

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Failed running command "cd '/terraform' && envdir /env terraform show -json /terraform/terraform.tfplan" (exit 1)
Output: Terraform couldn't read the given file as a state or plan file.
The errors while attempting to read the file as each format are
shown below.

State read error: Error loading statefile: open /terraform/terraform.tfplan: no such file or directory

Plan read error: open /terraform/terraform.tfplan: no such file or directory


### Expected Behavior

Apply should be completed successfully with v0.14.11

### Actual Behavior

Terraform crash

### Steps to Reproduce

terraform plan

### Additional Context

The upgrade worked successfully for multiple environments with any issue. Started seeing the crash failures out of nowhere. No code changes involved.

**Comment by apparentlymart** [comment]
Hi @tipirnenichowdary! I'm sorry this didn't work as expected.

The documented upgrade process includes an intermediate step of upgrading from v0.13 to v0.14 primarily because that extra step helps confirm that the v0.13 upgrade process was completed successfully before moving on. However, if you've already been successfully using Terraform v0.13 for some time you may be able to successfully skip the v0.14 series and upgrade directly to the latest v1.0.x release, which at the time of writing is v1.0.11.

Can you try that and see if it improves the situation? I'm hoping that the bug you encountered was fixed in a later release.

If you are able to successfully upgrade to v1.0.11 then from there you should be able to upgrade to the very latest v1.x minor release, since everything in that major series is subject to [compatibility promises](https://developer.hashicorp.com/terraform/language/v1-compatibility-promises). (There are some pragmatic exceptions, but they are only rarely relevant.)

The v0.14 series is well past its period of routine maintenance now, so it's unlikely to see any new releases unless they are for very significant security reasons, or similar. So I think we will need to find a way to get you past this error despite the bug, rather than fixing the bug. (And as noted above, I hope it's already been fixed in a later release anyway.)

**Comment by tipirnenichowdary** [comment]
Thank you @apparentlymart. I will upgrade directly to 1.0.11
