### ISSUE TITLE
Crash when generating configuration for an imported object that has sensitive attributes

### ISSUE THREAD

**Issue by maos999** [hashicorp/terraform#34992]
### Terraform Version

```shell
1.8.0
```

### Terraform Configuration Files

```terraform
terraform {
    required_version = ">= 1.8.0"
    required_providers {
      azurerm = {
        source  = "hashicorp/azurerm"
        version = ">=3.99.0"
      }
  }
}

provider "azurerm" {
  skip_provider_registration = true
  features {
    
  }
}

import {
  to = azurerm_windows_function_app.demo-func-app
  id = "/subscriptions/xxxxxxxx/resourceGroups/demo-func-rg/providers/Microsoft.Web/sites/demo-func-mt"
}

#terraform plan '-generate-config-out=generated_resources.tf'
```

### Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

panic: value is marked, so must be unmarked first
goroutine 75 [running]:
runtime/debug.Stack()
        /Users/runner/hostedtoolcache/go/1.22.1/x64/src/runtime/debug/stack.go:24 +0x64
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /Users/runner/work/terraform/terraform/internal/logging/panic.go:84 +0x198
panic({0x10378cb40?, 0x103e31460?})
        /Users/runner/hostedtoolcache/go/1.22.1/x64/src/runtime/panic.go:770 +0x124
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
        /Users/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.3/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.ElementIterator({{{0x103e74108?, 0x14000818f40?}}, {0x103a60180?, 0x14001854fd8?}})
        /Users/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.3/cty/value_ops.go:1191 +0x54
github.com/hashicorp/terraform/internal/genconfig.omitUnknowns({{{0x103e74108, 0x14000818f40}}, {0x103a60180, 0x14001854fd8}})
        /Users/runner/work/terraform/terraform/internal/genconfig/generate_config.go:589 +0xd8
github.com/hashicorp/terraform/internal/genconfig.omitUnknowns({{{0x103e73ff0, 0x140009807c0}}, {0x1038c65c0, 0x14001ec0e70}})
        /Users/runner/work/terraform/terraform/internal/genconfig/generate_config.go:611 +0x20c
github.com/hashicorp/terraform/internal/genconfig.GenerateResourceContents({{}, {0x1059345e0, 0x0, 0x0}, {{}, {{}, 0x4d, {0x140001103a0, 0x1c}, {0x14000b981e0, ...}}, ...}}, ...)
        /Users/runner/work/terraform/terraform/internal/genconfig/generate_config.go:41 +0x38c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).generateHCLStringAttributes(0x14000502e70, {{}, {0x1059345e0, 0x0, 0x0}, {{}, {{}, 0x4d, {0x140001103a0, 0x1c}, ...}, ...}}, ...)
        /Users/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:688 +0x154
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).importState(0x14000502e70, {0x103e93c68, 0x140005585a0}, {{}, {0x1059345e0, 0x0, 0x0}, {{}, {{}, 0x4d, ...}, ...}}, ...)
        /Users/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:624 +0x10c4
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0x14000502e70, {0x103e93c68, 0x140005585a0})
        /Users/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:169 +0x3d0
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x18?, {0x103e93c68?, 0x140005585a0?}, 0xb8?)
        /Users/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:75 +0x7c
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x14001460280, {0x103e93c68, 0x140005585a0}, {0x12d3310b8, 0x14000502e70})
        /Users/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:153 +0xa8
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x103df9560, 0x14000502e70})
        /Users/runner/work/terraform/terraform/internal/terraform/graph.go:112 +0x478
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x1400158de60, {0x103df9560, 0x14000502e70}, 0x140015d6b00)
        /Users/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2a8
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 63
        /Users/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xc30
```

### Expected Behavior

.

### Actual Behavior

.

### Steps to Reproduce

.

**Comment by liamcervante** [comment]
This actually worked previously because of another bug in Terraform that was fixed in https://github.com/hashicorp/terraform/pull/34567. Previously, we weren't properly assigning the sensitive marks from the schema within the plan and instead letting the renderer work out the sensitive status later in the process. With the linked PR we started applying the sensitive marks within the planning graph. Now, when it comes time to generate the config we are not properly handling the sensitive status of certain attributes.

The code that is triggering the crash is checking for unknown values within the imported data. There shouldn't actually be any unknown data returned by the provider and we have started enforcing that with the following PR: https://github.com/hashicorp/terraform/pull/34525.

I think the fix here is to ensure the same check from #34525 is made within the import execution path, and then remove the check we have for unknown values within the generate config function.
