### ISSUE TITLE
ServiceEndpoint resource crashing - terraform-provider-azuredevops_v1.1.1 plugin crashed!

### ISSUE THREAD

**Issue by ankurkapoor** [hashicorp/terraform#35413]
### Terraform Version

```shell
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xcd5cd6]

goroutine 43 [running]:
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.resourceServiceEndpointKubernetesRead(0x0?, {0xd85520?, 0xc000548780})
	github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_kubernetes.go:219 +0xb6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x10c8ca0?, {0x10c8ca0?, 0xc000129320?}, 0xd?, {0xd85520?, 0xc000548780?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003ca7e0, {0x10c8ca0, 0xc000129320}, 0xc00009d6c0, {0xd85520, 0xc000548780})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000386d80, {0x10c8ca0?, 0xc000129200?}, 0xc000743440)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00033b0e0, {0x10c8ca0?, 0xc000128c30?}, 0xc00042c420)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xf0bae0?, 0xc00033b0e0}, {0x10c8ca0, 0xc000128c30}, 0xc00023c4d0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000003c0, {0x10cba40, 0xc0003fda00}, 0xc00049ed80, 0xc0004181b0, 0x166b610, 0x0)
	google.golang.org/grpc@v1.56.3/server.go:1335 +0xde3
google.golang.org/grpc.(*Server).handleStream(0xc0000003c0, {0x10cba40, 0xc0003fda00}, 0xc00049ed80, 0x0)
	google.golang.org/grpc@v1.56.3/server.go:1712 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.3/server.go:947 +0xca
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.56.3/server.go:958 +0x15c

Error: The terraform-provider-azuredevops_v1.1.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

##[warning]Can't find loc string for key: TerraformPlanFailed
##[error]Error: TerraformPlanFailed 1
```

### Terraform Configuration Files

```
data "azuredevops_project" "ado_project" {
  name = "Test"
}

######### Kubernetes endpoint #########
#Setup Service Endpoint for Private Kubernetes Cluster
resource "azuredevops_serviceendpoint_kubernetes" "kubernetes" {
  project_id            = data.azuredevops_project.ado_project.id
  service_endpoint_name = "ServiceConnection-Kubernetes-${var.environment}"
  apiserver_url         = "https://${azurerm_kubernetes_cluster.aks.fqdn}"
  authorization_type    = "Kubeconfig"
  kubeconfig {
    kube_config = azurerm_kubernetes_cluster.aks.kube_config_raw
  }
}

resource "azuredevops_pipeline_authorization" "kubernetes" {
  project_id  = data.azuredevops_project.ado_project.id
  resource_id = azuredevops_serviceendpoint_kubernetes.kubernetes.id
  type        = "endpoint"
}

```

### Debug Output

No debug output available since its part of Azure pipeline run.

### Expected Behavior

The plan should be able to generate a clean destroy or build plan. Currently its failing in both scenarios.

# module.aks.azuredevops_serviceendpoint_kubernetes.kubernetes will be destroyed
  - resource "azuredevops_serviceendpoint_kubernetes" "kubernetes" {
      - apiserver_url         = "https://cccc-aks-qhduia9e.hcp.uksouth.azmk8s.io"/ -> ***
      - authorization         = {
          - "scheme" = "Kubernetes"
        } -> ***
      - authorization_type    = "Kubeconfig" -> ***
      - description           = "Managed by Terraform" -> ***
      - id                    = "f810249c-49bb-41b6-9e01-4ca7f60f10b2" -> ***
      - project_id            = "9d04ad56-c5de-4ac1-a0bf-bad2ee4ac506" -> ***
      - service_endpoint_name = "ServiceConnection-Kubernetes-XXXX" -> ***

      - kubeconfig {
          - accept_untrusted_certs = true -> ***
          - cluster_context        = "XXXX-aks" -> ***
          - kube_config            = (sensitive value) -> ***
        }
    }

### Actual Behavior

Its crashing with above output.

### Steps to Reproduce

1. **terraform init**
2. **terraform plan**

### Additional Context

We run the above code as part of a custom TF module that does creation of AKS cluster and then setup self hosted agent on ADO using service endpoint connection.

**Comment by apparentlymart** [comment]
Hi @ankurkapoor! Thanks for reporting this.

You've described a problem with the `microsoft/azuredevops` provider rather than with Terraform Core, so this isn't something we can address in this repository. Please report it in [the provider's own repository](https://github.com/microsoft/terraform-provider-azuredevops) instead. Thanks again!
