### ISSUE TITLE
`panic: attempt to iterate on non-collection, non-tuple type` during import with invalid `for_each`

### ISSUE THREAD

**Issue by mss** [hashicorp/terraform#35844]
### Terraform Version

```shell
Terraform v1.9.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.55.0
```

### Terraform Configuration Files

```terraform
variable "import_resources" {
  description = "Resources to import"
  type        = map(string)
  nullable    = false
  default     = {}
}

import {
  for_each = var.import_resources["account_alias"]
  #for_each = compact([lookup(var.import_resources, "account_alias", null)])

  id = each.value
  to = module.global.aws_iam_account_alias.this
}
```

### Debug Output

https://gist.github.com/mss/39411fbaded35cdec1a35868a94649cd

```
panic: attempt to iterate on non-collection, non-tuple type
2024-10-11T18:57:17.557+0200 [TRACE] Completed graph transform *terraform.OrphanResourceInstanceCountTransformer (no changes)
2024-10-11T18:57:17.557+0200 [TRACE] Executing graph transform *terraform.AttachStateTransformer
2024-10-11T18:57:17.557+0200 [TRACE] vertex "module.global.module.iam.data.aws_caller_identity.this": starting visit (*terraform.NodePlannableResourceInstance)
2024-10-11T18:57:17.557+0200 [TRACE] NodeAbstractResourceInstance.AttachResourceState for module.global.aws_ec2_serial_console_access.this
2024-10-11T18:57:17.557+0200 [TRACE] Completed graph transform *terraform.AttachStateTransformer (no changes)
2024-10-11T18:57:17.557+0200 [TRACE] Executing graph transform *terraform.TargetsTransformer
2024-10-11T18:57:17.557+0200 [TRACE] vertex "module.global.module.iam.data.aws_caller_identity.this": belongs to module.global.module.iam
2024-10-11T18:57:17.557+0200 [TRACE] Completed graph transform *terraform.TargetsTransformer (no changes)
2024-10-11T18:57:17.557+0200 [TRACE] Executing graph transform *terraform.ReferenceTransformer
2024-10-11T18:57:17.557+0200 [TRACE] terraform.contextPlugins: Schema for provider "registry.terraform.io/hashicorp/aws" is in the global cache
2024-10-11T18:57:17.557+0200 [DEBUG] ReferenceTransformer: "module.global.aws_ec2_serial_console_access.this" references: []
2024-10-11T18:57:17.557+0200 [TRACE] Completed graph transform *terraform.ReferenceTransformer (no changes)
2024-10-11T18:57:17.557+0200 [TRACE] Executing graph transform *terraform.RootTransformer
2024-10-11T18:57:17.557+0200 [TRACE] terraform.contextPlugins: Schema for provider "registry.terraform.io/hashicorp/aws" is in the global cache
2024-10-11T18:57:17.557+0200 [TRACE] Completed graph transform *terraform.RootTransformer with new graph:
  module.global.aws_ec2_serial_console_access.this - *terraform.NodePlannableResourceInstance
  root - terraform.graphNodeRoot
    module.global.aws_ec2_serial_console_access.this - *terraform.NodePlannableResourceInstance
  ------
goroutine 921 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	github.com/hashicorp/terraform/internal/logging/panic.go:84 +0x18b
panic({0x2e7a540?, 0x3dd6950?})
	runtime/panic.go:770 +0x132
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1.1()
	github.com/hashicorp/terraform/internal/terraform/graph.go:59 +0x4c5
panic({0x2e7a540?, 0x3dd6950?})
	runtime/panic.go:770 +0x132
github.com/zclconf/go-cty/cty.elementIterator({{{0x3e192c8?, 0xc000137909?}}, {0x2e7a540?, 0xc0007edbe0?}})
	github.com/zclconf/go-cty@v1.14.4/cty/element_iterator.go:97 +0x6c7
github.com/zclconf/go-cty/cty.Value.ElementIterator({{{0x3e192c8?, 0xc000137909?}}, {0x2e7a540?, 0xc0007edbe0?}})
	github.com/zclconf/go-cty@v1.14.4/cty/value_ops.go:1198 +0xa5
github.com/hashicorp/terraform/internal/terraform.(*forEachEvaluator).ImportValues(0xc0038cb378)
	github.com/hashicorp/terraform/internal/terraform/eval_for_each.go:127 +0x3a5
github.com/hashicorp/terraform/internal/terraform.(*nodeExpandPlannableResource).expandResourceImports(0xc001b0b180, {0x3e3d608, 0xc0019a4780})
	github.com/hashicorp/terraform/internal/terraform/node_resource_plan.go:188 +0x209
github.com/hashicorp/terraform/internal/terraform.(*nodeExpandPlannableResource).DynamicExpand(0xc001b0b180, {0x3e3d608, 0xc0019a4780})
	github.com/hashicorp/terraform/internal/terraform/node_resource_plan.go:118 +0x3a5
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x34b2fc0, 0xc001b0b180})
	github.com/hashicorp/terraform/internal/terraform/graph.go:153 +0xa3c
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000cba120, {0x34b2fc0, 0xc001b0b180}, 0xc0029a20c0)
	github.com/hashicorp/terraform/internal/dag/walk.go:384 +0x2d7
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 721
	github.com/hashicorp/terraform/internal/dag/walk.go:307 +0xff3
```

### Expected Behavior

No crash

### Actual Behavior

It crashes

### Steps to Reproduce

1. `terraform plan`

### Additional Context

I just noticed that I have a syntax error in my code (`for_each` points to a string).

**Comment by liamcervante** [comment]
Hi @mss, thanks for filing this! I can replicate this in the v1.9.x series, but if I build from main or use the v1.10.x alpha releases then it seems to have been fixed. I think this is because we have prepared https://github.com/hashicorp/terraform/pull/35543 for release in v1.10.0.

@jbardin - I'm not sure if you think we should make an effort to backport these fixes into the v1.9 branch? I'm going to close this already fixed, but we can reopen if you think it is worth is.
