### ISSUE TITLE
Azure Terraform vpngw  Error: Plugin did not respond

### ISSUE THREAD

**Issue by ZDercsenyi** [hashicorp/terraform#36087]
### Terraform Version

```shell
Terraform v1.9.8
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v3.0.2
+ provider registry.terraform.io/hashicorp/azurerm v4.10.0
+ provider registry.terraform.io/hashicorp/random v3.6.3
```

### Terraform Configuration Files

resource "azurerm_virtual_network_gateway" "vpngw" {
  name                = var.vpngw-name
  location            = var.location
  resource_group_name = var.resourcegroup-name
  type     = "Vpn"
  vpn_type = "RouteBased"

  active_active = false
  enable_bgp    = false
  sku           =  var.vpngw-sku

  ip_configuration {
    name                          = "vnetGatewayConfig"
    public_ip_address_id          = var.public-ip-id
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = var.subnet-id
  }

  dynamic "custom_route" {
    for_each = length(var.custom-routes) > 0 ? [1]: []
    content {
      address_prefixes = var.custom-routes
    }
  }

vpn_client_configuration {
    address_space = [var.p2s-ip-range]
    aad_audience = var.aad-audience != "" ? var.aad-audience : null
    aad_issuer =  var.aad-issuer  != "" ? var.aad-issuer  : null
    aad_tenant = var.aad-tenant  != "" ? var.aad-tenant  : null
    vpn_auth_types = var.vpn-auth-types
    vpn_client_protocols = var.vpn-client-protocols
} 
}

output "vpn-gw-id" {
  value = azurerm_virtual_network_gateway.vpngw.id
}

### Debug Output

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.vpn-gateway.azurerm_virtual_network_gateway.vpngw: Creating...
╷
│ Error: Plugin did not respond
│
│   with module.vpn-gateway.azurerm_virtual_network_gateway.vpngw,
│   on ..\..\modules\Azure\azure-vnet-gateway\main.tf line 1, in resource "azurerm_virtual_network_gateway" "vpngw":
│    1: resource "azurerm_virtual_network_gateway" "vpngw" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v4.10.0_x5.exe plugin:

panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 117 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.expandVirtualNetworkGatewayVpnClientConfig(0xe70a1e0?, {{0xc001db2120, 0x24}, {0xc002e833c8, 0x13}, {0xc002e81900, 0x10}})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/network/virtual_network_gateway_resource.go:1094 +0x1ae5
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.getVirtualNetworkGatewayProperties({{0xc001db2120, 0x24}, {0xc002e833c8, 0x13}, {0xc002e81900, 0x10}}, 0xc002fdc380)
        github.com/hashicorp/terraform-provider-azurerm/internal/services/network/virtual_network_gateway_resource.go:933 +0x7bb
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.resourceVirtualNetworkGatewayCreate(0xc002fdc380, {0x76b3c00, 0xc001e91208})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/network/virtual_network_gateway_resource.go:673 +0x3fc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x8f7a9f8?, {0x8f7a9f8?, 0xc002fdeab0?}, 0xd?, {0x76b3c00?, 0xc001e91208?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:794 +0x15f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0017801c0, {0x8f7a9f8, 0xc002fdeab0}, 0xc001e4e8f0, 0xc002fdc200, {0x76b3c00, 0xc001e91208})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:937 +0xa89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000b92d68, {0x8f7a9f8?, 0xc002fde9f0?}, 0xc0001111d0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/grpc_provider.go:1155 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc000b14500, {0x8f7a9f8?, 0xc002fde720?}, 0xc0001111d0)
        github.com/hashicorp/terraform-plugin-mux@v0.17.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0019f86e0, {0x8f7a9f8?, 0xc002fc7ce0?}, 0xc0015a9180)
        github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/tf5server/server.go:865 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x845dc60, 0xc0019f86e0}, {0x8f7a9f8, 0xc002fc7ce0}, 0xc002e8d980, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:611 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001d0e00, {0x8f7a9f8, 0xc002fc7c50}, {0x8fa93a0, 0xc00165e820}, 0xc002fd2120, 0xc000dcb320, 0xe672f38, 0x0)
        google.golang.org/grpc@v1.67.1/server.go:1394 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc0001d0e00, {0x8fa93a0, 0xc00165e820}, 0xc002fd2120)
        google.golang.org/grpc@v1.67.1/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.67.1/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 26
        google.golang.org/grpc@v1.67.1/server.go:1040 +0x125

Error: The terraform-provider-azurerm_v4.10.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

VPN Gateway should be created successfully.

### Actual Behavior

Apply fails with error.

### Steps to Reproduce

terraform init
terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
