### ISSUE TITLE
Crash Report when applying a vsphere machine

### ISSUE THREAD

**Issue by ethankhall** [hashicorp/terraform#4302]
I was running terraform apply and had a crash.
## Output from consule before the crash

```
vsphere_virtual_machine.ldap: Creating...
  cluster:                         "" => "main"
  datacenter:                      "" => "home"
  disk.#:                          "" => "2"
  disk.0.datastore:                "" => "ssd1"
  disk.0.template:                 "" => "templates/centos71-v0.5.18"
  disk.1.datastore:                "" => "ssd1"
  disk.1.size:                     "" => "10"
  domain:                          "" => "int.ehdev.io"
  memory:                          "" => "768"
  name:                            "" => "infrastructure-ldap-1"
  network_interface.#:             "" => "2"
  network_interface.0.ip_address:  "" => "<computed>"
  network_interface.0.label:       "" => "Infa VM"
  network_interface.0.subnet_mask: "" => "<computed>"
  network_interface.1.ip_address:  "" => "<computed>"
  network_interface.1.label:       "" => "Infa VM"
  network_interface.1.subnet_mask: "" => "<computed>"
  time_zone:                       "" => "America/Los_Angeles"
  vcpu:                            "" => "1"
Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.ldap: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: interface conversion: interface is nil, not string
```
## Terraform Version

```
> terraform --version
Terraform v0.6.8
```
## Crash Log

[crash.txt](https://github.com/hashicorp/terraform/files/60756/crash.txt)

**Comment by ethankhall** [comment]
The issue happens when you have a network interface that doesn't have an IP address. Making the second NIC get an IP lets apply continue. This can happen if you use systemd-networkd and you don't have the catchall dhcp setup and only one nic get an IP.

**Comment by phinze** [comment]
Relevant snippet from the crash log:

```
2015/12/13 18:34:37 [DEBUG] terraform-provider-vsphere: panic: interface conversion: interface is nil, not string
2015/12/13 18:34:37 [DEBUG] terraform-provider-vsphere: 
2015/12/13 18:34:37 [DEBUG] terraform-provider-vsphere: goroutine 82 [running]:
2015/12/13 18:34:37 [DEBUG] terraform-provider-vsphere: github.com/hashicorp/terraform/builtin/providers/vsphere.resourceVSphereVirtualMachineRead(0xc8202e7980, 0xefc100, 0xc8203d7eb0, 0x0, 0x0)
2015/12/13 18:34:37 [DEBUG] terraform-provider-vsphere: 	/private/tmp/terraform20151202-21396-jm3im7/terraform-0.6.8/src/github.com/hashicorp/terraform/builtin/providers/vsphere/resource_vsphere_virtual_machine.go:427 +0x2121
2015/12/13 18:34:37 [DEBUG] terraform-provider-vsphere: github.com/hashicorp/terraform/builtin/providers/vsphere.resourceVSphereVirtualMachineCreate(0xc8202e7980, 0xefc100, 0xc8203d7eb0, 0x0, 0x0)
2015/12/13 18:34:37 [DEBUG] terraform-provider-vsphere: 	/private/tmp/terraform20151202-21396-jm3im7/terraform-0.6.8/src/github.com/hashicorp/terraform/builtin/providers/vsphere/resource_vsphere_virtual_machine.go:344 +0x1af3
```

**Comment by chrislovecnm** [comment]
We are currently rewriting that block of code, because of another issue.https://github.com/hashicorp/terraform/issues/4112 - this is not a duplicate issue, but is in the exact same code blocks.

@tkak something else to consider.  I noticed that possible nil previously, and forgot to file an issue.

**Comment by chrislovecnm** [comment]
Will push this in a large PR that I am working on

**Comment by chrislovecnm** [comment]
Fixed in https://github.com/hashicorp/terraform/pull/7031 - when merged
