### ISSUE TITLE
terraform crash 

### ISSUE THREAD

**Issue by cloudeng** [hashicorp/terraform#4391]
empty policy terraform got crashed 

```hcl
resource "aws_sqs_queue" "test_queue" {
  name                       = "${var.sqs_name}"
  depends_on = ["aws_sns_topic.test_sns"]
 visibility_timeout_seconds = "${var.visibility_timeout}"
 message_retention_seconds  = "${var.retentiontimes}"
 max_message_size           = "${var.messagesize}"
 delay_seconds              = "${var.delay}"
 receive_wait_time_seconds  = "${var.waittime}"
  policy = <<EOF
  {
   
  }
 EOF
}
```

LOG : 

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/hcl/hcl/parser.(*Parser).objectItem(0xc8200f9018, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/hcl/hcl/parser/parser.go:154 +0x423
github.com/hashicorp/hcl/hcl/parser.(*Parser).objectList(0xc8200f9018, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/hcl/hcl/parser/parser.go:69 +0xc1
github.com/hashicorp/hcl/hcl/parser.(*Parser).objectType(0xc8200f9018, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/hcl/hcl/parser/parser.go:241 +0xf1
github.com/hashicorp/hcl/hcl/parser.(*Parser).objectItem(0xc8200f9018, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/hcl/hcl/parser/parser.go:146 +0x1fc
github.com/hashicorp/hcl/hcl/parser.(*Parser).objectList(0xc8200f9018, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/hcl/hcl/parser/parser.go:69 +0xc1
github.com/hashicorp/hcl/hcl/parser.(*Parser).Parse(0xc8200f9018, 0xc8200b32b0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/hcl/hcl/parser/parser.go:52 +0x100
github.com/hashicorp/hcl/hcl/parser.Parse(0xc820105880, 0x36e, 0x380, 0xc820105880, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/hcl/hcl/parser/parser.go:39 +0x185
github.com/hashicorp/hcl.Parse(0xc820105500, 0x36e, 0x36e, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/hcl/parse.go:17 +0x89
github.com/hashicorp/terraform/config.loadFileHcl(0xc820178680, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/loader_hcl.go:155 +0x2d6
github.com/hashicorp/terraform/config.loadTree(0xc820178680, 0x34, 0xc8200f9418, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/import_tree.go:47 +0x313
github.com/hashicorp/terraform/config.LoadFile(0xc820178680, 0x34, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/loader.go:39 +0x3b
github.com/hashicorp/terraform/config.LoadDir(0xc82000a034, 0x2c, 0x10, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/loader.go:91 +0x38c
github.com/hashicorp/terraform/config/module.NewTreeModule(0x0, 0x0, 0xc82000a034, 0x2c, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:40 +0x41
github.com/hashicorp/terraform/command.(*Meta).Context(0xc8201600f0, 0xc82000a034, 0x2c, 0xf7bac0, 0x11, 0x0, 0xa, 0x4, 0x300000002, 0x0, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/command/meta.go:148 +0x509
github.com/hashicorp/terraform/command.(*PlanCommand).Run(0xc8201600f0, 0xc82000a290, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/command/plan.go:66 +0x80c
github.com/mitchellh/cli.(*CLI).Run(0xc820139a20, 0xc8201682a0, 0x0, 0x0)
        /opt/gopath/src/github.com/mitchellh/cli/cli.go:112 +0x655
main.wrappedMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:146 +0xb08
main.realMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:82 +0xa88
main.main()
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:18 +0x18

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [semacquire]:
sync.runtime_Syncsemacquire(0xc82010a340)
        /usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc82010a330)
        /usr/local/go/src/sync/cond.go:62 +0x9b
io.(*pipe).read(0xc82010a300, 0xc82016b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:52 +0x2d2
io.(*PipeReader).Read(0xc82002a168, 0xc82016b000, 0x1000, 0x1000, 0xc82001a898, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:134 +0x50
bufio.(*Scanner).Scan(0xc82007a980, 0x2)
        /usr/local/go/src/bufio/scan.go:180 +0x877
github.com/hashicorp/terraform/command.(*Meta).flagSet.func1(0xc82007a980, 0xc8201600f0)
        /opt/gopath/src/github.com/hashicorp/terraform/command/meta.go:323 +0x25
created by github.com/hashicorp/terraform/command.(*Meta).flagSet
        /opt/gopath/src/github.com/hashicorp/terraform/command/meta.go:326 +0x5d5



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by jen20** [comment]
Hi @cloudeng! Thanks for reporting this. Can you let me know what version of Terraform you are running here, and on which operating system? You can find the version of Terraform using the `terraform --version` command.

Since this is clearly a panic, I am keen to get to the bottom of it - as the error message says we treat all occurrences of panics as Terraform bugs. Running on the current master branch and the current release (0.6.8) on Mac OS X using the config copied from the issue, I get the following (correct) output:

**main.tf:**
```hcl
resource "aws_sqs_queue" "test_queue" {
  name                       = "${var.sqs_name}"
  depends_on = ["aws_sns_topic.test_sns"]
 visibility_timeout_seconds = "${var.visibility_timeout}"
 message_retention_seconds  = "${var.retentiontimes}"
 max_message_size           = "${var.messagesize}"
 delay_seconds              = "${var.delay}"
 receive_wait_time_seconds  = "${var.waittime}"
  policy = <<EOF
  {

  }
 EOF
}
```

**Output:**
```
$ terraform plan
Error loading config: Error parsing /Users/James/Code/terraform/emptypolicy/main.tf: At 15:1: heredoc not terminated
```

If I fix the indentation of the HEREDOC such that the terminating mark is the first character on the line, I get the following:

**main.tf:**
```hcl
resource "aws_sqs_queue" "test_queue" {
    name                       = "${var.sqs_name}"
    depends_on = ["aws_sns_topic.test_sns"]
    visibility_timeout_seconds = "${var.visibility_timeout}"
    message_retention_seconds  = "${var.retentiontimes}"
    max_message_size           = "${var.messagesize}"
    delay_seconds              = "${var.delay}"
    receive_wait_time_seconds  = "${var.waittime}"
    policy = <<EOF
    {

    }
EOF
}
```

**Output:**
```
$ terraform plan
Error configuring: 7 error(s) occurred:

* aws_sqs_queue.test_queue: missing dependency: aws_sns_topic.test_sns
* aws_sqs_queue.test_queue: missing dependency: var.visibility_timeout
* aws_sqs_queue.test_queue: missing dependency: var.retentiontimes
* aws_sqs_queue.test_queue: missing dependency: var.messagesize
* aws_sqs_queue.test_queue: missing dependency: var.delay
* aws_sqs_queue.test_queue: missing dependency: var.waittime
* aws_sqs_queue.test_queue: missing dependency: var.sqs_name
```

**Comment by cloudeng** [comment]
Hi @jen20 i am using Terraform v0.6.7

I am using  vagrant ubuntu/trusty64

**Comment by phinze** [comment]
Hi @cloudeng - this should be fixed in the latest version of Terraform! Feel free to follow up if you also see this error with Terraform v0.6.8. :+1:
