### ISSUE TITLE
Panic if no account credentials are available in ARM

### ISSUE THREAD

**Issue by jen20** [hashicorp/terraform#4697]
Registering the provider types needs to happen after the credentials check: if no credentials are available via environment variables or directly, a panic such as this occurs:

```
$ terraform plan
Refreshing Terraform state prior to plan...

Error refreshing state: 1 error(s) occurred:

* unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
2016/01/16 08:36:14 [DEBUG] terraform-provider-azurerm: [signal 0xb code=0x1 addr=0x10 pc=0x1ba5c7]
2016/01/16 08:36:14 [DEBUG] terraform-provider-azurerm:
2016/01/16 08:36:14 [DEBUG] terraform-provider-azurerm: goroutine 58 [running]:
2016/01/16 08:36:14 [DEBUG] terraform-provider-azurerm: github.com/Azure/azure-sdk-for-go/arm/resources/resources.ProvidersClient.Register(0x10d2270, 0xc820210240, 0x10d2298, 0xc8201dfe40, 0x0, 0x0, 0x9442e0, 0x13, 0x0, 0xd18c2e2800, ...)
2016/01/16 08:36:14 [DEBUG] terraform-provider-azurerm: 	/Users/James/Code/go/src/github.com/Azure/azure-sdk-for-go/arm/resources/resources/providers.go:206 +0x217
2016/01/16 08:36:14 [DEBUG] terraform-provider-azurerm: github.com/hashicorp/terraform/builtin/providers/azurerm.registerAzureResourceProvidersWithSubscription(0xc820204280, 0xc820258000, 0x0, 0x0)
2016/01/16 08:36:14 [DEBUG] terraform-provider-azurerm: 	/Users/James/Code/go/src/github.com/hashicorp/terraform/builtin/providers/azurerm/provider.go:101 +0x152
```

**Comment by catsby** [comment]
#4902 was merged, think I'll close this...
