### ISSUE TITLE
Terraform Crash version v0.6.9

### ISSUE THREAD

**Issue by achalupa74** [hashicorp/terraform#4915]
I managed to get a terraform crash during a 'terraform apply' run:

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
[jenkins-slave@bosbld-man dev]$ ls
crash.log  dev.tf  terraform.tfstate  terraform.tfstate.backup
[jenkins-slave@bosbld-man dev]$ terraform -version
Terraform v0.6.9

Your version of Terraform is out of date! The latest version
is 0.6.10. You can update by downloading from www.terraform.io
[jenkins-slave@bosbld-man dev]$

Attached is the crash log.

**Comment by jen20** [comment]
Thanks for opening the issue @achalupa74 - we'll get this resolved.

Relevant section of the crash log:

```
2016/01/30 11:46:32 [DEBUG] terraform-provider-aws: panic: runtime error: invalid memory address or nil pointer dereference
2016/01/30 11:46:32 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x5829b3]
2016/01/30 11:46:32 [DEBUG] terraform-provider-aws: 
2016/01/30 11:46:32 [DEBUG] terraform-provider-aws: goroutine 1597 [running]:
2016/01/30 11:46:32 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.routeIDHash(0xc8237674a0, 0x0, 0x0, 0x0)
2016/01/30 11:46:32 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route.go:303 +0xa3
2016/01/30 11:46:32 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsRouteCreate(0xc8237674a0, 0xcedda0, 0xc821f22b40, 0x0, 0x0)
2016/01/30 11:46:32 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route.go:161 +0x9bd
```

**Comment by catsby** [comment]
Thanks for opening this @achalupa74 – you don't by chance have a sample configuration file (minus any secrets) that demonstrates this, do you?

**Comment by achalupa74** [comment]
Thanks for the responses guys.  I'm willing to share my scripts.  I've stripped out any passwords or AWS keys.  Warning there are several modules in this package.  I've only seen the crash twice so for (most recently this afternoon).  Attached is my set of scripts.

To run the scripts CD to the folder: \terraform\deployments\Manhattan\dev,
then run 'terraform apply'.

[terraform.zip](https://github.com/hashicorp/terraform/files/112910/terraform.zip)

**Comment by jen20** [comment]
Doing some more investigation here: it looks like the crash was in the following code which has subsequently moved around a bit since v0.6.10:

```
func routeIDHash(d *schema.ResourceData, r *ec2.Route) string {
	return fmt.Sprintf("r-%s%d", d.Get("route_table_id").(string), hashcode.String(*r.DestinationCidrBlock))
}
```

I'd imagine that the crash must be in the dereference of `r.DestinationCidrBlock` though it is hard to imagine how the route could exist in this case, and I cannot reproduce this locally.
