### ISSUE TITLE
Crash report - AWS

### ISSUE THREAD

**Issue by trungnguyen** [hashicorp/terraform#5472]
Terraform version: 0.6.11

Here is the crash.log
[crash.zip](https://github.com/hashicorp/terraform/files/160272/crash.zip)

**Comment by jen20** [comment]
Relevant section of the crash log:

```
2016/03/06 11:15:44 [DEBUG] terraform-provisioner-remote-exec.exe: panic: runtime error: invalid memory address or nil pointer dereference
2016/03/06 11:15:44 [DEBUG] terraform-provisioner-remote-exec.exe: [signal 0xc0000005 code=0x0 addr=0x58 pc=0x6b5c8d]
2016/03/06 11:15:44 [DEBUG] terraform-provisioner-remote-exec.exe: 
2016/03/06 11:15:44 [DEBUG] terraform-provisioner-remote-exec.exe: goroutine 93 [running]:
2016/03/06 11:15:44 [DEBUG] terraform-provisioner-remote-exec.exe: github.com/hashicorp/terraform/vendor/github.com/packer-community/winrmcp/winrmcp.cleanupContent(0xc08205b580, 0xc0822ea1c0, 0x3a, 0x0, 0x0)
2016/03/06 11:15:44 [DEBUG] terraform-provisioner-remote-exec.exe: 	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/packer-community/winrmcp/winrmcp/cp.go:169 +0x18d
2016/03/06 11:15:44 [DEBUG] terraform-provisioner-remote-exec.exe: github.com/hashicorp/terraform/vendor/github.com/packer-community/winrmcp/winrmcp.doCopy(0xc08205b580, 0xc0822d5360, 0x154a498, 0xc0821cef90, 0xc0822a5240, 0x20, 0x0, 0x0)
2016/03/06 11:15:44 [DEBUG] terraform-provisioner-remote-exec.exe: 	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/packer-community/winrmcp/winrmcp/cp.go:42 +0xcbd
```

@trungnguyen - can you confirm that my edit to the title here is correct, and that you were provisioning a Windows instance when this occurred?

**Comment by trungnguyen** [comment]
Yes, your change in the title is correct.
Yes I were provisioning a Windows instance when it occurred.
BTW it happened only once, next time I did "terraform apply" and it did succeed.

**Comment by jen20** [comment]
Thanks for the follow up info @trungnguyen! I suspect we are neglecting to handle a transient error condition in the provisioner.
