### ISSUE TITLE
Concurrent map writes in TestApply_parallelism command test

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#5517]
Got this on Travis just now:

```
fatal error: concurrent map writes

goroutine 455 [running]:
runtime.throw(0x1093be0, 0x15)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:530 +0x90 fp=0xc8203693b8 sp=0xc8203693a0
runtime.mapassign1(0xc7bfa0, 0xc820345ec0, 0xc820369520, 0xc8203694e8)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/hashmap.go:445 +0xb1 fp=0xc820369460 sp=0xc8203693b8
github.com/hashicorp/terraform/terraform.(*EvalDiff).Eval(0xc82025c390, 0x2b671b08ebf0, 0xc82035f2b0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/hashicorp/terraform/terraform/eval_diff.go:126 +0x7f4 fp=0xc820369548 sp=0xc820369460
github.com/hashicorp/terraform/terraform.EvalRaw(0x2b671b04de80, 0xc82025c390, 0x2b671b08ebf0, 0xc82035f2b0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x25b fp=0xc820369688 sp=0xc820369548
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc820242a00, 0x2b671b08ebf0, 0xc82035f2b0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:10 +0xea fp=0xc820369730 sp=0xc820369688
github.com/hashicorp/terraform/terraform.EvalRaw(0x2b671b08edb8, 0xc820242a00, 0x2b671b08ebf0, 0xc82035f2b0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x25b fp=0xc820369870 sp=0xc820369730
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc82025c450, 0x2b671b08ebf0, 0xc82035f2b0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x67 fp=0xc8203698b8 sp=0xc820369870
github.com/hashicorp/terraform/terraform.EvalRaw(0x2b671b08ede0, 0xc82025c450, 0x2b671b08ebf0, 0xc82035f2b0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x25b fp=0xc8203699f8 sp=0xc8203698b8
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc820242320, 0x2b671b08ebf0, 0xc82035f2b0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:10 +0xea fp=0xc820369aa0 sp=0xc8203699f8
github.com/hashicorp/terraform/terraform.EvalRaw(0x2b671b08edb8, 0xc820242320, 0x2b671b08ebf0, 0xc82035f2b0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x25b fp=0xc820369be0 sp=0xc820369aa0
github.com/hashicorp/terraform/terraform.Eval(0x2b671b08edb8, 0xc820242320, 0x2b671b08ebf0, 0xc82035f2b0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:34 +0x6a fp=0xc820369c48 sp=0xc820369be0
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0xf76620, 0xc8202f3fb0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:198 +0x9a9 fp=0xc820369eb8 sp=0xc820369c48
github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk.func3(0xc820131530, 0xc8202fbbc0, 0xc820131148, 0xc8202180c0, 0xc820131540, 0xf76620, 0xc8202f3fb0, 0xc8202a90e0, 0xc8202a9140)
	/home/travis/gopath/src/github.com/hashicorp/terraform/dag/dag.go:238 +0xeb fp=0xc820369f58 sp=0xc820369eb8
runtime.goexit()
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820369f60 sp=0xc820369f58
created by github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk
	/home/travis/gopath/src/github.com/hashicorp/terraform/dag/dag.go:247 +0x715
```

Full log:
https://gist.github.com/phinze/2d0d84cbc85595bc79b5

**Comment by phinze** [comment]
@jbardin do you think your race hunt would have taken care of this one?

**Comment by jbardin** [comment]
I think #7877 should have taken care of this.

**Comment by phinze** [comment]
I do too - closing.
