### ISSUE TITLE
Panic error for digitalocean_droplet

### ISSUE THREAD

**Issue by sheerun** [hashicorp/terraform#5583]
```
2016/03/11 13:08:44 [DEBUG] vertex provider.digitalocean (close), waiting for: digitalocean_droplet.master
2016/03/11 13:08:48 [DEBUG] terraform-provider-digitalocean: panic: runtime error: invalid memory address or nil pointer dereference
2016/03/11 13:08:48 [DEBUG] terraform-provider-digitalocean: [signal 0xb code=0x1 addr=0x0 pc=0x61063]
2016/03/11 13:08:48 [DEBUG] terraform-provider-digitalocean:
2016/03/11 13:08:48 [DEBUG] terraform-provider-digitalocean: goroutine 99 [running]:
2016/03/11 13:08:48 [DEBUG] terraform-provider-digitalocean: panic(0x666080, 0x820bcc110)
2016/03/11 13:08:48 [DEBUG] terraform-provider-digitalocean: 	/opt/go/src/runtime/panic.go:464 +0x3e6
2016/03/11 13:08:48 [DEBUG] terraform-provider-digitalocean: github.com/hashicorp/terraform/builtin/providers/digitalocean.resourceDigitalOceanDropletRead(0x820d78ae0, 0x69e740, 0x820df1b00, 0x0, 0x0)
2016/03/11 13:08:48 [DEBUG] terraform-provider-digitalocean: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/digitalocean/resource_digitalocean_droplet.go:192 +0x263
2016/03/11 13:08:48 [DEBUG] terraform-provider-digitalocean: github.com/hashicorp/terraform/builtin/providers/digitalocean.newDropletStateRefreshFunc.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/03/11 13:08:48 [DEBUG] terraform-provider-digitalocean: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/digitalocean/resource_digitalocean_droplet.go:447 +0x199
2016/03/11 13:08:48 [DEBUG] terraform-provider-digitalocean: github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState.func1(0x820d799e0, 0x820d79980, 0x821092c80, 0x821092c90, 0x821092c70)
2016/03/11 13:08:48 [DEBUG] terraform-provider-digitalocean: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/resource/state.go:83 +0x1ef
2016/03/11 13:08:48 [DEBUG] terraform-provider-digitalocean: created by github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState
2016/03/11 13:08:48 [DEBUG] terraform-provider-digitalocean: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/resource/state.go:129 +0x20c
```

**Comment by jen20** [comment]
Hi @sheerun! Thanks for reporting this. Anything causing a crash is considered a bug in Terraform. I'll take a look and open PR to fix it.

**Comment by sheerun** [comment]
It happens randomly, there's no way to reliably reproduce
