### ISSUE TITLE
v0.6.13 - Terraform crash on provisioner

### ISSUE THREAD

**Issue by dcloud9** [hashicorp/terraform#5754]
Hi,
Provisioner crashes on terraform plan|apply|destroy|refresh after modules successfully built that stacks.
It happened also in v0.6.12, bumped +1 version to 0.6.13, but still hit the same crash.
Attached the crash.log.

[crash.log.gz](https://github.com/hashicorp/terraform/files/182672/crash.log.gz)
````
2016/03/21 14:09:21 [DEBUG] /usr/local/bin/terraform-provisioner-file: plugin process exited
2016/03/21 14:09:21 [DEBUG] /usr/local/bin/terraform-provisioner-local-exec: plugin process exited
2016/03/21 14:09:21 [DEBUG] /usr/local/bin/terraform-provisioner-remote-exec: plugin process exited
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
terraform/modules$ terraform --version
Terraform v0.6.13

**Comment by radeksimko** [comment]
Cutting out the interesting but of crash log:

```
2016/03/21 16:15:28 [DEBUG] terraform-provider-aws: panic: runtime error: invalid memory address or nil pointer dereference
2016/03/21 16:15:28 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x5e4c57]
2016/03/21 16:15:28 [DEBUG] terraform-provider-aws: 
2016/03/21 16:15:28 [DEBUG] terraform-provider-aws: goroutine 515 [running]:
2016/03/21 16:15:28 [DEBUG] terraform-provider-aws: panic(0x11c3be0, 0xc82000a130)
2016/03/21 16:15:28 [DEBUG] terraform-provider-aws: 	/opt/go/src/runtime/panic.go:464 +0x3e6
2016/03/21 16:15:28 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsRouteExists(0xc8215f73e0, 0xeaf860, 0xc8200f65a0, 0x1ee30e0, 0x0, 0x0)
2016/03/21 16:15:28 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route.go:297 +0x407
2016/03/21 16:15:28 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc8208fd380, 0xc8215ef6b0, 0xeaf860, 0xc8200f65a0, 0xc820a267d8, 0x0, 0x0)
2016/03/21 16:15:28 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:188 +0x1b7
2016/03/21 16:15:28 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc8208990b0, 0xc8215fe580, 0xc8215ef6b0, 0x1ee3201, 0x0, 0x0)
2016/03/21 16:15:28 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:187 +0x1da
2016/03/21 16:15:28 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Refresh(0xc820929460, 0xc8215fcbe0, 0xc8215fce20, 0x0, 0x0)
2016/03/21 16:15:28 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/rpc/resource_provider.go:345 +0x6a
2016/03/21 16:15:28 [DEBUG] terraform-provider-aws: reflect.Value.call(0x11047a0, 0x13dc1f8, 0x13, 0x1488788, 0x4, 0xc820c33ed8, 0x3, 0x3, 0x0, 0x0, ...)
```

**Comment by phinze** [comment]
Hi @dcloud9 - thanks for the report. This crash is fixed on master now. :+1:
