### ISSUE TITLE
Crash during (after) successful apply

### ISSUE THREAD

**Issue by mgoodness** [hashicorp/terraform#5855]
v0.6.13
[crash.log.txt](https://github.com/hashicorp/terraform/files/189654/crash.log.txt)

```
State path: terraform.tfstate
panic: missing root module

goroutine 1 [running]:
panic(0x825c00, 0xc8203e13c0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/hashicorp/terraform/terraform.(*State).RootModule(0xc82044e000, 0x0)
	/private/tmp/terraform20160316-80855-hnqetc/terraform-0.6.13/src/github.com/hashicorp/terraform/terraform/state.go:205 +0xa7
github.com/hashicorp/terraform/command.outputsAsString(0xc82044e000, 0x0, 0x0)
	/private/tmp/terraform20160316-80855-hnqetc/terraform-0.6.13/src/github.com/hashicorp/terraform/command/apply.go:379 +0x81
github.com/hashicorp/terraform/command.(*ApplyCommand).Run(0xc8200d4d00, 0xc8201ab4f0, 0x0, 0x0, 0xc8201572b0)
	/private/tmp/terraform20160316-80855-hnqetc/terraform-0.6.13/src/github.com/hashicorp/terraform/command/apply.go:253 +0x24bd
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc8200da540, 0xc820131cb0, 0x0, 0x0)
	/private/tmp/terraform20160316-80855-hnqetc/terraform-0.6.13/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:153 +0x5ee
main.wrappedMain(0x0)
	/private/tmp/terraform20160316-80855-hnqetc/terraform-0.6.13/src/github.com/hashicorp/terraform/main.go:140 +0xb05
main.realMain(0x0)
	/private/tmp/terraform20160316-80855-hnqetc/terraform-0.6.13/src/github.com/hashicorp/terraform/main.go:76 +0xa10
main.main()
	/private/tmp/terraform20160316-80855-hnqetc/terraform-0.6.13/src/github.com/hashicorp/terraform/main.go:19 +0x18
```

**Comment by phinze** [comment]
Hi @mgoodness - thanks for the report, and sorry for the trouble!

A few questions to help us narrow this down:

 * Does this crash also occur for you on Terraform 0.6.14?
 * Can you share the config that you were using when the crash occurred?

**Comment by mgoodness** [comment]
No trouble, @phinze ; the configuration applied successfully. Will try it again, with 0.6.14, and report back.

**Comment by mitchellh** [comment]
Hey @mgoodness we never got that report back and haven't heard of this happening with anyone else? There has been a lot of core fixes around state management since March and hopefully this doesn't happen anymore but if it does please help us out by opening a new issue. Thanks!

**Comment by mgoodness** [comment]
Thank you, @mitchellh! Things have been much more stable since I filed the issue. Sorry for not updating/closing it sooner.

**Comment by mitchellh** [comment]
No worries and good to hear. I take crashes super seriously so if you see another please let us know. Thanks!
