### ISSUE TITLE
Crash in terraform 0.6.14 on refreshing route state

### ISSUE THREAD

**Issue by greg-jaunt** [hashicorp/terraform#5865]
I attempted to change a CIDR block in a route, and have ended up suck in a state where terraform will crash on every run.  It appears to be crashing while Refreshing state:

```
panic: runtime error: invalid memory address or nil pointer dereference
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x1e8517]
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws:
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: goroutine 454 [running]:
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: panic(0xdce9a0, 0x821f02110)
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: 	/opt/go/src/runtime/panic.go:464 +0x3e6
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsRouteExists(0x823ab88a0, 0xab8ee0, 0x822daf440, 0x1af5a80, 0x0, 0x0)
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route.go:297 +0x407
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0x823256b80, 0x823aba9f0, 0xab8ee0, 0x822daf440, 0x821f75ff0, 0x0, 0x0)
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:188 +0x1b7
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0x823272f60, 0x823a5da80, 0x823aba9f0, 0x1af5c01, 0x0, 0x0)
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:187 +0x1da
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Refresh(0x82314c200, 0x823aad1b0, 0x823aad5b0, 0x0, 0x0)
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/rpc/resource_provider.go:345 +0x6a
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: reflect.Value.call(0xd0eec0, 0xfe7c18, 0x13, 0x10955f8, 0x4, 0x82341bed8, 0x3, 0x3, 0x0, 0x0, ...)
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: 	/opt/go/src/reflect/value.go:435 +0x120d
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: reflect.Value.Call(0xd0eec0, 0xfe7c18, 0x13, 0x82341bed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: 	/opt/go/src/reflect/value.go:303 +0xb1
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: net/rpc.(*service).call(0x823257440, 0x823257400, 0x823148d00, 0x822d80200, 0x822db9ce0, 0xaba080, 0x823aad1b0, 0x16, 0xaba0e0, 0x823aad5b0, ...)
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: 	/opt/go/src/net/rpc/server.go:383 +0x1c2
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: created by net/rpc.(*Server).ServeCodec
2016/03/24 17:02:35 [DEBUG] terraform-provider-aws: 	/opt/go/src/net/rpc/server.go:477 +0x49d
```

I would appreciate any assistance in tracking this down.

Thanks.

**Comment by phinze** [comment]
Hi @greg-jaunt - thanks for the report - and sorry for the trouble here! You can work around the crash by yanking the resource in question out of your `tfstate` file. It will show up under a `"resources"` key and the whole `"aws_route.foo": { ... }` block can be removed to make Terraform "forget" about the resource and work around the crash.

For our part, we'll look into the root cause and get this fixed up. :+1:

**Comment by greg-jaunt** [comment]
Thanks for the fast response!

I have quite a few routes.  Can I get any hints from the trace or crash log on which one is causing the issue?

**Comment by phinze** [comment]
@greg-jaunt should be one of the last few `Refreshing resource aws_route.????`... in your output before the crash.

**Comment by phinze** [comment]
Actually @greg-jaunt I see the trouble in the code - looks like if the Route Table referenced by `route_table_id` disappears for any reason, we're not handling it properly.

**Comment by greg-jaunt** [comment]
Thanks for tracking that down!  I also worked out the required state file change to work around the problem.
