### ISSUE TITLE
Resource `heroku_cert` - unexpected EOF

### ISSUE THREAD

**Issue by fnmunhoz** [hashicorp/terraform#5930]
Hello!

I'm trying to update a certificate file on heroku, but I'm receiving this on `terraform apply`:

```
Error applying plan:

1 error(s) occurred:

* heroku_cert.ssl-production: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: interface conversion: interface {} is string, not *string
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku:
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku: goroutine 198 [running]:
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku: panic(0x674de0, 0xc8202bfc40)
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku:  /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku: github.com/hashicorp/terraform/builtin/providers/heroku.resourceHerokuCertUpdate(0xc8204a4ea0, 0x73b020, 0xc8202187f8, 0x0, 0x0)
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku:  /private/tmp/terraform20160322-40204-nd0o52/terraform-0.6.14/src/github.com/hashicorp/terraform/builtin/providers/heroku/resource_heroku_cert.go:96 +0x40d
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc8202be7c0, 0xc82018f2f0, 0xc820472650, 0x73b020, 0xc8202187f8, 0xc82018f401, 0x0, 0x0)
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku:  /private/tmp/terraform20160322-40204-nd0o52/terraform-0.6.14/src/github.com/hashicorp/terraform/helper/schema/resource.go:152 +0x3b9
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc8204af8c0, 0xc8202bf540, 0xc82018f2f0, 0xc820472650, 0x1, 0x0, 0x0)
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku:  /private/tmp/terraform20160322-40204-nd0o52/terraform-0.6.14/src/github.com/hashicorp/terraform/helper/schema/provider.go:162 +0x1ed
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Apply(0xc82033fc00, 0xc8203208a0, 0xc8204726a0, 0x0, 0x0)
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku:  /private/tmp/terraform20160322-40204-nd0o52/terraform-0.6.14/src/github.com/hashicorp/terraform/rpc/resource_provider.go:323 +0x76
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku: reflect.Value.call(0x60a7a0, 0x6f1bf8, 0x13, 0x73ed80, 0x4, 0xc8201e1ee8, 0x3, 0x3, 0x0, 0x0, ...)
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku:  /usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:435 +0x120d
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku: reflect.Value.Call(0x60a7a0, 0x6f1bf8, 0x13, 0xc8201e1ee8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku:  /usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:303 +0xb1
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku: net/rpc.(*service).call(0xc8202be840, 0xc8202be800, 0xc820459698, 0xc8201a8800, 0xc82033fc20, 0x51f400, 0xc8203208a0, 0x16, 0x51f460, 0xc8204726a0, ...)
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku:  /usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:383 +0x1c2
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku: created by net/rpc.(*Server).ServeCodec
2016/03/30 13:32:31 [DEBUG] terraform-provider-heroku:  /usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:477 +0x49d
2016/03/30 13:32:31 [DEBUG] root: eval: *terraform.EvalWriteState
2016/03/30 13:32:31 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2016/03/30 13:32:31 [DEBUG] root: eval: *terraform.EvalIf
2016/03/30 13:32:31 [DEBUG] root: eval: *terraform.EvalWriteDiff
2016/03/30 13:32:31 [DEBUG] root: eval: *terraform.EvalIf
2016/03/30 13:32:31 [DEBUG] root: eval: *terraform.EvalWriteState
2016/03/30 13:32:31 [DEBUG] root: eval: *terraform.EvalApplyPost
2016/03/30 13:32:31 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* heroku_cert.ssl-production: unexpected EOF
2016/03/30 13:32:31 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* heroku_cert.ssl-production: unexpected EOF
2016/03/30 13:32:31 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* heroku_cert.ssl-production: unexpected EOF
2016/03/30 13:32:31 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* heroku_cert.ssl-production: unexpected EOF
2016/03/30 13:32:31 [TRACE] [walkApply] Exiting eval tree: heroku_cert.ssl-production
2016/03/30 13:32:31 [DEBUG] vertex provider.heroku (close), got dep: heroku_cert.ssl-production
2016/03/30 13:32:31 [DEBUG] vertex root, got dep: provider.heroku (close)
2016/03/30 13:32:31 [DEBUG] vertex root, got dep: provider.dnsimple
2016/03/30 13:32:31 [DEBUG] /usr/local/Cellar/terraform/0.6.14/bin/terraform-provider-heroku: plugin process exited
2016/03/30 13:32:31 [DEBUG] waiting for all plugin processes to complete...
2016/03/30 13:32:31 [DEBUG] /usr/local/Cellar/terraform/0.6.14/bin/terraform-provider-dnsimple: plugin process exited
```

My resources looks like that:

```
resource "heroku_app" "production" {
    name = "appname-production"
    region = "us"

    config_vars {
        ...
    }
}

resource "heroku_domain" "production" {
    app = "${heroku_app.production.name}"
    hostname = "${var.appname_domain}"
}

resource "heroku_domain" "www" {
    app = "${heroku_app.production.name}"
    hostname = "www.${var.appname_domain}"
}

resource "heroku_addon" "ssl-production" {
    app = "${heroku_app.production.name}"
    plan = "ssl:endpoint"
}

resource "heroku_cert" "ssl-production" {
    app = "${heroku_app.production.name}"
    certificate_chain = "${file("www_appname_com.crt")}"
    private_key = "${file("www_appname.key")}"
    depends_on = ["heroku_addon.ssl-production"]
}
```

I've tried with the latest version of terraform `0.6.4` but no success.

If there is any other information that I could bring to help, let me known.

Thanks!

**Comment by BestFriendChris** [comment]
I'm also seeing this when trying to update the heroku cert (running terraform version `0.9.3`)

**Comment by catsby** [comment]
Hello – I'm going to close this now and assume it's been fixed (as per comment above). Please let me know if you're still hitting this on Terraform v0.9
