### ISSUE TITLE
terraform crash when reading a lot of values out of consul

### ISSUE THREAD

**Issue by dansteen** [hashicorp/terraform#6097]
I get a terraform crash when I read a lot of entries from consul and then use them in my config.  As an example:

```
resource "consul_keys" "matching-spark-scaler" {
    # get the values from consul for the config
    # first determin if we enable scaling or not
    key {
      name = "scale_up_enabled"
      path = "app/matching-spark-scaler/${consul_keys.matching-spark-scaler-version.var.hash}/scaleUpEnabled"
    }
    key {
      name = "scale_down_enabled"
      path = "app/matching-spark-scaler/${consul_keys.matching-spark-scaler-version.var.hash}/scaleDownEnabled"
    }
}
```

and then using the above in a resource:
```
resource "aws_cloudwatch_metric_alarm" "matching-spark_max_memory_available" {
    alarm_name = "matching-spark ${var.env} Max Memory Available"
    alarm_description = "matching-spark ${var.env} Max Memory Available"
    namespace = "AWS/ElasticMapReduce"
    statistic = "Maximum"
    metric_name = "MemoryAvailableMB"
    comparison_operator = "GreaterThanOrEqualToThreshold"
    threshold = "${ ( ( ( ( consul_keys.matching-spark-scaler.var.recycle_stream_executor_memory * consul_keys.matching-spark-scaler.var.recycle_stream_num_executors ) + consul_keys.matching-spark-scaler.var.recycle_stream_driver_memory ) + ( ( consul_keys.matching-spark-scaler.var.cluster_update_executor_memory * consul_keys.matching-spark-scaler.var.cluster_update_num_executors ) + consul_keys.matching-spark-scaler.var.cluster_update_driver_memory ) + ( ( consul_keys.matching-spark-scaler.var.streaming_kmeans_executor_memory * consul_keys.matching-spark-scaler.var.streaming_kmeans_num_executors ) + consul_keys.matching-spark-scaler.var.streaming_kmeans_driver_memory ) ) * consul_keys.matching-spark-scaler.var.max_app_capacity ) }"
    evaluation_periods = "1"
    period = "60"
    alarm_actions = ["${aws_sns_topic.matching-spark-alarm.arn}"]
   # NOTE: the below causes an crash
    actions_enabled = "${consul_keys.matching-spark-scaler2.var.scale_down_enabled}"
    # NOTE: If I change it to this things work
    #actions_enabled = "true"
    dimensions {
      JobFlowId = "${consul_keys.matching-spark-alarm.var.cluster_id}"
    }
}
```

But the above doesn't really tell the whole story, as I have a few other similar resources, and a lot of other consul reads throughout my config.   As long as I disable the ones that look like the above then things succeed.  So it seems like I am hitting some limit or other.

I have attached the crash log.

v0.6.14

[crash.log.gz](https://github.com/hashicorp/terraform/files/210853/crash.log.gz)

**Comment by apparentlymart** [comment]
Hi @dansteen. Sorry for this crash!

The panic part of the log output is here:

```
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: panic: Error reading level config: strconv.ParseBool: parsing "11": invalid syntax
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: 
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: goroutine 9691 [running]:
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: panic(0x1199e00, 0xc822af1760)
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: 	/opt/go/src/runtime/panic.go:464 +0x3e6
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc824929380, 0xc822af15b0, 0x1, 0x1, 0xc822af1502, 0x0, 0x0, 0x0, 0x0, 0x400000, ...)
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:394 +0x20a
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc824929380, 0x14b7420, 0xf, 0xc822af1201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:365 +0x235
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc824929380, 0x14b7420, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:342 +0x78
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.schemaMap.diffString(0xc82598fec0, 0x14b7420, 0xf, 0xc825cf41a0, 0xc822b0d7b0, 0xc824929380, 0x0, 0x0, 0x0)
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:929 +0xa5
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc82598fec0, 0x14b7420, 0xf, 0xc825cf41a0, 0xc822b0d7b0, 0xc824929380, 0xc823525f00, 0x0, 0x0)
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:576 +0xaf
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc82598fec0, 0xc824ab74a0, 0xc824ab76b0, 0xc82402d950, 0x0, 0x0)
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:302 +0x1ff
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc825ce2880, 0xc824ab74a0, 0xc824ab76b0, 0x1b, 0x0, 0x0)
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:163 +0x44
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc825d3c720, 0xc8256b2f40, 0xc824ab74a0, 0xc824ab76b0, 0x301, 0x0, 0x0)
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:175 +0x1c5
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Diff(0xc82599f680, 0xc822671ae0, 0xc822b0d7a0, 0x0, 0x0)
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/rpc/resource_provider.go:334 +0x76
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: reflect.Value.call(0x1112f40, 0x13ec298, 0x13, 0x14996b0, 0x4, 0xc824f21ed8, 0x3, 0x3, 0x0, 0x0, ...)
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: 	/opt/go/src/reflect/value.go:435 +0x120d
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: reflect.Value.Call(0x1112f40, 0x13ec298, 0x13, 0xc824f21ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: 	/opt/go/src/reflect/value.go:303 +0xb1
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: net/rpc.(*service).call(0xc825d1d2c0, 0xc825d1d280, 0xc825d4e030, 0xc822521a00, 0xc82599f6a0, 0xebda60, 0xc822671ae0, 0x16, 0xebdac0, 0xc822b0d7a0, ...)
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: 	/opt/go/src/net/rpc/server.go:383 +0x1c2
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: created by net/rpc.(*Server).ServeCodec
2016/04/08 16:37:25 [DEBUG] terraform-provider-aws: 	/opt/go/src/net/rpc/server.go:477 +0x49d
```

Is it possible that your consul key `app/matching-spark-scaler/${consul_keys.matching-spark-scaler-version.var.hash}/scaleDownEnabled` actually does contain the string "11"?

If it is, it's certainly still a bug that Terraform crashes here rather than simply reporting that a boolean value is required, but a workaround would be to make that consul key contain "true" or "1", which I expect Terraform would then parse as expected.

If you do have something true-ish in that Consul key then the bug is likely elsewhere, in which case we can dig some more.

**Comment by apparentlymart** [comment]
Another possibility: I've noticed that sometimes computed map attributes end up interpolating as an integer... possibly the number of elements in the map? or something else?

In that case, doing an initial plan/apply with `-target="consul_keys.matching-spark-scaler"` may resolve the issue and allow that boolean value to interpolate correctly.

Still a bug that it's crashing rather than returning a proper error about the boolean syntax, though.

**Comment by dansteen** [comment]
hi @apparentlymart thanks for the reply!  (Sorry it took me so long to get back to you)

The `app/matching-spark-scaler/${consul_keys.matching-spark-scaler-version.var.hash}/scaleDownEnabled` returns "true" or "false" (depending)

I'm not sure about that second possibility.  My config is really heavily modularized so it's hard for me to just run a -target in a way that works.  I'll see if I can put something together for that.

**Comment by catsby** [comment]
Hey @dansteen do you have any more information here?

**Comment by dansteen** [comment]
looking...

**Comment by dansteen** [comment]
So, since this original issue I've updated to v0.6.16, and I am no longer able to trigger this panic.  I do get this the first time I run "apply":

```
Error applying plan:

1 error(s) occurred:

* consul_keys.matching-spark: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.16
    Resource ID: consul_keys.matching-spark
    Mismatch reason: attribute mismatch: key.1211574727.delete
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"key.1211574727.path":*terrafo
rm.ResourceAttrDiff{Old:"service/sns/matching-spark/stag", New:"service/sns/matching-spark/stag", NewComputed:false, NewRemoved:false, New
Extra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.1211574727.value":*terraform.ResourceAttrDiff{Old:"arn:aws:sns:us-east-1:31531
6724794:matching-spark-alarm-stag", New:"arn:aws:sns:us-east-1:315316724794:matching-spark-alarm-stag", NewComputed:false, NewRemoved:fals
e, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.754144773.name":*terraform.ResourceAttrDiff{Old:"matching-spark cloudwat
ch min", New:"matching-spark cloudwatch min", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0
}, "key.~2348288191.delete":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(ni
l), RequiresNew:false, Type:0x0}, "key.2120412503.name":*terraform.ResourceAttrDiff{Old:"matching-spark emr config", New:"matching-spark e
mr config", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.2937742136.delete":*terraf
orm.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x
0}, "key.2937742136.path":*terraform.ResourceAttrDiff{Old:"cloud/matching-spark/task_node_memory/stag", New:"cloud/matching-spark/task_nod
e_memory/stag", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.2120412503.path":*terr
aform.ResourceAttrDiff{Old:"cloud/matching-spark/emr_config/stag", New:"cloud/matching-spark/emr_config/stag", NewComputed:false, NewRemov
ed:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.1301176783.path":*terraform.ResourceAttrDiff{Old:"cloud/matching-
spark/max_alarm_name/stag", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.~23
48288191.path":*terraform.ResourceAttrDiff{Old:"", New:"cloud/matching-spark/max_alarm_name/stag", NewComputed:false, NewRemoved:false, Ne
wExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.1211574727.name":*terraform.ResourceAttrDiff{Old:"matching-spark sns", New:"m
atching-spark sns", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.2937742136.value":
*terraform.ResourceAttrDiff{Old:"15360", New:"15360", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false,
Type:0x0}, "key.~2348288191.value":*terraform.ResourceAttrDiff{Old:"", New:"${aws_cloudwatch_metric_alarm.matching-spark_max_memory_availa
ble.id}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.~2348288191.default":*terraf
orm.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.1
301176783.delete":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), Re
quiresNew:false, Type:0x0}, "key.1211574727.default":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:true, NewEx
tra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.2937742136.name":*terraform.ResourceAttrDiff{Old:"task node memory", New:"task n
ode memory", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.2120412503.value":*terraf
orm.ResourceAttrDiff{Old:"stag/config/emr/emr-config.json", New:"stag/config/emr/emr-config.json", NewComputed:false, NewRemoved:false, Ne
wExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.~2348288191.name":*terraform.ResourceAttrDiff{Old:"", New:"matching-spark clo
udwatch max", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.754144773.path":*terrafo
rm.ResourceAttrDiff{Old:"cloud/matching-spark/min_alarm_name/stag", New:"cloud/matching-spark/min_alarm_name/stag", NewComputed:false, New
Removed:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.1211574727.delete":*terraform.ResourceAttrDiff{Old:"false",
New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.754144773.value":*terrafo
rm.ResourceAttrDiff{Old:"matching-spark stag min Memory Available", New:"matching-spark stag min Memory Available", NewComputed:false, New
Removed:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.2120412503.delete":*terraform.ResourceAttrDiff{Old:"false",
New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.2120412503.default":*terr
aform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.
1301176783.name":*terraform.ResourceAttrDiff{Old:"matching-spark cloudwatch max", New:"", NewComputed:false, NewRemoved:true, NewExtra:int
erface {}(nil), RequiresNew:false, Type:0x0}, "key.754144773.delete":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:fal
se, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.754144773.default":*terraform.ResourceAttrDiff{Old:""
, New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.2937742136.default":*terrafor
m.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "key.1301
176783.default":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:fa
lse, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyT
ainted:false}


```

But that's not unusual for this sort of thing, and it goes away with a second "apply", so I think this can be safely closed.

Thanks for following up!

**Comment by dansteen** [comment]
this looks like it has been completely resolved using the new "data sources" methods
