### ISSUE TITLE
provider/openstack: Terraform Crash with 0.6.15

### ISSUE THREAD

**Issue by matthughes** [hashicorp/terraform#6426]
TF files that was working fine with 0.6.14 crashes repeatedly when I upgrade to 0.6.15.

**Comment by matthughes** [comment]
[crash.txt](https://github.com/hashicorp/terraform/files/243656/crash.txt)

**Comment by apparentlymart** [comment]
Thanks for the report, @matthughes!

Here's the stack trace part of that log, for easier skimming:

```
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: panic: interface conversion: interface {} is nil, not map[string]interface {}
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: goroutine 73 [running]:
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: panic(0x73a8e0, 0xc82007f8c0)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/builtin/providers/openstack.resourceComputeSchedulerHintsHash(0x0, 0x0, 0xc800000001)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/builtin/providers/openstack/resource_openstack_compute_instance_v2.go:1291 +0xdc8
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.(*Set).hash(0xc82016ade0, 0x0, 0x0, 0x0, 0x0)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/helper/schema/set.go:180 +0x40
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.(*Set).add(0xc82016ade0, 0x0, 0x0, 0xc8203d0d00, 0x0, 0x0)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/helper/schema/set.go:167 +0x95
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readSet(0xc820292540, 0xc8202d4ec0, 0x1, 0x1, 0xc8203d0d00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:228 +0x643
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readField(0xc820292540, 0xc8202d4ec0, 0x1, 0x1, 0xd52e00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:90 +0x6d6
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).ReadField(0xc820292540, 0xc8202d4ec0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x1b0000, 0x0, ...)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:27 +0xc9
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.(*MultiLevelFieldReader).ReadFieldExact(0xc82017a6e0, 0xc8202d4ec0, 0x1, 0x1, 0x81a860, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/helper/schema/field_reader_multi.go:31 +0x27c
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc82052c000, 0xc8202d4ec0, 0x1, 0x1, 0xc8202d4e02, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:389 +0x176
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc82052c000, 0x8373b0, 0xf, 0x1201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:365 +0x235
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc82052c000, 0x8373b0, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:342 +0x78
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.schemaMap.diffSet(0xc82034e5d0, 0x8373b0, 0xf, 0xc8203d0d00, 0xc820312a40, 0xc82052c000, 0x0, 0x0, 0x0)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/helper/schema/schema.go:808 +0x7c
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc82034e5d0, 0x8373b0, 0xf, 0xc8203d0d00, 0xc820312a40, 0xc82052c000, 0x746822203a224c00, 0x0, 0x0)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/helper/schema/schema.go:582 +0x32e
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc82034e5d0, 0xc820292060, 0xc820292120, 0xc82042e950, 0x0, 0x0)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/helper/schema/schema.go:302 +0x1ff
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc820275240, 0xc820292060, 0xc820292120, 0x1d, 0x0, 0x0)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/helper/schema/resource.go:163 +0x44
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc82034ef00, 0xc820126000, 0xc820292060, 0xc820292120, 0x203a224c52556e01, 0x0, 0x0)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/helper/schema/provider.go:175 +0x1c5
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Diff(0xc82037c6a0, 0xc82017a040, 0xc820312a30, 0x0, 0x0)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/private/tmp/terraform-20160427-87811-1i9p9b0/terraform-0.6.15/src/github.com/hashicorp/terraform/rpc/resource_provider.go:334 +0x76
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: reflect.Value.call(0x6cc460, 0x7c6198, 0x13, 0x816c28, 0x4, 0xc8205cded8, 0x3, 0x3, 0x0, 0x0, ...)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: reflect.Value.Call(0x6cc460, 0x7c6198, 0x13, 0xc8205cded8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: net/rpc.(*service).call(0xc820275c80, 0xc820275c40, 0xc8201e47d0, 0xc820221b00, 0xc82018c480, 0x5c4d60, 0xc82017a040, 0x16, 0x5c4dc0, 0xc820312a30, ...)
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:383 +0x1c2
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: created by net/rpc.(*Server).ServeCodec
2016/04/30 10:47:09 [DEBUG] terraform-provider-openstack: 	/usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:477 +0x49d
```

This crash seems specific to the openstack provider, so I'm going to tag it that way for now until we learn more. Thanks again!

**Comment by jtopjian** [comment]
@matthughes Thanks for the report! I see the issue here, but, if possible, can you post a sanitized version of the configuration that is triggering this error? I'm curious to see how it happened.

**Comment by stack72** [comment]
ping @matthughes https://github.com/hashicorp/terraform/issues/6426#issuecomment-216006067

**Comment by mitchellh** [comment]
Hello! I'm going through `waiting-response` labeled issues and closing issues that haven't been responded to with a meaningful response in at least 2+ weeks. If this is still an issue, please open a new issue so we can start anew. Feel free to reference this existing issue to make a link between the two. Thanks!
