### ISSUE TITLE
Terraform plan crashes when aws_cloudfront_distribution.xxx.default_cache_behavior.forwarded_values.cookies is not set

### ISSUE THREAD

**Issue by astoltz** [hashicorp/terraform#6441]
Terraform version: v0.6.15

Example:

```
resource "aws_cloudfront_distribution" "prod_assets_cloudfront" {
  enabled     = true
  comment     = "${aws_s3_bucket.prod_assets.id}"
  aliases     = ["${aws_s3_bucket.prod_assets.id}"]
  price_class = "PriceClass_100"

  origin {
    domain_name = "${aws_s3_bucket.prod_assets.website_endpoint}"
    origin_id   = "prod_assets_s3"

    custom_origin_config {
      http_port = 80
      https_port = 443
      origin_protocol_policy = "http-only"
      origin_ssl_protocols = ["TLSv1", "TLSv1.1", "TLSv1.2"]
    }
  }

  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "prod_assets_s3"

    forwarded_values {
      query_string = false
      #cookies {
      #  forward = "none"
      #}
    }

    viewer_protocol_policy = "allow-all"
    min_ttl                = 0
    default_ttl            = 3600
    max_ttl                = 86400
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }
}
```
[crash.log.zip](https://github.com/hashicorp/terraform/files/245529/crash.log.zip)

**Comment by apparentlymart** [comment]
Here's the stack trace I fished out of the log, for easier reference:

```
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: panic: runtime error: index out of range
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: goroutine 910 [running]:
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: panic(0xe56460, 0x8220080c0)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/go/src/runtime/panic.go:464 +0x3e6
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.forwardedValuesHash(0xb72000, 0x82268b890, 0x800000001)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/cloudfront_distribution_configuration_structure.go:385 +0x860
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Set).hash(0x82229fbc0, 0xb72000, 0x82268b890, 0x0, 0x0)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/set.go:180 +0x40
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Set).add(0x82229fbc0, 0xb72000, 0x82268b890, 0x82225e600, 0x0, 0x0)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/set.go:167 +0x95
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readSet(0x822615b00, 0x82268b710, 0x3, 0x3, 0x82225e680, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:228 +0x643
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readField(0x822615b00, 0x82268b710, 0x3, 0x3, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:90 +0x6d6
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*nestedConfigFieldReader).ReadField(0x82202ef00, 0x82268b710, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x822290000, 0x0, ...)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:271 +0x90
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.readObjectField(0x8822057100, 0x82202ef00, 0x82229f680, 0x2, 0x2, 0x8223c79b0, 0x0, 0x0, 0x0, 0x0, ...)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/field_reader.go:200 +0x26d
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readField(0x822615b00, 0x82229f680, 0x2, 0x2, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:94 +0x81d
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*nestedConfigFieldReader).ReadField(0x82202eef0, 0x82229f680, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:271 +0x90
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.readListField(0x8822057100, 0x82202eef0, 0x8225b3f70, 0x1, 0x1, 0x822260c30, 0x0, 0x0, 0x0, 0x0, ...)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/field_reader.go:167 +0x484
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readSet(0x822615b00, 0x8225b3f70, 0x1, 0x1, 0x822260c30, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:205 +0x1a5
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readField(0x822615b00, 0x8225b3f70, 0x1, 0x1, 0x8821fff000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:90 +0x6d6
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).ReadField(0x822615b00, 0x8225b3f70, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x340000, 0x0, ...)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:27 +0xc9
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*MultiLevelFieldReader).ReadFieldExact(0x8225084c0, 0x8225b3f70, 0x1, 0x1, 0x11312e8, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/field_reader_multi.go:31 +0x27c
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0x8225a48a0, 0x8225b3f70, 0x1, 0x1, 0x8225b3f02, 0x0, 0x0, 0x0, 0x0, 0x1bf0000, ...)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:389 +0x176
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0x8225a48a0, 0x1234960, 0x16, 0x822621201, 0x0, 0x0, 0x0, 0x0, 0x822620000, 0x0, ...)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:365 +0x235
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0x8225a48a0, 0x1234960, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:342 +0x78
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.schemaMap.diffSet(0x8223c7c20, 0x1234960, 0x16, 0x822260c30, 0x8226cb2b0, 0x8225a48a0, 0x0, 0x0, 0x0)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:808 +0x7c
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0x8223c7c20, 0x1234960, 0x16, 0x822260c30, 0x8226cb2b0, 0x8225a48a0, 0x973e00, 0x0, 0x0)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:582 +0x32e
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0x8223c7c20, 0x822658690, 0x822658750, 0x8221ce950, 0x0, 0x0)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:302 +0x1ff
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0x822287b00, 0x822658690, 0x822658750, 0x1b, 0x0, 0x0)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:163 +0x44
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0x8221b2240, 0x822269c80, 0x822658690, 0x822658750, 0x8223e6001, 0x0, 0x0)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:175 +0x1c5
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Diff(0x82212c260, 0x822505d40, 0x8226d4da0, 0x0, 0x0)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/rpc/resource_provider.go:334 +0x76
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: reflect.Value.call(0xd93fc0, 0x107c1b8, 0x13, 0x112cfb8, 0x4, 0x822625ed8, 0x3, 0x3, 0x0, 0x0, ...)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/go/src/reflect/value.go:435 +0x120d
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: reflect.Value.Call(0xd93fc0, 0x107c1b8, 0x13, 0x822625ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/go/src/reflect/value.go:303 +0xb1
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: net/rpc.(*service).call(0x8221bdfc0, 0x8221bdf80, 0x8223aee30, 0x822072200, 0x822333900, 0xb34240, 0x822505d40, 0x16, 0xb342a0, 0x8226d4da0, ...)
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/go/src/net/rpc/server.go:383 +0x1c2
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: created by net/rpc.(*Server).ServeCodec
2016/05/02 11:49:14 [DEBUG] terraform-provider-aws: 	/opt/go/src/net/rpc/server.go:477 +0x49d
```

This crash seems to be inside the custom hashing function for the `forwarded_values` set, so I'm going to tag this as an AWS provider issue for now, until we learn some more.

It might be possible to "quick-fix" this by removing the custom hashing function and instead use the built-in default that was added some versions ago. If any of the fields in this block are `ForceNew` then that will require a schema upgrade function, but if not we might be able to get away with just removing the set callback and dealing with some noisy diffs the first time someone runs Terraform after upgrading.

**Comment by jrnt30** [comment]
Seems like a duplicate of #6425

**Comment by astoltz** [comment]
I didn't see that one. Thanks.
