### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by TeaBough** [hashicorp/terraform#6767]
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_network_interface

### Terraform Configuration Files
```hcl
resource "aws_network_interface" "eni-53a81d09" {
  subnet_id         = "subnet-89d9f1cf"
  private_ips       = ["10.0.0.239"]
  security_groups   = []
  source_dest_check = false
  description = "Primary network interface"
}
```

### Panic Output
https://gist.githubusercontent.com/TeaBough/8bbe93352826906ef3750e0a46f8a639/raw/9f6e51edf5ca48cd001fae63dfa548757e8c93fc/crash.log

### Expected Behavior
Should have detect that the network interfaces are already created

### Actual Behavior
Terraform crashed : 
```
2016/05/19 14:47:18 [DEBUG] terraform-provider-aws: panic: runtime error: invalid memory address or nil pointer dereference
```

### AWS State
This happens when the network-interface has no security-groups (on AWS). I'm using terraforming to fetch my current aws architecture. Before it was possible to have a network-interface with no security attached, now it's not. I think that's where the problem is.

**Comment by TeaBough** [comment]
PR : https://github.com/hashicorp/terraform/pull/6851

**Comment by catsby** [comment]
Thanks for reporting/fixing this!

**Comment by ivanjaros** [comment]
Just got the same error with the official 0.6.16. Using Virtualbox with Ubuntu 16.4 :(
Any info on 0.6.17?

**Comment by jen20** [comment]
Hi @ivanjaros! I just tried to repro this on `master` (slated for 0.7 release shortly) and saw no crash. We aren't anticipating a 0.6.17 release, but 0.7 will be out soon.

The config I used was:

```
resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_subnet" "test" {
  cidr_block = "10.0.1.0/24"
  vpc_id     = "${aws_vpc.test.id}"
}

resource "aws_network_interface" "eni-53a81d09" {
  subnet_id         = "${aws_subnet.test.id}"
  private_ips       = ["10.0.1.239"]
  security_groups   = []
  source_dest_check = false
  description       = "Primary network interface"
}
```

**Comment by ivanjaros** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x71357a]

goroutine 1 [running]:
panic(0xea9960, 0xc82000e140)
	/opt/go/src/runtime/panic.go:481 +0x3e6
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/hcl/ast.(*ObjectList).Filter(0xc82019c840, 0xc820129248, 0x1, 0x1, 0x2)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/hcl/ast/ast.go:59 +0xaa
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decodeStruct(0xc82012ac60, 0xc82019c800, 0x18, 0x7f47bda5f600, 0xc82019c840, 0xf18fa0, 0xc8201aa690, 0x199, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:603 +0x1d76
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decode(0xc82012ac60, 0xc82019c800, 0x18, 0x7f47bda5f570, 0xc820013720, 0xf18fa0, 0xc8201aa690, 0x199, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:108 +0x9a4
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decodePtr(0xc82012ac60, 0xc82019c800, 0x18, 0x7f47bda5f570, 0xc820013720, 0xc556e0, 0xc82002a320, 0x196, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:397 +0x151
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decode(0xc82012ac60, 0xc82019c800, 0x18, 0x7f47bda5f570, 0xc820013720, 0xc556e0, 0xc82002a320, 0x196, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:102 +0x862
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decodeMap(0xc82012ac60, 0xc820199f40, 0xd, 0x7f47bda5f600, 0xc82019c7a0, 0xca8cc0, 0xc82002a308, 0x195, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:378 +0x14c5
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decode(0xc82012ac60, 0xc820199f40, 0xd, 0x7f47bda5f600, 0xc82019c7a0, 0xca8cc0, 0xc82002a308, 0x195, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:100 +0x7f4
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decodeStruct(0xc82012ac60, 0x104c308, 0x4, 0x7f47bda5f600, 0xc82019c240, 0xcc63c0, 0xc82002a308, 0x199, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:627 +0x22d0
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decode(0xc82012ac60, 0x104c308, 0x4, 0x7f47bda5f600, 0xc82019c240, 0xcc63c0, 0xc82002a308, 0x199, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:108 +0x9a4
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.DecodeObject(0xc80220, 0xc82002a308, 0x7f47bda5f600, 0xc82019c240, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:60 +0x25f
github.com/hashicorp/terraform/config.(*hclConfigurable).Config(0xc82019c700, 0x1043740, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/loader_hcl.go:47 +0x361
github.com/hashicorp/terraform/config.(*importTree).ConfigTree(0xc82019e940, 0x32, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/import_tree.go:87 +0x68
github.com/hashicorp/terraform/config.LoadFile(0xc82019e400, 0x32, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/loader.go:44 +0x80
github.com/hashicorp/terraform/config.LoadDir(0xc8200100f4, 0x26, 0x11, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/loader.go:91 +0x38c
github.com/hashicorp/terraform/config/module.NewTreeModule(0x0, 0x0, 0xc8200100f4, 0x26, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:40 +0x41
github.com/hashicorp/terraform/command.(*Meta).Context(0xc8200b1000, 0xc8200100f4, 0x26, 0x1120060, 0x11, 0x0, 0xa, 0x4, 0xc82019c010, 0x0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta.go:148 +0x509
github.com/hashicorp/terraform/command.(*ApplyCommand).Run(0xc8200b1000, 0xc82000a4f0, 0x0, 0x0, 0xc82010bab0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/apply.go:104 +0xd37
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc8200b6600, 0xc8201963f0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:153 +0x5ee
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:142 +0xb05
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:78 +0xa10
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:21 +0x18
```

**Comment by ivanjaros** [comment]
I get the same issue on Windows 10 desktop(not VM).

**Comment by ivanjaros** [comment]
Also I am using JSON format.

**Comment by ivanjaros** [comment]
Same issue with Terraform 0.7.0-dev. I tried to run terraform validate - same result as well. So I don't know if the config is the issue or terraform execution.
