### ISSUE TITLE
TF crash when attempting to interpolate list off of string when braces are not added

### ISSUE THREAD

**Issue by vancluever** [hashicorp/terraform#6835]
Simple scenario here:

Consider the following config:

```
variable "foo" {
  type = "string"
}

resource "aws_something" "bar" {
  data = "${split(",", var.foo)}"
}
```

If `data` is a list or map value, when `schema.go` attempts to determine if the value is computed or not, it crashes:

```
panic: Unknown kind: string
2016/05/23 10:52:59 [DEBUG] plugin: terraform:
2016/05/23 10:52:59 [DEBUG] plugin: terraform: goroutine 9 [running]:
2016/05/23 10:52:59 [DEBUG] plugin: terraform: panic(0x24323e0, 0xc8205007d0)
2016/05/23 10:52:59 [DEBUG] plugin: terraform:  /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
2016/05/23 10:52:59 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/terraform.(*ResourceConfig).get(0xc820304de0, 0xc820500760, 0x9, 0xc820304e10, 0x0, 0x0, 0x2432301)
2016/05/23 10:52:59 [DEBUG] plugin: terraform:  GOPATH/src/github.com/hashicorp/terraform/terraform/resource.go:212 +0x697
2016/05/23 10:52:59 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/terraform.(*ResourceConfig).IsComputed(0xc820304de0, 0xc820500760, 0x9, 0x5ebb0a8)
2016/05/23 10:52:59 [DEBUG] plugin: terraform:  GOPATH/src/github.com/hashicorp/terraform/terraform/resource.go:149 +0x72
2016/05/23 10:52:59 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.validatePrimitive(0xc8204548d0, 0xc820500760, 0x9, 0x24323e0, 0xc8205001f0, 0xc820388f70, 0xc820304de0, 0x0, 0x0, 0x0, ...)
2016/05/23 10:52:59 [DEBUG] plugin: terraform:  GOPATH/src/github.com/hashicorp/terraform/helper/schema/schema.go:1237 +0x501
2016/05/23 10:52:59 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.validateType(0xc8204548d0, 0xc820500760, 0x9, 0x24323e0, 0xc8205001f0, 0xc820388f70, 0xc820304de0, 0x0, 0x0, 0x0, ...)
2016/05/23 10:52:59 [DEBUG] plugin: terraform:  GOPATH/src/github.com/hashicorp/terraform/helper/schema/schema.go:1297 +0x7d3
2016/05/23 10:52:59 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.validateList(0xc8204548d0, 0x34fcbe0, 0x7, 0x23f4460, 0xc820426860, 0xc820389930, 0xc820304de0, 0x0, 0x0, 0x0, ...)
```

Adding braces fixes the issue:

```
resource "aws_something" "bar" {
  data = ["${split(",", var.foo)}"]
}

```

For what it's worth, this is happening on the `aws_route53_record` resource.

**Comment by eedwardsdisco** [comment]
That's not a bug. Any time you're turning a variable into a list, you need to wrap it in braces.

e.g. valid syntax for a list in terraform HCL:

`soandso = [list]`

the `split` function generates a list, and thus you need to declare the variable it's going to be stored in as a list, by wrapping it in braces

**Comment by vancluever** [comment]
@eedwardsdisco anything that results in a panic (crash) is a TF bug and needs to be reported.

**Comment by eedwardsdisco** [comment]
@vancluever aha :)

**Comment by vancluever** [comment]
Yeah, you are right, it's just that it needs to be caught versus produce a panic. :)

**Comment by mitchellh** [comment]
This no longer crashes and gives a useful error at least:

```
* '[data]' expected type 'string', got unconvertible type '[]interface {}'
```

**Comment by vancluever** [comment]
Thanks @mitchellh!
