### ISSUE TITLE
Crash report from  0.7.0 rc2

### ISSUE THREAD

**Issue by trauts2** [hashicorp/terraform#7170]
### Debug Output

https://gist.github.com/trauts2/6df7d91eb743b0258dc2ab94479f681c

### Panic Output

Gist with debug attached

[crash.log.zip](https://github.com/hashicorp/terraform/files/315275/crash.log.zip)

**Comment by jen20** [comment]
```
2016/06/14 20:30:55 [DEBUG] plugin: terraform: Error creating plan: 2 error(s) occurred:

* unexpected EOF
* unexpected EOF
panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'
2016/06/14 20:30:55 [DEBUG] plugin: terraform:
2016/06/14 20:30:55 [DEBUG] plugin: terraform: goroutine 365 [running]:
2016/06/14 20:30:55 [DEBUG] plugin: terraform: panic(0x2c3c320, 0xc8208644d0)
2016/06/14 20:30:55 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/panic.go:481 +0x3e6
2016/06/14 20:30:55 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc8208ae3c0, 0xc820864400, 0x1, 0x1, 0xc820864402, 0x0, 0x0, 0x0, 0x0, 0x4010000, ...)
2016/06/14 20:30:55 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:443 +0x20a
2016/06/14 20:30:55 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc8208ae3c0, 0x3647370, 0x9, 0xc820861201, 0x0, 0x0, 0x0, 0x0, 0x2e00000, 0x0, ...)
2016/06/14 20:30:55 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:414 +0x235
2016/06/14 20:30:55 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc8208ae3c0, 0x3647370, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/06/14 20:30:55 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:391 +0x78
2016/06/14 20:30:55 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.diffString(0xc820a50bd0, 0x3647370, 0x9, 0xc820cbf0a0, 0xc82097fc70, 0xc8208ae3c0, 0x76334000, 0x0, 0x0)
2016/06/14 20:30:55 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:962 +0xa5
2016/06/14 20:30:55 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc820a50bd0, 0x3647370, 0x9, 0xc820cbf0a0, 0xc82097fc70, 0xc8208ae3c0, 0x0, 0x0, 0x0)
2016/06/14 20:30:55 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:609 +0xaf
2016/06/14 20:30:55 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc820a50bd0, 0xc820b98a80, 0xc820783230, 0xc8208ab950, 0x0, 0x0)
2016/06/14 20:30:55 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:332 +0x22a
2016/06/14 20:30:55 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc820732360, 0xc820b98a80, 0xc820783230, 0xc, 0x0, 0x0)
2016/06/14 20:30:55 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:179 +0x44
2016/06/14 20:30:55 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc820a270e0, 0xc820b98a40, 0xc820b98a80, 0xc820783230, 0x1, 0x0, 0x0)
2016/06/14 20:30:55 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:189 +0x1c5
2016/06/14 20:30:55 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Diff(0xc820a70f20, 0xc8209d5ba0, 0xc82097fc60, 0x0, 0x0)
2016/06/14 20:30:55 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:471 +0x76
```

**Comment by jen20** [comment]
Hi @trauts2! Thanks for reporting this, it is definitely a bug and we need to fix it before the release of 0.7. Is there any chance you could post the configuration that makes this occur, with any sensitive information removed? If not I can have a reasonable guess from the back trace about what may be causing this! Thanks!

**Comment by trauts2** [comment]
Hi James,

In my stumblings I worked around it and don't think I saved the config
state that caused it.  Hope the verbose debug and backtrace get you close.
Next time I'll remember to save off a sanitized set of files.

Amazed by terraform, what you and crew are building is brilliant and
elegant.  Thanks!

Stu

**Comment by phinze** [comment]
Hi folks! I've got two reproduction cases that produce this backtrace, one during `plan` and the other during `apply`.

This one crashes during plan, like the original report:

```tf
data "aws_availability_zones" "instance" { }

resource "aws_instance" "foo" {
  ami = "ami-lolidk"
  instance_type = "t2.nano"
  # whoops here is a string field referencing the whole list of AZs
  availability_zone = "${data.aws_availability_zones.instance.names}"
}
```

And this one doesn't involve a data source but has a similar shape - it crashes during apply:

```tf
resource "aws_elb" "elb" {
  availability_zones = ["us-east-1a"]
  listener {
    instance_port = 80
    instance_protocol = "http"
    lb_port = 80
    lb_protocol = "http"
  }
}

resource "aws_instance" "foo" {
  ami = "ami-lolidk"
  instance_type = "t2.nano"
  # this doesn't make sense but it was the first computed list attribute i found :)
  availability_zone = "${aws_elb.elb.instances}"
}
```

Digging into a fix now!
