### ISSUE TITLE
Crash on terraform apply

### ISSUE THREAD

**Issue by ACluelessOne** [hashicorp/terraform#7535]
Hi there,

### Terraform Version
Terraform version 0.6.16

### Terraform Configuration Files
vsphere.tf

```
module "vsphere-dc" {
  source = "./terraform/vsphere"
  long_name = ""
  short_name = "mantl"
  datacenter = "Intern2016"
  cluster = "First-Cluster"
  pool = "" # format is cluster_name/Resources/pool_name
  template = "CentOS-tem"
  network_label = "VM Network"
  domain = ""
  dns_server1 = ""
  dns_server2 = ""
  datastore = "datastore"
  control_count = 1
  worker_count = 1
  edge_count = 1
  kubeworker_count = 0
  control_volume_size = 20 # size in gigabytes
  worker_volume_size = 20
  edge_volume_size = 20
  ssh_user = "root"
  ssh_key = "~/.ssh/id_rsa"
  consul_dc = "mantl"

  #Optional Parameters
  #folder = "Mantl"
  #control_cpu = "2"
  #worker_cpu = "4"
  #edge_cpu = "2"
  #control_ram = "4096"
  #worker_ram = "10240"
  #edge_ram = "4096"
  #disk_type = "" # thin or eager_zeored, default is thin
  #linked_clone = "" # true or false, default is false.  If using link$
}
```

### Debug Output
https://gist.githubusercontent.com/ACluelessOne/01577a9d948e94df0c3c25db83ef2338/raw/3079762ee8411d8b96b6eafdc890a8a6132a5933/crash.log

### Expected Behavior
Completion

### Actual Behavior
Unexpected EOF for all the nodes

### Steps to Reproduce
terraform get
terraform plan
terraform apply

**Comment by stack72** [comment]
Pulling out the crash from the log

```
2016/07/07 13:12:11 [DEBUG] apply: vsphere_virtual_machine.mi-worker-nodes: executing Apply
2016/07/07 13:12:11 [DEBUG] terraform-provider-vsphere: panic: interface conversion: interface is nil, not string
2016/07/07 13:12:11 [DEBUG] terraform-provider-vsphere: 
2016/07/07 13:12:11 [DEBUG] terraform-provider-vsphere: goroutine 75 [running]:
2016/07/07 13:12:11 [DEBUG] terraform-provider-vsphere: panic(0x11ce840, 0xc82047e180)
2016/07/07 13:12:11 [DEBUG] terraform-provider-vsphere: 	/opt/go/src/runtime/panic.go:481 +0x3e6
2016/07/07 13:12:11 [DEBUG] terraform-provider-vsphere: github.com/hashicorp/terraform/builtin/providers/vsphere.resourceVSphereVirtualMachineCreate(0xc820014360, 0x13fc1c0, 0xc82044bf60, 0x0, 0x0)
2016/07/07 13:12:11 [DEBUG] terraform-provider-vsphere: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/vsphere/resource_vsphere_virtual_machine.go:557 +0xb61
2016/07/07 13:12:11 [DEBUG] terraform-provider-vsphere: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc820419d80, 0xc8204b0480, 0xc8204ae8f0, 0x13fc1c0, 0xc82044bf60, 0xc82049c101, 0x0, 0x0)
2016/07/07 13:12:11 [DEBUG] terraform-provider-vsphere: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:146 +0x29e
2016/07/07 13:12:11 [DEBUG] terraform-provider-vsphere: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc820426d20, 0xc820444b80, 0xc8204b0480, 0xc8204ae8f0, 0x1, 0x0, 0x0)
2016/07/07 13:12:11 [DEBUG] terraform-provider-vsphere: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:162 +0x1ed
2016/07/07 13:12:11 [DEBUG] terraform-provider-vsphere: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Apply(0xc820430000, 0xc8204a28c0, 0xc8204aecf0, 0x0, 0x0)
```

**Comment by jare19** [comment]
I think you have the answer there in your log snippit. 

> panic: interface conversion: interface is nil, not string

I would guess that one of your interfaces do not have an IP

**Comment by ACluelessOne** [comment]
Does this mean my template does not have any IP address?
Sorry but im new to this.

**Comment by catsby** [comment]
I _believe_ this could be caused by the empty `dns_server` tries:

```
  dns_server1 = ""
  dns_server2 = ""
```

Is that correct usage for the module? Do they get a default value if you omit them?

**Comment by ACluelessOne** [comment]
thanks. it is due to the unfilled DNS server. After including the correct dns it is solved
