### ISSUE TITLE
Reporting crash

### ISSUE THREAD

**Issue by Tomino2112** [hashicorp/terraform#7715]
Hi, reporting crash log
### Terraform Version

0.6.16
### Panic Output

https://gist.github.com/Tomino2112/d250f7560ab886a43f9b1e8365183def

**Comment by Tomino2112** [comment]
Just realized, this is happening when im trying to assignelastic ip to instance.

I tried:

```
associate_public_ip_address = "${aws_eip.vpn.id}"
```

and 

```
associate_public_ip_address = "${aws_eip.vpn.public_ip}"
```

Both give same error

**Comment by stack72** [comment]
Hi @Tomino2112 

My apologies here for the issue. Sorry if this has caused issues for you. The issue here is that `associate_public_ip_address` actually accepts a boolean. It should be `true` or `false`, not the actual IP address

Thanks

Paul

**Comment by stack72** [comment]
Panic output:

```
016/07/20 16:12:06 [DEBUG] terraform-provider-aws.exe: panic: Error reading level config: strconv.ParseBool: parsing "${aws_eip.vpn.id}": invalid syntax
2016/07/20 16:12:06 [DEBUG] terraform-provider-aws.exe: 
2016/07/20 16:12:06 [DEBUG] terraform-provider-aws.exe: goroutine 492 [running]:
2016/07/20 16:12:06 [DEBUG] terraform-provider-aws.exe: panic(0x14050c0, 0xc0824f3c60)
2016/07/20 16:12:06 [DEBUG] terraform-provider-aws.exe:     /opt/go/src/runtime/panic.go:481 +0x3f4
2016/07/20 16:12:06 [DEBUG] terraform-provider-aws.exe: github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc08229e6c0, 0xc0824f3b70, 0x1, 0x1, 0xc0824f3b02, 0x0, 0x0, 0x0, 0x0, 0x410000, ...)
2016/07/20 16:12:06 [DEBUG] terraform-provider-aws.exe:     /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:394 +0x211
2016/07/20 16:12:06 [DEBUG] terraform-provider-aws.exe: github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc08229e6c0, 0x188bc80, 0x1b, 0xc0824f1201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/07/20 16:12:06 [DEBUG] terraform-provider-aws.exe:     /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:365 +0x23c
2016/07/20 16:12:06 [DEBUG] terraform-provider-aws.exe: github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc08229e6c0, 0x188bc80, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/07/20 16:12:06 [DEBUG] terraform-provider-aws.exe:     /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:342 +0x7f
```

**Comment by Tomino2112** [comment]
I see,  so it creates the IP automatically?

**Comment by stack72** [comment]
Hi @Tomino2112 

yes, it will create it automatically. But when it creates a public ip like that, the IP can change on machine reboot. Therefore, your idea of using an EIP was correct.

You can do it like this:

```
resource "aws_eip" "vpn" {
  instance = "${aws_instance.web.id}"
}

resource "aws_instance" "vpn" {
  ....
}
```

**Comment by Tomino2112** [comment]
Aha!  Didnt know i can assign ip to instance in the eip block.  Actually i ran into quite a few issues with our config,  any chace i could pick your brain for a bit?

**Comment by Tomino2112** [comment]
Another crash log:

https://gist.github.com/Tomino2112/3f7d1e756c6d1e5e0edad86617e040bb

**Comment by mitchellh** [comment]
Reproduced this crash, taking a look.

**Comment by mitchellh** [comment]
Minimal repro, reproduces on `terraform plan`:

```
resource "aws_eip" "vpn" {}

resource "aws_instance" "fo" {
  ami = "foo"
  instance_type = "bar"
  associate_public_ip_address = "${aws_eip.vpn.id}"
}
```
