### ISSUE TITLE
crash with "panic: Unknown type in count var"

### ISSUE THREAD

**Issue by akoeb-zalando** [hashicorp/terraform#8132]
terraform validate crashes on wrong variable usage inside a count assignment.

### Terraform Version

    ```
    $ terraform -v
    2016/08/11 13:18:51 [INFO] Terraform version: 0.7.0  e822a79165dbc06bbf8271ee349fe256867d53dc
    ```

### Affected Resource(s)

seen with aws_ebs_volume and aws_ebs_volume_attachment, probably others.

### Terraform Configuration Files

This is the code that produced the crash:

    count = "${length(var.map1) * length(map2)}"

This is the code that does not crash:

    count = "${length(var.map1) * length(var.map2)}"

(Note the wrong variable usage in the first example, both are list variables)

### Debug Output

```
$ terraform validate 
2016/08/11 13:17:15 [INFO] Terraform version: 0.7.0  e822a79165dbc06bbf8271ee349fe256867d53dc
2016/08/11 13:17:15 [DEBUG] Detected home directory from env var: /home/akoeb
2016/08/11 13:17:15 [DEBUG] Detected home directory from env var: /home/akoeb
2016/08/11 13:17:15 [DEBUG] Attempting to open CLI config file: /home/akoeb/.terraformrc
2016/08/11 13:17:15 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2016/08/11 13:17:15 [DEBUG] Detected home directory from env var: /home/akoeb
2016/08/11 13:17:15 [DEBUG] plugin: waiting for all plugin processes to complete...
panic: Unknown type in count var: aws_volume_attachment.ebs_att

goroutine 1 [running]:
panic(0x2a76840, 0xc820388e00)
	/opt/go/src/runtime/panic.go:481 +0x3e6
github.com/hashicorp/terraform/config.(*Config).Validate(0xc8201ef340, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/config.go:474 +0x59bb
github.com/hashicorp/terraform/command.(*ValidateCommand).validate(0xc8202162d0, 0xc8202ff000, 0x36, 0x36)
	/opt/gopath/src/github.com/hashicorp/terraform/command/validate.go:52 +0x1df
github.com/hashicorp/terraform/command.(*ValidateCommand).Run(0xc8202162d0, 0xc82000a4d0, 0x0, 0x0, 0xc8202f4070)
	/opt/gopath/src/github.com/hashicorp/terraform/command/validate.go:36 +0x277
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc8201de840, 0xc8201ff950, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:153 +0x56e
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:144 +0xaf9
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:80 +0xa10
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:23 +0x28
panic: Unknown type in count var: aws_volume_attachment.ebs_att

goroutine 1 [running]:
panic(0x2a76840, 0xc820388e00)
	/opt/go/src/runtime/panic.go:481 +0x3e6
github.com/hashicorp/terraform/config.(*Config).Validate(0xc8201ef340, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/config.go:474 +0x59bb
github.com/hashicorp/terraform/command.(*ValidateCommand).validate(0xc8202162d0, 0xc8202ff000, 0x36, 0x36)
	/opt/gopath/src/github.com/hashicorp/terraform/command/validate.go:52 +0x1df
github.com/hashicorp/terraform/command.(*ValidateCommand).Run(0xc8202162d0, 0xc82000a4d0, 0x0, 0x0, 0xc8202f4070)
	/opt/gopath/src/github.com/hashicorp/terraform/command/validate.go:36 +0x277
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc8201de840, 0xc8201ff950, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:153 +0x56e
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:144 +0xaf9
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:80 +0xa10
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:23 +0x28

```
### Panic Output

```
panic: Unknown type in count var: aws_volume_attachment.ebs_att

goroutine 1 [running]:
panic(0x2a76840, 0xc820388e00)
        /opt/go/src/runtime/panic.go:481 +0x3e6
github.com/hashicorp/terraform/config.(*Config).Validate(0xc8201ef340, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/config.go:474 +0x59bb
github.com/hashicorp/terraform/command.(*ValidateCommand).validate(0xc8202162d0, 0xc8202ff000, 0x36, 0x36)
        /opt/gopath/src/github.com/hashicorp/terraform/command/validate.go:52 +0x1df
github.com/hashicorp/terraform/command.(*ValidateCommand).Run(0xc8202162d0, 0xc82000a4d0, 0x0, 0x0, 0xc8202f4070)
        /opt/gopath/src/github.com/hashicorp/terraform/command/validate.go:36 +0x277
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc8201de840, 0xc8201ff950, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:153 +0x56e
main.wrappedMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:144 +0xaf9
main.realMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:80 +0xa10
main.main()
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:23 +0x28

```

### Expected Behavior

not crash but produce error message with line number

### Actual Behavior

it crashes

**Comment by mitchellh** [comment]
This is fixed with #8243
