### ISSUE TITLE
crash when importing aws_route_table

### ISSUE THREAD

**Issue by drscre** [hashicorp/terraform#8225]
Terraform v0.7.0 crashes when i try to import aws_route_table resource:
```terraform import aws_route_table.private <my_route_table_id>```

crash.log:
https://gist.github.com/drscre/1b7994cadb588924ce627b2487e985a9

**Comment by mitchellh** [comment]
I can see how this is possible but unclear what exactly caused it. Do you mind showing me your AWS route table + all routes? (Properties in AWS console are good).

**Comment by drscre** [comment]
The original problematic route table is now gone, but it was similar to this (maybe the problem is s3 enpoint ? ):
![route_table](https://cloud.githubusercontent.com/assets/844519/17752752/f040eada-64d5-11e6-957b-7dbdb8e6b4d1.png)

**Comment by mitchellh** [comment]
I feel very strongly that the S3 endpoint is it. I didn't realize that was possible. But I am pretty sure we don't handle that well at all.

**Comment by brianbianco** [comment]
I run into this exact problem when trying to import a route table that uses s3 endpoints.

Here is what my route table looks like:

<img width="544" alt="screen shot 2016-08-18 at 1 43 34 pm" src="https://cloud.githubusercontent.com/assets/523384/17784390/5e1c4972-654a-11e6-9154-17325646aa53.png">

```
$ terraform import aws_route_table.public rtb-473fb622
aws_route_table.public: Importing from ID "rtb-473fb622"...
Error importing: 1 error(s) occurred:

* import aws_route_table.public (id: rtb-473fb622): unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
2016/08/18 13:45:42 [DEBUG] plugin: terraform: [signal 0xb code=0x1 addr=0x0 pc=0x55d526]
2016/08/18 13:45:42 [DEBUG] plugin: terraform:
2016/08/18 13:45:42 [DEBUG] plugin: terraform: goroutine 104 [running]:
2016/08/18 13:45:42 [DEBUG] plugin: terraform: panic(0x2fb1ba0, 0xc8200120e0)
2016/08/18 13:45:42 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/panic.go:481 +0x3e6
2016/08/18 13:45:42 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/aws.routeIDHash(0xc820460d80, 0xc82062eff0, 0x0, 0x0)
2016/08/18 13:45:42 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route.go:362 +0xa6
2016/08/18 13:45:42 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsRouteTableImportState(0xc8204600c0, 0x253e380, 0xc820492000, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/08/18 13:45:42 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/import_aws_route_table.go:48 +0xf57
2016/08/18 13:45:42 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).ImportState(0xc8203f1a40, 0xc820472640, 0xc8205c5de0, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/08/18 13:45:42 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:254 +0x496
2016/08/18 13:45:42 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ImportState(0xc820140ce0, 0xc820662880, 0xc820662ba0, 0x0, 0x0)
2016/08/18 13:45:42 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:493 +0x86
2016/08/18 13:45:42 [DEBUG] plugin: terraform: reflect.Value.call(0x2c6c4c0, 0x3650678, 0x13, 0x37c3bf8, 0x4, 0xc8206bded8, 0x3, 0x3, 0x0, 0x0, ...)
2016/08/18 13:45:42 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:435 +0x120d
2016/08/18 13:45:42 [DEBUG] plugin: terraform: reflect.Value.Call(0x2c6c4c0, 0x3650678, 0x13, 0xc8206bded8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/08/18 13:45:42 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:303 +0xb1
2016/08/18 13:45:42 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc820360500, 0xc8203604c0, 0xc8203581b8, 0xc820370300, 0xc820362140, 0x2540cc0, 0xc820662880, 0x16, 0x2540d20, 0xc820662ba0, ...)
2016/08/18 13:45:42 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:383 +0x1c2
2016/08/18 13:45:42 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2016/08/18 13:45:42 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:477 +0x49d
2016/08/18 13:45:42 [ERROR] root: eval: *terraform.EvalImportState, err: import aws_route_table.public (id: rtb-473fb622): unexpected EOF
2016/08/18 13:45:42 [ERROR] root: eval: *terraform.EvalSequence, err: import aws_route_table.public (id: rtb-473fb622): unexpected EOF
2016/08/18 13:45:42 [TRACE] [walkImport] Exiting eval tree: aws_route_table.public (import id: rtb-473fb622)
2016/08/18 13:45:42 [DEBUG] vertex provider.aws (close), got dep: aws_route_table.public (import id: rtb-473fb622)
2016/08/18 13:45:42 [DEBUG] plugin: /usr/local/bin/terraform: plugin process exited
2016/08/18 13:45:42 [DEBUG] plugin: waiting for all plugin processes to complete...



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by catsby** [comment]
The error is coming from `routeIDHash`, I suspect this route 

```
          DestinationPrefixListId: "pl-68a54001",
          GatewayId: "vpce-8ec521e7",
          Origin: "CreateRoute",
          State: "active"
```

does not have a `DestinationCidrBlock`

- https://github.com/hashicorp/terraform/blob/6a2e568063f1b474314d8d30433b171e2215be26/builtin/providers/aws/resource_aws_route.go#L362

**Comment by brianbianco** [comment]
@catsby Right that's what I was saying in my previous comment.  The routeHashID function looks for DestinationCidrBlock but there isn't one.  I tried changing the code to simply use DestinationPrefixListId if CidrBlock doesn't exist.  The import gets further but still ends up failing with the following:

```
aws_route_table.public: Importing from ID "rtb-473fb622"...
aws_route_table.public: Import complete!
  Imported aws_route_table (ID: rtb-473fb622)
  Imported aws_route (ID: r-rtb-473fb6221080289494)
  Imported aws_route (ID: r-rtb-473fb6222319287420)
  Imported aws_route_table_association (ID: rtbassoc-b129b1d4)
  Imported aws_route_table_association (ID: rtbassoc-ac29b1c9)
  Imported aws_route_table_association (ID: rtbassoc-d829b1bd)
  Imported aws_main_route_table_association (ID: rtbassoc-5529b130)
aws_route.public-1: Refreshing state... (ID: r-rtb-473fb6222319287420)
aws_route_table.public: Refreshing state... (ID: rtb-473fb622)
aws_route.public: Refreshing state... (ID: r-rtb-473fb6221080289494)
aws_main_route_table_association.public: Refreshing state... (ID: rtbassoc-5529b130)
aws_route_table_association.public-1: Refreshing state... (ID: rtbassoc-ac29b1c9)
aws_route_table_association.public: Refreshing state... (ID: rtbassoc-b129b1d4)
aws_route_table_association.public-2: Refreshing state... (ID: rtbassoc-d829b1bd)
Error importing: 1 error(s) occurred:

* import aws_route.public-1 (id: r-rtb-473fb6222319287420): Terraform detected a resource with this ID doesn't
exist. Please verify the ID is correct. You cannot import non-existent
resources using Terraform import.
```

I was in the process of trying to track down how imports work exactly to see if somehow its local state was calculating it's ID with a different function?

**Comment by brianbianco** [comment]
@catsby Sorry to be clear, that route doesn't have a destination cidr block because it is a route for an s3 vpc endpoint.  It isn't supposed to have one, but is still a valid route.

**Comment by brianbianco** [comment]
@catsby If you are viewing the issues in email, I have edited and updated my comments a bunch which may not be coming through in email updates.

**Comment by catsby** [comment]
@brianbianco understood, thanks! We appreciate all the info, we'll dig in 😄

**Comment by brianbianco** [comment]
@catsby is there any update on the status of import issues related to route tables?

**Comment by cread** [comment]
I've also just had this crash with version 0.7.4.

**Comment by sammysammy** [comment]
Hi I've also just had this issue - same with 0.7.4 and 0.7.5 - also includes a VPC endpoint

**Comment by ewbankkit** [comment]
Same in *0.7.8-dev*.
