### ISSUE TITLE
aws_route53_record create panic

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#8393]
### Terraform Version

v0.7.1

### Affected Resource(s)

 - aws_route53_record

### Terraform Configuration Files

Accidentally created two text records for the same key:

```hcl
resource "aws_route53_record" "one" {
  zone_id = "${aws_route53_zone.zone.id}"
  name    = "${var.domain}"
  type    = "TXT"
  ttl     = "300"
  records = ["one"]
}
resource "aws_route53_record" "two" {
  zone_id = "${aws_route53_zone.zone.id}"
  name    = "${var.domain}"
  type    = "TXT"
  ttl     = "300"
  records = ["two"]
}
```

### Panic Output

```
panic: interface conversion: interface {} is nil, not *route53.ChangeResourceRecordSetsOutput
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws:
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws: goroutine 486 [running]:
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws: panic(0xe5bb20, 0xc4206fecc0)
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws:     /Users/phinze/.gimme/versions/go1.7.darwin.amd64/src/runtime/panic.go:500 +0x1a1
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsRoute53RecordCreate(0xc4206ca9c0, 0xd16c20, 0xc42039e300, 0xe5fb60, 0xcaf1)
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws:     /Users/phinze/go/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route53_record.go:274 +0xb0a
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4206f0f00, 0xc42046d1c0, 0xc4202dbe00, 0xd16c20, 0xc42039e300, 0x1, 0xc4207206f0, 0x0)
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws:     /Users/phinze/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:162 +0x30e
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4206edf50, 0xc42046d180, 0xc42046d1c0, 0xc4202dbe00, 0x0, 0x18, 0x18)
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws:     /Users/phinze/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:176 +0x9b
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4202daf40, 0xc4202db640, 0xc4203c5fc0, 0x0, 0x0)
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws:     /Users/phinze/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:460 +0x57
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws: reflect.Value.call(0xc4203083c0, 0xc4205e8960, 0x13, 0x1020230, 0x4, 0xc42073fee0, 0x3, 0x3, 0xc4205c4e01, 0xc4205c4ea0, ...)
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws:     /Users/phinze/.gimme/versions/go1.7.darwin.amd64/src/reflect/value.go:434 +0x5c8
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws: reflect.Value.Call(0xc4203083c0, 0xc4205e8960, 0x13, 0xc42073fee0, 0x3, 0x3, 0x1, 0xc4204a7560, 0x20003)
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws:     /Users/phinze/.gimme/versions/go1.7.darwin.amd64/src/reflect/value.go:302 +0xa4
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws: net/rpc.(*service).call(0xc420017d40, 0xc420016680, 0xc42045c7c0, 0xc42031e780, 0xc4202d1140, 0xd177a0, 0xc4202db640, 0x16, 0xd177e0, 0xc4203c5fc0, ...)
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws:     /Users/phinze/.gimme/versions/go1.7.darwin.amd64/src/net/rpc/server.go:383 +0x148
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws: created by net/rpc.(*Server).ServeCodec
2016/08/22 12:29:14 [DEBUG] plugin: terraform-provider-aws:     /Users/phinze/.gimme/versions/go1.7.darwin.amd64/src/net/rpc/server.go:477 +0x421
```

### Expected Behavior

Probably just an error during apply.

### Actual Behavior

Kaboom!

### Steps to Reproduce

1. `terraform apply`

**Comment by stack72** [comment]
Closed via #8399
