### ISSUE TITLE
Crash when looking up amis in multiple regions

### ISSUE THREAD

**Issue by kojiromike** [hashicorp/terraform#9061]
### Terraform Version
Terraform v0.7.4

### Affected Resource(s)
- aws_ami (data, not resource)

### Terraform Configuration Files
```hcl
provider "aws" {
  alias  = "us-west-1"
  region = "us-west-1"
}
provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
}
provider "aws" {
  alias  = "us-west-2"
  region = "us-west-2"
}
data "aws_ami" "ubuntu_uw1_latest" {
  provider    = "aws.us-west-1"
  most_recent = true
  name_regex  = "^ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-\\d+"
  owners      = ["099720109477"]
}
data "aws_ami" "ubuntu_ue1_latest" {
  provider    = "aws.us-east-1"
  most_recent = true
  name_regex  = "^ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-\\d+"
  owners      = ["099720109477"]
}
data "aws_ami" "ubuntu_uw2_latest" {
  provider    = "aws.us-west-2"
  most_recent = true
  name_regex  = "^ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-\\d+"
  owners      = ["099720109477"]
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
[crash.log](https://gist.github.com/kojiromike/3099f729a585090ea3d749fc56fb4389)

### Expected Behavior
What should have happened?

Terraform should've compiled a list of AMIs; one per region/provider.

### Actual Behavior
What actually happened?

`SIGSEGV`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan` with the above config.

**Comment by stack72** [comment]
Hi @kojiromike 

Apologies for the issue here. Luckily, this has already been fixed in master. You can thank @kwilczynski for his awesome work in #9033 for the fix :)

In 0.7.4, I get the following using your config:

```
% terraform apply
data.aws_ami.ubuntu_uw1_latest: Refreshing state...
data.aws_ami.ubuntu_uw2_latest: Refreshing state...
data.aws_ami.ubuntu_ue1_latest: Refreshing state...
Error refreshing state: 3 error(s) occurred:

* data.aws_ami.ubuntu_uw2_latest: unexpected EOF
* data.aws_ami.ubuntu_ue1_latest: unexpected EOF
* data.aws_ami.ubuntu_uw1_latest: unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
2016/09/26 19:34:22 [DEBUG] plugin: terraform: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2b7c17]
2016/09/26 19:34:22 [DEBUG] plugin: terraform:
2016/09/26 19:34:22 [DEBUG] plugin: terraform: goroutine 162 [running]:
2016/09/26 19:34:22 [DEBUG] plugin: terraform: panic(0x249f340, 0x424c44070)
2016/09/26 19:34:22 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/panic.go:500 +0x1a1
2016/09/26 19:34:22 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/aws.dataSourceAwsAmiRead(0x4250eb260, 0x21fcee0, 0x425450000, 0xea00000000000007, 0x0)
2016/09/26 19:34:22 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/data_source_aws_ami.go:242 +0x387
2016/09/26 19:34:22 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0x4250ea540, 0x42568e000, 0x21fcee0, 0x425450000, 0x424c8d0c8, 0x1, 0x18)
2016/09/26 19:34:22 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:207 +0xda
2016/09/26 19:34:22 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0x42512bda0, 0x425659840, 0x42568e000, 0x0, 0x9b7467, 0x424e162a0)
2016/09/26 19:34:22 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:317 +0x91
2016/09/26 19:34:22 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ReadDataApply(0x424dacb60, 0x42566cf50, 0x42566d460, 0x0, 0x0)
2016/09/26 19:34:22 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:537 +0x4e
2016/09/26 19:34:22 [DEBUG] plugin: terraform: reflect.Value.call(0x424ca4d80, 0x424c5e500, 0x13, 0x2a63bf3, 0x4, 0x425685ed0, 0x3, 0x3, 0x0, 0x0, ...)
2016/09/26 19:34:22 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:434 +0x5c8
2016/09/26 19:34:22 [DEBUG] plugin: terraform: reflect.Value.Call(0x424ca4d80, 0x424c5e500, 0x13, 0x425685ed0, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/09/26 19:34:22 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:302 +0xa4
2016/09/26 19:34:22 [DEBUG] plugin: terraform: net/rpc.(*service).call(0x424e57a40, 0x424e57a00, 0x4250a7f00, 0x42505b500, 0x424c43f80, 0x21fee60, 0x42566cf50, 0x16, 0x21feea0, 0x42566d460, ...)
2016/09/26 19:34:22 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:383 +0x148
2016/09/26 19:34:22 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2016/09/26 19:34:22 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:477 +0x421
2016/09/26 19:34:22 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.aws_ami.ubuntu_uw2_latest: unexpected EOF
2016/09/26 19:34:22 [ERROR] root: eval: *terraform.EvalSequence, err: data.aws_ami.ubuntu_uw2_latest: unexpected EOF
2016/09/26 19:34:22 [ERROR] root: eval: *terraform.EvalOpFilter, err: data.aws_ami.ubuntu_uw2_latest: unexpected EOF
2016/09/26 19:34:22 [ERROR] root: eval: *terraform.EvalSequence, err: data.aws_ami.ubuntu_uw2_latest: unexpected EOF
2016/09/26 19:34:22 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.aws_ami.ubuntu_ue1_latest: unexpected EOF
2016/09/26 19:34:22 [TRACE] [walkRefresh] Exiting eval tree: data.aws_ami.ubuntu_uw2_latest
2016/09/26 19:34:22 [ERROR] root: eval: *terraform.EvalSequence, err: data.aws_ami.ubuntu_ue1_latest: unexpected EOF
2016/09/26 19:34:22 [ERROR] root: eval: *terraform.EvalOpFilter, err: data.aws_ami.ubuntu_ue1_latest: unexpected EOF
2016/09/26 19:34:22 [ERROR] root: eval: *terraform.EvalSequence, err: data.aws_ami.ubuntu_ue1_latest: unexpected EOF
2016/09/26 19:34:22 [TRACE] [walkRefresh] Exiting eval tree: data.aws_ami.ubuntu_ue1_latest
2016/09/26 19:34:22 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.aws_ami.ubuntu_uw1_latest: unexpected EOF
2016/09/26 19:34:22 [ERROR] root: eval: *terraform.EvalSequence, err: data.aws_ami.ubuntu_uw1_latest: unexpected EOF
2016/09/26 19:34:22 [ERROR] root: eval: *terraform.EvalOpFilter, err: data.aws_ami.ubuntu_uw1_latest: unexpected EOF
2016/09/26 19:34:22 [ERROR] root: eval: *terraform.EvalSequence, err: data.aws_ami.ubuntu_uw1_latest: unexpected EOF
2016/09/26 19:34:22 [TRACE] [walkRefresh] Exiting eval tree: data.aws_ami.ubuntu_uw1_latest
2016/09/26 19:34:22 [DEBUG] vertex provider.aws.us-east-1 (close), got dep: data.aws_ami.ubuntu_ue1_latest
2016/09/26 19:34:22 [DEBUG] vertex provider.aws.us-west-2 (close), got dep: data.aws_ami.ubuntu_uw2_latest
2016/09/26 19:34:22 [DEBUG] vertex provider.aws.us-west-1 (close), got dep: data.aws_ami.ubuntu_uw1_latest
2016/09/26 19:34:22 [DEBUG] vertex provider.aws.us-west-1 (close), got dep: provider.aws.us-west-1
2016/09/26 19:34:22 [DEBUG] vertex root, got dep: provider.aws.us-east-1 (close)
2016/09/26 19:34:22 [DEBUG] vertex root, got dep: provider.aws.us-west-1 (close)
2016/09/26 19:34:22 [DEBUG] vertex root, got dep: provider.aws.us-west-2 (close)
2016/09/26 19:34:22 [DEBUG] plugin: /Users/stacko/Code/go/bin/terraform: plugin process exited
2016/09/26 19:34:22 [DEBUG] plugin: waiting for all plugin processes to complete...



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

In master, I get the following:

```
% terraform apply                                                                                                                                                                                       2 ↵
[WARN] /Users/stacko/Code/go/bin/terraform-provider-aws overrides an internal plugin for aws-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
data.aws_ami.ubuntu_uw2_latest: Refreshing state...
data.aws_ami.ubuntu_ue1_latest: Refreshing state...
data.aws_ami.ubuntu_uw1_latest: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
[stacko@Pauls-MacBook-Pro:~/Code/terraform-recreations/9061]
% terraform show
[WARN] /Users/stacko/Code/go/bin/terraform-provider-aws overrides an internal plugin for aws-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
data.aws_ami.ubuntu_ue1_latest:
  id = ami-864d84ee
  architecture = x86_64
  block_device_mappings.# = 3
  block_device_mappings.1634610537.device_name = /dev/sdb
  block_device_mappings.1634610537.ebs.% = 0
  block_device_mappings.1634610537.no_device =
  block_device_mappings.1634610537.virtual_name = ephemeral0
  block_device_mappings.2547816212.device_name = /dev/sda1
  block_device_mappings.2547816212.ebs.% = 6
  block_device_mappings.2547816212.ebs.delete_on_termination = true
  block_device_mappings.2547816212.ebs.encrypted = false
  block_device_mappings.2547816212.ebs.iops = 0
  block_device_mappings.2547816212.ebs.snapshot_id = snap-a8eef902
  block_device_mappings.2547816212.ebs.volume_size = 8
  block_device_mappings.2547816212.ebs.volume_type = gp2
  block_device_mappings.2547816212.no_device =
  block_device_mappings.2547816212.virtual_name =
  block_device_mappings.3850042718.device_name = /dev/sdc
  block_device_mappings.3850042718.ebs.% = 0
  block_device_mappings.3850042718.no_device =
  block_device_mappings.3850042718.virtual_name = ephemeral1
  creation_date = 2014-07-23T18:03:03.000Z
  hypervisor = xen
  image_id = ami-864d84ee
  image_location = 099720109477/ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20140607.1
  image_type = machine
  most_recent = true
  name = ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20140607.1
  name_regex = ^ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-\d+
  owner_id = 099720109477
  owners.# = 1
  owners.0 = 099720109477
  product_codes.# = 0
  public = true
  root_device_name = /dev/sda1
  root_device_type = ebs
  sriov_net_support = simple
  state = available
  state_reason.% = 2
  state_reason.code = UNSET
  state_reason.message = UNSET
  tags.# = 0
  virtualization_type = hvm
data.aws_ami.ubuntu_uw1_latest:
  id = ami-a7fdfee2
  architecture = x86_64
  block_device_mappings.# = 3
  block_device_mappings.1634610537.device_name = /dev/sdb
  block_device_mappings.1634610537.ebs.% = 0
  block_device_mappings.1634610537.no_device =
  block_device_mappings.1634610537.virtual_name = ephemeral0
  block_device_mappings.2547816212.device_name = /dev/sda1
  block_device_mappings.2547816212.ebs.% = 6
  block_device_mappings.2547816212.ebs.delete_on_termination = true
  block_device_mappings.2547816212.ebs.encrypted = false
  block_device_mappings.2547816212.ebs.iops = 0
  block_device_mappings.2547816212.ebs.snapshot_id = snap-56475e99
  block_device_mappings.2547816212.ebs.volume_size = 8
  block_device_mappings.2547816212.ebs.volume_type = gp2
  block_device_mappings.2547816212.no_device =
  block_device_mappings.2547816212.virtual_name =
  block_device_mappings.3850042718.device_name = /dev/sdc
  block_device_mappings.3850042718.ebs.% = 0
  block_device_mappings.3850042718.no_device =
  block_device_mappings.3850042718.virtual_name = ephemeral1
  creation_date = 2014-07-23T18:11:54.000Z
  hypervisor = xen
  image_id = ami-a7fdfee2
  image_location = 099720109477/ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20140607.1
  image_type = machine
  most_recent = true
  name = ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20140607.1
  name_regex = ^ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-\d+
  owner_id = 099720109477
  owners.# = 1
  owners.0 = 099720109477
  product_codes.# = 0
  public = true
  root_device_name = /dev/sda1
  root_device_type = ebs
  sriov_net_support = simple
  state = available
  state_reason.% = 2
  state_reason.code = UNSET
  state_reason.message = UNSET
  tags.# = 0
  virtualization_type = hvm
data.aws_ami.ubuntu_uw2_latest:
  id = ami-e7b8c0d7
  architecture = x86_64
  block_device_mappings.# = 3
  block_device_mappings.1634610537.device_name = /dev/sdb
  block_device_mappings.1634610537.ebs.% = 0
  block_device_mappings.1634610537.no_device =
  block_device_mappings.1634610537.virtual_name = ephemeral0
  block_device_mappings.2547816212.device_name = /dev/sda1
  block_device_mappings.2547816212.ebs.% = 6
  block_device_mappings.2547816212.ebs.delete_on_termination = true
  block_device_mappings.2547816212.ebs.encrypted = false
  block_device_mappings.2547816212.ebs.iops = 0
  block_device_mappings.2547816212.ebs.snapshot_id = snap-5ebe82aa
  block_device_mappings.2547816212.ebs.volume_size = 8
  block_device_mappings.2547816212.ebs.volume_type = gp2
  block_device_mappings.2547816212.no_device =
  block_device_mappings.2547816212.virtual_name =
  block_device_mappings.3850042718.device_name = /dev/sdc
  block_device_mappings.3850042718.ebs.% = 0
  block_device_mappings.3850042718.no_device =
  block_device_mappings.3850042718.virtual_name = ephemeral1
  creation_date = 2014-07-23T18:05:49.000Z
  hypervisor = xen
  image_id = ami-e7b8c0d7
  image_location = 099720109477/ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20140607.1
  image_type = machine
  most_recent = true
  name = ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20140607.1
  name_regex = ^ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-\d+
  owner_id = 099720109477
  owners.# = 1
  owners.0 = 099720109477
  product_codes.# = 0
  public = true
  root_device_name = /dev/sda1
  root_device_type = ebs
  sriov_net_support = simple
  state = available
  state_reason.% = 2
  state_reason.code = UNSET
  state_reason.message = UNSET
  tags.# = 0
  virtualization_type = hvm
```

Hope this helps

Paul

**Comment by kwilczynski** [comment]
@kojiromike hi there!

Thank you @stack72, but it is a team effort!

@kojiromike if I may, I would suggest a different approach. Instead of using the `name_regex` regular expression to match the desired image, I would recommend using the `filter` block together with `name` attribute, which accepts wildcard searches, and together with `most_recent` set to `true` you might achieve an overall speed-up in the lookup, as the heavy lifting is being offset against AWS' back-end in this case, rather than walking the list of images to find a match.

For example:

(using `name_regex`)

$ time ./terraform apply &>/dev/null

real	0m12.466s
user	0m2.133s
sys	0m0.228s

(using `filter` together with `name` attribute)

$ time ./terraform apply &>/dev/null

real	0m8.496s
user	0m0.267s
sys	0m0.154s

The filter block might look like the following:

```
  filter {
    name = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }
```

Hope this helps.
