### ISSUE TITLE
Crash on syntax check using aws_eip

### ISSUE THREAD

**Issue by vfabrizi** [hashicorp/terraform#9682]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.7.7

#### Code
```
resource "aws_launch_configuration" "bastion" {
  image_id                    = "${var.ami}"
  instance_type               = "${var.instance_type}"
  associate_public_ip_address = "${aws_eip.bastion.id}"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_eip" "bastion" {
  vpc = true
}
```

### Affected Resource(s)
aws_launch_configuration, aws_eip

[crash.zip](https://github.com/hashicorp/terraform/files/558146/crash.zip)

### Expected Behavior
I understand the correct value for the associate_public_ip_address property should be [true|false], still the parser fail to manage the unexpected value.

### Actual Behavior
Terraform crash while checking the syntax of the tf files

### Steps to Reproduce
1. `terraform apply`

**Comment by kwilczynski** [comment]
@vfabrizi hi there! I am sorry are having issues with Terraform!

**Comment by kwilczynski** [comment]
Relevant part of the crash log:

```
28 11:28:48 [DEBUG] plugin: terraform: panic: Error reading level config: strconv.ParseBool: parsing "${aws_eip.bastion.id}": invalid syntax
2016/10/28 11:28:48 [DEBUG] plugin: terraform: 
2016/10/28 11:28:48 [DEBUG] plugin: terraform: goroutine 120 [running]:
2016/10/28 11:28:48 [DEBUG] plugin: terraform: panic(0x2447960, 0xc420451650)
2016/10/28 11:28:48 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/panic.go:500 +0x1a1
2016/10/28 11:28:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc420802060, 0xc420451570, 0x1, 0x1, 0xc420451512, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/10/28 11:28:48 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:443 +0x31d
2016/10/28 11:28:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc420802060, 0x2ae3154, 0x1b, 0x11201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/10/28 11:28:48 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:414 +0x13d
2016/10/28 11:28:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc420802060, 0x2ae3154, 0x1b, 0xc41ffded45, 0xc4207834f8, 0x19b4e, 0xc420425740, 0x30)
2016/10/28 11:28:48 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:391 +0x61
2016/10/28 11:28:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.diffString(0xc4204279e0, 0x2ae3154, 0x1b, 0xc4207185a0, 0xc420783630, 0xc420802060, 0x2ca3300, 0x0, 0x0)
2016/10/28 11:28:48 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:998 +0xb5
2016/10/28 11:28:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc4204279e0, 0x2ae3154, 0x1b, 0xc4207185a0, 0xc4205a6a80, 0xc420802060, 0xc420326900, 0x0, 0x0)
2016/10/28 11:28:48 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:635 +0x122
2016/10/28 11:28:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc4204279e0, 0xc420659450, 0xc4204252c0, 0xc42065b8b8, 0xc420470be0, 0x0)
2016/10/28 11:28:48 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:354 +0x1d6
2016/10/28 11:28:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc420706ba0, 0xc420659450, 0xc4204252c0, 0x18, 0xc420470c70, 0xc420424601)
2016/10/28 11:28:48 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:179 +0x42
2016/10/28 11:28:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc4203b6360, 0xc42000bf00, 0xc420659450, 0xc4204252c0, 0x0, 0x18, 0x18)
2016/10/28 11:28:48 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:191 +0x84
2016/10/28 11:28:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Diff(0xc420687fc0, 0xc4205a6900, 0xc420450fb0, 0x0, 0x0)
2016/10/28 11:28:48 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:471 +0x57
2016/10/28 11:28:48 [DEBUG] plugin: terraform: reflect.Value.call(0xc420449c20, 0xc4200804d0, 0x13, 0x2a8503f, 0x4, 0xc420783ed0, 0x3, 0x3, 0x411dde0, 0xc4201c6480, ...)
2016/10/28 11:28:48 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:434 +0x5c8
2016/10/28 11:28:48 [DEBUG] plugin: terraform: reflect.Value.Call(0xc420449c20, 0xc4200804d0, 0x13, 0xc420783ed0, 0x3, 0x3, 0x1, 0xc4202f95c0, 0xc4202f9560)
2016/10/28 11:28:48 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:302 +0xa4
2016/10/28 11:28:48 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc42047d700, 0xc42047d680, 0xc4206680d8, 0xc420606200, 0xc420678060, 0x2222f40, 0xc4205a6900, 0x16, 0x2222f80, 0xc420450fb0, ...)
2016/10/28 11:28:48 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:383 +0x148
2016/10/28 11:28:48 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2016/10/28 11:28:48 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:477 +0x421
```

**Comment by jbardin** [comment]
Hi,

Thanks for the crash output! I'm tracking this issue with #7715.
