### ISSUE TITLE
crash segmentation violation

### ISSUE THREAD

**Issue by dcharbonnier** [hashicorp/terraform#9798]
### Terraform Version
0.7.8 (docker image hashicorp/terraform:0.7.8)

### Affected Resource(s)
null_resource

### Panic Output
```
module.minio.null_resource.bootstrap: Provisioning with 'file'...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4f2af4]

goroutine 1484 [running]:
panic(0x29e4da0, 0xc420010040)
	/opt/go/src/runtime/panic.go:500 +0x1a1
github.com/hashicorp/terraform/terraform.(*EvalApplyProvisioners).apply(0xc4209633b0, 0x471e9a0, 0xc42005c1a0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_apply.go:278 +0x5b4
github.com/hashicorp/terraform/terraform.(*EvalApplyProvisioners).Eval(0xc4209633b0, 0x471e9a0, 0xc42005c1a0, 0x2, 0x2, 0xc420bcd410, 0xa)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_apply.go:179 +0x151
github.com/hashicorp/terraform/terraform.EvalRaw(0x4704480, 0xc4209633b0, 0x471e9a0, 0xc42005c1a0, 0x2d89940, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x17f
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc42045ae20, 0x471e9a0, 0xc42005c1a0, 0x2, 0x2, 0xc4207b5100, 0xa)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:10 +0x6c
github.com/hashicorp/terraform/terraform.EvalRaw(0x4704d80, 0xc42045ae20, 0x471e9a0, 0xc42005c1a0, 0x4704d80, 0xc42045ae20, 0xc4209634a0, 0x25)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x17f
github.com/hashicorp/terraform/terraform.Eval(0x4704d80, 0xc42045ae20, 0x471e9a0, 0xc42005c1a0, 0xc42045ae20, 0x4704d80, 0xc42045ae20, 0xc420565746)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:34 +0x53
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2e94ba0, 0xc4205ce230, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:249 +0xa0f
github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk.func3(0xc4208788a0, 0xc42032a380, 0xc4208780a8, 0xc4201ce630, 0xc4208788d0, 0x2e94ba0, 0xc4205ce230, 0xc42042cf60, 0xc42042df20)
	/opt/gopath/src/github.com/hashicorp/terraform/dag/dag.go:238 +0x251
created by github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk
	/opt/gopath/src/github.com/hashicorp/terraform/dag/dag.go:247 +0x618

```

Providing the full log and the config files on github is not possible but feel free to contact me.

**Comment by dcharbonnier** [comment]
same config work with 0.7.7

**Comment by kwilczynski** [comment]
@dcharbonnier hi there! I am sorry you are having issues.

I am also afraid, that without the template example that would allow us to reproduce the problem, it is going to be very hard to deduce what the underlying issue is, I am sorry to say.

**Comment by dcharbonnier** [comment]
no problem

**Comment by dcharbonnier** [comment]
#9840
