### ISSUE TITLE
NPE at Terraform v0.7.8

### ISSUE THREAD

**Issue by akranga** [hashicorp/terraform#9870]
NPE at Terraform v0.7.8 see details below:
```
module.hook.aws_autoscaling_lifecycle_hook.launching: Creation complete
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf1f24]

goroutine 1793 [running]:
panic(0x25e3540, 0xc4200100e0)
	/opt/go/src/runtime/panic.go:500 +0x1a1
github.com/hashicorp/terraform/terraform.(*EvalApplyProvisioners).apply(0xc421041020, 0x431cc20, 0xc4214349c0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_apply.go:278 +0x5b4
github.com/hashicorp/terraform/terraform.(*EvalApplyProvisioners).Eval(0xc421041020, 0x431cc20, 0xc4214349c0, 0x2, 0x2, 0xc4217924e0, 0xa)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_apply.go:179 +0x151
github.com/hashicorp/terraform/terraform.EvalRaw(0x4302480, 0xc421041020, 0x431cc20, 0xc4214349c0, 0x29882a0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x17f
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc42111f1c0, 0x431cc20, 0xc4214349c0, 0x2, 0x2, 0xc4215d8de0, 0xa)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:10 +0x6c
github.com/hashicorp/terraform/terraform.EvalRaw(0x4302d80, 0xc42111f1c0, 0x431cc20, 0xc4214349c0, 0x4302d80, 0xc42111f1c0, 0xc42111f280, 0x1f)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x17f
github.com/hashicorp/terraform/terraform.Eval(0x4302d80, 0xc42111f1c0, 0x431cc20, 0xc4214349c0, 0xc42111f1c0, 0x4302d80, 0xc42111f1c0, 0xc41ff68a87)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:34 +0x53
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2a939e0, 0xc42049e150, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:249 +0xa0f
github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk.func3(0xc421340620, 0xc4214ba140, 0xc4213403c8, 0xc420d628a0, 0xc421340630, 0x2a939e0, 0xc42049e150, 0xc421121020, 0xc4211a4360)
	/opt/gopath/src/github.com/hashicorp/terraform/dag/dag.go:238 +0x251
created by github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk
	/opt/gopath/src/github.com/hashicorp/terraform/dag/dag.go:247 +0x618
```

`0.7.9-dev` seems to be okay

**Comment by marcinzaremba** [comment]
Look at #9840, it's been fixed already by @mitchellh

**Comment by apparentlymart** [comment]
Thanks for reporting this, @akranga!

It does indeed look like this is the same as #9840, so I'm going to close this.
