### ISSUE TITLE
panic: aws_acm_certificate

### ISSUE THREAD

**Issue by ligustah** [hashicorp/terraform#9989]
### Terraform Version
v0.7.9

### Affected Resource(s)
- aws_acm_certificate

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "eu-central-1"
}

// the example used here: https://www.terraform.io/docs/providers/aws/d/acm_certificate.html
data "aws_acm_certificate" "example" {
  domain = "tf.example.com"
  statuses = ["ISSUED"]
}
```

### Panic Output
https://gist.github.com/ligustah/fd63a16e80052ec3fff1a43a9377f6f7

### Expected Behavior
It should not panic

### Actual Behavior
It panicked

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
It doesn't appear to require valid AWS credentials, as it crashes before contacting the API.

**Comment by kwilczynski** [comment]
@ligustah hi there! Sorry that you have had a bad experience with this resource!

We will look into resolving the problem as soon as possible.

**Comment by devinsba** [comment]
Still seeing this behavior on a version built from master after #9990 was merged in

**Comment by stack72** [comment]
Hi @devinsba 

How did you build from master?

P.

**Comment by devinsba** [comment]
`XC_OS=darwin XC_ARCH=amd64 make bin`

**Comment by stack72** [comment]
Hi @devinsba 

Very weird - can you tell me if the same issue happens in 0.7.10 (just released yesterday) - I am not seeing the issue any more

P.

**Comment by stack72** [comment]
```
% envchain aws.hce-packages terraform plan                                                                                                                                                            
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

data.aws_acm_certificate.example: Refreshing state...

No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.

[stacko@Pauls-MacBook-Pro:~/Code/engineering-services-org/engservices-teamcity on master]
% envchain aws.hce-packages terraform apply                                                                                                                                                               
data.aws_acm_certificate.example: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

[stacko@Pauls-MacBook-Pro:~/Code/engineering-services-org/engservices-teamcity on master]
% envchain aws.hce-packages terraform destroy                                                                                                                                                             
Do you really want to destroy?
  Terraform will delete all your managed infrastructure.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

data.aws_acm_certificate.example: Refreshing state...

Destroy complete! Resources: 0 destroyed.
```

**Comment by devinsba** [comment]
```
provider "aws" {
  region = "us-east-1"
}

data "aws_acm_certificate" "artifactory" {
  domain = "artifactory.example.com"
  statuses = ["ISSUED"]
}

output "ssl_cert_arn" {
  value = "${data.aws_acm_certificate.artifactory.arn}"
}
```

```
terraform version && terraform plan
Terraform v0.7.10

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

data.aws_acm_certificate.artifactory: Refreshing state...
Error refreshing state: 1 error(s) occurred:

* data.aws_acm_certificate.artifactory: unexpected EOF
panic: interface conversion: interface is []interface {}, not []string
2016/11/10 09:16:14 [DEBUG] plugin: terraform:
2016/11/10 09:16:14 [DEBUG] plugin: terraform: goroutine 116 [running]:
2016/11/10 09:16:14 [DEBUG] plugin: terraform: panic(0x2698420, 0x4250a89c0)
2016/11/10 09:16:14 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/panic.go:500 +0x1a1
2016/11/10 09:16:14 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/aws.dataSourceAwsAcmCertificateRead(0x42548f2c0, 0x2362200, 0x4253c4340, 0x2b00000000000028, 0x0)
2016/11/10 09:16:14 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/data_source_aws_acm_certificate.go:69 +0x6e6
2016/11/10 09:16:14 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0x42514e600, 0x425007460, 0x2362200, 0x4253c4340, 0x42517b3a8, 0x1, 0x0)
2016/11/10 09:16:14 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:207 +0xda
2016/11/10 09:16:14 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0x4254919e0, 0x4253a2000, 0x425007460, 0x0, 0x18, 0x18)
2016/11/10 09:16:14 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:317 +0x91
2016/11/10 09:16:14 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ReadDataApply(0x425146060, 0x425152d60, 0x4251530a0, 0x0, 0x0)
2016/11/10 09:16:14 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:537 +0x4e
2016/11/10 09:16:14 [DEBUG] plugin: terraform: reflect.Value.call(0x4253696e0, 0x4254aa0f8, 0x13, 0x2bfa312, 0x4, 0x425193ed0, 0x3, 0x3, 0x4352fc0, 0x425375b80, ...)
2016/11/10 09:16:14 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:434 +0x5c8
2016/11/10 09:16:14 [DEBUG] plugin: terraform: reflect.Value.Call(0x4253696e0, 0x4254aa0f8, 0x13, 0x425193ed0, 0x3, 0x3, 0x0, 0x425211680, 0x425211620)
2016/11/10 09:16:14 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:302 +0xa4
2016/11/10 09:16:14 [DEBUG] plugin: terraform: net/rpc.(*service).call(0x424ef3e80, 0x424ef3bc0, 0x424efb770, 0x4250b6300, 0x425146100, 0x2364340, 0x425152d60, 0x16, 0x2364380, 0x4251530a0, ...)
2016/11/10 09:16:14 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:383 +0x148
2016/11/10 09:16:14 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2016/11/10 09:16:14 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:477 +0x421
2016/11/10 09:16:14 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.aws_acm_certificate.artifactory: unexpected EOF
2016/11/10 09:16:14 [ERROR] root: eval: *terraform.EvalSequence, err: data.aws_acm_certificate.artifactory: unexpected EOF
2016/11/10 09:16:14 [ERROR] root: eval: *terraform.EvalOpFilter, err: data.aws_acm_certificate.artifactory: unexpected EOF
2016/11/10 09:16:14 [ERROR] root: eval: *terraform.EvalSequence, err: data.aws_acm_certificate.artifactory: unexpected EOF
2016/11/10 09:16:14 [TRACE] [walkRefresh] Exiting eval tree: data.aws_acm_certificate.artifactory
2016/11/10 09:16:14 [DEBUG] plugin: /Users/ddcbdevins/bin/terraform: plugin process exited
2016/11/10 09:16:14 [DEBUG] vertex "output.ssl_cert_arn", got dep: "data.aws_acm_certificate.artifactory"
2016/11/10 09:16:14 [DEBUG] vertex "root", got dep: "output.ssl_cert_arn"
2016/11/10 09:16:14 [DEBUG] vertex "provider.aws (close)", got dep: "data.aws_acm_certificate.artifactory"
2016/11/10 09:16:14 [DEBUG] vertex "root", got dep: "provider.aws (close)"
2016/11/10 09:16:14 [INFO] Starting shadow graph walk: walkRefresh
2016/11/10 09:16:14 [DEBUG] Waiting for shadow graph to complete...
2016/11/10 09:16:14 [DEBUG] vertex 'root.provider.aws': walking
2016/11/10 09:16:14 [DEBUG] vertex 'root.provider.aws': evaluating
2016/11/10 09:16:14 [TRACE] [walkRefresh] Entering eval tree: provider.aws
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalSequence
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalInitProvider
2016/11/10 09:16:14 [DEBUG] root: eval: terraform.EvalNoop
2016/11/10 09:16:14 [DEBUG] root: eval: terraform.EvalNoop
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalOpFilter
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalSequence
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalGetProvider
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalInterpolate
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalBuildProviderConfig
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalSetProviderConfig
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalOpFilter
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalSequence
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalConfigProvider
2016/11/10 09:16:14 [TRACE] [walkRefresh] Exiting eval tree: provider.aws
2016/11/10 09:16:14 [DEBUG] vertex "data.aws_acm_certificate.artifactory", got dep: "provider.aws"
2016/11/10 09:16:14 [DEBUG] vertex "provider.aws (close)", got dep: "provider.aws"
2016/11/10 09:16:14 [DEBUG] vertex 'root.data.aws_acm_certificate.artifactory': walking
2016/11/10 09:16:14 [DEBUG] vertex 'root.data.aws_acm_certificate.artifactory': evaluating
2016/11/10 09:16:14 [TRACE] [walkRefresh] Entering eval tree: data.aws_acm_certificate.artifactory
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalSequence
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalInterpolate
2016/11/10 09:16:14 [DEBUG] root: eval: terraform.EvalNoop
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalCountFixZeroOneBoundary
2016/11/10 09:16:14 [TRACE] [walkRefresh] Exiting eval tree: data.aws_acm_certificate.artifactory
2016/11/10 09:16:14 [DEBUG] vertex 'root.data.aws_acm_certificate.artifactory': expanding/walking dynamic subgraph
2016/11/10 09:16:14 [TRACE] Graph after step *terraform.ResourceCountTransformerOld:

data.aws_acm_certificate.artifactory - *terraform.graphNodeExpandedResource
2016/11/10 09:16:14 [TRACE] Graph after step *terraform.TargetsTransformer:

data.aws_acm_certificate.artifactory - *terraform.graphNodeExpandedResource
2016/11/10 09:16:14 [TRACE] Graph after step *terraform.RootTransformer:

data.aws_acm_certificate.artifactory - *terraform.graphNodeExpandedResource
2016/11/10 09:16:14 [DEBUG] vertex 'root.data.aws_acm_certificate.artifactory': walking
2016/11/10 09:16:14 [DEBUG] vertex 'root.data.aws_acm_certificate.artifactory': evaluating
2016/11/10 09:16:14 [TRACE] [walkRefresh] Entering eval tree: data.aws_acm_certificate.artifactory
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalSequence
2016/11/10 09:16:14 [DEBUG] root: eval: terraform.EvalNoop
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalInstanceInfo
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalOpFilter
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalSequence
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalWriteState
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalInterpolate
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalIf
2016/11/10 09:16:14 [DEBUG] root: eval: terraform.EvalNoop
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalGetProvider
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalReadDataDiff
2016/11/10 09:16:14 [DEBUG] root: eval: *terraform.EvalReadDataApply
2016/11/10 09:16:14 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.aws_acm_certificate.artifactory: unexpected EOF
2016/11/10 09:16:14 [ERROR] root: eval: *terraform.EvalSequence, err: data.aws_acm_certificate.artifactory: unexpected EOF
2016/11/10 09:16:14 [ERROR] root: eval: *terraform.EvalOpFilter, err: data.aws_acm_certificate.artifactory: unexpected EOF
2016/11/10 09:16:14 [ERROR] root: eval: *terraform.EvalSequence, err: data.aws_acm_certificate.artifactory: unexpected EOF
2016/11/10 09:16:14 [TRACE] [walkRefresh] Exiting eval tree: data.aws_acm_certificate.artifactory
2016/11/10 09:16:14 [DEBUG] vertex "output.ssl_cert_arn", got dep: "data.aws_acm_certificate.artifactory"
2016/11/10 09:16:14 [DEBUG] vertex "root", got dep: "output.ssl_cert_arn"
2016/11/10 09:16:14 [DEBUG] vertex "provider.aws (close)", got dep: "data.aws_acm_certificate.artifactory"
2016/11/10 09:16:14 [DEBUG] vertex "root", got dep: "provider.aws (close)"
2016/11/10 09:16:14 [ERROR] Shadow graph error: 1 error(s) occurred:

* data.aws_acm_certificate.artifactory: unexpected EOF
2016/11/10 09:16:14 [DEBUG] plugin: waiting for all plugin processes to complete...



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by stack72** [comment]
@devinsba fantastic - was able to recreate it when i was able to see what style of config you were using - will get a fix in a PR today :)

**Comment by lattwood** [comment]
@stack72 thanks! just hit this
